### ISSUE TITLE
CI is broken due to missing libfxr

### ISSUE THREAD

**Issue by karajas** [dotnet/source-build#100]
/cc @crummel @dleeapho 

This seems to be due to the missing libhost*.so files that reproed locally also. Jenkins CI looks for strings that match error messages.

**Comment by karajas** [comment]
Updating title to reflect missing file.

**Comment by karajas** [comment]
Think I have a fix, it seems to be a pathing issue. Testing now,

**Comment by karajas** [comment]
This is due to the csproj not publishing the fixed version assets of the host and hostresolver for the specific rid.
After trying to fix the publish step without building, i am exploring the option of trying to reuse depproj's instead.

**Comment by stevedesmond-ca** [comment]
Should this be resolved now that #128 is merged?

**Comment by karajas** [comment]
Yup this error should be resolved with that pr
