### ISSUE TITLE
[Branch release/3.0] buildbootstrapcli.sh failed on Linux

### ISSUE THREAD

**Issue by KexyBiscuit** [dotnet/source-build#1025]
```shell
./buildbootstrapcli.sh -rid aosc.5-x64 -os Linux -seedcli ~/dotnet
```

```
**** Copying new binaries to dotnetcli/ ****
cp: cannot stat 'core-setup/cli/exe/dotnet/dotnet': No such file or directory
```

79c6f03

**Comment by dseefeld** [comment]
Can you provide more information about your environment and what you're trying to do?

**Comment by omajid** [comment]
I was running into this issue too. It's a change in core-setup's build paths in 3.x versions.

https://github.com/dotnet/source-build/pull/1145 fixed it for me.

**Comment by KexyBiscuit** [comment]
@dseefeld I'm trying to build .NET Core for a new distro.

**Comment by s0dy** [comment]
@dseefeld I also have the same problem, I tried with:

- dotnet/source-build release/2.2 and dotnet-sdk-2.2.108-linux-x64.tar.gz
- dotnet/source-build release/3.0 and dotnet-sdk-3.0.100-preview7-012821-linux-x64.tar.gz

```
./buildbootstrapcli.sh -rid exherbo-x64 -os linux -seedcli ~/seed-cli
```
```
CoreFX binaries will be copied from /home/s0dy/source-build/scripts/bootstrap/exherbo-x64/corefx/artifacts/obj/native/Linux-x64-Release
**** Copying new binaries to dotnetcli/ ****
cp: cannot stat 'core-setup/bin/exherbo-x64.release/corehost/dotnet': No such file or directory
```


@omajid I also did not succeed with your changes #1145

**Comment by omajid** [comment]
@s0dy What error did you get with my patch? It should have worked around the `cp: cannot stat...` error. Did you run into another issue?

**Comment by s0dy** [comment]
@omajid I still have the same error message "**cp: cannot stat...**"

I may not have done the right way? I replaced the default script with [your modified version](https://raw.githubusercontent.com/dotnet/source-build/75ee842f05db144a949e991673f798773f455294/scripts/bootstrap/buildbootstrapcli.sh)

**Comment by omajid** [comment]
@s0dy Huh. That should have worked. Do you have the first few lines of output from the bootstrap script? I am looking for these pieces:

    Framework version: 
    SDK version:
    FXR version:

**Comment by s0dy** [comment]
```
Framework version: 3.0.0-preview7-27912-14
SDK version:       3.0.100-preview7-012821
FXR version:       3.0.0-preview7-27912-14
```

**Comment by dseefeld** [comment]
Let's get https://github.com/dotnet/source-build/pull/1145 merged and then see where this is at.

**Comment by s0dy** [comment]
It does not work for me with the #1145

```
cp: cannot stat 'core-setup/bin/exherbo-x64.release/corehost/dotnet': No such file or directory
```


```
s0dy@thinkpad ../scripts/bootstrap (release/3.0) ls -l exherbo-x64/core-setup/bin

drwxr-xr-x - s0dy s0dy 08-30 12:23 exherbo.-x64.release/
drwxr-xr-x - s0dy s0dy 08-30 12:20 obj/
```

The name of the folder is not good, it contains a dot after the name of the distribution

**Comment by s0dy** [comment]
```
s0dy@thinkpad ../core-setup/bin ((HEAD detached at 4da6ee64)) mv exherbo.-x64.release exherbo-x64.release
```

After renaming the folder, the script ends well

```
./buildbootstrapcli.sh -rid exherbo-x64 -os Linux -seedcli ~/seed-cli
...
...
**** Bootstrap CLI was successfully built  ****

**Comment by omajid** [comment]
I guess this may really be a bug in core-setup if it produces output directory with an RID (`exherbo.-x64`) that contains a dot without the version after it. But I suspect we have no choice but to accommodate this in the bootstrap script.

**Comment by omajid** [comment]
@dseefeld do you want me to modify https://github.com/dotnet/source-build/pull/1145 right now or wait for that to be merged and then handle this case as a separate PR?

**Comment by dseefeld** [comment]
Let's get #1145 merged.  I'll try to get that done today.  I noticed that there was a restore source failure on one leg that needed to be restarted.  I restarted it and will merge when that completes.

**Comment by MichaelSimons** [comment]
[Triage] Closing as obsolete - `buildbootstrapcli.sh` no longer exists.
