### ISSUE TITLE
ROOTFS_DIR always set on armel.

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/source-build#1037]
For `arm`, if `ArmEnvironmentVariables` is set, the `ROOTFS_DIR` won't explicitly be set by the build. However, on armel, this unconditionally happens. Instead the checks should check for ArmEnvironmentVairables, and if not set then decide to set for armel and arm

https://github.com/dotnet/source-build/blob/release/3.0/dir.props#L123

**Comment by dseefeld** [comment]
arm is not officially supported yet, but if you have changes for this, please submit a PR.

**Comment by dseefeld** [comment]
If you have changes.  If you want to submit a PR, feel free to reopen.
