### ISSUE TITLE
Update coreclr to 3.0 SDK in preview6

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1052]
When source-build is updated to preview6, coreclr should be changed to build with 3.0 SDK.  Here's the coreclr commit that updates to 3.0:

https://github.com/dotnet/coreclr/commit/5894a0f4ecd7360dc25b1e01afb0120efceb7a11#diff-274660eb4b1b1d963a330b471e10f41c

**Comment by crummel** [comment]
Included in https://github.com/dotnet/source-build/pull/1141.

**Comment by dseefeld** [comment]
Done.
