### ISSUE TITLE
Update linker repo to use source-built version of Microsoft.Build.Framework

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1053]
The linker repo has the following prebuilt.  This should be resolved by using the source-build version.

Microsoft.Build.Framework | 15.1.1012
-- | --

**Comment by nguerrera** [comment]
I'm not sure that the linker needs to use the source-built version. It doesn't need to redist these. I think there should be an LKG reference-only version of MSBuild. cc @sbomer

I don't want to end up with unnecessary edges in the DARC flow by over-flowing everything.

**Comment by dseefeld** [comment]
Added to list of reference-only packages for source-build.
