### ISSUE TITLE
[Coreclr] Add skipgenerateversion to the BuildArguments in coreclr.proj

### ISSUE THREAD

**Issue by jashook** [dotnet/source-build#1057]
This is to address: https://github.com/dotnet/coreclr/issues/24888#issuecomment-498424284. Note that corefx is avoiding this problem with the following msbuild argument in source build: https://github.com/dotnet/source-build/blob/release/3.0/repos/corefx.proj#L28. Coreclr does not have a redefinition of the target, and simply needs `skipgenerateversion` to be passed to build.sh

**Comment by jashook** [comment]
Note this is required now that coreclr builds on arcade.

**Comment by dseefeld** [comment]
Fixed in #1141
