### ISSUE TITLE
Build fails on Fedora 26

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#106]
Build (`./build.sh`) fails when applying a patch:

    "/home/omajid/devel/dotnet/source-build/build.proj" (default target) (1) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2:3) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2:6) ->
    (Build target) ->
      /home/omajid/devel/dotnet/source-build/src/corefx/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/omajid/devel/dotnet/so
    urce-build/src/corefx/external/ilasm/ilasm.depproj] [/home/omajid/devel/dotnet/source-build/targets/repository.proj]
      /home/omajid/devel/dotnet/source-build/src/corefx/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/home/omajid/devel/dotnet/so
    urce-build/src/corefx/external/ilasm/ilasm.depproj] [/home/omajid/devel/dotnet/source-build/targets/repository.proj]
      /home/omajid/devel/dotnet/source-build/targets/repository.proj(75,5): error MSB3073: The command "/home/omajid/devel/dotnet/source-build/src/corefx/build.sh -Release -
    buildArch=x64 -portable=false -- /p:ILLinkTrimAssembly=false" exited with code 1.

    "/home/omajid/devel/dotnet/source-build/build.proj" (default target) (1) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2:10) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2:12) ->
    (ApplyPatches target) ->
      /home/omajid/devel/dotnet/source-build/targets/repository.proj(49,5): error MSB3073: The command "patch -p1 --binary --ignore-whitespace -i /home/omajid/devel/dotnet/$ource-build/patches/nuget-client/0001-Revert-38949ce93081016167dfd8e37e4e897bedf47d65-DOS-.patch" exited with code 1.

    "/home/omajid/devel/dotnet/source-build/build.proj" (default target) (1) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2:38) ->
    (Build target) ->
      /home/omajid/devel/dotnet/source-build/Tools/dotnetcli/sdk/2.0.0-preview3-006845/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(141,5)$ error : The file '/home/omajid/devel/dotnet/source-build/src/xliff-tasks/bin/Release/XliffTasks/netcoreapp1.1/XliffTasks.dll' to be packed was not found on disk. [/hom$/omajid/devel/dotnet/source-build/src/xliff-tasks/src/XliffTasks/XliffTasks.csproj] [/home/omajid/devel/dotnet/source-build/targets/repository.proj]
      /home/omajid/devel/dotnet/source-build/Tools/dotnetcli/sdk/2.0.0-preview3-006845/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(141,5)$ error : The file '/home/omajid/devel/dotnet/source-build/src/xliff-tasks/bin/Release/XliffTasks/netcoreapp1.1/XliffTasks.dll' to be packed was not found on disk. [/hom$/omajid/devel/dotnet/source-build/src/xliff-tasks/src/XliffTasks/XliffTasks.csproj] [/home/omajid/devel/dotnet/source-build/targets/repository.proj]
      /home/omajid/devel/dotnet/source-build/targets/xliff-tasks.targets(8,5): error MSB3073: The command "/home/omajid/devel/dotnet/source-build/Tools/dotnetcli/dotnet bui$d /home/omajid/devel/dotnet/source-build/src/xliff-tasks/build/build.proj /t:Pack /v:normal /flp:Verbosity=Diag;LogFile=/home/omajid/devel/dotnet/source-build/src/xliff$tasks/msbuild.log" exited with code -1. [/home/omajid/devel/dotnet/source-build/targets/repository.proj]

This is on Fedora 26:

    $ cat /etc/os-release 
    NAME=Fedora
    VERSION="26 (Workstation Edition)"
    ID=fedora
    VERSION_ID=26
    PRETTY_NAME="Fedora 26 (Workstation Edition)"
    ANSI_COLOR="0;34"
    CPE_NAME="cpe:/o:fedoraproject:fedora:26"
    HOME_URL="https://fedoraproject.org/"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="Fedora"
    REDHAT_BUGZILLA_PRODUCT_VERSION=26
    REDHAT_SUPPORT_PRODUCT="Fedora"
    REDHAT_SUPPORT_PRODUCT_VERSION=26
    PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
    VARIANT="Workstation Edition"
    VARIANT_ID=workstation
    $ uname -a
    Linux trull 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Reverting https://github.com/dotnet/source-build/pull/103 did not help.

**Comment by omajid** [comment]
After deleting that clone, I did a fresh clone today:

    $ rm -rf ~/.nuget ~/.dotnet/ ~/.nuget/ ~/.local/share/NuGet ~/.templateengine /tmp/NuGet/
    $ rm -rf /tmp/NuGet /tmp/NuGetScratch /tmp/.NETCore* /tmp/.NETStandard*
    $ git clone --recursive git@github.com:dotnet/source-build
    $ cd source-build
    $ git rev-parse HEAD
    1b1fbed07487d0c864ee0fc4d34c47e5a9c56935
    $ ./build.sh
    ... lots of output truncated ...
    
    "/home/omajid/devel/dotnet/source-build/build.proj" (default target) (1) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2:3) ->
    "/home/omajid/devel/dotnet/source-build/targets/repository.proj" (BuildRepositoryAndDependencies target) (2:6) ->
    (Build target) ->
      /home/omajid/devel/dotnet/source-build/src/corefx/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet pa
    ckages. [/home/omajid/devel/dotnet/source-build/src/corefx/external/ilasm/ilasm.depproj] [/home/omajid/devel/dotnet/source-build/tar
    gets/repository.proj]
      /home/omajid/devel/dotnet/source-build/src/corefx/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet pa
    ckages. [/home/omajid/devel/dotnet/source-build/src/corefx/external/ilasm/ilasm.depproj] [/home/omajid/devel/dotnet/source-build/tar
    gets/repository.proj]
      /home/omajid/devel/dotnet/source-build/targets/repository.proj(74,5): error MSB3073: The command "/home/omajid/devel/dotnet/source
    -build/src/corefx/build.sh -Release -buildArch=x64 -portable=false -- /p:ILLinkTrimAssembly=false" exited with code 1.

        563 Warning(s)
        3 Error(s)

    Time Elapsed 00:17:20.40

**Comment by omajid** [comment]
I had to make this change for `source-build` to work on F26. I dont know the significance of these versions. Are the current versions a bug?

    --- a/patches/corefx/0005-Stabilize-CoreCLR-Dependencies.patch
    +++ b/patches/corefx/0005-Stabilize-CoreCLR-Dependencies.patch
    @@ -18,8 +18,11 @@ index b6a263f..1177b52 100644
      <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
        <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props" />
        <PropertyGroup>
    -@@ -15,10 +15,10 @@
    -       <Version>2.0.0-$(CoreFxExpectedPrerelease)</Version>
    +@@ -15,12 +15,12 @@
    +   <ItemGroup>
    +     <PackageReference Include="Microsoft.NETCore.Platforms">
    +-      <Version>2.0.0-$(CoreFxExpectedPrerelease)</Version>
    ++      <Version>2.0.0</Version>
          </PackageReference>
          <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR">
     -      <Version>2.0.0-$(CoreClrExpectedPrerelease)</Version>
    @@ -41,8 +44,12 @@ index 9b8bc36..431c6f2 100644
      <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
        <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props" />
        <PropertyGroup>
    -@@ -28,10 +28,10 @@
    -       <Version>2.0.0-$(CoreFxExpectedPrerelease)</Version>
    +@@ -28,13 +28,13 @@
    + 
    +   <ItemGroup Condition="'$(TargetGroup)'!='uapaot'">
    +     <PackageReference Include="Microsoft.NETCore.Platforms">
    +-      <Version>2.0.0-$(CoreFxExpectedPrerelease)</Version>
    ++      <Version>2.0.0</Version>
          </PackageReference>
          <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR">
     -      <Version>2.0.0-$(CoreClrExpectedPrerelease)</Version>

**Comment by weshaggard** [comment]
This issue was fixed in corefx release/2.0.0 branch with https://github.com/dotnet/corefx/commit/130fceb83c5c3f7e1920b18ca00936c0f6fc3e8c#diff-e3d63a38169eb4938ec2ee405f75b7e0. The version should match the version of the coreclr that was just built.
