### ISSUE TITLE
Package Microsoft.NETCore.App 3.0.0-preview4-27615-11 is not compatible with netcoreapp2.0

### ISSUE THREAD

**Issue by s0dy** [dotnet/source-build#1061]
I get this error when trying to compile dotnet on Exherbo linux (from the master).

`Restore completed in 205.77 ms for /home/s0dy/source-build/Tools/ilasm/ildasm.depproj.
/home/s0dy/source-build/Tools/dotnetcli/sdk/3.0.100-preview4-011223/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/home/s0dy/source-build/Tools/ilasm/ildasm.depproj]`

`Build succeeded.
    0 Warning(s)
    0 Error(s)`

`Time Elapsed 00:00:04.05
Making all .sh files executable under Tools.
/home/s0dy/source-build/Tools/crossgen/crossgen.csproj : error NU1202: Package Microsoft.NETCore.App 3.0.0-preview4-27615-11 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.NETCore.App 3.0.0-preview4-27615-11 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)
/home/s0dy/source-build/Tools/crossgen/crossgen.csproj : error NU1202: Package Microsoft.NETCore.App 3.0.0-preview4-27615-11 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / linux-x64. Package Microsoft.NETCore.App 3.0.0-preview4-27615-11 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)
Restore failed in 2.44 min for /home/s0dy/source-build/Tools/crossgen/crossgen.csproj.`

I also want to clarify that I modified the contents of the file DotnetCLIVersion.txt (I replaced 2.1.503 by 3.0.100-preview4-011223) to be able to compile with libssl-1.1 ([https://github.com/dotnet/coreclr/issues/24757](url)). I do not know if this has a relationship.

**Comment by omajid** [comment]
I wonder if `2.1.507` instead of `3.0.100-preview4-011223)` will work any better. Recent versions of 2.1 should support OpenSSl 1.1.

**Comment by s0dy** [comment]
Thank you @omajid, unfortunately I still can not do with `2.1.507`

`Time Elapsed 00:00:04.75
Making all .sh files executable under Tools.
  Restoring packages for /home/s0dy/source-build/Tools/crossgen/crossgen.csproj...
  Installing Microsoft.NETCore.App 2.2.0.
  Installing runtime.linux-x64.Microsoft.NETCore.App 2.2.0.`

`/home/s0dy/source-build/Tools/crossgen/crossgen.csproj : warning NU1603: crossgen depends on Microsoft.NETCore.App (>= 2.1.11) but Microsoft.NETCore.App 2.1.11 was not found. An approximate best match of Microsoft.NETCore.App 2.2.0 was resolved.`

`/home/s0dy/source-build/Tools/crossgen/crossgen.csproj : error NU1202: Package Microsoft.NETCore.App 2.2.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.NETCore.App 2.2.0 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)
/home/s0dy/source-build/Tools/crossgen/crossgen.csproj : error NU1202: Package Microsoft.NETCore.App 2.2.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / linux-x64. Package Microsoft.NETCore.App 2.2.0 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)`

` Generating MSBuild file /home/s0dy/source-build/Tools/crossgen/obj/crossgen.csproj.nuget.g.props.
  Generating MSBuild file /home/s0dy/source-build/Tools/crossgen/obj/crossgen.csproj.nuget.g.targets.
  Restore failed in 1.86 min for /home/s0dy/source-build/Tools/crossgen/crossgen.csproj.`

**Comment by dseefeld** [comment]
Does the latest 2.1 SDK unblock you?

**Comment by dseefeld** [comment]
Closed based on no response from OP.  Feel free to reopen if needed.
