### ISSUE TITLE
3.0 preview 6 release

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1072]

**Comment by omajid** [comment]
Is https://github.com/dotnet/source-build/commit/f00f8fef779a3a788866cc82eb2b6fee319e4d25 good to go? Could it be tagged as preview 6?

**Comment by crummel** [comment]
Sorry about that, yes, it's ready.  Tagged as [v3.0.100-preview6-012264-SDK](https://github.com/dotnet/source-build/releases/tag/v3.0.100-preview6-012264-SDK).

**Comment by omajid** [comment]
Thanks for tagging it!
