### ISSUE TITLE
Source-build patch removal for Roslyn

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1075]
CRummel responsibility due to no repo-owned patches.

Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/roslyn.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
roslyn/0001-Don-t-append-description-from-source-information-bec.patch | Build | Incorporate | source-build | This is an Arcade or SourceLink fix we need   to make to allow supplying repo info as a param or env var.
roslyn/0002-Add-repository-properties-for-new-SDK-warning.patch | ToolCompat | Remove | source-build |

**Comment by tmat** [comment]
These shouldn't be needed once we enable Source Link in source build.

**Comment by crummel** [comment]
Yes, I agree.  Closing this.
