### ISSUE TITLE
Source-build patch removal for xliff-tasks

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1076]
Responsibility to @Crummel - no repo fixes.

Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/xliff-tasks.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
xliff-tasks/0001-Hardcode-version-until-we-fix-Arcade.patch | Build | SourceBuildFix | source-build | Should be fixable as part of daily build   work.  Possibly related to fix for   roslyn-0001.

**Comment by dseefeld** [comment]
Fixed in #1141
