### ISSUE TITLE
Exclude NuGet.Client tests from tarball

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#108]
There are a lot of NuGet.Client tests that get brought in via the nuget-client submodule. We should try to exclude these from the output source tarball. In addition to general economy, some of these have odd licenses that don't jibe with the source-build license. Example:

`src/nuget-client/submodules/NuGet.Services.Metadata/tests/AAD/NuGet.Test.WebSite/Scripts/jquery-1.10.2.intellisense.js
src/nuget-client/submodules/NuGet.Services.Metadata/tests/AAD/NuGet.Test.WebSite/Scripts/jquery.validate-vsdoc.js
src/nuget-client/submodules/NuGet.Services.Metadata/tests/AAD/NuGet.Test.WebSite/Scripts/jquery.validate.unobtrusive.js
src/nuget-client/submodules/NuGet.Services.Metadata/tests/AAD/NuGet.Test.WebSite/Scripts/jquery.validate.unobtrusive.min.js
src/nuget-client/submodules/NuGet.Services.Metadata/tests/AAD/NuGet.Test.WebSite/Scripts/modernizr-2.6.2.js
src/nuget-client/submodules/NuGet.Services.Metadata/tests/PublishTestDriverWebSite/Scripts/jquery.validate-vsdoc.js
src/nuget-client/submodules/NuGet.Services.Metadata/tests/PublishTestDriverWebSite/Scripts/jquery.validate.unobtrusive.js
src/nuget-client/submodules/NuGet.Services.Metadata/tests/PublishTestDriverWebSite/Scripts/jquery.validate.unobtrusive.min.js
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery-1.9.1.js
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery-1.9.1.min.js
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile-1.3.0.css
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile-1.3.0.js
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile-1.3.0.min.css
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile-1.3.0.min.js
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile.structure-1.3.0.css
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile.structure-1.3.0.min.css
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile.theme-1.3.0.css
src/nuget-client/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery.mobile.theme-1.3.0.min.css`

/cc @omajid

**Comment by omajid** [comment]
+1 on cleaning up code with bizarre licenses.

**Comment by mishra14** [comment]
This should have been fixed in https://github.com/NuGet/NuGet.Client/commit/3e5a0f4ed1e98244f8dd7204e8468460116ff559

**Comment by crummel** [comment]
We took the above NuGet.Client commit in https://github.com/dotnet/source-build/commit/420bf6fc0bf9a6963dbd72edff8f5bdb3a99ce45, so closing this now.

**Comment by dleeapho** [comment]
Thanks @mishra14 !
