### ISSUE TITLE
Add ASP.NET core end to end tests to source-build

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1081]
ASP.NET has a set of end-to-end tests that are used in 2.1/2.2.  When these test are ported to 3.0, they should also be used to validate source-build.

**Comment by JunTaoLuo** [comment]
With all the changes in how source build will be restructured, does this still need to be addressed?

**Comment by dagood** [comment]
The 5.0 work shouldn't change much for product testing. It may be a little easier to add repo tests to the source-build job in each repo vs. in this centralized repo. (But 5.0 plans also don't call for any additional product testing, as far as I'm aware.)

**Comment by JunTaoLuo** [comment]
If there's no need for additional product testing required, it sounds like this issue can be closed?

**Comment by dagood** [comment]
Maybe to clarify: source-build doesn't have any ASP.NET Core product testing currently, and needs it.

The 5.0 plans are unrelated (they do not add *or remove* any testing requirements), so this should still be tracked.

**Comment by MichaelSimons** [comment]
[Triage]  This is superseded by the [VMR work](https://github.com/dotnet/source-build/issues/2956)
