### ISSUE TITLE
Add reference packages for Microsoft.Extensions.DependencyModel

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1087]
The following package has been identified as reference-only packages. This should be added to the source-build-reference-packages repo:
- [ ] - Microsoft.Extensions.DependencyModel -    2.1.0-preview2-26306-03

Breakout from https://github.com/dotnet/source-build/issues/950

**Comment by dseefeld** [comment]
@dagood core-setup is the only repo referencing this prebuilt.  Is there any reason that this needs to be this specific preview2 version?  We're already building 2.1.0 as a reference package.

**Comment by dagood** [comment]
No, I've actually already updated to the stable 2.1.0 version in the arcade migration. Updated https://github.com/dotnet/core-setup/issues/7148 to cover this.

**Comment by dseefeld** [comment]
Great, thanks.  Closing this since no further action is necessary.
