### ISSUE TITLE
Add reference packages for NuGet.ProjectModel

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1090]
The following package has been identified as reference-only packages. This should be added to the source-build-reference-packages repo:
- [ ] - NuGet.ProjectModel -  ~~4.3.0-preview2-4095~~ 4.9.4

Breakout from https://github.com/dotnet/source-build/issues/950

**Comment by dagood** [comment]
@dseefeld Is Core-Setup the only potential user of this package? (I think so based on my reading of the prebuilt report dashboard, but not sure.)

The preview version means we're stuck with a MyGet feed, I would prefer switching to a stable version on the nuget gallery. Could we go with the latest with `net46` support, `4.9.4`?

**Comment by dseefeld** [comment]
@dagood  Yes core-setup is the only repo including this package.  Please update to what you need and I'll update this issue to the new version.

**Comment by dagood** [comment]
Great, changing to `4.9.4` then.

**Comment by dseefeld** [comment]
@dagood  Do you have an issue in core-setup that can be linked here so we can track this change?

**Comment by dagood** [comment]
Filed https://github.com/dotnet/core-setup/issues/7148 for that.

**Comment by dseefeld** [comment]
Closing as this is no longer reported as a prebuilt.
