### ISSUE TITLE
Modify restore source infrastructure to generate NuGet.config

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1099]
With the changes to arcade to remove RestoreSources and use NuGet.config instead (https://github.com/dotnet/arcade/pull/3041), source-build should modify its infrastructure code to generate a NuGet.config file to provide its restore sources to repos being built.

**Comment by crummel** [comment]
Taking this since it's part of https://github.com/dotnet/source-build/pull/1237.
