### ISSUE TITLE
Use 3.0 SDK as default and remove 2.x SDK if possible

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1129]
As from https://github.com/dotnet/source-build/pull/1124/files#r300042436, we should remove the workaround method for using a 3.0 SDK and switch to that as default.  Ideally, we should remove the 2.x SDK - we required both because of an SDK breaking change but everything using Arcade should be on 3.0 now.

**Comment by dseefeld** [comment]
Is part of PR #1188

**Comment by crummel** [comment]
https://github.com/dotnet/source-build/pull/1188 has been merged.
