### ISSUE TITLE
Don't generate the rootfs every time when cross-compiling

### ISSUE THREAD

**Issue by stevedesmond-ca** [dotnet/source-build#113]
Steps to reproduce:
1. `sudo ./build.sh /p:Platform=arm`
1. let it build all the way
1. `sudo ./build.sh /p:Platform=arm` again

Expected result:
- Not much should happen, since it just got build and nothing changed

Observed result:
- The rootfs is regenerated right off the bat, which takes a really long time and downloads an entire OS

We should add a condition to only generate the rootfs if it doesn't already exist.

**Comment by eerhardt** [comment]
@weshaggard is currently fixing this in https://github.com/dotnet/source-build/pull/158

**Comment by weshaggard** [comment]
Fixed by https://github.com/dotnet/source-build/pull/158
