### ISSUE TITLE
Analyze prebuilts for AspnetCore-Tooling

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1150]
The following prebuilt packages are included as dependencies in source-build by **AspNetCore-Tooling**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## Prebuilt Table Updated 2019-07-19

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
System.Reflection.Metadata | 1.7.0-preview7.19352.8 |

**Comment by JunTaoLuo** [comment]
For Microsoft.NET.Compilers.Toolset, we may be able to remove this at some point. The reason we had a dependency on this is that we needed a newer version of Roslyn in this repo than what's referenced by Arcade. I've spoken with the product owner @NTaylorMullen and it seems like once Arcade moves to preview 7 SDK, we should be able to remove this dependency.

As for the System.Reflection.Metadata, I see it referenced by Microsoft.NET.Sdk.Razor as a dependency for net46 only so I'm not sure why it's being flagged in source build. We should update the TFM of the project to be netcoreapp3.0 only so this dependency is not used.

**Comment by NTaylorMullen** [comment]
@ajaybhargavb @pranavkm is there any concerns with moving `Microsoft.NET.Sdk.Razor` to netcoreapp3.0?

**Comment by pranavkm** [comment]
> As for the System.Reflection.Metadata, I see it referenced by Microsoft.NET.Sdk.Razor as a dependency for net46 only so I'm not sure why it's being flagged in source build. We should update the TFM of the project to be netcoreapp3.0 only so this dependency is not used.

The project produces a tasks library. We have to cross-compile to continue supporting VS. We could consider bumping it up to `net472` to match .NET SDK: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj#L9, but we cannot stop cross-compiling.

**Comment by JunTaoLuo** [comment]
I believe the underlying issue has been addressed now that the package is built by corefx. Can we close this now?

**Comment by JunTaoLuo** [comment]
cc @dseefeld

**Comment by dseefeld** [comment]
We usually keep these open until there are no outstanding prebuilts.

**Comment by dseefeld** [comment]
All prebuilts removed.
