### ISSUE TITLE
source-build 3.0 Preview 7 versions out of sync?

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1158]
When I build 3.0 from source-build, I get:

- SDK version `3.0.100-preview7-012802`
- Runtime version `3.0.0-preview7-27902-19`

The Microsoft releases have a slightly different version:

- [3.0 Preivew 7 release notes](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview7.md) say that the SDK is version `3.0.100-preview7-012821`
- Microsoft.NETCore.App on nuget.org is version `3.0.0-preview7-27912-14`

Is this version discrepancy expected?

**Comment by crummel** [comment]
This should be fixed with #1159, I've tagged the new build as https://github.com/dotnet/source-build/releases/tag/v3.0.100-preview7-012821-SDK.  Let me know if you see any more issues.

**Comment by omajid** [comment]
Thanks! I can confirm this solves the new issues I was seeing. In my tests, we are back to essentially the same set of issues seen in Preview 6 (eg, xunit broken, missing ASP.NET Core, missing sourcelink commit ids).

**Comment by crummel** [comment]
I couldn't find an issue for the XUnit problem, I opened https://github.com/dotnet/source-build/issues/1161 for that.  I've started working on the sourcelink fixes, so hopefully I'll have a PR for that soon.
