### ISSUE TITLE
Roadmap for implementing support for OSes

### ISSUE THREAD

**Issue by 4creators** [dotnet/source-build#119]
In some projects I am working on an ability to use this build system would be very helpful. To enable any planing around this I would appreciate if team would share feature implementation roadmap indicating approximate times when support for .NET supported OSes will be available in this repo. This could potentially save some duplicate work on my side.

**Comment by omajid** [comment]
There are separate issues tracking support for different OS'es now:

- Windows: https://github.com/dotnet/source-build/issues/2910
- macOS: https://github.com/dotnet/source-build/issues/2909
- aribitrary Linux distros: https://github.com/dotnet/source-build/issues/297

Is there anything else that needs to be answered? Can this issue be closed as a "duplicate" of these other issues (sorry for the terminology, I know the other issues were filed later).

**Comment by MichaelSimons** [comment]
[Triage] Closing in favor of tracking with the previously mentioned issues.
