### ISSUE TITLE
Source-build support for Windows is suspended.

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1190]
This has never worked beyond core-setup. 

- [ ] Update readme
- [ ] Remove Windows build scripts / legs

**Comment by neeraj9** [comment]
The README or relevant documentation for building this repository should be updated to reflect this stand.

**Comment by MichaelSimons** [comment]
[Triage] source-build for windows is tracked in https://github.com/dotnet/source-build/issues/2910.
