### ISSUE TITLE
Analyze prebuilts for AspNetCore

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1191]
The following prebuilt packages are included as dependencies in source-build by **AspNetCore-Tooling**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

Package | Version | Comment
-- | -- | --
Internal.AspNetCore.BuildTasks | 3.0.0-build-20190530.3 | Should be able to remove since   we don't need this in source build
Microsoft.Bcl.AsyncInterfaces | 1.0.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
Microsoft.Build.Framework | 16.0.461 | Use ref-only version
Microsoft.Build.Tasks.Core | 16.0.461 | Use ref-only version
Microsoft.Build.Utilities.Core | 16.0.461 | Use ref-only version
Microsoft.Extensions.DependencyModel | 2.1.0 | Looks like we can unpin the   version here
Microsoft.Win32.Registry | 4.6.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
System.ComponentModel.Annotations | 4.6.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
System.IO.Pipelines | 4.6.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
System.Security.Cryptography.Cng | 4.6.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
System.Security.Cryptography.Xml | 4.6.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
System.Security.Principal.Windows | 4.6.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
System.Text.Json | 4.6.0-preview8.19405.3 | Should be built by CoreFX in   Preview 9
Yarn.MSBuild | 1.15.2 | Should be able to remove since   we don't need this in source build

**Comment by JunTaoLuo** [comment]
I think the only dependency here is `Microsoft.CodeAnalysis.CSharp.Workspaces` at this point and it seems like after https://github.com/dotnet/roslyn/pull/38425 is available in source build, the prebuilt should be eliminated?

**Comment by dseefeld** [comment]
That change isn't in soure-build, yet.

**Comment by JunTaoLuo** [comment]
I understand, but I just wanted to make sure the other prebuilts listed in this issue have been addressed?

**Comment by dseefeld** [comment]
Yes.  The report linked above is the source of truth for prebuilts and it only has one listed for aspnetcore:  Microsoft.CodeAnalysis.CSharp.Workspaces 3.0.0

**Comment by JunTaoLuo** [comment]
I'm not sure I understand how the linked page works: https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23. It shows that there's a prebuilt dependency on Microsoft.IdentityModel.Clients.ActiveDirectory but the AspNetCore packages with this dependency is not being built in source build. From the UI it seems like it may be an Arcade dependency?

**Comment by dseefeld** [comment]
> I'm not sure I understand how the linked page works: https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23. It shows that there's a prebuilt dependency on Microsoft.IdentityModel.Clients.ActiveDirectory but the AspNetCore packages with this dependency is not being built in source build. From the UI it seems like it may be an Arcade dependency?

Microsoft.IdentityModel.Clients.ActiveDirectory is specific to Arcade.  All prebuilts have been removed for AspNetCore

**Comment by dseefeld** [comment]
All prebuilts removed.
