### ISSUE TITLE
test utilities patch removal for coreFX tests

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1198]
Get rid of test utilities patch.

https://github.com/dotnet/source-build/pull/1113#pullrequestreview-280422235

cc @ericstj @ViktorHofer

**Comment by ViktorHofer** [comment]
We shouldn't depend on patches too much and instead submit PRs directly to corefx where we review necessary changes for sourcebuild.

**Comment by MichaelSimons** [comment]
These patches have long been removed.  Closing.
