### ISSUE TITLE
Minimize test exclusion list for coreFX Tests. 

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1199]
Core FX `1bb52e6a3db7f3673a3825f3677b9f27b9af99aa` results in some test failures. Due to this, source-build has to exclude some tests for coreFX test builds via a test exclusion file. The goal is to not exclude any tests. Either the list of tests should keep minimizing and tend to 0 as we update coreFX; or this would need further investigation.

**Comment by dseefeld** [comment]
Category test exclusion doesn't appear to be working in source-build as well.  This should be fixed and tests that should not be excluded should be added back.

**Comment by crummel** [comment]
[Scrub] Recommend closing as obsolete - VMR will let us run tests in situ.
