### ISSUE TITLE
Documentation - instructions how to build for Windows, macOS using Docker

### ISSUE THREAD

**Issue by 4creators** [dotnet/source-build#120]
> If you are building on Windows or OSX, building is possible via Docker. (https://hub.docker.com/r/microsoft/dotnet/)

Unfortunately I could not find any docs of how to use docker to build with source-build.

**Comment by dleeapho** [comment]
I think we should create reference Dockerfiles as part of our documentation.

**Comment by omajid** [comment]
I would be happy to help with Fedora/CentOS/RHEL.

**Comment by 4creators** [comment]
Thanks for reply. Reference Docerfiles would be very helpful. One of scenarios I am working on requires custom build of whole .NET Core SDK with modified CoreCLR for all platforms including Windows and macOS.

**Comment by MichaelSimons** [comment]
The instructions for building are located at https://github.com/dotnet/source-build#building-net-70-and-net-60.  These are kept up-to-date with the supported platforms/configurations.
