### ISSUE TITLE
3.0 RTM isn't tagged

### ISSUE THREAD

**Issue by kevingosse** [dotnet/source-build#1256]
Hello,

No tag has been pushed for 3.0 RTM, so I don't know what commit to use to build it locally (the latest one is v3.0.100-rc1-014190-SDK, but I think there have been a few commits in corefx between RC1 and RTM). What is the right source-build version to use to build 3.0 RTM?

Thanks.

**Comment by azixaka** [comment]
This issue prevents Red Hat from releasing .net core 3 image to their RH Catalogue so .net 3.0 won't be available in OpenShift until source-build is tagged, as per this issue - [https://github.com/redhat-developer/s2i-dotnetcore/issues/271](url).

Could you please give a timeline on when this is going to happen?

**Comment by crummel** [comment]
Hi @kevingosse and @azixaka, sorry for the delay.  We're currently working through some CI issues and testing locally to make sure everything looks good.  If you're building on your own we're expecting https://github.com/dotnet/source-build/commit/6df8641e6f585bc6566c0ded29b6773a3a726f3f to be the tagged commit but we should know for sure whether we need more changes by the end of the day.

**Comment by crummel** [comment]
We've completed our testing and I've tagged https://github.com/dotnet/source-build/releases/tag/v3.0.100-SDK.  Let us know if you have any issues building it.
