### ISSUE TITLE
Fedora 27/glibc 2.26 support

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#126]
Fedora 27 uses `glibc` 2.26. This introduces some incompatible build-time changes. See https://sourceware.org/glibc/wiki/Release/2.26#Packaging_Changes for more details.

So Fedora 27 (as well as any other distribution using `glibc` 2.26) will need some additional fixes:

- https://github.com/dotnet/core-setup/pull/3129 (Merged)
- https://github.com/dotnet/coreclr/pull/13785 (Merged)

For now, we are carrying these as: https://pagure.io/fedora-dotnet/blob/f0c2fa0abb63c100a494d417c26036879e65f8f1/f/f27-libc.patch

**Comment by dleeapho** [comment]
Fedora 27 GAs in October (probably).

**Comment by omajid** [comment]
I am going to look into opening a PR for this. Should I just add the fixes under `patches` or would it be better to update coreclr and core-setup to newer commits that include this fix?

**Comment by dagood** [comment]
Thanks! Best to update the submodules--they should generally be able to stay in sync with release/2.0.0 for CoreCLR/CoreFX/Core-Setup now.

**Comment by omajid** [comment]
Those fixes were merged into `master` for `coreclr` and `core-setup`. They are not in `release/2.0.0`. Do you think it would be better to try and get those merged into the `release/2.0.0` branches for both? And `master` of `source-build` tracks `release/2.0.0` for both of those?

**Comment by dagood** [comment]
The default `source-build` branch is `dev/release/2.0`, which points to `core*` `release/2.0.0` for 2.0 servicing.
 * If this issue needs to be fixed for 2.0 servicing, the fix should be ported to the `core*` `release/2.0.0` branches and source-build `dev/release/2.0` updated.
 * If it only needs to be fixed for 2.1+, updating `source-build ` `master` to the newest `core*` `master`s is correct.

**Comment by omajid** [comment]
As far as I can tell, we now use recent enough versions of coreclr and corefx that all the fixes are now available out of the box.
