### ISSUE TITLE
Prebuilt Removal: Investigate Microsoft.CodeAnalysis,2.8.2 in arcade

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1265]
Arcade defines a static version package reference for Microsoft.CodeAnalysis,2.8.2 here:
https://github.com/dotnet/arcade/blob/14abaee3dba41fbe608431fb6a4f4b2435dcac33/src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj#L60-L61

This is causing multiple indirect prebuilts.  There is a comment which states:
`Need to reference version 2.8.2 of CodeAnalysis so that we don't have downgrade issues with System.Reflection.Metadata version`

This should be investigated to see if source-build can use a source-built version for this package.

**Comment by chcosta** [comment]
@joperezr , can you take a look?

**Comment by joperezr** [comment]
That reference should be now removed from the Packaging task. We removed the task that depended on it and it seems now that we forgot to also remove the extra package dependency.

**Comment by dseefeld** [comment]
@joperezr - Thanks, that's great to hear!
