### ISSUE TITLE
Prebuilt Removal: Investigate Microsoft.NETCore.App.Runtime... in AspNetCore

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1266]
There are a set of runtime packages referenced here in AspNetCore:

https://github.com/aspnet/AspNetCore/blob/68dcbe39906d50c31f934b5f6141548b3fe3838b/eng/Dependencies.props#L103-L112

with the comment:

`Runtime packages required for crossgen`

These are causing an indirect prebuilt in source-build.  Are these required to build source-build or is there a source-built package that we can use here?

**Comment by dseefeld** [comment]
@JunTaoLuo Any idea on what we can do with these packages?

**Comment by JunTaoLuo** [comment]
Yes these packages provide the crossgen.exe that we use. I see in the build logs that these are built by core-setup, so I'm not sure why they would be missing. 

However, in source-build only the package with the RID specific to that environment is built so maybe we can ensure that not all of these packages are needed for each distro. What I mean is that we should only depend on the debian package when building on debian for example.

**Comment by dseefeld** [comment]
Fixed with #1342
