### ISSUE TITLE
Update source-build for 1.1.x release

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#127]
@crummel commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1561)

- [x] Go back to previously shipped tarball commit and make sure everything still builds (no submodules disappeared, etc)
- [x] Update submodules to new 1.1 branches for CoreCLR, CoreFX, core-setup, CLI
- [x] Update submodules that these depend on
- [x] Update patches as needed
- [x] Do we need to include 1.0.x builds in this? (#1560)

**Comment by omajid** [comment]
> Do we need to include 1.0.x builds in this?

The previous binaries that Red Hat have shipped have not included 1.0.x bits in our "1.1" releases (aside from the 1.0 RC2-era CLI). This is not a request from us at this time. Of course, it would be nice to have for the community.

**Comment by crummel** [comment]
Closing as this was for the previous servicing release and that has been delivered.
