### ISSUE TITLE
Patch removal: Yarn workaround for AspNetCore

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1276]
AspNetCore doesn't use Yarn.MSBuild in its source-build build, but the package is still restored due to some combination of being in the global.json and appearing in `<Project Sdk="Yarn.MSBuild">` project headers.  Currently this is worked around in source-build with a [patch](https://github.com/dotnet/source-build/blob/fb449b4f8f1af3521feb858ac975617c248b060d/patches/aspnetcore/0006-Remove-Yarn-dependency-not-used-in-source-build.patch).  Need to find some workaround to keep it from restoring when not being used.

cc @JunTaoLuo

**Comment by MichaelSimons** [comment]
This patch no longer exists.  Recommend closing.
