### ISSUE TITLE
Prebuilt Removal:  Investigate remaining indirect prebuilts in Arcade

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1280]
The following prebuilts are being reported as indirect prebuilts in arcade.  These need to be investigated and removed.

- [x]   Microsoft.IdentityModel.Clients.ActiveDirectory -  3.19.8
- [x]   System.Private.DataContractSerialization -    4.3.0
- [x]   System.Runtime.Serialization.Json -    4.3.0
- [x]   System.Text.Encoding.CodePages -  4.5.1
- [x]   System.Xml.XmlSerializer -  4.3.0
- [x]   System.Xml.XPath.XDocument  - 4.3.0
- [x]   System.Xml.XPath  - 4.3.0
- [x]   System.ValueTuple - 4.3.0
- [x]   System.Runtime.CompilerServices.Unsafe - 4.6.0-preview7.19362.9
- [x]   Microsoft.CodeAnalysis.Common  - 2.1.0
- [x]   Microsoft.CodeAnalysis.Analyzers -  1.1.0
- [x]   Microsoft.Bcl.AsyncInterfaces  - 1.0.0-preview7.19362.9

**Comment by adaggarwal** [comment]
Adding the ones after arcade update

**Comment by dseefeld** [comment]
Fixed by #1331
