### ISSUE TITLE
Prebuilt Removal: Investigate remaining indirect prebuilts in NuGet.Client repo

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1283]
The following prebuilts are being reported as indirect prebuilts in NuGet.Client. These need to be investigated and removed.

- [ ]   runtime.any.System.Collections -  4.3.0
- [ ]   runtime.any.System.Diagnostics.Tools -    4.3.0
- [ ]   runtime.any.System.Diagnostics.Tracing -    4.3.0
- [ ]   runtime.any.System.Globalization -    4.3.0
- [ ]   runtime.any.System.Globalization.Calendars -    4.3.0
- [ ]   runtime.any.System.IO -  4.3.0
- [ ]   runtime.any.System.Reflection -  4.3.0
- [ ]   runtime.any.System.Reflection.Extensions -    4.3.0
- [ ]   runtime.any.System.Reflection.Primitives -    4.3.0
- [ ]   runtime.any.System.Resources.ResourceManager -  4.3.0
- [ ] runtime.any.System.Runtime   -  4.3.0
- [ ]   runtime.any.System.Runtime.Handles -    4.3.0
- [ ]   runtime.any.System.Runtime.InteropServices -    4.3.0
- [ ]   runtime.any.System.Text.Encoding -    4.3.0
- [ ]   runtime.any.System.Text.Encoding.Extensions -    4.3.0
- [ ]   runtime.any.System.Threading.Tasks -    4.3.0
- [ ]   runtime.win.Microsoft.Win32.Primitives -    4.3.0
- [ ]   runtime.win.System.Diagnostics.Debug -    4.3.0
- [ ]   runtime.win.System.IO.FileSystem -    4.3.0
- [ ]   runtime.win.System.Net.Primitives -    4.3.0
- [ ]   runtime.win.System.Runtime.Extensions -    4.3.0
- [ ]   runtime.win7.System.Private.Uri -    4.3.0
- [ ] System.Private.Uri -  4.3.0

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/source-build/pull/1308
