### ISSUE TITLE
Prebuilt Removal: Investigate remaining indirect prebuilts in Roslyn repo

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1284]
The following prebuilts are being reported as indirect prebuilts in roslyn. These need to be investigated and removed.

- [x]   RoslynTools.Lightup.System.Runtime.Loader -    4.3.0
- [x]   System.CodeDom -  4.4.0

**Comment by NikolaMilosavljevic** [comment]
System.CodeDom prebuilt will be automatically removed when the following PR is completed:
https://github.com/dotnet/source-build/pull/1291

**Comment by NikolaMilosavljevic** [comment]
RoslynTools.Lightup.System.Runtime.Loader was removed in Roslyn repo on 8/28 with https://github.com/dotnet/roslyn/commit/3e9505e9b430c852bc36579647c5951b4a808316

It was replaced with a reference of System.Runtime.Loader - that one would need to be removed from prebuilts once we sync to new Roslyn tag.

**Comment by dseefeld** [comment]
All Roslyn prebuilts have been removed.
