### ISSUE TITLE
Prebuilt Removal: Investigate remaining indirect prebuilts in Sdk repo

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1285]
The following prebuilts are being reported as indirect prebuilts in sdk. These need to be investigated and removed.

- [x]   Microsoft.NETFramework.ReferenceAssemblies.net472 -  1.0.0-preview.2
- [x]   Microsoft.NETFramework.ReferenceAssemblies.net472 -  1.0.0-preview.2
- [x]   System.Threading.Tasks.Dataflow -    4.5.24

**Comment by dseefeld** [comment]
System.Threading.Tasks.Dataflow,4.5.24 is fixed with this change: https://github.com/dotnet/source-build-reference-packages/pull/74

**Comment by adaggarwal** [comment]
#1296 for Microsoft.NETFramework.ReferenceAssemblies.net472 -  1.0.0-preview.2

**Comment by nguerrera** [comment]
Microsoft.NETFramework.ReferenceAssemblies comes from arcade:


https://github.com/dotnet/arcade/blob/380eaaf663b425943754a15b29e814df0bb1b078/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L132

**Comment by nguerrera** [comment]
We need to build for net472 in all the build task repos so that VS Code can work: https://github.com/dotnet/source-build/issues/125

**Comment by nguerrera** [comment]
Microsoft.NETFramework.ReferenceAssemblies should be provided as reference only package in source build

**Comment by adaggarwal** [comment]
net472 fixed [#80](https://github.com/dotnet/source-build-reference-packages/pull/80)
