### ISSUE TITLE
Prebuilt Removal: Investigate remaining indirect prebuilts in Toolset repo

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1286]
The following prebuilt is being reported as indirect prebuilts in toolset. This needs to be investigated and removed.

- [x] System.ValueTuple   -  4.4.0

**Comment by adaggarwal** [comment]
[#78](https://github.com/dotnet/source-build-reference-packages/pull/78) adds this package to source-build-ref-packages.

**Comment by adaggarwal** [comment]
Fixed.
