### ISSUE TITLE
Add ref assembly packages 

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1298]
The following packages are needed for source-build-reference-packages to be completely independent from Reference Assembly packages

- [x] "Microsoft.NETFramework.ReferenceAssemblies.net45"
- [x] "Microsoft.NETFramework.ReferenceAssemblies.net451"
- [x] "Microsoft.NETFramework.ReferenceAssemblies.net46"
- [x] "Microsoft.NETFramework.ReferenceAssemblies.net461"
- [x] "Microsoft.NETFramework.ReferenceAssemblies.net462"
- [x] "Microsoft.NETFramework.ReferenceAssemblies.net47"
- [x] Microsoft.NETFramework.ReferenceAssemblies.net472 -  1.0.0-preview.2
- [x] NETStandard.Library 2.0.3
- [x] NETStandard.Library.NetFramework - 2.0.1-servicing-26011-01
- [x] Microsoft.TargetingPack.NetFramework.v.4.7.2 - 1.0.0

**Comment by adaggarwal** [comment]
[#72](https://github.com/dotnet/source-build-reference-packages/pull/72) fixed net 46

**Comment by adaggarwal** [comment]
[#76](https://github.com/dotnet/source-build-reference-packages/pull/76) fixed net 461

**Comment by adaggarwal** [comment]
Depends on #1313 for faster turn-around. ATM, the ref-pack build is getting past 2h30m for 4/8 target packs. Adding 4 more would shoot up the build time by approximately 2 more hours. A parallelization effort for target packs is needed to keep the build time practical.

**Comment by crummel** [comment]
I added `NETStandard.Library` version 2.0.3 to the list of ref packages we need - we don't produce netstandard2.0 reference assemblies but we do need to include them.

**Comment by adaggarwal** [comment]
Added Microsoft.NETFramework.ReferenceAssemblies.net472 -  1.0.0-preview.2

Reason - https://github.com/dotnet/source-build/issues/1285#issuecomment-542801879

**Comment by adaggarwal** [comment]
[#80](https://github.com/dotnet/source-build-reference-packages/pull/80)  - Microsoft.NETFramework.ReferenceAssemblies.net472 - 1.0.0-preview.2

**Comment by adaggarwal** [comment]
[#82](https://github.com/dotnet/source-build-reference-packages/pull/82) for net45

**Comment by adaggarwal** [comment]
[#83](https://github.com/dotnet/source-build-reference-packages/pull/83) got net451

**Comment by adaggarwal** [comment]
[#84](https://github.com/dotnet/source-build-reference-packages/pull/84) for net462

**Comment by adaggarwal** [comment]
[#85](https://github.com/dotnet/source-build-reference-packages/pull/85) for net47

**Comment by adaggarwal** [comment]
[#86](https://github.com/dotnet/source-build-reference-packages/pull/86) for netStandard.Lib `2.0.3`

**Comment by adaggarwal** [comment]
[#90](https://github.com/dotnet/source-build-reference-packages/pull/90) for `Microsoft.Netcore.App.Ref - 3.0.0`
