### ISSUE TITLE
Check for repos using custom build tasks without source-built packages

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1320]
Similar to https://github.com/dotnet/source-build/pull/1318, several repos have custom build tasks that are built in a separate build before the main build.  Check to make sure they are getting these properties.

**Comment by crummel** [comment]
Note some repos could be coincidentally matching source-built versions now and break sometime down the road as well.

**Comment by MichaelSimons** [comment]
[Triage] Since we are building cleanly offline, this doesn't appear to be an issue.  Closing.
