### ISSUE TITLE
CI legs need to to be updated to latest 

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1324]

**Comment by adaggarwal** [comment]
Fedora29 -> 30 update can be a problem ATM. Faced an issue regarding set `locale` to utf-8. 

cc @MichaelSimons

**Comment by adaggarwal** [comment]
> Fedora29 -> 30 update can be a problem ATM. Faced an issue regarding set `locale` to utf-8.


https://github.com/dotnet/source-build/issues/1339#issuecomment-548879934 helped for Fedora locale set error.

**Comment by omajid** [comment]
For additional context, this was a [Change in Fedora 30](https://fedoraproject.org/wiki/Changes/Remove_glibc-langpacks-all_from_buildroot). The consequences is that the language features that various locale features require don't work out of the box for non-`C` locales.

There's two fixes for this, as far as I can tell:

1. Use a `C` locale. `C`/`C.UTF-8`/`POSIX` work out of the box
2. Install the language pack for the non-`C` locale.  That's what `glibc-langpack-en` does.

**Comment by adaggarwal** [comment]
> 2. Install the language pack for the non-`C` locale.  That's what `glibc-langpack-en` does.

[#212](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/212) to install glibc-language-pack-en
