### ISSUE TITLE
Publish with `linux-x64` fails on 3.1 Preview 1

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1339]
I built source-build 3.1 Preview 1 tag on Fedora 31. Then running a `publish` failed:

```
+ dotnet new console --no-restore
The template "Console Application" was created successfully.
++ ../runtime-id --portable
+ dotnet publish -r linux-x64 /p:PublishReadyToRun=true
Microsoft (R) Build Engine version 16.4.0-preview-19502-03+3af680463 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 85.47 ms for /home/omajid/devel/dotnet-bunny/dotnet-regular-tests/publish-ready-to-run-linux/publish-ready-to-run-linux.csproj. 
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  publish-ready-to-run-linux -> /home/omajid/devel/dotnet-bunny/dotnet-regular-tests/publish-ready-to-run-linux/bin/Debug/netcoreapp3.1/linux-x64/publish-ready-to-run-linux.dll
/usr/lib64/dotnet/sdk/3.1.100-preview1-014459/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(273,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [/home/omajid/devel/dotnet-bunny/dotnet-regular-tests/publish-ready-to-run-linux/publish-ready-to-run-linux.csproj]
```

This was working with 3.0 and seems like a regression for 3.1.

**Comment by omajid** [comment]
cc @tmds

**Comment by crummel** [comment]
This is probably a regression on https://github.com/dotnet/source-build/issues/1232.  @adaggarwal, can you check if the 3.1 preview2 PR needs the same fix?

**Comment by adaggarwal** [comment]
@omajid, are you using Fedora 31? I tried Fedora 30 and its seems to failing on build as well. 

`/MountedPath/source-build-31prev2/tools-local/init-build.proj(192,5): error : /usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`

`/MountedPath/source-build-31prev2/tools-local/init-build.proj(192,5): error : /usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  3247`

`/MountedPath/source-build-31prev2/tools-local/init-build.proj(192,5): error MSB3073: The command "git --git-dir=/MountedPath/source-build-31prev2/.git/modules/src/arcade.git rev-list --count a42a124635ce1a218309ecb31ec59d559cacb886" exited with code -1.
/MountedPath/source-build-31prev2/tools-local/init-build.proj(192,5): error : InvalidOperationException: git command '--git-dir=/MountedPath/source-build-31prev2/.git/modules/src/arcade.git rev-list --count a42a124635ce1a218309ecb31ec59d559cacb886' failed with exit code -
1 and error 3247
`

**Comment by omajid** [comment]
> @omajid, are you using Fedora 31?

Yes

> I tried Fedora 30 and its seems to failing on build

Does installing `glibc-langpack-en` help?

**Comment by adaggarwal** [comment]
> Does installing `glibc-langpack-en` help?

That helped! 👍

**Comment by adaggarwal** [comment]
The test passed with fedora30 for me

`./dotnet publish -r linux-x64 /p:PublishReadyToRun=true
Microsoft (R) Build Engine version 16.4.0-preview-19528-01+3745451f4 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 3.63 sec for /MountedPath/source-build-31prev2/testing-smoke/builtCli/builtCli.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  builtCli -> /MountedPath/source-build-31prev2/testing-smoke/builtCli/bin/Debug/netcoreapp3.1/linux-x64/builtCli.dll
  builtCli -> /MountedPath/source-build-31prev2/testing-smoke/builtCli/bin/Debug/netcoreapp3.1/linux-x64/publish/
`

**Comment by adaggarwal** [comment]
Fixed. Since it passes with 3.1prev2 on fedora 31.
