### ISSUE TITLE
AspNetCore shared framework is missing System.Drawing.Common.dll in 3.0

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1343]
From https://github.com/dotnet/core/issues/3734, inlining a few details:

> When installing `rh-dotnet30-dotnet-runtime-3.0` as suggested here:
> https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-current
> 
> The folder: `/opt/rh/rh-dotnet30/root/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App/3.0.0`
> is missing `System.Drawing.Common.dll`
> 
> Which is part of the AspNetCore binaries here:
> https://dotnet.microsoft.com/download/dotnet-core/3.0

> We are using this assembly (System.Drawing.Common.dll) to edit png images.

> I don't think there's any good reason for source-build to be different, somehow [the dependency](https://github.com/aspnet/AspNetCore/blob/aee5e4080331553ea9dfb7fb388b6d72f715bf6a/eng/SharedFramework.External.props#L69) may have broken?

**Comment by tmds** [comment]
@dagood have you had the chance to look into this?

cc @omajid

**Comment by dagood** [comment]
I haven't been planning to, I filed this for source-build triage. For a rough direction, seems like this would be caused by some CoreFX => ASP.NET Core dependency problem, or maybe simply some logic in ASP.NET or source-build. @dleeapho @dseefeld @crummel @adaggarwal @NikolaMilosavljevic

**Comment by dseefeld** [comment]
This doesn't appear to be an issue anymore.  The latest versions 3.0.3 and 3.1.10 both have System.Drawing.Common.dll present.
