### ISSUE TITLE
Attach SDK product to each release as a resource for non-source-build devs to understand the state of source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1345]
I think source-build should:

* Save the built SDK in the rolling build pipeline. (For some distro, probably CentOS.)
* Upload the built SDK to the GitHub release.
  * OR have some way to trace the GitHub release back to the AzDO build to find this artifact. (Not useful to external contributors, but maybe storage space is a concern?)

Since I don't actively work on it, I don't have completed source-builds laying around (especially multiple branches!), but I fairly often want to know the current state of the source-build project to avoid breaking it, or to understand how source-build puts some things together. (And maybe find a bug.)

At the moment I'm particularly interested in 3.1.0-preview1.

@crummel @dseefeld @adaggarwal

**Comment by crummel** [comment]
Also related #1321.

**Comment by MichaelSimons** [comment]
[Triage] This appears to be covered by #1321
