### ISSUE TITLE
How to update arcade-services?

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1354]
I would like to pull in this fix from arcade-services: https://github.com/dotnet/arcade-services/pull/694/

What's the process of getting the arcade-submodule here in source-build updated to include that fix?

**Comment by adaggarwal** [comment]
imo, with [darc update](https://github.com/dotnet/source-build/pull/1315) we stopped relying on arcade-services. We could very well trash it?

cc @crummel
