### ISSUE TITLE
apphost has a permission of -rwxr--r--

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1366]
It looks like https://github.com/dotnet/core-setup/issues/7062 (which was merged into core-setup) still hasn't been completely fixed yet.

I built source-build's 3.1 Preview 3 SDK:

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /usr/lib64/dotnet/sdk/3.1.100-preview3-014645/

Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  797bee2941

.NET Core SDKs installed:
  3.1.100-preview3-014645 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

And `/usr/lib64/dotnet/sdk/3.1.100-preview3-014645/AppHostTemplate/apphost` still has bad permissions:

```
$ ls -l /usr/lib64/dotnet/sdk/3.1.100-preview3-014645/AppHostTemplate/apphost
-rwxr--r--. 1 root root 97600 Nov 16 05:37 /usr/lib64/dotnet/sdk/3.1.100-preview3-014645/AppHostTemplate/apphost
```

```
$ strings /usr/lib64/dotnet/sdk/3.1.100-preview3-014645/AppHostTemplate/apphost | grep '(#)'
@(#)Version 3.100.19.55302 @Commit: 13f35c3d86a40ff811bfde0b64cfb86431c19d15
```

**Comment by omajid** [comment]
cc @tmds

**Comment by dagood** [comment]
I think this can be closed based on the convo in https://github.com/dotnet/core-setup/issues/7062#issuecomment-555183638. Sound ok, or is there really a problem with the generated apphost in the source-built SDK?

**Comment by omajid** [comment]
If there's a (simple) way to fix the permissions in the SDK itself, I would like to fix that. Funny looking file permissions get flagged by various tools. This isn't urgent, though.

**Comment by dagood** [comment]
Reducing the apphost template to `-r--r--r--` is tracked by https://github.com/dotnet/core-setup/issues/8863 (the file is currently `-rwxr--r--` in the Microsoft build tar.gz too, as you noted). Are the tools finding it strange that a binary file that *could* be run doesn't have `x`? The funny permissions are expected because really is a funny file.

**Comment by omajid** [comment]
I somehow missed https://github.com/dotnet/core-setup/issues/8863. I am going to close this issue, then.

>  Are the tools finding it strange that a binary file that could be run doesn't have x

No, I dont think I know of any tool that does that.
