### ISSUE TITLE
Working with submodules

### ISSUE THREAD

**Issue by weshaggard** [dotnet/source-build#137]
While getting started in this repo I forget to update/initialize the submodules. I suspect that might be a common issue for folks so I was thinking we should consider adding a `git submodule update --init` to the beginning of the build scripts but given I'm pretty new to submodules I don't know if that will start to cause issue if there are changes to the modules or if there are patches applied to them. Anyone have enough experience to advise for or against always doing an update/init from the build scripts?

**Comment by dagood** [comment]
I would be fine with doing this if a project submodule dir that's in the build lineup doesn't exist, but I think we shouldn't do this blindly on each build: it would update away from dev commits on the submodules.
