### ISSUE TITLE
Prebuilt Removal: Investigate release/3.1 prebuilts for roslyn

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1374]
The following prebuilts are being reported in roslyn in release/3.1. These need to be investigated and removed.

- [ ]   Microsoft.CodeAnalysis.CSharp.CodeStyle - 3.3.1-beta3-19454-05
- [ ]   Microsoft.CodeAnalysis.VisualBasic.CodeStyle - 3.3.1-beta3-19454-05
- [x]   Microsoft.NETFramework.ReferenceAssemblies.net472 - 1.0.0-alpha-004

**Comment by adaggarwal** [comment]
#1382 takes care of `Microsoft.NETFramework.ReferenceAssemblies.net472 - 1.0.0-alpha-004 `
