### ISSUE TITLE
We need to support incremental building

### ISSUE THREAD

**Issue by weshaggard** [dotnet/source-build#139]
Today we have a lot of levels of repo and prep builds (refs/dummypackages/patching, etc) that happen every time you run a build. A lot of those steps can be done incrementally so we don't have to build everything every time.

**Comment by weshaggard** [comment]
:(

**Comment by wfurt** [comment]
agreed @weshaggard Having better support for partial or incremental builds would be nice.

**Comment by weshaggard** [comment]
@wfurt we have improved it some but it it definitely can still use some work but we need more specific work items to investigate. I also think a lot of the incremental build issues need to be addressed in the individual repos.
