### ISSUE TITLE
The source-tarball genrated by source-build should work everywhere

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1412]
Historically, source-build has generated fairly portable source tarballs. If I built the source-build tarball on RHEL 7, for example, I have been able to use it to build source-build on Fedora 29, 30 and 31, as well as RHEL 8.

With the recent reduction in prebuilts, some of this functionality has regressed. Now, I need to build source-build on each platform/architecture. I can't re-use the RHEL 7 tarball on Fedora. I can't build the source-tarball I built on Fedora 31 in Fedora 32.

I think the eventual goal, fitting in with the 0 prebuilts goal, is to not have anything in the source-tarball that's OS/architecture specific. The same source-tarball should be build-able everywhere; the individual doing a build should supply a working SDK (and/or other OS-specific dependencies) to source-build.

**Comment by tmds** [comment]
> I need to build source-build on each platform/architecture.

Is it a dependency on the rid of the platform that was used to generate the tarball?
Or another platform dependency?

This is related to https://github.com/dotnet/source-build/issues/298 (create linux-x64 compatible tarball for each release).

**Comment by tmds** [comment]
I wonder if we can generate a tarball for the `fedora-x64` rid and use it on multiple versions of Fedora...

cc @crummel @dagood

**Comment by crummel** [comment]
Bringing this one up for triage again because I believe it's relevant to some issues we had with recent releases.

**Comment by omajid** [comment]
With all the bootstrap work complete, I have had decent success now using the same tarball for building 3.1 on Fedora 32 and 33 on x8664 and also, separately, on Fedora 33 on x64 and arm64. Are there still any known issues here?

**Comment by crummel** [comment]
[Scrub] Believe this has been solved with the current prep.sh approach.
