### ISSUE TITLE
What version of .NET Core does this repo build?

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#142]
I just managed to run this successfully and took a look at the output:

    $ git rev-parse HEAD
    1b1fbed07487d0c864ee0fc4d34c47e5a9c56935

    $ ls bin/x64/Release/*
    bin/x64/Release/dotnet-sdk-2.0.0-preview3-006908-linux-x64.tar.gz
    bin/x64/Release/dotnet-sdk-debug-2.0.0-preview3-006908-linux-x64.tar.gz
    bin/x64/Release/dotnet-sdk-internal-2.0.0-preview3-006908-linux-x64.tar.gz
    bin/x64/Release/dotnet-sdk-langpack-2.0.0-preview3-006908-linux-x64.tar.gz

The built binary says both preview3 and 2.0.0 (final):

    $ ./dotnet --info
    .NET Command Line Tools (2.0.0-preview3-006908)
    
    Product Information:
     Version:            2.0.0-preview3-006908
     Commit SHA-1 hash:  38031f6e5c
    
    Runtime Environment:
     OS Name:     fedora
     OS Version:  26
     OS Platform: Linux
     RID:         fedora.26-x64
     Base Path:   /home/omajid/devel/dotnet/source-build/dotnet/sdk/2.0.0-preview3-006908/
    
    Microsoft .NET Core Shared Framework Host
    
      Version  : 2.0.0
      Build    : 82b22fa44e46d624ebeddf156f33e9cfb317bd57

Is this repository supposed to build 2.0.0? Or A pre-release version of the upcoming 2.0.x update? Or A pre-release version of 2.1?

**Comment by leecow** [comment]
Hey @omajid, I think you're talking about the master branch and the release monikers have not yet been updated. The intention is for source-build to track with the various master branches (coreclr, cli, etc). We'll get this updated.

**Comment by omajid** [comment]
Thanks. That clears things up. I thought `master` here was tracking the 2.0 release and I was really confused.
