### ISSUE TITLE
Hidden version files in installation

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1421]
.NET Core installations - runtime and sdk - include hidden version files. 

    $ find /usr/lib64/dotnet/ -iname '.*' 
    /usr/lib64/dotnet/shared/Microsoft.NETCore.App/2.0.6/.version
    /usr/lib64/dotnet/sdk/2.1.101/.version

Is there a good reason they have to be hidden files? What if we just renamed them to `version` instead of `.version`? Hidden files are often a surprise to users and some software can flag them as suspicious.

**Comment by dseefeld** [comment]
This is an issue in core-setup, aspnet and core-sdk.

**Comment by dseefeld** [comment]
This is a source-build "cleanliness/readiness" issue for maintainers.

**Comment by MichaelSimons** [comment]
[Triage] This is not a source-build specific issue.  @omajid - would you please open repo specific issues for this and close this issue?

**Comment by omajid** [comment]
I filed issues in the product repos:

- SDK: https://github.com/dotnet/sdk/issues/28598
- ASP.NET Core: https://github.com/dotnet/aspnetcore/issues/44559
- Runtime: https://github.com/dotnet/runtime/issues/77061
