### ISSUE TITLE
[3.0/3.1] GenerateBundledVersions.targets needs to include target rid in AppHostRuntimeIdentifiers

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#1444]
With previous release we had [a patch](https://github.com/dotnet/source-build/pull/1231/files) that got rid of the target rid from the RuntimePackRuntimeIdentifiers.

With the servicing update this is already the case (part of https://github.com/dotnet/core-sdk/commit/0f52aed34c765c54fbb7affad075313ae2390e2f).
The target rid is now missing in the AppHostRuntimeIdentifiers.

cc @nguerrera @dagood @crummel @omajid

**Comment by tmds** [comment]
A patch like this should work:
3.0 version:
```diff
diff --git a/src/redist/targets/GenerateBundledVersions.targets b/src/redist/targets/GenerateBundledVersions.targets
index 3a2726493..70eb78ef9 100644
--- a/src/redist/targets/GenerateBundledVersions.targets
+++ b/src/redist/targets/GenerateBundledVersions.targets
@@ -38,6 +38,11 @@
           win-x86;
           " />
 
+      <NetCoreHostPackRids Include="
+          $(ProductMonikerRid);
+          @(NetCoreRuntimePackRids)
+          " />
+
       <AspNetCoreRuntimePackRids Include="
         win-x64;
         win-x86;
@@ -157,7 +162,7 @@ Copyright (c) .NET Foundation. All rights reserved.
                       TargetFramework="netcoreapp3.0"
                       AppHostPackNamePattern="Microsoft.NETCore.App.Host.**RID**"
                       AppHostPackVersion="$(_NETCoreAppPackageVersion)"
-                      AppHostRuntimeIdentifiers="@(NetCoreRuntimePackRids, '%3B')"
+                      AppHostRuntimeIdentifiers="@(NetCoreHostPackRids, '%3B')"
                       />
     
     <KnownFrameworkReference Include="Microsoft.WindowsDesktop.App"

```
I can make a PR for it, and the 3.1 equivalent.

**Comment by dagood** [comment]
Makes sense to me. Nit: `NetCoreHostPackRids` => `NetCoreAppHostPackRids` would be more consistent with the rest of the file. (The NuGet package IDs don't map intuitively to the "proper names" of the packs.)

/cc @dseefeld
