### ISSUE TITLE
Implement repo API and contracts

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#146]
- https://github.com/dotnet/source-build/issues/183 Auto-dependency flow build
- [ ] Patch-less build

**Comment by omajid** [comment]
Is there a document that covers the repo API in some detail? I know some of the motivation behind it - basically document/automate inputs (files, build commands) and outputs (artifacts) of each repository - but is there some place where I can read up on more details?

**Comment by dleeapho** [comment]
@omajid what you are describing will be part of this issue, viz. @eerhardt will take stock of what we need and design the API for repos.
