### ISSUE TITLE
Why is source-build-reference-packages consumed as a prebuilt?

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1461]
https://github.com/dotnet/source-build/pull/1009 consumes source-build-reference-packages as a prebuilt--a tar.gz of nupkgs. However, `source-build-reference-packages` can build from source. Why is it used as a prebuilt?

(I looked at https://github.com/dotnet/source-build/pull/1009 for an answer, readmes, and a few docs. Maybe I missed something. I think this should have an explanation somewhere visible.)

@dseefeld @crummel @adaggarwal

**Comment by omajid** [comment]
@tmds was asking me the same question earlier today. I dont know the answer.

However, I don't mind source-build depending on prebuilts as long as there are sensible/obvious ways for users to provide those prebuilts (instead of source-build automagically downloading binaries from the internet).

**Comment by dagood** [comment]
Oh duh, right over here: https://github.com/dotnet/source-build/issues/1456#issuecomment-578812849.

It looks like the answer from @dseefeld is that this is purely a build time optimization.

**Comment by dagood** [comment]
Filed https://github.com/dotnet/source-build-reference-packages/pull/98 to add something about this to the readme.
