### ISSUE TITLE
Produce RHEL8 tarballs in CI

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1465]
We don't currently produce RHEL8 tarballs - there are some differences here like the lack of system libunwind.  We should use a supported RHEL8 Docker image to do these builds in CI - not like the snapshot RHEL7 image we use.

**Comment by omajid** [comment]
Using CentOS 8 or [CentOS Stream](https://developers.redhat.com/blog/2019/09/24/changes-to-centos-what-centos-stream-means-for-developers/) - a rolling preview of what goes in the next release of RHEL 8 - might also be a good idea.

**Comment by dagood** [comment]
Triage notes:
The cross-distro tarball work #1412 would fix the direct issue here, but testing on CentOS 8 or Stream could be valuable to catch issues with dependencies.

**Comment by crummel** [comment]
[Scrub] We now have CentOS Stream 8 CI.
