### ISSUE TITLE
What is the current re-patching workflow?

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1468]
Now that we use Darc to clone component repos rather than submodules, I expect https://github.com/dotnet/source-build/blob/release/3.1/extract-patches.sh no longer works. Do we have an updated typical workflow?

When I solved a bug in 3.0, I used `git am` to reapply patches to an external clone I made, then manually ran `git format-patch` to recreate patch files, then copied them over into source-build.

@crummel @adaggarwal @dseefeld

**Comment by dseefeld** [comment]
I use `extract-patches.sh`.  When making changes in repos, I work in the "non-commit-id labelled" directory of the repo in bin/src and checkout the target commit.  Then I run `git am` to reapply patches, make my changes and commit and then use `extract-patches.sh` to recreate patch files.

**Comment by dagood** [comment]
Interesting... I wouldn't expect this to work anymore--I would expect it to give you the source-build commit, which is not in the same tree as the repo commit, causing some sort of failure or unexpected behavior:

https://github.com/dotnet/source-build/blob/3085962b9d1c17a6c0b746837b94238257966d0a/extract-patches.sh#L5-L10

**Comment by dseefeld** [comment]
I see.  I don't ever use that path because I always pass in the base SHA instead of allowing it to try to figure it out.

**Comment by adaggarwal** [comment]
I usually go with the manual approach `git am` -> `format-patch`

**Comment by dagood** [comment]
Thanks, filed https://github.com/dotnet/source-build/issues/1469 to track improving the script.

**Comment by dagood** [comment]
Reopening to track documenting the expected way to do this. In particular, for servicing scenarios, where we shouldn't spend time figuring out a personal process.

**Comment by MichaelSimons** [comment]
[Triage] We don't want patches and don't want to do work that encourages them 😄.
