### ISSUE TITLE
Improve extract-patches.sh to autodetect base commit with Darc clones

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1469]
Currently `extract-patches.sh` can only detect base commit hash with submodules:

https://github.com/dotnet/source-build/blob/3085962b9d1c17a6c0b746837b94238257966d0a/extract-patches.sh#L5-L10

We should find a way to have it handle the new Darc approach to improve servicing workflows. The detection enables devs to run `extract-patches.sh` without manually looking up the base commit and copying it over, which is IMO significantly detrimental to the process.

**Comment by crummel** [comment]
[Scrub] Believe this script is obsolete, recommend closing.
