### ISSUE TITLE
Update distro images in CI

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1480]
We're behind the current version of most of our CI image distros on all our branches - these should be updated.

Related: #1465, #1526

**Comment by omajid** [comment]
Is there anything I can do to help? I have some experience with CentOS 8 and/or Fedora 31/32 that might be useful.

@adaggarwal and I were sharing a centos 8-based `Dockerfile` that probably belongs in CI.

**Comment by dagood** [comment]
https://github.com/dotnet/dotnet-buildtools-prereqs-docker is the place to put them if you're up for it. 🙂 There might be some simpler cases covered by this issue as well though--platforms where newer images are already available, but we haven't updated our dependencies yet.

**Comment by adaggarwal** [comment]
For reference, this is the `Dockerfile` : 

```
FROM centos:8

RUN dnf install --setopt tsflags=nodocs --refresh -y \
        dnf-plugins-core &&  \
    dnf config-manager --set-enabled PowerTools  && \
    dnf install --setopt tsflags=nodocs --refresh -y \
        clang \
        cmake \
        compat-openssl10 \
        curl-devel \
        findutils \
        git \
        glibc-langpack-en \
        hostname \
        krb5-devel \
        libicu-devel \
        lldb-devel \
        llvm \
        lttng-ust-devel \
        make \
        openssl-devel \
        python3 \
        tar \
        wget \
        which \
        zlib-devel && \
    dnf upgrade -y && \
    dnf clean all -y
```

**Comment by MichaelSimons** [comment]
[Triage] The build pipeline utilizes floating dotnet-buildtools/prereqs docker images that get rebuilt upon base image updates - https://github.com/dotnet/installer/blob/main/src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml#L12.
