### ISSUE TITLE
Tags are missing for the 2.1.15, 3.0.2, & 3.1.1 release.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#1484]
The 2.1.15, 3.0.2, & 3.1.1 release happened on 1/14/2020.  I don't see the corresponding [Tags](https://github.com/dotnet/source-build/tags) for these releases.  Please create them.

**Comment by crummel** [comment]
Sorry, have been working through CI and other issues.  I've tagged 2.1.15, 3.0.2 and 3.1.1 should happen tonight or later this weekend.

**Comment by crummel** [comment]
These have been tagged, closing this.
