### ISSUE TITLE
SourceBuiltArtifacts tarball should include portable versions of coreclr-tools

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1493]
To better support all distros, SourceBuiltArtifacts should include the portable version of coreclr-tools.

**Comment by dagood** [comment]
(I was writing this too, posting extra info. 🙂)

Currently, we use the system libunwind for CoreCLR nonportable, and always bundle libunwind for CoreCLR portable. This is good for distros where libunwind is available, for various reasons. (https://github.com/dotnet/coreclr/pull/17164.) When it isn't available, the `/p:UseSystemLibraries=false` MSBuild arg enables bundling everywhere.

The problem: we put the non-portable CoreCLR native tools in the previously-source-built tarball. This means that by running a tarball production build on a distro that provides libunwind (RHEL 7), the output previously-source-built tarball isn't compatible with distros that don't provide libunwind (RHEL 8).

To make this scenario easier, we should include the portable build instead. We do, generally speaking, want the tarball to be as cross-distro-compatible as reasonable.
