### ISSUE TITLE
Move packages from reference-only source in tarball to source-build-reference-packages

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1497]
There are 4 packages that are always round-tripped when building a tarball using ildasm/ilasm.  These packages can be moved to source-build-reference-packages targetPacks so they don't need to be rebuilt each time.  The 5 packages are:
- [x] Microsoft.NETCore.App 2.0.0
- [x] Microsoft.NETCore.App 2.1.0
- [x] NETstandard.Library 2.0.0
- [x] NETstandard.Library 2.0.1
- [x] Microsoft.AspNetCore.App.Ref 3.1.2

**Comment by adaggarwal** [comment]
[PR fix](https://github.com/dotnet/source-build-reference-packages/pull/105) for Microsoft.NETCore.App 2.0.0

**Comment by adaggarwal** [comment]
[PR](https://github.com/dotnet/source-build-reference-packages/pull/106) for Microsoft.NETCore.App 2.0.1

**Comment by adaggarwal** [comment]
[PR](https://github.com/dotnet/source-build-reference-packages/pull/107) for Microsoft.AspNetCore.App.Ref 3.1.2

**Comment by adaggarwal** [comment]
[PR](https://github.com/dotnet/source-build-reference-packages/pull/109) for NETstandard.Library 2.0.1

**Comment by adaggarwal** [comment]
[PR](https://github.com/dotnet/source-build-reference-packages/pull/108) for NETstandard.Library 2.0.0
