### ISSUE TITLE
Use consistent SHA1 for source-build-reference-packages for bootstrap CI

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1498]
Currently the source-build-reference-packages which is cloned during the bootstrap build is always the head. This should be changed to use the SHA1 in `versionDetails` for consistency issues. Feb 3.1 had a minor break due to this issue.

**Comment by MichaelSimons** [comment]
[Triage] The repo shas are determines by the installer's Version.Detail.xml graph which source-build-reference-packages is part of..
