### ISSUE TITLE
Patch Removal 5.0

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1501]
- [ ] Merge existing patches into repos to eliminate need for branches in most repos.  
- [ ] Plan and document "branch over patch" for tactical updates for source-build

**Comment by MichaelSimons** [comment]
The work to merge existing patches into the repos was completed as part of ArPow Stage 1.  The tactical update infrastructure is covered by https://github.com/dotnet/source-build/issues/2191.
