### ISSUE TITLE
Move special handling from source-build to repos

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1502]
Move special handling to the repos
- Msft repos: eng/*.props.
- Non-Msft repos: fork the repos, add Arcade wrapper.
  - Can be, but not necessarily, a full blown GitHub fork.
- This refers to odd things like NuGet.config manipulation. Should reduce this over time, but a place to put it that isn't the source-build repo.
- Source-build still orchestrates, but very limited build command per repo.
Contrast to lots of custom ops in each source-build repos/*.proj file + common.

**Comment by MichaelSimons** [comment]
[Triage] this is covered by other ArPow issues.
