### ISSUE TITLE
Input Handling to each repo

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1504]
Move input handling to the repos
- Source-build passes in prebuilts as "BYO".
- PVP, RestoreSources, etc. generated by the repo as needed.
- Doesn't include restore from source-build transport package (sb-transport) or recursive build from source (BfS), but demonstrates the place to put it.

**Comment by MichaelSimons** [comment]
[Triage] This is the consumption of the intermediate packages which is covered by other issues per repo.
