### ISSUE TITLE
Make moving to new versions of submodules easy

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#151]
Updating to the latest version of submodules should be one command.

**Comment by dagood** [comment]
No longer blocked: https://github.com/dotnet/corefx/pull/25208 upgraded BuildTools over the hump.

**Comment by dagood** [comment]
Implemented in https://github.com/dotnet/source-build/pull/254. Now I can use it to hook up auto-submodule-update PRs (https://github.com/dotnet/source-build/issues/269).
