### ISSUE TITLE
Arcade-powered source-build (ArPow)

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1510]
**Situation**
.NET 3.1 is source-build clean, it can bootstrap and be cleanly built with no prebuilt binaries. This was a hard-won effort started in .NET 1.1 .NET Core is now in Fedora, and RHEL, and RHEL-downstream repositories. Yet source-build infra structure is apart from the Microsoft distribution build (aka Official Build) and entails exceptional work to maintain source-buildability. Checks for source-buildability lag far behind repo CI.

**Objective**
Support Linux-first efforts by producing highly maintainable, routine source-builds that are ready for packaging into existing and future distro archives.

**Execution**
To ensure source-buildability as whole, we will move the infrastructure that produces source-built tarballs into the same orchestration mechanisms that produces the binary Microsoft distribution. We intend to place source-buildability checks at the heart of routine dev process by moving the checks into repo PR validation. We want any repo to be built from source using build.sh

**Comment by MichaelSimons** [comment]
[Triage] Repos have been onboarded onto ArPow.  Remaining ArPow work is tracked with specific issues.
