### ISSUE TITLE
Reconcile LLVM-in-Mono build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1514]
Mono pulls a copy of LLVM produced by https://github.com/dotnet/llvm-project.  We will need to either incorporate this repo as well as the Mono changes in runtime or find another solution for these prebuilts.

**Comment by crummel** [comment]
llvm-project is Arcade-ified, so it appears to just bring down an SDK + Arcade + Arcade's default set of tools, and other than that just depend on local cmake and compiler.

**Comment by crummel** [comment]
@directhex notes that this is perf improvements so this isn't strictly required to bring Mono into source-build.

**Comment by MichaelSimons** [comment]
[Triage]  llvm is currently not required in source-build.  Any features that require it (e.g. Native AOT) would drive the need.
