### ISSUE TITLE
Update source-build Docker images with required tooling for Mono

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1515]
This should essentially be changing to use images after these PRs were merged:
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/233
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/245

**Comment by MichaelSimons** [comment]
Closing as [Source-build now has a mono leg](https://github.com/dotnet/sdk/blob/main/eng/pipelines/templates/stages/vmr-build.yml#L237).  I don't believe any other image updates are required.
