### ISSUE TITLE
Investigate libgdi requirements for Mono

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1521]
- Do we have libgdi already?
- Is our System.Drawing busted?
- Can we work around a dependency in Mono?

**Comment by omajid** [comment]
> - Do we have libgdi already?

Several distributions, such as RHEL, don't.

> Is our System.Drawing busted?

Is there a test suite or an interactive application that can help us answer this?

**Comment by wfurt** [comment]
I think libgdi is soft dependency and System.Drawing is considered legacy. All tests should check for presence of libgdi and skip if there is not one on the system.

**Comment by omajid** [comment]
System.Drawing is no longer supported on non-Windows: https://github.com/dotnet/announcements/issues/228

libgdi is only a requirement for using System.Drawing on Linux (which is no longer supported). It's not a hard dependency for Mono.

It seems like there's nothing to do here and we can close this issue?

**Comment by MichaelSimons** [comment]
[Triage] Closing as obsolete.
