### ISSUE TITLE
2.1 auto-update hidden failure 

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1524]
The auto-update command - `.\build.cmd /t:UpdateDependencies /p:UpdateFromManifestFile=$(manifestFile) /clp:v=n` didnt update cli version and required a [manual checkout](https://github.com/dotnet/source-build/pull/1517/commits/820d3c4e97c52862e8901d4cb4c1648af18f2d4a)

**Comment by MichaelSimons** [comment]
[Triage] the auto-update command is no longer applicable to source-build.  Closing as obsolete.
