### ISSUE TITLE
Keep RepoName consistent between releases

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1534]
For the February release, we had CLI -> dotnet-cli and a few others due to the internal repos.  For March we took the auto-update change of URLs which changed casing.  We should keep these consistent between releases.

**Comment by omajid** [comment]
Constantly changing repo names break downstream packaging scripts on every release.

For example, this is what I had to change in Fedora for the Feb release:

https://src.fedoraproject.org/rpms/dotnet3.1/c/afa7f9a38cd8368e41e41309d6bd4fae20a0e3a5?branch=master

Some of this is unavoidable, like changing the package version/release, but some of it seems a little pointless - like changing locations of where stuff we need to install is located .

**Comment by dseefeld** [comment]
This will require an uber-clone change to supply a base name for the repo so they can be consistent between internal and external builds.  Alternately, can we rename the folders on tarball build?  Then a DARC change will not be necessary.

**Comment by omajid** [comment]
@MichaelSimons can we close this issue now? AFAIK, this is now fixed for 6.0 and later.

**Comment by MichaelSimons** [comment]
> @MichaelSimons can we close this issue now? AFAIK, this is now fixed for 6.0 and later.

Yes - thanks for bringing this to my attention.
