### ISSUE TITLE
Add jbevain/cecil (Mono.Cecil official repo) to source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1537]
Right now, we build mono/linker, which has a mono/cecil submodule. In 5.0, the mono/cecil submodule won't be used anymore, and instead the official Mono.Cecil package built by jbevain/cecil and published to the NuGet gallery will be adopted. This means we'll need to add this repository to avoid the prebuilt.

https://github.com/jbevain/cecil/

**Comment by omajid** [comment]
I am going to take a shot at it, but it will be slow as I am learning things.

**Comment by omajid** [comment]
Can't even figure out how to build it :cry: 

I filed https://github.com/jbevain/cecil/issues/693 to get some help

**Comment by marek-safar** [comment]
There was a change in the strategy for .net5 and mono/cecil submodule is still used instead of Mono.Cecil NuGet.

**Comment by omajid** [comment]
Thanks, @marek-safar 

@dagood Sounds like we should close this issue, then?

**Comment by dagood** [comment]
Thanks for the update. @marek-safar, do you know when https://github.com/mono/linker/pull/1477 will end up in a release? rc2, GA?

That PR looks like it'll make our prebuilt disappear once that happens, which is good.

**Comment by marek-safar** [comment]
@dagood mono/linker#1477 should be included in rc2 but last time I checked the update was sitting in dotnet/sdk PRs queue
