### ISSUE TITLE
Publish assets in source-build-reference-packages dir in blob feed

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1544]
After [updating](https://github.com/dotnet/source-build-reference-packages/pull/96) source-build-reference-packages to use arcade publishing, artifacts (`Private.SourceBuild.ReferencePackages.*.tar.gz`) are published in .NETCore general blob feed - `https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/*` 

The problem here is that the main asset directory gets populated with reference packages artifacts. It'll be better if the asset directory has a source-build-reference-packages dir which can be used to hold these artifacts.

**Comment by mmitche** [comment]
That's pretty easy to do:

```
https://github.com/dotnet/runtime/blob/e47e7be443103a1a3a39c29c42fe346095b54942/src/installer/publish/prepare-artifacts.proj#L104​​​​​​​
```

Simply add that RelativeBlobPath element to the items in the itemgroup, or generate the assets in a directory like source-build-reference-packages inside your build.

Btw I would avoid using such a long path if you can.

**Comment by MichaelSimons** [comment]
[Triage] This was done as part of ArPow.
