### ISSUE TITLE
Re-enable bootstrap build in CI in master

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1550]
As part of updating the master branch to 5.0, the bootstrap test build was disabled until the entire product is built. This should be re-enabled once the master branch builds through core-sdk.

**Comment by omajid** [comment]
I was trying out bootstrap locally and it doesn't seem to currently work.

Building runtime using source-build-reference-packages and a previously-built source-build fails with this error for me:

```
21>/home/omajid/fedora-git/dotnet5.0/dotnet-v5.0.100-SDK/previously-built-dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file '/home/omajid/fedora-git/dotnet5.0/dotnet-v5.0.100-SDK/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/artifacts/obj/coreclr/ILVerification/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/omajid/fedora-git/dotnet5.0/dotnet-v5.0.100-SDK/src/runtime.cf258a14b70ad9069470a108f13765e
0e5988f51/src/coreclr/src/tools/ILVerification/ILVerification.csproj]        
```

**Comment by dseefeld** [comment]
@omajid Yes.  That's the same error I'm seeing in my bootstrap tests.  Trying to work through it now.

**Comment by dseefeld** [comment]
PR https://github.com/dotnet/source-build/pull/1949
