### ISSUE TITLE
Bootstrap smoke-tests are not working

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1553]
This appears to be a VSTest version mismatch issue, see binlog here.

**Comment by omajid** [comment]
I just ran into something when building 3.1.103.2 against 3.1.103.2 to fix an unrelated issue:

```
# dotnet new xunit
The template "xUnit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /root/xunittest/xunittest.csproj...
  Restore completed in 182.25 ms for /root/xunittest/xunittest.csproj.

Restore succeeded.

[root@fef9162c6a16 xunittest]# dotnet test
Test run for /root/xunittest/bin/Debug/netcoreapp3.1/xunittest.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0-dev+55e7e45431c9c05656c999b902686e7402664573
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No suitable test runtime provider found for this run.
```

Is this the same "VSTest version mismatch issue" discussed here?

**Comment by crummel** [comment]
It looks pretty similar, could you try with `dotnet test /bl` and post the binlog?

**Comment by omajid** [comment]
[msbuild.binlog.tar.gz](https://github.com/dotnet/source-build/files/4530260/msbuild.binlog.tar.gz)

I generated this on a Fedora rawhide container containing this build of dotnet: https://koji.fedoraproject.org/koji/taskinfo?taskID=43714346

**Comment by MichaelSimons** [comment]
[Triage] Smoke-tests run and pass in CI against the bootstrap leg.
