### ISSUE TITLE
Determine repo build order during "darc clone" for arcade-powered source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1561]
https://github.com/dotnet/source-build/issues/1495 tracks having `darc clone` able to make a synthetically coherent graph and clone it. Once we have that, we still need some external mechanism to determine build order, which is not great for maintenance.

To fix this, `darc clone` should also output some files that can be used to drive the build order. This is a simple way to let us put the ordering info in the repos, in `Version.Details.xml`. And to start off with, they can be overrides in the root repo's `Version.Details.xml`.

(This may mean that dependencies need to mark whether they're circular: if nupkgs from N-1 or previously-source-built are needed, or ref-only. I haven't thought through yet how much help the system needs to figure this out.)

**Comment by dagood** [comment]
> which is not great for maintenance.

But on the flip side, the build graph is also not something that we'd expect to change often. We can probably skip improving this in 5.0.

**Comment by dseefeld** [comment]
Small improvement.  Not needed for 5.0.
