### ISSUE TITLE
Handle non-standard repo URLs during 5.0 "darc clone" 

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1562]
* Some `Version.Details.xml` entries are outdated, with old names of repos such as dotnet/core-sdk (dotnet/installer) and aspnet/aspnetcore (dotnet/aspnetcore). If the repo hasn't been rebuilt since it was last used by the SDK product, there hasn't been any reason/chance to update the dependency checked into the source code.
* During internal builds, some URLs point to dnceng.visualstudio.com and have a different format.

`darc clone` for 5.0 should handle these in some way. I think they are very related (normalizing names, handling it correctly in synthetic coherency resolution, and cloning from the right location) and make sense to implement in the same effort.

**Comment by dseefeld** [comment]
No longer needed because existing support will continue to work.  Related to #1534
