### ISSUE TITLE
Microsoft.AspNetCore.App symbols missing in 3.1 source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1565]
Opened from https://github.com/dotnet/source-build/issues/1564:

> In our source-build .NET Core 3.1 we include `pdb` files for `Microsoft.NETCore.App` dlls.

> Also, we don't seem to have `pdb` files for `Microsoft.AspNetCore.App`, so we may be missing debug info for ASP.NET framework?

**Comment by MichaelSimons** [comment]
This was resolved with https://github.com/dotnet/source-build/issues/3547.
