### ISSUE TITLE
CI for N-1->N and N->N workflow

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1572]
Now that Linux distributions are starting to package source-build, there's a few workflows for using using source-build that don't seem to be tested in our CI here. Maybe these scenarios should be tested here:

1. Using N-1 to build N. For example, using 3.1.102 to build 3.1.103. This is to make sure someone can upgrade from a previous release of source-build to the next release.

    Here's an example of this for 3.1.103: https://github.com/dotnet/source-build/issues/1570

2. Using N to build N. For example, using 3.1.103 to build 3.1.103. This is when distributions notice an issue and want to carry a (hopefully temporary) patch for it while it is merged upstream into, say, `dotnet/runtime`. When these distributions want to build that local fix, they are building N (with local patches) using a previous build of N. 

   Here's an example of this: https://src.fedoraproject.org/rpms/dotnet3.1/pull-request/3. Disabling warnings (to fix build) results in an SDK that fails `dotnet test`.

If these scenarios are already being tested, perhaps any failures in these should block a source-build release?

cc @crummel @dagood @dleeapho @dseefeld @RheaAyase @tmds

**Comment by dseefeld** [comment]
Item 2 above is already tested in CI using the bootstrapping CI leg.  In 3.1.103, this leg didn't get run and so, issues that would have gotten caught were not.

Item 1 requires additional infrastructure to save the results of a previous build and use it for subsequent builds.

**Comment by MichaelSimons** [comment]
This has been implemented in [CI](https://github.com/dotnet/installer/blob/main/src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml) starting in .NET 6.0
