### ISSUE TITLE
Add tests to compare source-built SDK to official SDK

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1579]
These can probably be added to the smoke-testing section of the build.  Also add to the release checklist.

**Comment by omajid** [comment]
My super-quick tests that I used in https://github.com/dotnet/source-build/issues/1123 did:

    diff -u <(cd "${DIR1}" && find | sort) <(cd "${DIR2}" && find | sort)

**Comment by dseefeld** [comment]
#1611 is a start on this.

**Comment by MichaelSimons** [comment]
[Triage] This was implemented in the 6.0 timeframe - https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/SdkContentTests.cs
