### ISSUE TITLE
Add publish scenarios to smoke-tests

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1580]
I think the smoke tests only run framework-dependent "dotnet run" right now. We should include framework-dependent and self-contained publish.

**Comment by omajid** [comment]
Please feel free to adapt from https://github.com/redhat-developer/dotnet-regular-tests/blob/master/apphost-framework-lookup/test.sh, https://github.com/redhat-developer/dotnet-regular-tests/blob/master/restore-with-rid/test.sh and any other interesting looking tests in that repo.

**Comment by dseefeld** [comment]
A main benefit of this is to determine all smoke-test prereqs that are required for these scenarios when performing internal builds.

**Comment by crummel** [comment]
We should also include ASP.NET when we do this.  Clearing triaged to bring it up post-retrospective.
