### ISSUE TITLE
Use source modification to remove internal feeds from nuget.config, not patches

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1594]
Similar to adding sources, we should remove sources from nuget.config as a build step rather than a patch.

This should reduce a source of unconditional patch updating during servicing builds.

**Comment by MichaelSimons** [comment]
Source-build patches no longer are utilized for this.  One mechanism that removes these sources is [here](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/repos/Directory.Build.targets#L198).
