### ISSUE TITLE
Download ref-pkg and previously-source-built tarballs early in CI

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1596]
In dotnet/runtime, there used to be problems cloning the entire repo in each build job. They solved that temporarily by cloning once in an initial build job, then using artifacts to transfer the full repo to each build job.

We could try a similar approach for the tarball download issue https://github.com/dotnet/source-build/issues/1586. At the very least, we would fail *way* earlier in the build so hangs don't cost us as much time.

**Comment by dagood** [comment]
Here's a sample of the hang with the extra logging, note the slow download rate https://dev.azure.com/dnceng/public/_build/results?buildId=736126&view=logs&j=38382a72-42d7-5ed1-69ac-5d05cc6cd998&t=591b10f9-2d15-5229-aff9-fb5707406388&l=4586:

```
  Progress... 00:09:55.0525769, current file size 97.7% (136,970,240 / 140,186,641) ~ 230.18 kB/s
  Progress... 00:10:00.0516971, current file size 98.5% (138,084,352 / 140,186,641) ~ 230.12 kB/s
  Progress... 00:10:05.0502898, current file size 99.3% (139,165,696 / 140,186,641) ~ 230.01 kB/s
  DownloadFileSB.StreamCopyComplete https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/Private.SourceBuild.ReferencePackages.1.0.0-beta.20278.2.tar.gz
/src/build.proj(156,5): error : 600 second timeout exceeded, but download completed after 00:10:09.4736593. Try increasing timeout from 600 if this is acceptable.
```

vs. another job in the same build:

```
  Progress... 00:00:05.0083167, current file size 81.9% (114,782,208 / 140,186,641) ~ 22,918.32 kB/s
  DownloadFileSB.StreamCopyComplete https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/Private.SourceBuild.ReferencePackages.1.0.0-beta.20278.2.tar.gz
  DownloadFileSB.Downloading Complete! Elapsed: 00:00:07.9988882
```

**Comment by asbjornu** [comment]
I experienced the following problem in my build just now:

```
/private/tmp/dotnet-20200808-51698-1ahymh4/build.proj(156,5): error : 600 second timeout exceeded, but download completed after 00:12:23.1734990. Try increasing timeout from 600 if this is acceptable.
```

Upon inspection, the built `.tar.gz` looks fine, so I'm not sure exactly what has gone wrong here and why the build was failed. Anyhow, is there anything I can do to increase the timeout?

**Comment by dagood** [comment]
Yeah, you hit the artificial limit, not a download error. The artificial limit is there to detect when CI hangs but didn't *really* hang, so we can figure out if we can just extend the timeout a little bit more or if something more serious is going on. So far we haven't been successful in finding out why the download speed from Azure fluctuates so dramatically.

But it doesn't make sense to use the artificial limit in non-CI builds. We have https://github.com/dotnet/source-build/issues/1658 tracking removing that.

Disabling it with args is mentioned here: https://github.com/dotnet/source-build/pull/1597. Pass this:
`/p:DownloadSourceBuildReferencePackagesTimeoutSeconds=N/A /p:DownloadSourceBuiltArtifactsTimeoutSeconds=N/A`
to the build command.

**Comment by asbjornu** [comment]
Thanks, @dagood. The parameters seems to have done the job.

**Comment by MichaelSimons** [comment]
[Triage] This has been solved by the introduction of [`prep.sh`](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/prep.sh)
