### ISSUE TITLE
Integrate some distro tests as early warnings

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1600]
We can incorporate some tests to improve early notice of issues.  Especially called out:
- file listings vs MSFT-built SDK
- file sizes vs MSFT-built SDK
- file sizes vs N-1 source-built SDK

References: https://github.com/redhat-developer/dotnet-bunny, https://github.com/redhat-developer/dotnet-regular-tests

**Comment by MichaelSimons** [comment]
This has been superseded by https://github.com/dotnet/source-build/issues/2880.
