### ISSUE TITLE
Error building source-build-reference-packages commit 6e2aee6

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1603]
I am trying to build source-build-reference-packages in Fedora

```
+ ./build.sh --with-sdk /usr/lib64/dotnet --with-packages /usr/lib64/dotnet/source-built-artifacts/Private.SourceBuilt.Artifacts.0.1.0-.tar.gz
 Found SDK version 3.1.103 in /usr/lib64/dotnet
 Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
 Copyright (C) Microsoft Corporation. All rights reserved.
...
"/home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/src/referencePackages/buildReferencePackages.proj" (default target) (1) ->
(Build target) -> 
  /home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/src/referencePackages/src/nuget.common/5.1.0/NuGet.Common.csproj : error NU1101: Unable to find package runtime.native.System. No packages exist with this id in source(s): Local artifacts/bin dir, Source-built packages [/home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/src/referencePackages/buildReferencePackages.proj]
  /home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/src/referencePackages/buildReferencePackages.proj(55,5): error MSB3073: The command "$__DOTNET_CMD pack --output /home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/artifacts/reference-packages/ /home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/src/referencePackages/src/nuget.common/5.1.0/NuGet.Common.csproj /bl:/home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/artifacts/log/nuget.common/5.1.0/NuGet.Common.binlog /p:ArtifactsBinDir=/home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/artifacts/bin/ /p:ArtifactsObjDir=/home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/artifacts/obj/ /p:RepoRoot=/home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/ /nowarn:NU1603,NU1605,NU5125,CS0109,CS0169,CS0618,CS0649,CS3001,CS3002,CS3003,CS3009" exited with code 1.

    3313 Warning(s)
    2 Error(s)

Time Elapsed 00:10:18.85
error: Bad exit status from /var/tmp/rpm-tmp.KE9v3i (%build)
```

[NuGet.Common.binlog.tar.gz](https://github.com/dotnet/source-build/files/4717968/NuGet.Common.binlog.tar.gz)

**Comment by dagood** [comment]
It would be useful to get `/home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/src/referencePackages/src/nuget.common/5.1.0/obj/project.assets.json` file to see why the package is being referenced, from this binlog line (I wonder if we can force/trick MSBuild to embed it in the binlog somehow, considering how useful it is?):

```
Writing assets file to disk. Path: /home/omajid/fedora-git/dotnet-build-reference-packages/source-build-reference-packages-6e2aee66b0e7a01664bde0f6b495bdbb4099f84c/src/referencePackages/src/nuget.common/5.1.0/obj/project.assets.json
```

Looking into what might be special about this package in source-build...

(Link to the copy on the gallery: https://www.nuget.org/packages/runtime.native.System/)

**Comment by omajid** [comment]
[projects.assets.json.tar.gz](https://github.com/dotnet/source-build/files/4718253/projects.assets.json.tar.gz)

**Comment by dagood** [comment]
I have data for this package in a 3.1.104 tarball at `./packages/reference/staging/runtime.native.system`, but I'm not sure how that translates to a source-build-reference-packages build... taking a look, thanks.

**Comment by dagood** [comment]
The dependency is fairly direct:
* NuGet.Common.csproj (netstandard2.0) ->
  * `System.Diagnostics.Process 4.3.0` ->
    * `runtime.native.System 4.3.0`

So I think the question is why `runtime.native.System` was available before and isn't anymore.
@dseefeld @crummel what do we expect to have available to the build at this point?

**Comment by dagood** [comment]
@dseefeld noted offline that his build doesn't have the `System.Diagnostics.Process` `runtimeTargets` section in the project.assets.json, and I *think* that indicates `System.Diagnostics.Process` is the "real" package rather than a ref package. I see in the assets file it's using a home directory packages dir, is it possible it's dirty?

```
  "packageFolders": {
    "/home/omajid/.nuget/packages/": {}
  },
```

(Possible fix: make source-build-reference-packages use a local package cache by default.)

**Comment by omajid** [comment]
>  I see in the assets file it's using a home directory packages dir, is it possible it's dirty?

Ugh. I think you are right. I am working on multiple things at a time, so it's very likely something else is polluting the cache. I am retrying with a clean cache and no other dotnet programs running.

**Comment by omajid** [comment]
I can confirm that cleaning my local nuget caches did the trick. Thanks for root-causing it so quickly!

I am going to close this issue since #1605 handles the remaining pain points.

**Comment by dagood** [comment]
Phew, glad that was it. 😄

I think ref-ness validation (https://github.com/dotnet/source-build/issues/1599) could be feasible with pretty good value in SBRP... there's fairly global knowledge that every dependency should be ref-only (so getting the right knowledge isn't likely to be a new source of bugs), and having the system point this out rather than kind of guessing based on project.assets.json would fast-track resolution.
