### ISSUE TITLE
Fix source-build infrastructure issues that prevent clean merges

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1608]
This issue includes anything that prevents clean merges between AzDo and GitHub repos, including:
- ProdCon feed authentication issues
- Missing text-only nupkgs
- Missing smoke-test-prereq nupkgs
- Consistent repo names (covered in https://github.com/dotnet/source-build/issues/1534)
- Consistent repo URLs
- Occasionally missing upstream hashes - this may just be something we need to bug upstream about when it happens

**Comment by MichaelSimons** [comment]
This is no longer an issue in .NET 6.0 +
