### ISSUE TITLE
Add versioning to source-build-reference-packages

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1612]
This can assist with determining whether a given set of ref packages has required changes.

**Comment by dseefeld** [comment]
SBRP should have it's own versioning scheme, not tied to SDK versions or build.  Also, tags should be included in the repo for each version.

**Comment by MichaelSimons** [comment]
Not sure what the purpose is of this.  With ArPow, SBRP is included in the tarball build for a specific sha.  SBRP also produced a versions source-build intermediate file.
