### ISSUE TITLE
Move source-build-reference-packages tooling into the repo

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1622]
There is some external tooling to generate the projects that we put into source-build-reference-packages (IL, text-only, and GenAPI-based). These tools should be put in the repo itself for better maintainability.

**Comment by omajid** [comment]
I believe this was fixed with https://github.com/dotnet/source-build-reference-packages/pull/294 ?

Also, this issue seems like a duplicate of https://github.com/dotnet/source-build/issues/2609 ?

**Comment by MichaelSimons** [comment]
The one piece of tooling that was not ported is the IL source generator used to generate the targeting packs.  This issue should either be repurposed for that or a new issue should be opened.

**Comment by crummel** [comment]
Opened https://github.com/dotnet/source-build/issues/3091 to move the targeting pack tooling.
