### ISSUE TITLE
PackageVersions.props in the source build tarball is in an arch-specific location

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1629]
A source-build tarball contains a `PackageVersions.props` file. This file doesn't seem to have anything architecture-specific:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="SourceBuiltPackageVersions.props" Condition="Exists('SourceBuiltPackageVersions.props')" />
  <Import Project="GennedPackageVersions.props" Condition="Exists('GennedPackageVersions.props')" />
</Project>
```

But it's located in an architecture-specific location.

```
artifacts/obj/x64/Release/PackageVersions.props
```

In fact, it's the only file in that location when prebuilts are removed:

```
$ tar tf dotnet-v3.1.105-SDK.tar.gz | grep '\/artifacts'
dotnet-v3.1.105-SDK/artifacts/
dotnet-v3.1.105-SDK/artifacts/obj/
dotnet-v3.1.105-SDK/artifacts/obj/x64/
dotnet-v3.1.105-SDK/artifacts/obj/x64/Release/
dotnet-v3.1.105-SDK/artifacts/obj/x64/Release/PackageVersions.props
```

Building this tarball fails on arm64. An arm64 build looks for a `artifacts/obj/arm64/Release/PackageVersions.props` instead (note `arm64` instead of `x64`). I can work around it by copying the file over into the expected location. That makes everything work as expected.

Is it safe to assume this file will stay the same for all architectures?

Is there any reason this file really needs to be placed in an architecture-specific location that's specific to x64?

**Comment by omajid** [comment]
cc @crummel

**Comment by crummel** [comment]
Triage:
We should be able to generate this file and just leave it out of the tarball entirely.

**Comment by omajid** [comment]
This is no longer an issue with .NET 7.

```
$ tar tf dotnet-v7.0.100-rc.2.22477.23.tar.gz | grep PackageVersions.props
```
