### ISSUE TITLE
Next steps on SDK comparison testing

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1630]
@dagood added some next steps to improve our SDK comparison testing here: https://github.com/dotnet/source-build/pull/1611#pullrequestreview-433453313.

---

1. Add a baseline diff vs. last release.
2. Filter the results such that any output that makes it past the filter is something that we need to take action on. (E.g. scenario impacting.)
3. *(Out of scope) Eliminate differences between Microsoft and source-built SDKs.*

**Comment by crummel** [comment]
Triage: @dagood to split this issue up.

**Comment by dagood** [comment]
I've edited the description to track the noise-reduction improvements here (improvements to the testing itself), and opened a couple new issues for orthogonal tasks:
* [Support internal SDK download for Microsoft SDK vs. source-built SDK file list diff smoke-test #1631](https://github.com/dotnet/source-build/issues/1631)
* [Add Microsoft SDK vs. source-built SDK file list diff smoke-test review to release checklist #1632](https://github.com/dotnet/source-build/issues/1632)

**Comment by MichaelSimons** [comment]
This test has been implemented [here](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/SdkContentTests.cs)
