### ISSUE TITLE
[SBRP dev/source-build-5.0] Official build binlog is surprisingly large

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1633]
The source-build-reference-packages official build binlog for arcade-powered source-build (5.0) is huge: **236 MB**, and opens slowly: **3 minutes** (on a strong machine from NVMe M.2). The build itself only takes ~8 minutes so this is interesting.

(This is the inner binlog that does building and source-built nupkg packing. The outer binlog that generates the intermediate nupkg is < 1 MB.)

To break this down a bit I ran a few local builds using a warm package cache and only a subset of the projects. Time/Size *might* be interesting, but not sure if it really points to something:

  | Size (MB) | View Time (s) | Time/Size
-- | -- | -- | --
all.binlog | 140 | 180 | 1.29
refpkg.binlog | 92 | 55 | 0.60
targetingpack.binlog | 47 | 44 | 0.94
textonly.binlog | 0.8 | ~1 | ~1.25

This may be inevitable when we're building a large number of small projects. It would make sense that this ends up running a *lot* of SDK targets very quickly rather than spending time compiling code.

---

The download and load times don't make it impossible to diagnose issues, just take a while... and since it's caused by the inner build, not the outer infra, it isn't something that I'd expect to see broadly with the 5.0 plans. Therefore, I don't think this is a high priority.

**Comment by dseefeld** [comment]
Not a blocking issue. If it causes issues in the future, this can be re-opened.
