### ISSUE TITLE
[SBRP] Rearrange source-build-reference-packages branches: fork 3.1

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1634]
Currently, SBRP has:
* `master` branch, flows into source-build `release/3.1` and `master`.
* `dev/source-build-5.0` branch, flows nowhere yet. The references it builds are the same as `master`, but the infra and transport format are quite different.

Ideally, we could continue only having a `master` branch in SBRP, because the IL/C#/text-only source code isn't expected to be different for each branch. However, infrastructure and tooling SDK differences could make this infeasible. Moving to two branches is the simple answer:

* `master` => `release/3.1`
* `dev/source-build-5.0` => `master`

I think we should probably avoid doing this until the work to get a source-built 5.0 preview is complete (https://github.com/dotnet/source-build/issues/1500), to avoid disrupting it with e.g. broken Maestro++ subscriptions.

---

@omajid @crummel @dseefeld will changing the source branch from `master` => `release/3.1` have an impact on Fedora builds (or other infra)? If we start tagging our 3.1 releases (https://github.com/dotnet/source-build/issues/1612) will that mitigate effects? Or does it always build based on commit hash, so this is irrelevant? 🙂

**Comment by dagood** [comment]
We can do this incrementally. I've started by pushing a `release/3.1` branch that points to SBRP `master` at this point.

**Comment by omajid** [comment]
> will changing the source branch from master => release/3.1 have an impact on Fedora builds (or other infra)? If we start tagging our 3.1 releases (#1612) will that mitigate effects? Or does it always build based on commit hash, so this is irrelevant?

The current Fedora builds are based off of commit ids. So it doesn't really matter if that's the `master` branch or `release/3.1`. 

Tagging and doing official source tarball releases is preferred by Fedora, though.

**Comment by dagood** [comment]
This is complete. The impact on dotnet/source-build is minimal because subscriptions are based on channels, not branches, so I just had to adjust them on the SBRP side.
