### ISSUE TITLE
2.1 servicing: Consume Microsoft.DotNet.Web.* template text-only prebuilts in a way that is stable

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1637]
Recently, this prebuilt is updated in the baseline for servicing events: https://github.com/dotnet/source-build/pull/1617/files#diff-12e0b639243090fbbbc957767a1d9398

```diff
-    <Usage Id="Microsoft.DotNet.Web.ItemTemplates" Version="2.1.18" />
-    <Usage Id="Microsoft.DotNet.Web.ProjectTemplates.2.1" Version="2.1.18" />
-    <Usage Id="Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1" Version="2.1.18" />
+    <Usage Id="Microsoft.DotNet.Web.ItemTemplates" Version="2.1.19" />
+    <Usage Id="Microsoft.DotNet.Web.ProjectTemplates.2.1" Version="2.1.19" />
+    <Usage Id="Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1" Version="2.1.19" />
```

We should eliminate the need to update the baseline every time. For example, we could:
1. Figure out how to build these.
2. Special-case this package to not be detected, or more minimally, replace the patch version with a `*` so the baseline remains the same.
3. Update the text-only prebuilt detection to understand and allow this package.

**Comment by dagood** [comment]
> 3\. Update the text-only prebuilt detection to understand and allow this package.

This system actually is catching it, I just forgot that the online prebuilt baseline is for the production build, where it's being restored. The other options are still valid, in particular (2).

**Comment by dagood** [comment]
Also check for this with updates to the N-1 SDK, there may be unstable package references there too.

**Comment by MichaelSimons** [comment]
All required templates are produced by source-build.  These prebuilts have been eliminated in recent versions.
