### ISSUE TITLE
Reconcile OSName in source-build with repo usage

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1639]
An issue with 5.0 building on OSX turned out to be that we were setting OSName incorrectly in the installer build. I think the issue may exist in 3.1 as well.  OSName is checked in some of the repos as "$(OSName)" == "osx" but we're setting it to something like osx.10.14 in this code: https://github.com/dotnet/source-build/blob/05e2a037c5bfcfc718ff2b76494a91bbe24eac68/repos/cli.proj#L5-L7  That same code was in installer.proj in 5.0 (copied over).  This was causing the check to fail in the installer repo and it was setting CreateCrossgenSymbols to true here: https://github.com/dotnet/installer/blob/efcb9c319c41105e769afcafbd6c8860f7411f25/src/redist/targets/Crossgen.targets#L107-L109  

The fix in 5.0 was to update this line: https://github.com/dotnet/source-build/blob/05e2a037c5bfcfc718ff2b76494a91bbe24eac68/repos/cli.proj#L7 to the following:

`<OSNameOverride>$(OverrideTargetRid.Substring(0, $(OverrideTargetRid.IndexOf("-"))))</OSNameOverride>`

**Comment by MichaelSimons** [comment]
[Triage] This code has been refactored some since it was originally opened.  The OSX issue is N/A until https://github.com/dotnet/source-build/issues/3034 is implemented in .NET 8.
