### ISSUE TITLE
Remove sdk patch in master branch for 5.0 to fix OmniSharp compatibility

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1640]
For 5.0 a patch was added to sdk to not build the following projects for net472:
 .../Microsoft.DotNet.Cli.Utils.csproj
 .../Microsoft.NET.Build.Extensions.Tasks.csproj
 .../Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj

This patch should be removed and usage of a targeting pack for these projects should be investigated.

See patches/sdk/0005-Don-t-build-for-net472.patch

**Comment by dagood** [comment]
PR in progress: https://github.com/dotnet/source-build/pull/1928

**Comment by dagood** [comment]
Completed by https://github.com/dotnet/source-build/pull/1928.
