### ISSUE TITLE
Darc clone in existing source-build directory doesn't fetch new tags, causing failure to find commits

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1642]
An existing clone wasn't able to fetch the commit associated with this tag, `56c0dbb`:

https://github.com/dotnet/aspnetcore-tooling/tree/v5.0.0-preview.4.20251.2

Log: https://gist.github.com/omajid/b1c179fa62be8aabec19acd33f30f54b

That commit doesn't exist in a branch, only the tag. ASP.NET has a convention of deleting preview branches, which *should* be fine for us, as long as they have a tag. We depend on this working for other reasons (using tags to make commits available to source-build) so this should be investigated/fixed.

I think that Darc's fetch refspec (based on that log) is limiting itself to branches (heads) since it doesn't include `refs/tags/*`:

```
  Fetching +refs/heads/*:refs/remotes/c77ff56f-05f7-4147-8621-47c675e794e2/* from[...]
  Fetching +refs/heads/*:refs/remotes/origin/* from[...]
```

Workarounds are to fix it manually using git commands, clean `.git/modules/...`, or use a fresh source-build clone.

**Comment by crummel** [comment]
This could also be a pretty straightforward Darc improvement; I wouldn't expect the number of tags to cause perf issues like the PR fetch did.

**Comment by crummel** [comment]
GitHub server also now supports fetching unreachable commits - check if LibGit2Sharp does as well.

**Comment by MichaelSimons** [comment]
Darc clone is no longer being.  This issue is obsolete.
