### ISSUE TITLE
Darc clone sets up .git files containing absolute paths, breaking Docker + host scenarios like patch fixup

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1643]
My normal workflow is to build inside a short-lived Docker container. Darc clone creates a `.git` file in each repo to point to an absolute path somewhere in the source-build `.git` dir for data. This makes the repos unusable on my host since e.g. `/work/.git/modules/...` isn't where the files are anymore. After manually fixing up the `.git` files by making them relative, it works fine.

Changing to a relative directory is the obvious solution. This may need changes in Darc to accommodate. (I don't think it's terrible to use absolute paths though. My understanding is it's common to find absolute paths in build artifacts.)

The reason I run into this scenario is that I want to fix up patches only on demand. That is, only when a "real" local containerized build fails due to the patches not applying. When that happens, I want to use the power of my host machine (newer Git, more tooling installed, etc.) to immediately start fixing up the patches.

**Comment by dseefeld** [comment]
Absolute paths is allegedly  a limitation libgit2sharp.  Scenario can be accomplished using CloneOnly target.  @dagood Please check and file a new issue if it doesn't work.
