### ISSUE TITLE
Re-enable package-source-build in 5.0 for Private.SourceBuilt.Artifacts generation

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1647]
https://github.com/dotnet/source-build/blob/41f4a2a61303617bf0823fa0ff42e388aba8266e/repos/known-good.proj#L70

@omajid hit this in https://github.com/dotnet/source-build/issues/1645: `Private.SourceBuilt.Artifacts.*.tar.gz` is missing.

@dseefeld @crummel

**Comment by dseefeld** [comment]
Fixed with #1759
