### ISSUE TITLE
Use targeting packs to build net4xx rather than removing from TargetFrameworks using patches

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1650]
Currently there are patches in various repos to stop building net4xx target frameworks.

https://github.com/dotnet/source-build/blob/master/patches/roslyn/0001-Conditionally-remove-net472-from-TargetFrameworks.patch
https://github.com/dotnet/source-build/blob/master/patches/arcade/0006-Don-t-build-for-net472-when-building-from-source.patch
...

I think we can use the SBRP-built  [microsoft.netframework.referenceassemblies.net472/1.0.0-preview.2](https://github.com/dotnet/source-build-reference-packages/tree/a9cf71cddf11fa52d4e1379a470561da095d31bb/src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net472/1.0.0-preview.2) to build this target framework as normal. This should remove a persistent source of patches across many repos if we can do this.

**Comment by dseefeld** [comment]
Some repos assume that source-build means to not build for .NET Framework.

**Comment by dagood** [comment]
This also breaks OmniSharp because it tries to load build tasks on .NET Framework with Mono.

**Comment by MichaelSimons** [comment]
Removal of Net4* targeting is being tracked with https://github.com/dotnet/source-build/issues/3014.
