### ISSUE TITLE
Migrate smoke tests to a testing framework

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1654]
Right now, `smoke-test.sh` is a shell script that runs some scenarios and emits some diagnostic output and logs. It's grown over time and is not simple. The main complexities IMO:
* scenario combinations and various incoming args to enable/disable certain subsets
* logging modes
* the output capture + scan for "Press Ctrl+C to shut down"
* successfully terminating subcommands in case of failure.

Up until recently, tests have been some combo of `dotnet new; dotnet restore; dotnet run; dotnet publish` and mostly just look for a zero exit code, but now we're going after some extra validation:
* Add tests to compare source-built SDK to official SDK #1579
* Integrate some distro tests as early warnings #1600
* Add verification of output version to source-build testing #1610

I think we should use a testing framework to manage the complexity. I'd also expect some broader benefits, like better logging/reporting and getting status of every test even if an "early" one fails.

---

A .NET managed testing framework would be familiar for everyone working on source-build. It would also make it easy to maintainably implement more advanced things like baseline tests for SDK content and file size diffs. (In particular, we already did baseline-based validation for prebuilt lists in managed code.)

We should also consider testing frameworks that might be more popular for distro package maintainers in particular.

**Comment by dseefeld** [comment]
Discussion during Triage: Is the current smoke test just a smoke test and other tests that we need to add should be included as other integration tests?

**Comment by MichaelSimons** [comment]
Implemented in release/6.0.1xx - closing.
