### ISSUE TITLE
Only use timeout for SBRP + previously-source-built in CI builds

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1658]
In https://github.com/dotnet/source-build/pull/1597 we introduced a timeout and more logging to the file download task, to try to narrow down slow download times in CI. (Sometimes it got a fast connection, sometimes it got a slow connection.) However, on a local machine, the timeout is not useful and can cause the build to fail even if the person running the build is ok with it taking a while.

https://github.com/dotnet/source-build/blob/a0438857c6dcd46ee5524a5484118655a4bb1060/build.proj#L152-L167

**Comment by omajid** [comment]
:+1:  I run into this error all the time on slower machines or machines with a slow network connection. I dont care too much if the download takes a while. But when the download taking too long makes an otherwise fine build fail, that frustrates me a lot.

**Comment by dagood** [comment]
Fixed in https://github.com/dotnet/source-build/pull/1799 (3.1) and https://github.com/dotnet/source-build/pull/1800 (master).
