### ISSUE TITLE
Add parameter to use external cache dir for SBRP and previously-source-built tarballs

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1659]
These files can unpredictably take a very long time to download, which is particularly bad in source-build since we need to do fresh builds all the time. It would speed up local builds quite significantly to have an easy way to cache the files in a directory that won't be wiped by `git clean -xdf` or similar commands.

We might just need to:
* Change the download to skip if the file exists.
* Make sure the download writes the stream to a temp file, not the final (to avoid cancellation problems).
  * Ideally we'd also have a checksum, but we don't have a reasonable way to check these in with auto-updates AFAIK. 😕
* Make sure overriding the shared definition of `ExternalTarballsDir` works.
* Provide a shortcut to override `ExternalTarballsDir` with, say, `$HOME/.dotnet-source-build/external-tarballs/`?

**Comment by MichaelSimons** [comment]
SBRP is now built as part of source-build.  Prep.sh also [provides a means](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/prep.sh#L59) for devs to cache the previously-source-built artifacts locally.

**Comment by MichaelSimons** [comment]
Closing per my previous comment.
