### ISSUE TITLE
Add arcade-powered source-build to MS repos not using Arcade

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1661]
Counterpart to **Source-build non-MS repos #1509**

Some repos aren't on Arcade, but _are_ in dependency flow and are in the `Microsoft` or `dotnet` organization. This means we won't have to fork them, but getting them on Arcade may not be feasible given the timeframe and risk.

The arcade-powered source-build plan is to add an Arcade wrapper into these repos that internally just calls the existing build infra. The Arcade wrapper contains the logic to provide the correct args to the build (same general strategy as before) and produce intermediate nupkgs using shared tooling. The wrapper can then be included in the AzDO job that publishes to dependency flow and in PR validation.

* https://github.com/NuGet/NuGet.Client
* ...?

There is also one that isn't in dependency flow or on Arcade:

* https://github.com/aspnet/common => https://github.com/dotnet/extensions/tree/servicing/1.0.x
  * Potentially used by NuGet.Client for a command line implementation, might be removable.

**Comment by MichaelSimons** [comment]
This is being tracked at a per repo basis.  The only repo not on arcade is NuGet - https://github.com/dotnet/source-build/issues/2069
