### ISSUE TITLE
Update docker images when cmake changes are in source-build

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1665]
https://github.com/dotnet/runtime/pull/39044 Implements a downgrade of CMake to a minimum version of 3.6.2.  As part of this change, a Centos7 docker image was added that includes CMake 3.6.2 and removes the source-build specific images that upgraded the CMake version for Centos8, Debian Stretch and Ubuntu 18.04.  https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/344

When the runtime changes for CMake are in source-build, the docker images used for CI builds can be reverted back to non-source-build specific versions with the default versions of CMake and the Centos7 image can be update to the image added in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/344

**Comment by MichaelSimons** [comment]
Source-build utilizes the shared dotnet-buildtools-prereqs images with a floating tag.  If updates are made, source-build will automatically pick-up the changes.
