### ISSUE TITLE
[release/3.1] Evaluate passing AlwaysPackEvenIfNotServicing=true to Core-Setup for next servicing release

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1668]
Core-Setup is moving to a package-granular release strategy of its managed packages with https://github.com/dotnet/core-setup/pull/9049. I think we probably need to always build those in source-build so that downstream repos can consume the binaries even when they won't be shipped in the next Microsoft build.

A flag `AlwaysPackEvenIfNotServicing` is in that PR to let us disable the granularity. I believe this will probably be needed to avoid adding a prebuilt.

Another thing to consider is whether we need to downgrade the produced package's version to match the last-released Microsoft package.

**Comment by dagood** [comment]
> Another thing to consider is whether we need to downgrade the produced package's version to match the last-released Microsoft package.

This is somewhat tied to https://github.com/dotnet/source-build/tree/release/3.1/Documentation/planning/nongranular-servicing-readiness, but for the time being, the default is to match the Microsoft build and we should have this downgrade.

**Comment by dseefeld** [comment]
This flag was implemented in the 3.1.107 release here: https://github.com/dotnet/source-build/pull/1702/
We chose not to downgrade the package's version as testing didn't uncover any issues with the version difference.  This does introduce a difference between the source-built build and the "official" build WRT the version of the assemblies built with this flag. 
@dagood can this be closed?

**Comment by dagood** [comment]
Yep, thanks. This issue just tracks the flag to avoid a prebuilt, and https://github.com/dotnet/source-build/issues/1691 tracks doing further validation that enabling this flag without fixing the version difference hasn't hurt any scenarios.
