### ISSUE TITLE
Remove duplicated auth inputs in internal authentication infrastructure

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1673]
The entrypoint for NuGet feed configuration is in `build.sh`, and depends on environment variables:

https://github.com/dotnet/source-build/blob/ea2042c6a31b4a83e136505e6cb3010b461da631/build.sh#L105-L106

But you also need to pass your PAT in as `AzDoPat` for this code:

https://github.com/dotnet/source-build/blob/ea2042c6a31b4a83e136505e6cb3010b461da631/Directory.Build.targets#L38-L40

A simple fix here would be to default `AzDoPat` to `internalPackageFeedPat` if it exists. This way, the env var would properly set up both values, but you could still configure two PATs with different scopes if you really wanted to.

An alternative (or complementary?) fix would be to have a new `build.sh` parameter that sets this up.

**Comment by MichaelSimons** [comment]
Closing as obsolete with the VMR.
