### ISSUE TITLE
Remove hard-coded internal feed list from build.sh

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1674]
The NuGet feed configuration is in `build.sh`, and hard-codes the set of feeds to auth against:

https://github.com/dotnet/source-build/blob/ea2042c6a31b4a83e136505e6cb3010b461da631/build.sh#L105-L115

As mentioned, these should be read from the NuGet.Config, with the odd extra one also added in.

We could potentially reuse some of this Arcade eng/common code (although I don't think it's factored in a usable way right now), or make a copy for ourselves and tweak it to what we need:

https://github.com/dotnet/source-build/blob/ea2042c6a31b4a83e136505e6cb3010b461da631/eng/common/internal-feed-operations.sh#L50-L57

The extra feed not in the NuGet.Config is injected in official builds by an Arcade script: https://github.com/dotnet/arcade/blob/6c537df8e5a2be916202d4f03c63e24fdec33c7b/eng/common/SetupNugetSources.ps1#L140

**Comment by MichaelSimons** [comment]
The feedlist has been removed from build.sh starting in .NET 6.0
