### ISSUE TITLE
Fix internal authenticator install script to work in Ubuntu 18.04 CI

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1675]
This script is used to set up the CI machine (docker container) with the prerequisites to install the AzDO NuGet authentication plugin:

https://github.com/dotnet/source-build/blob/ea2042c6a31b4a83e136505e6cb3010b461da631/eng/install-nuget-credprovider.sh#L9-L21

This set of commands fails on Ubuntu 18.04. The available `curl` requires `libcurl4`, which is in conflict with the already-installed `libcurl3`. Uninstalling `libcurl3` to let `curl` + `libcurl4` install causes the CoreFX build to break. This is as far as I investigated.

(We should consider setting up (or using) a Docker image that has this all set up properly in the first place, but the value of making big changes here is questionable. It *may* become a reliability (flakiness) problem, or suddenly block us when 18.04 goes EOL and the feeds get turned off. (But why are we on 18.04 then?) For background, dotnet/core-setup and dotnet/runtime use an almost identical script.)

**Comment by omajid** [comment]
> Uninstalling libcurl3 to let curl + libcurl4 install causes the CoreFX build to break

This sounds like a bug, somewhere (probably corefx?). Fedora has one version of curl, and .NET Core (including corefx) works just fine. RHEL 7 has a much older curl, and .NET Core works there too. Both `libcurl3` and `libcurl4` packages have a recent version of the curl code. Perhaps someone more familiar with Debian/Ubuntu can take a look at this?

**Comment by dagood** [comment]
I went back and found the logs for what I ran into:

```
    -- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
    CMake Error at System.Net.Http.Native/CMakeLists.txt:5 (message):
      !!! Cannot find libcurl and System.Net.Http.Native cannot build without it.
      Try installing libcurl4-openssl-dev (or the appropriate package for your
      platform) !!!
    
    
    -- Configuring incomplete, errors occurred!
    See also "/src/artifacts/src/dotnet-corefx.73aa947bfae18d576fc2fe69fb9c3f7839decd93/artifacts/obj/native/netcoreapp-Linux-Release-x64/CMakeFiles/CMakeOutput.log".
    See also "/src/artifacts/src/dotnet-corefx.73aa947bfae18d576fc2fe69fb9c3f7839decd93/artifacts/obj/native/netcoreapp-Linux-Release-x64/CMakeFiles/CMakeError.log".
    Failed to generate native component build project!
  /src/artifacts/src/dotnet-corefx.73aa947bfae18d576fc2fe69fb9c3f7839decd93/src/Native/build-native.proj(36,5): error MSB3073: The command ""/src/artifacts/src/dotnet-corefx.73aa947bfae18d576fc2fe69fb9c3f7839decd93/src/Native/build-native.sh" x64 Release Linux outconfig netcoreapp-Linux-Release-x64 -portable" exited with code 1.
##[error]/src/artifacts/src/dotnet-corefx.73aa947bfae18d576fc2fe69fb9c3f7839decd93/src/Native/build-native.proj(36,5): error MSB3073: The command ""/src/artifacts/src/dotnet-corefx.73aa947bfae18d576fc2fe69fb9c3f7839decd93/src/Native/build-native.sh" x64 Release Linux outconfig netcoreapp-Linux-Release-x64 -portable" exited with code 1.
```

I didn't try installing `libcurl4-openssl-dev` like it suggested, seems reasonable though and should be easy to test out for a new Docker image.

**Comment by MichaelSimons** [comment]
install-nuget-credprovider.sh is no longer part of source-build.  CI authentication is handled via common arcade script as illustrated [here](https://github.com/dotnet/installer/blob/main/src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml#L58)
