### ISSUE TITLE
Investigate smoke-test-prereqs generation: should it always contain all packages used?

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1677]
For internal builds, I implemented this to make sure smoke-test can still run when authenticated feeds aren't available and packages aren't pushed to anonymously accessible feeds yet:

https://github.com/dotnet/source-build/blob/ea2042c6a31b4a83e136505e6cb3010b461da631/eng/SourceBuild.Tarball.targets#L236-L241

We should consider making the non-internal build work the same way: just keep all packages used by smoke test always. This simplifies both tarball creation and smoke-testing by removing a difference in behavior between internal and non-internal builds.

**Comment by dseefeld** [comment]
There is value in eliminating these in public builds to ensure that it works with the public nuget packages.  The way packages are captured for internal builds assumes that if they're downloaded by smoke-tests, then they are from the official build, but they may be from source-build.
