### ISSUE TITLE
Look into using official Fedora packages for our Fedora CI

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1678]
This could also be an additional leg - we could add Fedora Rawhide using the Fedora-built source-build-reference-packages and additional Fedora-built tooling rather than using the Microsoft Fedora docker-build-prereqs image that includes binaries that cannot ship in Fedora.

**Comment by dseefeld** [comment]
Using the N-1 versions of the SDK and SBRP from Fedora may be an option that is more easily maintainable without using their build spec.  This would validate that we can build with these without needing the Fedora infra.  The N-1 versions should be included in a text file in the source-build repo.

**Comment by MichaelSimons** [comment]
Source-build CI does a bootstrap build [here](https://github.com/dotnet/installer/blob/main/src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml#L93).  Note this is only done for one version of Fedora - not every distro/version tested in CI.
