### ISSUE TITLE
Where will "scripts/bootstrap/buildbootstrapcli.sh" go in 5.0?

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1681]
The current arcade-powered source-build plan for 5.0 means dotnet/source-build will be for servicing 3.1/2.1, obsolete for new versions. This means `scripts/bootstrap/buildbootstrapcli.sh` for 5.0 needs a new place to live.

dotnet/installer is the obvious choice. It'll be the tip repo where we produce tarballs, and it may end up with other "extra" source-build infra in it if it doesn't make it into the dotnet/arcade toolset.

**Comment by omajid** [comment]
IIRC, @janvorli added this script to this repo, initially. Any thoughts, @janvorli ?

**Comment by janvorli** [comment]
I am sorry for a late response, I was OOF most of the time during last two weeks.  The current script depends heavily on the separate coreclr, corefx and core-setup repos and updating it for 5.0 will require substantial change. 
Is this script being currently used by source build?

**Comment by dagood** [comment]
IIRC it may be used to create a bootstrapped prebuilt SDK for an OS or architecture that .NET Core doesn't officially support, then that prebuilt bootstrap can be run through source-build to create a non-prebuilt SDK to perhaps put in a distro. This isn't something that we exercise in CI or anything like that, so there's no reason from the source-build point of view to put the script in a particular place.

(It would be nice to make it obsolete entirely by making bootstrapping just another way you can build with the common infra, but that isn't a current goal of the source-build team.)

**Comment by janvorli** [comment]
Is sounds like putting a new version of that script for 5.0 into dotnet/installer would make sense.

**Comment by dagood** [comment]
Thanks, closing discussion then, and opened https://github.com/dotnet/source-build/issues/1694 to track the script.
