### ISSUE TITLE
Improve setup and production build documentation for servicing releases on RHEL7 + RHEL 8

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1682]
We have some internal docs on how to get a basic RHEL machine, but not much on how to build the tarball on it. There is a lot of assumed knowledge here in the servicing process. A few things in particular to document:

* How to get the developer subscription for access to compilers, etc.
* Make sure 30 GB of space is available.
* Make sure `/tmp/` in particular has space.
* How to set up the environment to use the right compiler during the native builds.
* Sequence of commands to run to emulate CI and produce a viable tarball.

**Comment by omajid** [comment]
Some comments:

- Is https://developers.redhat.com/rhel8 the right starting point for item 1?

- For item 4, you can `curl -sSL https://git.centos.org/rpms/dotnet3.1/raw/c8/f/SPECS/dotnet3.1.spec | grep '^BuildRequires:' | awk '{ print $2 }'` to get the list of native dependencies we use for RHEL 8 and CentOS 8.

  - RHEL 7 and CentOS 7 are a bit more of a mess. You can see it all in the [CentOS git](https://git.centos.org/rpms/rh-dotnet31-dotnet/blob/c7-dotnet/f/SPECS/dotnet.spec) though: https://git.centos.org/rpms/rh-dotnet31-dotnet/raw/c7-dotnet/f/SPECS/dotnet.spec

- What is a "viable" tarball? :thinking:

**Comment by dagood** [comment]
> * Is https://developers.redhat.com/rhel8 the right starting point for item 1?

Yeah, we have this figured out, but wasn't documented.

> * For item 4, you can `curl -sSL https://git.centos.org/rpms/dotnet3.1/raw/c8/f/SPECS/dotnet3.1.spec | grep '^BuildRequires:' | awk '{ print $2 }'` to get the list of native dependencies we use for RHEL 8 and CentOS 8.

Nifty. :+1:

> * What is a "viable" tarball? 🤔

Just one that we can potentially send out. I think the only *likely* reason one wouldn't be viable is if it still had the smoke-test-prereqs inside it--there's logic for that in the CI yaml that has to be replicated locally.

**Comment by dagood** [comment]
> * Make sure 30 GB of space is available.

We could maybe also check it at the beginning of the build. (Thanks @omajid for the suggestion)

**Comment by dagood** [comment]
Here are some brief notes from my VM setup for 3.1.109. It didn't quite come from a clean machine (I had RHEL7 + 8 VMs from an earlier cancelled attempt that I kept using) but these got me the final steps of the way:

## RHEL7

Native compiler toolsets:

```
sudo subscription-manager repos --enable rhel-server-rhscl-7-rpms
sudo yum install -y llvm-toolset-7.0-clang llvm-toolset-7.0-cmake llvm-toolset-7.0-lldb-devel llvm-toolset-7.0-llvm
```

Build inside an llvm scl-enabled shell (rather than setting up `PATH` et. al. manually):

```
scl enable llvm-toolset-7.0 bash
```

To get `lttng-ust-devel`, it looks like it's reasonable to pull from EfficiOS because Red Hat directs us there:
https://developers.redhat.com/blog/2015/07/09/lttng-packages-available-for-rhel-7/
http://packages.efficios.com
I didn't poke around much for an in-distro way to get it, maybe there is one.
```
wget -P /etc/yum.repos.d/ https://packages.efficios.com/repo.files/EfficiOS-RHEL7-x86-64.repo
rpmkeys --import https://packages.efficios.com/rhel/repo.key
```

Finally, other packages based on the CentOS7 `spec`:

```
sudo yum install -y \
  lttng-ust-devel \
  coreutils \
  git \
  krb5-devel \
  libcurl-devel \
  libicu-devel \
  openssl-devel \
  python \
  tar \
  zlib-devel
```

## RHEL8

lttng is in the distro, in a specific repo (thanks omajid for help finding this):

```
sudo subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
sudo yum install lttng-ust-devel
```

General packages based on CentOS8 `spec`:

```
sudo yum install -y \
  clang \
  cmake \
  coreutils \
  git \
  glibc-langpack-en \
  hostname \
  krb5-devel \
  libcurl-devel \
  libicu-devel \
  lldb-devel \
  llvm \
  openssl-devel \
  python3 \
  tar \
  zlib-devel
```

libunwind-devel is not available in RHEL8, have to disable it. Can use a source edit, like CentOS8:
https://git.centos.org/rpms/dotnet3.1/blob/c8/f/SPECS/dotnet3.1.spec#_328
Or pass a property to the build script, e.g.:
```
./build-source-tarball.sh ../dotnet-3.1.109 -- /p:UseSystemLibunwind=false /p:DownloadSourceBuildReferencePackagesTimeoutSeconds=N/A /p:DownloadSourceBuiltArtifactsTimeoutSeconds=N/A
```

(In theory you can get a system libunwind package elsewhere, but we shouldn't diverge from how these distros *actually* build .NET from source unless we have a reason. This way we have a chance of catching system library usage bugs in our own build before it hits the distro itself.)

**Comment by dagood** [comment]
For e.g. 5.0.100, an authenticated build with tarball creation looks something like this on RHEL 8:

```sh
cd source-build # dotnet/source-build dir at desired commit.

export internalPackageFeedPat; read internalPackageFeedPat
./build-source-tarball.sh ../dotnet-5.0.100-rhel.8 -- /p:UseSystemLibunwind=false /p:AzDoPat=$internalPackageFeedPat
./build.sh --run-smoke-test

cd ..

mkdir -p dotnet-5.0.100-rhel.8-smoke-test-prereqs/packages/smoke-test-packages
find source-build/testing-smoke/smoke-test-packages/ -iname '*.nupkg' -exec cp {} dotnet-5.0.100-rhel.8-smoke-test-prereqs/packages/smoke-test-packages/ \;
tar --numeric-owner -czf dotnet-5.0.100-rhel.8-smoke-test-prereqs.tar.gz dotnet-5.0.100-rhel.8-smoke-test-prereqs/
tar --numeric-owner -czf dotnet-5.0.100-rhel.8.tar.gz dotnet-5.0.100-rhel.8/

read sas_token_authed_upload_virtual_dir
azcopy dotnet-5.0.100-rhel.8-smoke-test-prereqs.tar.gz "$sas_token_authed_upload_virtual_dir"
azcopy dotnet-5.0.100-rhel.8.tar.gz "$sas_token_authed_upload_virtual_dir"
```
