### ISSUE TITLE
Validate Core-Setup AlwaysPackEvenIfNotServicing=true doesn't break compatibility with Microsoft-built SDK/Runtime

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1691]
https://github.com/dotnet/source-build/issues/1668 tracks adding `/p:AlwaysPackEvenIfNotServicing=true` to the Core-Setup build. This means that even if Microsoft doesn't release a new patch release for PlatformAbstractions/DependencyModel/HostModel, source-build will still produce it, avoiding prebuilts in downstream repos.

This issue tracks answering/fixing this open question from https://github.com/dotnet/source-build/issues/1668:

> Another thing to consider is whether we need to downgrade the produced package's version to match the last-released Microsoft package.

By default, yes, we should do this, to match the Microsoft release. However, it requires more complex infra, so it's worth some more discussion. We're considering fixing https://github.com/dotnet/source-build/issues/1668 without implementing the downgrade.

If we just add `/p:AlwaysPackEvenIfNotServicing=true`, then if Microsoft doesn't patch HostModel etc. in 3.1.7, we end up with different DLL identities in the SDK we ship vs. the Microsoft build:

* Source-Build: HostModel.dll, 3.1.7
* Microsoft: HostModel.dll, 3.1.6 (harvested from the last shipped release)

In theory, if someone compiles a DLL referencing the HostModel 3.1.7 in the source-built SDK, then tries to move it to a machine that uses the Microsoft-built SDK, it could fail to load the dependency because only 3.1.6 is present. However, I don't think this is a valid scenario. DLLs should build against the lowest-versioned HostModel DLL possible so the result is compatible with any version that may be available at runtime. (This would be done with a `PackageReference`.)

This ties into the plan at https://github.com/dotnet/source-build/tree/release/3.1/Documentation/planning/nongranular-servicing-readiness to actually run tests to validate that the Microsoft servicing build skips don't break compatibility.

/cc @dseefeld

**Comment by dagood** [comment]
> We're considering fixing #1668 without implementing the downgrade.

> In theory, if someone compiles a DLL referencing the HostModel 3.1.7 in the source-built SDK, then tries to move it to a machine that uses the Microsoft-built SDK, it could fail to load the dependency because only 3.1.6 is present.

To expand a bit, it takes some effort to get this to bite you.

It's not *too* hard to get partway there with MSBuild: `<Reference Include="full/path/to/sdk/Microsoft.DotNet.PlatformAbstractions.dll" Private="false" />`. But then, you need to add the SDK to the assembly resolver search path to run it. (I don't know how to do this part with the `dotnet` or `apphost` hosts.) Then you'd probably see the error if it's copied to a machine with the Microsoft SDK.

The failure I'd expect is something like this:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.PlatformAbstractions, Version=3.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.DotNet.PlatformAbstractions, Version=3.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

Funnily enough, without `Private="false"`, the build would actually copy the SDK's `Microsoft.DotNet.PlatformAbstractions.dll` to the output directory, so it may make it work. (Although I think it'd be carrying `crossgen`/`R2R` results that might be dead weight?)

All this vs. `<PackageReference Include="Microsoft.DotNet.PlatformAbstractions" Version="3.1.6" />`, which just works and should be obvious in the .NET ecosystem.

Maybe the right question is: if someone gets in this situation, is it ok to tell them that we don't support it, and they should use a `PackageReference` instead?

---

An interesting bit here is that if someone needs a source-built PlatformAbstractions, this may be the only way to do it... but this is a larger problem than these three packages--all platform extension libraries (built by .NET Core but not in a shared framework) have this problem.

**Comment by dagood** [comment]
> If we just add `/p:AlwaysPackEvenIfNotServicing=true`, then if Microsoft doesn't patch HostModel etc. in 3.1.7, we end up with different DLL identities in the SDK we ship vs. the Microsoft build:
> 
> * Source-Build: HostModel.dll, 3.1.7
> * Microsoft: HostModel.dll, 3.1.6 (harvested from the last shipped release)

Update: we did this in 3.1.7 / 3.1.107, and haven't seen any issues with it so far.

**Comment by MichaelSimons** [comment]
Starting in at least .NET 6.0, source-build builds the full product in servicing.  This issue is obsolete.
