### ISSUE TITLE
[ArPow] Re-enable sourcelink

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1693]
https://github.com/dotnet/sourcelink/issues/629 is an issue for the current source-build plan, worked around by disabling sourcelink in https://github.com/dotnet/source-build-reference-packages/pull/133.

When fixed and uptaken by Arcade, we can enable sourcelink in 5.0.

(Filing this a little early, to make sure it ends up tracked.)

**Comment by omajid** [comment]
Sourcelink is enabled in .NET 6 and 7, which is why we discovered issues like https://github.com/dotnet/source-build/issues/2903
