### ISSUE TITLE
Include "scripts/bootstrap/buildbootstrapcli.sh" in dotnet/installer for 5.0

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1694]
Discussed in https://github.com/dotnet/source-build/issues/1681. Simple task, but worth tracking. Make sure the script ends up in dotnet/installer for continued maintenance in 5.0+ when source-build infra will no longer have a dedicated repo.

**Comment by MichaelSimons** [comment]
Closing as obsolete.  buildbootstrapcli.sh no longer exists.
