### ISSUE TITLE
Add smoke-test mode to use internal authenticated sources, not smoke-test-prereqs

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1708]
Currently we test two main package source scenarios in smoke-test:
* `ONLINE RESTORE SOURCE`: online feeds + smoke-test-prereqs used.
* `LOCAL RESTORE SOURCE`: online feeds + smoke-test-prereqs used + source-build output nupkgs used.

For internal builds, smoke-test-prereqs always includes all packages used by smoke-test, because they may not be accessible if you don't have internal creds. This means all smoke-test runs using a internally built tarball depend on smoke-test-prereqs.

We can add a third mode that only uses online feeds, that would only be run by people with internal creds. It can be used to double-check that the contents of smoke-test-prereqs is compatible with what's planned to ship with the Microsoft build.

To make this an effective check, we can't rely on the sources that are already in the repo, we have to grab "end-user" sources from the Microsoft build, via email threads and things like that. If we reused the same nuget sources we built with, there's no difference from smoke-test-prereqs. Since the source is likely the same, it's not clear whether running check will actually turn anything up.

The production build already kind of does this: it's how we gather smoke-test-prereqs. However, we don't have a way to easily run this same "mode" in the tarball output, which is the actual product.

---

Note to triage: I think we should close this since the value's unclear. Filing because I straightened out what we're actually missing here even though I don't think we need it anymore.

Earlier related issues: https://github.com/dotnet/source-build/issues/1692, https://github.com/dotnet/source-build/issues/1677

**Comment by dseefeld** [comment]
Closing per previous comment.
