### ISSUE TITLE
Remove ProdConBlobFeedUrl from smoke-test

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1713]
The parameter for ProdConBlobFeedUrl doesn't appear to be used, but is still included as a parameter in smoke-test.sh and is being included in CI.  This confuses things when running smoke-tests manually.  This parameter should be investigated and removed if it is no longer needed.

**Comment by MichaelSimons** [comment]
[Triage] smoke-test.sh no longer exists.  ProdConBlobFeedUrl was removed when the smoke-tests were re-written in with a test framework
