### ISSUE TITLE
[3.1.107-SDK] git error near end of building source tarball

### ISSUE THREAD

**Issue by cerebrate** [dotnet/source-build#1718]
Shortly after the download of `https://dotnetcli.azureedge.net/source-built-artifacts/assets/Private.SourceBuilt.Artifacts.0.1.0-3.1.106.tar.gz`, the build fails with the error:

```
  fatal: invalid reference: HEAD
/home/avatar/src/source-build-3.1.107-SDK/eng/SourceBuild.Tarball.targets(46,5): error MSB3073: The command "git --work-tree="/home/avatar/src/source-build-3.1.107-SDK/artifacts/source-tarball/" checkout HEAD -- src" exited with code 128. [/home/avatar/src/source-build-3.1.107-SDK/packages/restored/microsoft.dotnet.arcade.sdk/1.0.0-beta.19359.6/tools/Build.proj]
```

Tested with target directories within and without the source tree, previously existing and not; the same result persists.

**Comment by dseefeld** [comment]
@cerebrate Any info on this?  Is this continuing to fail for you?

**Comment by cerebrate** [comment]
I've got it working, but not in a terribly useful way -- for debugging purposes, that is.

Which is to say, it was failing right up until it wasn't, and the only thing that changed at the appropriate time was the updating and restarting of a local NFS server which, in theory, had nothing at all to do with the build (all the build folders, etc., were local, and so forth), which leaves me in the rather unhelpful situation of having to say "it works now, but I have _no idea why_ .) 😦 🤷

**Comment by dagood** [comment]
Hmm... well, from my perspective, the simplest explanation is that you ran a build on a GitHub tar.gz while thinking it was on a Git clone, and when you tried again, it was actually the first time trying it with a Git clone. No idea how likely that is given your setup/process, but it seems to be a pretty specific error that we can't repro without the GitHub tar.gz.

If you (or anyone) hits this again with a Git clone, please share the binlogs and more info, and don't clean up the repo so we can do more deep investigation. Would be happy to reopen the issue then and dig deeper into this.
