### ISSUE TITLE
Include prebuilt reports in intermediate nupkgs (arcade-powered source-build)

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1725]
We need some way to keep track of prebuilt status, especially when we haven't enabled prebuilt enforcement in the repos. Putting the prebuilt reports in the intermediate nupkgs and passing them on seems like a reasonable way to do this. We can look at some sort of consolidated report in dotnet/installer that shows the results throughout the graph, just like the current baselines in dotnet/source-build.

**Comment by dseefeld** [comment]
Fixed with https://github.com/dotnet/arcade/pull/6121
