### ISSUE TITLE
Should source-build build ILRewrite?

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1728]
Source-build currently doesn't build ILRewrite code, but a targets file in Arcade tries to use it without knowing the code isn't available, so we had to patch this out.  What is ILRewrite and should we build it?

See also discussion at https://github.com/dotnet/source-build/pull/1727/files/746f9090bab3a1a6983d54ae1ef73c5b71d508d5#diff-28993e60d03feb55482484005897b1e5.

**Comment by MichaelSimons** [comment]
[Triage] This isn't impacting the build from a source-build requirements perspective.  Closing as obsolete.
