### ISSUE TITLE
Investigate review comments on source-build MSBuild tasks: usage hash code, commenting, unusual XML writing procedure

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1730]
Got some interesting comments on https://github.com/dotnet/arcade/pull/6121, but not addressed in that PR because it is mainly a straight copy of source-build tasks into dotnet/arcade for arcade-powered source-build:

https://github.com/dotnet/source-build/blob/cf4ce124d08271dfca38b66c2a5b54fee2671869/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/Usage.cs#L106-L110

> [Does PackageIdentity have an appropriate GetHashCode for this? (or is a value type)](https://github.com/dotnet/arcade/pull/6121#discussion_r483773079)

https://github.com/dotnet/source-build/blob/cf4ce124d08271dfca38b66c2a5b54fee2671869/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/WriteBuildOutputProps.cs#L24-L26

> [Can you include the expected metadata for this task item here?](https://github.com/dotnet/arcade/pull/6121#discussion_r483779130)

https://github.com/dotnet/source-build/blob/cf4ce124d08271dfca38b66c2a5b54fee2671869/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/WriteBuildOutputProps.cs#L80-L81

> [Is there a reason we're writing the xml text explicitly this rather using an XmlDocument or other such method?](https://github.com/dotnet/arcade/pull/6121#discussion_r483780908)

**Comment by crummel** [comment]
[Scrub] In light of https://github.com/dotnet/source-build/issues/3073 and https://github.com/dotnet/source-build/issues/2295, I think this can be closed and when we reconcile the Arcade versions of the tasks with the source-build versions we can call these out in the code reviews.
