### ISSUE TITLE
SBRP pre-arcade Microsoft.Bcl.AsyncInterfaces.1.1.0.nupkg redists net472 targeting pack contents, unlike on nuget gallery

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1781]
Taking the output from https://dev.azure.com/dnceng/internal/_build/results?buildId=832629&view=results, (I think https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/Private.SourceBuild.ReferencePackages.1.0.0-beta.20476.1.tar.gz), I see in `Microsoft.Bcl.AsyncInterfaces.1.1.0.nupkg\ref\net461\`:

```
Microsoft.Bcl.AsyncInterfaces.dll
Microsoft.Win32.Primitives.dll
netstandard.dll
System.AppContext.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.NonGeneric.dll
...
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
```

However https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/1.1.0 `ref\net461\` only has:

```
Microsoft.Bcl.AsyncInterfaces.dll
```

Maybe this is just missing `PrivateAssets="All"`? (I usually see that attribute on this package ref, and it certainly seems like it would have the desired effect here.)

```xml
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net461" Version="1.0.0-alpha-5" />
```

https://github.com/dotnet/source-build-reference-packages/pull/165/files#diff-f25d52a113bbd37bc0a2c09e8b35655eR28

I don't have a clear link from the .NET Framework targeting pack nupkg to this file being included, I'm just guessing based on the .NET Framework pack having a lot of assemblies like this.

---

This seems like a likely cause for this kind of error in source-build:

```
PrepareForReadyToRunCompilation.cs(362,117): error CS0433: The type 'Architecture' exists in both 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' [/bst/bootstrap_dir/final-sdk/src/sdk.afdde814dc8dedb325e63b39cf72249b43918a23/src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj]
```

Because in the `Csc` task inputs, we see it's finding this copy of `System.Runtime.InteropServices.RuntimeInformation`, which isn't there in the nuget gallery nupkg:

```
/.../packages/restored/microsoft.bcl.asyncinterfaces/1.1.0/ref/net461/System.Runtime.InteropServices.RuntimeInformation.dll
```

/cc @dseefeld

**Comment by crummel** [comment]
[Scrub] Pre-arcade SBRP is no longer used and this issue does not repro in post-arcade SBRP.
