### ISSUE TITLE
Smoke-test 3.1 issue: "curl: (60) Peer's Certificate has expired."

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1788]
```
LOCAL RESTORE SOURCE - ALL TESTS PASSED!
curl: (60) Peer's Certificate has expired.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

##[debug]Exit code 60 received from tool '/bin/bash'
##[debug]STDIO streams have closed for tool '/bin/bash'
##[error]Bash exited with code '60'.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=839463&view=logs&j=8c35c666-1cc6-56eb-620e-0f6e7d3caf0a&s=149ab9f9-2746-51c3-9bed-64d13cb4f094&t=b30ab823-f7fe-562e-90b7-7ff3e51be1be&l=1420

This may be flakiness.

Based on the log sequence, I think it's this call:

https://github.com/dotnet/source-build/blob/aba40993f730291e4032c9b3c01d27ae7bb1b0aa/scripts/fetch-microsoft-sdk.sh#L45-L51

Maybe our CA certs are just out of date in that docker image.

**Comment by dseefeld** [comment]
Workaround: Manually download and compare and include in release checklist rather than doing this automatically.  It's hard to know if a fix is valid because the issue is somewhat flaky.

**Comment by MichaelSimons** [comment]
smoke-tests have been reliable since .NET 6.0.  This issue is obsolete.
