### ISSUE TITLE
Investigate including dotnet/icu in source-build 5.0

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1792]
https://github.com/dotnet/icu showed up as a dotnet/runtime dependency between 5.0 preview 7 and 5.0 preview 8:
https://github.com/dotnet/runtime/blob/v5.0.0-preview.8.20407.11/eng/Version.Details.xml#L7-L10
https://github.com/dotnet/runtime/commit/8c1792d7e2b2a0f1965e46ccf6b34fe6ee15ea3a

Based on that, it looks like a `browser-wasm` dependency. It might not be necessary for 5.0--we don't think we can build our own `browser-wasm` runtime pack yet (https://github.com/dotnet/source-build/issues/1721), and runtime packs in general can't even be distributed in the SDK (#1215), so everyone will use the Microsoft-built one from nuget.org for Blazor.

If dotnet/icu bits somehow end up inside the SDK, though, rather than just the runtime pack, we will need to do this to remove prebuilts.

**Comment by dseefeld** [comment]
Doesn't appear that this is needed for source-build 5.0, since we're not building browser-wasm runtime pack.  If prebuilts happen to appear for this because of other dependencies, it can be addressed then.
