### ISSUE TITLE
[release/5.0] Add NuGet 4.9.4 packages to SBRP

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1803]
These packages are used by dotnet/runtime as reference-only:

```
NuGet.Common,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.Configuration,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.DependencyResolver.Core,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.Frameworks,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.LibraryModel,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.Packaging,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.Packaging.Core,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.ProjectModel,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.Protocol,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
NuGet.Versioning,4.9.4+ed6e2dca9391d13b431f4eff58c5194f0ebcee13
```

The version numbers are not quite processed correctly by the prebuilt usage finder (https://github.com/dotnet/source-build/issues/793), you have to search for e.g. `NuGet.Versioning/4.9.4` to find them in project.assets.json files.

https://github.com/dotnet/runtime/blob/v5.0.0-rc.1.20451.14/eng/Versions.props#L132-L133

**Comment by dseefeld** [comment]
Rather than add to SBRP, I updated the version used to 5.1.0 which already exists in SBRP.  https://github.com/dotnet/source-build/pull/1843

**Comment by dagood** [comment]
Completed (a while back) by https://github.com/dotnet/source-build/pull/1843.
