### ISSUE TITLE
Make prebuilt report accessible anonymously

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1823]
I went to write instructions for how to access the prebuilt report from PR validation builds, but encountered an AzDO bug (feature? 😕) partway through where you can't dig into the artifact tree unless you have Microsoft auth.

The way it should work is that you to first go to the PR build via the `source-build-CI` `Details` link, and click this text that's meant to represent a button labeled "Artifacts": (AzDO interface is also pretty inconsistent/unintuitive here about the affordance...)

![image](https://user-images.githubusercontent.com/12819531/96740836-d67d1880-1386-11eb-895d-912e36c749aa.png)

Then click into this hierarchy:

![image](https://user-images.githubusercontent.com/12819531/96741133-1fcd6800-1387-11eb-85f4-6c118829a755.png)

But anonymously, you can only download the entire logs artifact, and it doesn't even tell you how large it thinks it is even after starting the download--so you end up downloading >1GB of logs without knowing what you're getting into:

![image](https://user-images.githubusercontent.com/12819531/96741525-7fc40e80-1387-11eb-9777-4bf9538d1ddb.png)

I filed an issue on AzDO a few years ago about this, but nobody addressed it. 🙁

We can work around it by modifying the yaml to publish the prebuilt report as yet another top-level artifact, to make its size manageable for unauthed download by separating it from the other logs. (This makes it easier to find too, but that's just a matter of being ok with a redundant artifact.)

**Comment by tmds** [comment]
@dagood please make it available as a top-level artifact, we don't want to wait for the AzDO issue to get solved.

**Comment by dagood** [comment]
Yeah, I don't anticipate AzDO resolving this.

**Comment by dagood** [comment]
Merged fix into `master` with https://github.com/dotnet/source-build/pull/1831.

Need to use the hidden-until-mouseover `...` to initiate the download. Now it's on the order of MB rather than GB, so much more reasonable than before:

![image](https://user-images.githubusercontent.com/12819531/96922180-1f12ff80-1475-11eb-82dd-61465bdd071f.png)
