### ISSUE TITLE
Add microsoft.aspnetcore.app.ref/3.1.10 to SBRP pre-arcade-release/3.1

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1835]
For 3.1.110 (https://github.com/dotnet/source-build/pull/1832) it looks like the build is using the ref-only package auto-dasm-asm process to get `microsoft.aspnetcore.app.ref/3.1.10`, but I think this may need to be put in SBRP for future releases.

```
0cff553536cf  ./packages/reference/staging/microsoft.aspnetcore.app.ref/3.1.10/ref/netcoreapp3.1/System.IO.Pipelines.dll
0cff553536cf  ./packages/restored/microsoft.aspnetcore.app.ref/3.1.10/ref/netcoreapp3.1/System.IO.Pipelines.dll
0cff553536cf  ./src/installer.f02c158773cf1b5fd547570d55ad5a436b58f81d/artifacts/bin/redist/Release/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.10/ref/netcoreapp3.1/System.IO.Pipelines.dll
0cff553536cf  ./testing-smoke/builtCli/packs/Microsoft.AspNetCore.App.Ref/3.1.10/ref/netcoreapp3.1/System.IO.Pipelines.dll
```

I don't quite remember why we can't rely on the ref-only package flow to handle it, but want to file this issue to track to handle this in the future either way.

@dseefeld @crummel

**Comment by MichaelSimons** [comment]
3.1 is EOL in two months.  This issue is obsolete.
