### ISSUE TITLE
Build runtime repo using --allconfigurations

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1838]
Currently, packages built in the libraries subset of the runtime repo build are only built for the current TFM (net5.0).  This causes issues when using these packages when the consumer is building with other TFMs.  This causes workarounds that make the source-built product different than the official builds of the product.  Building the libraries with the `--allconfigurations` flag would allow them to be built from source for all supported TFMs.  An initial build with `--allconfigurations` was attempted, but ran into issues with TypeForwards not generating correctly for some packages.  Discussions with the runtime team have indicated that it may be related to GenFacades not supporting ILRewriting in source-build.  This needs more investigation.

**Comment by ericstj** [comment]
@dseefeld I believe this should be unblocked now that https://github.com/dotnet/runtime/pull/52793 is merged.  Can you give this a try and see if it works now?

**Comment by MichaelSimons** [comment]
This has been implemented [here](https://github.com/dotnet/runtime/blob/main/eng/SourceBuild.props#L37)
