### ISSUE TITLE
dotnet-install.sh script fails to download: "curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate."

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1839]
> CI has a hickup:
> 
> ```
> 2020-10-27T09:41:55.5816737Z + /src/eng/common/dotnet-install.sh -runtime dotnet -version 3.1.1
> 2020-10-27T09:41:55.6017354Z Downloading 'https://dot.net/v1/dotnet-install.sh'
> 2020-10-27T09:41:56.1715723Z curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
> 2020-10-27T09:41:56.1763973Z bash: /src/.dotnet/dotnet-install.sh: No such file or directory
> 2020-10-27T09:41:56.1873338Z Failed to install dotnet SDK (exit code '127').
> ```
> 

_Originally posted by @tmds in https://github.com/dotnet/source-build/pull/1828#issuecomment-717198918_

**Comment by dagood** [comment]
This seems like flakiness.

**Comment by dseefeld** [comment]
Looks like AzDo flakiness.
