### ISSUE TITLE
Determine desired TFM behavior in a product build (+document?)

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#184]
In https://github.com/dotnet/source-build/pull/181#discussion_r141086135 @eerhardt had some good questions about the source-built product:

> >[An arg [to tell a repo what TFM to build] makes sense to me.] It sounds like we'll need one for netstandard and one for netcoreapp.
> 
> Do we need both?  I assumed the idea was that the whole source build would be for `netcoreapp`?  /cc @weshaggard @ericstj

> A really good/important question we need to figure out is: "What is the expected usage of these `source-built` assets?"
> 
> Do we expected people to reference the .nupkgs that are produced by this build?  If so, then they won't be able to build any `netstandard1.x` projects.  (Or even `netstandard2.0` when we move to a `netstandard2.1` or `3.0`.) Is this intended?

I'm not 100% sure this is something that needs to be independently tracked/documented, but it's easy to close this issue if not.

**Comment by dseefeld** [comment]
This will come into play when we address #210.

**Comment by weshaggard** [comment]
Lets use #210 to track
