### ISSUE TITLE
Document reasonable inner loop for patch development

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1840]
For 5.0 we need a reasonable way to develop patches. Right now I don't know if we have a reasonable way to do this. I came up with this to work on onboarding the symreader repo:

1. Add the repo to `eng/Version.Details.xml`.
1. Add a `repos/foo.proj` file based on a repo that seems similar.
1. Run a build with `/p:RootRepo=foo`, fail intentionally in `foo.proj`.
1. ```
    cd artifacts/src/foo.abcdef123/
    git init
    git remote add dagood https://github.com/dagood/foo
    git fetch dagood
    git checkout -f abcdef123
    # If this is an existing repo, can run 'git am ../../../patches/foo/*.patch' to apply patches.
    git checkout -b onboard
    ```
1. Make changes in `artifacts/src/foo.abcdef123/`.
    * I'm able to open a remote folder in VS Code in this dir and it seems to work. Since we won't be running fresh builds, it *shouldn't* need to be deleted + recreated during the dev flow.
1. Commit changes to new branch and push to your fork to preserve in case the dir gets deleted unexpectedly.
    * If this happens, can use `git checkout -f dagood/onboard` next time to restore progress.
1. Run the build command in the source-build root again. (Semaphores should make it only rerun your build command.)
1. Repeat change -> build as much as needed.
    * `artifacts/obj/semaphores/foo/` may contain semaphores that prevent certain pre-built actions from happening. For example, might need to delete `UpdateGlobalJsonVersions.complete` if you revert the change on the Git side during dev work. I think.

Once done:
1. `../../../extract-patches.sh abcdef123`

Related: https://github.com/dotnet/source-build/issues/1468 tracks documenting a workflow for reapplying existing patches. (The focus there would be merge conflicts and patch operations, not actually running the build, though.)

---

@dseefeld @crummel does this flow seem reasonable?

FYI @tmds @omajid

**Comment by dseefeld** [comment]
This flow seems reasonable to me.  

My process is a little more manual.  In your step 4, instead of initializing a git repo there, I just make the desired changes in the `artifacts/src/foo.abcdef123/` folder, and re-build until I've fixed the problem or made the changes that I want.   At that point, I do the following steps:

```
cd artifacts/src/foo
git checkout -f abcdef123
# If this is an existing repo, can run 'git am ../../../patches/foo/*.patch' to apply patches.
# Either re-make changes in artifacts/src/foo folder or copy changed files from artifacts/src/foo.abcdef123/ to artifacts/src/foo
git add <modified files>
git commit
../../../extract-patches.sh abcdef123
```

**Comment by MichaelSimons** [comment]
[Triage] Patches are evil and are being phases out.  We are not wanting to make any investments to promote their use.
