### ISSUE TITLE
Fix location of runtime and aspnetcore blob output

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1853]
As part of the update to 5.0GA, a patch was added to the installer repo to allow it to find aspnetcore and runtime blob output.  The original code was looking in a folder based on an unstable version number and source-build's output for these were in a folder based on a stable version number.

```
-    <AspNetCoreBlobVersion>$(VSRedistCommonAspNetCoreSharedFrameworkx6450PackageVersion)</AspNetCoreBlobVersion>
-    <CoreSetupBlobVersion>$(MicrosoftNETCoreAppInternalPackageVersion)</CoreSetupBlobVersion>
+    <AspNetCoreBlobVersion>$(MicrosoftAspNetCoreAppRefPackageVersion)</AspNetCoreBlobVersion>
+    <CoreSetupBlobVersion>$(MicrosoftNETCoreAppRefPackageVersion)</CoreSetupBlobVersion>
```

While this achieves the desired result, it was noted by @dagood:

> This will break in servicing, the ref package doesn't update with every release but the runtime version will. I believe the infra we have putting them in a stable location is what's wrong here (or rather, not matching what the modern infra does anymore). The blob storage virtual folder should always be unstable and only the filename version gets stable.

This should be fixed by updating the source-build infra to put this output into a folder based on an unstable version number.

**Comment by MichaelSimons** [comment]
[Triage] @crummel - can you please check if this issue is still applicable?

**Comment by crummel** [comment]
[Scrub] We appear to handle unstable versions of these packages properly now.
