### ISSUE TITLE
Fix installation of runtime into the tooling SDK dir during the build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1854]
https://github.com/dotnet/source-build/pull/1845 adds a line like this:

```
<Exec Command="tar -xvf $(SourceBuiltAssetsDir)dotnet-runtime-$(runtimeOutputPackageVersion)-$(TargetRid).tar.gz -C $(DOTNET_INSTALL_DIR)" />
```

https://github.com/dotnet/source-build/pull/1845#discussion_r514404001

> What happens on a rebuild? What happens in bootstrapping when we build N using N? This seems pretty difficult to get right. Maybe it doesn't need to block merging this PR (so we can keep working on prebuilts in parallel ASAP) but I think we should find a less overwritey way immediately.

**Comment by dseefeld** [comment]
Triage: Follow up with aspnetcore team to see if they can use the currently installed SDK rather than the current runtime version.

**Comment by crummel** [comment]
[Scrub] This untarring process is no longer used in source-build.
