### ISSUE TITLE
Re-add aspnetcore version number patch for servicing

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1855]
When updating source-build for 5.0GA, the following patch to update the aspnetcore version was not needed because the version matched what was being produced (5.0.0).  When servicing 5.0 releases, this patch should be re-added.

https://github.com/dotnet/source-build/blob/6674ad97df11b0959f55096b12cc5801c8a2af30/patches/aspnetcore/0005-Fix-version-number.patch

**Comment by dseefeld** [comment]
Triage: A better approach may be to add an "update" to the source-build infra that updates the version rather than using a patch.

**Comment by dseefeld** [comment]
https://github.com/dotnet/aspnetcore/issues/11592 covers fixing this upstream.

**Comment by MichaelSimons** [comment]
[Triage] This issue is obsolete.
