### ISSUE TITLE
Build `Microsoft.CodeAnalysis` 3.8.0 as part of roslyn repo

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1870]
> > But it also appears like some rolsyn packages are not being built? `Microsoft.CodeAnalysis` 3.8.0 should have been build as part of roslyn repo, but it's not present. This appears to be a super-package; maybe I can patch roslyn-analzyers to use individual nuget packages?
> 
> Hmm. It: https://github.com/dotnet/roslyn/blob/4c195c3ac1974edcefa76774d7a59a2350ec55fa/src/NuGet/Microsoft.CodeAnalysis.Package.csproj
> appears to be deliberately disabled: https://github.com/dotnet/roslyn/blob/4c195c3ac1974edcefa76774d7a59a2350ec55fa/src/NuGet/Directory.Build.props#L4
> 
> But I don't know why. 😕
> 
> It seems to me like it'd be reasonable to try patching `<ExcludeFromSourceBuild>false</ExcludeFromSourceBuild>` into that proj to get rid of the exclusion and try to build it.
> 
> @crummel @dseefeld any ideas?
> 
> _Originally posted by @dagood in https://github.com/dotnet/source-build/pull/1849#issuecomment-723322482_

**Comment by omajid** [comment]
Closing as fixed via #1872
