### ISSUE TITLE
5.0.0 Runtime / 5.0.100 SDK GA

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1891]
This epic tracks remaining work to get the 5.0.100 SDK released (with 5.0.0 Runtime).

5.0 servicing followup issues go in https://github.com/dotnet/source-build/issues/1862.

Originally https://github.com/dotnet/source-build/issues/1510 tracked 5.0.100, but it now tracks arcade-powered source-build. I'm creating this epic to track 5.0.100 issues.

**Comment by omajid** [comment]
5.0 GA happened. Is there any need to keep this issue open? Can we close it?

**Comment by MichaelSimons** [comment]
[Triage] Closing as .NET 5.0 is complete.  There is one outstanding testing issue which is tracked separately.
