### ISSUE TITLE
Overriding 4.7.0 dependencies with 5.0.0 top-level dependencies in dotnet/sdk to avoid shipping prebuilts/refs

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1896]
There was an issue trying to introduce some SBRP packages: https://github.com/dotnet/source-build-reference-packages/pull/189

> [dseefeld]
> System.Drawing.Common,4.7.0 is causing an issue with the tarball build:
> 
> ```
> /tb/tarball_886198/src/installer.5044b938294b7b920a5a4393a5f0f8b7b1750548/src/redist/targets/Crossgen.targets(127,5): error : Error: Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. [/tb/tarball_886198/src/installer.5044b938294b7b920a5a4393a5f0f8b7b1750548/src/redist/redist.csproj] 
> /tb/tarball_886198/src/installer.5044b938294b7b920a5a4393a5f0f8b7b1750548/src/redist/targets/Crossgen.targets(127,5): error : (0x80070002) [/tb/tarball_886198/src/installer.5044b938294b7b920a5a4393a5f0f8b7b1750548/src/redist/redist.csproj] 
> ```
> 
> Reverting this package until a solution can be determined.

> [dagood]
> Looking at this because it ends up overlapping with `Microsoft.Win32.SystemEvents/4.7.0`. (Anything built in dotnet/runtime with a recent version that is at some point used as a lib/runtime, probably.)
> 
> I believe that if we have MSBuild/Roslyn/FSharp upgrade their `System` packages, we avoid missing the lib/runtime DLL. But then we have to upgrade them to target `net5.0` (from ~`netcoreapp3.1`) because we only build `net5.0` in dotnet/runtime. This might let us avoid this PR entirely.
> 
> An alternative is to have dotnet/sdk override the `System` packages with a top-level dependency on the 5.0.0 source-built version. At that point we're already targeting `net5.0`, so it should take the real lib/runtime fine. This way we can get these ref-only packages back into SBRP but not break the build.

Making Roslyn target `net5.0` seems like a significant effort. `netcoreapp3.1` shows up a ton in the projects. Trying an automated replacement of `netcoreapp3.1` -> `net5.0` instead of a patch file (https://github.com/dotnet/source-build/commit/5cc195e224415ec5bb4e98834d6f7626c2d9c039) seemed to make ok replacements, but the build is broken. The initial set of errors from a standalone build (the "Test" ones might not apply in source-build context):

```
13 results. Search took: 00:00:00.1583198
Project "Microsoft.CodeAnalysis.csproj" (Build target(s)):
    Target CoreCompile
        CscTask Csc
            Error /work/src/Compilers/Core/Portable/Diagnostic/Location.cs(33,10): error CS0436: The type 'MemberNotNullWhenAttribute' in '/work/src/Compilers/Core/Portable/InternalUtilities/NullableAttributes.cs' conflicts with the imported type 'MemberNotNullWhenAttribute' in...
            Error /work/src/Compilers/Core/Portable/Collections/IOrderedReadOnlySet.cs(12,49): error CS0104: 'IReadOnlySet<>' is an ambiguous reference between 'Roslyn.Utilities.IReadOnlySet<T>' and 'System.Collections.Generic.IReadOnlySet<T>' [/work/src/Compilers/Core/Portable...
            Error /work/src/Compilers/Core/Portable/Collections/OrderedSet.cs(15,59): error CS0104: 'IReadOnlySet<>' is an ambiguous reference between 'Roslyn.Utilities.IReadOnlySet<T>' and 'System.Collections.Generic.IReadOnlySet<T>' [/work/src/Compilers/Core/Portable/Microsof...
            Error /work/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs(82,16): error CS0104: 'IReadOnlySet<>' is an ambiguous reference between 'Roslyn.Utilities.IReadOnlySet<T>' and 'System.Collections.Generic.IReadOnlySet<T>' [/work/src/Compilers/Core/Portable/Micr...
            Error /work/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs(480,24): error CS0104: 'IReadOnlySet<>' is an ambiguous reference between 'Roslyn.Utilities.IReadOnlySet<T>' and 'System.Collections.Generic.IReadOnlySet<T>' [/work/src/Compilers/Core/Portable/Mic...
            Error /work/src/Compilers/Core/Portable/Compilation/SemanticModel.cs(250,10): error CS0436: The type 'MemberNotNullWhenAttribute' in '/work/src/Compilers/Core/Portable/InternalUtilities/NullableAttributes.cs' conflicts with the imported type 'MemberNotNullWhenAttrib...
Project "CompilersIOperationGenerator.csproj" (default targets):
    Target CoreCompile
        CscTask Csc
            Error /work/src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Program.cs(32,24): error CS8600: Converting null literal or possible null value to non-nullable type. [/work/src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/CompilersIO...
            Error /work/src/Tools/Source/CompilerGeneratorTools/Source/IOperationGenerator/Program.cs(35,41): error CS8604: Possible null reference argument for parameter 'tree' in 'void IOperationClassWriter.Write(Tree tree, string location)'. [/work/src/Tools/Source/CompilerG...
Project "Microsoft.Build.Tasks.CodeAnalysis.csproj" (Build target(s)):
    Target CoreCompile
        CscTask Csc
            Error /work/src/Compilers/Core/MSBuildTask/Utilities.cs(157,17): error CS0618: 'Assembly.GlobalAssemblyCache' is obsolete: 'The Global Assembly Cache is not supported.' [/work/src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj]
            Error /work/src/Compilers/Core/MSBuildTask/Utilities.cs(162,17): error CS0618: 'Assembly.CodeBase' is obsolete: 'Assembly.CodeBase and Assembly.EscapedCodeBase are only included for .NET Framework compatibility. Use Assembly.Location instead.' [/work/src/Compilers/C...
Project "Roslyn.Test.Utilities.csproj" (Build target(s)):
    Target CoreCompile
        CscTask Csc
            Error CSC error CS1566: Error reading resource 'netcoreapp31.mscorlib.dll' -- 'Could not find a part of the path '/work/.container-home/.nuget/packages/microsoft.netcore.app.ref/3.1.0/ref/net5.0/mscorlib.dll'.' [/work/src/Test/Utilities/Portable/Roslyn.Test.Utilitie...
Project "Roslyn.Test.Utilities.csproj" (default targets):
    Target CoreCompile
        CscTask Csc
            Error CSC error CS1566: Error reading resource 'netcoreapp31.mscorlib.dll' -- 'Could not find a part of the path '/work/.container-home/.nuget/packages/microsoft.netcore.app.ref/3.1.0/ref/net5.0/mscorlib.dll'.' [/work/src/Test/Utilities/Portable/Roslyn.Test.Utilitie...
Error Build failed.
```

I have no idea if it's reasonable to get through these along with any followup errors in downstream repos. @tmds is this something you're looking at tackling? /cc @omajid. If we can't make a patch that supports both `netcoreapp3.1` and `net5.0`, that seems to me to be an issue with the idea that the cost is minimal for repos to maintain support for both (https://github.com/dotnet/source-build/issues/1763).

The alternative has us using 5.0.0 packages only where the projects are already targeting `net5.0`, and fill in the `netcoreapp3.1` gaps with SBRP as planned. I'm filing this to document why the overrides seem reasonable for 5.0.0 GA. It seems like a much less risky path as far as schedule goes.

/cc @dseefeld @crummel

**Comment by dseefeld** [comment]
> [dseefeld]
> System.Drawing.Common,4.7.0 is causing an issue with the tarball build:

I've been investigating this.  I found that the package was generated incorrectly.  It didn't have code generated for netcoreapp3.0.  I'm working on changes for the generator and am trying to rebuild and test this package with the fixes to see if it makes a difference.

**Comment by dagood** [comment]
The error suggests that the ref package was being used in dotnet/sdk to generate the toolset, which is crossgen'd in dotnet/installer. We can't produce working libraries out of SBRP so I'd expect it to not work after that either. (Maybe with a "can't load reference assemblies" error rather than "can't find file" though.)

**Comment by dagood** [comment]
> have dotnet/sdk override the `System` packages with a top-level dependency on the 5.0.0 source-built version.

Done by https://github.com/dotnet/source-build/pull/1897. This should unblock us from adding these 4.7.0 versions into SBRP, and we can target `net5.0` as an improvement to remove those from SBRP, later.
