### ISSUE TITLE
how to build dotnet 5.0 from source?

### ISSUE THREAD

**Issue by blackcross86** [dotnet/source-build#1903]
how to build dotnet 5.0 from source?

**Comment by omajid** [comment]
The support for 5.0 is fully complete yet: the functionality is there, but some minor issues are still being worked on

If you want to try it out:

```
git clone http://github.com/dotnet/source-build
cd source-build
git checkout master
./build.sh
```

That will produce a tarball that you can use. See https://github.com/dotnet/source-build/tree/release/3.1/Documentation#building

**Comment by blackcross86** [comment]
> Поддержка 5.0 еще полностью завершена: функциональность есть, но некоторые мелкие проблемы все еще работают.
> 
> Если вы хотите попробовать:
> 
> ```
> git clone http://github.com/dotnet/source-build
> cd source-build
> git checkout master
> ./build.sh
> ```
> 
> Это создаст архив, который вы используете. См. [Https://github.com/dotnet/source-build/tree/release/3.1/Documentation#building](https://github.com/dotnet/source-build/tree/release/3.1/Documentation#building)

![2020-11-20_18-01](https://user-images.githubusercontent.com/74768319/99814777-83031380-2b5a-11eb-98ab-8b14cb8e5730.png) Thank you .. But I have such a problem, I don't understand how to solve.

**Comment by blackcross86** [comment]
> The support for 5.0 is fully complete yet: the functionality is there, but some minor issues are still being worked on
> 
> If you want to try it out:
> 
> ```
> git clone http://github.com/dotnet/source-build
> cd source-build
> git checkout master
> ./build.sh
> ```
> 
> That will produce a tarball that you can use. See https://github.com/dotnet/source-build/tree/release/3.1/Documentation#building

![2020-11-20_18-01](https://user-images.githubusercontent.com/74768319/99815309-29e7af80-2b5b-11eb-9456-ec705a5b2c54.png) 
Thank you .. But I have such a problem, I don't understand how to solve.

**Comment by omajid** [comment]
Sorry, that's not an error I am familiar with. It sounds like there's a networking issue, but I dont know if that's a software issue (incompatibility between your OS and .NET?) or a network outage.

Can you share more details about your environment? What OS is this? What architecture? Is the error reproducible?

**Comment by blackcross86** [comment]
> Sorry, that's not an error I am familiar with. It sounds like there's a networking issue, but I dont know if that's a software issue (incompatibility between your OS and .NET?) or a network outage.
> 
> Can you share more details about your environment? What OS is this? What architecture? Is the error reproducible?
I have Rosa linux x86_64 (rpm base), builds in mock environment.

**Comment by omajid** [comment]
> builds in mock environment

As I understand it, `mock` disables networking for builds. Is that what you are seeing? Building via `./build.sh` needs to use the network so `mock` won't work that way.

If you want to build using `mock`, you should create a tarball when connected to the internet (use `./build-source-tarball.sh`) and then build that tarball inside mock.

**Comment by blackcross86** [comment]
> > builds in mock environment
> 
> As I understand it, `mock` disables networking for builds. Is that what you are seeing? Building via `./build.sh` needs to use the network so `mock` won't work that way.
> 
> If you want to build using `mock`, you should create a tarball when connected to the internet (use `./build-source-tarball.sh`) and then build that tarball inside mock.

i am throwing network (resolv.conf) in mock But on host same error.

**Comment by blackcross86** [comment]
> > builds in mock environment
> 
> As I understand it, `mock` disables networking for builds. Is that what you are seeing? Building via `./build.sh` needs to use the network so `mock` won't work that way.
> 
> If you want to build using `mock`, you should create a tarball when connected to the internet (use `./build-source-tarball.sh`) and then build that tarball inside mock.

do in the .dotnet/corefx/cryptography/x509stores /my openssl pkcs12 -in myfile.pfx -nocerts -out private-key.pem -nodes folder, and update-ca-trust. The assembly went. Is it correct? How can I get around this on linux?
