### ISSUE TITLE
Remove Microsoft.NETCore.App.Host.linux-x64 prebuilts

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1905]
These were at one point categorized as SBRP, but they have native binaries in them (host templates) so that probably doesn't make sense:

```
Microsoft.NETCore.App.Host.linux-x64/3.0.3
Microsoft.NETCore.App.Host.linux-x64/3.1.7
```

Two options I see now.
* Add `<UseAppHost>false</UseAppHost>` in the projects that are using these, since we shouldn't be using them anyway. (Targeted fix.)
* Have the projects target `net5.0` and continue to generate apphosts as normal. (Forward fix.)

Approx usage of 3.1.7 (PackageDownload, so not in annotated report):

```
#> grep -i 'Microsoft.NETCore.App.Host.linux-x64/3.1.7' -l -r src
src/roslyn-analyzers.5c7721621bbab897c3ace6bf2c1489dda259eb9e/artifacts/obj/GenerateDocumentationAndConfigFiles/project.nuget.cache
src/roslyn-analyzers.5c7721621bbab897c3ace6bf2c1489dda259eb9e/artifacts/obj/GenerateGlobalAnalyzerConfigs/project.nuget.cache
src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/artifacts/obj/coreclr/ILVerify/project.nuget.cache
src/fsharp.da6be68280c89131cdba2045525b80890401defd/artifacts/obj/fsyacc/project.nuget.cache
src/fsharp.da6be68280c89131cdba2045525b80890401defd/artifacts/obj/fsi/project.nuget.cache
src/fsharp.da6be68280c89131cdba2045525b80890401defd/artifacts/obj/fsc/project.nuget.cache
src/fsharp.da6be68280c89131cdba2045525b80890401defd/artifacts/obj/AssemblyCheck/project.nuget.cache
src/fsharp.da6be68280c89131cdba2045525b80890401defd/artifacts/obj/fslex/project.nuget.cache
```

3.0.3:

```
#> grep -i 'Microsoft.NETCore.App.Host.linux-x64/3.0.3' -l -r src
src/linker.e792d61a0ead2f6422b4c9af651c1128d978d454/artifacts/obj/analyzer/project.nuget.cache
src/linker.e792d61a0ead2f6422b4c9af651c1128d978d454/artifacts/obj/Mono.Linker/project.nuget.cache
```

**Comment by omajid** [comment]
The roslyn-analyzer uses appear to be tools that are run during the build itself to produce all the build artifacts. I hope it's safe to bump them up to `net5.0`.

**Comment by dagood** [comment]
@omajid, are you planning to try that out? If those tools are launched via the `dotnet` host (or loaded as MSBuild tasks), the apphost shouldn't be needed, but either way works.

@tmds, maybe you would be interested in tackling some of these too?

(I have reservations about working towards solving the 2.0/2.1 app host prebuilts by upgrading to `net5.0`, because those ones are solvable very straightforwardly by SBRP--no binaries. Here though, SBRP doesn't seem to be an option, so it seems like a good opportunity to split up the work.)

**Comment by omajid** [comment]
> @omajid, are you planning to try that out?

Yes, but my Linux port has made the roslyn-analyzers build flaky (upstream and source-build), so I am trying to put out that fire first :cry: 

> If those tools are launched via the dotnet host (or loaded as MSBuild tasks), the apphost shouldn't be needed, but either way works.

Oh, right. They are lauched via `dotnet`: https://github.com/dotnet/roslyn-analyzers/blob/37eba3a5aa2d706745f37692ad7ba7cb0a66a115/eng/GenerateAnalyzerNuspec.targets#L100-L109

**Comment by omajid** [comment]
@dagood I have PRs out for roslyn-analyzers (upstream and source-build).

Want me to take a shot at something else too?

**Comment by dagood** [comment]
Awesome, thanks. I'll take a look at the `linker` one, if you can try `runtime` or `fsharp` that would be great.

**Comment by dagood** [comment]
I have a PR running for `linker` here: https://github.com/dotnet/source-build/pull/1908. I'm taking a look at `fsharp` now (but will return to `linker` if that PR goes red).

**Comment by omajid** [comment]
PR for runtime (ILVerify) here: https://github.com/dotnet/source-build/pull/1909

**Comment by tmds** [comment]
> @tmds, maybe you would be interested in tackling some of these too?

@dagood looks like these are all tacked. Feel free to throw something else my way.

**Comment by dagood** [comment]
Yeah, this should be fixed now. Waiting on the rolling build to confirm.

**Comment by dagood** [comment]
These two packages are gone in the latest build, updated the wiki. 🎉
