### ISSUE TITLE
Text-only packages built by SBRP have extra files in them (intermediate output, csproj)

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1906]
E.g. MicroBuild.Core 0.3.0 contains:

```
MicroBuild.Core.csproj
obj/project.assets.json
obj/MicroBuild.Core.csproj.nuget.dgspec.json
microbuild.core/0.3.0/Debug/netstandard1.3/MicroBuild.Core.assets.cache
...
```

These probably don't affect usage and I don't think we need to fix this for 5.0.0, but wanted to track the difference.

**Comment by MichaelSimons** [comment]
Flowed in with https://github.com/dotnet/installer/pull/13565.
