### ISSUE TITLE
Switch default branch to latest, not release/3.1

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1919]
Right now, the default branch is `release/3.1`. This means docs are maintained on `release/3.1` primarily, and the old *and new* branches have out of date docs. This makes it hard to add new info specific to a newer branch, because there's a bunch of stuff missing. We should probably have the newest branch be the default branch.

I think the reason we have 3.1 as the default is we want it to be what people encounter when they try to build this repo, since it's much more stable and likely to work at any random point in time. I think we should just be more ready to point people to a doc saying that the default branch is volatile and may not produce something they would consider usable.

/cc @dseefeld @crummel @dleeapho

**Comment by dseefeld** [comment]
@dagood to do this once we start using master for arcade-powered source-build.

**Comment by dagood** [comment]
Default branch is switched, and no need for the warnings yet because `master` still tracks 5.0 for now.
