### ISSUE TITLE
Design how to bootstrap a new distro/RID

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#192]
We should design and document how to bootstrap .NET Core on a new distro and/or architecture.

**Comment by dleeapho** [comment]
Once we have this, we should look at retiring [dotnet.bootstrap.py](https://github.com/dotnet/core/tree/master/tools/dotnet-bootstrap)

**Comment by omajid** [comment]
Can this be closed? This is mostly covered by the new boostrap script: https://github.com/dotnet/source-build/blob/master/Documentation/boostrap-new-os.md. At least, I was able to use it for a new distro.

**Comment by dseefeld** [comment]
Yes.  This is covered by the boostrap script.  Closing.
