### ISSUE TITLE
Microsoft.NETCore.App.Host.linux-x64/3.1.7 is still used as a prebuilt

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1931]
As of https://dev.azure.com/dnceng/internal/_build/results?buildId=900696&view=results (738ffd8), this is the offline baseline:

```xml
<Usage Id="Microsoft.AspNetCore.App.Ref" Version="5.0.0-rc.1.20451.17" />
<Usage Id="Microsoft.AspNetCore.App.Ref" Version="5.0.0" />
<Usage Id="Microsoft.NETCore.App.Host.linux-x64" Version="3.1.7" />
<Usage Id="Microsoft.NETCore.App.Ref" Version="5.0.0" />
```

The targeting packs are expected, but the apphost pack isn't. I get one grep result for it:

```
#> grep -i Microsoft.NETCore.App.Host.linux-x64/3.1.7 -r src
src/roslyn-analyzers.5c7721621bbab897c3ace6bf2c1489dda259eb9e/artifacts/obj/GenerateAnalyzerNuspec/project.nuget.cache:    "/work/packages/restored/microsoft.netcore.app.host.linux-x64/3.1.7/microsoft.netcore.app.host.linux-x64.3.1.7.nupkg.sha512"
```

Not 100% sure whether https://github.com/dotnet/source-build/pull/1907 regressed (with https://github.com/dotnet/source-build/pull/1902?) or my initial check wasn't thorough enough. /cc @omajid 

(Either way, we should probably make it a priority to get the baseline up to date to make sure we don't get more regressions as broader functional changes start going in like fixing OmniSharp. @dseefeld @crummel /cc @tmds)

**Comment by omajid** [comment]
Hm. I think we need to replace https://github.com/dotnet/source-build/blob/master/patches/roslyn-analyzers/0006-Disable-AppHost.patch with https://github.com/dotnet/roslyn-analyzers/pull/4451/files. That should remove the remaining AppHost.

**Comment by omajid** [comment]
I opened https://github.com/dotnet/source-build/pull/1932.

**Comment by omajid** [comment]
Microsoft.NETCore.App.Host.linux-x64/3.1.7 has been removed from the baseline with #1932.
