### ISSUE TITLE
what am I doing wrong?

### ISSUE THREAD

**Issue by blackcross86** [dotnet/source-build#1934]
![2020-12-01_10-23](https://user-images.githubusercontent.com/74768319/100709482-438cc080-33bf-11eb-88b9-bcea37c8646f.png)
[command-line-api.log](https://github.com/dotnet/source-build/files/5620853/command-line-api.log)

**Comment by dseefeld** [comment]
Your log indicates that it's looking for Microsoft.AspNetCore.App.Ref 3.1.8.  This seems to be missing from source-build-reference-packages.  Filed https://github.com/dotnet/source-build/issues/1940 to have it added.

**Comment by blackcross86** [comment]
> Your log indicates that it's looking for Microsoft.AspNetCore.App.Ref 3.1.8. This seems to be missing from source-build-reference-packages. Filed #1940 to have it added.

Thanks for the answer, and when will they add?

**Comment by dseefeld** [comment]
> > Your log indicates that it's looking for Microsoft.AspNetCore.App.Ref 3.1.8. This seems to be missing from source-build-reference-packages. Filed #1940 to have it added.
> 
> Thanks for the answer, and when will they add?

I'm working on them now.  I'll post the PRs when ready.

**Comment by dseefeld** [comment]
https://github.com/dotnet/source-build-reference-packages/pull/203 adds these to SBRP.

**Comment by dseefeld** [comment]
This issue should be fixed with #1942.

**Comment by blackcross86** [comment]
> This issue should be fixed with #1942.

thanks
