### ISSUE TITLE
NuGet.targets error MSB4018

### ISSUE THREAD

**Issue by blackcross86** [dotnet/source-build#1941]
![2020-12-07_19-19](https://user-images.githubusercontent.com/74768319/101376163-49077080-38c1-11eb-8e59-468147e106aa.png)
I attach the assembly log 
[build.log](https://github.com/dotnet/source-build/files/5653831/build.log)

**Comment by dagood** [comment]
Can you please post the text (using [a fenced code block](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)) in the future, not a screenshot?

```
DEBUG util.py:623:  Project "/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/init-build.proj" (1) is building "/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj" (2) on node 1 (Restore target(s)).
DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018: The "WarnForInvalidProjectsTask" task failed unexpectedly. [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018:    at NuGet.Common.RuntimeEnvironmentHelper.GetCurrentProcessFilePath() [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018:    at NuGet.Common.RuntimeEnvironmentHelper.<>c.<.cctor>b__25_4() [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018:    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
```

(Posting an excerpt and attaching the full log is good though, thanks.)

It looks like you hit an exception in this code in the .NET SDK toolset: https://github.com/NuGet/NuGet.Client/blob/3ef6cd3c0145e59314a495569c2d53296794fbf3/src/NuGet.Core/NuGet.Common/RuntimeEnvironmentHelper.cs#L87-L90

I don't know why that would happen, but it might have to do with your environment.

Could you read https://aka.ms/binlog and send us `/builddir/build/BUILD/dotnet5-5.0.100-x64/artifacts/log/Debug/BuildXPlatTasks_1206151819.binlog` if that's ok with you?
It will contain more detail, like what environment variables were set.

**Comment by blackcross86** [comment]
> Can you please post the text (using [a fenced code block](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)) in the future, not a screenshot?
> 
> ```
> DEBUG util.py:623:  Project "/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/init-build.proj" (1) is building "/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj" (2) on node 1 (Restore target(s)).
> DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018: The "WarnForInvalidProjectsTask" task failed unexpectedly. [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
> DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
> DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018:    at NuGet.Common.RuntimeEnvironmentHelper.GetCurrentProcessFilePath() [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
> DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018:    at NuGet.Common.RuntimeEnvironmentHelper.<>c.<.cctor>b__25_4() [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
> DEBUG util.py:623:  /builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet/sdk/5.0.100-rc.1.20452.10/NuGet.targets(309,5): error MSB4018:    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) [/builddir/build/BUILD/dotnet5-5.0.100-x64/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
> ```
> 
> (Posting an excerpt and attaching the full log is good though, thanks.)
> 
> It looks like you hit an exception in this code in the .NET SDK toolset: https://github.com/NuGet/NuGet.Client/blob/3ef6cd3c0145e59314a495569c2d53296794fbf3/src/NuGet.Core/NuGet.Common/RuntimeEnvironmentHelper.cs#L87-L90
> 
> I don't know why that would happen, but it might have to do with your environment.
> 
> Could you read https://aka.ms/binlog and send us `/builddir/build/BUILD/dotnet5-5.0.100-x64/artifacts/log/Debug/BuildXPlatTasks_1206151819.binlog` if that's ok with you?
> It will contain more detail, like what environment variables were set.

Sorry, but there is no such log , and there is no directory

**Comment by dagood** [comment]
> > Could you read https://aka.ms/binlog and send us `/builddir/build/BUILD/dotnet5-5.0.100-x64/artifacts/log/Debug/BuildXPlatTasks_1206151819.binlog` if that's ok with you?
> > It will contain more detail, like what environment variables were set.
> 
> Sorry, but there is no such log , and there is no directory

I don't know how that could happen, grabbed that path out of your log. 😕 What directories do exist that show up in that path?

Can you maybe go to the build directory and try running `find . -iname '*.binlog'`?

**Comment by blackcross86** [comment]
> I don't know how that could happen, grabbed that path out of your log.  What directories do exist that show up in that path?
> 
> Can you maybe go to the build directory and try running `find . -iname '*.binlog'`?

there is a path artifacts/obj/{semaphores, x64}.Only msbuild.binlog

**Comment by blackcross86** [comment]
I will attach in the binlog archive
[binlog.zip](https://github.com/dotnet/source-build/files/5681149/binlog.zip)

**Comment by dagood** [comment]
I'm sorry, I misread the command line. That's the right file, thanks. 😛

The closest thing I can find that someone has reported about this kind of error is https://github.com/dotnet/sdk/issues/4165. It mentions unsetting an environment variable called `DYLD_FALLBACK_LIBRARY_PATH` to make things work, but I don't see that env var in your binlog.

I'm kind of at a loss. Maybe you can try for a simpler repro that directly uses the API that seems to throw? Something like:

1. `export PATH="$PATH:/builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet"`
2. Go to `/tmp` (or anywhere other than the source-build dir): `dotnet new console -o repro && cd repro`
3. Replace contents of `Program.cs`:
   ```cs
   using System;
   using System.Diagnostics;
   
   using (var process = Process.GetCurrentProcess())
   {
       Console.WriteLine(process.MainModule.FileName);
   }
   ```
4. `dotnet run`

I get `/tmp/repro/bin/Debug/net5.0/repro` printed to my logs with that.

My hope is that this causes the same exception, and experts on the runtime and libraries can take a look without source-build getting in the way.

You could also try to repro using the SDKs available at https://dotnet.microsoft.com/download/dotnet/5.0. (`/builddir/build/BUILD/dotnet5-5.0.100-x64/.dotnet` should be a copy of the 5.0.100-rc.1 SDK, but it wouldn't hurt to try to repro with the stable builds, and without source-build involved at all.)

**Comment by blackcross86** [comment]
> My hope is that this causes the same exception, and experts on the runtime and libraries can take a look without source-build getting in the way.

I did what you wrote, but there were no such exceptions.Maybe because the assembly is happening in docker? I will attach another log
[sourcelink.log](https://github.com/dotnet/source-build/files/5697307/sourcelink.log)

**Comment by dagood** [comment]
Yeah, you need to try to repro in the same environment that the build happened in. If you built in a Docker container, you need to run the repro steps in a Docker container set up the same way (or even the same Docker container).

> I will attach another log

Where did this come from? How did you get to a sourcelink build, when you got stopped by a failure earlier in the process? What does the binlog say for this build (I can't find anything interesting in that log file alone). This is very confusing.

**Comment by blackcross86** [comment]
> What does the binlog say for this build (I can't find anything interesting in that log file alone).
[msbuild-binlog.zip](https://github.com/dotnet/source-build/files/5698336/msbuild-binlog.zip)

**Comment by blackcross86** [comment]
> Where did this come from? How did you get to a sourcelink build, when you got stopped by a failure earlier in the process? 
I didn't understand anything myself, maybe they corrected something in the source code.

**Comment by dseefeld** [comment]
@blackcross86 Did you manage to repro this without source-build?  Are you still having issues with this?

**Comment by blackcross86** [comment]
> @blackcross86 Did you manage to repro this without source-build? Are you still having issues with this?

Yes, there are problems, everything builds fine on the computer. But when I build on abf rosalinux, the build crashes. Logs in the archive.
[logs.zip](https://github.com/dotnet/source-build/files/5784519/logs.zip)

**Comment by dagood** [comment]
This might be related to this issue in dotnet/sdk--it has the same first few lines in the stack trace: https://github.com/dotnet/sdk/issues/13474.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.Muxer..ctor()
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging..ctor(IEnumerable`1 argsToForward, String msbuildPath)
   at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp..ctor(IEnumerable`1 argsToForward, String msbuildPath)
   at Microsoft.DotNet.Tools.MSBuild.MSBuildCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

I suggest you try to reproduce the issue by running the steps I mentioned in https://github.com/dotnet/source-build/issues/1941#issuecomment-743439591 inside your Docker container, then post that to https://github.com/dotnet/sdk/issues/13474. That info may help them figure out what the bug is.

Or, if my steps don't actually give any useful information, https://github.com/dotnet/sdk/issues/13474 is still the best place to get help with this.

**Comment by DuratarskeyK** [comment]
I managed to replicate an error this way:
`[root@newpc repro]# unshare -p --fork /bin/bash
[root@newpc repro]# dotnet run
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.Muxer..ctor()
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging..ctor(IEnumerable`1 argsToForward, String msbuildPath)
   at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp..ctor(IEnumerable`1 argsToForward, String msbuildPath)
   at Microsoft.DotNet.Tools.Run.RunCommand.EnsureProjectIsBuilt()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)`
After entering a pid namespace it all crashes. This is what @dagood suggested, except my Program.cs is:
`using System;
using System.Diagnostics;

public class Program
{
        public static void Main()
        {
                using (var process = Process.GetCurrentProcess())
                {
                        Console.WriteLine(process.MainModule.FileName);
                }
        }
}`
If I remount proc though it all goes away, albeit wasn't able to fix it by doing that in out builders.

**Comment by dagood** [comment]
@DuratarskeyK That info looks useful, but this issue is closed (not the right repo to address it, and *might* be a duplicate)--I'd recommend you file a new issue in dotnet/sdk, and include which version of the .NET SDK you're using to reproduce the problem.
