### ISSUE TITLE
Add OmniSharp smoke-test

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1950]
@omajid made this nice and simple OmniSharp test script: https://gist.github.com/omajid/4e7b0d4571f94e5c49fc608bad287428

We should consider putting it in as a smoke-test (and pinning the OmniSharp release version for reliability) to make sure we don't regress here again.

**Comment by omajid** [comment]
Omnisharp forks processes in the background and that script doesn't clean up very well, hanging in CI for all child processes to die. Here's my updated version: https://github.com/redhat-developer/dotnet-regular-tests/blob/main/omnisharp/test.sh

**Comment by MichaelSimons** [comment]
Implemented with https://github.com/dotnet/installer/pull/12251.
