### ISSUE TITLE
Add text only templates to tarball instead of building in SBRP

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1954]
A set of text-only templates rev fairly regularly.  These have been added to SBRP so they don't show up as prebuilts.  These should be captured during the production build and built in the tarball, rather than SBRP.

**Comment by dagood** [comment]
It looks like this means reverting (or reimplementing) stuff removed in this commit: https://github.com/dotnet/source-build/commit/b6c2aa362d872e7367c8fbf41e387ca9af099056#diff-1be4c0801784cdae56987501f63b65ef925c4b51b58e0c96e554cefcec7a1bb4

**Comment by dseefeld** [comment]
This will not be ported to 3.1 currently, since there doesn't seem to be additional text-only prebuilts added every release in 3.1.  If it becomes an issue, this can be ported.
