### ISSUE TITLE
[SBRP] generate.sh doesn't handle LangVersion automatically

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1956]
There are some "fixups" for specific packages, but this isn't handled automatically. This means that the person adding packages to SBRP needs to be able to quickly understand and react to the compile errors that result from using unavailable features. (Such as `where T : struct`.)

Shouldn't we always use the latest unless there's a reason not to? At least, always emit the lang version that GenAPI is set up to emit?

**Comment by ViktorHofer** [comment]
I think we should close this issue as `LangVersion` already default to `latest`: https://github.com/dotnet/source-build-reference-packages/blob/9b3501d37b4e88be557e595eb309d74a7dff76e6/src/referencePackages/Directory.Build.props#L48
