### ISSUE TITLE
[SBRP] generate.sh doesn't handle "<icon>" in reference package nuspecs

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1957]
The tooling generated some nuspecs with `<icon>Icon.png</icon>`, but without placing the file. It should either point at a central file (avoid many duplicates of the same file) or remove the icon because we don't need it in this context.

**Comment by tkapin** [comment]
@MichaelSimons - I've added area-product-experience label to this based on our recent conversation. Please feel free to remove it if you think it shouldn't be labeled so.

**Comment by MichaelSimons** [comment]
Just like the runtime repo - we only allow one area per issue.  This really is an sbrp issue so I assigned it to area-sbrp.  The area-product-experience is intended for the source-build product experience.
