### ISSUE TITLE
[SBRP] (pre-arcade) reference package build order shouldn't be manually maintained

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1959]
https://github.com/dotnet/source-build-reference-packages/blob/pre-arcade/src/referencePackages/src/ProjectsToBuild.props is the full list of reference packages being built, **manually topologically sorted**. This list should be an emergent property of the projects, or there should not be an order at all. At worst, dotnet-source-build-utilities should automatically maintain the hard-coded sorted list.

See also https://github.com/dotnet/source-build/issues/1690 about post-arcade branches. (There is no order at all there currently, and automatic P2P references is a goal in order to reduce online dependencies during SBRP production build.)

**Comment by MichaelSimons** [comment]
[Triage] This is no longer an issue post-arcade.  Closing as obsolete.
