### ISSUE TITLE
Potentially standardize patch application target in arcade-powered source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1967]
We could potentially standardize a patch-applying target in dotnet/arcade to use throughout the .NET repos for initial implementation of arcade-powered source-build infra.

Currently, I *expect* patching can be done by adding an MSBuild target in a customized `eng/SourceBuild.props` file. If this is true, there doesn't seem to me to be a good reason to add a standard patch application target:
* We expect to remove patches from the repos quickly.
* The target *should* be simple enough that there won't be any benefit to having a central implementation that we can patch once for everyone.
* It's simpler to edit/maintain the target for repo-specific quirks if the target is stored inside the repo itself.

I think we need to try it out to make sure `eng/SourceBuild.props` can really do this, and go from there.

**Comment by dseefeld** [comment]
As noted above, we expect these patches to be short-lived, so maintaining this infra may not be worth it.  Closing.
