### ISSUE TITLE
Make it reasonable to add packages to SBRP, as a downstream repo source-build champ who needs more

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1969]
This involves:
* Making the SBRP tooling public.
* Documenting the SBRP tooling and/or making improvements to how it's used to make it reasonable for a repo's champ.

**Comment by crummel** [comment]
Related: https://github.com/dotnet/source-build/issues/3091, https://github.com/dotnet/source-build/issues/3089, https://github.com/dotnet/source-build/issues/3054, https://github.com/dotnet/source-build/issues/3044, https://github.com/dotnet/source-build/issues/3038, https://github.com/dotnet/source-build/issues/2804, https://github.com/dotnet/source-build/issues/1968, https://github.com/dotnet/source-build/issues/1958, https://github.com/dotnet/source-build/issues/1957, https://github.com/dotnet/source-build/issues/1956, https://github.com/dotnet/source-build/issues/1690.

**Comment by MichaelSimons** [comment]
I am making the assertion that the spirit of this issue has been completed during the .NET 8.0 release.  Of course there are more things that can be done to improve this process.  We are expecting repo developers to be adding their own SBRPs following the  [documented instructions](https://github.com/dotnet/source-build-reference-packages/blob/main/README.md#adding-new-packages).  This process has been proven out via several contributions outside of the source-build team.
