### ISSUE TITLE
Fix arcade-powered source-build intermediate nupkgs blocking signing validation in official build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1984]
Right now, the intermediate nupkg is not signed, and the nupkgs inside the intermediate nupkg aren't signed. Signing validation in the official build fails and lists both of these as errors. (When it's turned on--didn't catch this in SBRP because we've never signed anything there.)

Could we sign them? Perhaps, that makes them a different from the actual source-build, but it *shouldn't* change much. However, AFAIK there is no common/shared Arcade infra for signing nupkgs that were built on Linux. (I'm only familiar with the dotnet/runtime implementation, which takes some effort.)

Could we skip validation? This keeps the build the same as a real source-build. It also sounds easier. It doesn't look like there's currently any infra to programmatically skip packages, though--only a single txt file checked in at `eng/`. I don't think we should manually write exclusions for the intermediate nupkg into that file for every single repo.

https://dev.azure.com/dnceng/internal/_build/results?buildId=951564

**Comment by dseefeld** [comment]
Fixed with dotnet/arcade#6806
