### ISSUE TITLE
Implement auto-dependency flow CoreFX, Standard

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#199]

**Comment by dagood** [comment]
Splitting off ones that I'm not actively working on:

 * https://github.com/dotnet/source-build/issues/200 CoreCLR
 * https://github.com/dotnet/source-build/issues/201 Core-Setup

**Comment by dagood** [comment]
@eerhardt @weshaggard 

My current progress on this issue: https://github.com/dotnet/source-build/compare/dev/release/2.0...dagood:flow-api. It should be pretty well organized by commit. The work is on top of https://github.com/dotnet/source-build/pull/195 and I cherry-picked in https://github.com/dotnet/source-build/pull/207 too.

**Comment by dagood** [comment]
This was merged in with https://github.com/dotnet/source-build/pull/219, thanks @eerhardt!
