### ISSUE TITLE
Arcade-powered source-build: onboarding doc improvements

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2010]
Some improvements to make to the onboarding docs and process based on dotnet/arcade onboarding feedback and experience:

* The arcade-template-based part of the CI onboarding doc should include:
  * What the implementer should expect to see (a new CI leg with a certain name).
  * The intent: a new job in the same pipeline as the others--the yml config should be the *only* change necessary for repos that stick closely to the Arcade template. (No need to create a new pipeline.)
* We should probably have some boilerplate ready to go that we can use to file issues on the repo that provides some context and the motivation behind the work we're asking the repo champion to implement.
  * I wrote out a little of this in https://github.com/dotnet/arcade/issues/6845 and https://github.com/dotnet/arcade/issues/6879.
  * Describe what the deal is with patch files--we're familiar but not everyone has been part of a patch incorporation push before.
  * Make the ask more explicit in the issue itself ("submit a PR that does X and let us know if CI hits an error that isn't familiar", "review and merge PR X that we submitted")

**Comment by MichaelSimons** [comment]
Closing as the repo work is almost complete.
