### ISSUE TITLE
[ArPow] determine how to work with repos using Arcade 1.0 (release/3.x)

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2013]
dotnet/roslyn `master` is on Arcade 1.0 (`release/3.x`), not Arcade 6.0 (or even Arcade 5.0). This is a problem because the arcade-powered source-build work so far is only in Arcade 6.0. I think we can either:

1. Port arcade-powered source-build back to dotnet/arcade `release/3.x`.
   * And `release/5.0`, so if dotnet/roslyn upgrades from 1.0 -> 5.0, it still has arcade-powered source-build.
2. Figure out how to have Roslyn use Arcade 1.0 for the Microsoft build, and 6.0 for our arcade-powered source-build job.
   * The big thing to figure out here is how to have one subscription auto-update the 1.0 Arcade tooling, and another subscription separately update the 6.0 tooling. I don't think Maestro++ has a mechanism for depending on the same repo twice like this.

**Comment by dagood** [comment]
MSBuild will update to Arcade 6, so we don't have to worry about this there: https://github.com/dotnet/msbuild/issues/6119.

Roslyn might also update (there is no known reason not to) but not sure yet if they're going to do that.

**Comment by dagood** [comment]
I cloned a bunch of repos that will be part of ArPow and looked at which version they have in the default branch. A few more:
```
./vstest/global.json
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.21072.7",
./clicommandlineparser/global.json
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19207.1"
```

**Comment by MichaelSimons** [comment]
All repos who are on Arcade have upgraded to 6.0.
