### ISSUE TITLE
[ArPow] Add strict coherent parent dependency transitive graph to each repo to reduce dependencies

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2017]
In https://github.com/dotnet/source-build/issues/1563, we stopped trying to force coherency, and decided to store in every repo the full list of transitive dependencies on upstream repos.

In ArPow, these stand out in the prebuilt reports: packages like sourcelink being prebuilt. E.g. aspnet/xdt has a dependency on dotnet/arcade, but none on dotnet/sourcelink.

I think we should go ahead without adding these at first:
* We aren't enforcing a baseline on prebuilts in the repo builds yet.
* This would slow down initial ArPow implementation.
* The Microsoft-built assets *should* behave the same as the source-build assets. In some cases it's more important to get the build running using source-build bits (dotnet/runtime), and we can decide that on a case-by-case basis. (This is only if the dependencies are missing in the first place, which normally shouldn't be the case.)

Later, polishing this up will be part of stage 4, when we try to reduce per-repo prebuilts to the minimal level so that we can enforce a baseline that prevents regression.

**Comment by MichaelSimons** [comment]
[Triage] Closing as obsolete.
