### ISSUE TITLE
Update release/2.1 ProdConFeed.txt process

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2033]
With the new single NuGet feed requirement ProdConFeed.txt in release/2.1 was changed to an internal AzDo feed to avoid tripping the warning task.  When we change this back for the next release, internal release/2.1 updates may trip the detector task for multiple NuGet feeds.  We may need to take another approach to injecting the ProdCon feed or get an exception for the release/2.1 branch.

**Comment by crummel** [comment]
This also may apply to smoke-testNuGet.config - extra feeds that may include needed templates were removed and may need to be restored temporarily for internal builds and then removed again when the build goes public.

**Comment by dagood** [comment]
Triage: @crummel will look at this and update the checklist with any new steps needed.

**Comment by MichaelSimons** [comment]
2.1 is EOL.  This issue is obsolete.
