### ISSUE TITLE
[ArPow] Onboard clicommandlineparser to arcade-powered source-build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2037]

**Comment by MichaelSimons** [comment]
In progress with https://github.com/dotnet/CliCommandLineParser/pull/177

**Comment by MichaelSimons** [comment]
@crummel, I tried building CliCommandLineParser repo with the ArPow command and encountered some issues.  While investigating I noticed the [repo is on Arcade 1.x](https://github.com/dotnet/CliCommandLineParser/blob/master/eng/Version.Details.xml#L6).  How is ArPow working in this repo?
