### ISSUE TITLE
[ArPow] Onboard symreader to arcade-powered source-build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2040]

**Comment by crummel** [comment]
In progress with https://github.com/dotnet/symreader/pull/235.

**Comment by omajid** [comment]
PR was merged; can someone please look over the internal build to see if it looks okay?

**Comment by MichaelSimons** [comment]
The internal build is failing for pre-existing issues.  I logged https://github.com/dotnet/symreader/issues/236 to track the issue.

**Comment by MichaelSimons** [comment]
The symreader build issues have been resolved and I have verified the intermediate NuGet package is being created with the expected contents.
