### ISSUE TITLE
[ArPow] Onboard test-templates to arcade-powered source-build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2041]

**Comment by omajid** [comment]
PR: https://github.com/dotnet/test-templates/pull/126

**Comment by omajid** [comment]
PR was merged last week.

**Comment by dagood** [comment]
Here's an internal/official build that ran with that change that we can run through the source-build-side stage 3: https://dev.azure.com/dnceng/internal/_build/results?buildId=995058&view=results

**Comment by dagood** [comment]
I took a look, and the artifacts look reasonable. The prebuilt report is pointing out that it seems to be missing `<SourceBuild...>` elements to grab ArPow-built arcade, ref packages, sourcelink, and xliff-tasks. Everything there except the Arcade one requires darc, to set up subscriptions, so I think it's reasonable to leave it as it is for now and burn down these prebuilts when we get to stage 4.

(In case I haven't mentioned it elsewhere before, these aren't going to necessarily end up as prebuilts in the final tarball: the inputs and flow being more strict should force source-build usage just like it does in dotnet/source-build.)
