### ISSUE TITLE
[ArPow] Create tarball generation and tarball build infrastructure for dotnet/installer

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2063]
Once ArPow is complete through dotnet/installer, there's still work to do to generate the tarballs.

1. Infrastructure to clone the repos from dotnet/installer's Versions.Details.xml and put it in a tarball location. Following dotnet/source-build, this could be `darc clone`, but it would be nice to make it a lot simpler (and maybe faster) before then: https://github.com/dotnet/source-build/issues/1571
2. A full "strict coherent parent dependency" graph accessible in dotnet/installer, to put together a coherent set of repos. This just means we have to *pick* one version of each repo to work with--the build itself will probably not be fully coherent.
    * If it's not up to date, might need more work to fill it in, like https://github.com/dotnet/installer/pull/8377.
    * Some work might be needed in the repos to flow this along: https://github.com/dotnet/source-build/issues/2017.
    * More info on "strict coherency": https://github.com/dotnet/arcade/issues/5195.
3. Infra to copy build tooling into the tarball to make it self-buildable.
    * May involve copying a chunk of dotnet/source-build `release/5.0` infra into dotnet/installer `eng/SourceBuildTarball/*`.
    * There's a balance to make here. How much infra can be removed and replaced with ArPow's Arcade-side infra? Should we actually start using intermediate nupkgs in the tarball build as a way to safely segment up incremental builds (#928)?
4. Infra to publish the tarball as a public artifact from each official build. Note that we *should* be able to have one tarball serve all RIDs (https://github.com/dotnet/source-build/issues/1412, #298), but we can publish more tarballs if this doesn't end up working for 6.0.

This infra might make sense to permanently house in dotnet/installer's eng/ dir. dotnet/installer will be the only place producing tarballs for the foreseeable future, and having the code live in the repo directly rather than putting it in Arcade makes it significantly more maintainable when issues or new features come up.

To do an early prototype, we can choose a build subgraph and implement all of these steps there. (Any strict coherent parent dependencies are good incremental progress on other goals too (stage 4), and the bulk of the infra could probably just be moved to dotnet/installer when the full ArPow build graph is ready.)

**Comment by crummel** [comment]
Triage: @dseefeld to start proving this out after his 6.0 work.

**Comment by MichaelSimons** [comment]
Consider including https://github.com/dotnet/source-build/issues/1694 as part of this work.

**Comment by dseefeld** [comment]
Completed  with https://github.com/dotnet/installer/pull/10961
