### ISSUE TITLE
[ArPow] Onboard NuGet.client to arcade-powered source-build 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2069]
- [x] ArPow wrapper: [in progress](https://github.com/NuGet/NuGet.Client/pull/4105) (crummel).
- [x] Introduce Arcade to NuGet repo: [in progress](https://github.com/NuGet/NuGet.Client/pull/3945) (crummel).
- [x] build.sh changes: blocked by above (NuGet team).
- [x] CI leg: [in progress](https://github.com/NuGet/NuGet.Client/pull/4105) (crummel).
- [ ] Reconcile patches: blocked by CI (shared crummel/NuGet).

**Comment by crummel** [comment]
ArPow-blocking work is done.  Put the rest into https://github.com/dotnet/source-build/issues/2310 and https://github.com/dotnet/source-build/issues/2311.
