### ISSUE TITLE
[ArPow] Onboard roslyn-analyzers to arcade-powered source-build 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2071]

**Comment by omajid** [comment]
PR: https://github.com/dotnet/roslyn-analyzers/pull/4930 (not complete, yet)

**Comment by MichaelSimons** [comment]
I was validating the internal builds to ensure the source-build intermediate NuGet package was getting built and published.  The only internal CI build I found is https://dev.azure.com/dnceng/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=830&branch=main (internal link) which is wired up to https://github.com/dotnet/roslyn-analyzers/blob/main/azure-pipelines-microbuild.yml.  This pipeline yaml was not updated to include the source-build leg.  @sharwell, can you confirm there isn't a internal CI build running for https://github.com/dotnet/roslyn-analyzers/blob/main/azure-pipelines.yml?  If not, we will need to add the source-build leg to `azure-pipelines-microbuild.yml`.

**Comment by sharwell** [comment]
This is the pipeline for signed builds from dotnet/roslyn-analyzers: https://dev.azure.com/dnceng/internal/_build?definitionId=830&_a=summary
