### ISSUE TITLE
[ArPow] Onboard websdk to arcade-powered source-build 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2073]

**Comment by omajid** [comment]
Is this https://github.com/dotnet/websdk ? That says:

> This Repo has moved!

> This repo has been merged into https://github.com/dotnet/sdk. Previous releases (prior to .NET 5) will still be serviced out of this repo.

Digging through source-build's 5.0 branch, I see no websdk patches or proj file. `patches/sdk/0018-Ensure-WebSdk-projects-finish-before-PublishNetSdks.patch` talks about it, but that seems to indicate that this is indeed part of dotnet/sdk repo.

**Comment by MichaelSimons** [comment]
@omajid - you are correct.  Thanks for pointing this out.  This appears to be a remnant from 3.1.  I will remove it from the table.
