### ISSUE TITLE
[ArPow] Onboard vstest to arcade-powered source-build 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2076]

**Comment by omajid** [comment]
vstest seems to be an older version of arcade:

    ./build.sh -c Release --restore --build --pack /p:ArcadeBuildFromSource=true -bl

Doesn't seem to do anything different for source-build. `Version.Details.xml` says:

    <Dependency Name="Microsoft.DotNet.Arcade.Sdk" Version="1.0.0-beta.21123.5"

**Comment by MichaelSimons** [comment]
I logged https://github.com/microsoft/vstest/issues/2804 to track upgrading the Arcade version.
