### ISSUE TITLE
smoke-test.sh --targetRid argument isn't read in time

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2081]
Currently this needs to be an environment variable, reading the argument just needs to move to before we depend on the targetRid.

**Comment by omajid** [comment]
Hey, @crummel are you still looking into this? Would it be okay if I did a PR for this?

**Comment by crummel** [comment]
Sure, I haven't really done anything on it yet.  Thanks!

**Comment by omajid** [comment]
Can we close this now? Does this need to be ported to additional branches?

**Comment by omajid** [comment]
Hearing no objections, closing it now.
