### ISSUE TITLE
[OSX] libcoreclrpal.a has no symbols

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2091]
```/Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcoreclrpal.a(context.S.o) has no symbols```

Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=1036678&view=logs&j=a59ff6a2-9e96-5a3b-b5d4-48ceb0364bde&t=80689c54-0f3e-5a76-9a71-2fd026be971e&l=4070

**Comment by MichaelSimons** [comment]
[Triage] MacOS support is being tracked with #2909
