### ISSUE TITLE
how to fix the error? dotnet 3.1 RID

### ISSUE THREAD

**Issue by blackcross86** [dotnet/source-build#2095]
![2021-03-18_03-30](https://user-images.githubusercontent.com/74768319/111555998-a0f42400-879a-11eb-9b78-8feccb4aa3b5.png)

```
NAME="ROSA Desktop Fresh R12"
VERSION="2019.1 (EE 2019.1 Desktop)"
ID="rosa"
VERSION_ID="2019.1"
BUILD_ID="20201213.21"
PRETTY_NAME="ROSA Desktop Fresh R12 2019.1 (EE 2019.1 Desktop)"
VERSION_CODENAME="(EE 2019.1 Desktop)"
ANSI_COLOR="1;43"
CPE_NAME="cpe:/o:rosa:rosalinux:2019.1"
HOME_URL="http://www.rosalinux.com//"
BUG_REPORT_URL="https://bugs.rosalinux.ru/"
SUPPORT_URL="https://forum.rosalinux.ru/"
PRIVACY_POLICY_URL="https://www.rosalinux.ru/products/rosa-fresh/"

```

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.112
 Commit:    cd75074bf4

Runtime Environment:
 OS Name:     rosa
 OS Version:  2019.1
 OS Platform: Linux
 RID:         rosa.2019.1-x64
 Base Path:   /usr/lib64/dotnet/sdk/3.1.112/

Host (useful for support):
  Version: 3.1.12
  Commit:  899abf95fa

.NET Core SDKs installed:
  3.1.112 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by omajid** [comment]
I generally see this error from roslyn when the SDK that's being used to build roslyn doesn't have the runtime id (RID) in it's RID graph.

This `rosa.2019.1-x64` RID is probably missing from the `RuntimeIdentifierGraph.json` file under `/usr/lib64/dotnet/sdk/3.1.112/`.

I generally have to use a patch like https://src.fedoraproject.org/rpms/dotnet5.0/blob/a36231563c01b8257a7a703e8505519b8773e895/f/runtime-48203-fedora-35-rid.patch to add new RIDs in the correct place in the RID graph.

**Comment by omajid** [comment]
The general issue here is also captured by https://github.com/dotnet/source-build/issues/297

**Comment by blackcross86** [comment]
![2021-03-19_03-29](https://user-images.githubusercontent.com/74768319/111714803-83d75800-8863-11eb-9eac-6813526e5d10.png)
> > I generally have to use a patch like https://src.fedoraproject.org/rpms/dotnet5.0/blob/a36231563c01b8257a7a703e8505519b8773e895/f/runtime-48203-fedora-35-rid.patch to add new RIDs in the correct place in the RID graph.

error again. what is it

``` diff

--- a/pkg/Microsoft.NETCore.Platforms/runtimeGroups.props	2021-02-27 22:01:04.000000000 +0300
+++ b/pkg/Microsoft.NETCore.Platforms/runtimeGroups.props	2021-03-19 02:42:51.689038577 +0300
@@ -125,6 +125,13 @@
       <Versions>9</Versions>
     </RuntimeGroup>

+    <RuntimeGroup Include="rosa">
+      <Parent>linux</Parent>
+      <Architectures>x64;arm64</Architectures>
+      <Versions>2019.1;2019.05</Versions>
+      <TreatVersionsAsCompatible>false</TreatVersionsAsCompatible>
+    </RuntimeGroup>
+
     <RuntimeGroup Include="sles">
       <Parent>linux</Parent>
       <Architectures>x64</Architectures>

```

**Comment by omajid** [comment]
`runtimeGroups.props` is used to generate the `runtime.json` and `runtime.compatiblity.json` files. The build is complaining that you have updated the props file but not the json files. The files being inconsistent is generally a mistake.

[This readme](https://github.com/dotnet/corefx/tree/release/3.1/pkg/Microsoft.NETCore.Platforms#adding-a-new-os) describes the workflow for updaitng the json file. Basically, you do a one-time build with `/p:UpdateRuntimeFiles=true` to automatically update the json files from the props file, and then commit the result.

The way I generally do this is by grabbing the `release/3.1` branch from the https://github.com/dotnet/corefx repo, updating the `runtimeGroups.props` file in there, and building with `/p:UpdateRuntimeFiles=true`:

    ./build.sh /p:UpdateRuntimeFiles=true

Then I get a patch that updates all three files, like along the lines of https://src.fedoraproject.org/rpms/dotnet5.0/blob/a36231563c01b8257a7a703e8505519b8773e895/f/runtime-48203-fedora-35-rid.patch. I then  apply that when building source-build 3.1.

**Comment by blackcross86** [comment]
> `runtimeGroups.props` is used to generate the `runtime.json` and `runtime.compatiblity.json` files. The build is complaining that you have updated the props file but not the json files. The files being inconsistent is generally a mistake.
> 
> [This readme](https://github.com/dotnet/corefx/tree/release/3.1/pkg/Microsoft.NETCore.Platforms#adding-a-new-os) describes the workflow for updaitng the json file. Basically, you do a one-time build with `/p:UpdateRuntimeFiles=true` to automatically update the json files from the props file, and then commit the result.
> 
> The way I generally do this is by grabbing the `release/3.1` branch from the https://github.com/dotnet/corefx repo, updating the `runtimeGroups.props` file in there, and building with `/p:UpdateRuntimeFiles=true`:
> 
> ```
> ./build.sh /p:UpdateRuntimeFiles=true
> ```
> 
> Then I get a patch that updates all three files, like along the lines of https://src.fedoraproject.org/rpms/dotnet5.0/blob/a36231563c01b8257a7a703e8505519b8773e895/f/runtime-48203-fedora-35-rid.patch. I then apply that when building source-build 3.1.

thanks a lot, helped

**Comment by omajid** [comment]
@crummel @dseefeld @MichaelSimons is there any documentation for updating RIDs for source-build? Would it be useful to have? I can take the notes from above and write up some new docs..

**Comment by blackcross86** [comment]
I can only provide a patch for Rosalinux.

**Comment by crummel** [comment]
I don't think there is, it would be great if you want to write something up.  I could also use something like that in my proposal for https://github.com/NuGet/Home/issues/5862.
