### ISSUE TITLE
Investigate using OSX image for CI instead of default pool

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2100]
runtime appears to use a specific OSX image which means they run into fewer issues like https://github.com/dotnet/source-build/issues/2091, https://github.com/dotnet/source-build/pull/1962, https://github.com/dotnet/source-build/pull/1817, https://github.com/dotnet/source-build/issues/1757, https://github.com/dotnet/source-build/issues/1739, https://github.com/dotnet/source-build/issues/1685, https://github.com/dotnet/source-build/pull/1542, https://github.com/dotnet/source-build/pull/1363.  We should look into this and see if it's an options for us.

**Comment by MichaelSimons** [comment]
[Triage] MacOS support is being tracked with #2909
