### ISSUE TITLE
Unable to build-source-tarbal for v5.0.104 

### ISSUE THREAD

**Issue by lupin-de-mid** [dotnet/source-build#2112]
I try switch from netcore 3 to dotnet 5, but i'm unable to build `v5.0.104-sdk` on early stages
Same results if call `./build.sh`

error when checkout artifacts/src/linker/external/cecil

full log [build_log.txt](https://github.com/dotnet/source-build/files/6257075/build_log.txt)

```
s /home/user/tarball/source-build/artifacts/src/linker/external/cecil
user@astra16:~/tarball/source-build$ ls -a /home/user/tarball/source-build/artifacts/src/linker/external/cecil
.  ..  .git
user@astra16:~/tarball/source-build$ ls -a /home/user/tarball/source-build/artifacts/src/linker/external/cecil/.git 
/home/user/tarball/source-build/artifacts/src/linker/external/cecil/.git
user@astra16:~/tarball/source-build$ cat  /home/user/tarball/source-build/artifacts/src/linker/external/cecil/.git 
gitdir: /home/user/tarball/source-build/.git/modules/src/linker.git/modules/external/ceciluser@astra16:~/tarball/source-build$ 
```

**Comment by omajid** [comment]
From Gitter:

>  I successfully create two archive based on script https://src.fedoraproject.org/rpms/dotnet5.0/blob/rawhide/f/build-dotnet-tarball with - boostrap and without.

Sounds like this issue can be closed now?
