### ISSUE TITLE
5.0.104 creates map files with a file size of 0

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2114]
5.0.104/5.0.4 creates a number of map files for debug symbols. Some of them have a file size of 0. For example:

```
$ ls -l '/usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.4/Microsoft.VisualBasic.ni.{2e6b171e-f5af-4f1b-8464-9cfe0cc3282d}.map' 
-rw-r--r--. 1 root root 0 Mar 17 14:35 /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.4/Microsoft.VisualBasic.ni.{2e6b171e-f5af-4f1b-8464-9cfe0cc3282d}.map
```

An empty files seems very strange. Is the 0-byte size expected? Is there some way to verify that this file is valid/usable?

cc @tmds

**Comment by MichaelSimons** [comment]
[Triage] @dseefeld, please take a look to see if this is specific to 5.0.104 or if it affects 5.0.200 as well.

**Comment by omajid** [comment]
I just finished building 5.0.202 on Fedora, so I can confirm this is still there:

```
$ ls -l /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.5/Microsoft.VisualBasic.ni.\{f9c7e647-10b9-4140-91a1-93aca083c5bd\}.map 
-rw-r--r--. 1 root root 0 Apr 15 14:04 /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.5/Microsoft.VisualBasic.ni.{f9c7e647-10b9-4140-91a1-93aca083c5bd}.map
```

**Comment by MichaelSimons** [comment]
[Triage] Closing as this is obsolete.  Please open a new issue if this is still relevant in a supported release.
