### ISSUE TITLE
Automation improvements

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2123]
#### Situation
There are currently many manual steps in and around our [build and release process](https://github.com/dotnet/source-build/blob/main/.github/ISSUE_TEMPLATE/releases/release_checklist.md) for servicing.  These cause problems because they can be easily forgotten, they may not be done consistently between servicing events, and they make servicing take longer.

#### Objective
Improve servicing ease and turn-around times by automating work that is currently done manually.  Prioritize work that is easier to automate and takes the most effort manually.

#### Execution
Identify opportunities for automating manual servicing work, estimate and prioritize them.  All these improvements should be small and independent so improvements can be made gradually whenever we have time.  Ideally we will make at least one improvement per servicing cycle that we can then try out in that cycle.

**Comment by MichaelSimons** [comment]
[Triage] It would be beneficial to identify which issues would still exist with ArPow.  Additionally we would like to identify phases w/the idea being the top phase would be the items we would like to tackle first.  Once the phases are identified, they should be reviewed by the triage team.

**Comment by crummel** [comment]
Based on value/effort ratio, "shovel-readiness", and usefulness after ArPow I recommend these for the first pass:
- https://github.com/dotnet/source-build/issues/2127 (already has a PR)
- https://github.com/dotnet/source-build/issues/2124
- https://github.com/dotnet/source-build/issues/2081
- https://github.com/dotnet/source-build/issues/1594
- https://github.com/dotnet/source-build/issues/600

And these for later implementation:
- https://github.com/dotnet/source-build/issues/2128
- https://github.com/dotnet/source-build/issues/2125
- https://github.com/dotnet/source-build/issues/1669
- https://github.com/dotnet/source-build/issues/1610
- https://github.com/dotnet/source-build/issues/747

And the rest for later re-evaluation.

**Comment by MichaelSimons** [comment]
[Triage] The decision is that we will commit to fixing one issue per servicing cycle.  @crummel, please add to project board and assign milestones.

**Comment by MichaelSimons** [comment]
[Triage] This is superseded by #3065
