### ISSUE TITLE
Automatically verify that XML/Intellisense docs are included in SDK output

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2127]
Should be easily automatable and eliminates a manual step in servicing validation.

**Comment by omajid** [comment]
I have a test script that I used in https://github.com/dotnet/source-build/issues/1686

**Comment by omajid** [comment]
A couple of questions:

- My original test (as mentioned in the comment above) as in bash. Is that suitable for inclusion in source-build? Or should I try and re-write it in something more cross-platform?
- Should this be plugged into `smoke-test.sh` or is there a better place for this test?

**Comment by omajid** [comment]
Now that #2137 is merged, is it okay to close this issue now?
