### ISSUE TITLE
[release/3.1] Unable to use 3.1.113 to build 3.1.114

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2131]
Trying to use a previously-built 3.1.113 to build the latest 3.1.114 fails:

```
  [19:26:33.72] Building reference-only assemblies.
  /home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/packages/source-built/coreclr-tools/x64/ilasm /home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/packages/reference/source/microsoft.aspnetcore.app.ref/3.1.10/ref/netcoreapp3.1/Microsoft.AspNetCore.Antiforgery.il -dll -quiet -nologo -output=/home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/packages/reference/staging/microsoft.aspnetcore.app.ref/3.1.10/ref/netcoreapp3.1/Microsoft.AspNetCore.Antiforgery.dll
  /tmp/tmp92b6e7b52a6643f6bf66cad56dc8fdca.exec.cmd: line 2: /home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/packages/source-built/coreclr-tools/x64/ilasm: No such file or directory
/home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/tools-local/init-build.proj(122,5): error MSB3073: The command "/home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/packages/source-built/coreclr-tools/x64/ilasm /home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/packages/reference/source/microsoft.aspnetcore.app.ref/3.1.10/ref/netcoreapp3.1/Microsoft.AspNetCore.Antiforgery.il -dll -quiet -nologo -output=/home/omajid/fedora-git/dotnet3.1/dotnet-v3.1.114-SDK/packages/reference/staging/microsoft.aspnetcore.app.ref/3.1.10/ref/netcoreapp3.1/Microsoft.AspNetCore.Antiforgery.dll" exited with code 127.
```

Like the error says `source-built/coreclr-tools/x64/ilasm` doesn't exist, but `source-built/coreclr-tools/ilasm` does.

**Comment by alucryd** [comment]
FWIW it also fails when bootstrapping with the official 3.1.114 SDK from Microsoft on Arch Linux. Also tried 3.1.112 and 3.1.113 official distributions, is there any SDK where `source-built/coreclr-tools/x64/ilasm` actually exists?

**Comment by alucryd** [comment]
Actually, it complains about ildasm here, but for the same reasons. I'll just patch `Directory.Build.props`.

**Comment by omajid** [comment]
Thanks! That's a good idea. It worked for me too: https://src.fedoraproject.org/rpms/dotnet3.1/blob/9382d427e2e907ecca5e554311d14017e5d433a9/f/source-build-ilasm-ildasm-path-fix.patch

**Comment by MichaelSimons** [comment]
[Triage]:  Not worth fixing anymore as we will be able to use the previous to build the current going forward.  This was an oversite.

Fix is to use a local patch to get to the current version.
