### ISSUE TITLE
Tarball restructuring

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2143]
#### Situation
There are many steps required to build tarballs for testing internally when doing a servicing release.  Much of the work is in preparing tarballs, since tarballs for each platform are generated on the platform.  Generation of RHEL7 and RHEL8 tarballs is not automated and must be done on a developer machine but these are the tarballs that we’re releasing to the RedHat team. 

#### Objective
Improve servicing time, effort and storage space by automatically generating a single tarball for all platforms that can then be prepared to build on a specific platform.

#### Execution
Generate and release a “bare tarball” which contain just the common pieces of a tarball for all platforms.  Provide a script to prepare the tarball to be built on a given platform.  This provides flexibility in that tarballs can be built using either the prepare script or can be built by using the `--with-ref-packages` `--with-packages` and `--with-sdk options`.  This improves servicing in 3 ways: 1) tarball creation can be automated for all platforms 2) tarballs are smaller and require less storage & time to copy and 3) reduces the steps required to do servicing.

#### Implementation Plan

1. Generate base tarball and setup CI to generate the base tarball with each build.
2. Use the base tarball for servicing releases.
3. Iron out any issue that may arise from using base tarballs or identify areas where base tarball won't work.
4. Add CI leg that only generates base tarball + smoke-test-prereqs (for internal builds)
5. Move all CI legs to work with only base tarballs
6. Update bootstrap CI leg to use base tarball
7. Add logic to generate base tarball without production build

**Comment by MichaelSimons** [comment]
[Triage] @deeseld will create a POF, share with key partners (e.g. RHEL) to get feedback, and then work on making it production.

**Comment by MichaelSimons** [comment]
The remaining work is to refactor CI to make use of the base tarball which is covered in #2663 and #2611
