### ISSUE TITLE
The tarball is not only made up of source codes

### ISSUE THREAD

**Issue by deflarten** [dotnet/source-build#2169]
Can I build from source without internet from the tarball I received, but without the archived packages (artifacts)?
Packages in packages / archive are not source codes
Can't sdk be built entirely from source codes alone?

**Comment by omajid** [comment]
Hi. I think https://github.com/dotnet/source-build/issues/1930 answers this in more detail. Summary: no, you need a set of working SDK/artifacts to build .NET. Once you have built source-build (and source-build-reference-packages) once, you can use that to build subsequent releases from sources (only). We do this in Fedora where we built (bootstrapped) .NET 5.0 once and are now using our self-built .NET 5.0 to build subsequent versions.

Please let us know if there's additional information that you need.

**Comment by mid-kid** [comment]
The only two directories that contain binaries are `packages/archive` and `.dotnet`. Remove those two and you're left with only source code.
To build it you need a `dotnet-sdk` archive, a `Private.SourceBuilt.Artifacts` and a `Package.SourceBuild.ReferencePackages`. The former two are built by this repo and can only be built with themselves, but the last one can be built from source, with this repo: https://github.com/dotnet/source-build-reference-packages (see the pre-arcade branch)

**Comment by MichaelSimons** [comment]
[Triage] Thanks to @omajid and @mid-kid for providing answers.  Closing but feel free to continue discussing.
