### ISSUE TITLE
Investigate differences between Docker and non-Docker tarball build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2171]
While testing the base tarball (https://github.com/dotnet/source-build/pull/2170) we found differences between the build on a non-Docker Debian VM with all prereqs and a build on the usual Debian Docker image we use (mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-d61254f-20190807161114).  The Docker image built and passed smoke tests, but the non-Docker VM had this error:
```
dpkg : error : cannot access archive '/home/chris/base-tarball/dotnet-5.0.6-base/src/installer.b5f47e6c6aa198df48121dc3076c9626f50b116e/artifacts/obj/redist/Release/downloads/dotnet-apphost-pack-5.0.6-x64.deb': No such file or directory [/home/chris/base-tarball/dotnet-5.0.6-base/src/installer.b5f47e6c6aa198df48121dc3076c9626f50b116e/src/redist/redist.csproj]
```

I have also seen similar errors when a tarball was produced on a non-Debian system and then a build was attempted from the same tarball on a Debian system.  My suspicion is one of:
- We have differences between the production and tarball builds that lead to these .deb files not being produced or consumed correctly.
- Installer uses `$(RunningInDocker)` or a similar distinction to determine whether to build or use these files.
- There is an error that does not stop the build when .deb creation fails (due to missing files or tools), and this attempt to find the .deb file exposes it.

**Comment by MichaelSimons** [comment]
[Triage] Closing as obsolete.
