### ISSUE TITLE
3.1 and 5.0 are building Newtonsoft from an individual's fork

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2185]
The Version.Details.xml file for 3.1 and 5.0 is configured to pull the Newtonsoft.Json code from and individual's fork (a .NET team member).  This should be considered an untrusted source.

**5.0** 
https://github.com/dotnet/source-build/blob/release/5.0/eng/Version.Details.xml#L110
https://github.com/dotnet/source-build/blob/release/5.0/eng/Version.Details.xml#L121

This source should be moved into a repo owned by the _dotnet_ organization.

**Comment by dagood** [comment]
IMO the commits should just be turned into patches, like in `main`:
https://github.com/dotnet/source-build/tree/main/patches/newtonsoft-json

**Comment by MichaelSimons** [comment]
>IMO the commits should just be turned into patches, like in main:

Agreed.
