### ISSUE TITLE
[Feature request] Provide ability to build CLI with telemetry removed or disabled by default

### ISSUE THREAD

**Issue by 4creators** [dotnet/source-build#221]
One of the requirements of many distros as indicated in one of the comments in [.NET core should not SPY on users by default](https://github.com/dotnet/cli/issues/3093#issuecomment-333577581) issue is an ability to build CLI with telemetry disabled.

As this is a fundamental requirement for many applications dotnet support for that configuration knob would be very helpful for oss community and teams / projects working with legally protected or otherwise sensitive data (it is my use case). 

This request is related to issue #187

**Comment by dseefeld** [comment]
Distros are free to patch telemetry out of the product.

**Comment by omajid** [comment]
Here's the fix we are looking at using in Fedora with source-build to disable telemetry by default: https://pagure.io/dotnet-sig/dotnet-2-1/pull-request/9#request_diff
