### ISSUE TITLE
[ArPow] Add prebuilt checks to ArPow tarball

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2218]
ArPow tarballs will require the ability to do overall prebuilt checks for the entire tarball build.  ArPow infra currently does prebuilt checking on a repo by repo basis, but this task is to ensure that it works when building in a tarball and that prebuilt reporting for each repo is rolled up to the whole tarball build.

**Comment by MichaelSimons** [comment]
@dseefeld, was this completed with your recent prebuilt changes in #2256?

**Comment by dseefeld** [comment]
> @dseefeld, was this completed with your recent prebuilt changes in #2256?

Yes.  Fixed by dotnet/installer#11021
