### ISSUE TITLE
Build.cmd script accepts /m:x parameter and passes it to MSBuild but it is ignored when submodules are build

### ISSUE THREAD

**Issue by 4creators** [dotnet/source-build#222]
Testing recent source-build on Windows I have encountered problem of excessive spawning of MSVC cl instances during coreclr repo build. On my 4 core / 8 thread laptop it leads to memory consumption of up to 14 GB - for details see https://github.com/dotnet/coreclr/issues/14406.

Passing /m:x parameter to build script has no effect on submodules and seems to be ignored.

**Comment by dleeapho** [comment]
@eerhardt Do you think we need another parameter in the repo api to pass the /m:x parameter to submodule builds?

**Comment by 4creators** [comment]
@dleeapho @eerhardt  imho it would be very useful to have 2 additional parameters: maxcpucount (m), and BuildInParallel - where both could be applied individually to every repo and globally. This would solve 14 GB memory usage in coreclr issue as passing BuildInParallel=false should switch off MSBuild parallelism but leave CL parallelism on (I am not sure about the second action but it would be handy to have such granularity of control over build of more than dozen repos).

**Comment by weshaggard** [comment]
I definitely think it is worth having some means of passing this type of information to the repo's, or if not pass it ensure the repo's have a reasonable setting when building in the larger source-build system. For this particular issue it seems like we need to solve it even for the individual repo build so perhaps it isn't something unique to source-build.

**Comment by dseefeld** [comment]
This area is likely to change with ProdCon/source-build sync.
