### ISSUE TITLE
Investigate the need for cssparser in source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2221]
cssparser no longer appears to be needed in source-build.  The 5.0.204 tarball builds offline and tests pass with cssparser removed.

This was discovered as part of ArPow while investigating/defining the repo dependency graph.  This issue is intended to be used to research this and log any follow-up issues per the findings.

**Comment by omajid** [comment]
cssparser was required by ASP.NET Core (razor, in particular): https://github.com/dotnet/source-build/pull/1814

https://github.com/dotnet/aspnetcore/blob/release/5.0/src/Razor/Microsoft.AspNetCore.Razor.Tools/src/rzc.csproj still has a dependency on it:

```xml
    <ExcludeFromSourceBuild>false<ExcludeFromSourceBuild>
...
...
  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis.Razor" />
    <Reference Include="Microsoft.Css.Parser" />
    <Reference Include="Newtonsoft.Json" />
   </ItemGroup>
```

**Comment by MichaelSimons** [comment]
aspnetcore pull request that introduced the dependency - https://github.com/dotnet/aspnetcore/pull/23657

This was refactored to be version agnostic in https://github.com/dotnet/aspnetcore/pull/24136/files#diff-a1101ac616ef1ed07d7e31509e84668b39843b26da6c506eea37e06659b54491.  A possible reason the 5.0.204 tarball still builds is because the reference is picked up from the previously source-build artifacts.

This project however does not exist in 6.0.  It appears to have been moved to the SDK repo - https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Tool/Microsoft.NET.Sdk.Razor.Tool.csproj#L31.  This implies the dependency should be moved from aspnetcore to the sdk.  It also appears that this aspnetcore versions property can get cleaned up - https://github.com/dotnet/aspnetcore/blob/main/eng/Versions.props#L192

**Comment by omajid** [comment]
> A possible reason the 5.0.204 tarball still builds is because the reference is picked up from the previously source-build artifacts.

Ouch. That means we can accidentally use "prebuilts" instead of building things ourselves :( I thought we were using techniques like poisoning to avoid this? Is there an issue tracking this bug?

**Comment by MichaelSimons** [comment]
Here are the two PRs in which the Razor SDK was moved from aspnetcore to the sdk.

aspnetcore - https://github.com/dotnet/aspnetcore/pull/29548
sdk - https://github.com/dotnet/sdk/pull/15248

**Comment by MichaelSimons** [comment]
> > A possible reason the 5.0.204 tarball still builds is because the reference is picked up from the previously source-build artifacts.
> 
> Ouch. That means we can accidentally use "prebuilts" instead of building things ourselves :( I thought we were using techniques like poisoning to avoid this? Is there an issue tracking this bug?

@crummel - can you answer this?

**Comment by crummel** [comment]
I believe we didn't consider previously-source-built packages as "external", so those aren't poisoned or considered prebuilts.  I thought of a couple more scenarios where this could happen wouldn't be caught by our current checks so I logged https://github.com/dotnet/source-build/issues/2222 - the idea being to add a check that we don't stop producing any packages without knowing about it.

**Comment by MichaelSimons** [comment]
Closing as the dependency has simply moved as noted in the conversation.
