### ISSUE TITLE
Implement check that (new source-built packages) is a superset of (previously-source-built-packages)

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2222]
As seen in https://github.com/dotnet/source-build/issues/2221, there exists an issue where:

- A repo produces PackageA in version 1.
- Downstream repos either depend on PackageA with the Arcade-style `$(PackageAPackageVersion)` or as a "latest" reference (without a version number).
- PackageA stops being produced in version 2 (the repo is removed without noticing, packages are consolidated or renamed, package is moved to another repo).
- The downstream repo still depends on PackageA and ends up picking it up from a previously-source-built-packages tarball.
- In version 3, the previously-source-built-packages version 2 tarball no longer includes PackageA and the build fails.

While PackageA is still source-built in version 2, it isn't source-built when we thought it was, and we break the build entirely in version 3.  The most straightforward way to catch all these potential cases seems to adding a check after the build that there are no package-names in previously-source-built that are not also in the "just-source-built" feed as well (artifacts/obj/x64/Release/packages/blob-feed).  Note that package-name-versions should not be considered as these will not generally match.  This could be implemented as part of the poisoning or prebuilt checks.

**Comment by omajid** [comment]
When you say version 1, 2 and 3, those could be just point upgrades from each other, right? Or just successive builds of the same version too, right? In other words, this could hit us at any point, not just at major release changes?

**Comment by crummel** [comment]
Yes, this could happen any time any repo changes the packages it produces.  I'm not aware of this happening in a real build rather than a tarball hacked-up for testing, but early on I remember Roslyn rearranged some packages - I think they consolidated so we were missing packages rather than the other way around though.

**Comment by crummel** [comment]
This was also seen in https://github.com/dotnet/source-build/pull/2329.  We may want to consider addressing this issue sooner, or at least having a short-term fix or checklist item that we can use until we have a proper fix.

**Comment by MichaelSimons** [comment]
[Triage] We believe that the Stage 2 CI legs should catch the scenarios where a package is removed from source-build but still referenced.  If the removed component is not referenced then this isn't an issue.  Adding an explicit test may help the UX in calling out that a package was removed and catch it in stage 1 but it comes at a cost.  When a package is removed and not referenced, you would need to update the test in some way to allow it to pass.  Having a test that just warns in this case is of limited value.  We generally want to avoid warnings in our tests/builds.
