### ISSUE TITLE
Enable Razor Omnisharp DLLs for 6.0

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2232]
https://github.com/dotnet/source-build/pull/2178 will need to be ported to 6.0

**Comment by MichaelSimons** [comment]
[Triage] this may not be necessary depending on TFM changes which would be ideal.

**Comment by MichaelSimons** [comment]
[Triage] Omnisharp is working and is tested via [OmniSharpTests](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/OmniSharpTests.cs).  Closing as obsolete.
