### ISSUE TITLE
Evaluate current runtime approach of building for select TFMs

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2233]
According to https://github.com/dotnet/source-build/pull/2178#discussion_r638340576 we should now be able to build for all configurations in runtime instead of picking and choosing working ones.

See also #2232.

**Comment by MichaelSimons** [comment]
[Triage] Removal of net4.* tfms is tracked with #3014.  With the Unified Build work in .NET 8.0 project with build with the latest tfm or a net standard tfm.
