### ISSUE TITLE
Ensure powershell scripts are always called with -NoProfile command line option

### ISSUE THREAD

**Issue by 4creators** [dotnet/source-build#225]
Due to the default behavior of powershell.exe invocation which executes profile scripts on startup it is necessary to guard scripts executed via powershell.exe invocation against it with -NoProfile command line option. Skipping of this option may lead to machine environment dependent execution errors which are hard to debug and fix - see #220. Therefore it would be good practice to ensure that powershell scripts are always invoked with -NoProfile command line option and it can be enforced by using wrapped powershell command containing that option.

**Comment by 4creators** [comment]
There seems to be discussion https://github.com/PowerShell/PowerShell/issues/992 related to default powershell behavior for non-interactive script execution with regard to profile script execution. One of possible solution to general problem could be creation of system wide alias i.e. **posh** which would enforce unix like behavior for shell scripts. This would make possible to have best of two worlds Windows convention based powershell and Unix convention based posh commands.

**Comment by MichaelSimons** [comment]
[Triage]  Closing as obsolete.  There are no longer any powershell scripts for source-build.
