### ISSUE TITLE
[ArPow Tarball] Location for Legacy source-build infra

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2252]
Where should the legacy source-build infra go?  In the prototype, it is under `src/SourceBuild/tarball/content` in the root repo.  This also needs cleanup, since it was all copied from the source-build repo verbatim and then modified to build the prototype, but there are targets and props that will no longer be required.

**Comment by MichaelSimons** [comment]
This logic now resides in dotnet/installers.

**Comment by MichaelSimons** [comment]
[Triage] This issue is obsolete.  There are some open issues (e.g. #2295 and #3073) tracking specific work items.
