### ISSUE TITLE
[ArPow Tarball] Using DOTNET_HOST_BOOTSTRAP_VERSION in tarball build

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2258]
The existing tarball build script has code to determine the DotNet Host version from PVP.  This sets DOTNET_HOST_BOOTSTRAP_VERSION.  It doesn't appear that this exists anymore.  This needs to be investigated to ensure it is no longer needed.

**Comment by MichaelSimons** [comment]
[Triage] We don't believe this is needed at all anymore because we no longer are doing production builds.
