### ISSUE TITLE
[ArPow Tarball] git-clone-to-dir.sh file is restored without correct permissions.

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2259]
Arcade contains this script in the Arcade SDK under `tools/SourceBuild`.  When restoring arcade using the `ExtractToolPackage` target, it is not executable, which causes an issue with the inner build clone.  How is unzipping the package different than installing it with NuGet?

**Comment by omajid** [comment]
Probably https://github.com/NuGet/NuGet.Client/commit/d62db666c710bf95121fe8f5c6a6cbe01985456f?w=1 ?

**Comment by dseefeld** [comment]
Based on Omair's comment above, it appears that nuget does special processing when installing a package.  We're doing this within `ExtractToolPackage` in source-build.  Closing, since there's nothing to do.
