### ISSUE TITLE
[ArPow Tarball] Including .git dir in source tarball

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2260]
In the tarball prototype, the clone step clones all source into the tarball directory including their .git directory.  This is included to allow the inner build to clone and build.  This will result in larger tarballs because it's not just including source.  This needs to be investigated to determine if less can be included or if there is an alternative to cloning to do the inner build.

**Comment by MichaelSimons** [comment]
Changes were made in https://github.com/dotnet/installer/pull/11029 to reduce the tarball from 954309136 to 818628526. There is an opportunity to reduce this to 675411252 with the use of --fetch=1 but our patching mechanism will not work in a shallow git environment.  This should be investigated before this issue is closed.

**Comment by omajid** [comment]
I wanted to establish a baseline of the impact of `.git` directory.

```
$ tar czf dotnet-source-build.tar.gz -C artifacts tarball
$ ls -alh dotnet-source-build.tar.gz
-rw-rw-r--. 1 omajid omajid 799M Jul  9 10:39 dotnet-source-build.tar.gz
```

That's ~800 MB of compressed *sources*! And it doesn't contain many larger repositories yet: runtime, roslyn, sdk or aspnetcore.

A rm -rf of .git:

```
$ find -depth -name '.git' -exec rm -rf {} \;
$ tar czf dotnet-source-build-without-git.tar.gz -C artifacts tarball
$ ls -alh dotnet-source-build-without-git.tar.gz
-rw-rw-r--. 1 omajid omajid 276M Jul  9 11:05 dotnet-source-build-without-git.tar.gz
```

By removing `.git`, we can cut down the size by 65%. In other words, the tarball is 2.9x the size it could be.
