### ISSUE TITLE
[ArPow Tarball] Unpacking intermediate packages duplication

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2261]
Intermediate packages are created from the inner build and then copied and unzipped into the blob-feed.  This is good separation between repo builds, but takes up more space.  If space becomes an issue, alternatives should be considered.

Discussions when initially planning ArPow were to isolate repo builds more in the tarball build by only providing required packages to a given repo build.  This would include SBRP, Previously source-built and any intermediate packages on which the repo was dependent.  Instead of a steadily growing blob-feed for subsequent repo builds, source-build would supply only the required packages in the cache and clean them up between repo builds.  This would make the intermediate packages the source of truth for packages that are built and would eliminate the direct duplication of packages in the blob-feed directory.

**Comment by MichaelSimons** [comment]
[Triage] The intermediates have been removed from the artifacts tarball but are still produced as part of the tarball build.  The production is not necessary and consumes a lot of disk space.

**Comment by MichaelSimons** [comment]
Closing as intermediate packages are no longer created in the product source-build (https://github.com/dotnet/arcade/pull/14348).
