### ISSUE TITLE
[ArPow Tarball] Add step to package source-build artifacts to arpow tarball

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2285]
- [x] Re-enable packaging of source-built assets.
 - [x] Upload source-built assets to Azure storage.
 - [ ] Re-enable using previously source-built NuGet.Packaging in the tarball's arcade.proj

**Comment by dseefeld** [comment]
The last step in this issue is waiting for #2279

**Comment by MichaelSimons** [comment]
Logged a [separate issue](https://github.com/dotnet/source-build/issues/2473) to track the remaining work - Re-enable using previously source-built NuGet.Packaging in the tarball's arcade.proj.
