### ISSUE TITLE
[ArPow] Add distro matrix to tarball ci

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2299]
This builds upon the work done in https://github.com/dotnet/source-build/issues/2290.

Add the various distro type/versions and source-build configurations (e.g. offline/online) to the tarball ci.

**Comment by omajid** [comment]
A couple of options to consider, mostly based on current/existing as well as potential next users of source-build.

- Latest released version of Fedora (34/35)
- RHEL
- CentOS Stream 9, which is basically the in-development/in-testing version of RHEL 9
- Other RHEL rebuilds? CentOS? Rocky?
- Arch? (We have reports from ArchLinux maintainers that indicate they use source-build and the build often breaks for them)
- Ubuntu
- Debian
