### ISSUE TITLE
[ArPow Tarball] Remove old RepoApi properties if possible

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2306]
With ArPow, some of the RepoApi output placement properties are no longer neccessary, since ArPow builds write their pkg output to a common location.  These should be reviewed and removed if no longer needed.

Properties to review:
  - OutputPlacementRepoApiImplemented
  - DependencyVersionInputRepoApiImplemented
  - RepoApiImplemented
  - SourceOverrideRepoApiImplemented

**Comment by MichaelSimons** [comment]
With ArPow, it seems SourceOverrideRepoApiImplemented=false should be the default/only behavior needed.  This will help cleanup the project further.
