### ISSUE TITLE
Investigate prebuilt poisoning in new ArPow tarball build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2317]
Previously we separated poisoning into two steps: after the production build, poison assemblies and packages.  Then, after using those poisoned packages in an offline build, check if any of them made it through to the final output.  We no longer really have this distinction of production/offline builds (see https://github.com/dotnet/installer/pull/11091), so we'll have to do something different here.

**Comment by MichaelSimons** [comment]
[Triage]  Closing as this is being addressed by https://github.com/dotnet/source-build/issues/2652.
