### ISSUE TITLE
.NET library license in some textOnlyPackages in source-build-reference-packages

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2344]
A number of files contain a "MICROSOFT .NET LIBRARY" license which includes comments like "You may not ... publish the software for otehrs to copy" which makes it, IMO, a non-Free lincese.

Here are some files where I can see this license:

- https://github.com/dotnet/source-build-reference-packages/blob/main/src/textOnlyPackages/src/microsoft.netcore.targets/1.1.3/dotnet_library_license.txt
- https://github.com/dotnet/source-build-reference-packages/blob/main/src/textOnlyPackages/src/microsoft.netcore.platforms/1.0.1/dotnet_library_license.txt
- https://github.com/dotnet/source-build-reference-packages/blob/main/src/textOnlyPackages/src/microsoft.netcore.platforms/1.0.2/dotnet_library_license.txt
- https://github.com/dotnet/source-build-reference-packages/blob/main/src/textOnlyPackages//src/textOnlyPackages/src/microsoft.netcore.platforms/1.0.1/dotnet_library_license.txt
- https://github.com/dotnet/source-build-reference-packages/blob/main/src/textOnlyPackages/src/microsoft.netcore.platforms/1.1.1/dotnet_library_license.txt

@dseefeld @crummel @MichaelSimons

**Comment by dseefeld** [comment]
Fixed by https://github.com/dotnet/source-build-reference-packages/pull/240
