### ISSUE TITLE
[ArPow] Remove arcade patches

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2345]
When completing https://github.com/dotnet/installer/pull/11293, patches were required in arcade to update TFMs and remove some test projects.  The patches are addressed in arcade with https://github.com/dotnet/arcade/pull/7674.  Once the changes to arcade are picked up by source-build, the patches can be removed.

**Comment by MichaelSimons** [comment]
Closing in lieu of https://github.com/dotnet/source-build/issues/2708.
