### ISSUE TITLE
[ArPow] Remove SBRP patch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2346]
When completing https://github.com/dotnet/installer/pull/11293, patches were required in source-build-reference-packages to update eng/common.  The patches are addressed in SBRP with https://github.com/dotnet/source-build-reference-packages/pull/219.  Once the changes to SBRP are picked up by source-build, the patches can be removed.

**Comment by MichaelSimons** [comment]
The patches have been removed.
