### ISSUE TITLE
[ArPow] Remove clicommandlineparser patch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2350]
When completing https://github.com/dotnet/installer/pull/11327, a patch was required in clicommandlineparser to build offline for net6.0. The patch is addressed in clicommandlineparser with https://github.com/dotnet/CliCommandLineParser/pull/188. Once the changes to clicommandlineparser are picked up by source-build, the patch can be removed.

**Comment by MichaelSimons** [comment]
Closing in lieu of https://github.com/dotnet/source-build/issues/2708.
