### ISSUE TITLE
Create tooling that will identify unused packages and TFMs from SBRP 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2357]
We currently don't have any convenient means of detecting what packages and TFMs from SBRP are no longer referenced and should be removed.  We should have automated reporting/tooling around this.

Reasons this tooling is valuable:

1. Size of SBRP - 
    1. Repo size on disk - 5.8 GB 
    2. Artifacts size -  119 MB ~10% of all SB artifacts
1. Build times - building fewer packages and tfms will have a direct impact
1. Generate tooling - The tooling to support all possible package versions/TFMs is complicated.  Eliminating unnecessary packages/TFMs simplifies this process - e.g. support 4.* TFMs is very different than netstandard/netcore TFMs.

**Comment by MichaelSimons** [comment]
An easy way to perform this check is to compare the restored packages against the reference packages.  Here are the manual steps I ran.

1. ls packages/reference/packages > refenced.txt
2. find packages/restored -iname *.nupkg -printf "%f\n" | sort > restored.txt 
3. Compare files - items in referenced only can be removed

If unreferenced packages exist:

4. Removed from SBRP
5. Flow updated SBRP into installer
6. Build w/updated SBRP
5. Rebuild w/previous Private Artifacts
6. Validate prebuilts
7. Release steps 1-3 to ensure no additional packages can be removed.  There may be SBRPs that were only used by the SBRPs that were just removed.

**Comment by MichaelSimons** [comment]
Here are the specific commands I have been using to identify the list of unreferenced packages:

``` bash
find packages/reference/ -type f -name "*.nupkg" -printf "%f\n" | awk '{print tolower($0)}' | sort > reference.txt
find packages/restored/ -type f -name "*.nupkg" -printf "%f\n" | awk '{print tolower($0)}' | sort > restored.txt
grep -v -f restored.txt reference.txt
```

**Comment by MichaelSimons** [comment]
The following packages are not referenced in the product build but are required by the repo legs.  These will eventually be referenced by the product build once the per repo pvp feature is fully rolled out.

Microsoft.Extensions.Logging.Abstractions.7.0.0
System.Threading.Tasks.4.3.0
System.Reflection.Metadata 6.0.1

**Comment by oleksandr-didyk** [comment]
References for `Microsoft.Build: 17.3.2` added with https://github.com/dotnet/source-build-reference-packages/pull/592:
  - Microsoft.Win32.SystemEvents: 6.0.0
  - System.Drawing.Common: 6.0.0
  - System.Windows.Extensions: 6.0.0
  - System.Formats.Asn1: 6.0.0
  - System.Security.Cryptography.Pkcs: 6.0.1
  - System.Security.Cryptography.Xml: 6.0.0
  - System.Security.Permissions: 6.0.0
  - System.Security.Cryptography.ProtectedData: 6.0.0
  - System.Configuration.ConfigurationManager: 6.0.0
  - System.Threading.Tasks.Dataflow: 6.0.0
  - System.Reflection.MetadataLoadContext: 6.0.0
  - System.Resources.Extensions: 6.0.0
  - System.CodeDom: 6.0.0
  - Microsoft.IO.Redist: 6.0.0
  - Microsoft.NET.StringTools: 17.3.2
  - Microsoft.Build.Framework: 17.3.2
  - Microsoft.Build.Utilities.Core: 17.3.2
  - Microsoft.Build: 17.3.2
