### ISSUE TITLE
Handle non-required files under non-open source licenses

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2359]
When ArPow builds a tarball for the complete .NET source code, it includes code from all the individual repositories. Some of those repositories have code that's still under a non-open source license.

Some of these are blockers to releasing .NET and are being worked on (eg, https://github.com/dotnet/runtime/issues/56394 and https://github.com/dotnet/source-build/issues/2344).

However, there are additional files without clear movement upstream. They are also not strictly part of "building the SDK". Some are tests, some are samples. For example:

- https://github.com/NuGet/Home/issues/11094
- https://github.com/dotnet/aspnetcore/issues/34785
- https://github.com/aspnet/jquery-validation-unobtrusive/issues/140
- https://github.com/Humanizr/sample-aspnetmvc/issues/1

As a workaround, maybe we can delete these files when building the tarball?

**Comment by omajid** [comment]
In Fedora, I have this set of steps to remove similar issues in 5.0: https://pagure.io/dotnet-sig/dotnet5.0/blob/master/f/build-dotnet-tarball#_153

```
# Remove files with funny licenses, crypto implementations and other
# not-very-useful artifacts to reduce tarball size
rm -r src/aspnetcore.*/src/SignalR/clients/java/signalr/gradle*
find src/aspnetcore.*/src -type d -name samples -print0 | xargs -0 rm -r
rm -r src/NuGet.Client.*/test/EndToEnd
rm -r src/runtime.*/src/mono/
rm -r src/Humanizer.*/samples/
```

That was more of a blunt hammer; we can be more surgical about what we delete.

**Comment by richlander** [comment]
Can we re-consider this solution for .NET 7? Even if we got half of these remediated for .NET 7, that would still be a step forward. Fair?

**Comment by omajid** [comment]
Sure, we would love for this to be fixed in the individual component repos. But as you can see, we have had no traction on the individual issues. Some of them have been open since 2020!

This solution was only adapted because it let us "fix" the issue without bothering the consumers of source-build (eg, RHEL, Fedora).

**Comment by richlander** [comment]
Can someone point out where the ref to the Humanizr project is coming from?

**Comment by MichaelSimons** [comment]
> Can someone point out where the ref to the Humanizr project is coming from?

roslyn and roslyn-analyzers reference it in a number of places. 

https://github.com/search?q=humanizer+repo%3Adotnet%2Froslyn+repo%3Adotnet%2Froslyn-analyzers+extension%3Acsproj&type=Code&ref=advsearch&l=&l=

**Comment by dougbu** [comment]
Adding @mkArtakMSFT and @Pilchie to give them additional background on the license issues in our two repos.

**Comment by richlander** [comment]
It sounds like @ChrisSfanos is going to make the required fixes, including in Humanizr.

**Comment by MichaelSimons** [comment]
Now that the nuget-client license issues are resolved, the [source-build logic](https://github.com/dotnet/installer/blob/main/src/SourceBuild/Arcade/tools/SourceBuildArcadeTarball.targets#L272) to account for these should be removed.

**Comment by MichaelSimons** [comment]
It looks like the licensing issue in Humanizer has been addressed but now we need the product repo(s) to update to a newer version.  I opened https://github.com/dotnet/roslyn-analyzers/issues/6186 to track this.

**Comment by MichaelSimons** [comment]
All of the known licensing issues have been resolved - closing.
