### ISSUE TITLE
Smoke-test-prereqs is including locally-built packages

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2375]
This should be getting pulled from the local build.  This is causing issues when testing internal builds including specifically:
- Source-build does not build for lowest-common-denominator system libraries, which can cause runtime failures on older OSs.
- For some dependency closures, source-build does not build every package in the closure, which can cause restore failures when packages don't have the versions they expect.

**Comment by MichaelSimons** [comment]
[Triage] This was addressed during the smoke-test rewrite in 6.0
