### ISSUE TITLE
Versions.props hasn't been updated in the 5.0.9 SDK 206 release

### ISSUE THREAD

**Issue by alucryd** [dotnet/source-build#2379]
Please update the file next time, we're relying on it to automatically update the Arch Linux package version.

**Comment by omajid** [comment]
Does that mean that the ASP.NET version is wrong? Since https://github.com/dotnet/source-build/pull/2005, it's generated from Version.props.

**Comment by dseefeld** [comment]
Triage: It looks like this file was missed in the last update.  #2157 is a start will help to automate testing for this scenario.

**Comment by crummel** [comment]
Sorry I missed that, https://github.com/dotnet/source-build/pull/2386 will fix the issue.  We don't believe this will have any material effect on the built SDK - this is used for conflict detection in ASP.NET but nothing else yet.

**Comment by alucryd** [comment]
Thanks a lot!

**Comment by MichaelSimons** [comment]
[Triage] This is obsolete.  The version number is no longer manual tracked.
