### ISSUE TITLE
3.1.18 and 5.0.9 releases won't build on Arch Linux

### ISSUE THREAD

**Issue by alucryd** [dotnet/source-build#2380]
Hi there, it seems both 3.1 and 5.0 builds broke on arch linux with the latest releases, without any change to our build recipes.
Both builds fail when bootstrapped with either an official SDK or the one from our repositories. Please find the build logs for each version below.

- 3.1.18: https://buildbot.alucryd.xyz/#/builders/345/builds/61/steps/12/logs/stdio
- 5.0.9: https://buildbot.alucryd.xyz/#/builders/257/builds/190/steps/11/logs/stdio

**Comment by alucryd** [comment]
The build still fails for 5.0.9.1: https://buildbot.alucryd.xyz/#/builders/257/builds/192/steps/11/logs/stdio

@crummel I think there was a misunderstanding, the `Versions.props` mismatch wasn't the reason these builds failed, I had worked around that. If you look at the logs 3.x fails during the corefx build, while 5.x fails during the msbuild build.

**Comment by omajid** [comment]
From 3.1:

>   /build/dotnet-core-3.1/src/dotnet-source-build/Tools/source-built/Microsoft.NET.Sdk.IL/targets/Microsoft.NET.Sdk.IL.targets(140,5): error MSB3073: The command "/build/dotnet-core-3.1/src/dotnet-source-build/Tools/source-built/coreclr-tools/ilasm -QUIET -NOLOGO -OPTIMIZE -DLL  -INCLUDE=include/netstandard -OUTPUT="/build/dotnet-core-3.1/src/dotnet-source-build/artifacts/src/corefx.35d34d408c00b1a44a5f4df0f434030849419f1e/artifacts/obj/System.Runtime.CompilerServices.Unsafe/netstandard-Release/System.Runtime.CompilerServices.Unsafe.dll" -KEY="/build/dotnet-core-3.1/src/dotnet-source-build/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/snk/MSFT.snk" System.Runtime.CompilerServices.Unsafe.il" exited with code 139. [/build/dotnet-core-3.1/src/dotnet-source-build/artifacts/src/corefx.35d34d408c00b1a44a5f4df0f434030849419f1e/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.ilproj]

The exit codes which are larger than 128 are generally set by a signal handler in the runtime. It is generally set to 128 + the signal number of the signal. 11 is `SIGSEGV` (`#define SIGSEGV     11` from `/usr/include/bits/signum-generic.h` in my OS).

5.0:

> /build/dotnet-core/src/dotnet-source-build/repos/Directory.Build.targets(374,5): error MSB3073: The command "/build/dotnet-core/src/dotnet-source-build/artifacts/src/msbuild.5e4b48a27efce55a613664b58d353ab4c8d1f6c1/build.sh --build --publish --pack /p:DotNetBuildFromSource=true /p:DotNetCoreSdkDir=/build/dotnet-core/src/dotnet-source-build/.dotnet/ --configuration Release --projects /build/dotnet-core/src/dotnet-source-build/artifacts/src/msbuild.5e4b48a27efce55a613664b58d353ab4c8d1f6c1/MSBuild.SourceBuild.slnf --nodereuse false  /p:DisableNerdbankVersioning=true /p:DotNetPackageVersionPropsPath=/build/dotnet-core/src/dotnet-source-build/artifacts/obj/x64/Release/PackageVersions.props --warnAsError false -v minimal -bl -ci  /p:DotNetRestoreSourcePropsPath=/build/dotnet-core/src/dotnet-source-build/artifacts/obj/x64/Release/RestoreSources.props >> /build/dotnet-core/src/dotnet-source-build/artifacts/logs/msbuild.log 2>&1" exited with code 139. [/build/dotnet-core/src/dotnet-source-build/repos/msbuild.proj]

Same thing here.

Are these both using self-built previous SDK on Arch? Can you reproduce failures if you try and build corefx and/or msbuild standalone? Can you attach a debugger and get a backtrace?

It sounds like something in underlying OS changed in a way that's incompatible with the .NET runtime. And that's causing the runtime to segfault. We will need to find out what that is and fix it. The fix will probably need to go into dotnet/runtime repo. The error doesn't seem to be related to source-build itself, per se.

**Comment by alucryd** [comment]
@loqs Thanks for the heads up, I should finally have time to take a look at this. However, and correct me if I'm wrong, I don't think there have been a soname bump in lttng-ust 2.13.0 so, short of building 2.12.0 statically in the dotnet build, this will be tricky.

**Comment by alucryd** [comment]
Confirmed building with 2.12.0 worked. I might give 2.12.2 a shot later on, but for now it will have to do. Thanks again @loqs.

**Comment by omajid** [comment]
@alucryd FYI: https://github.com/dotnet/runtime/issues/57784

If you have more details, can you please open a new issue in dotnet/runtime?
