### ISSUE TITLE
[ArPow] Remove runtime patch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2394]
As part of https://github.com/dotnet/installer/pull/11506 a patch was introduced to build allconfigurations only when building non-portable.  This issue is addressed in https://github.com/dotnet/runtime/pull/58122.  Once this change is picked up by source-build, the patch can be removed.

**Comment by MichaelSimons** [comment]
Another patch was added as part of https://github.com/dotnet/source-build/issues/2404 which should also get backported.
