### ISSUE TITLE
Resolve prebuilts for the arcade repo for 6.0

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2411]
The arcade repo contains prebuilts as identified by the prebuilt report at `artifacts\prebuilt-report\annotated-usage.xml` in the Offline BuildLogs for any installer build.  These prebuilts need to be resolved by either a) conditioning out the code that includes the package, b) updating the package version to use the version that is built in source-build (using package version flow) or c) adding the package to SBRP.

**Comment by MichaelSimons** [comment]
All Arcade prebuilts have been resolved with the most recent build.  Closing.

**Comment by MichaelSimons** [comment]
Re-opening as there are a number of new arcade prebuilts in the latest report.  The all are packages product in SB but the arcade build is picking up older versions.
