### ISSUE TITLE
Resolve prebuilts for the roslyn-analyzers repo for 6.0

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2420]
The roslyn-analyzers repo contains prebuilts as identified by the prebuilt report at `artifacts\prebuilt-report\annotated-usage.xml` in the Offline BuildLogs for any installer build.  These prebuilts need to be resolved by either a) conditioning out the code that includes the package, b) updating the package version to use the version that is built in source-build (using package version flow) or c) adding the package to SBRP.

**Comment by dagood** [comment]
The roslyn-analyzers repo is missing producing the `Microsoft.CodeAnalysis.BannedApiAnalyzers` package. Adding this back in (so other repos can consume it) might affect roslyn-analyzers prebuilts: https://github.com/dotnet/roslyn-analyzers/issues/5619
