### ISSUE TITLE
6.0 preview SDK claims it's a GA version (6.0.100)

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2433]
Originally reported by @uweigand

> I noticed that running the source-build will set appropriate version 
> suffixes e.g. for the runtime and aspnetcore, but the main tarball as 
> well as the SDK directory will simply use "6.0.100" -- that seems 
> misleading given that the current state is certainly not yet the final .NET 6 release.
>
> To clarify, the tarball created is simply called 
> dotnet-sdk-6.0.100-ubuntu.20.04-s390x.tar.gz, and when I execute the 
> dotnet executable in there, I get:
>
> ```
> $ ./dotnet --info .NET SDK 
> (reflecting any global.json):
> Version:   6.0.100
> Commit:    f3ea71b28f
>
> Runtime Environment:
> OS Name:     ubuntu
> OS Version:  20.04
> OS Platform: Linux
> RID:         ubuntu.20.04-s390x
> Base Path:  dotnet-source-build/sdk/6.0.100/
>
> Host (useful for support):
>  Version: 6.0.0-preview.7.21356.2
>  Commit:  566b53a66b
>
> .NET SDKs installed:
>  6.0.100 [dotnet-source-build/sdk]
>
> .NET runtimes installed:
>  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2  [dotnet-source-build/shared/Microsoft.AspNetCore.App]
>  Microsoft.NETCore.App 6.0.0-preview.7.21356.2 [dotnet-source-build/shared/Microsoft.NETCore.App]
> ```

@crummel  mentioned that it might be a result of setting `IsStable` or `UseStableversions` to `true`: https://github.com/dotnet/installer/blob/69fcba5df7b373f79aa36bab8f419028eec91fc2/src/SourceBuild/tarball/content/repos/Directory.Build.props#L18

**Comment by uweigand** [comment]
@crummel I see that `UseStableVersions` is true on the main branch, but I'm using the release/6.01xx branch of the installer to create the tarball, and there `UseStableVersions` is actually false:
https://github.com/dotnet/installer/blob/e0050dd0f022d3986cad2ce2cd0fbee927565b68/src/SourceBuild/tarball/content/Directory.Build.props#L23

Also, I do get the preview versions for all the intermediate packages.  It's just the final installer package that doesn't seem to get the version suffix.  (But this is the package that determines the version shown as the main "Version" above.)

**Comment by dseefeld** [comment]
Related to #2440
