### ISSUE TITLE
Unquoted argument in dotnet-install.sh leads to build failure if the working directory path contains spaces

### ISSUE THREAD

**Issue by Mr-Tao** [dotnet/source-build#2435]
The `$dotnetRoot` argument being passed in line 78 should be quoted.
https://github.com/dotnet/source-build/blob/bf414f06b05fc5c8fdeffe94e477d8fe102acac5/eng/common/dotnet-install.sh#L78

If the absolute path of the script contains spaces, it is being passed as multiple arguments.  The values of the remaining arguments are populated with bogus values as a result.

Consequently, invocation of the `InstallDotNet` function in line 203 fails, despite the `$root` argument being properly quoted there, as it already contains only the leading part of the path up to the first space and remaining arguments contain all sorts of nonsense.

https://github.com/dotnet/source-build/blob/bf414f06b05fc5c8fdeffe94e477d8fe102acac5/eng/common/tools.sh#L191-L203

A snippet of an example output of `bash -x  dotnet-install.sh -runtime dotnet -version 3.1.1` executed in `~/dotnet script test/a/b/c/d`
```
+ skipNonVersionedFilesArg=--skip-non-versioned-files
+ bash /home/mustermann/dotnet/dotnet-install.sh --version script --install-dir /home/mustermann/dotnet --architecture test/a/b/.dotnet --runtime 3.1.1 --skip-non-versioned-files
dotnet_install: Error: Unsupported value for --runtime: '3.1.1'. Valid values are 'dotnet' and 'aspnetcore'.
+ local exit_code=1
```

**Comment by omajid** [comment]
The dotnet-install script, as well as all files under eng/common are maintained in https://github.com/dotnet/arcade. IMO, this bug should be migrated to that repository.

**Comment by MichaelSimons** [comment]
[Triage] source-build is using the Arcade version of the script.  If this is still an issue please follow [@omajid's guideance](https://github.com/dotnet/source-build/issues/2435#issuecomment-915301541).
