### ISSUE TITLE
[SBRP] Add netcoreapp3.0 to 4.7.0 System.Security.Permissions

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2438]
This is needed for the following runtime error:

```
  /repos/tarball1/src/runtime.c300b096419523024f2b807ec9db3c2d91df0298/artifacts/source-build/self/package-cache/microsoft.dotnet.cilstrip.sources/6.0.0-beta.21430.1/contentFiles/cs/netstandard2.0/Mono.Cecil/SecurityDeclaration.cs(54,10): error CS0433: The type 'PermissionSet' exists in both 'System.Security.Permissions, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/repos/tarball1/src/runtime.c300b096419523024f2b807ec9db3c2d91df0298/artifacts/source-build/self/src/src/tasks/ILStripTask/ILStrip.csproj]
  /repos/tarball1/src/runtime.c300b096419523024f2b807ec9db3c2d91df0298/artifacts/source-build/self/package-cache/microsoft.dotnet.cilstrip.sources/6.0.0-beta.21430.1/contentFiles/cs/netstandard2.0/Mono.Cecil/SecurityDeclaration.cs(42,3): error CS0433: The type 'PermissionSet' exists in both 'System.Security.Permissions, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/repos/tarball1/src/runtime.c300b096419523024f2b807ec9db3c2d91df0298/artifacts/source-build/self/src/src/tasks/ILStripTask/ILStrip.csproj]
```

The `PermissionSet` class was moved from `System.Security.Permissions.dll` to `System.Runtime.dll`.  The two referenced assemblies are not coherent.

When building in the tarball the following assemblies are used:
/reference:/repos/tarball1/src/runtime.c300b096419523024f2b807ec9db3c2d91df0298/artifacts/source-build/self/package-cache/system.security.permissions/4.7.0/ref/netstandard2.0/System.Security.Permissions.dll
/reference:/repos/tarball1/.dotnet/packs/Microsoft.NETCore.App.Ref/6.0.0-rc.2.21423.6/ref/net6.0/System.Runtime.dll 

When building the runtime repo outside of source-build, a netcoreapp3.0 version of System.Security.Permissions.dll is used.

A workaround for the ILStrip.csproj is to exclude it from source-build since it does not appear to be required.

**Comment by uweigand** [comment]
> @uweigand - the patch was a temporary workaround until this issue was fixed. I am will try removing the patch now that 4.7.0 was added to the source-build-reference-packages. The result is that IlStrip should be part of source-build again.

Excellent, thanks!   I can confirm that removing the patch makes the runtime source-build go through successfully for me.
