### ISSUE TITLE
Update ArPow tarball build to work with internal repos

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2448]
Clone for ArPow needs to be updated to be able to work with internal repos.  This includes:
- Cloning internal repos when building a tarball
- Creating a method of capturing smoke-test-prereqs (since we have no production build)
- Building a tarball with internal feeds

In release/5.0, there are nuget.config files for smoke-tests that are different for internal production build vs. tarball build with smoke-test-prereqs.  This needs to be reconciled also.  See https://github.com/dotnet/source-build/pull/2159

**Comment by MichaelSimons** [comment]
Closing as there is no known work.  6.0 RC2 was an internal release.
