### ISSUE TITLE
SBRP code generation for projects should be less verbose

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2449]
When generating code for projects, the SBRP code generator generates the string `$(ArtifactsBinDir)<pkgName>/<version>`  once for the nuspec file, once for the output path for every TFM.  This could be improved by declaring a common variable and using that throughout the project file.

**Comment by MichaelSimons** [comment]
This was resolved with https://github.com/dotnet/source-build-reference-packages/pull/574
