### ISSUE TITLE
[ArPow] Remove symreader patch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2452]
When completing https://github.com/dotnet/installer/pull/11955, a patch was required in symreader to remove a test project. The patch is addressed in symreader with https://github.com/dotnet/symreader/pull/249. Once the change to symreader is picked up by source-build, the patch can be removed.

**Comment by MichaelSimons** [comment]
Resolved with https://github.com/dotnet/installer/pull/12066.
