### ISSUE TITLE
[ArPow] Remove roslyn-analyzers patch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2453]
When completing https://github.com/dotnet/installer/pull/11978, a patch was required in roslyn-analyzers to remove test projects. The patch is addressed in roslyn-analyzers with https://github.com/dotnet/roslyn-analyzers/pull/5469. Once the change to roslyn-analyzers is picked up by source-build, the patch can be removed.

**Comment by MichaelSimons** [comment]
Resolved with https://github.com/dotnet/installer/pull/12066
