### ISSUE TITLE
dotnet-install.sh doesn't properly detect musl systems without os-release

### ISSUE THREAD

**Issue by TinfoilSubmarine** [dotnet/source-build#2459]
Not sure if this is where this issue goes, but I need to start somewhere.

The script that gets pulled in from https://dot.net/v1/dotnet-install.sh doesn't detect that my system is musl since I don't have anything at `/etc/os-release` since it just returns at 178 if it can't find os-release. Copied below:
```
    elif [ "$uname" = "Linux" ]; then
        local linux_platform_name
178 ->  linux_platform_name="$(get_linux_platform_name)" || { echo "linux" && return 0 ; }

        if [ "$linux_platform_name" = "rhel.6" ]; then
            echo $linux_platform_name
            return 0
        elif is_musl_based_distro; then
            echo "linux-musl"
            return 0
        elif [ "$linux_platform_name" = "linux-musl" ]; then
            echo "linux-musl"
            return 0
        else
            echo "linux"
            return 0
        fi
    fi
```

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/install-scripts #217](https://github.com/dotnet/install-scripts/issues/217) via [**ZenHub**](https://www.zenhub.com/)
