### ISSUE TITLE
[ArPow] Remove vstest patch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2465]
As part of https://github.com/dotnet/installer/pull/11980 a patch was introduced to exclude the externals project when building from source. This issue is addressed in https://github.com/microsoft/vstest/pull/3063. Once this change is picked up by source-build, the patch can be removed.

**Comment by MichaelSimons** [comment]
Closing in lieu of https://github.com/dotnet/source-build/issues/2708.
