### ISSUE TITLE
Can we remove the `fedora.33-x64` intermediate artifacts?

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2472]
Why do we have `fedora.33-x64` intermediate artifacts?

The previously source-built artifacts tarball contains some RID-specific artifacts:

```
$ find -iname '*intermediate*nupkg' -exec du -hs {} \; | sort -hr | grep fedora                                                                                                                                 
366M    ./Microsoft.SourceBuild.Intermediate.runtime.runtime.fedora.33-x64.6.0.0-rc.2.21459.6.nupkg                                                                                                                                           
358M    ./Microsoft.SourceBuild.Intermediate.runtime.Crossgen2Pack.fedora.33-x64.6.0.0-rc.2.21459.6.nupkg                                                                                                                                     
320M    ./Microsoft.SourceBuild.Intermediate.runtime.fedora.33-x64.6.0.0-rc.2.21459.6.nupkg   
```

These seem like they would have very limited use. They wouldn't be used on Fedora 34, nor on RHEL, nor on any other Linux distribution. Even Fedora 33 would fall back to linux-x64, right? They have a really large footprint too, around 1GB. Does it really make sense to keep them in the "main" Private.SourceBuilt.Artifacts.0.1.0-6.0.100-bootstrap.17.tar.gz tarball?

**Comment by omajid** [comment]
I tried it out and it removal doesn't seem to make any differences, as far as I can see.

**Comment by oleksandr-didyk** [comment]
**General overview:**
When building the product tarball, intermediate packages are included in the resulting archive. The packages themselves also contain unnecessary (from the product build's perspective) tarballs inside, bloating the end tarball's size by a couple of Gbs.

**Proposed solution:**
Based on existing limitations (ex.: handling rid-specific tarballs), the go-to solution is to limit intermediate package usage to repo builds and exclude them from the tarball builds. The later should utilize package feeds to circumvent not having required source-built packages in local Nuget cache.

**Actions to take:**
  - condition out the logic for retrieving and restoring intermediate packages to local Nuget cache;
  - verify resulting changes by building and comparing the product's tarball;
  - use the tarball from the previous action to build the product again (`using n-1 version to build version n`). The product's ability to build itself using source-built `n-1` should be confirmed first.

**Comment by MichaelSimons** [comment]
Regarding the _Actions to take_, the logic which create the artifacts tarball will need to be updated to exclude all intermediate NuGet packages.

**Comment by MichaelSimons** [comment]
Validating these changes is currently blocked by https://github.com/dotnet/installer/pull/14089.  There are some patches required to update the artifacts in addition to a new dotnet toolset is required.
