### ISSUE TITLE
Microsoft.DotNet.SourceBuild.Tasks.XPlat RemoveInternetSourcesFromNuGetConfig needs to handle missing config file

### ISSUE THREAD

**Issue by MattGal** [dotnet/source-build#2479]
[This line](https://github.com/dotnet/source-build/blob/release/3.1/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/RemoveInternetSourcesFromNuGetConfig.cs#L39) in RemoveInternetSourcesFromNuGetConfig needs a check for the existence of the file (I would just make the PR but there could be an esoteric reason that this should fail some other way.)

Failing to check for the file before reading causes [build failures](https://dev.azure.com/dnceng/internal/_build/results?buildId=1381307&view=logs&j=b9699899-7397-58dc-1551-d4801b3b3dfe&t=2beba4da-da67-557f-b169-2ed90945e20d) despite a non-existent nuget.config definitely not containing any internet sources.

**Comment by dseefeld** [comment]
[Triage]: The underlying issue is not a missing nuget.config file, rather, the commit sha is missing from the installer source directory name.  This is because the main branch is missing some source-build updates that were made in 6.0 and 6.0-rc2.

**Comment by dseefeld** [comment]
This should get fixes with the backport to main: https://github.com/dotnet/installer/pull/12058
