### ISSUE TITLE
Add BuildTools submodule

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#248]
Right now, there's no BuildTools submodule in `dev/release/2.0`. It seems like we should include it to be fully building from source, even though it's only a build-time toolset.

**Comment by omajid** [comment]
Agreed. Unless it is a standalone component meant for use by everyone else too (like newtonsoft.json), it should be built from source as part of .NET Core.

**Comment by dleeapho** [comment]
We are removing buildtools.
