### ISSUE TITLE
Tag of v5.0.401

### ISSUE THREAD

**Issue by hdost** [dotnet/source-build#2480]
Is there a chance that there will be a newer tag/ is there a way to track pace of new versions?

**Comment by omajid** [comment]
https://github.com/dotnet/source-build/issues/1842 has some information about why a 5.0.4xx is unlikely to be available soon:

> Source-build supports the oldest in-service feature band [ ... ] for compatibility reasons: we don't want to break our users any more than necessary.
>
> We could support source-build for multiple SDK feature bands at the same time. The problem is that it takes a significant chunk of ongoing time to maintain source-build for multiple [...] SDK feature bands, so we don't have a plan to do that [...].

**Comment by omajid** [comment]
And there's a much larger discussion at https://github.com/dotnet/source-build/issues/1743 too.

**Comment by hdost** [comment]
Thank you @omajid I will take look

**Comment by hdost** [comment]
https://github.com/dotnet/source-build/issues/1743 answers it for me, I'll follow that.
