### ISSUE TITLE
Add Version.Details.xml SourceBuild attribute to indicate tarball only dependency

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2481]
Example:

```
    <Dependency Name="Microsoft.Build" Version="17.0.0-preview-21474-03" CoherentParentDependency="Microsoft.NET.Sdk">
      <Uri>https://github.com/dotnet/msbuild</Uri>
      <Sha>9f83c725ff188ea0d68b306997328581935a7813</Sha>
      <SourceBuild RepoName="msbuild" ManagedOnly="true" TarballOnly="True"/>
    </Dependency>
```

The `TarballOnly` attribute would indicate this dependency is only used in the tarball builds.  It means the corresponding NuGet package should not be retrieved during the repo build.

The reason this is needed is because there have been a number of cases when a dependency won't build in the source-build repo leg - e.g. the source build intermediate is not produced.  In these cases the dependency still needs to be expressed for the tarball build.  These situations are typically temporal but can block the tarball builds until the underlying issue is resolved.  This mechanism will allow us to unblock the tarball builds.

Related to https://github.com/dotnet/source-build/issues/2431

**Comment by MichaelSimons** [comment]
> Should I include the TarballOnly attribute too so it's ready?

Yes - we will need to support this as it is still referenced in places.

**Comment by premun** [comment]
Whoever works on this - I have extracted [logic for parsing `Version.Details.xml` into a separate class in DarcLib](https://github.com/dotnet/arcade-services/blob/main/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/VersionDetailsParser.cs). Previously it was part of a larger monolith. This library is also available in `dotnet/installer` now and can be used there. It should be trivially easy to add the `TarballOnly` attribute too.

**Comment by MichaelSimons** [comment]
There should be no need for this going forward.  The removal of SourceBuildTarball is tracked with https://github.com/dotnet/source-build/issues/2481.
