### ISSUE TITLE
[ArPow] Remove roslyn-analyzers patch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2497]
When completing https://github.com/dotnet/installer/pull/12129, two patches were required to eliminate some prebuilts in roslyn-analyzers.  The patches are addressed in https://github.com/dotnet/roslyn-analyzers/pull/5618.  Once the changes are picked up by source-build, the patches can be removed.

**Comment by MichaelSimons** [comment]
The changes have flown in and the patches were removed.
