### ISSUE TITLE
5.0: Remove Microsoft.CodeAnalysis.CSharp.BannedApiAnalyzers from build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2502]
Currently roslyn-analyzers is patched to remove a pinned MicrosoftCodeAnalysisVersion=2.9.0:

https://github.com/dotnet/source-build/blob/85b2cbf13bda47f7957752840baf068e6e53e779/patches/roslyn-analyzers/0004-Update-to-netstandard2.0.patch#L111-L120

This was probably done to remove a prebuilt, but this explicitly breaks the analyzer per the team:

https://github.com/dotnet/roslyn-analyzers/issues/5619#issuecomment-941717796

> > Trying adding it back in locally, the only new prebuilt dependency it seems to bring in is System.ValueTuple/4.3.0
> 
> The issue is the analyzer intentionally references an older version of the compiler apis.
> 
> https://github.com/dotnet/roslyn-analyzers/blob/b2165afd4b0fe82be4ed1d5dba1e393920bed6c2/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/CSharp/Microsoft.CodeAnalysis.CSharp.BannedApiAnalyzers.csproj#L5
> 
> Rolling forward to use whatever version of the compiler was built locally is not a valid configuration and would mean that the source build is producing different output that the real build.

It should be removed so the broken analyzer doesn't eventually cause a problem.

It doesn't seem to end up in the SDK product. We're probably planning to remove it in 6.0, so we can see what happens there.

**Comment by MichaelSimons** [comment]
[Triage] BannedApiAnalyzers is excluded from the build in this [patch](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/patches/roslyn-analyzers/0001-Eliminate-pre-built-assets-during-source-build-for-r.patch).  #3049 is tracking the removal of this patch.
