### ISSUE TITLE
Resolve Microsoft.AspNetCore.App.Ref prebuilt for 6.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2506]
The Microsoft.AspNetCore.App.Ref is not getting produced by aspnetcore and is not in SBRP therefore it appears are a prebuilt coming from the installer repo.  The logic to build this in aspnetcore is conditioned out for source-build -https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Framework/App.Ref/src/Microsoft.AspNetCore.App.Ref.csproj#L107.  In 5.0 this package came from SBRP.  Producing it in SBRP won't eliminate the prebuilt without work as the version is non-stable.

Ideally aspnetcore would produce this package for the 6.0.0 release then it should come from SBRP for servicing.

**Comment by dougbu** [comment]
If I'm understanding correctly, the fix would be to simply delete https://github.com/dotnet/aspnetcore/blob/release/6.0/Directory.Build.props#L145
