### ISSUE TITLE
Build dotnet/format during source-build

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#2509]
In 6.0, the dotnet/sdk took a new dependency on https://github.com/dotnet/format/ in order to provide the `dotnet format` command.

See https://github.com/dotnet/sdk/pull/18814.

Because of this, we need to onboard https://github.com/dotnet/format/ into source-build in order to build this command that ships in the product.

**Comment by MichaelSimons** [comment]
Closed by linked PRs
