### ISSUE TITLE
Build microsoft/MSBuildLocator during source-build

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#2510]
In 6.0, the dotnet/sdk took a new dependency on https://github.com/microsoft/MSBuildLocator in the `dotnet watch` command.

See https://github.com/dotnet/sdk/pull/16401.

Because of this, we need to onboard https://github.com/microsoft/MSBuildLocator into source-build in order to build this library that ships in the product.

cc @captainsafia @rainersigwald @pranavkm @AndyGerlicher @MichaelSimons

**Comment by rainersigwald** [comment]
Lots of discussion in dotnet/format#1383 that arguably should have been here instead.

**Comment by pranavkm** [comment]
Quick follow up here - do we see fix from #2520 as a long term solution? For dotnet-watch, it's a fairly trivial change to not use the locator assembly (the tool is in the SDK, so it's easy for it locate MSBuild binaries from the SDK root).

**Comment by eerhardt** [comment]
> For dotnet-watch, it's a fairly trivial change 

I believe the larger issue is `dotnet-format`, which ships both as an OOB NuGet and inside the SDK. They would need to produce 2 versions of `dotnet-format`, one that wasn't dependent on MSBuildLocator for the SDK, and one in the NuGet package that used MSBuildLocator.

I suggested this on https://github.com/dotnet/format/issues/1383#issuecomment-943523213, but I'm not sure a consensus was reached on that approach.
