### ISSUE TITLE
SourceLink prebuilts present in SBRP

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2515]
When setting up prebuilt checking in SBRP CI, sourcelink is still showing prebuilts even though the intermediate package is being referenced.

In `eng/Version.Details.xml`, the following version of sourcelink is referenced: `1.1.0-beta-21423-02`

This version of sourcelink's intermediate package is restored when building source build, but when building, it is using version `1.1.0-beta-20206-02`.  These are reported as prebuilts.  They have been added to the "Ignore" section of the prebuilt baseline for now, but should be removed when this issue is fixed.

**Comment by MichaelSimons** [comment]
This issue has been resolved some time ago - See https://github.com/dotnet/source-build-reference-packages/blob/main/eng/SourceBuildPrebuiltBaseline.xml
