### ISSUE TITLE
Need to build more Roslyn packages in source-build

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#2516]
The following packages are not being built by dotnet/roslyn during source-build, but are required by other repos that are being source-built.

* Microsoft.CodeAnalysis.CSharp.CodeStyle
* Microsoft.CodeAnalysis.VisualBasic.CodeStyle
* Microsoft.CodeAnalysis.CSharp.Features
* Microsoft.CodeAnalysis.Workspaces.MSBuild

These are referenced here:

https://github.com/dotnet/sdk/blob/44c3cc228985a4a1a0147e14109ddb8467b7a8df/src/Layout/redist/redist.csproj#L35-L36
https://github.com/dotnet/sdk/blob/44c3cc228985a4a1a0147e14109ddb8467b7a8df/src/BuiltInTools/dotnet-watch/dotnet-watch.csproj#L24-L25

https://github.com/dotnet/format/blob/1f5ecaf6029a666d88fb11f3c5869afa020728bf/src/dotnet-format.csproj#L45-L52

The reason (as far as I can tell) that they are not being built is because the roslyn repo's source-build command builds the `Compilers.sln`, but these projects aren't in that sln file.

https://github.com/dotnet/roslyn/blob/df3d7a83748b32236516874c6bed7ddd04437a38/eng/SourceBuild.props#L14
https://github.com/dotnet/roslyn/blob/df3d7a83748b32236516874c6bed7ddd04437a38/Compilers.sln

cc @dagood @sharwell

**Comment by dagood** [comment]
I'm pausing work on this, prioritizing these first:

* #2417 (partially complete)
* https://github.com/dotnet/source-build/issues/2506 (higher risk)

I'll pick it up again after those if nobody else grabs it first.
