### ISSUE TITLE
Add cleanup of dependency projects in SBRP to 6.0 servicing checklist

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2522]
As part of https://github.com/dotnet/source-build-reference-packages/pull/270, a feature was added to the build of SBRP to build and reference dependency packages inside the repo.  This is needed to allow adding of packages with their dependencies when the dependencies won't exist in previously source-built packages.  This is most likely in servicing releases.  Once the dependencies are included in previously source-built packages, the entries can be removed from `eng/Build.props`.  

The servicing checklist for 6.0 should be updated to check for these and remove them if present.

**Comment by MichaelSimons** [comment]
This is covered in https://github.com/dotnet/source-build/pull/2650
