### ISSUE TITLE
Resolve "uncategorized" prebuilts for the fsharp repo for 6.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2526]
The following "uncatergorized" prebuilts are coming from fsharp. They can be seen in the repo's prebuilt-report. The project location of where these come from is unknown.

```
<Usage Id="Microsoft.NETCore.App.Host.linux-x64" Version="5.0.9" />
```

**Comment by dagood** [comment]
> Upgrading them to `net6.0` is the fix in line with #1763.

Roslyn is currently building netcoreapp3.1 for 6.0, so I'm unsure if we're still going with TFM upgrades.
