### ISSUE TITLE
Re-enable tests for submodules

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#253]
Removing all `skiptests` arguments is currently giving this error:
`/home/chris/dotnet_source-build/src/core-setup/src/test/Assets/TestProjects/PortableTestApp/PortableTestApp.csproj : error NU1003: PackageTargetFallback and AssetTargetFallback cannot be used together. Remove PackageTargetFallback(deprecated) references from the project environment. [/home/chris/dotnet_source-build/src/core-setup/src/test/dir.proj]`

In the long-term, we would like to enable tests for all submodules to ensure we ship a working product.

**Comment by dleeapho** [comment]
Closing for now. Removing `skiptests` doesn't have the ROI at this time. We should instead work on tests of the Red Hat tarball built CLI.
