### ISSUE TITLE
Add Microsoft.NET.Sdk.IL,6.0.0-rc.1.21415.6 to SBRP

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#2535]
dotnet/runtime both produces and consumes the `Microsoft.NET.Sdk.IL` package.

Produces: https://github.com/dotnet/runtime/tree/main/src/coreclr/.nuget/Microsoft.NET.Sdk.IL

Consumes:  https://github.com/dotnet/runtime/blob/862a90f46492203a20311ce8a2008b74e9a30f85/global.json#L21

Since this is a MSBuild Sdk that is listed in global.json, we need to consume a previously built version of it.

We should add the [current version](https://github.com/dotnet/runtime/blob/release/6.0/global.json#L21) being consumed in release/6.0 to SBRP - `6.0.0-rc.1.21415.6`.

We have 5.0.0-preview.8 already in SBRP for 5.0:

https://github.com/dotnet/source-build-reference-packages/tree/main/src/textOnlyPackages/src/microsoft.net.sdk.il/5.0.0-preview.8.20359.4

**Comment by dseefeld** [comment]
@eerhardt Why is it referencing an rc1 version?  Will GA ship referencing that version?
