### ISSUE TITLE
Document how modern ArPow PVP works, plus context

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2546]
There's an old doc with the initial design for PVP:
https://github.com/dotnet/source-build/blob/main/Documentation/auto-dependency-flow/api.md#file-format-package-version-props

I think ArPow needs a new doc that requires less context to understand, and adds new things that have come along since then. I think these would be useful:

* `PackageVersion` vs. `Version` suffix?
* What is the meaning of the `RefOnly` prefix in `eng/Versions.props`? (Or any other prefix?)
* What are `CurrentSourceBuiltPackageVersions.props` and `PreviouslySourceBuiltPackageVersions.props` about?
* What is the connection to Maestro++/BAR/Darc upgrades and `eng/Version.Details.xml`?

**Comment by MichaelSimons** [comment]
[Triage] This should be done as part of the [per repo pvp work](https://github.com/dotnet/source-build/issues/3041).  CC @oleksandr-didyk

**Comment by oleksandr-didyk** [comment]
> [Triage] This should be done as part of the [per repo pvp work](https://github.com/dotnet/source-build/issues/3041). CC @oleksandr-didyk

Reflected this in the original PvP issue for better tracking

**Comment by MichaelSimons** [comment]
This is currently documented in https://github.com/dotnet/source-build/blob/main/Documentation/package-dependency-flow.md.
