### ISSUE TITLE
Investigate 6.0 SDK missing file: `shared/Microsoft.NETCore.App/6.0.0/.version`

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2569]
In the Microsoft-built SDK, this file contains the commit hash on the first line and then the version number on a second line. I don't think anyone uses it (it's just informational) but it would be good to fix this diff if it's a small thing.

https://github.com/dagood/source-build/pull/9#discussion_r734897814

**Comment by MichaelSimons** [comment]
Closing as a patch was added in source-build and was backported to runtime.
