### ISSUE TITLE
ASPNET templating not in source-build

### ISSUE THREAD

**Issue by karajas** [dotnet/source-build#257]
https://github.com/aspnet/templating 

/cc @crummel @natemcmaster

**Comment by dleeapho** [comment]
@karajas is this about getting asp.net source built (ie the larger question) or is this something else.

**Comment by omajid** [comment]
I assumed it was getting the templates - which are used by `dotnet new` - included here.

**Comment by natemcmaster** [comment]
For context: in the dotnet CLI < v2.0.3, the aspnet templates were part of https://github.com/dotnet/templating. In v2.0.3, we started building the template packages from https://github.com/aspnet/templating.

**Comment by dseefeld** [comment]
Assuming this does not affect prebuilts because the package should be text only.  No binaries.

**Comment by MichaelSimons** [comment]
[Triage] Obsolete issue - aspnet templates are now part of source-build.
