### ISSUE TITLE
Investigate 6.0 SDK diff: unnecessary `runtime/` folders

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2573]
Files like `./sdk/6.0.100/DotnetTools/dotnet-format/runtimes/browser/lib/net6.0/System.Text.Encodings.Web.dll` show up in the source-built SDK but not the Microsoft-built SDK. They are most likely not interfering with any functionality, but we should figure out why they're showing up, and ideally fix this diff.

https://github.com/dagood/source-build/pull/9#discussion_r734899321

**Comment by NikolaMilosavljevic** [comment]
I see the opposite in 8.0 SDK diff. The following files are only present in Microsoft-built SDK:
```
sdk/8.0.100-preview.6.23309.1/DotnetTools/dotnet-format/runtimes/unix/lib/net6.0/System.Drawing.Common.dll
sdk/8.0.100-preview.6.23309.1/DotnetTools/dotnet-format/runtimes/win/lib/net6.0/Microsoft.Win32.SystemEvents.dll
sdk/8.0.100-preview.6.23309.1/DotnetTools/dotnet-format/runtimes/win/lib/net6.0/System.Drawing.Common.dll
sdk/8.0.100-preview.6.23309.1/DotnetTools/dotnet-format/runtimes/win/lib/net6.0/System.Security.Cryptography.ProtectedData.dll
sdk/8.0.100-preview.6.23309.1/DotnetTools/dotnet-format/runtimes/win/lib/net6.0/System.Windows.Extensions.dll
```

@MichaelSimons I presume the fix is needed in 8.0 SDK only - or are we considering backporting all changes to older, still-supported source-built SDKs?

**Comment by MichaelSimons** [comment]
8.0 only, we are not backporting these changes.

The 8.0 diff is more logical - `System.Drawing.Common.dll`, `Microsoft.Win32.SystemEvents.dll`, and `System.Windows.Extensions.dll` are windows only assemblies.  `System.Security.Cryptography.ProtectedData.dll` is unknown though.  Is that a transitive dependency?

**Comment by NikolaMilosavljevic** [comment]
> 8.0 only, we are not backporting these changes.
> 
> The 8.0 diff is more logical - `System.Drawing.Common.dll`, `Microsoft.Win32.SystemEvents.dll`, and `System.Windows.Extensions.dll` are windows only assemblies. `System.Security.Cryptography.ProtectedData.dll` is unknown though. Is that a transitive dependency?

Yes, it is transitive, via `System.Configuration.ConfigurationManager`. But, also it seems to be used on Windows platforms only - here's the relevant part in deps.json file:
```
      "System.Security.Cryptography.ProtectedData/6.0.0": {
        "runtime": {
          "lib/net6.0/System.Security.Cryptography.ProtectedData.dll": {
            "assemblyVersion": "6.0.0.0",
            "fileVersion": "6.0.21.52210"
          }
        },
        "runtimeTargets": {
          "runtimes/win/lib/net6.0/System.Security.Cryptography.ProtectedData.dll": {
            "rid": "win",
            "assetType": "runtime",
            "assemblyVersion": "6.0.0.0",
            "fileVersion": "6.0.21.52210"
          }
        }
      },
```
