### ISSUE TITLE
Investigate F# integration into the .NET SDK: figure out what would make it more source-build and smoke-test compatible

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2581]
The F# integration into the SDK is not like other components. As of writing, in the stabilized dotnet/installer 6.0.1xx branch, `dotnet run` on an F# project fails for both the Microsoft build and source-build, because it can't find a 6.0.1 FSharp.Core package. The package doesn't seem to exist anywhere. This can be worked around with some extra args to use a preview package instead:

```
$ dotnet restore /p:_NETCoreSdkIsPreview=true
$ dotnet run --no-restore /p:_NETCoreSdkIsPreview=true
```

This behavior makes it difficult to maintain smoke-tests, and the args cast doubt on our ability to actually test the final product that we deliver.

This needs some investigation. I think that at *least*, we should figure out how to be as sure as possible that we are smoke-testing the right thing. Ideally, F# can be made more source-build friendly overall. (A bonus would be to make it more friendly for Microsoft-built .NET SDK ingestion, too.)

In 6.0, there were some diffs in the FSharp part of the SDK that were concerning, and this ran into our difficulties in smoke-testing F# projects: https://github.com/dagood/source-build/pull/9/files#r736887609.

**Comment by crummel** [comment]
We didn't run into this for the 7.0 release so it appears https://github.com/dotnet/fsharp/pull/13544 was all it took to fix it.  I am still looking into the prebuilts issue but I no longer believe it's related.
