### ISSUE TITLE
Run a F# test on the 6.0.0 SDK that targets missing files according to the SDK diff

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2582]
The 6.0.0 SDK is missing a number of F# dependencies in the FSharp dir:

https://github.com/dagood/source-build/pull/9/files#r736887609

It would be good to run more tests that specifically try to get at features that would depend on those DLLs, to figure out if there's a feature gap caused by the diff.

**Comment by MichaelSimons** [comment]
[Triage] We have eliminated all unexpected FSharp differences.  The only file diffs that remain are Windows components not included in linux.  Additionally we have started running published projects in our scenarios tests.
