### ISSUE TITLE
6.0 SDK diff: unnecessary files redisted in `dotnet-format` dir already present in shared fx

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#2583]
```
./sdk/6.0.100/DotnetTools/dotnet-format/System.Collections.Immutable.dll
./sdk/6.0.100/DotnetTools/dotnet-format/System.Diagnostics.DiagnosticSource.dll
./sdk/6.0.100/DotnetTools/dotnet-format/System.Reflection.Metadata.dll
./sdk/6.0.100/DotnetTools/dotnet-format/System.Runtime.CompilerServices.Unsafe.dll
./sdk/6.0.100/DotnetTools/dotnet-format/System.Text.Encoding.CodePages.dll
./sdk/6.0.100/DotnetTools/dotnet-format/System.Text.Encodings.Web.dll
./sdk/6.0.100/DotnetTools/dotnet-format/System.Text.Json.dll
```

These are in the sharedfx and shouldn't need to be here.

https://github.com/dagood/source-build/pull/9/files/c16bba2273c1519dea0e1c2a031053f8269b8551#r736883570

---

There are some poisoned DLLs also showing up in this directory, but they are distinct from these ones, all `Microsoft.Extensions.*`:
* https://github.com/dotnet/source-build/issues/2577

**Comment by MichaelSimons** [comment]
These diffs are no longer present in .NET 8.0.  Closing.
