### ISSUE TITLE
Tooling to generate SBRP should be included in the SBRP repo

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2609]
The tooling is currently internal.  There is nothing proprietary about the tooling.  It should reside within the SBRP repo to make it easier for anyone to contribute to the tooling as well as to use it to create new packages.

**Comment by dseefeld** [comment]
Fixed with https://github.com/dotnet/source-build-reference-packages/pull/294, https://github.com/dotnet/source-build-reference-packages/pull/300 & https://github.com/dotnet/source-build-reference-packages/pull/302
