### ISSUE TITLE
Add tests for complete built product

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#262]
We should add at least a few quick tests to ensure that the built CLI works correctly. - `dotnet new`, `restore`, `build`, `run`.  Nikolche pointed out that omitting the ILMerge step from the NuGet build has interacted with an MSBuild assembly loading bug in the past, leading to issues with the `dotnet pack` verb, so we should include that as well.

**Comment by dleeapho** [comment]
This seems like a useful initial test to 'fail-fast' if the built cli is not viable.

**Comment by dseefeld** [comment]
Smoke-tests are complete, but we should still add issues to do "dotnet pack"  and "dotnet/publish".

/cc @crummel
