### ISSUE TITLE
Cleanup source-build servicing build definitions

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2622]
There are three different source-build servicing (pre 6.0) build definitions which appears to be overlapping each other and end up running multiple time for the same commits.

[source-build-internal-CI](https://dev.azure.com/dnceng/internal/_build?definitionId=251) - runs on commits to the internal repos
[source-build-official-CI](https://dev.azure.com/dnceng/internal/_build?definitionId=940) - runs on commits and prs
[source-build-rolling-CI](https://dev.azure.com/dnceng/internal/_build?definitionId=114) - runs on commits to the public repos

Only one build should be run for each commit and PR, anything else is wasting compute resources.

**Comment by lbussell** [comment]
I've refactored these pipelines:

- source-build-rolling-CI is deprecated.
- source-build-internal-CI is now [source-build-pre-arcade-CI](https://dev.azure.com/dnceng/internal/_build?definitionId=251). It runs on internal commits, internal PRs, and public commits mirrored to internal branches for 3.1 and 5.0.
- source-build-official-CI is now [source-build-externals-CI](https://dev.azure.com/dnceng/internal/_build?definitionId=940). It runs on internal commits, internal PRs, and public commits mirrored to internal branches for 6.0+ and main, and produces source-build intermediate packages for the tarball build.

The full source-build tarball CI is now associated with the [dotnet/installer](https://github.com/dotnet/installer) repo.
