### ISSUE TITLE
source-build build system sends telemetry, with no way of opting out

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2624]
source-build's standard arguments include the `-ci` flag:

```xml
    <StandardSourceBuildArgs> $(FlagParameterPrefix)ci</StandardSourceBuildArgs>
```

https://github.com/dotnet/installer/blob/db0dfa0c082e4a4e690d1cbb8e3588e3cb949092/src/SourceBuild/tarball/content/repos/Directory.Build.props#L129

This tells arcade to send telemetry:

```bash
  if [[ "$ci" == true ]]; then
    TryLogClientIpAddress
  fi
```

https://github.com/dotnet/arcade/blob/7a5974bab0e9ef7503fc1a9b148960b0a0b47ba3/eng/common/build.sh#L191-L193

What it actually ends up doing is this:

```bash
function TryLogClientIpAddress () {
  echo 'Attempting to log this client''s IP for Azure Package feed telemetry purposes'
  if command -v curl > /dev/null; then
    curl -s 'http://co1r5a.msedge.net/fdv2/diagnostics.aspx' | grep ' IP: ' || true
  fi
}
```

https://github.com/dotnet/arcade/blob/7a5974bab0e9ef7503fc1a9b148960b0a0b47ba3/eng/common/tools.sh#L408-L413

There's a few things here:

- It send telemetry, with no way of opting out
- The data, coming from outsize of Azure doesn't seem like it would be useful to the folks collecting it
- The API endpoint seems to have some rate limit in place. I tried a few builds one after another on my machine and the build hangs for me after printing the message, probably waiting for the API endpoint to reply.

**Comment by MichaelSimons** [comment]
@MattGal - Do you have thoughts on this?  What do you think about adding an option (environment variable) to skip sending this telemetry?

**Comment by omajid** [comment]
If there is supposed to be an environment variable that corresponds to "this build is running under CI with telemetry and full unit tests", could we also utilize it to remove `sudo` for https://github.com/dotnet/installer/issues/12634 ?

**Comment by MichaelSimons** [comment]
This was resolved with https://github.com/dotnet/arcade/issues/8205.  The telemetry logging was removed.  It will still need to flow into the product repos.
