### ISSUE TITLE
6.0.2xx is failing to build with the latest dependency flow.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2626]
https://dev.azure.com/dnceng/public/_build/results?buildId=1472120&view=logs&j=b9699899-7397-58dc-1551-d4801b3b3dfe&t=2beba4da-da67-557f-b169-2ed90945e20d&s=6884a131-87da-5381-61f3-d7acc3b91d76

The dependency flow was merged to unblock other work.

**Comment by MichaelSimons** [comment]
There are multiple issues.

1. SDK breaking online builds - https://github.com/dotnet/sdk/issues/22640
2. msbuild prebuilts breaking offline builds.

**Comment by MichaelSimons** [comment]
Current status:  Online builds pass now.  Offline is failing w/prebuilts which are tracked by the various linked issues.

**Comment by MichaelSimons** [comment]
Current status:  Online builds pass.  One remaining fsharp related prebuilt tracked with https://github.com/dotnet/fsharp/issues/12499.

**Comment by MichaelSimons** [comment]
cc @shushanhf

**Comment by shushanhf** [comment]
> cc @shushanhf

Thanks～

**Comment by MichaelSimons** [comment]
Build passes now - smoke-test fails tracked with https://github.com/dotnet/source-build/issues/2736.
