### ISSUE TITLE
CVE being reported by component governance on SBRP's packages

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2639]
This was first reported by the dotnet/templating repo - https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-templating/alert/4732456?typeId=6669620.  Their reference to SBRP is causing this CG issue to be reported.  This is a bit of a red herring as this is a reference assembly.  That being said, SBRP should not be causing CG issues in consuming product repos.  

I would think all product reference to the vulnerable versions should be upgraded and then removed from SBRP.  For System.Net.Http, SBRP contains the fixed version.  Having [SBRP tooling to identity unused packages](https://github.com/dotnet/source-build/issues/2357) fixed would be helpful here as there may already be no references to the vulnerable versions.

After fixing, please ensure CG is enabled in SBRP so these can be caught.

**Comment by MichaelSimons** [comment]
cc @vlada-shubina

**Comment by vlada-shubina** [comment]
Similar issues with other packages:
- `System.Text.Encodings.Web` (4.6.0) - https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-templating/alert/4732459?typeId=6669620
- `System.Net.Http` (4.1.0) - https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-templating/alert/2977711?typeId=6669620
- `System.Net.Security` (4.3.0) - https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-templating/alert/4732461?typeId=6669620
- `Microsoft.AspNetCore.App.Ref` (3.1.3) - https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-templating/alert/4793566?typeId=6669620
- `Microsoft.AspNetCore.App.Ref` (3.1.2) - https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-templating/alert/4793565?typeId=6669620

**Comment by vatsalyaagrawal** [comment]
This issue is causing CG issues in Roslyn also. What is the ETA for this fix?

**Comment by MichaelSimons** [comment]
I am actively working on resolving these within SBRP.  The System.Net.Http and System.Net.Security alerts are the only two remaining and I just sent a PR for those.  Once fixed I will trigger the dependency flow.

**Comment by MichaelSimons** [comment]
@vatsalyaagrawal - I took a look at the [alerts reported on the Roslyn repo](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-roslyn?_a=alerts&typeId=6265214&alerts-view-option=active) (internal link) and they do not appear to originate from the microsoft.sourcebuild.intermediate.source-build-reference-packages which is what this issue is about.

**Comment by tmat** [comment]
@MichaelSimons Can you confirm this issue will be addressed by your changes?

https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-sourcelink/alert/4654764?typeId=6403486

**Comment by MichaelSimons** [comment]
>Can you confirm this issue will be addressed by your changes?

Yes that was fixed in https://github.com/dotnet/source-build-reference-packages/pull/299.  It should get fixed by https://github.com/dotnet/sourcelink/pull/779 but that PR is failing because the package is published to the .NET 7 feeds which aren't configured.

**Comment by tmat** [comment]
You mean there are packages needed for the build that are not in these feeds?
```
<add key="dotnet-public" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />
    <add key="dotnet-eng" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" />
    <add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />
```

**Comment by MichaelSimons** [comment]
>You mean there are packages needed for the build that are not in these feeds?

They should be but SBRP was associated with the wrong channel in main.  I have corrected this, the [PR](https://github.com/dotnet/sourcelink/pull/779) was updated, and CI passed.

**Comment by MichaelSimons** [comment]
All critical and high alerts have been addressed in SBRP now.  There are a few medium alerts but there is no requirement at this time to address them.  Closing.

**Comment by tmat** [comment]
@MichaelSimons Thanks!

**Comment by tmat** [comment]
Another source-build related issue:
https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-sourcelink/alert/2916597?typeId=6403486

**Comment by MichaelSimons** [comment]
> Another source-build related issue:
https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-sourcelink/alert/2916597?typeId=6403486

@tmat - these are medium alerts which does not meet the bar as being required to address.  These are coming from the project template packages from SBRP can be safely dismissed in sourcelink as `vulnerable code is not used`

**Comment by vlada-shubina** [comment]
@MichaelSimons 

out of list above, the following remains active:
System.Net.Http (4.1.0) - https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-templating/alert/2977711?typeId=6669620

It is high prio - could you please check it? Thank you.

**Comment by MichaelSimons** [comment]
@vlada-shubina - When I look at the vulnerability, it appears as though the source-build leg has been addresses.  Is there another reference outside of source-build?

<img width="772" alt="image" src="https://user-images.githubusercontent.com/8290530/150149557-7b236888-8050-43c5-88cd-553e11e9101c.png">

**Comment by vlada-shubina** [comment]
> @vlada-shubina  - When I look at the vulnerability, it appears as though the source-build leg has been addresses. Is there another reference outside of source-build?
> 
> <img alt="image" width="772" src="https://user-images.githubusercontent.com/8290530/150149557-7b236888-8050-43c5-88cd-553e11e9101c.png">

yes, later I noticed that as well, apologies for early alert. I'm investigating now what package has dependency on 4.1.0, but haven't got anywhere so far. There is no direct dependencies to `System.Net.Http`, i'm investigating dependencies now. 

Likely this is caused by the assemblies excluded from source-build (like tests), otherwise source build won't be fixed either.

**Comment by vlada-shubina** [comment]
@MichaelSimons there is new one reported: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-templating/alert/6882921?typeId=6669620

Could you please check it?

**Comment by MichaelSimons** [comment]
@vlada-shubina - Thanks for brining this to attention.  I opened a separate issue to track this.
