### ISSUE TITLE
Source build do not working with clang 13

### ISSUE THREAD

**Issue by kant2002** [dotnet/source-build#2645]
Is it possible backport https://github.com/dotnet/runtime/pull/60328 to release/6.0 branch? I was trying to compile .NET from sources in Gentoo, and because it is using clang-13 it does not work. 

And I assume some other infra magic should happens, either here, or in `dotnet/installer`.

**Comment by omajid** [comment]
Warnings should get fixed with https://github.com/dotnet/runtime/pull/61442

There's another, much more complex, issue too which is being tracked by  https://github.com/dotnet/runtime/issues/61671

**Comment by kant2002** [comment]
Thanks for the hints, I would follow them closely too. What I was thinking is that I follow Readme.
```
git clone https://github.com/dotnet/installer
cd installer/
git switch -c v6.0.100 v6.0.100
```

and that lead me to clang-13 warnings bug. I now understand that there other issues preventing me from compiling locally, but isn't at least warnings should be in the `v6.0.100` branch right now? I just trying understand process better.

Also, if changes in main right now, what should I do to restart process, just clean sources directory and start again? or there shortcuts for the process?

**Comment by omajid** [comment]
To be honest, I find the process a bit weird too. There are so many different github projects in play and it's hard to figure where a change is and where it next needs to flow to.

The `v6.0.100` commit is actually a tag, not a branch. It matches exactly what was released as "6.0", and it's missing all followup fixes that are have been merged and scheduled to be released in future (bugfix) releases.

The `main` branch is currently developing what will become .NET 7 next year. You shouldn't use it for anything other than testing right now.

If you want to use the main branch (or even rebuild v6.0.100), you will have to start from scratch; there isn't a way to do proper incremental builds at this point.

**Comment by MichaelSimons** [comment]
[Triage] The runtime fix is on target to release w/6.0.2.  We should have documentation for the workflow on how to create a patch for source-build users who would like to get it into 6.0.1.

**Comment by omajid** [comment]
This should have been fixed in the February release of .NET 6. Is anyone still running into this?

**Comment by MichaelSimons** [comment]
[Triage] Closing as the underlying issue has been resolved and we have heard of no more issues.
