### ISSUE TITLE
Automate the poison report generation

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2652]
Dependent on:

https://github.com/dotnet/source-build/issues/2633
https://github.com/dotnet/source-build/issues/2568

**Comment by crummel** [comment]
Notes:
This is a two-part issue - in 3.1/5.0 the process is tooling build -> poison tooling builds if enabled -> poisoning runs -> source-build runs -> poison check runs.  So poison automation needs to be disabled for a dev/default build and CI will enable a flag to build and run poison tooling and checks.
