### ISSUE TITLE
Add SBRP tooling to support text-only packages

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2655]
Tooling should exist to automate the process for adding a text-only package to SBRP.  User should be able to provide the package name and version with an optional feed.  The tooling in dotnet/installers around text-only package generation may be a good reference for implementing this.

**Comment by oleksandr-didyk** [comment]
**Additional information:**
  - existing tooling in `dotnet/installers` can be found [here](https://github.com/dotnet/installer/blob/43f10a2ade067443ca542711727266fae4741762/src/SourceBuild/Arcade/tools/TextOnlyPackages.csproj)
  - entry point for the resulting tooling should be the `./generate.sh` in SB repo root ([source](https://github.com/dotnet/source-build-reference-packages/blob/main/generate.sh))
  - usage of the prepared mechanism should be documented at least in the source build docs (available [here](https://github.com/dotnet/source-build/blob/main/Documentation/sourcebuild-in-repos/new-dependencies.md))

**Comment by oleksandr-didyk** [comment]
Update on progress -> started migrating MSBuild logic found in `dotnet/installers` to SBRP; in general, the idea behind the solution is to have an MSBuild project similar to that in `dotnet/installers`, with the small difference that the package name, version and optionally feed are provided as CL properties provided by the entrypoint script

**Comment by oleksandr-didyk** [comment]
Update on progress -> during PR review it was decided to extend the current task goal with merging the existing reference package generation tooling and the proposed text-only one for better maintenance / re-usability; currently working on adding that to the opened PR

**Comment by oleksandr-didyk** [comment]
Update on progress -> PR feedback incorporated into the branch, waiting for re-review
