### ISSUE TITLE
Don't exclude internal feeds when they are available

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2664]
https://github.com/dotnet/source-build/blob/release/5.0/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/RemoveInternetSourcesFromNuGetConfig.cs#L76-L77 excludes internal feeds even for the online internal build.  I think this has been the hidden root cause for several missing package errors in internal builds that we have seen come and go over time.  We already use an [environment variable](https://github.com/dotnet/source-build/blob/release/3.1/repos/Directory.Build.targets#L191) in the targets file calling this code to guess whether we are running in an internal build environment so I think this should be a simple matter of letting the RemoveInternetSources task know about that and adjust this condition to only exclude those feeds in offline or non-internal environments.

**Comment by MichaelSimons** [comment]
[Triage] Closing as the ROI does not justify the work given the nearby EOL.
