### ISSUE TITLE
We should remove versions of ref packages we already have implementation packages for

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2666]
This leads to a recurring problem where the build grabs the ref package instead of the implementation package and causes issues in the downstream build.  I propose:
- after extracting both the previously-source-built and ref packages tarballs, delete any ref package that match the PSB packages.
- when copying packages to the blob feed after each build, check for and delete any match ref packages.

**Comment by MichaelSimons** [comment]
Going forward starting with 6.0 - the previous-source-built and ref packages scenario is covered by https://github.com/dotnet/source-build/issues/2357 and isn't something we should handle within the tarball build process.

**Comment by MichaelSimons** [comment]
[Triage] Closing as the ROI does not justify the work given the nearby EOL.
