### ISSUE TITLE
[release/6.0.1xx] Ensure release tags are automatically created when 6.0.102 is released

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2693]
Automation is in place but there were some permissions issues that broke it in 6.0.101.  These issues have been resolved but there is no way to validate the E2E until the next release.  This applies to SBRP as well as the source-build repo.

**Comment by MichaelSimons** [comment]
@rbhanda - I am not finding that the 6.0.102 release tags were created in https://github.com/dotnet/source-build-reference-packages or https://github.com/dotnet/source-build.  Can you investigate on your side to see why the automation failed to create these?

**Comment by rbhanda** [comment]
Thanks a lot for flagging this. I have pushed the tags manually as of now. We are investigating why the automation did not tag these.

**Comment by MichaelSimons** [comment]
After discussion with the release team, there does not seem to be a requirement to tag source-build and source-build-reference-packages after moving source-build into installer.
