### ISSUE TITLE
[release/3.1][release/5.0] Ilasm and Ildasm not in correct location on Alpine Linux build

### ISSUE THREAD

**Issue by ayakael** [dotnet/source-build#2697]
# Issue
Various steps in the build process looks for ilasm in ildasm in $builddir/src/dotnet-3.1/Tools/source-built/coreclr-tools/x64 while they are  built to $builddir/src/dotnet-3.1/Tools/source-built/coreclr-tools on Alpine Linux 3.15.

# To reproduce
Build on Alpine Linux 3.15 using APKBUILD available at: https://gitlab.alpinelinux.org/ayakael/aports/-/tree/testing/dotnet/testing/dotnet31 without build_coreclr-tools-path.patch

# To fix
I constructed the following patch:
```
From 4603257752b01b60f1c1f2d1c2a77e07ae814647 Mon Sep 17 00:00:00 2001
From: "build@apk-groulx" <build@apk-groulx.praxis>
Date: Sun, 5 Dec 2021 15:46:08 +0000
Subject: [PATCH 1/1] Ildasm and ilasm paths changed to where they actually
 apper

---
 Directory.Build.props       | 4 ++--
 repos/coreclr-portable.proj | 2 +-
 repos/coreclr.common.props  | 2 +-
 repos/coreclr.proj          | 4 ++--
 4 files changed, 6 insertions(+), 6 deletions(-)

diff --git a/Directory.Build.props b/Directory.Build.props
index f6a6f54..8247c3e 100644
--- a/Directory.Build.props
+++ b/Directory.Build.props
@@ -133,8 +133,8 @@
     <AspNetRazorBuildServerLogDir>$(BaseOutputPath)aspnet-debug</AspNetRazorBuildServerLogDir>
     <AspNetRazorBuildServerLogFile>$(AspNetRazorBuildServerLogDir)razor-build-server.log</AspNetRazorBuildServerLogFile>
     <IlasmPath Condition="'$(OfflineBuild)' != 'true'">invalid: ILAsm is not expected to be needed in the online build</IlasmPath>
-    <IlasmPath Condition="'$(OfflineBuild)' == 'true'">$(PrebuiltSourceBuiltPackagesPath)coreclr-tools/$(BuildArchitecture)/ilasm</IlasmPath>
-    <IldasmPath Condition="'$(OfflineBuild)' != 'true'">$(ToolPackageExtractDir)coreclr-tools/$(BuildArchitecture)/ildasm</IldasmPath>
+    <IlasmPath Condition="'$(OfflineBuild)' == 'true'">$(PrebuiltSourceBuiltPackagesPath)coreclr-tools/ilasm</IlasmPath>
+    <IldasmPath Condition="'$(OfflineBuild)' != 'true'">$(ToolPackageExtractDir)coreclr-tools/ildasm</IldasmPath>
     <IldasmPath Condition="'$(OfflineBuild)' == 'true'">invalid: ILDasm is not expected to be needed in the offline build</IldasmPath>
     <!-- Dir where git info is generated during online builds. -->
     <GitInfoOutputDir>$(BaseOutputPath)git-info/</GitInfoOutputDir>
diff --git a/repos/coreclr-portable.proj b/repos/coreclr-portable.proj
index 78adc14..378547e 100644
--- a/repos/coreclr-portable.proj
+++ b/repos/coreclr-portable.proj
@@ -19,7 +19,7 @@
           Inputs="$(MSBuildProjectFullPath)"
           Outputs="$(RepoCompletedSemaphorePath)CopyTools.complete">
     <PropertyGroup>
-      <CoreClrDestinationDir>$(ToolPackageExtractDir)coreclr-tools/$(BuildArchitecture)</CoreClrDestinationDir>
+      <CoreClrDestinationDir>$(ToolPackageExtractDir)coreclr-tools</CoreClrDestinationDir>
       <AssemblyExtension Condition="'$(TargetOS)' == 'Linux'">so</AssemblyExtension>
       <AssemblyExtension Condition="'$(TargetOS)' == 'FreeBSD'">so</AssemblyExtension>
       <AssemblyExtension Condition="'$(TargetOS)' == 'OSX'">dylib</AssemblyExtension>
diff --git a/repos/coreclr.proj b/repos/coreclr.proj
index 7e67b28..037c68a 100644
--- a/repos/coreclr.proj
+++ b/repos/coreclr.proj
@@ -15,11 +15,11 @@
   <!-- OSX and portable only build this and not coreclr-portable, so we need to copy its tools here -->
   <Target Name="CopyTools"
           AfterTargets="Package"
-          Condition="'$(TargetOS)' == 'OSX' or '$(PortableBuild)' == 'true'"
+          Condition="'$(TargetOS)' == 'OSX' or '$(PortableBuild)' == 'true' or '$(TargetRid)' == 'linux-musl-x64'"
           Inputs="$(MSBuildProjectFullPath)"
           Outputs="$(RepoCompletedSemaphorePath)CopyTools.complete">
     <PropertyGroup>
-      <CoreClrDestinationDir>$(ToolPackageExtractDir)coreclr-tools/$(BuildArchitecture)</CoreClrDestinationDir>
+      <CoreClrDestinationDir>$(ToolPackageExtractDir)coreclr-tools</CoreClrDestinationDir>
       <AssemblyExtension Condition="'$(TargetOS)' == 'Linux'">so</AssemblyExtension>
       <AssemblyExtension Condition="'$(TargetOS)' == 'FreeBSD'">so</AssemblyExtension>
       <AssemblyExtension Condition="'$(TargetOS)' == 'OSX'">dylib</AssemblyExtension>
-- 
2.34.0
```
This would not work for other platforms, as I assume other platforms *do* actually look for ilasm and ildasm in currect location.

# Note
I would've opened this issue in dotnet/coreclr, but unfortunately that space has been closed. Should I send this to dotnet/runtime?

Made as part of Alpine Linux dotnet31 / dotnet5 packaging project, see dotnet/source-build#2695

**Comment by ayakael** [comment]
@omajid I see that ya'll encountered this bug in dotnet31 on Fedora. Any idea what causes this issue?

**Comment by omajid** [comment]
I am almost positive I know what this is, but I can find any references/details in my notes or here on github.

Here's what I remember:

- At some point source-build 3.1 broke going from a N-1 build of 3.1 to the N build of 3.1. The N-1 build had coreclr-tools placed in one location, and the N build was looking at it in another location
- In source-build, this was "fixed" by updating the artifacts for N-1 build in-place manually
- For Fedora, I patched the build to look for coreclr-tools in the old location

Now that I am thinking about it, I am not sure this is needed anymore:

- For recent builds they have a consistent location for N-1 and N coreclr-tools
- The recent builds put coreclr-tools in *both* `coreclr-tools/$(BuildArchitecture)"` and `coreclr-tools/`

I wonder if this patch is really needed anymore...

**Comment by ayakael** [comment]
I remember an important detail: ilasm was present in both locations, except that the one in  `coreclr-tools/$(BuildArchitecture)` gave me a segmentation fault, no doubt because it's pulled from linux-x64 prebuilt `Private.SourceBuilt.Artifacts`. The version available in `coreclr-tools/` worked with linux-musl-x64, which makes sense given the source-build "fix" that updates the artifacts in-place. No doubt this becomes a non-issue with local `Private.SourceBuilt.Artifacts`, which means my patch is only necessary when building with `dotnet31-stage0-artifacts` package. I'll test, see if some patches cease to be necessary when building with `dotnet31-bootstrap-artifacts` (bootstrap being the musl built version)

**Comment by ayakael** [comment]
Confirming that with proper artifacts dotnet-3.1 does not need this patch anymore, and dotnet 5.0 has no need for it at all.
