### ISSUE TITLE
[release/5.0] OSX fails smoke tests on missing XML files

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2700]
The source-build OSX build is successful and passes all smoke tests, but fails at the end of the tests because it's missing some xml files. I've attached a full build log containing the list of files and the failure at the end.

[osx-net5-xml-failure-log.txt](https://github.com/dotnet/source-build/files/7747309/osx-net5-xml-failure-log.txt)

**Comment by lbussell** [comment]
I have worked around this issue for now with https://github.com/dotnet/source-build/pull/2702, so our CI is unblocked.

**Comment by MichaelSimons** [comment]
[Triage] This has been a problem area in the past related to old runtimes which has special logic in the tests to handle.  Given the near EOL, the ROI does not justify fixing.
