### ISSUE TITLE
6.0.101 fails bootstrap builds.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2706]
This is because there are three runtime packages that weren't built with 6.0.101

* System.Runtime.CompilerServices.Unsafe
* System.Text.Encodings.Web
* Microsoft.Bcl.AsyncInterfaces

These package are marked as IsPackable, but don't have GeneratePackageOnBuild set therefore they are not being built in 6.0.1 and later: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fblob%2Frelease%2F6.0%2Fdocs%2Fproject%2Flibrary-servicing.md%23check-if-a-package-is-generated&amp;data=04%7C01%7Cmichael.simons%40microsoft.com%7C15d84e0fe6bd4cec107108d9c17cd05d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637753564091200710%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=NSKquzP5QNivJZihDN4p0Ep1RXB8dJQWkkC5IHgImro%3D&amp;reserved=0

**Comment by MichaelSimons** [comment]
Opened https://github.com/dotnet/runtime/issues/63451 to get input from the runtime folks.

**Comment by omajid** [comment]
This issue was moved to the "Done" column in the issue board. Presumably this should have been closed at that time.

@MichaelSimons please re-open if I have this wrong.
