### ISSUE TITLE
Automate the publishing process of source tarballs for servicing releases

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2710]
This involves taking the source ~~and smoke-test-prereqs~~ tarball and publishing to the internal blob storage account with the correctly versioned names.

**Comment by lbussell** [comment]
Providing some more clarity, the steps required to complete this work are:

- Read installer build information from our internal release (non-source-build) pipelines
- Upload dotnet source tarball to azure storage (dotnetcli)
- Upload source-build artifacts to azure storage (dotnetclimsrc)

Reference: https://github.com/dotnet/source-build/blob/3c8f23d08475e6f59a5ca889e0719b61e18db476/.github/ISSUE_TEMPLATE/releases/release_checklist.md

**Comment by lbussell** [comment]
Smoke test prereqs will be handled by: https://github.com/dotnet/source-build/issues/3068
