### ISSUE TITLE
Create VS Code Remote / GitHub Codespaces Dev Container for Source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2712]
The desired outcome is to provide an experience where a developer can come to source build and immediate start developing/contributing with a low barrier of entry.

For details see [VS Code Remote / GitHub Codespaces Container](https://github.com/microsoft/vscode-dev-containers)

**Comment by lbussell** [comment]
Completed with https://github.com/dotnet/installer/pull/14084
