### ISSUE TITLE
Investigate the usefulness of enable Codespaces prebuilds

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2713]
The desired outcome is that any developer can come to the installer repo and utilize Codespaces prebuilds to instantly get an environment where there source-build tarball is created and built.  They can instantly start working with the source-build environment.  Maybe the build is failing so they want to investigate, maybe they want to inspect prebuilts, etc.  There maybe two prebuild permutations that are of interest.  One, where the source-tarball is already created.  Second, where the source-tarball has been built.

Prereq:  https://github.com/dotnet/source-build/issues/2712

Addition info on Codespaces prebuilds: https://github.com/github/codespaces-precache#step-1-set-up-access-token

**Comment by lbussell** [comment]
I added the codespaces prebuild configuration with https://github.com/dotnet/installer/pull/14084. There is still the outstanding bug linked above, but the work for this is otherwise done.
