### ISSUE TITLE
source-build for .NET 6 can build a SDK that's missing components

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2731]
I have a source-built SDK that was causing errors when I was trying to use it. Turns out it doesn't have `Microsoft.NET.Sdk`

```
$ find /usr/lib64/dotnet -iname SDK.prop
/usr/lib64/dotnet/sdk/6.0.100/Sdks/FSharp.NET.Sdk/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.Docker.Sdk/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.ILLink.Tasks/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Publish/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Web/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Web.ProjectSystem/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Worker/Sdk/Sdk.props
```

I have seen this issue on arm64 on a couple of different operating systems now, including Fedora Rawhide and CentOS 8 (only heard about this one). The bootstrap build (that is, one using `prep.sh` + prebuilts) works and produces a working SDK. The second build produces an SDK which is  missing `Microsoft.NET.Sdk`. The build itself does not fail. The sdk tarball is built too, but it's just missing that one (?) SDK.

I don't know what's causing it.

This can be seen on  arm64 Rawhide right now:

```
$ podman run -it registry.fedoraproject.org/fedora:rawhide
...
# uname -m
aarch64
...
# dnf install -y dotnet-sdk-6.0 findutils
...
# find /usr/lib64/dotnet -iname Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/FSharp.NET.Sdk/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.Docker.Sdk/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.ILLink.Tasks/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Publish/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Web/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Web.ProjectSystem/Sdk/Sdk.props
/usr/lib64/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk.Worker/Sdk/Sdk.props
```

**Comment by crummel** [comment]
Michael and I are looking at this one now.

**Comment by omajid** [comment]
FWIW, I have only seen this on arm64. I could not reproduce this on any x64 machine I have.

**Comment by omajid** [comment]
I have not been able to reproduce a bad build. I took the same SDK on arm64/rawhide that was used to build the buggy one, and tried to use it to build the exact same set of sources as the buggy build. It produces a working building :confused:

**Comment by omajid** [comment]
From what I can tell, this must be the log of the bad build (the one that produces an SDK without `Microsoft.NET.Sdk` dir: https://kojipkgs.fedoraproject.org//packages/dotnet6.0/6.0.100/2.fc36/data/logs/aarch64/build.log

it looks like the SDK nuget packages were produced:

```
  New NuGet package(s) after building sdk:
    -> Microsoft.DotNet.Cli 6.0.100-rtm.21527.8
    -> Microsoft.DotNet.Cli.Sln.Internal 6.0.100-rtm.21527.8
    -> Microsoft.DotNet.Cli.Utils 6.0.100-rtm.21527.8
    -> Microsoft.DotNet.Compatibility 1.0.0-rtm.21527.8
    -> Microsoft.DotNet.Configurer 6.0.100-rtm.21527.8
    -> Microsoft.DotNet.InternalAbstractions 6.0.100-rtm.21527.8
    -> Microsoft.DotNet.MSBuildSdkResolver 6.0.100-rtm.21527.8
    -> microsoft.dotnet.templateLocator 6.0.100-rtm.21527.8
    -> Microsoft.NET.Build.Extensions 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.BlazorWebAssembly 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.Publish 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.Razor 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.Web 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.Web.ProjectSystem 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.Worker 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.WorkloadManifestReader 6.0.100-rtm.21527.8
    -> Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver 6.0.100-rtm.21527.8
    -> Microsoft.SourceBuild.Intermediate.sdk 6.0.100-rtm.21527.8
```

**Comment by omajid** [comment]
Just ran into it again at https://centos.softwarefactory-project.io/zuul/t/centos/build/3d814e5f33c3412493159a91c737711f

This time, it was an x86_64 build.

I think this is the build log: https://kojihub.stream.rdu2.redhat.com/kojifiles/packages/dotnet6.0/6.0.100/1.el9~bootstrap/data/logs/x86_64/build.log

**Comment by MichaelSimons** [comment]
[Triage] Closing as this hasn't occurred in some time.  Closing, but please feel free to reopen if it happens again.
