### ISSUE TITLE
Post-net7, remove TFM patches from NuGet

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2745]
After net7, source-build should align with NuGet TFMs, so we can remove all TFM changes and hopefully stay that way going forward.  This includes:
- build/common.project.props TFM selection
- individual project TFM changes
- NuGet.Build.Tasks.Pack changes to account for differing TFMs

**Comment by MichaelSimons** [comment]
[Triage] All nuget patches have been removed in .NET 7.0.  Closing as obsolete.
