### ISSUE TITLE
Error bootstrapping .NET 6 on CentOS Stream 9; failure building source-build-reference-packages

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2757]
I am having trouble bootstrapping .NET 6 on CentOS Stream 9. The initial build builds, but the second build fails.

Errors look mostly like this:

```
error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

Here's an online build log that shows the error: 

https://centos.softwarefactory-project.io/logs/5/5/eab7569826a07a7ecf5b7177334298c628481c7f/check/mock-build/067b710/job-output.txt

Here's a binlog of the same error from (but a separate local build) http://people.redhat.com/~omajid/scratch/source-build-2022-02-14.binlog

### Steps to Reproduce

On a Fedora machine, after installing `centpkg`: https://copr.fedorainfracloud.org/coprs/james/centpkg/

```
centpkg clone -a dotnet6.0
cd dotnet6.0
git remote add omajid https://gitlab.com/omajid/centos_rpms_dotnet6.0.git
git fetch --all
git checkout bz1986211-disable-bootstrap2
centpkg --release c9s mockbuild
```

### Other Information

This worked in upstream CI using CentOS Stream 9.

This same set of binaries build on RHEL 9, which is supposed to be identical to CentOS Stream 9.

**Comment by MichaelSimons** [comment]
@omajid - Could you please share the following file - `/builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/source-build-reference-packages.fc184172bf8144f7c91a7bc0226b7d90c5821576/artifacts/source-build/self/package-cache/microsoft.netframework.referenceassemblies.net461/1.0.2/build/.NETFramework/v4.6.1/mscorlib.dll`?

**Comment by omajid** [comment]
[mscorlib.dll.tar.gz](https://github.com/dotnet/source-build/files/8072237/mscorlib.dll.tar.gz)

**Comment by MichaelSimons** [comment]
I am not spotting the issue.  The one thing that is interesting is all the build errors are from packages that aren't referenced by source-build and have since been removed.  Would it be possible to try updating the SBRP commit sha to latest release/6.0?

**Comment by omajid** [comment]
Thanks!

I updated to 6.0.102 and that built fine using the 6.0.100 build.

I am glad it works, but I wish I knew why it wasn't working before :confused:
