### ISSUE TITLE
Separate previously-source-built packages into IL and RID-specific groups

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2758]
In 5.0, we had a "Gather packages" leg which took RID-specific packages from all the individual legs and combined them into one tarball, along with universal packages, to create the previously-source-built tarball that was used in future builds.

A more storage-efficient and CI-friendly way of doing this would be to have one PSB tarball for universal packages, along with independent packages for each RID as needed.

**Comment by MichaelSimons** [comment]
[Triage] We no longer gather artifacts to create a single PSB tarball.  Prep.sh has eliminated the need for this.
