### ISSUE TITLE
Cleanup --bootstrap argument in prep.sh

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2759]
After implementing https://github.com/dotnet/source-build/issues/2630 and https://github.com/dotnet/source-build/issues/2758, we should no longer need the `--bootstrap` argument in prep.sh.  This will make it easier to optimize our previously-source-built package structure to include only the intermediate packages rather than both the intermediates and individual packages.

**Comment by MichaelSimons** [comment]
[Triage] There is still value in supporting the --bootstrap argument.  We would like to avoid a multi-arch previous source-build artifacts tarball.
