### ISSUE TITLE
Update smoke-tests to gather microsoft.net.runtime.monoaotcompiler.task prereq

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2774]
During servicing releases, the smoke-tests prereqs gathering logic should be updated to include the `microsoft.net.runtime.monoaotcompiler.task` package which is required to run `dotnet workload install macos`

**Comment by MichaelSimons** [comment]
Ideally this would be solved with https://github.com/dotnet/arcade/issues/8592

**Comment by omajid** [comment]
FWIW, the `macos` workload has been removed as a possible installation option on Linux (which is entirely sensible, I am not sure why it was working in the first place). So I am using `dotnet workload install wasm-tools` now  (https://github.com/redhat-developer/dotnet-regular-tests/pull/195) which has a similar issue. It fails at a missing `microsoft.net.runtime.webassembly.sdk`.

**Comment by MichaelSimons** [comment]
This is duplicate of https://github.com/dotnet/source-build/issues/3068
