### ISSUE TITLE
[Alpine Linux] Dotnet6 package

### ISSUE THREAD

**Issue by ayakael** [dotnet/source-build#2782]
I am currently working on an Alpine Linux dotnet6 package, and in the process of having packages merged for dotnet31 and dotnet5. As the build process is different for dotnet6 and above, I've been working on redesigning the APKBUILD. 

Here is the repo where the work is being done: https://gitlab.alpinelinux.org/ayakael/aports/-/tree/testing/dotnet6

## Patch notes
* **aspnetcore_always-build-App.Ref-and-the-targeting-packs.patch** (dotnet/aspnetcore#39471)
Aspnetcore doesn't build certain packages every build, This patches forces building them.
* **build_copy-sbrp-from-artifacts-instead-of-move.patch** (see dotnet/installer#13118)
It is expected that location of --with-packages should be writable, thus allowing SBRP to be moved. In cases where Artifacts are provided by distro packages (like with Fedora and Alpine), that folder will be read-only. Thus build fails when there is an attempt at moving SBRP. This patch adjusts so that SBRP is copied rather than moved.
* **build_fix-musl-build.patch** (see dotnet/installer#13119)
Aspnetcore looks for linux-x64 version of nupkgs that, under Alpine, should be linux-musl-x64. Adjusting aspnetcore has a downstream effect on installer, thus needing adjustment there as well. 
* **command-line-api_fix-musl.build.patch**
Command-line-api looks for Runtime nupkgs for non-musl systems, causing errors as they are not provided by artifacts package. This patch fixes this by making linux-nusl-x64 the only platform supported
* **command-line-api_use-work-tree-with-git.patch** (see dotnet/command-line-api#1401)
This makes things work better in a source-tarball build, where there may be a .git directory but it's for a different repo than command-line-api.
* **fsharp_use-work-tree-with-git.patch** (see dotnet/source-build#2445)
This makes things work better in a source-tarball build, where there may be a .git directory but it's for a different repo than fshap.
* **installer_include-musl-bits-in-source-build-bootstrap-tarball.patch** (see dotnet/installer#13076)
This makes the "portable" tarball portable to musl-based Linux distributions as well.
* **installer_internal-repo-fix.patch** (see dotnet/installer#12852)
Add logic to convert internal repo uris in version.details.xml
* **installer_musl-build-fix.patch**
Installer doesn't know to look for CrossGen2 nupkg on anything other than linux-$(BuildArchitecture). It should rather be $(SharedFrameworkRid) to match actual RID,
* **runtime_add-rid-for-alpine-315.patch** (see dotnet/runtime#64304)
Adds RID for Alpine 3.15
* **runtime_disable-package-validation.patch** (see dotnet/runtime#60881)
Disable package validation which breaks build.
* **runtime_force-microsoftnetcoreilasmpackageruntimeid-as-musl.patch**
Runtime doesn't know to look for linux-musl version of Microsoft.NETCore.Ilasm nupkgs. This forces looking for it
* **runtime_non-portable-distrorid-fix-alpine.patch** (see dotnet/runtime#62942)
Runtime doesn't generate a proper distro-rid for Alpine, leaving the last version digit. This, treating the RID like RHEL, removes the trailing digit
* **runtime_release-6.0-Build-all-packages-when-in-source-build.patch** (see dotnet/runtime#63653)
Similar to aspnetcore, not all packages are built every build. This forces building them.
* **sdk_telemetry-optout.patch**
Optouts of SDK telemetry
* **source-build-reference-packages_musl-check.patch** (see dotnet/source-build-reference-packages#318)
Use the same logic as dotnet-isntall.sh to identify whether a system is musl-based or not. For musl-based Linux systems, use `linux-musl` as the platform name, which leads to better RID names. 
* **vstest_use-work-tree-with-git.patch** (see microsoft/vstest#3046)
This makes things work better in a source-tarball build, where there may be a .git directory somewhere in our parent directories but it's for a different repo than vstest
* **xliff-tasks_use-work-tree-with.git.patch** (see dotnet/source-build#2445)
This makes things work better in a source-tarball build, where there may be a .git directory somewhere in our parent directories but it's for a different repo than xliff-tasks

For issue page for dotnet31 and dotnet5 package, please see dotnet/source-build#2695

**Comment by ayakael** [comment]
@MichaelSimons Many thanks!

**Comment by ayakael** [comment]
@omajid How did you get s390x architecture built on Fedora without prebuilt binaries? Did you crosscompile?

**Comment by omajid** [comment]
Basically, yes. @uweigand did the initial cross compile and produced the s390x SDK and nuget packages. I put them in [a tarball](https://src.fedoraproject.org/lookaside/pkgs/dotnet6.0/dotnet-s390x-prebuilts-2021-10-29.tar.gz/sha512/6ea9d857edce50efd1cc35a73b3b3ccb170bbdb5cc4c8b20fb0ee1c7cb75cc573a565b01ef1bf4eec10a3e6e5209143957425cee5ff3fe24c7c1c89813272a99/dotnet-s390x-prebuilts-2021-10-29.tar.gz) and used them to bootstrap source-build on s390x, same way we did for arm64.

@uweigand, can you helps us figure out how to cross compile for alpine (musl, s390x)?

**Comment by ayakael** [comment]
> Basically, yes. @uweigand did the initial cross compile and produced the s390x SDK and nuget packages. I put them in [a tarball](https://src.fedoraproject.org/lookaside/pkgs/dotnet6.0/dotnet-s390x-prebuilts-2021-10-29.tar.gz/sha512/6ea9d857edce50efd1cc35a73b3b3ccb170bbdb5cc4c8b20fb0ee1c7cb75cc573a565b01ef1bf4eec10a3e6e5209143957425cee5ff3fe24c7c1c89813272a99/dotnet-s390x-prebuilts-2021-10-29.tar.gz) and used them to bootstrap source-build on s390x, same way we did for arm64.
> 
> @uweigand, can you helps us figure out how to cross compile for alpine (musl, s390x)?

To plug easily into the current build process, it'd be a question of indeed having a prebuilt tarball available online similar to `dotnet-sdk-6.0.102-linux-musl-x64.tar.gz` and `Private.SourceBuilt.Artifacts.0.1.0-6.0.100-bootstrap.29.tar.gz`

**Comment by ayakael** [comment]
I'm experimenting with https://github.com/redhat-developer/dotnet-regular-tests/ to see about using that testing suite for alpine. Unfortunately, lots of tests fail with dotnet 6.0.3, which makes me wonder if the testing suite is the problem. How portable is this testing suite to `linux-musl` environment?

**Comment by omajid** [comment]
That test suite was designed and tested with the assumption that it would be testing rpm-packaged .NET SDKs in a rpm+glibc based Linux distribution. There are going to be lots of test failures on other environments, even on `linux-x64`.

If you are interested, we can try and improve that test suite by diasbling certain tests on `linux-musl` and/or fixing the broken tests to handle linux-musl correctly. Can you share test results and/or logs?

Or, better yet, help me add Alpine to [the CI matrix](https://github.com/redhat-developer/dotnet-regular-tests/blob/main/.github/workflows/ci.yml) ?

**Comment by ayakael** [comment]
@uweigand  I'd appreciate access to those scripts :) As a package maintainer, I've never had the chance to experiment with crosscompiling, so this looks like a fun project. Ideally, I'd like to be able to run a single script in a `alpine-x64` environment that builds an `linux-musl-s390x` sdk + artifacts tar that can be pulled by Alpine's `dotnet6-stage0` package. 

The completionist in me would eventually like to build for `x86`, `armhf`, `ppc64le`. Cross-compiling for `s390x` sets the groundworks for those.

BTW excellent news, `dotnet6` is slated for inclusion in Alpine 3.16 on `x86_64`, `aarch64` and `armv7` platform ^^ looks like it'll be released in May. `dotnet31` and `dotnet5` won't make it for they're EOL soon. `dotnet6` will be supported for a long time given its LTS status.

**Comment by ayakael** [comment]
One last thing that has been in the back of mind is the naming convention. Why is runtime packaged under `dotnetx-runtime `and sdk under `dotnetx-sdk`? Why not have `dotnetx` package runtime bits and `dotnetx-dev` package sdk bits? I feel like that is more in line with how most distros do it. Alpine, for example, has the `-dev `subpackage. I suppose now that 3.16 is weeks away, I'm getting cold feet about certain decisions.

**Comment by ayakael** [comment]
Above bug was introduced with musl 1.2.3, opened up an issue with runtime here https://github.com/dotnet/runtime/issues/67763

**Comment by ayakael** [comment]
dotnet6 is now in community, rejoice! After many moons of work, it is time to close this issue

**Comment by uweigand** [comment]
> @uweigand I'd appreciate access to those scripts :) 

@ayakael sorry for the late reply, I've been out sick.   Not sure if you still need those at this point, but I've attached the set of scripts I've been using to cross-build a 6.0.100 SDK for s390x.   These are intended to run on Ubuntu 20.04 (or 18.04) with a cross-compile environment targeting s390x installed.

[dotnet-s390x.tar.gz](https://github.com/dotnet/source-build/files/8463748/dotnet-s390x.tar.gz)

**Comment by ayakael** [comment]
@uweigand Awesome, much obliged! Do you consent for me to share this with a select few Alpine developpers so we can work on creating this cross-compile environment on Alpine?

**Comment by uweigand** [comment]
Absolutely, feel free to share.
