### ISSUE TITLE
Enhance SBRP tooling to include dependencies when generating reference packages

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2796]
When generating reference packages for SBRP, sometimes their dependencies also need to be generated. The SBRP tooling should be able to walk the dependency graph defined in the nuspec files so that we can generate the desired packages and all of its required dependencies all at once. This will also make it easier for any .NET developer to generate reference packages when they are needed instead of relying on the source build team.

**Comment by MichaelSimons** [comment]
I believe the generate tooling already behaves this way.  @lbussell can you confirm?  If this is an issue can you provide a concrete example that is broken?
