### ISSUE TITLE
Add additional validation to SBRP

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2804]
The following validation logic should be added to the SBRP build.

1. Ensure no packages are signed.  Signed package are an indication that the package did not originate from SBRP.  This is particularly relevant to text-only packages.
2. Ensure all packaged assemblies have the following attribute indicating the originated from SBRP.

`[assembly: AssemblyInformationalVersion("<x.y.z> built by: SOURCEBUILD")]`

**Comment by omajid** [comment]
Could/should we do the same for unmanaged binaries?

**Comment by MichaelSimons** [comment]
> Could/should we do the same for unmanaged binaries?

Can you give me an example of an unmanaged binary in SBRP that you are referring to?  Are you referring to checking for the presence of (e.g. ensuring they don't exist)?

**Comment by omajid** [comment]
Uh, I think I misread the issue. I was thinking about source-build in general, not SBRP in particular.

**Comment by ellahathaway** [comment]
Marking as blocked since https://github.com/dotnet/source-build/issues/3724 needs to be completed first.
