### ISSUE TITLE
[release/3.1] [release/5.0] Previously Source Built Artifacts have differing size when created manually

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2807]
### Describe the Bug

An issue with RHEL CI meant that we needed to manually build and create the Previously Source-Built artifacts archive for .NET 5.0.212. The resulting artifacts tarball is 2.3 GiB vs. previous months being around 1.4-1.7 GiB.

### Steps to Reproduce

1. Grab all CI previously source built artifacts from the legs specified here, except for RHEL:

https://github.com/dotnet/source-build/blob/e01134818d4189e0f402b664c0e0e7cd507624d1/.vsts.pipelines/builds/matrix.yml#L140-L147

2. Follow the instructions in [prepare-artifacts.yml](https://github.com/dotnet/source-build/blob/release/5.0/.vsts.pipelines/stages/prepare-artifacts.yml) exactly to create the previously source built archive.

3. Examine the size of the resulting archive.

**Comment by MichaelSimons** [comment]
[Triage] @crummel is this affecting 3.1 as well?

**Comment by lbussell** [comment]
From my research, it seems that we have never had RHEL artifacts in both the 3.1 and 5.0 Previously Source Built Artifacts archives. My guess is that this is a CI issue with the way that the artifacts are uploaded. I'll continue to investigate.

**Comment by crummel** [comment]
The missing RHEL packages is acceptable as these fall back to CentOS7 artifacts, similar to how release/6.0 is working now.  With the ending EOLs this doesn't seem worth doing at this point.
