### ISSUE TITLE
CentOS 8 is EOL

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2810]
[CentOS 8 is EOL](https://www.centos.org/centos-linux-eol/), this has been known for some time. We have CentOS 8 CI legs in all current .NET source-build branches (3.1, 5.0, 6.0). We should migrate to CentOS Stream 8, which has [support until 2024](https://wiki.centos.org/About/Product). It is up for debate which branches we should move to Stream 8.

**Comment by MichaelSimons** [comment]
[Triage] we should define a policy for what we run CI on.  It will list distros and versions.  This will then guide the correct action when new versions are released and reach EOL.

**Comment by MichaelSimons** [comment]
Defining a policy is tracked with https://github.com/dotnet/source-build/issues/2813

**Comment by MichaelSimons** [comment]
This was fixed with https://github.com/dotnet/installer/pull/14321
