### ISSUE TITLE
Investigate new online prebuilt S.R.Metadata in Arcade

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2820]
This is a new online-only prebuilt that appears to have been brought into Arcade in the last two months.

**Comment by crummel** [comment]
Notes: Michael stopped seeing this with the 6.0.104 previously-source-built package in 6.0.2xx.  Logan is seeing it in 7.0p3 after adding razor-compiler to the build.

**Comment by MichaelSimons** [comment]
I no longer see this in 6.0.1xx as well in the latest builds - https://dev.azure.com/dnceng/internal/_build/results?buildId=1720897&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by crummel** [comment]
Closing as this no longer is reported as a prebuilt in 6.0.5.
