### ISSUE TITLE
Simplify NuGet.config injection to just replace with a source-build-blessed file

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2838]
When there are no more prebuilts in a build, we should be able to just replace each repo's NuGet.config with a source-build NuGet.config that only references previously-source-built, reference-packages, and the blob-feed.  Right now we are still just injecting all of these feeds (+ prebuilt) into the NuGet.config.  This would give us extra assurance that we are only using source-built package in the build.

**Comment by MichaelSimons** [comment]
[Triage] With the VMR, individual repo nuget.configs could be cloaked and then a common shared nuget.config could exist at the root.  This would eliminate the need for injection logic.

**Comment by MichaelSimons** [comment]
[Triage] This should be fixed with https://github.com/dotnet/source-build/issues/3170.

**Comment by MichaelSimons** [comment]
Propose closing as won't fix.  If you don't build with the repo's feeds prebuilt investigation scenarios can be difficult because you end up failing on the first failure.  We are already removing feeds in offline builds so this doesn't add additional assurance.
