### ISSUE TITLE
Capture smoke-test-prereqs for all architectures in CI

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2848]
This is necessary for distro maintainers to run the smoke-tests.

Question:  Is a single tarball necessary?  Would arch specific tarballs suffice?

**Comment by omajid** [comment]
> Question: Is a single tarball necessary? Would arch specific tarballs suffice?

I wouldn't matter to me: I extract all tarballs (3.1 vs 5.0 vs 6.0) to a single location before using them anyway, and I can extract `arm64` vs `x64` the same way.

**Comment by MichaelSimons** [comment]
[Triage] We should do the minimal amount of work (MVP).  This involved adding the architecture into the name to differentiate the artifacts and then update the release checklist.
