### ISSUE TITLE
Rebuilding same sources produces different package versions

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2852]
I built the 6.0.103 release a few weeks ago and got:

dotnet/sdk/6.0.103/DotnetTools/dotnet-user-secrets/6.0.3-servicing.22154.1/tools/net6.0/any/assets/SecretManager.targets

I rebuilt it last night and got a different build of dotnet-user-secrets:

dotnet/sdk/6.0.103/DotnetTools/dotnet-user-secrets/6.0.3-servicing.22160.1/tools/net6.0/any/assets/SecretManager.targets

"22154.1" vs "22160.1"

This seems like a bug? Shouldn't rebuilding the same set of source code produce the same version of dotnet-user-secerts?

**Comment by MichaelSimons** [comment]
[Triage] We should validate this is still and issue for 8.0/VMR

**Comment by omajid** [comment]
I built .NET 8 Preview 4 twice, once last week and once today. The file name diff is empty:

```
$ diff -u <(tar tf dotnet-sdk-8.0.100-preview.4.23260.1-fedora.38-x64-2023-06-08.tar.gz | sort -u) <(tar tf dotnet-sdk-8.0.100-preview.4.23260.1-fedora.38-x64-2023-06-12.tar.gz | sort -u) 
$
```

Both contain `./sdk/8.0.100-preview.4.23260.1/DotnetTools/dotnet-user-secrets/8.0.0-preview.4.23260.4/`. So this doesn't seem to affect the VMR anymore.

**Comment by MichaelSimons** [comment]
[Triage] Closing as this no longer reproduces in the VMR.
