### ISSUE TITLE
Establish a house Markdown style

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2855]
Comparing the before-and-after of https://github.com/dotnet/source-build/pull/2726/commits/d021e413893ef6a333b4b090898372f98533f6af, I believe the former is more readable in a significant number of places.  We should decide which Markdown rules to follow and which to ignore as passable-by-GitHub (e.g. using 1. 1. 1. in numbered lists instead of 1. 2. 3. and unnatural line-breaking just for hanging indents).  Does Microsoft have this already?

Blocks https://github.com/dotnet/source-build/issues/2854.

**Comment by MichaelSimons** [comment]
[Triage] A checked in linter config file feels like the approach we should take.  The initial PR can be used to flush out the rules everyone can agree on.
