### ISSUE TITLE
CoreFx is being built twice with the second being built as portable

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#286]
Per @weshaggard:

> The second build is intended to build NETStandard.Library.NETframework support package that the SDK consumes.
For the second leg we don't actually need to do the native build at all.
There are two fixes that come to mind. First we call build-managed.sh directly for the netframework leg. Or we pass in portable=false for that leg to at least let the native build happen the same way.

The second build being native-portable removes direct linking to libs.

/cc @omajid

**Comment by omajid** [comment]
cc @aslicerh

**Comment by omajid** [comment]
In my quick tests, this works:

    diff -ruN dotnet/targets/corefx.targets dotnet/targets/corefx.targets
    --- dotnet/targets/corefx.targets   2017-10-25 20:40:18.000000000 -0400
    +++ dotnet/targets/corefx.targets   2017-11-10 12:39:18.045215772 -0500
    @@ -16,7 +16,7 @@
    
       <Target Name="BuildNetStandardLibraryNetFramework"
               BeforeTargets="Package">
    -    <Exec Command="$(ProjectDirectory)/build$(ShellExtension) -$(Configuration) -Framework=netfx -OSGroup=Windows    _NT -- /p:ILLinkTrimAssembly=false"
    +    <Exec Command="$(ProjectDirectory)/build$(ShellExtension) -$(Configuration) -Framework=netfx -OSGroup=Windows    _NT -portable=false -- /p:ILLinkTrimAssembly=false"
               WorkingDirectory="$(ProjectDirectory)"
               EnvironmentVariables="@(EnvironmentVariables)" />
       </Target>

The build log then contains:

    /builddir/build/BUILD/dotnet/src/corefx/build.sh -Release -Framework=netfx -OSGroup=Windows_NT -portable=false -- /p:ILLinkTrimAssembly=false
    Tools are already initialized
    Running: /builddir/build/BUILD/dotnet/src/corefx/src/Native/build-native.sh  --TargetGroup=netfx --OSGroup=Windows_NT  x64  Release  Linux  --numproc 32  false  toolSetDir=c:\tools\clr /p:ILLinkTrimAssembly=false
    /builddir/build/BUILD/dotnet/src/corefx/src/Native/build-native.sh: line 369: lsb_release: command not found
    Setting up directories for build
    Checking pre-requisites...
    Commencing build of corefx native components for Linux.x64.Release
    Invoking cmake with arguments: "/builddir/build/BUILD/dotnet/src/corefx/src/Native/Unix" RELEASE  -DFEATURE_DISTRO_AGNOSTIC_SSL=0 -DCMAKE_STATIC_LIB_LINK=0

This is the second invocation, and since the configuration is identical to the first invocation, nothing is rebuilt via cmake.

**Comment by karajas** [comment]
I approve of setting portableBuilds=false. Do we need to prevent the second invocation?

**Comment by weshaggard** [comment]
Thansk @omajid 

>/builddir/build/BUILD/dotnet/src/corefx/src/Native/build-native.sh: line 369: lsb_release: command not found

Is that error always there and ignored?

**Comment by omajid** [comment]
> Is that error always there and ignored?

Hm. This is really the first time I have noticed this error. But the way we build code in the Fedora buildsystem, we always start with a fresh "system", if you will, so yeah, this has always been missing.

**Comment by weshaggard** [comment]
That will eventually go away as we are moving our branches to 3.9 for everything so I guess as long as it isn't blocking anything we can safely ignore it.

**Comment by dseefeld** [comment]
@crummel Please fix this for 2.0.4

**Comment by omajid** [comment]
https://github.com/dotnet/source-build/pull/302 fixes this, hopefully.

**Comment by dseefeld** [comment]
It looks like this has been fixed and ported to all required branches.
