### ISSUE TITLE
Cleanup top level tarball folders

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2867]
There are too many top level folders in the tarball.  The # and names hurt the approachability of the tarball.

/ArcadeOverrides - should be removed - https://github.com/dotnet/source-build/issues/2295
/scripts - Proposed removing in https://github.com/dotnet/installer/pull/13843
/keys - Move under eng.
/Tools vs tools-local - Why do we need two tools folders?  Can these be combined and moved under eng?
/repos - The name of this is a bit confusing because it could lead the consumer to think this is where the repo source lives.  This should have a more meaningful name.  I question if this should be a top level folder.  Would it make sense to move under eng?
/packages - This is confusing because it doesn't contain any of the resulting packages rather it is a collection of packages used by the build.  This should have a more descriptive name.  Would it make sense to move this under artifacts?

**Comment by omajid** [comment]
`/repos`, I think, is the odd one out. That's one of the few things I sometimes end up modifying as part of distro builds. There's some value to it being a top-level visible directory too.

What do you think about moving the contents of repos into `/src`?

**Comment by MichaelSimons** [comment]
> `/repos`, I think, is the odd one out. That's one of the few things I sometimes end up modifying as part of distro builds. There's some value to it being a top-level visible directory too.
> 
> What do you think about moving the contents of repos into `/src`?

Thanks for the input.  I can live with it at the root of the repo if it had a more descriptive name that helped differentiate it between `/src`.  `repo-projects`  or even `projects` would be more meaningful to me.  Putting it in `/src` would make it the odd one out there IMO.

**Comment by crummel** [comment]
Originally, `Tools` was the SDK, Arcade, anything else we needed to bootstrap and `tools-local` were source-build-specific things built in the source-build.  I don't know that separating them has huge value now that most consumers will supply their own bootstrap SDK and previously-source-built packages.  I could also see combining `repos` and `tools-local` into a `local-src` or similar to separate source-build itself vs contributing-repo-sources.  Or `/src/source-build` (`/src/orchestration`?  we used that in 1.x for a bit) in addition to `/src/sdk` etc.

I guess really the distinction to me seems to be:
- repo sources
- source-build sources itself
- stuff to bootstrap source-build

So spitballing a completely new organization could be:
- All the /src/repos/<repo> - moved from /src/<repo> so we can retain the different dir.props and dir.targets for contributing repos vs our code
- /src/source-build/tools - tools-local
- /src/source-build/build - /repos
- src/source-build/... - anything else we end up needing
- /prereqs - git-info, toolset, keys, Tools.  prep.sh puts the bootstrap SDK, PSB, and SBRP tarballs here.  we look for smoke-test-prereqs here.
- /eng - as required
- /test - remains as is
- /artifacts - should go away for the shipped tarball (unless empty for convenience)
- /packages - still used for extracted package tarballs but not shipped unless empty for convenience

**Comment by MichaelSimons** [comment]
[Triage] Discussing this in triage, the following proposal was formulated:

/ artifacts - contains all build output
/ eng
    / common - common arcade
    / tools - source build tasks and tools - this is the existing tools-local directory
/ prereqs - requirements necessary to build the tarball
    / git-info
    / keys
    / packages
    / tools - source-built tools - this is the existing Tools directory
/ src - repo source
/ test - scenario tests

The one folder that still has varying opinions is the current `/repos`.  Everyone seems to agree it should be renamed to better indicate is contains the repo projects. There are three options on the table.

/ eng / repo-projects
/ repo-projects
/ src / repo-projects

**Comment by mmitche** [comment]
What's the purpose of the folder?

**Comment by MichaelSimons** [comment]
> What's the purpose of the folder?

It contains a project for each product repo that is part of source-build.  The projects encapsulate the logic to invoke the product build.  Most of the logic is defined shared props/targets but some repos require varying degrees of specialization.

**Comment by mmitche** [comment]
Would you expect this to go away in the "one true source build land"?

**Comment by MichaelSimons** [comment]
Discussing this with @crummel, we have come up with the following proposal.  One of the primary changes it includes is moving all directories that are modified by the build into artifacts.

```
/ artifacts - contains all build output
  / packages - existing top-level packages folder; archiveArtrifacts.txt is replaced with content from eng/versions.props
  / source-build-sdks - this existing Tools directory
/ eng
   / common - common arcade
   / tools - source build tasks and tools - this is the existing tools-local directory
/ prereqs - requirements necessary to build the tarball
   / git-info - existing top-level git-info folder
   / keys - existing top-level keys folder
/ repo-projects - renames repos
/ src - repo source
/ test - scenario tests
```

**Comment by premun** [comment]
> What is the recommended process to follow in order to make the suggested change to the git-info folder?

1. Change https://github.com/dotnet/arcade-services/blob/4b97ba07fa0b7cbda645aa94f32099c4e3ef0710/src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs#L54 to `prereqs/git-info`
2. Bump DarcLib in installer
3. Let VMR sync
4. Remove `/git-info` manually in the VMR

**Comment by MichaelSimons** [comment]
@premun - the git-info renaming will also require changes to the source-build infra.  Those will have to be made in the same PR where the DarcLib flows in.  I will prepare those changes and coordinate w/you.

**Comment by premun** [comment]
Alright. I don't expect problems as essentially the `git-info` files are just a dump during the VMR sync, a simple XML projection of the `source-manifest.json` that is not ever read again by the VMR tooling.

**Comment by MichaelSimons** [comment]
> We should also probably move the the directories in installer.

@premun - I agree.  FYI there is a readme.md at src/SourceBuild that should be preserved at src/VirtualMonoRepo.  The readme needs some updating.  That can be done with a follow-up commit.  Doing this next week sounds great while there is a lull in activity as many will be on holiday break.

**Comment by premun** [comment]
Yeah, I imagine we can put there the instructions around `vmr-sync.sh`

**Comment by premun** [comment]
@MichaelSimons feel free to re-assign this to me and I will take care of that

**Comment by MichaelSimons** [comment]
> @MichaelSimons feel free to re-assign this to me and I will take care of that

I logged a separate issue for this because it is not really part of this issue which is just about the root tarball/VMR folder. 
 https://github.com/dotnet/source-build/issues/3184

**Comment by premun** [comment]
@MichaelSimons should we remove https://github.com/dotnet/dotnet/blob/main/packages/archive/archiveArtifacts.txt?

**Comment by MichaelSimons** [comment]
> @MichaelSimons should we remove https://github.com/dotnet/dotnet/blob/main/packages/archive/archiveArtifacts.txt?

I will do that once https://github.com/dotnet/installer/pull/15140 is completed.  The entire packages directory will be removed.

**Comment by MichaelSimons** [comment]
Closing as completed.  Thanks @premun for your help on this.  Overall this was a nice improvement.
