### ISSUE TITLE
Add support for repo level source-build support for NuGet package source mappings

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2869]
NuGet package source mappings are a recent addition.  Support was added to handle them within the tarball build under https://github.com/dotnet/source-build/issues/2752.  The repo level source-builds also need support in order to pickup the packages from the source-build intermediate source.

**Comment by MichaelSimons** [comment]
@oleksandr-didyk, can you confirm this was resolved with https://github.com/dotnet/arcade/pull/12809?

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk, can you confirm this was resolved with [dotnet/arcade#12809](https://github.com/dotnet/arcade/pull/12809)?

Yes, it is + is working for `format` as far as I'm aware. Closing
