### ISSUE TITLE
[SBRP] Remove obsolete packages from source-build-reference-packages

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2871]
Known dead-ended packages:
- System.Memory
- Microsoft.Bcl.HashCode

More to come.

**Comment by MichaelSimons** [comment]
[Triage] These should get cleaned up when we cleanup the unreferenced SBRP packages in 7.0.  If not, that is an indicator they are being referenced which probably means something is broken.

**Comment by MichaelSimons** [comment]
> for our education, how did you find that these packages are not needed anymore? Is the final tarball necessary for that? Also, do we need to introduce some process to periodically prune the source-build-reference-packages of obsolete packages?

@tkapin - see https://github.com/dotnet/source-build/issues/2357 - it is an issue for automating the process and captures the steps taken to identify unused packages.

**Comment by MichaelSimons** [comment]
Turns out these packages do need to remain as they are required to build the product.
