### ISSUE TITLE
Sort out issues with building Microsoft.FSharp.Compiler

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2873]
FSharp refactored how Microsoft.FSharp.Compiler get built in https://github.com/dotnet/fsharp/pull/12628.  There are two issues that need fixing

1. Microsoft.FSharp.Compiler no longer is included in the main repo's solution which is what source-build builds.
    1. Solution:  Add Microsoft.FSharp.Compiler.sln to the list of project built in source-build
3. The Microsoft.FSharp.Compiler.nuspec changed and now has a dependency (e.g. paths within the nuspec) on `UsingToolNuGetRepack` running.  NuGet repack is disabled for source-build and the infrastructure is excluded.
    1. Solution 1:  Add support for `UsingToolNuGetRepack` in source-build.  This will make source-build inline with the product build.  That being said there don't appear to be reasons for needing repack in source-build.
    2. Solution 2:  Decouple the nuspec from `UsingToolNuGetRepack` and instead pass in path properties from the csproj where conditional logic can be utilized to correct determine the paths based on if repack was called.

**Comment by MichaelSimons** [comment]
[Triage] Assigning to logan to investigate the repack part of this.

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/fsharp/pull/13239
