### ISSUE TITLE
Update and canonicalize source-build champions list

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2881]
It's been a while since we've updated the source-build champions list and there are a couple versions floating around.  We should update this for 7.0.

**Comment by MichaelSimons** [comment]
[Triage] With the increased importance of source-build, the champions concept has not been utilizes in the past two releases now.  CODEOWNERS is the preferred contact mechanism as it is not repo specific.  Any board communication or escalation should be utilizing tactics.
