### ISSUE TITLE
Include machine-readable info in markdown comment in release announcement post

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2888]
We should add some parseable data in a markdown comment in the automated source-build release announcement discussion post, so that distro maintainers can trigger automation when the announcement goes out for new releases. The data should include the git tag to pull from the installer repo, and potentially a github.com URL directly to the tag.

See https://github.com/dotnet/source-build/issues/1836#issuecomment-1138806925

**Comment by lbussell** [comment]
@dotnet/distro-maintainers would this be valuable for querying info about releases? What info would be needed? I could easily include things like:

- dotnet/installer release tag/sha
- SDK version
- Runtime version
- Release channel (6.0)

I was thinking of using json inside of a comment in the announcement discussion. Would a different format be better?

**Comment by omajid** [comment]
For me, those 4 pieces of info would be sufficient.
