### ISSUE TITLE
Investigate removing use of /p:SuppressTfmSupportBuildWarnings=true in Roslyn

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2889]
As part of updating the previous source-build artifacts to a 7.0 version, a number of unsupported TFM errors occurred because of consuming the latest 7.0 assembly versions of various pacakges.

```
error : System.Text.Encoding.CodePages doesn't support netcoreapp3.1. Consider updating your TargetFramework to net6.0 or later.
```

Using a strategy of pinning these versions so as to not use the latest and instead utilize reference packages leads to a large number of packages including Microsoft.CodeAnalysis.  The SBRP tooling does not work to gen this assembly.  As a temporary workaround to unblock work, these warnings/errors were disabled with `/p:SuppressTfmSupportBuildWarnings=true`.

A deeper investigation is needed in how this issue should be resolved for 7.0

**Comment by MichaelSimons** [comment]
[Triage] The preferred solution is to have SBRP tooling that supported the Microsoft.CodeAnalysis assemblies and then we simply add ref packs and remove the `SuppressTfmSupportBuildWarnings` flag usage.

**Comment by ViktorHofer** [comment]
@MichaelSimons the `SuppressTfmSupportBuildWarnings` setting shouldn't be used inside our stack. It was added for customers as a workaround who wanted to reference newest packages on unsupported .NETCoreApp runtimes.

For .NET 8, that flag indicates that we are building an out-of-support netcoreapp2.x, netcoreapp3.x or net5.0 component that then references a 7.0.x or 8.0.0 package.
