### ISSUE TITLE
Source-build release pipeline pull request deletes entire Versions.props file

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2896]
There is an issue somewhere in this code:
https://github.com/dotnet/source-build/blob/dd7ff5db09b2daa541b2059b1ca6f2c8b6144242/eng/submit-source-build-release-pr.sh#L136-L138

which completely deletes eng/Versions.props as seen here:
https://github.com/dotnet/installer/pull/13978/commits/c58a4510b43ed55f385da34bf11bd5cba1a593a3

It should only update the private source-built artifacts version number.

**Comment by omajid** [comment]
My guess is that both the commands `cat` and `tee` are running in parallel because of the pipe and `tee` empties it before `cat` can read it.

Maybe we can use `sed -i $versions_props_path $regex; cat $versions_props_path`?
