### ISSUE TITLE
Remove unnecessary xml doc from SBRP targeting packs

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2902]
Any of the SBRP targeting packs that do not ship with the SDK do not require the xml doc files.  The xml doc files are ~408 MB (uncompressed) in size.  The only targeting pack that I believe ships with the SDK is NetStandard.Library.Ref/2.1.0

**Comment by oleksandr-didyk** [comment]
**Basic rundown of current state**:
  - existing target packs were generated by internal tooling that does not differentiate between assets within the package and retrieves everything
  - `.xml` docs are part of the copied assets and are used for SDK-bound features like InteliSense; without the SDK the xml docs are useless and bloat the tarbal size
  - usage of the target pack generation tooling in the future is not expected

**Proposed solution**: manually (or with the help of one-off tooling) remove the `.xml` docs from target packs without affecting other `.xml` assets; no extension of the internal tooling is needed and the tooling itself should be considered obsolete
