### ISSUE TITLE
SourceLink RepositoryUrls are incorrect in release/6.0 and release/7.0

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2903]
These end up being local file paths in some cases - these should always be the GitHub paths.

**Comment by omajid** [comment]
This also a UX impact for users using a source-built SDK from a Linux distribution. If there are pdb files present, VSCode will load them up, then try and use the invalid RepositoryUrls (which point to non-existant local paths), which then results in hundreds of errors being shown to users.

**Comment by richlander** [comment]
@tmat

**Comment by MichaelSimons** [comment]
[Triage] @NikolaMilosavljevic, was this issue addressed by your recent SourceLink changes?  If so please close.

**Comment by NikolaMilosavljevic** [comment]
> [Triage] @NikolaMilosavljevic, was this issue addressed by your recent SourceLink changes? If so please close.

This was resolved in 7.0, but was not backported to 6.0 - should it be? I could create a new issue for backporting to 6.0.

**Comment by MichaelSimons** [comment]
Hearing no strong feedback to get this fixed prior to now is an indicator to me that it doesn't meet the criteria to backport.  If source-build partners feel otherwise please let us know.  Closing.
