### ISSUE TITLE
.NET 8: Source build improvements

### ISSUE THREAD

**Issue by richlander** [dotnet/source-build#2911]
The following improvements should be considered for .NET 8.

- #2956
- #2901 
- #2925
- #2926
- #2932
- https://github.com/dotnet/runtime/issues/71287
- https://github.com/dotnet/source-build/issues/2974
- https://github.com/dotnet/source-build/issues/2975
- https://github.com/dotnet/source-build/issues/2979
- https://github.com/dotnet/source-build/issues/2983
- https://github.com/dotnet/source-build/issues/3015
- https://github.com/dotnet/source-build/issues/3014
- https://github.com/dotnet/source-build/issues/3013
- https://github.com/dotnet/source-build/issues/2980
- https://github.com/dotnet/source-build/issues/3033
- https://github.com/dotnet/source-build/issues/3034

**Comment by mmitche** [comment]
@richlander Any objection to me triaging away items here that are definitely not going to be done in .NET 8? E.g. shipping source build as the official build?

**Comment by richlander** [comment]
Right. Sounds good. Or move to .NET 9.

**Comment by mmitche** [comment]
Added https://github.com/dotnet/source-build/issues/2979

**Comment by mmitche** [comment]
Added https://github.com/dotnet/source-build/issues/2983

**Comment by MichaelSimons** [comment]
Closing as .NET 8.0 work has been completed.  A few items were pushed to .NET 9.0
