### ISSUE TITLE
 [v6.0.301] build.sh : when cloning repo nuget-client "fatal : remote error : upload-pack: not our ref a8942f45835ba527cedacc02f7a75468f7a7b4bd"

### ISSUE THREAD

**Issue by TruckDynasty** [dotnet/source-build#2913]
Running into an issue while trying to build dotnet v6.0.301 from source.  The issue looks a lot like one that just got closed (#2912)

The ref is different though:
a8942f45835ba527cedacc02f7a75468f7a7b4bd

If it's any help tracking down the problem, I've previously had success building from the 6.0.103-source branch.  The machine is also an arm64 platform if that makes any difference

**Comment by TruckDynasty** [comment]
v6.0.300 worked fine, though

**Comment by MichaelSimons** [comment]
The 6.0.3xx channel is not supported by source-build per the [source-build support policy](https://github.com/dotnet/source-build/#support). Only 6.0.1xx is supported by source-build.

**Comment by TruckDynasty** [comment]
Guess that explains why I was able to build 6.0.103 from source lol!  Thanks for your time

**Comment by MichaelSimons** [comment]
[Triage] Closing as 6.0.3xx channel is not supported by source-build.  That being said, the underlying issue was fixed in https://github.com/dotnet/sdk/pull/26133 and will get picked up in the July servicing release.
