### ISSUE TITLE
.NET 8: Enable source-build to run from a git repo

### ISSUE THREAD

**Issue by richlander** [dotnet/source-build#2925]
Today, source-build assumes a certain layout and environment. We want to move to a git VMR (#2924) layout as the primary way for anyone (including Microsoft) to officially consume .NET source and build it. We need to update source-build to work within that layout. This likely assumes a lot.

It should be straightforward to do the following:

- Build the .NET SDK (AKA the entire product), for a specific OS+architecture (AKA a RID).
- Build just part of the repo, like ASP.NET Core or the .NET Runtime, for a specific OS+architecture.
- Build, make a small change, and then build again (the same way) but incrementally.
- Build the product and then immediately transition to running what you've built.
- Debug why the build failed or the product crashed.
- Upgrade the build to newer dependencies, including the toolset.
- Build .NET per modern secure supply chain practices (SBOM and related topics).
- Easily root-cause which change came in (source bombed from an atomic repo like dotnet/runtime) during the development phase.
- Easily jump between patches (8.0.0, 8.0.1) to root cause when/where a regression came in, for servicing.

The last two relate somewhat more to VMR mechanics.

Note: We may provide an initial version of this experience for .NET 7. It's likely we won't finish it during that timeframe.

**Comment by MichaelSimons** [comment]
This work has been completedvia the creation of the VMR - https://github.com/dotnet/dotnet
