### ISSUE TITLE
.NET 8: Establish downstream / upstream guidance

### ISSUE THREAD

**Issue by richlander** [dotnet/source-build#2926]
[Upstream](https://www.redhat.com/en/blog/what-open-source-upstream) is an established concept within open source. To a large degree, the .NET project has been operating in alignment with the upstream model. However, very little has ever been written down or communicated about that. We should fix that. The introduction of the Virtual Mono Repo (VMR; #2924) is the perfect opportunity for that.

There are a few obvious aspects of that:

- Better clarity on the changes that we'll accept, particularly that won't be included in Microsoft-provided builds.
- Better separation between Microsoft and community builds ([example](https://github.com/dotnet/sdk/issues/24474)).
- Make it much easier for any party to build .NET SDK w/o a significant upfront investment. This includes making it easier to create a short- or long-term fork.
- Removing unnecessary product friction like [RIDs](https://github.com/dotnet/runtime/issues/71285).
- Support model/group for distro-maintainers.
- Publicly documented model for CVE handling and pre-disclosure.

**Comment by MichaelSimons** [comment]
[Triage] @richlander, @mmitche - Aside from creating the VMR has any traction been made on this?  Is the remaining work in scop for .NET 8.0 or .NET 9.0?

**Comment by mmitche** [comment]
I am re-scoping this issue into three issues:
- Infrastructure changes that are moving to .NET 9:
  ```
  - Better separation between Microsoft and community builds (https://github.com/dotnet/sdk/issues/24474).
  - Make it much easier for any party to build .NET SDK w/o a significant upfront investment. This includes making it easier to 
  create a short- or long-term fork.
  ```
- Infrastructural changes around CVE disclosure that should be completed in the .NET 8 timeframe.
- "soft" changes that should be completed .NET 8 around documentation.

The RID graph removal has been completed.
