### ISSUE TITLE
Servicing VMR doesn't work without root gitdir

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2927]
Reported by @omajid: git-archiving the servicing VMR and trying to build from that fails.  This appears to be because the source-build build expects to have a gitdir available for sourcelink purposes.  Since none of this code is shipping we should be able to just disable sourcelink in the root tools.

**Comment by omajid** [comment]
FWIW, I am not tied to `git archive`. Fedora/RHEL/CentOS's `rpmbuild` just needs a source tarball to work with. If there was a script or an official way to generate a source tarball that kept some needed git metadata, I would be totally okay with using that.

**Comment by omajid** [comment]
> Since none of this code is shipping [...]

Can you elaborate on this? We do want to ship the results. 

> we should be able to just disable sourcelink in the root tools

Is there a way to tell sourcelink to point to the appropriate git repositories of the component projects?

**Comment by crummel** [comment]
This would just be disabling it for the source-build tooling itself, like [MS.DN.SourceBulid.Tasks.XPlat](https://github.com/dotnet/installer/tree/main/src/SourceBuild/tarball/content/tools-local/tasks) - none of that code should ship.  Binaries from each individual repo should still pick up their source-link metadata as usual because we set up the [minimal sourcelink metadata](https://github.com/dotnet/sourcelink/blob/main/docs/README.md#Minimal_git_repository_metadata).

**Comment by MichaelSimons** [comment]
[Triage] @omajid, is this a blocker for you?  Would RedHat utilize the VMR if this were fixed?  This information will help us prioritize this work.

**Comment by MichaelSimons** [comment]
[Triage] This is not a blocker for RedHat as long as we continue to produce the tarball.  Once we transition to only having the VMR, this will need to be addressed.

**Comment by MichaelSimons** [comment]
> This has been addressed by the `pack-sources.sh` script in the VMR. We are also providing a buildable source tarball attached on the GitHub release. Can we close this?

I still see this as an issue.  That being said https://github.com/dotnet/source-build/issues/3265 lays out the plan to achieve the desired behavior.

**Comment by MichaelSimons** [comment]
This was resolved by https://github.com/dotnet/source-build/issues/3366.  Building outside of a git context works now but does require the user to supply some options on where to retrieve the required sourcelink info from.
