### ISSUE TITLE
WebScenarioTests_BlazorWasm_CSharp test is failing in main

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2946]
Steps to reproduce:

Using a source-built .NET 7 SDK (I used the one from [this build](https://dev.azure.com/dnceng/public/_build/results?buildId=1890856&view=artifacts&pathAsName=false&type=publishedArtifacts)):

1. Run `dotnet new blazorwasm --name WebScenarioTests_BlazorWasm_CSharp --output WebScenarioTests_BlazorWasm_CSharp --language "C#"`
2. Add a NuGet.config file with the following content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-public" value="[https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json"](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json%22) />
    <add key="dotnet7" value="[https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json"](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json%22) />
    <add key="dotnet7-transport" value="[https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7-transport/nuget/v3/index.json"](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7-transport/nuget/v3/index.json%22) />
  </packageSources>
</configuration>
```

3. Run `dotnet build`
4. The expected behaviour is the project should build cleanly, but we observe the following error:

```
/data/WebScenarioTests_BlazorWasm_CSharp_MS/Program.cs(3,7): error CS0246: The type or namespace name 'WebScenarioTests_BlazorWasm_CSharp' could not be found (are you missing a using directive or an assembly reference?) [/data/WebScenarioTests_BlazorWasm_CSharp_MS/WebScenarioTests_BlazorWasm_CSharp.csproj]
```

I cannot reproduce this using the official build of the .NET 7 SDK linked in the https://github.com/dotnet/installer README file.

**Comment by lbussell** [comment]
@jaredpar do you know anyone who could help us diagnose this?

**Comment by jaredpar** [comment]
My starting point would be to get a binary log file for each build (just add `/bl` to the `dotnet build` command line). Then compare the differences in arguments to the `<Csc>` task where the error is happening. If you have both binlogs I'm happy to help take a quick look.

**Comment by lbussell** [comment]
Here are the [binlogs.tar.gz](https://github.com/dotnet/source-build/files/9155053/binlogs.tar.gz).

Also I looked at the `Csc` tasks and ran them through a comparison tool. Controlling for the executable paths and ignoring the version number differences, It looks like the official microsoft build has a couple extra `/analyzers:...` arguments. See for yourself:

[csc_failure.txt](https://github.com/dotnet/source-build/files/9155054/csc_failure.txt)
[csc_success.txt](https://github.com/dotnet/source-build/files/9155055/csc_success.txt)

(7.0.100-rc.1.22370.6 is Microsoft version, 7.0.100-rc.1.22369.1 is Source Build version)

**Comment by jaredpar** [comment]
Thanks. I did a quick formatting on these files, diffed them and this is the result 

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/146967/180101462-3faaafff-938a-4a21-8f25-d90ed793e03a.png">

It appears none of the Razor code generators are being passed through from the .NET SDK to the compiler in the source build version of the tools. Analyzers are though which is surprising. Can you check and see if they're installed on the source build instance?

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - Is this something you can investigate?

**Comment by MichaelSimons** [comment]
Re-opening as there was a test that was disabled as a result of this regression that needs to be re-enabled.
