### ISSUE TITLE
Add SBRP support for meta packages

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2949]
If you try to generated a reference package for `System.Composition,1.0.31` you will notice no reference package source is created.  This is because this package is a meta-package.  It contains no source and only references other packages.  The SBRP generate tooling should be updated to support this scenario.

**Comment by ViktorHofer** [comment]
Such a package would now be defined as "test only package", right? If so, then I guess we can close this issue as SBRP now has a generator for such.
