### ISSUE TITLE
Building 'vstest in tarball' : a cp cannot stat line

### ISSUE THREAD

**Issue by mirespace** [dotnet/source-build#2957]
Hi everyone,

after building from source for Ubuntu 22.04 and in the next on-development release, I saw the following line in the buildlog about no file found when copying ( https://launchpadlibrarian.net/614648881/buildlog_ubuntu-kinetic-amd64.dotnet6_6.0.107-0ubuntu1_BUILDING.txt.gz ):

` cp: cannot stat '/<<PKGBUILDDIR>>/src/vstest/artifacts/source-build/self/package-cache/[microsoft.visualstudio.coverage.io/17.0.0-beta.21471.1/lib/netstandard2.0/**](http://microsoft.visualstudio.coverage.io/17.0.0-beta.21471.1/lib/netstandard2.0/**)': No such file or directory `

I discovered it appears since we're bootstrapping with our own debs at least... maybe is not important at all, but I want to share it with you for a double check in case it might affect dotnet behaviour in some sense.... although it seems to be Visual Studio Tests.

It doesn't break the build, the packages have installed fine too and `dotnet --info` is working, but I was curious about it... so I checked Fedoras' log to see if the same was happening there ( https://kojipkgs.fedoraproject.org//packages/dotnet6.0/6.0.107/2.fc37/data/logs/x86_64/build.log ) ... and it's not.

In fact, the `cp` error appears when `Building 'vstest in tarball'` stage, but it seems on Fedora this is not being done (nothing except the call to build appears) because in Ubuntu logs I see a lot of things happening (the commented cp among others indeed).

The build was done with the following command:
```
VERBOSE=1 ./build.sh \
--with-sdk /<<PKGBUILDDIR>>/previously-built-dotnet \
    	-- \
    	/v:n \
    	/p:SkipPortableRuntimeBuild=true \
    	/p:LogVerbosity=n \
    	/p:MinimalConsoleLogOutput=false \
    	/p:ContinueOnPrebuiltBaselineError=true \

Detected '--': passing remaining parameters '/v:n /p:SkipPortableRuntimeBuild=true /p:LogVerbosity=n /p:MinimalConsoleLogOutput=false /p:ContinueOnPrebuiltBaselineError=true' as build.sh arguments.
Using custom bootstrap SDK from '/<<PKGBUILDDIR>>/previously-built-dotnet', version '6.0.106'
Found bootstrap SDK 6.0.106, bootstrap Arcade 6.0.0-beta.22261.7, bootstrap SourceLink 1.1.0-beta-21480-02
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
```
Any clues as to what might be going on here? Thanks in advance for your time in this.

**Comment by crummel** [comment]
Yeah, I'm not sure you should need the coverage.io packages.  I'll check this out in a Debian container and see if I can repro.  Thanks!

**Comment by MichaelSimons** [comment]
Closing in favor of tracking this issue with https://github.com/microsoft/vstest/issues/4068
