### ISSUE TITLE
Issue with Jab 0.8.1

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/source-build#2963]
CG recently detected the issue with `Jab.0.8.1` package introduced by source build.

See more info [here](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-templating/alert/7212695?typeId=6669620)

**Comment by MichaelSimons** [comment]
I submitted the missing license information.  It takes a little while for this information to flow.  I will monitor.

**Comment by MichaelSimons** [comment]
I verified the license information was process and this CG alert is no longer present.

**Comment by vlada-shubina** [comment]
@MichaelSimons now we have same issue with `Jab.0.8.4`, see https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-templating/alert/7238589?typeId=6669620

Should I create new issue for it? Thanks

**Comment by MichaelSimons** [comment]
I saw this yesterday and already submitted the missing license information for 0.8.4.  It will take a couple days to get processed.
