### ISSUE TITLE
Update diagnostics version

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2970]
The diagnostics version we are building w/source-build (5.0.0-preview.21506.1) is older and should be upgraded in order to remove this [patch](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/patches/diagnostics/0001-Pin-the-Microsoft.Extensions.Logging-version-so-that.patch) was backported but has never flowed in.

**Comment by NikolaMilosavljevic** [comment]
Fixed.
