### ISSUE TITLE
Remove roslyn Microsoft.CodeAnalysis.Common patch

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2971]
Patch: https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/patches/roslyn/0001-lift-version-of-Microsoft.CodeAnalysis.Common-depend.patch

Now that we have demonstrated the ability to generate Microsoft.CodeAnalysis.Common SBRP assemblies, SBRPs should be generated so that the afore mentioned patch can be removed.

**Comment by MichaelSimons** [comment]
https://github.com/dotnet/source-build-reference-packages/pull/416 will be an important reference while adding the required Microsoft.CodeAnalysis.Common assemblies to SBRP.

**Comment by NikolaMilosavljevic** [comment]
This is now fixed.
