### ISSUE TITLE
Remove aspnetcore submodule workaround patch

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2972]
Patch:  https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/patches/aspnetcore/0001-Revert-sourcelink-submodule-workaround.patch

This patch should be backported to aspnetcore.  An [attempt was made to backport this patch](https://github.com/dotnet/aspnetcore/pull/39324) at the beginning of 7.0 but there were issues and the changes were reverted.  This needs to be investigated so that the patch can be removed.

**Comment by NikolaMilosavljevic** [comment]
Will be fixed with: https://github.com/dotnet/installer/pull/14458
