### ISSUE TITLE
Unified Build Controls

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#2975]
### Description

Update the unified build control set to remove source-build specificity and enable Unified Build

### General Work
- [x] https://github.com/dotnet/source-build/issues/2974
- [x] #3932
- [x] #3937
- [x] #3938
- [x] #3939
- [x] #3940
- [x] #3941
- [x] #3942
- [x] #3943
- [x] #3944
- [x] #3945
- [x] #3946
- [x] #3947
- [x] #3961
- [x] #3948
- [x] #3949
- [x] #3950
- [x] #3951
- [x] #4008 
- [x] #4182

**T-Shirt Size: Large**

**Comment by mmitche** [comment]
Part of #2911

**Comment by mmitche** [comment]
Once aspnetcore goes in, this will be officially back in the "Blocked" column.

**Comment by mmitche** [comment]
Blocked on net8 arcade moves.

**Comment by ViktorHofer** [comment]
Time to celebrate, everything's done.
