### ISSUE TITLE
.NET 8: Enable VMR/source-build build validation on every PR

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#2983]
### Description

To improve the **stability** and **quality** of source-build, it is necessary to more regularly validate it. It is a peer of the official build, and we cannot ship without it green. As we get dependency updates, we need to be validating just like we validate our normal installer build.

There is an existing job that validates source-build tarball generation, but the source-build tarball build only runs if the source-build directories have changed (e.g. patches or infrastructure changing). This is largely because of the cost. The build of the tarball is long, 2-4 hours.

We need to do a couple things:
- [ ] Reduce the time cost of the source-build (VMR or tarball) build. This could be done by any number of methods. Anecdotally, the current tarball build executes in < 1 hour on a developer machine.
- [ ] Enable builds of the tarball on every PR

After the existing tarball generation goes away, it will replaced by the VMR update process. The proposed VMR update (as a result of the installer repo and/or dependency changes) should be built in a similar manner to the tarball.

**Comment by MichaelSimons** [comment]
This issue has been completed.  Installer PR validation will sync the VMR and run an online source-build.
