### ISSUE TITLE
FSharp assemblies are not reported as prebuilts yet get added to the prebuilts tarball

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2989]
Looking at a recent [CI build](https://dev.azure.com/dnceng/internal/_build/results?buildId=1938356&view=logs&j=87a4ea9e-995f-5db7-cd08-b96ecbe4e25a&t=f8cf185b-29d6-52a5-84b1-6edc34dd9fec) (internal Microsoft link), the following prebuilts are reported:

```
  /tarball/repos/Directory.Build.targets(811,5): warning : 7 new packages used not in baseline! See report at /tarball/artifacts/prebuilt-report/baseline-comparison.xml for more information. Package IDs are: [/tarball/repos/known-good.proj]
/tarball/repos/Directory.Build.targets(811,5): warning : Microsoft.AspNetCore.App.Ref.6.0.8 [/tarball/repos/known-good.proj]
/tarball/repos/Directory.Build.targets(811,5): warning : Microsoft.DotNet.Common.ItemTemplates.7.0.100-rc.1.22409.4 [/tarball/repos/known-good.proj]
/tarball/repos/Directory.Build.targets(811,5): warning : Microsoft.DotNet.Common.ProjectTemplates.7.0.7.0.100-rc.1.22409.4 [/tarball/repos/known-good.proj]
/tarball/repos/Directory.Build.targets(811,5): warning : Microsoft.NETCore.App.Host.linux-x64.6.0.8 [/tarball/repos/known-good.proj]
/tarball/repos/Directory.Build.targets(811,5): warning : Microsoft.NETCore.App.Ref.6.0.8 [/tarball/repos/known-good.proj]
/tarball/repos/Directory.Build.targets(811,5): warning : runtime.placeholder-rid.Microsoft.NETCore.Runtime.ObjWriter.1.0.0-alpha.1.22364.1 [/tarball/repos/known-good.proj]
```

If you look at the generated `Private.SourceBuilt.Prebuilts.7.0.100.x64.tar.gz`, you will find additional fsharp packages.

``` console
$ tar -tf artifacts/x64/Release/Private.SourceBuilt.Prebuilts.7.0.100.x64.tar.gz 
./
./FSharp.Compiler.Service.41.0.6-preview.22409.11.nupkg
./FSharp.Core.6.0.6-beta.22409.11.nupkg
./FSharp.Core.6.0.6.nupkg
./FSharp.Compiler.Service.41.0.6.nupkg
./microsoft.netcore.app.ref.6.0.8.nupkg
./microsoft.netcore.app.host.linux-x64.6.0.8.nupkg
./microsoft.aspnetcore.app.ref.6.0.8.nupkg
./runtime.linux-x64.microsoft.netcore.runtime.objwriter.1.0.0-alpha.1.22364.1.nupkg
```

Investigation should be done to see which is correct (either the report or the generated tarball) and then fix the other.

**Comment by crummel** [comment]
@KevinRansom I tested this offline and none of these F# packages are required to actually build the product.  Any idea where I should start looking for why they're being restored?

**Comment by crummel** [comment]
These packages are still in the online prebuilts but now with a 7.0 version number, so this wasn't just a 6.0 -> 7.0 transition problem.  The offline build also has the F# packages included in the prebuilt tarball but not the prebuilt report.  I'm still looking into how exactly this is happening, but we know that we can build offline without the F# packages so it's not a prebuilt leakage.

**Comment by crummel** [comment]
Things that I tried:
- Rearranging the build order - we thought that this might be runtime using the F# packages before they were built.
- Patching all F# projects to net7.
- Patching all F# projects to `<LangVersion>latest</LangVersion>`.
- Patching F# projects with these packages in assets.json to the new versions (build failure).
- Fiddling with F# PVP properties - tried environment variables and command-line variables.

**Comment by MichaelSimons** [comment]
@Crummel - Do you have an understanding what causes these to be included in the prebuilt tarball but not reported as prebuilts in the prebuilt report?

**Comment by crummel** [comment]
They are still being downloaded but because we have a source-built version the prebuilt report assumes that we will just upgrade it in PVP so they aren't "real" prebuilts - just a circular dependency that will be fixed.  The prebuilt tarball logic is simpler and just grabs everything in the NuGet cache that wasn't source-built.

**Comment by MichaelSimons** [comment]
Confirmed this is still an issue in 8.0
