### ISSUE TITLE
Change arm64 CI from Debian to Ubuntu

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2993]
Since we officially support Ubuntu 20.04 and 22.04 on arm64, and not Debian which we currently use, we should switch our arm64 CI from Debian to Ubuntu.

Related:

- https://github.com/dotnet/installer/pull/14321
- https://github.com/dotnet/source-build/issues/2813
- https://github.com/dotnet/source-build/issues/2992

**Comment by MichaelSimons** [comment]
@mthalman - Another good one to fix which I have assigned to you.
