### ISSUE TITLE
Update CI from Fedora 33 to Fedora 36

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2995]
Fedora 33 has been EOL for a while, so we should update to the latest version of Fedora.

Currently, this is blocked by an error: "no usable version of clang found" in runtime. If this is a product issue, we should file a corresponding issue in runtime.

**Comment by lbussell** [comment]
@omajid, Do you currently work around this? I see that there is this patch in Fedora, is it related? https://src.fedoraproject.org/rpms/dotnet6.0/blob/rawhide/f/runtime-arm64-lld-fix.patch

**Comment by omajid** [comment]
AFAIK, that patch was to pick up LLVM's linker. That only affected arm64 with non-4k page sizes.

**Comment by omajid** [comment]
I can't reproduce this. A fresh checkout of `main` in runtime starts building using clang for me. Is there a link to the failure log I can look at? Can you confirm clang is installed?

**Comment by lbussell** [comment]
I didn't double-check the image we used, I don't think it actually has clang in it: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/fedora/36/amd64/Dockerfile

I'll just update that then.

**Comment by omajid** [comment]
Maybe sync https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/fedora/36/amd64/Dockerfile with https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/fedora/34/amd64/Dockerfile? There's other things missing too (`clang`, `cmake`, `jq` jump out). Not sure if the `llvm-devel` and `lldb-devel` are still needed; AFAIK, they are only used by the native build of dotnet/diagnostics now.
