### ISSUE TITLE
Would be nice if Documentation also had some description on what is present in the source tarball or after a build.

### ISSUE THREAD

**Issue by tedneward** [dotnet/source-build#300]
Like, what have I got? How do I use it? Where does everything live? And so on.

**Comment by omajid** [comment]
This should be covered by https://github.com/dotnet/source-build/tree/release/3.1/Documentation#building and https://github.com/dotnet/source-build/blob/release/3.1/Documentation/packaging-installation.md.

Is there anything else that should be done?

**Comment by MichaelSimons** [comment]
[Triage] Closing per the documentation links provided earlier.
