### ISSUE TITLE
[Poison] SBRP assemblies are leaking into dotnet-watch and dotnet-format

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3000]
Logging this separately from https://github.com/dotnet/source-build/issues/2577 because I think it's likely they have a common cause.  It could be another instance of https://github.com/dotnet/source-build/issues/2583.

**Comment by NikolaMilosavljevic** [comment]
Not an issue anymore after https://github.com/dotnet/installer/pull/15347
