### ISSUE TITLE
dotnet format tests are failing in main

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3004]
[Failing CI build](https://dev.azure.com/dnceng/internal/_build/results?buildId=1954803) (internal Microsoft link)

```
System.InvalidOperationException : Failed to execute /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/.dotnet/dotnet format /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/projects-202208192259567698/FormatProject/FormatProject.csproj
Exit code: 3

Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.
```

This last passed CI on https://github.com/dotnet/installer/commit/319773e868fead7c3bedba92f894594d1d81ff59. There were a few commits after that before the next failing CI run on https://github.com/dotnet/installer/commit/d117d579c56308c490d40e0860b6c926c08d5ae3.

**Comment by MichaelSimons** [comment]
Underlying issue has been resolved, closing.

**Comment by badsyntax** [comment]
@MichaelSimons what was the underlying issue? how did you solve this?

**Comment by MichaelSimons** [comment]
I'm not sure why this was closed.  Trying this today I still see the issue in main and the source-build unit test is still disabled.  re-opening.

**Comment by MichaelSimons** [comment]
This seems related to https://github.com/dotnet/format/issues/1785

**Comment by MichaelSimons** [comment]
I tried running the dotnet format tests and it appears a ref assemblies is being loaded.  This needs to be addressed for .NET 8.0

```
     System.InvalidOperationException : Failed to execute /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet format /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202307311948161538/FormatProject/FormatProject.csproj
  Exit code: 1
  
  Unhandled exception: System.BadImageFormatException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies cannot be loaded for execution. (0x80131058)
  File name: 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
     at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
     at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
     at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
    Stack Trace:
       at Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ValidateExitCode(ValueTuple`3 result, Int32 expectedExitCode) in /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs:line 125
     at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetHelper.ExecuteCmd(String args, String workingDirectory, Action`1 processConfigCallback, Nullable`1 expectedExitCode, Int32 millisecondTimeout) in /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetHelper.cs:line 118
     at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetFormatTests.FormatProject() in /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetFormatTests.cs:line 34
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    Standard Output Messages:
   Executing: /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet new console --name FormatProject --output /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202307311948161538/FormatProject --language "C#" 
   Executing: /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet format /repos/dotnet2/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202307311948161538/FormatProject/FormatProject.csproj
  ```

**Comment by MichaelSimons** [comment]
Fixed with https://github.com/dotnet/installer/pull/17238

**Comment by mthalman** [comment]
The fix from https://github.com/dotnet/installer/pull/17238 didn't pass in the internal CI run. It's failing on the Alpine leg:

```
System.InvalidOperationException : Failed to execute /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet format /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202308231449174553/FormatProject/FormatProject.csproj
Exit code: 3


Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.
```

**Comment by NikolaMilosavljevic** [comment]
> The fix from [dotnet/installer#17238](https://github.com/dotnet/installer/pull/17238) didn't pass in the internal CI run. It's failing on the Alpine leg:
> 
> ```
> System.InvalidOperationException : Failed to execute /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet format /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202308231449174553/FormatProject/FormatProject.csproj
> Exit code: 3
> 
> 
> Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.
> ```

Well, this is odd. I'll test this locally to understand why it doesn't work on Alpine.

**Comment by NikolaMilosavljevic** [comment]
This seems like another issue with MSBuildLocator - on Alpine it's not finding hostfxr library which is used for discovery of SDK/MSBuild paths.

@mthalman @MichaelSimons should we condition this test to not run on Alpine?

**Comment by MichaelSimons** [comment]
> @mthalman @MichaelSimons should we condition this test to not run on Alpine?

Yes and link to a product issue.

**Comment by NikolaMilosavljevic** [comment]
> > @mthalman @MichaelSimons should we condition this test to not run on Alpine?
> 
> Yes and link to a product issue.

Where would the comment/link go - vmr yaml file (this is where we condition OmniSharp tests - https://github.com/dotnet/installer/blob/6fa2d3d9a6b9c445d396080845c375dc5b5480a4/eng/pipelines/templates/stages/vmr-build.yml#L85) or source file for dotnet-format tests?

**Comment by MichaelSimons** [comment]
I would say the build definition.  We should also have a tracking issue on our side that links to the product issue so that we re-enable this test.

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/installer/pull/17238 and conditioned the Alpine leg with https://github.com/dotnet/installer/pull/17247
