### ISSUE TITLE
[Proposal] .NET 8: Mandated `dotnet/` forks of external source-build dependencies

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3009]
## Context
To be able to build the product from source, we need to make sure all external dependencies are source-buildable as well. As of now, these dependencies are referenced from the product repositories in the form of git submodules.
Additionally to this, we use https://github.com/dotnet/source-build-externals as a proxy to verify that we can build these dependencies and to produce intermediate packages for them.

#### [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore)
- [github.com/google/googletest](https://github.com/google/googletest) \> `/src/submodules/googletest`
- [github.com/aspnet/MessagePack-CSharp.git](https://github.com/aspnet/MessagePack-CSharp.git) \> `/src/submodules/MessagePack-CSharp`
- [github.com/dotnet/spa-templates.git](https://github.com/dotnet/spa-templates.git) \> `/src/submodules/spa-templates`

#### [dotnet/linker](https://github.com/dotnet/linker)
- [github.com/mono/cecil.git](https://github.com/mono/cecil.git) \> `/external/cecil`

#### [NuGet/nuget-client](https://github.com/NuGet/nuget-client)
- [github.com/NuGet/FileSystem.git](https://github.com/NuGet/FileSystem.git) \> `/submodules/FileSystem`
- [github.com/aspnet/Common.git](https://github.com/aspnet/Common.git) \> `/submodules/Common`
- [github.com/NuGet/NuGet.Build.Localization.git](https://github.com/NuGet/NuGet.Build.Localization.git) \> `/submodules/NuGet.Build.Localization`

#### [dotnet/source-build-externals](https://github.com/dotnet/source-build-externals)
- [github.com/Microsoft/ApplicationInsights-dotnet](https://github.com/Microsoft/ApplicationInsights-dotnet) \> `/src/application-insights`
- [github.com/dotnet/cssparser](https://github.com/dotnet/cssparser) \> `/src/cssparser`
- [github.com/Humanizr/Humanizer](https://github.com/Humanizr/Humanizer) \> `/src/humanizer`
- [github.com/JamesNK/Newtonsoft.Json.git](https://github.com/JamesNK/Newtonsoft.Json.git) \> `/src/newtonsoft-json`
- [github.com/microsoft/MSBuildLocator](https://github.com/microsoft/MSBuildLocator) \> `/src/MSBuildLocator`
- [github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) \> `/src/azure-activedirectory-identitymodel-extensions-for-dotnet`
- [github.com/pakrym/jab](https://github.com/pakrym/jab) \> `/src/jab`

## Problems

There are several problems with the current setup that we need to address:

- **Servicing continuity**  
  Submodules are just references to commits in other repositories. If any of these commits or the repositories are removed, we won't be able to build/service the product anymore. This is a considerable risk.
- **VMR as the source for product build**  
  The current setup works for the tarball build where we fetch all the submodules, strip unnecessary/forbidden files and hand the tarball to a client. It, however, does not work for the case where we use the VMR as the source for the build. There we expect to give clients a SHA as a complete and final source which must not contain any of these artifacts.  
  For this scenario to work, we will need to strip the external remote repo somewhere in the pipeline so that when we fetch the referenced submodule, it is ready for building from source.
- **Bar for adding new dependencies**  
  The current state of things makes it easy for the client teams to pick up new dependencies. It is then difficult to maintain the level of quality we require for the rest of the product as new dependencies often have no guarantee of a secure supply chain. The responsibility then shifts onto the infrastructure team (and the [source-build-externals repo](https://github.com/dotnet/source-build-externals)). This approach might not be tenable long-term considering the fact we aim to bring more and more of dotnet into the source-build world (e.g. workloads).

## Proposed solution

Since we need to be in control of the longevity of the dependencies, **requiring a Microsoft-owned man-in-the-middle fork of all external dependencies** might be a solution that would deal with all of the problems at once. As a functional example, we already do this with https://github.com/mono/cecil.

The fork would give us a free hand in:
- Stripping files not needed (or even forbidden) in the source-build, e.g. binaries
- Applying custom patches needed for .NET without the need to flow them upstream
- Ensuring secure supply chain
- Deferring the maintenance onto whoever introduced the dependency

Overall this process seems to follow the OSS downstream/upstream model more natively. 

Furthermore, it is expected that the engineering team would provide:
- Documentation and tooling to make the forking process as straightforward as possible
- Infrastructure for verification of the contents of the repository/branch to make sure it complies with our client requirements (e.g. no binaries)
- Infrastructure to build intermediate packages from the forks

### Pros
- Business continuity would be granted.
- Ownership of forks would be clear, maintenance cost spread over the organization.
- Custom changes applied on top would not have to be flown back to upstream.
- Some operations such as custom patches that we apply today would not be necessary. The [source-build-externals repo](https://github.com/dotnet/source-build-externals)) might not be needed anymore.
- Higher cost of onboarding of a new dependency would make devs think twice.

### Cons
- Consuming updates from the upstream would require one extra step (pulling changes to the man-in-the-middle fork first) but this can be probably automated easily.
- Risk of explosion of the number of forks under the dotnet organization.
- Any OSS concerns with us having forks of everything?

**Comment by mmitche** [comment]
@MichaelSimons @crummel @richlander

**Comment by dougbu** [comment]
> Overall this process seems to follow the OSS downstream/upstream model more natively.

This does not seem true given the earlier "&hellip; without the need to flow them upstream" point. We should not be in the business of making positive changes to our forks without contributing back to the community. File removal seems fine but not that.

> [github.com/aspnet/MessagePack-CSharp.git](https://github.com/aspnet/MessagePack-CSharp.git) > /src/submodules/MessagePack-CSharp
> [github.com/dotnet/spa-templates.git](https://github.com/dotnet/spa-templates.git) > /src/submodules/spa-templates

The first of these is a fork already, of [neuecc/MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp). The second was split off from [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) and remains part of the dotnet/ organization. We shouldn't need to make further governance changes or add new forks for either.

----

More generally, the submodules in [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) are, with the slight exception of /src/submodules/spa-templates (which produces a template package e.g. <https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates.7.0>), **not** built independently. /src/submodules/MessagePack-CSharp/ code is compiled into Microsoft.AspNetCore.Components.Server.dll and /src/submodules/googletest/ code is compiled into some of our IIS test assemblies. How does this approach account for such use❔

**Comment by mmitche** [comment]
> > Overall this process seems to follow the OSS downstream/upstream model more natively.
> 
> This does not seem true given the earlier "… without the need to flow them upstream" point. We should not be in the business of making positive changes to our forks without contributing back to the community. File removal seems fine but not that.

I think that is more true to the upstream/downstream model. We're making our changes more transparent (in source, rather than in patch files), and can choose to upstream them. **However**, we may simply not be able to upstream them. Most of the changes are for the ability for these components to successfully build within the source-build ruleset, and on Microsoft infrastructure. They often do not make sense in the context of the users of the upstream repo. I agree that positive changes should go upstream, but there are cases when we need to integrate with our engineering systems that should only exist in the downstream.

These exist in patches today, and should not.

> The first of these is a fork already, of [neuecc/MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp). The second was split off from [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) and remains part of the dotnet/ organization. We shouldn't need to make further governance changes or add new forks for either.

Yep, these are good.



> More generally, the submodules in [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) are, with the slight exception of /src/submodules/spa-templates (which produces a template package e.g. https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates.7.0), **not** built independently. /src/submodules/MessagePack-CSharp/ code is compiled into Microsoft.AspNetCore.Components.Server.dll and /src/submodules/googletest/ code is compiled into some of our IIS test assemblies. How does this approach account for such use❔

I don't think this scenario is in conflict with what @premun is proposing. This is basically saying that where we have a submodule or external source-build dependency (these exist in aspnetcore, source-build-externals, etc.), the submodule remote should be a public downstream fork in the dotnet org, and that we should be checking in changes to comply with source-build requirements into those repos, rather than relying on applying patches located in the source-build/installer repos.

@omajid Does that sound good to you?

**Comment by omajid** [comment]
From an OSS perspective, forking shouldn't be a problem in itself. It can become much more problematic when there are code changes and different forks diverge. The maintenance of forks also becomes a problem and often takes up too much manpower. One thing to consider would be user perception: would the public see it as good community stewardship if dotnet is forking a ton of projects? I am tempted to think we should consider forking as an option of last-resort. 

Is it an option to upstream some changes to some Microsoft-owned repositories? For example https://github.com/aspnet/MessagePack-CSharp, https://github.com/mono/cecil, https://github.com/NuGet/FileSystem and https://github.com/NuGet/NuGet.Build.Localization seem like places where it might be possible to upstream changes? Perhaps some of them can be moved into the dotnet org too? I am also quite confused to see github.com/dotnet/cssparser in that list since it's, presumably, already in the dotnet org?

Maybe a meta-question: if the external repos really are first-class projects (eg, googletest) and the expected model of users (which would be .NET here) to consume the projects is not by copying sources, would it be worth it to make that an explicit build-time (or runtime) dependency of .NET? That we, we *dont* fork them, and ask the builders to get those separately? As a point of comparison, we don't carry a fork of cmake sources even though we need it to build.

**Comment by mmitche** [comment]
> Is it an option to upstream some changes to some Microsoft-owned repositories? For example https://github.com/aspnet/MessagePack-CSharp, https://github.com/mono/cecil, https://github.com/NuGet/FileSystem and https://github.com/NuGet/NuGet.Build.Localization seem like places where it might be possible to upstream changes? Perhaps some of them can be moved into the dotnet org too? I am also quite confused to see github.com/dotnet/cssparser in that list since it's, presumably, already in the dotnet org?

Yes, these will get upstream changes and stop relying on patches. I'm primarily concerned with cases where the code is coming from third parties and we use patches today.

> Maybe a meta-question: if the external repos really are first-class projects (eg, googletest) and the expected model of users (which would be .NET here) to consume the projects is not by copying sources, would it be worth it to make that an explicit build-time (or runtime) dependency of .NET? That we, we dont fork them, and ask the builders to get those separately? As a point of comparison, we don't carry a fork of cmake sources even though we need it to build.

What do we do if these projects cannot be built from source? Do we drive source-buildability projects for this separately?

**Comment by omajid** [comment]
> What do we do if these projects cannot be built from source? Do we drive source-buildability projects for this separately?

That seems like the best thing to do in the long term? I suspect compromises might be necessary in the short term.

**Comment by premun** [comment]
So.. we have had a lengthy discussion and we probably have somewhat conflicting requirements that are going to be driving this decision. We will have to explore these in more depth and weigh/relax some of them before we will settle on a decision. Regardless, thanks for your input, you raised some very interesting points.

**Comment by premun** [comment]
We have been through many more discussions and investigations and in the end, we have found a different solution that will not mandate as strong requirement as this proposal is doing. We will manage with keeping dependencies being handled as they are now with only few weaker requirements on top of that to ensure the external dependencies are secure and compliant with our regular policies.

I am closing this as it's superseded by https://github.com/dotnet/arcade/issues/10829
