### ISSUE TITLE
Repo level prebuilt baseline should not require an exclusion for intermediate packages

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3010]
Right now if you utilize the repo level prebuilt baseline infrastructure from arcade, you will have to add exclusions for the source-build intermediate packages.

Example from source-build-reference-packages - https://github.com/dotnet/source-build-reference-packages/blob/main/eng/SourceBuildPrebuiltBaseline.xml#L7

```
<UsagePattern IdentityGlob="Microsoft.SourceBuild.Intermediate.*/*" />
```

Given these are common prebuilts they should be included as part of the infrastructure rather than requiring each repo to add these exclusions.

**Comment by tkapin** [comment]
As agreed with @MichaelSimons, I'll take this one as part of the hackathon to get some hands-on experience with source-build. Assigning to myself.

**Comment by ellahathaway** [comment]
Closing this issue since PRs from all relevant repos have been merged.
