### ISSUE TITLE
.NET 8: Tooling to identify reference packages used in source-build for a repo

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3013]
### Describe the Problem

In order to satisfy https://github.com/dotnet/source-build/issues/2901, we need ways to identify the reference packages currently in use when a repository is built from source, and what code path is pulling those reference packages in.

### Describe the Solution

Create tooling to identify the reference packages that are required by a repo source build. The report should include:
- The list of source build reference packages
- How each package is brought in.

### Additional Context

This helps drive the TFM reduction.

**Comment by MichaelSimons** [comment]
[Triage]  @mmitche - we completed the full FX TFM trimming without this.  Is there still a need for this tooling?

**Comment by mmitche** [comment]
Nope! And really, I think you could do this simply by removing the SBRP reference and building.
