### ISSUE TITLE
AddRidToRuntimeJson doesn't work for BSD or musl based distros

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#303]
`source-build` has a task that adds the current RID to the `runtime.json` file in `Microsoft.NETCore.Platforms`.

However, this task assumes that the current RID is based on the `linux` base RID, which is for libc based Linux distros.  The `linux` RID is not applicable for BSD or musl based distros.

https://github.com/dotnet/source-build/blob/aea4b384cfb5077422f8ee0dd967251ed1d4c6a7/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/AddRidToRuntimeJson.cs#L56-L57

In order for source-build to support Unix distros that are not libc-based Linux, we need to fix this task to add the correct RID graph in those scenarios.

cc @dotnet/source-build-contrib

**Comment by MichaelSimons** [comment]
AddRidToRuntimeJson was removed with https://github.com/dotnet/installer/pull/17760.  Closing as no longer applicable.
