### ISSUE TITLE
.NET 8: Enable experimental MacOS source build

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3034]
### Describe the Problem

Unified build seeks to expand the number of platforms that .NET 8 can source-build on, and replace the existing Microsoft official build with source-build. Part of this is enabling a build for MacOS.

### Describe the Solution

MacOS source build (with a number of prebuilts) might actually be functional today. It is in use in some capacity for homebrew.

**Comment by MichaelSimons** [comment]
[Triage] @mmitche, @directhex - Some work was done in this space earlier.  Has this been completed?  If not what remains?

**Comment by MichaelSimons** [comment]
gentle ping @mmitche, @directhex - what work remains here?

**Comment by mmitche** [comment]
I'm not sure. @directhex What work got done here? Is there a branch anywhere?

**Comment by directhex** [comment]
https://github.com/dotnet/source-build/issues/3217 is the state of the art in my work. I've had other commitments for net8

**Comment by MichaelSimons** [comment]
What should we do with this issue?  Close (indicating we did what we expected) or move to .NET 9.0?

**Comment by directhex** [comment]
Either is fine.

**Comment by omajid** [comment]
@asbjornu hey, have you looked at building .NET 8 (using https://github.com/dotnet/dotnet/) on macOS ?

**Comment by asbjornu** [comment]
> @asbjornu hey, have you looked at building .NET 8 (using https://github.com/dotnet/dotnet/) on macOS ?

@omajid, I just tried it out now, and everything worked until `./build.sh --clean-while-building --online`, which fails with [the following error](https://gist.github.com/asbjornu/e0c66b0646edaa7ceadd720845966dcf).

**Comment by asbjornu** [comment]
Right. From [`dotnet/runtime/…/macos-requirements.md`](https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/macos-requirements.md) I can see that I have to clone the `dotnet/runtime` directory and run `brew bundle --no-lock --file eng/Brewfile` to have all dependencies installed. I'm doing that now and we'll see how it goes. That shouldn't be a showstopper for Homebrew, so if this succeeds, I'll see if I can bump the Homebrew formula to v8.
