### ISSUE TITLE
Create better documentation explaining what source-build is and why it is important

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3039]
Many .NET contributors/repo developers don't have an understanding of what source-build is, how it works, and why it is important.  Documentation should exist that address these topics so it can be referenced when the source-build team gets asked these questions.

**Comment by omajid** [comment]
https://github.com/dotnet/source-build#source-build-goals contains a brief description of the essential why. Is the additional documentation just about expanding and clarifying that? Does anyone have a specific format in mind?
