### ISSUE TITLE
Get CI working e2e with offline build

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#304]
The following repos need to be updated to build in the dev/release/2.1 branch:

**Toolsets** 
- [x] roslyn-tools
- [x] ~~buildtools - Currently this is not included in source-build~~

**Tier 1** 
- [X] application-insights
- [X] common
- [X] javascriptservices
- [X] netcorecli-fsc
- [X] newtonsoft-json
- [X] standard
- [X] xliff-tasks
- [x] msbuild
- [x] clicommandlineparser
- [x] roslyn
- [X] ~~cli-deps-satellites~~

**Tier 2** 
- [X] nuget-client
- [X] websdk
- [x] coreclr
- [x] symreader
- [x] symreader-portable
- [x] templating

**Tier 3** 
- [x] corefx

**Tier 4** 
- [x] core-setup

**Tier 5** 
- [x] sdk
- [x] vstest
- [x] cli-migrate
- [x] fsharp

**Tier 6**
- [ ] cli

**Comment by dseefeld** [comment]
Prerequisite issues to resolve before this can be completed:

- dotnet/source-build#311
- dotnet/source-build#314
- dotnet/source-build#318
- dotnet/source-build#319

**Comment by dseefeld** [comment]
This was completed with https://github.com/dotnet/source-build/pull/418
