### ISSUE TITLE
Produce project-specific PackageVersions.props file

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3041]
Part of https://github.com/dotnet/source-build/issues/2482

Given the ability to retrieve project's dependency versions (https://github.com/dotnet/source-build/issues/3040), a `PackageVersions.props` file should be produced based on current and previous source-built versions.

It can differ from the current implementation and be one specific file instead of a combination of two (static `previous` SB versions and dynamic `current` SB versions)

**Comment by oleksandr-didyk** [comment]
Expected implementation time -> 3-5 working days

**Comment by MichaelSimons** [comment]
> Given the ability to retrieve project's dependency versions (https://github.com/dotnet/source-build/issues/3040), a PackageVersions.props file should be produced based on current and previous source-built versions.

To clarify, the PackageVersions.props should only contain the versions for the dependencies discovered in https://github.com/dotnet/source-build/issues/3040.

**Comment by premun** [comment]
Coincidentally, I have a class for this too:
https://github.com/dotnet/arcade-services/blob/main/src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/AllVersionsPropsFile.cs
or maybe
https://github.com/dotnet/arcade-services/blob/4cf29ede51d0cc12e43e94dee79bb9449ba55cb4/src/Microsoft.DotNet.Darc/src/DarcLib/Models/MsBuildPropsFile.cs#L32

These are dictionaries that serialize to/from a simple `.props` file.

**Comment by MichaelSimons** [comment]
This was completed as part of https://github.com/dotnet/installer/pull/15267.
