### ISSUE TITLE
Enable individual `PackageVersions.props` file on tarball-contributing repositories

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3043]
Part of https://github.com/dotnet/source-build/issues/2482

Given a project-specific PackageVersions.props file (https://github.com/dotnet/source-build/issues/3041), each of the repositories contributing to the product tarball should opt-in to the new functionality. The _opt-in_ would mean enabling the functionality, building the repository and resolving any issues encountered (investigating if pinned versions can be removed, adding packages to SBRP, etc) together with the repo owners

- [x] source-build-reference-packages: https://github.com/dotnet/installer/pull/15437
- [x] sourcelink: https://github.com/dotnet/installer/pull/15437
- [x] arcade
  - https://github.com/dotnet/arcade/pull/13009
  - https://github.com/dotnet/source-build-reference-packages/pull/595
  - https://github.com/dotnet/installer/pull/16111
  - https://github.com/dotnet/arcade/pull/13754
  - https://github.com/dotnet/source-build-reference-packages/pull/691
  - https://github.com/dotnet/installer/pull/16592
- [x] command-line-api
  - https://github.com/dotnet/command-line-api/pull/2149
  - https://github.com/dotnet/command-line-api/pull/2150
  - https://github.com/dotnet/installer/pull/16109
- [x] diagnostics: https://github.com/dotnet/installer/pull/15968
- [x] emsdk: https://github.com/dotnet/installer/pull/15995
- [x] razor
  - https://github.com/dotnet/installer/pull/16495 (blocked until PR below flows in, see https://github.com/dotnet/installer/pull/16495#issuecomment-1563126107 for details)
  - https://github.com/dotnet/razor/pull/8763
- [x] xliff-tasks
  - https://github.com/dotnet/source-build-reference-packages/pull/602
  - https://github.com/dotnet/installer/pull/16000
- [x] cecil: https://github.com/dotnet/installer/pull/16024
- [x] runtime
  - https://github.com/dotnet/runtime/pull/86650
  - https://github.com/dotnet/installer/pull/16532
- [x] roslyn
  - https://github.com/dotnet/roslyn/pull/68371
  - https://github.com/dotnet/installer/pull/16573
- [x] source-build-externals: https://github.com/dotnet/installer/pull/16002
- [x] symreader: https://github.com/dotnet/installer/pull/16003
- [x] xdt: https://github.com/dotnet/installer/pull/16006
- [x] msbuild
  - https://github.com/dotnet/msbuild/pull/8818
  - https://github.com/dotnet/installer/pull/16637
- [x] roslyn-analyzers:
  - https://github.com/dotnet/roslyn-analyzers/pull/6454
  - https://github.com/dotnet/installer/pull/15350
- [x] aspnetcore
  - https://github.com/dotnet/installer/pull/16543
- [x] deployment-tools
  - https://github.com/dotnet/source-build-reference-packages/pull/604
  - https://github.com/dotnet/installer/pull/16012
- [x] format
  - https://github.com/dotnet/installer/pull/16540
- [x] templating
  - https://github.com/dotnet/source-build-reference-packages/pull/608
  - https://github.com/dotnet/templating/pull/6360
  - https://github.com/dotnet/installer/pull/16149
- [x] nuget-client
  - https://github.com/dotnet/installer/pull/16603
- [x] test-templates
  - https://github.com/dotnet/installer/pull/16540
- [x] fsharp
  - https://github.com/dotnet/installer/pull/16540
- [x] sdk
  - https://github.com/dotnet/sdk/pull/33039
  - https://github.com/dotnet/sdk/pull/33179
  - https://github.com/dotnet/installer/pull/16633
- [x] vstest
  - https://github.com/microsoft/vstest/issues/4438
  - https://github.com/dotnet/installer/pull/16576
- [x] installer
  - https://github.com/dotnet/installer/pull/16550

**Comment by oleksandr-didyk** [comment]
Expected implementation time is hard to pin-point due to the number of repositories and the possible issues around enabling the functionality in question

**Comment by MichaelSimons** [comment]
Closing issue as this has been rolled out to all product repos.
