### ISSUE TITLE
Backport `Use the source-built version of ref packs and don't use app  host when building in source-build` roslyn patch

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3051]
Patch to backport - https://github.com/dotnet/installer/blob/release/7.0.1xx/src/SourceBuild/tarball/patches/roslyn/0001-Use-the-source-built-version-of-ref-packs-and-don-t-.patch

**Comment by crummel** [comment]
Backported with https://github.com/dotnet/roslyn/pull/64650 and flowing in with https://github.com/dotnet/installer/pull/14725.
