### ISSUE TITLE
Dll files are not getting removed by CleanClonedSource during tarball creation

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3053]
The following Dll files exist in the tarball:

```
src/roslyn/src/Compilers/Test/Resources/Core/SymbolsTests/V1/MTTestLib1.Dll
src/roslyn/src/Compilers/Test/Resources/Core/SymbolsTests/V1/MTTestLib2.Dll
src/roslyn/src/Compilers/Test/Resources/Core/SymbolsTests/V2/MTTestLib1.Dll
src/roslyn/src/Compilers/Test/Resources/Core/SymbolsTests/V2/MTTestLib3.Dll
src/roslyn/src/Compilers/Test/Resources/Core/SymbolsTests/V3/MTTestLib1.Dll
src/roslyn/src/Compilers/Test/Resources/Core/SymbolsTests/V3/MTTestLib4.Dll
```

These files should be cleaned up by the [`CleanClonedSource` target](https://github.com/dotnet/installer/blob/main/src/SourceBuild/Arcade/tools/SourceBuildArcadeTarball.targets#L246) during tarball creation

**Comment by MichaelSimons** [comment]
> It might be okay to leave them there.

Thanks, that's good to know.  My concern is why the cleanup target is not catching these.  If it isn't catching these there is the potential other more concerning files are being missed.

**Comment by crummel** [comment]
It appears that when you have two entries in an Item that differ only by case, MSBuild ignores the second one.  I have a minimal repro:
```
cat test.proj
<Project>
  <PropertyGroup>
    <BuildDependsOn>$(BuildDependsOn);TestCasing</BuildDependsOn>
  </PropertyGroup>
  <Target Name="TestCasing">
    <ItemGroup>
      <MyExtensions Include=".Dll;.dll" />
      <Binaries Include="**/*%(MyExtensions.Identity)" />
    </ItemGroup>
    <Message Importance="High" Text="Using %(MyExtensions.Identity)" />
    <Message Importance="High" Text="Found %(Binaries.Identity)" />
  </Target>
</Project>

mkdir files
touch files/test.dll
touch files/test.Dll
dotnet msbuild test.proj

MSBuild version 17.4.0-preview-22428-01+14c24b2d3 for .NET
  Using .Dll
  Found 1/test.Dll
```

This works okay on Windows because it's case-insensitive anyway but I would call this an MSBuild bug on Linux.  Luckily the only files with the capitalized `Dll` extension are the ones noted above so it's not a terribly widespread problem.  Logged https://github.com/dotnet/msbuild/issues/8044 for the MSBuild bug.

**Comment by MichaelSimons** [comment]
[Triage] This is something that was detected as a difference between the tarball and VMR.  Since the VMR removes this in 8.0 and it is acceptable to ship 7.0 with this binary since it is test related, we decided to close this as it is not required for 7.0
