### ISSUE TITLE
Create developer guidance documentation for resolving prebuilts

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3054]
## Overview

In .NET 8.0, [repo level prebuilt detection will be enabled](https://github.com/dotnet/source-build/issues/3017).  A prerequisite for this is to have documentation that provides the following guidance for repo developers:

1. Explanation of what prebuilts are.
2. Overview of how prebuilt detection works.
3. Action guide on how to eliminate prebuilts - e.g. use a source-build version if it exists, utilize SBRP, a prebuilt to source-build graph, etc.
4. FAQ

A natural home for this documentation would be in the [source-build repo documentation](https://github.com/dotnet/source-build/tree/main/Documentation/sourcebuild-in-repos).

The _Action Guide_ should be _tested_ by enabling prebuilt detection on a couple repos by devs with various source-build knowledge to ensure its completeness.

## Additional pointers

  - Small/simple repositories to start with: [`sourcelink`](https://github.com/dotnet/sourcelink), [`xdt`](https://github.com/dotnet/xdt)
  - Example documentation for similar purposes: [Migration to Main](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md)

**Comment by MichaelSimons** [comment]
> > utilize SBRP
> 
> Instructions on SBRP should be referencing the currently developed tooling, correct? (the one by @andriipatsula )

Yes - but are the instructions going to change with the new tooling?  I was expecting it to be abstracted away by the `generate` tooling.

**Comment by oleksandr-didyk** [comment]
> Yes - but are the instructions going to change with the new tooling? I was expecting it to be abstracted away by the generate tooling.

In terms of instructions to create a ref pack - they should not. However, I would expect there to be a link to documentation on known issues of the new tooling since repo owners might run into problems with new packages. And that would be created based on the new tooling.

**Comment by oleksandr-didyk** [comment]
Also, is there any existing documentation outside the linked [source-build repo documentation](https://github.com/dotnet/source-build/tree/main/Documentation/sourcebuild-in-repos?rgh-link-date=2022-10-11T13%3A31%3A57Z) and other SB repo's docs, such as for SBRP and SB externals?

**Comment by MichaelSimons** [comment]
> Also, is there any existing documentation outside the linked [source-build repo documentation](https://github.com/dotnet/source-build/tree/main/Documentation/sourcebuild-in-repos?rgh-link-date=2022-10-11T13%3A31%3A57Z) and other SB repo's docs, such as for SBRP and SB externals?

No

**Comment by oleksandr-didyk** [comment]
Potential content:

  - Pre-builds - introduction to what pre-builds are, how we detect them and why do we need them removed from the build
  - Step-by-step guide for enabling detection - guidance on setting up pre-build detection in a given repository (editing `Version.Details.xml`, `SourceBuildPrebuildDetectionBaseline.xml`, etc)
  - Eliminating pre-builds - a flow of questions / answers after which the reader should be able to eliminate a pre-build
    - understanding the type of dependency that is being used as a pre-build (direct, indirect, dangling)
    - verifying if the dependency is already being source-build (a simple pointer to the result of https://github.com/dotnet/source-build/issues/1319 should suffice)
    - resolving any potential issue if it is source-build but cannot be used directly (ex.: bumping version to latest, creating SBRP package for the pinned version, etc)
    - checking if SBRP or text-only could be used (just a general introduction, for any issues during generation of the packs a pointer to a different doc should be used)
    - adding a dependency to source-build (pointer to https://github.com/dotnet/source-build/blob/main/Documentation/sourcebuild-in-repos/new-dependencies.md can be used)
  - FAQ
  - Contacts

**Comment by oleksandr-didyk** [comment]
Draft PR for the doc -> https://github.com/dotnet/source-build/pull/3083

**Comment by oleksandr-didyk** [comment]
Suggestion for the documentation visibility - links to the docs should be added to places where the user will most likely interact with pre-build detection. This should include:

  - header of `SourceBuildPreBuildBaseline.xml` and `generated-baseline.xml` files
  - error message for pre-build detection -> most likely the main way repository owners / contributors will interact with pre-build detection, so an easy actionable step like reading the docs would be of great help in that case

**Comment by oleksandr-didyk** [comment]
Update on progress: will have the PR docs merged + implement the documentation visibility points mentioned above by 25th November EoD
