### ISSUE TITLE
Implement an artifacts size check smoke test

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3061]
### Describe the Problem

Our artifacts can sometimes change drastically in size between releases, and without a careful eye this can go unnoticed until very late in the release cycle (too late to make any changes).

### Describe the Solution

We should add a smoke test that checks that the Private.SourceBuilt.Artifacts and the SDK have not changed in size more than a certain amount, say 5 or 10 percent. I'm not sure if we should outright fail the test yet or let it be a warning.

### Additional Context

I know RedHat runs some tests against the size of our output files, can @omajid provide any input or advice?

**Comment by MichaelSimons** [comment]
@omajid - Can you share details on what granularity you are checking the size at?  If checking the entire SDK, I can think of a number of scenarios that may get overlooked.  On the other hand checking at a per file level could cause a fair amount of noise and become a maintenance issue.

**Comment by omajid** [comment]
I have seen some of our tools work at the level of file sizes, but at a very rough level, and it has been enough to catch issues (though it also produces some false positives). [I think our rules warn on the following cases](https://github.com/rpminspect/rpminspect/blob/main/lib/inspect_filesize.c):

- A 0-byte file is now no longer a 0-byte file
- A flle with a non-0 size is now a 0-byte file
- File size changes (increases or decreases) by a significant percentage, say, 25%
