### ISSUE TITLE
Automate SDK comparison baseline updates

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3062]
## The Problem

Today, we have SDK baseline comparison tests that make our CI show a warning. Since it doesn't fail the pipeline and updating the baseline is cumbersome, the CI is permanently yellow and we gain no value from the comparison tests.

## Solution

We should automate updating the SDK comparison test baseline (and potentially the poison test too if that's applicable). I think this could happen in the monthly source-build-release pipeline along with the automated updates to global.json and Private.SourceBuilt.Artifacts versions.

**Comment by MichaelSimons** [comment]
[Triage] We would like to investigate eliminating the poison and sdk differences and is something we hope to invest in reducing in the lull after the 7.0 release.  We should focus on the areas that are changing frequently at which point the baseline wouldn't need updating very frequently.
