### ISSUE TITLE
Automate the package collection process to satisfy pre-release smoke testing requirements

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3068]
### Describe the Problem

We collect packages restored from internal feeds during smoke tests. These are output as build artifacts. However, these packages are not sufficient for all types of testing the source-build tarball. At times we need to add additional packages for offline testing.

At the moment I use an empty project with PackageDownload targets and a manually created NuGet config: https://gist.github.com/lbussell/47a3953686c218ede865e305478df74a

Then, I create the prereqs with this script: https://gist.github.com/lbussell/5789974491e3d3ed737aac0e8b97b594

### Describe the Solution

This can be automated in my proposed source-build-pre-release pipeline.

The steps required to completely automate this are:

1. Download amd64 and arm64 smoke test prereqs artifacts from internal builds.
2. Create combine prereqs package as described above.
3. Upload finished prereqs to dotnetclimsrc azure storage account.

### Additional Context

Reference: https://github.com/dotnet/source-build/blob/3c8f23d08475e6f59a5ca889e0719b61e18db476/.github/ISSUE_TEMPLATE/releases/release_checklist.md

**Comment by MichaelSimons** [comment]
An alternate solution would be to mirror the Microsoft package feed into dotnet-security-partners.  This solution is preferred because it is scalable.  By that I mean each time a partner adds/refactors their tests and take a dependency on additional packages, we need to respond on our side with the smoke-test-prereqs approach.

**Comment by MichaelSimons** [comment]
@mmitche - IIRC you said that you could do this work.  We would like to do this for 6.0, 7.0 and 8.0.  Our partners have indicated that they are ready to consume this on their side.  An ideal timeframe would be to have this implemented within the next month or two.  Is that feasible?

**Comment by mmitche** [comment]
Yes. Is this something we would implement in the release pipeline @premun worked on?

**Comment by MichaelSimons** [comment]
> Yes. Is this something we would implement in the release pipeline @premun worked on?

That's what I was thinking.  Here is the initial [PR](url) for it.

**Comment by premun** [comment]
The proposed solution from Logan would look like this:
- The upload should happen during the [pre-release stage](https://github.com/dotnet/source-build/blob/prvysoky/one-pipeline-to-rule-them-all/eng/templates/stages/pre-release.yml).
- This stage already uploads stuff to dotnetclimsrc azure storage account (for 6.0/7.0 flows) so it should be only a matter of downloading and uploading also the smoke-test-prereqs artifact:
    ![image](https://user-images.githubusercontent.com/7013027/219645662-001014f9-ea2d-495f-97a3-a845989315ce.png)


For the feed-mirroring solution, I don't know enough about how that should work.

**Comment by lbussell** [comment]
I agree 100% Michael, we should not move forwards with the tarball approach. Should we close this issue as not planned and open another one for the NuGet feed mirroring?

**Comment by MichaelSimons** [comment]
> I agree 100% Michael, we should not move forwards with the tarball approach. Should we close this issue as not planned and open another one for the NuGet feed mirroring?

I opened https://github.com/dotnet/source-build/issues/3267 to better track the POR.  Closing this issue.
