### ISSUE TITLE
Automatically submit update PRs to VMR-lite

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3069]
Requires https://github.com/dotnet/source-build/issues/3064 as a prerequisite.

After we have an updated branch, we should create a PR to the correct internal branch using the Azure DevOps API.

This is relatively low priority because the return on investment is low, but it's necessary for complete release automation. It's very easy to submit PRs manually via the web UI.

**Comment by MichaelSimons** [comment]
[Triage] We should prioritize this as there is a 6.0/7.0 have a long servicing lifecycle.  We can port the core logic from 8.0.
