### ISSUE TITLE
Incorrect version of ASP files being pulled on Alpine or after portable build removal

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3071]
See https://github.com/dotnet/source-build/issues/3121 and https://github.com/dotnet/installer/pull/14549.

**Comment by ayakael** [comment]
In my backport of https://github.com/dotnet/installer/pull/14549 in https://github.com/dotnet/installer/pull/14816, I've included the fix as implemente by @tmds.

**Comment by MichaelSimons** [comment]
@crummel - Is this still and issue?  It appears as though all referenced issues have been resolved.

**Comment by crummel** [comment]
This has been resolved, closing.
