### ISSUE TITLE
Stop utilizing inner clone functionality with the Unified Build plan

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3072]
With Arcade powered source-build ([arpow](https://github.com/dotnet/source-build/tree/main/Documentation/planning/arcade-powered-source-build)) the source code is cloned to an _inner repo_ within the `artifacts` directory for the source-build repo legs.  This is done to get a clean environment in order to properly detect prebuilts without disrupting the developers workspace.  The inner clone never added value within the tarball but was kept in place in order to utilize a common code path between the repo legs and the tarball.  This inner clone has two significant downsides.

1. Performance - both in times of coping the source and the disk space requirements it drives.
2. UX - when a build occurs, devs often use the paths from the errors in build logs to navigate to the offending code.  If they make changes to the inner cloned code, those changes will get lost when rebuilding.  The inner clone is never preserved.

The inner clone should be removed with the Unified Build plan.  Perhaps it would make sense to stop the use within the VMR-lite for .NET 8.0 and within the repo build when source-build is the build in .NET 9.0.

**Comment by MichaelSimons** [comment]
[Triage] Doing this work will also help support incremental builds.

**Comment by tkapin** [comment]
@MichaelSimons / @NikolaMilosavljevic - do we have an estimate of how much time this shaved off of a VMR build?

**Comment by NikolaMilosavljevic** [comment]
> @MichaelSimons / @NikolaMilosavljevic - do we have an estimate of how much time this shaved off of a VMR build?

On a regular 8 core machine, that used to build product source-build in 46 minutes, this work saved 6 minutes, so close to 15%.
