### ISSUE TITLE
Clean up obsolete source-build tasks

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3073]
Known obsolete tasks:
- [PublishCoreSetupBinaries](https://github.com/dotnet/installer/blob/e40fc0b12e77adf35c32e2cc361d85b3a3fbbc0e/src/SourceBuild/tarball/content/repos/runtime.common.targets#L4)
- PublishToolsetBinaries

**Comment by MichaelSimons** [comment]
@mthalman - I assigned this to you.  It would be a good one to fix.
