### ISSUE TITLE
Allow comments in baseline files

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3075]
This would allow us to annotate individual items that have been investigated or had issues filed but cannot be fixed right now.

**Comment by MichaelSimons** [comment]
[Triage] Adding annotations may cause UX issues when updating the baseline.  For example you wouldn't be able to just accept the new output without incorporating the existing annotations.

**Comment by MichaelSimons** [comment]
Closing this as this is superseded by https://github.com/dotnet/source-build/issues/3266.
