### ISSUE TITLE
Component Governance: System.Security.Cryptography.Xml.4.7.0

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/source-build#3082]
source-build appears to reference `System.Security.Cryptography.Xml.4.7.0` that is causing the new component governance issue.

More details: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-templating/alert/7360924?typeId=6669620

please check if this is should be addressed or dismissed.

**Comment by MichaelSimons** [comment]
[Triage] When I looked there are actually two CG alerts that need to be addressed.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - Is this something you can take a look at?  This is a higher priority item.  To fix this, newer SBRP packages need to be created, remove the older versions, update any existing SBRP references, and lastly, validate source-build builds cleanly.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic - Is this something you can take a look at? This is a higher priority item. To fix this, newer SBRP packages need to be created, remove the older versions, update any existing SBRP references, and lastly, validate source-build builds cleanly.

Working on it - is `main` branch the target?

**Comment by MichaelSimons** [comment]
Yes - However be aware of https://github.com/dotnet/source-build/issues/3084.
