### ISSUE TITLE
Building source-build tarball stops terminal from functioning correctly afterwards

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3090]
### Describe the Bug

After building a tarball, the terminal configuration is messed up somehow.

### Steps to Reproduce

I observed this on .NET 7.0 GA/RTM. I have observed this before but didn't note which commit.

1. Create a source tarball.
1. Build the source tarball and let it finish.
1. Try typing anything in the terminal and observe that the output isn't displayed.

### Other Information

Running the command `stty sane` restores the terminal to a working state.

**Comment by MichaelSimons** [comment]
In .NET 8.0 where the tarball has been replaced with the VMR, this still occurs when running the smoke-tests

**Comment by mthalman** [comment]
Ah... that's what's been happening to me! I had no idea this was caused by the commands I was running.

**Comment by MichaelSimons** [comment]
This appears to be caused by the DotnetWatchTests
