### ISSUE TITLE
Component Governance: System.Drawing.Common.4.7.0

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3094]
source-build appears to reference System.Drawing.Common 4.7.0 that is causing the new component governance issue.

More details: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-templating/alert/7408013?typeId=6669620

Please check if this should be addressed or dismissed.

**Comment by MichaelSimons** [comment]
Yes this should be addressed.  4.7.2 should be added and 4.7.0 should be removed.
