### ISSUE TITLE
git-clone-to-dir.sh fails by default on newer git versions

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3111]
Git has disallowed the `file` transport by default now so `git-clone-to-dir.sh` fails with `fatal: transport 'file' not allowed`.  The solution is either `git config --global protocol.file.allow always` (for all clones on the machine) or `git -c protocol.file.allow=always clone <other stuff as usual>` (for the individual clone command).

**Comment by MichaelSimons** [comment]
[Triage] Per @crummel, this only affects 3.1 which is EOL shortly so we won't fix this.

**Comment by crummel** [comment]
Also showing up in https://github.com/dotnet/aspnetcore/pull/46174, we do need to fix this.

**Comment by crummel** [comment]
I've merged this in the Arcade main, 6.0, and 7.0 branches now.  Matt Mitchell triggered the dependency flow in 7.0 so you should get that soon.
