### ISSUE TITLE
UX improvements to runtime intermediate

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3113]
While enabling pre-build detection, we ran into some UX issues around using `runtime`'s intermediate in other repositories. 

This issue aims to track any future problems that are discovered / require mitigation.

- [ ] https://github.com/dotnet/source-build/issues/3003
- [x] https://github.com/dotnet/runtime/issues/78054

**Comment by MichaelSimons** [comment]
[Triage] Remaining work is tracked with open issues.  Not much value in this issue.
