### ISSUE TITLE
Cannot upgrade MSBuild version in sourcelink

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3114]
`sourcelink` repository has a dependency on Arcade, which in turn has a dependency on the `SourceLink` package. When updating one of the dependencies of `sourcelink` (for example, MSBuild), a version resolution exception is thrown as Arcade's `SourceLink` package requires a lower version of the updated dependency, failing the build

Changes performed to the repo that cause the exception -> https://github.com/oleksandr-didyk/sourcelink/commit/0c184611f542b9ca93b67feb2f73e8c59d27dfca

Build error log -> [build_error_log.txt](https://github.com/dotnet/source-build/files/9992164/build_error_log.txt)

CC: @crummel

**Comment by MichaelSimons** [comment]
This issue better belongs in the SourceLink repo.

**Comment by MichaelSimons** [comment]
@oleksandr-didyk - Please open this issue in SourceLink.

**Comment by oleksandr-didyk** [comment]
Sure thing -> https://github.com/dotnet/sourcelink/issues/909
