### ISSUE TITLE
Component Governance: System.Data.SqlClient from 4.8.3 to 4.8.5 

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/source-build#3116]
source-build appears to reference System.Data.SqlClient 4.8.3, that is causing the new component governance issue.

More details: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-templating/alert/7454376?typeId=6669620

please check if this is should be addressed or dismissed.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic can you please fix this?  TIA
