### ISSUE TITLE
Update MSBuildLocator in source-build-externals from 1.4.1 to 1.5.5

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3126]
dotnet/format has recently updated MSBuildLocator from 1.4.1 to 1.5.5: https://github.com/dotnet/format/commit/2d7dc85dc1c9856a77a3ccdbfcfac47a9f5ce05d

We should update the version in https://github.com/dotnet/source-build-externals' main branch to unblock offline tarball/VMR builds.

**Comment by MichaelSimons** [comment]
[Triage] There are some open questions on what version is going to be required in 7.0.  There is an active issue where the version is being updated in a servicing release - https://github.com/dotnet/format/issues/1759.  It will likely be needed in main.
