### ISSUE TITLE
[Epic] Build from source customers guidelines

### ISSUE THREAD

**Issue by ashnaga** [dotnet/source-build#3127]
### Describe the Problem
No concrete guidelines on build requirements, build instructions and scenarios, and others for the source-build consumers. 

### Describe the Solution
Create/consolidate the end-to-end (acquire, set env, build, packaging, and others) for the consumer which will be the self-service guideline for the source-build customers. Add all the references to the source-build landing page for the easy access.

### Additional Context
- https://github.com/dotnet/source-build/issues/3128

**Comment by MichaelSimons** [comment]
[Triage] Closing in preference of having specific issues opened for remaining areas.
