### ISSUE TITLE
Instructions to set-up build environment

### ISSUE THREAD

**Issue by ashnaga** [dotnet/source-build#3128]
### Describe the Problem

Instructions to set-up build environment

### Describe the Solution
A few sections to cover in this document
Hardware Requirement (RAM, Disk)
Software Requirement (OS)
Toolchain Setup for different environment.

**Comment by MichaelSimons** [comment]
[Triage]  This was completed in https://github.com/dotnet/source-build/blob/main/Documentation/system-requirements.md.
