### ISSUE TITLE
Eliminate tarball verbiage from source-build infrastructure

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3139]
There are several places in the source that references a source tarball.  This verbiage is obsolete with the introduction of the VMR.  A scrub should be done to update this verbiage.

```
$~/git/dotnet$ ./build.sh 
ERROR: SDK not found at /home/rich/git/dotnet/.dotnet ERROR: Private.SourceBuilt.Artifacts artifact not found at /home/rich/git/dotnet/packages/archive/ - Either run prep.sh or pass --with-packages parameter    Errors detected in tarball. To prep the tarball, run prep.sh while online to install an SDK    and Private.SourceBuilt.Artifacts tarball.  After prepping the tarball, the tarball  can be    built offline.  As an alternative to prepping the tarball, these assets can be provided using    the --with-sdk and --with-packages parameters
```

**Comment by MichaelSimons** [comment]
[Triage] This also includes the https://github.com/dotnet/installer/tree/main/src/SourceBuild/tarball directory.

**Comment by MichaelSimons** [comment]
The renaming of the tarball directory will have to be coordinated with @premun because it is likely to cause issues with the VMR synchronization process.

**Comment by premun** [comment]
@MichaelSimons off-topic but quite funny - I have found out by pure chance that Stanford apparently listed "tarball" under "Institucionalized Racism" in _Elimination of Harmful Language Initiative_ 😅

tarball | tar archive | While the term refers to an archive that has been created with  the tar command, it can be negatively associated with the pejorative  term tarbaby.
-- | -- | --

source: https://web.archive.org/web/20221219160303/https://itcommunity.stanford.edu/ehli

**Comment by premun** [comment]
@MichaelSimons installer's root README seems to still have some references:
https://github.com/dotnet/installer/#build-net-from-source-source-build

**Comment by premun** [comment]
Ah, sorry, this is about SB infra only
