### ISSUE TITLE
Source-build CI failing with seemingly random CSC error

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#314]
CI is failing randomly with the following error:

CSC : error CS2015: '/mnt/j/workspace/dotnet_source-build/dev_release_2.0/Ubuntu16.04_Release_prtest/packages/microsoft.build.runtime/15.4.8/contentFiles/any/netcoreapp1.0/MSBuild.dll' is a binary file instead of a text file [/mnt/j/workspace/dotnet_source-build/dev_release_2.0/Ubuntu16.04_Release_prtest/src/cli/src/tool_msbuild/tool_msbuild.csproj] [/mnt/j/workspace/dotnet_source-build/dev_release_2.0/Ubuntu16.04_Release_prtest/repos/cli.proj]

The error can disappear if the build is retried.

**Comment by omajid** [comment]
Do you know what the fix for this was? This is still happening on some of my machines.

**Comment by dseefeld** [comment]
@omajid the problem was an issue with the Microsoft.Build.Runtime.15.4.8 package on myget.  The package on the cli-deps feed has an attribute for buildAction="None", while the package on the msbuild feed doesn't have this attribute.  So, if the one from the msbuild  feed is used, it will try to compile the contents, which is a dll, causing this error.  The fix was to move the SHA of CLI to a more recent commit to update the version of Microsoft.Build.Runtime.

**Comment by omajid** [comment]
Thanks!
