### ISSUE TITLE
Consider how to handle old tooling branches

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3141]
After discussing https://github.com/dotnet/fsharp/issues/14153, we decided to keep the current workaround because F#'s rel/dev17.0 branch is considered dead by them.  In general we need to figure out how to handle branches like this.  Some notes from the discussion:

- 17.0 is a dead branch - possibly won't even build anymore in F#'s CI setup
- F# has never had any MSRC or bug fixes to old branches like this
- Most contributors are from the community and don't use preview builds of .NET, especially intermediate non-released ones
- Last SDK upgrade was a large amount of work (~3 man-weeks for 5 -> 6)
- Upgrading F# branch without the rest of the repos should be easily doable
  - This would make us not match the official SDK though.

**Comment by crummel** [comment]
I believe this will not be an issue going forward in the 8.0 VMR, and the servicing VMRs have managed to work around the issue.  Marking as untriaged to nominate for closing.

**Comment by MichaelSimons** [comment]
[Triage] This has been addressed by the VMR.
