### ISSUE TITLE
CodeQL onboarding/exception for source-build-reference-packages

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3144]

**Comment by premun** [comment]
@crummel can you share more details about what's happening for this? I imagine this is for 6.0/7.0 VMRs?

Asking because of https://github.com/dotnet/source-build/issues/3152

**Comment by crummel** [comment]
This is enabled in main now: https://github.com/dotnet/source-build-reference-packages/pull/498.  I haven't gotten warnings about 6.0/7.0 yet so I haven't enabled it there, but there are warnings I need to address yet.

**Comment by premun** [comment]
Ah, thanks. My bad, I saw the title cut off with ellipsis and saw only "source-bu" and somehow assumed SB as whole.
