### ISSUE TITLE
Consider a smoke-test to compare version numbers between MSFT and source-built SDKs

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3145]
For a while (5.0), we were comparing SDK and runtime pack versions from the source-built SDK to expected values.  While this is a useful test, it was never ported to current branches and could be expanded to be even more useful.  Instead of just checking the SDK and runtime versions, we could check actual assembly versions to make sure we match what the Microsoft build of the SDK has.  This is also useful for verifying our versioning code is working correctly (e.g. see https://github.com/dotnet/source-build/issues/2780).

**Comment by tmds** [comment]
If possible, we should check commit sha's as well.

This gives a better assurance that the source-code used for the Microsoft build and the source-build build was the same.
