### ISSUE TITLE
[VMR] nuget-client build fails on case-preserving filesystems (Mac, Windows)

### ISSUE THREAD

**Issue by directhex** [dotnet/source-build#3149]
On Linux, `NuGet.config` and `NuGet.Config` are different files. Both can exist in the same folder, and attempts to read the "wrong" file will result in a file not found error. As a result, we have a patch in the NuGet repo, `eng/source-build-patches/0001-Rename-NuGet.Config-to-NuGet.config-to-account-for-a.patch` authored by @crummel, to reconcile a bad casing assumption. However, on Windows and Mac, this patch fails to apply with `git apply` as those two filenames are considered equivalent. This breaks the build on non-Linux.

We either need a way to separate out source build patches by OS applicability (e.g. `eng/source-build-patches/$(TargetOS)/`), or need to eliminate the patch.

**Comment by MichaelSimons** [comment]
[Triage] A fix was accepted in Arcade to address the problem that required the patch.  We believe the source-build patch can now be removed.

**Comment by directhex** [comment]
Is there a plan to remove the patch from the nuget-client repo? This is still causing build failures on non-Linux:

```
    Check for patches in /Users/directhex/Projects/dotnet/src/nuget-client/eng/source-build/../../eng/source-build-patches/*.patch
  EXEC : error : NuGet.config: already exists in working directory [/Users/directhex/Projects/dotnet/src/nuget-client/eng/source-build/source-build.proj]
  /Users/directhex/Projects/dotnet/src/nuget-client/eng/source-build/source-build.proj(59,5): error MSB3073: The command "git --work-tree=/Users/directhex/Projects/dotnet/src/nuget-client/eng/source-build/../../ apply --ignore-whitespace --whitespace=nowarn --unsafe-paths "/Users/directhex/Projects/dotnet/src/nuget-client/eng/source-build-patches/0001-Rename-NuGet.Config-to-NuGet.config-to-account-for-a.patch"" exited with code 1.
```

**Comment by MichaelSimons** [comment]
> Is there a plan to remove the patch from the nuget-client repo? This is still causing build failures on non-Linux:

Yes, that is what we intend to do with this issue.

**Comment by MichaelSimons** [comment]
Taking a brief look, I don't think this is necessary anymore.  I just ran a full vmr build to confirm.  I will check a few more things and then open a PR to remove this.

**Comment by MichaelSimons** [comment]
Alright I think I found the fix that eliminated the need for this patch - https://github.com/dotnet/arcade/pull/7549.  I will open a PR to remove this.

**Comment by directhex** [comment]
OK. I can send a PR to NuGet.Client to remove https://github.com/NuGet/NuGet.Client/blob/dev/eng/source-build-patches/0001-Rename-NuGet.Config-to-NuGet.config-to-account-for-a.patch

**Comment by MichaelSimons** [comment]
> OK. I can send a PR to NuGet.Client to remove https://github.com/NuGet/NuGet.Client/blob/dev/eng/source-build-patches/0001-Rename-NuGet.Config-to-NuGet.config-to-account-for-a.patch

I just opened https://github.com/NuGet/NuGet.Client/pull/5414

**Comment by MichaelSimons** [comment]
This patch has been removed and flowed into the VMR.
