### ISSUE TITLE
Upgrade SBRP packages flagged by CG in 7.0

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/source-build#3153]
### Describe the Bug

A few packages are being flagged by CG.

* [System.Drawing.Common.4.7.0](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-xliff-tasks/alert/7407970?typeId=6429138)
* [System.Data.SqlClient.4.8.3](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-xliff-tasks/alert/7456435?typeId=6429138)
* [System.Security.Cryptography.Xml.4.7.0](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-xliff-tasks/alert/7239434?typeId=6429138)

### Steps to Reproduce

Run xliff-tasks build, check out those sweet sweet component governance flagged issues.

### Other Information

There are no workarounds. Please help me. Thanks!

**Comment by MichaelSimons** [comment]
Looks like a DARC subscription should be defined to flow in the latest version.  Upgrading to the latest 8.0 version will resolve these CG alerts.

**Comment by jonfortescue** [comment]
This worked. Thanks @MichaelSimons !
