### ISSUE TITLE
Remove invalid third party notices file

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#3154]
Can we remove files like ./src/nuget-client/src/NuGet.Clients/NuGet.VisualStudio.Client/NOTICES.txt which are known to be not valid for source-build, and apply only to non-source-build builds? (See https://github.com/NuGet/Home/issues/11804 for the reasoning for this file)

**Comment by MichaelSimons** [comment]
With the VMR we have an easy mechanism to do this.  It may make sense in this specific case to cloak the entire NuGet.VisualStudio.Client directory from the VMR if possible.

**Comment by omajid** [comment]
Is this a decision that can be made on the source-build engineering side? Does it need any other review?

**Comment by crummel** [comment]
@richlander or @leecow might need to take a look

**Comment by leecow** [comment]
Cloaking the entire directory feels like a composition / engineering decision, as it will not affect the underlying files and licenses.

**Comment by MichaelSimons** [comment]
[Triage] This change is needs to be made against the source mappings in the VMR.  The VMR does not have PR validation in place yet.  We should defer making this change until that work is completed in order to validate there are no source dependencies that would break the build.

**Comment by MichaelSimons** [comment]
[Triage] The VMR now has PR validation so this can be fixed now.

**Comment by premun** [comment]
@MichaelSimons we are just about to roll out this: https://github.com/dotnet/arcade/issues/11982
which means we will have `source-mappings.json` being mirrored from installer. So let's wait for that and do it in an installer PR.

**Comment by premun** [comment]
Assigning to @MilenaHristova and I will coordinate with her to take care of this

**Comment by premun** [comment]
@MilenaHristova I think we should take care of this one now
