### ISSUE TITLE
[release/7.0] Add Microsoft.NETFramework.ReferenceAssemblies 1.0.3 targeting pack to SBRP

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3158]
See the following build error in 7.0.2xx bootstrap: https://dev.azure.com/dnceng/internal/_build/results?buildId=2060862&view=logs&j=05a957c8-6537-5d6d-69e3-d72786d35c31&t=2ef7b31a-1958-50cd-c8a0-00414b8948fc&l=817

It is unclear to me why this is only happening in the bootstrap build.

**Comment by lbussell** [comment]
The first commit where this happens appears to be 8654d0944d9d5fc749c6aa0fe0974948a141c602: https://dev.azure.com/dnceng/internal/_build/results?buildId=2057484&view=results

**Comment by MichaelSimons** [comment]
[Triage] We should investigate to understand why this only surfaces in the bootstrap leg before adding the addition targeting pack to SBRP.

**Comment by crummel** [comment]
Have we seen this in 7.0.1xx?  Nominating for closure otherwise since we're not planning on supporting 7.0.2xx.

**Comment by MichaelSimons** [comment]
[Triage] this is not an issue in 7.0.1xx.  For 8.0, the need for this will be removed by https://github.com/dotnet/source-build/issues/3014.
