### ISSUE TITLE
Mirror VMR's internal servicing branches to dotnet-security-partners/dotnet

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3162]
Automation is needed to mirror the VMR's internal servicing branches to dotnet-security-partners/dotnet during the release process.

**Comment by MichaelSimons** [comment]
[Triage] This will have to handle the scenario where the branch does not exist in dotnet-security-partners/dotnet.

**Comment by lbussell** [comment]
Is this a duplicate of https://github.com/dotnet/source-build/issues/3147?

**Comment by MichaelSimons** [comment]
> Is this a duplicate of #3147?

Yes I think it is.

**Comment by premun** [comment]
Oh, I assumed this one is for my VMR. I will open one for me then.

I checked the pipeline @lbussell created and I suspect that it might just work with the right inputs.
