### ISSUE TITLE
[VMR] packages/archive/archiveArtifacts.txt content is not getting updated

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3167]
The https://github.com/dotnet/dotnet/blob/main/packages/archive/archiveArtifacts.txt file is not getting synchronized from the installer.  This file used to be generated as part of the tarball creation logic.  It's content is dynamic and is based on values in the installer's eng/version.props file.

**Comment by MichaelSimons** [comment]
cc @premun

**Comment by premun** [comment]
I think I will need to know more on how we can replace this process.

> based on values in the installer's eng/version.props file

I can see that we set this `SourceBuiltPrebuiltsTarballName` property in `Versions.props` and that it's only used to be put in this file.
I understand this is a manual process - updating this value? Whenever the bootstrap SDK's version is bumped? Would it be a problem that someone would update this file instead?

I can also see that there is this potential second "private" version. I understand this is used during some internal code flow / when doing the release?

**Comment by MichaelSimons** [comment]
Discussing this with @crummel, we have decided that the correct place for these versions to be stored in the source-build's versions.props file, not the installer's versions.props file.  The archiveArtifacts.txt file will be removed.
