### ISSUE TITLE
Rename src/SourceBuild/tarball directory in dotnet/installer

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3184]
The src/SourceBuild/tarball directory name no longer makes sense with the introduction of the VMR (Virtual Mono Repo).  This directory should be renamed.

A couple suggestions that I have heard are:

src/VirtualMonoRepo/
src/SourceBuild/

Within this folder there would be content/, patches/ and readme.md

This issue was also discussed in https://github.com/dotnet/source-build/issues/2867#issuecomment-1350697418.

**Comment by MichaelSimons** [comment]
[Triage] We discussed this and feel that src/SourceBuild is the better name.

**Comment by premun** [comment]
I found this reference that might be worth fixing: https://github.com/dotnet/source-build/blob/466a89576b148ea5d540c5ccfafbf9ffbe2d76c3/eng/submit-source-build-release-pr.sh#L36

**Comment by MichaelSimons** [comment]
@premun - is this work done?  Can this be closed?
