### ISSUE TITLE
Define UX for declaring a repo level source-build dependency on runtime

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3188]
I don't know how to do this.  What is source-build metadata is needed here?

```
    <Dependency Name="Microsoft.NETCore.App.Ref" Version="8.0.0-alpha.1.22611.2">
      <Uri>https://github.com/dotnet/runtime</Uri>
      <Sha>cfdf0f67485ae41f4454a687b1e01ccb32e5e799</Sha>
    </Dependency>
```

**Comment by oleksandr-didyk** [comment]
The referenced package is in the _main_ runtime intermediate, so it should be retrieved with the following declaration:
```xml
    <Dependency Name="Microsoft.NETCore.App.Ref" Version="8.0.0-alpha.1.22611.2">
      <Uri>https://github.com/dotnet/runtime</Uri>
      <Sha>cfdf0f67485ae41f4454a687b1e01ccb32e5e799</Sha>
	  <SourceBuild RepoName="runtime" ManagedOnly="false" />
    </Dependency>
```
Also, since this is a runtime intermediate, the RID should be specified when triggering the build

**Comment by MichaelSimons** [comment]
[Triage] This US issue here is that a target rid must be specified and it may not be specified.  More importantly, it must be the portable linux rid - linux-x64.  We should handle this within the ARPOW infrastructure.

**Comment by oleksandr-didyk** [comment]
This was resolved via https://github.com/dotnet/arcade/issues/12222, closing
