### ISSUE TITLE
[release/7.0] 7.0.2xx bootstrap build is broken

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3197]
The dotnet-installer-source-build-tarball-build bootstrap build is broken on https://github.com/dotnet/source-build/issues/3158

See the following build error: https://dev.azure.com/dnceng/internal/_build/results?buildId=2079907&view=logs&j=05a957c8-6537-5d6d-69e3-d72786d35c31&t=2ef7b31a-1958-50cd-c8a0-00414b8948fc&l=823

**Comment by MichaelSimons** [comment]
Per the [source-build support policy](https://github.com/dotnet/installer#support), only the 7.0.1xx feature band is supported.
