### ISSUE TITLE
Remove linker repo from source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3199]
The linker repo is being moved into runtime - https://github.com/dotnet/runtime/issues/75278.  As a result, linker should be removed from source-build.

- [x] Remove linker source-build project
- [x] Remove linker project references within source-build
- [x] Remove linker VMR source-mappings

**Comment by MichaelSimons** [comment]
The first two items were done with https://github.com/dotnet/installer/pull/15389

**Comment by MichaelSimons** [comment]
@premun - am I correct in my understanding that a VMR PR needs to be opened to remove the src/Linker directory?

**Comment by premun** [comment]
@MichaelSimons yes
