### ISSUE TITLE
prep.sh --bootstrap needs updates from no longer building runtime-portable.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3210]
`prep.sh --bootstrap` is going to fail next time PSB is updated because it will no longer contain runtime-portable assets.  This is because the bootstrap process is trying to read various LinuxX64 package versions as shown [here](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/eng/bootstrap/buildBootstrapPreviouslySB.csproj#L22).

This code should be updated to reference the non-linux-x64 variants which exist for everything except the following:

* MicrosoftAspNetCoreAppRuntimeLinuxx64Version
* MicrosoftNETCoreAppCrossgen2LinuxX64Version

For these we should utilize the `ExtraPackageVersionPropsPackageInfo` infra to define non-linux-x64 variants with values defined to be the RID specific package versions.

**Comment by crummel** [comment]
Yes, this should all be taken care of now.
