### ISSUE TITLE
Arcade uses improper proxy properties for source link dependencies

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3212]
### Describe the Bug

Arcade uses a proxy property (`MicrosoftSourceLinkVersion`) in the SDK for all packages related to source link. This causes issues with pvp source build, since it's not possible to create a dependency on such a package (it does not exist), and even outside PVP source build, it means that we must put in special properties to set this after sourcelink has been built.

Arcade should use the actual package names (SourceLink.GitHub, SourceLInk.AzureRepos.Git) for this these cases, and emit these properties into the SDK version props.

**Comment by MichaelSimons** [comment]
@mmitche - How are you handling the common `ExtraPackageVersionPropsPackageInfo`s defined [here](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/Directory.Build.props#L212)?  I would not be surprised if a number of these are obsolete and others could be made repo specific.

**Comment by mmitche** [comment]
@MichaelSimons I did not filter them with PVP flow, at least at tis point. I think that we should attempt to remove them. This is the first one I'm going to tackle.

**Comment by mmitche** [comment]
PR started here: https://github.com/dotnet/arcade/pull/12197/files

**Comment by mmitche** [comment]
This has been resolved in arcade now. Last piece is updating source-build-externals.
