### ISSUE TITLE
Syntax error in source-build release pipeline

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3213]
[All links are internal Microsoft only]

In the "Submit announcement discussion" pipeline step:

```bash
/usr/bin/bash --noprofile --norc /mnt/vss/_work/_temp/67b1c7ed-86a3-4162-9976-f912dbf1bfe4.sh
+ echo Repo ID is MDEwOlJlcG9zaXRvcnk2NTQ5MDc0Mg==
/mnt/vss/_work/_temp/67b1c7ed-86a3-4162-9976-f912dbf1bfe4.sh: line 21: syntax error near unexpected token `('
Repo ID is MDEwOlJlcG9zaXRvcnk2NTQ5MDc0Mg==
##[error]Bash exited with code '2'.
```

Please see [the error here](https://dnceng.visualstudio.com/internal/_build/results?buildId=2084709&view=logs&j=cc13dea4-d77f-56d3-b09d-728f0b5faa1f&t=9a58eb41-0aff-5452-bc29-7ca846bf256b&l=13). The fix should be something like [this commit](https://dnceng.visualstudio.com/internal/_git/dotnet-source-build/commit/ad8655d2ec16995564e9ffe12ee20ccc7ebc56d8?refName=refs/heads/dev/crummel/debugging).

This needs to be fixed before the next source-build release.

**Comment by MichaelSimons** [comment]
@lbussell - would you mind submitting a PR for this?  TIA
