### ISSUE TITLE
Port 7.0.2 release changes to main

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3215]
https://github.com/dotnet/installer/pull/15251 needs to be ported to main to get the build working again.  Changes are needed to adapt it to the VMR.

**Comment by tkapin** [comment]
@MichaelSimons is this resolved by https://github.com/dotnet/installer/pull/15315 or that's an orthogonal work? Thanks!

**Comment by MichaelSimons** [comment]
After https://github.com/dotnet/installer/pull/15315 is merged we need to update the previous source-build artifacts to address some prebuilts.  This issue is required to update the artifacts.
