### ISSUE TITLE
Prebuilt annotated-usage report is missing SourceBuildPackageIdCreator information

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3218]
Looking at the latest annotated-usage reports, the  SourceBuildPackageIdCreator information is missing.  This property/attribute is useful when investigating prebuilts as it indicates that source build produces a different version of the prebuilt. 

```
<AnnotatedUsage Id="System.Text.Encoding.CodePages" Version="7.0.0-rc.2.22472.3" File="src/razor/artifacts/buildObj/source-build/self/src/artifacts/obj/Microsoft.CodeAnalysis.Razor/project.assets.json" Project="src/razor/" SourceBuildPackageIdCreator="runtime SystemTextEncodingCodePagesPackageVersion/8.0.0-alpha.1.23053.7" />
```

This appears to be a regression caused by the [per repo pvp work](https://github.com/dotnet/installer/commit/987040517a2c80cdcc33fdd1ebb5a4b27685f4e3).  The PackageVersions.props.pre.*.xml files were renamed which the prebuilt reports depend on [here](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/repo-projects/Directory.Build.targets#L691)

**Comment by MichaelSimons** [comment]
cc @mmitche - Do you have bandwidth to fix this?

**Comment by mmitche** [comment]
Yep one sec I'll fix
