### ISSUE TITLE
Change servicing CI to be more in-line with linux distro servicing workflow

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3221]
### Describe the Problem

There are a few scenarios that matter for building .NET Source Build:
1. Linux distros bootstrapping a new version of .NET - This is covered by our Fedora "Bootstrap" CI leg.
1. Linux distros building a servicing version of .NET using their most-recently released SDK and artifacts.
1. Developers working on .NET Source-Build.

Our "default" PR validation, CI, and developer workflows run with the following setup:
1. A *Microsoft*-built SDK acquired with the `dotnet-install` script.
1. Previously Source-Built (PSB) Artifacts that are modified by the `prep.sh` script to include portable versions of certain packages.

Whereas Linux distros building servicing releases need to build with:
1. A source-built SDK with the latest publicly available .NET version in their distro.
1. PSB Artifacts from their latest .NET build.

Since our CI and developer workflows are different from Linux distros servicing scenarios, we have a gap in testing that we need to close.

### Describe the Solution

With https://github.com/dotnet/source-build/issues/3156, we have added some rudimentary validation that we won't break Linux distros' servicing workflows in the future.

Moving forwards, we should have more robust validation for more distros. After a new major version of .NET is released (or maybe even in the last few preview releases), PR validation/CI and Developer workflows should be focused on making sure that we don't break Linux distros.

One proposed solution is:
1. Store RID-specific source-built SDKs and PSB artifacts for each Major and servicing release in blob storage (for each RID that we build in CI). We do this now but only for CentOS 8 Stream, our "lowest-common-denominator" distro.
3. Modify the `prep.sh` script to download the correct source-built SDK and PSB artifacts for a given RID.

We could also potentially use some type of build images that contain .NET versions directly from Linux distro package feeds, but it's unclear where those would live or how they would be updated.

**Comment by MichaelSimons** [comment]
[Triage]. In prerelease branches we would test the bootstrap flow in all legs except one.  Once main reaches RC, we would inverse this to be the opposite and continue this pattern in the servicing branches.

It would be ideal if the `prep.sh` script only supported the bootstrap flow.  If you have an sdk and artifacts to build with, you are responsible for acquiring them.  The prep script should not be tied to the RIDs Microsoft builds in CI.

**Comment by MichaelSimons** [comment]
[Triage] In discussing this, the agreement is that we should add an offline leg that tests with the n-1 source-build SDK.  We don't want to change the CentOSStream8_Online_PreviousSourceBuiltSdk_x64 leg to just be offline because there is value in keeping this leg running when there is a prebuilt in the system that may break offline legs.
