### ISSUE TITLE
Missing root `NuGet.config` for some SB-infra projects

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3230]
### Context

The CG scan of the VMR showed that since the VMR is missing a root `NuGet.config`, some of the projects from the SourceBuild infra don't have a matching one. Each project needs to have one so that some other global one is not used.

CFS0011 alert info: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/project-artemis/central-feed-services-cfs#3-cfs0011---c-projects-are-missing-feed-configuration

### Offending files

- [x] [eng/bootstrap/buildBootstrapPreviouslySB.csproj](https://github.com/dotnet/dotnet/blob/main/eng/bootstrap/buildBootstrapPreviouslySB.csproj)
- [x] [test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj](https://github.com/dotnet/dotnet/blob/main/test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj)
- [x] [tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj](https://github.com/dotnet/dotnet/blob/main/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj)
- [x] [tools-local/tasks/SourceBuild.MSBuildSdkResolver/SourceBuild.MSBuildSdkResolver.csproj](https://github.com/dotnet/dotnet/blob/main/tools-local/tasks/SourceBuild.MSBuildSdkResolver/SourceBuild.MSBuildSdkResolver.csproj)

### Solution

I believe we should add a `NuGet.config` to VMR's root or next to these files. I am not sure what feeds this needs to configure though.

**Comment by MichaelSimons** [comment]
[Triage]  Some of these projects (e.g. [buildBootstrapPreviouslySB.csproj](https://github.com/dotnet/dotnet/blob/main/eng/bootstrap/buildBootstrapPreviouslySB.csproj)) build online and would require Microsoft feeds others would be satisfied by an empty NuGet.config at the root of the repo.  It is very important that the root NuGet.config be empty to prevent pulling in external packages.

**Comment by premun** [comment]
@MichaelSimons fyi I had to add the dotnet-public feed to restore these for smoke tests:

- `Microsoft.NET.Test.Sdk`
- `xunit`
- `xunit.runner.visualstudio`

I think they might have been getting restored from nuget.org until now.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=271909&view=logs&j=941f2e24-48a0-594a-6b1a-0e16aaeb8606&t=bff1be7c-b019-50b4-ca3b-6c316f1f727b&l=49
