### ISSUE TITLE
Build Cecil repo in VMR

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3232]
With the work to [merge linker into the runtime repo](https://github.com/dotnet/runtime/issues/75278), the cecil repo will no longer be a submodule and instead will be a standalone repo.  Once the [runtime changes flow](https://github.com/dotnet/installer/pull/15389) in to add a dependency on the cecil repo, a source-build cecil project will need to define in order to get it to build.

**Comment by tlakollo** [comment]
The dotnet cecil project already has source build information being produced and runtime adds the [SourceBuild tag into that depedency](https://github.com/dotnet/runtime/blob/main/eng/Version.Details.xml#L86), is anything else required?

**Comment by MichaelSimons** [comment]
> The dotnet cecil project already has source build information being produced and runtime adds the [SourceBuild tag into that depedency](https://github.com/dotnet/runtime/blob/main/eng/Version.Details.xml#L86), is anything else required?

Yes, there has to be a way in the full product source-build to trigger the cecil repo build.  This is done via the [repo-projects](https://github.com/dotnet/installer/tree/main/src/SourceBuild/content/repo-projects).

**Comment by MichaelSimons** [comment]
@mthalman - can you add this project and validate cecil is prebuilt clean?  It is dependent on https://github.com/dotnet/installer/pull/15389 flowing it but you could start work now based on that branch.
