### ISSUE TITLE
Unify Source Build release pipeline

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3241]
This issue is a follow up for https://github.com/dotnet/source-build/issues/3194

### Context

The 6.0/7.0 and the 8.0 release process of Source Build differs as we started using the VMR for this in 8.0. However, most of it is shared.
Further, the release process consists of running 3 different pipelines in a row in different points of time which is not ideal. It would be better to have a single pipeline represent a release.

### Goal

Have a single pipeline for 6.0/7.0/8.0 that would concatenate the three existing ones, gated by approvals.

The proposed pipeline would have these stages:
- **Get info stage** - Current pre-release pipeline
- **Approval gate** - Confirmation that smoke test prereqs are in place
- **Mirror stage** - Current mirroring pipeline
    - Possibly another stage for sending out comms, or could be part of this one
- **Approval gate** - Wait for .NET 8.0 release
- **Release stage** - Current release pipeline

Further ideas:
- We could then have 1 pipeline run for each release of each version (so a 6.0 run, 7.0 run, 8.0 run).
- We could have instructions directly in the PR gates (or in the release notes).

**Comment by MichaelSimons** [comment]
For clarity, the possible another stage on sending comms is part of the prerelease process which would happen prior to the GA release.

**Comment by premun** [comment]
> For clarity, the possible another stage on sending comms is part of the prerelease process which would happen prior to the GA release.

Thanks, fixed.

**Comment by premun** [comment]
This has been completed. Follow-up fixes and improvements were logged separately.

**Comment by premun** [comment]
Oops, this hasn't been merged yet actually
