### ISSUE TITLE
dotnet/dotnet build fails if en-US.UTF.8 locale is not installed

### ISSUE THREAD

**Issue by martincostello** [dotnet/source-build#3250]
### Describe the Bug

Attempting to build dotnet/dotnet on Ubuntu 22.04 LTS with WSL fails if the `en-US.UTF.8` locale is not already installed in the distro.

The build will run for a few seconds and then fail with various errors of the form:

```
bash : error : setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

Installing it manually with the `sudo locale-gen en_US.UTF-8` command then leads to the following error:

```sh
$ ./build.sh --clean-while-building --online
tar: PackageVersions.props: Cannot open: File exists
tar: Exiting with failure status due to previous errors
```

### Steps to Reproduce

Build dotnet/dotnet@c2c829eea2213b812f07259db041a6ba4165d34a (which right now matches the `release/8.0.1xx-preview1` branch).

```sh
./build.sh --clean-while-building --online
```

### Other Information

```bash
$ uname -a
Linux UK-FPH-TEC43012 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Version from `winver.exe`: `Version 21H2 (OS Build 22000.1574)`.

**Comment by MichaelSimons** [comment]
[Triage] The locale issue is expected and we believe this is not a source-build specific issue.  The problem of the build not working  after installing the expected locale is something we are tracking with #928 (number 7 specifically).

@crummel - can you link to the doc/issue for the locale issue and then close this?

**Comment by crummel** [comment]
https://github.com/dotnet/msbuild/issues/4194 is the older issue for this; it came up again recently in https://github.com/dotnet/runtime/issues/82873.
