### ISSUE TITLE
SBRPs: lack of support for the `netcoreapp3.1` TFM

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/source-build#3251]
### Describe the Bug
SBRP generator generates reference assemblies for all TFMs from the nuget package. Compilation of reference package with the `netcoreapp3.1` tfm using the `build.sh` script fails with numerous compilation issues like:

```text
*/lib/netcoreapp3.1/*: error CS0246: The type or namespace name 'DebuggableAttribute' could not be found
*/lib/netcoreapp3.1/*: error CS0518: Predefined type 'System.String' is not defined or imported
```

We may introduce filtering of TFMs and do not add the failing one to the `<TargetFrameworks>` list.

### Steps to Reproduce

Run the `./generate.sh --pkg microsoft.codeanalysis.common,4.4.0` and try to compile SBRPs.

**Comment by MichaelSimons** [comment]
[Triage]  To date, there has been no need for the netcoreapp3.1 TFMS in the SBRPs we are generating.  Unless there is a need we do not plan to investigate this.

**Comment by ViktorHofer** [comment]
@MichaelSimons given that there's no need for netcoreapp3.1 or other .NETCoreApp tfms, should we add those tfms to the exclusion list to that devs don't need to manually remove them after the generation is done?

**Comment by ViktorHofer** [comment]
Reopening as we have a tracking issue in this docs file: https://github.com/dotnet/source-build-reference-packages/blob/main/docs/known_generator_issues.md#unsupported-netcoreapp31-tfm.
