### ISSUE TITLE
6.0 CI does not produce UpdatedMsftToSdk.diff

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3258]
I'm not sure if this ever worked like 7.0 did, but 6.0 CI is not/no longer producing the new MSFT-build to Source-build diff, making updates to this baseline harder.  For an example, see https://dnceng.visualstudio.com/internal/_build/results?buildId=2114943&view=results.

**Comment by MichaelSimons** [comment]
[Triage] This may become a non-issue once https://github.com/dotnet/source-build/issues/3266 is addressed.

**Comment by crummel** [comment]
Yes, closing as redundant.
