### ISSUE TITLE
Build tarball artifacts are not versioned correctly

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3268]
The following build artifacts are not versioned correctly:

1.  Private.SourceBuilt.Artifacts
1.  Private.SourceBuilt.Prebuilts
1.  dotnet-smoke-test-prereqs

If you look at a Preview 1 build these are versioned as 8.0.100. I was the version to indicate they are for a Preview 1 build.  Furthermore when looking at these artifacts in CI, I would expect their version number to be build specific.  Having the version numbers include the build would help in traceability as it would identify which build produced them.  This would improve the dev workflow for uploading these build artifacts to blob storage as it would eliminate the need to rename them to the 0.1.0-8.0.100-n.centos.8-x64 syntax.

**Comment by NikolaMilosavljevic** [comment]
We could easily fix the naming of `Private.SourceBuilt.Artifacts`, to become something like `Private.SourceBuilt.Artifacts.8.0.100-preview.3.23178.1.centos.8-x64.tar.gz`.

What is the expectation for naming of `Private.SourceBuilt.Prebuilts` and `dotnet-smoke-test-prereqs`?

All of these artifacts are produced in separate infra projects, so the solutions would vary, as well as the cost for fixing.

@MichaelSimons

**Comment by MichaelSimons** [comment]
All should be versioned the same.
