### ISSUE TITLE
Release announcement generation / publishing

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3270]
### Context

The release pipeline creates and publishes the release announcement discussion. However, the text of the announcement needs to be customized which can prevent us from using the automation to publish it. It would be preferential if the pipeline did it (it will be authored by the bot, etc.).

### Proposed solution

1. The release pipeline will have a new parameter - an announcement gist URL
2. We will create an empty gist and run the pipeline, supplying the URL to it
3. The pipeline would print the suggested announcement content during the Pre-Release stage
4. We can take this and populate the gist where we would final-fit it
5. The pipeline would take the body of the announcement from there during the Release stage

**Comment by premun** [comment]
@MichaelSimons what do you think of this proposal? It should be very easy to implement using the GitHub CLI

**Comment by MichaelSimons** [comment]
I like this approach but I would want the URL to be optional.  For normal servicing releases, I don't recall a time that we posted a custom message, it certainly is an edge case.
