### ISSUE TITLE
[7.0] Poison tests are failing in CI

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3279]
[Failing CI](https://dev.azure.com/dnceng/internal/_build/results?buildId=2120057&view=results) (Microsoft Internal Link).

Differences need investigating and baseline needs updating.  Several of the changes appear to be desired changes related to removing the runtime-portable leg.

**Comment by crummel** [comment]
Fixed with https://github.com/dotnet/installer/pull/15688.
