### ISSUE TITLE
[Arm64/Linux] Create bootstrapped SDK

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/source-build#328]
Use https://github.com/dotnet/source-build/blob/dev/release/2.0/scripts/bootstrap/buildbootstrapcli.sh to create a bootstrapped [Arm64/Linux] SDK

**Comment by sdmaclea** [comment]
I made an attempt to do this with `dotnet-sdk-2.1.300-preview2-008171-linux-arm64` ( a recent daily build)

+ There are a few changes needed to the script.  I will open a PR.
+ `dotnet new console` works
+ `dotnet build` fails with 
`Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 134`

@janvorli FYI

**Comment by janvorli** [comment]
134 means an abort, most likely due to an assert. Can you try to pass `-v diag` to the dotnet build command to see if it reveals more details?

**Comment by sdmaclea** [comment]
@janvorli It had been too long.  Couldn't remember `-v diag`

It is failing to load `Microsoft.CodeAnalysis.CSharp`, because I was not able to get crossgen to complete on it.  This was what I originally suspected, but I missed csc.dll opening it in strace logs.

I will try your disable crossgen approach.

**Comment by sdmaclea** [comment]
With `COMPlus_ZapDisable=1` and `COMPlus_ReadyToRun=0` the build and run succeeds sometimes.  
The build is unstable though.  There are at least two failure modes.

```
The build failed. Please fix the build errors and run again.
```
or
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

The build failed. Please fix the build errors and run again.
```

I haven't checked if the x86 version of the build is stable.

**Comment by sdmaclea** [comment]
@janvorli I tried again with a recent build. dotnet-sdk-2.1.300-preview2-008281-linux-x64

When buildbootstrap  is complete it seems to not recognize its own runtime...
```
../dotnet-sdk-2.1.300-preview2-008281-linux-arm64/dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/sdmaclea/git/source-build/test/hw4/hw4.csproj...
  Restoring packages for /home/sdmaclea/git/source-build/test/hw4/hw4.csproj...
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.1.0-preview2-26227-01)
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102:   - Found 1436 version(s) in cli-deps [ Nearest version: 2.1.0-preview2-26209-04 ]
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102:   - Found 24 version(s) in nuget.org [ Nearest version: 2.1.0-preview1-26216-03 ]
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102:   - Found 0 version(s) in nuget-build
  Generating MSBuild file /home/sdmaclea/git/source-build/test/hw4/obj/hw4.csproj.nuget.g.props.
  Generating MSBuild file /home/sdmaclea/git/source-build/test/hw4/obj/hw4.csproj.nuget.g.targets.
  Restore failed in 1.03 sec for /home/sdmaclea/git/source-build/test/hw4/hw4.csproj.

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```
```
../dotnet-sdk-2.1.300-preview2-008281-linux-arm64/dotnet restore
  Restoring packages for /home/sdmaclea/git/source-build/test/hw4/hw4.csproj...
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.1.0-preview2-26227-01)
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102:   - Found 1436 version(s) in cli-deps [ Nearest version: 2.1.0-preview2-26209-04 ]
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102:   - Found 24 version(s) in nuget.org [ Nearest version: 2.1.0-preview1-26216-03 ]
/home/sdmaclea/git/source-build/test/hw4/hw4.csproj : error NU1102:   - Found 0 version(s) in nuget-build
  Restore failed in 973.53 ms for /home/sdmaclea/git/source-build/test/hw4/hw4.csproj.
```

I tried to look at `strace` and `-v diag`, but have made no progress.

I am going to look at the core-setup changes between the two builds....  Any other ideas?  Do you want me to try to send you the build?

**Comment by sdmaclea** [comment]
@steveharter Could this bootstrapping behavior change be related to the `Assembly Conflict Resolution` changes in core-setup between `b13a0d5` & `86d1f92`

**Comment by steveharter** [comment]
Not sure what you're trying to do exactly but those 'assembly conflict' changes did change a lot of cross-compiled code between hostfxr and hostpolicy. I've been trying to debug failures on OSX (perhaps present on Unix too) perhaps related to position-independent-code; see  https://github.com/dotnet/corefx/issues/27571

**Comment by janvorli** [comment]
@sdmaclea I get the same error on My x64 Ubuntu 14.04 when trying to use the latest cli. So it has nothing to do with your boostrapping.

However, I was thinking about the arm64 Linux bringup and seeing all the issues you have with the bootstrap CLI, it seems that it would make sense to focus on enabling official builds of the arm64 Linux packages in our lab using cross build. First in coreclr, then in corefx and finally in core-setup. 
We already have similar support for arm32, so adding it for arm64 should not be complicated.
Once we have that, dotnet cli would be able to target arm64 Linux when running on other platforms, like Linux x64 or Windows.

Does it make sense to you?

**Comment by sdmaclea** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/17178 which is the source of the instability
