### ISSUE TITLE
Remove all Full Fx TFMs from SBRP

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3282]
As part of https://github.com/dotnet/source-build/issues/3014, all net4* TFMs are being trimmed from source-build.  Once this work is completed, we expect a significant number of SBRPs will no longer be referenced and therefore will be removed.  Of the remaining SBRPs, we expect there will be some that target net4* and net core TFMs.  Because of this, we would still need to have the net4* targeting packs in SBRP which is not desirable.  

In order to address this problem, the generate SBRP tooling will need to be updated to filter out the net4* TFMs.  We can then regenerate the existing packages that reference net4* TFMs in order to "clean them up".

Full Fx TFMs to remove

- [x] net45 - https://github.com/dotnet/source-build-reference-packages/pull/598
- [x] net451 - https://github.com/dotnet/source-build-reference-packages/pull/596
- [x] net46
- [x] net461
- [x] net462
- [x] net47
- [x] net472

**Comment by ViktorHofer** [comment]
With the new reference source package generator that should be possible by adding the following [here](https://github.com/dotnet/source-build-reference-packages/blob/fdbe4632b67ee16bd1856417cda93fdbf84139ec/src/referencePackageSourceGenerator/ReferencePackageSourceGenerator.proj#L13): `net4*`.

**Comment by ViktorHofer** [comment]
Congratulations - great milestone 👍
