### ISSUE TITLE
prep.sh should be more modular

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3283]
prep.sh actually can do four different things:
- Download a MSFT-built SDK
- Download MSFT-built previously-source-built artifacts
- Additionally download portable packages and insert them into the previously-source-built archive (bootstrap scenario)
- Download known prebuilts for the current release (generally previews only)

We should break these out so that the default behavior is to do all four of these things but each individual behavior can be disabled with an argument like `--no-sdk` or `--skip-sdk`, etc.

**Comment by lbussell** [comment]
When this issue is completed, we should update the [N-1 CI leg](https://github.com/dotnet/installer/pull/15603) to include the --no-sdk option, as the point of that leg is to acquire its own SDK.

**Comment by MichaelSimons** [comment]
Fixed by https://github.com/dotnet/installer/pull/15697
