### ISSUE TITLE
SDK content differences - roslyn

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3286]
Microsoft and source-built SDKs contain the following differences related to `roslyn` content and packages. There should be no unintentional differences.

All intentional differences should be captured in SDK diff exclusion file: https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkDiffExclusions.txt

Files only present in Microsoft-built SDK:
```
-./sdk/x.y.z/Roslyn/bincore/System.Collections.Immutable.dll
-./sdk/x.y.z/Roslyn/bincore/System.Reflection.Metadata.dll
```

**Comment by NikolaMilosavljevic** [comment]
The diff has changed since 7.0 and recent changes. This comment addresses the current diff that shows 2 files present in Microsoft SDK, but not in source-built SDK:
```
./sdk/x.y.z/Roslyn/bincore/System.Collections.Immutable.dll
./sdk/x.y.z/Roslyn/bincore/System.Reflection.Metadata.dll
```

This was caused by PVP flow changes for `roslyn` repo. Before those changes, source-build would have revved the following properties: https://github.com/dotnet/roslyn/blob/17dcec138afd78a265be020ef8ca0e22a254aa88/eng/Versions.props#L305-L306
```
    <SystemCollectionsImmutableVersion>7.0.0</SystemCollectionsImmutableVersion>
    <SystemReflectionMetadataVersion>7.0.0</SystemReflectionMetadataVersion>
```

After PVP flow changes, `csc` project compilation against net8.0 would filter these binaries and not copy to project output, due to newer versions present in the target runtime - this is done in `ResolvePackageFileConflicts` task: https://github.com/dotnet/sdk/blob/258f5ce9eef56801c88495b89183edd45bfd22b6/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ConflictResolution.targets#L40

Here's the captured log entry:
```
Encountered conflict between 'Platform:System.Reflection.Metadata.dll' and 'CopyLocal:/src/git/dotnet/src/roslyn/artifacts/source-build/self/package-cache/system.reflection.metadata/7.0.0/lib/net7.0/System.Reflection.Metadata.dll'. Choosing 'Platform:System.Reflection.Metadata.dll' because AssemblyVersion '8.0.0.0' is greater than '7.0.0.0'.
```

@MichaelSimons @mmitche we have 2 options:
1. Add 7.0.0 dependencies to `eng/Version.Details.xml` for these 2 binaries - this will let the source-build bump the versions to latest, live ones, and we'll get these missing binaries in SDK layout.
2. Accept that there is a difference and we don't have these binaries next to csc.dll in source-build. At runtime, those binaries would be loaded from shared runtime, which would contain the exact same version.

**Comment by MichaelSimons** [comment]
Option 2 seems the better choice IMO.

**Comment by mmitche** [comment]
I think the second option is better. @jaredpar Might have some opinions here. Either way, the result is the same and we could see potential differences in behavior. However, I wonder whether that's the case even with the MSFT built SDK. Are there any contexts in which roslyn assemblies are loaded where we would have already loaded an 8.0 SCI/SRM?

**Comment by NikolaMilosavljevic** [comment]
Fixing this by adding the following entries to sdk diff exclusion list, so the diffing will ignore the files in Microsoft-built SDK.
```
msft,./sdk/x.y.z/Roslyn/bincore/System.Collections.Immutable.dll
msft,./sdk/x.y.z/Roslyn/bincore/System.Reflection.Metadata.dll
```

**Comment by NikolaMilosavljevic** [comment]
> I wonder if this is just a deployment bug on our part. If I go to our csc project and run `dotnet publish` I don't get either of these DLLs in the output but, as you noted, they are present in the SDK deployment. Guessing that means we're unnecessarily zipping them up into the transport package that we hand off to the .NET SDK.

This seems to be caused by the `TargetFrameworks` in the packaging project: https://github.com/dotnet/roslyn/blob/419ee237406466eebd6bdfbf932a31e26971ec4c/src/NuGet/Microsoft.Net.Compilers.Toolset/AnyCpu/Microsoft.Net.Compilers.Toolset.Package.csproj#L4

In `roslyn` repo build, this will evaluate to `net472;net6.0` due to: https://github.com/dotnet/roslyn/blob/419ee237406466eebd6bdfbf932a31e26971ec4c/eng/targets/Settings.props#L101

I'm not sure who else, besides .NET is consuming `Microsoft.Net.Compilers.Toolset` package, but this might be intentional.

In repo build, `csc` gets built for `net7.0`, `net6.0`, and `net472`. Due to these references being `7.0.0` both `net472` and `net6.0` project outputs would include the dependencies. SDK would end up consuming `net6.0` output.

In source-build, `csc` is only built for `net8.0`, dependencies are automatically bumped to `8.0.0` and get filtered as target platform contains them.
