### ISSUE TITLE
Understand and eliminate all remaining SDK content differences

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3291]
This is a master issue for tracking all remaining differences in SDK diff.

With https://github.com/dotnet/installer/pull/15650, majority of differences are now captured in the exclusion file https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkDiffExclusions.txt. Each exclusion has an associated tracking issues.

There are more differences that need to be understood, properly tracked, and eventually eliminated. Most of the issues would require implementation by teams that own the particular binary or package. This issue should be updated with links to all dependent work in other repos, once owners are identified and issues created.

Categorized differences and associated issues:

- https://github.com/dotnet/source-build/issues/2583
- https://github.com/dotnet/source-build/issues/2573
- https://github.com/dotnet/source-build/issues/3285
- https://github.com/dotnet/source-build/issues/3286
- https://github.com/dotnet/source-build/issues/3287
- https://github.com/dotnet/source-build/issues/3288
- https://github.com/dotnet/source-build/issues/3289
- https://github.com/dotnet/source-build/issues/3290
- https://github.com/dotnet/source-build/issues/3526

The following files are .NET FX binaries showing in Microsoft-built SDK - not an issue for source-build:
```
./sdk/x.y.z/Microsoft.CodeCoverage.IO.dll
./sdk/x.y.z/Microsoft.VisualStudio.Setup.Configuration.Interop.dll
```

**Comment by MichaelSimons** [comment]
We should fix https://github.com/dotnet/source-build/issues/3292 first as it will resolve at least one of these differences.

**Comment by NikolaMilosavljevic** [comment]
The following files are .NET FX binaries showing in Microsoft-built SDK - not an issue for source-build:
```
./sdk/x.y.z/Microsoft.CodeCoverage.IO.dll
./sdk/x.y.z/Microsoft.VisualStudio.Setup.Configuration.Interop.dll
```

**Comment by NikolaMilosavljevic** [comment]
Completed.
