### ISSUE TITLE
Run CompareMsftToSb on non-msft SDK legs only

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3292]
Currently CI is running the CompareMsftToSb on the legs that build with the MSFT SDK.  This is a source of some of the diffs as noted in https://github.com/dotnet/source-build/issues/2583#issuecomment-952415068.  We should refactor CI to only run on the bootstrap legs or the [new leg running with a previous source-build SDK](https://github.com/dotnet/installer/pull/15603).

**Comment by NikolaMilosavljevic** [comment]
It doesn't seem that this will yield significant improvements in the quality of SDK diffs. I did a local test of stage 1 and stage 2 source-builds - there was only one difference/improvement in SDK diffs: `./sdk/x.y.z/dotnettools/dotnet-watch/x.y.z/tools/netx.y/any/system.io.pipelines.dll`

**Comment by MichaelSimons** [comment]
[Triage] We should re-evaluate the value of this once we get closer to releasing 8.0.  Even though only one assembly was removed in the latest assessment, in the future there may be more and having this change would save time in investigation.  Hard to say what the value would be.

**Comment by NikolaMilosavljevic** [comment]
I've compared 8.0 preview 7 SDKs produced in source-builds that were running with 1) Microsoft SDK, 2) previously source-built SDK, 3) current source-built SDK. There were no differences in content, so we can continue running `CompareMsftToSb` tests on legs using Microsoft SDK.
