### ISSUE TITLE
Arcade poison leak Microsoft.NET.StringTools.dll

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3293]
This is a new poison leak introduced around 7.0.102 - 7.0.103 ([baseline update](https://github.com/dotnet/installer/pull/15688)).  This is non-shipping code but we should still make sure we understand what the new file is.

**Comment by crummel** [comment]
This is a normal MSBuild assembly that is just oddly named.  This should be resolved by the next previously-source-built update or by an SBRP package in the long run.

**Comment by MichaelSimons** [comment]
Re-opening, it doesn't feel correct to close this until the poison leak is addressed.  

@crummel, When you say _This should be resolved by the next previously-source-built update_, is this another case that would benefit by running the poison tests on a leg that doesn't use the MSFT SDK to build?

**Comment by crummel** [comment]
Running the poison tests with a source-built SDK had the same results, the same leak still showed up.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - is this something you could investigate after completing your 8.0 work?  TIA

**Comment by NikolaMilosavljevic** [comment]
Arcade packages are considered non-shipping - those packages were excluded from poisoning since https://github.com/dotnet/installer/pull/15347, so this does not repro. @MichaelSimons is there a different angle I might be missing? Otherwise, this can be closed.

**Comment by NikolaMilosavljevic** [comment]
This is a non-shipping package. We have improved the infrastructure in 8.0 to exclude all non-shipping packages from poisoning. But the infra was not backported to 7.0.

Based on previous decisions, we made, to ignore non-shipping packages in poison report, this new entry is acceptable. Closing the issue.
