### ISSUE TITLE
Offline CI legs are failing to find package runtime.linux-x64.Microsoft.DotNet.ILCompiler

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3315]
Failing Microsoft internal CI - https://dev.azure.com/dnceng/internal/_build/results?buildId=2134798

Sample failure
```
    /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj : error NU1101: Unable to find package runtime.linux-x64.Microsoft.DotNet.ILCompiler. No packages exist with this id in source(s): prebuilt, previously-source-built, reference-packages, source-built [/vmr/src/runtime/artifacts/source-build/self/src/Build.proj]
    /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj : error NU1101: Unable to find package runtime.linux-x64.Microsoft.DotNet.ILCompiler. No packages exist with this id in source(s): prebuilt, previously-source-built, reference-packages, source-built [/vmr/src/runtime/artifacts/source-build/self/src/Build.proj]
```

The failure seems to be caused by a new dependency on the IlCompiler in the runtime build.  The portable ILCompiler is not something the [prep's bootstrap logic](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/eng/bootstrap/buildBootstrapPreviouslySB.csproj#L30) restores for x64.

**Comment by MichaelSimons** [comment]
@mthalman - is this something you can fix?  TIA

@crummel - can you explain to me why the bootstrap packages are not consistent across architectures/rids?  For example there are more arm64 packages restored than the other architectures/rids.  Shouldn't they be uniform?

**Comment by crummel** [comment]
I think it's because we're guaranteed not to have any arm64 packages in previously-source-built (unless we go back to merging legs into the archive).  Some of the x64 packages will be covered by PSB, but arm64 and MUSL never will be.

**Comment by MichaelSimons** [comment]
> Some of the x64 packages will be covered by PSB, but arm64 and MUSL never will be.

I can see how that was the case when we were building the runtime repo in the portable configuration, but now that we aren't all the runtime assets are rid specific.
