### ISSUE TITLE
Release download URLs mix SDK and Runtime version

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#3317]
### Describe the Bug

The source-code for 8 Preview 2 (https://github.com/dotnet/dotnet/releases/tag/v8.0.100-preview.2) is available at this URL:

```
https://github.com/dotnet/dotnet/releases/download/v8.0.100-preview.2/dotnet-sdk-source-8.0.0-preview.2.tar.gz
                                                        ^ sdk version                       ^ runtime version     
```

Shouldn't it be both 8.0.100 or both 8.0.0?

**Comment by MichaelSimons** [comment]
@premun, @crummel - I thought we were going to change the release tagging to align with the runtime version number, not the SDK.

**Comment by crummel** [comment]
Yes, we found a couple issues with runtime vs SDK tagging yesterday and today.  We also had to manually truncate to the stabilized versions, and we were looking for the runtime-version tag in the installer repo.  I think we can assign this to @premun, he was already working on it.

**Comment by omajid** [comment]
> we were going to change the release tagging to align with the runtime version number, not the SDK.

Is there someplace I can read up some more about what is happening and why?

**Comment by MichaelSimons** [comment]
> Is there someplace I can read up some more about what is happening and why?

There isn't any documented.  We are going to tag the VMR release with runtime version instead of the SDK version in preparation for the VMR supporting multiple SDK feature bands.  @mmitche is just beginning to think about this problem and will have a writeup for a proposal on how to support this in the VMR.

**Comment by premun** [comment]
I changed the tarball name to contain the release tag - https://github.com/dotnet/source-build/pull/3322 - is that the desired behaviour?

**Comment by tmds** [comment]
> We are going to tag the VMR release with runtime version instead of the SDK version in preparation for the VMR supporting multiple SDK feature bands.

It seems strange to tag with the runtime version since multiple SDK versions can use the same runtime, and the repo includes an SDK.

**Comment by MichaelSimons** [comment]
> It seems strange to tag with the runtime version since multiple SDK versions can use the same runtime, and the repo includes an SDK.

The original thinking was that the vmr will contain all SDK feature bands within a single branch.  The build options will let you build one or multiple SDKs at once and they will all share the same runtime assets.  Thinking is just beginning on this and a proposal will be drafted and posted for feedback.

**Comment by tmds** [comment]
Is someone requesting for multiple feature bands?

As said in https://github.com/dotnet/source-build/issues/2694, we {Red Hat) are ok with shipping a single band.

Even if we can build all bands, I think we may decide to ship only one (tbd).

**Comment by MichaelSimons** [comment]
> Is someone requesting for multiple feature bands?

The goal of the unified build project is it is the only build system.  Microsoft's build would be based on this and has the requirement to ship all feature bands.

**Comment by tmds** [comment]
Thank you for clarifying.

> Microsoft's build would be based on this

Great! 👍

**Comment by MichaelSimons** [comment]
> The git tag should be either v8.0.0-preview.2.23128.3 or v8.0.0-preview.2? Basically equal to the tag on top.

The git tag should be the build number.  This matches the behavior in the rest of the repos - eg https://github.com/dotnet/runtime/releases/tag/v8.0.0-preview.2.23128.3

> The tarball should have the SDK version instead as the full URL will be prepended by the tag, so it will be: https://github.com/dotnet/dotnet/releases/download/v8.0.0-preview.2.23128.3/dotnet-sdk-source-v8.0.0-preview.2.23128.3.tar.gz

This doesn't much matter to me as this is going away long term.  IMO it should be:
https://github.com/dotnet/dotnet/releases/download/v8.0.0-preview.2.23128.3/dotnet-source-v8.0.0-preview.2.23128.3.tar.gz

Note use the runtime build number in both locations and drop the "sdk" name.

**Comment by premun** [comment]
This is fixed now
