### ISSUE TITLE
[SBRP] Can UAP TFMs be filtered out of the generated ref packs?

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3326]
Currently the generate tooling will generated UAP TFMs.  I question if this is necessary.  It would be preferrable to filter these out if they are not necessary.

A package to validate this on it `system.valuetuple,4.5.0`

**Comment by MichaelSimons** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
As just discussed offline, those can be filtered out as they shouldn't be an input to source build. @MichaelSimons do you want to open a PR for it or should I?

Just adding the `uap*` regex to https://github.com/dotnet/source-build-reference-packages/blob/75ba964bbf67d42da6f301030b02156c819c8a89/src/referencePackageSourceGenerator/ReferencePackageSourceGenerator.proj#L10 should be sufficient. Note that strictly speaking netcore50 which is already excluded is also UAP, so we are already excluding that TFM family to some degree.

**Comment by MichaelSimons** [comment]
I can open a PR.
