### ISSUE TITLE
Microsoft.NET.Workload.Emscripten prebuilts reported in latest builds

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3336]
Microsoft internal CI - https://dev.azure.com/dnceng/internal/_build/results?buildId=2139238&view=logs&j=941f2e24-48a0-594a-6b1a-0e16aaeb8606&t=cffff4a5-f52c-50c6-45c9-52a0bd619b26

The following Microsoft.NET.Workload.Emscripten prebuilts are being detected in the latest CI builds:

```
/vmr/repo-projects/Directory.Build.targets(676,5): warning : Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100-preview.3.8.0.0-preview.3.23167.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(676,5): warning : Microsoft.NET.Workload.Emscripten.net6.Manifest-8.0.100-preview.3.8.0.0-preview.3.23167.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(676,5): warning : Microsoft.NET.Workload.Emscripten.net7.Manifest-8.0.100-preview.3.8.0.0-preview.3.23167.1 [/vmr/repo-projects/dotnet.proj]
```

Checking the build logs I verified that a Microsoft.SourceBuild.Intermediate.emsdk 8.0.0-preview.3.23167.1 is being produced.  The one thing that jumped out at me if the version of the prebuilt being loaded is rather strange - 8.0.100-preview.3.8.0.0-preview.3.23167.1

**Comment by MichaelSimons** [comment]
Looks like the regression came in with these changes - https://github.com/dotnet/emsdk/compare/352d64e0ce9b99a8cff6207621432a986920ffd9..25d9f7a5e38a2d61b94ff341bc0d32135fcb15f9

**Comment by MichaelSimons** [comment]
I confirmed that the TFM filtering is the source of the prebuilts.  I [created a patch](https://github.com/dotnet/installer/pull/15866) to revert the filtering for preview.3.

@NikolaMilosavljevic - Can you please investigate the underlying issue?  TIA

**Comment by MichaelSimons** [comment]
Reopening to ensure the tfm filtering problem is addressed.

**Comment by NikolaMilosavljevic** [comment]
> I confirmed that the TFM filtering is the source of the prebuilts. I [created a patch](https://github.com/dotnet/installer/pull/15866) to revert the filtering for preview.3.
> 
> @NikolaMilosavljevic - Can you please investigate the underlying issue? TIA

Will take a look - yes, this appears to have been introduced with TFM trimming work, which is odd. Trimming change is very simple: https://github.com/dotnet/emsdk/pull/312

**Comment by NikolaMilosavljevic** [comment]
> The version there is correct, as far as I remember. Did filtering the TFMs stop producing the manifest?

Yeah - it stopped producing and packaging the manifests.
