### ISSUE TITLE
[SBRP] Add packages required by razor

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3341]
We are currently allowing prebuilts in `razor` - https://github.com/dotnet/razor/blob/main/eng/SourceBuildPrebuiltBaseline.xml

```
    <UsagePattern IdentityGlob="Microsoft.AspNetCore.App.Ref/7.0.2" />
    <UsagePattern IdentityGlob="Microsoft.NETCore.App.Ref/7.0.2" />
    <UsagePattern IdentityGlob="System.Text.Encoding.CodePages/6.0.0" />
```

We need to add 7.0 targeting packages and a package for `System.Text.Encoding.CodePages/6.0.0`

**Comment by MichaelSimons** [comment]
This has been addressed - closing.
