### ISSUE TITLE
Add basic tests for PackageSourceGenerator in SBRP

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3343]
In the past we have encountered trivial issues in SBRP caused by changes to the package source generator. Examples:
  - https://github.com/dotnet/source-build-reference-packages/pull/582
  - https://github.com/dotnet/source-build-reference-packages/pull/586

These could be safeguarded against with some basic tests that would executed as part of the CI thus validating any incoming changes before merge.

**Comment by ViktorHofer** [comment]
Closing as duplicate of https://github.com/dotnet/source-build/issues/3089
