### ISSUE TITLE
Onboard .NET Source-Build Bot to Secret Manager

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3347]
## Motivation

We would like to utilize Secret Manager tooling for managing / rotating secrets used in the source-build pipeline. This would help us adhere to secret best-practices as well as lower manual maintenance of these values.

## Work required

Instructions here: https://github.com/dotnet/dnceng/tree/main/src/SecretManager/Microsoft.DncEng.SecretManager#onboarding-a-new-repo

A pre-requisite for this work is moving the `source-build-release` pipeline to `dotnet-release` - https://github.com/dotnet/source-build/issues/3501. Since the repo in question is already using Secret Manager, we could re-use existing logic (such as the weekly pipeline that rotates the secrets).

Additionally, we should move any secret located outside of .NET Product Construction team's reach to a key vault under their control. With the team taking ownership of the pipeline in the future, it would make sense to have any secret be accessible to them, especially those that require manual rotation

## Progress
  - [x] secrets that the pipeline is using are catalogued and added to vault configs in the repository
      - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/32030
  - [x] any secret outside of .NET Product Construction team's access are moved to appropriate key vaults; variable groups are added making these secrets available to the release pipeline in AzDO

**Comment by MichaelSimons** [comment]
[Triage] @lbussell - is this something you can fix for source-build since you are also doing this work for .NET docker?

**Comment by tkapin** [comment]
@oleksandr-didyk - please describe what is being done here and link it to the appropriate issues describing the migration to the dotnet-releases repo, thanks.

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk - please describe what is being done here and link it to the appropriate issues describing the migration to the dotnet-releases repo, thanks.

Done, added a description, tasks performed and pre-requisite work on moving to `dotnet-release`
