### ISSUE TITLE
Remove MSBuild-related prebuilts once TFM filtering is implemented

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3348]
Prebuilts were added for MSBuild 16.10.0 and 16.11.0. Normally, these would be defined as SBRPs but an issue was encountered when attempting to do that. The build of the `Microsoft.Build` package was using the `Microsoft.Build.Framework` assembly from the `net472` targeting pack instead of from the newly built `Microsoft.Build.Framework` package. There is an API difference between those two `Microsoft.Build.Framework` versions that led to a compile error.

Since this issue is specific to the `net472` TFM, this issue should be resolved once TFM filtering is fully implemented.

Here's the list of packages that can be removed from prebuilts and added as SBRPs instead:

* Microsoft.Build.16.10.0
* Microsoft.Build.16.11.0
* Microsoft.Build.Framework.16.10.0
* Microsoft.Build.Framework.16.11.0
* Microsoft.Build.Tasks.Core.16.10.0
* Microsoft.Build.Tasks.Core.16.11.0
* Microsoft.Build.Utilities.Core.16.10.0
* Microsoft.Build.Utilities.Core.16.11.0
* Microsoft.NET.StringTools.1.0.0
* System.Configuration.ConfigurationManager.4.7.0
* System.Security.Cryptography.ProtectedData.4.7.0

Related:
* https://github.com/dotnet/source-build-reference-packages/pull/559#issuecomment-1460446713
* https://github.com/dotnet/installer/pull/15773
* https://github.com/dotnet/installer/pull/15933

**Comment by MichaelSimons** [comment]
These were added with https://github.com/dotnet/source-build-reference-packages/pull/609.
