### ISSUE TITLE
Remove prebuilts for 5.0 targeting packs

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3349]
The following prebuilts were added in https://github.com/dotnet/installer/pull/15933 to compensate for a change in NuGet:

* Microsoft.AspNetCore.App.Ref.5.0.0
* Microsoft.NetCore.App.Host.linux-arm64.5.0.17
* Microsoft.NetCore.App.Host.linux-x64.5.0.17

The change was introduced by https://github.com/dotnet/installer/pull/15905.

Related build that shows prebuilt failures: https://dev.azure.com/dnceng/internal/_build/results?buildId=2142871&view=results (internal link)

In order to remove these as prebuilts, we either need to have these targeting packs added to SBRP or a compensating change made in NuGet that prevents these from showing up as prebuilts.

**Comment by MichaelSimons** [comment]
I think this was a result of these changes - https://github.com/NuGet/NuGet.Client/pull/5098.
