### ISSUE TITLE
Pre-release stage should include link to generated PR

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3352]
The [`Update security-partners-dotnet`](https://github.com/dotnet/source-build/blob/4cd2965e63aa2d23112c4bb03282a4e905977a6f/eng/templates/stages/pre-release.yml#L114-L132) task generates a PR with the changes for the release. It would be helpful if it also included a link to the PR in the output to easily navigate to the PR (and cross-reference for troubleshooting purposes).

**Comment by premun** [comment]
FYI @MichaelSimons, @mthalman we will ask @ali-turan7 to help us with this and onboard him onto the project

**Comment by ali-turan7** [comment]
The response to the request for the establishment of a PR is recorded and parsed. The PR URL is built and printed using the information obtained.
