### ISSUE TITLE
Skip creation of PR in pre-release stage if it contains no commits

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3353]
If a release needs to be iterated upon due to issues that are encountered, it may be necessary to run the Pre-release stage multiple times. In that case, it's possible the PR that gets generated by [`Update security-partners-dotnet`](https://github.com/dotnet/source-build/blob/4cd2965e63aa2d23112c4bb03282a4e905977a6f/eng/templates/stages/pre-release.yml#L114-L132) has already been merged. So when a subsequent run of the Pre-release stage occurs, it will still create the PR even though it contains no commits. I suggest that the PR creation be skipped if it contains no commits, and include a warning message instead.

**Comment by premun** [comment]
FYI @MichaelSimons, @mthalman we will ask @ali-turan7 to help us with this and onboard him onto the project

**Comment by ali-turan7** [comment]
The necessary control is applied by comparing the new and target branches to determine whether a new commit has been made as well as whether a new PR is necessary.
