### ISSUE TITLE
Determine what to do about 'floating' App.Ref packs in source-build repo legs

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3356]
In the source-build repo legs (at least SDK), we get restores of Microsoft.NETCore.App.Ref, at a recent released version. This is most likely an implicit version that is used when building net6 or net7 targeted binaries.

It's infeasible to generate SBRPs for these, since:
- We'd have to do so every month
- In most cases they may not even be available publicly until after release day, and so couldn't be checked into SBRP.

My guess is that these are coming in via tests but investigation is warranted. 

I think we have a few options for this:
- Forcing an older, SBRP compatible ref pack version during repo source-build.
- Avoiding building any code that may use a ref pack of an older release (if the code is non-critical)
- Simply excluding these prebuilts in repo-level source-build.

I'm a fan of the first or third options there. **If** these are tests, the behavior they are exhibiting is intentional. We build plenty of code that attempts to target downlevel, because that's a core feature of the SDK. The version of the ref pack probably matters less than the fact that it is a 6.0/7.0 ref pack.

If the issues are coming from non-test code, most likely the TFM should be upgraded.

@dotnet/source-build-internal

**Comment by MichaelSimons** [comment]
@mmitche - Can you link to a concrete occurrence of this that I can take a look at.  I am interesting in knowing the details here on where the differences are coming from the full product source-build and the repo build.  Ideally we would want to eliminate this difference.

**Comment by mmitche** [comment]
I was seeing this in sdk repo-level source-build when I was enabling the baseline there. Let me see whether I can pull it up again.

**Comment by mmitche** [comment]
@MichaelSimons https://dev.azure.com/dnceng-public/public/_build/results?buildId=224422&view=logs&j=2f0d093c-1064-5c86-fc5b-b7b1eca8e66a&t=d2b639a6-cb19-5f1f-66fd-8047f66b3026&l=297

**Comment by mmitche** [comment]
Thanks. Commenting on that issue. That might be a difficult one to solve, if this is a downlevel targeting issue.

**Comment by MichaelSimons** [comment]
[Triage]  As noted we don't think this is going to be a wide spread issue and likely each occurrence will need to be scrutinized carefully.  This particular occurrence will be handled/discussed via https://github.com/dotnet/sdk/issues/30272.
