### ISSUE TITLE
Add SBRPs for SDK

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3357]
Add SBRPs for the dotnet/sdk repo based on the list in https://github.com/dotnet/sdk/blob/main/eng/SourceBuildPrebuiltBaseline.xml, or upgrade as necessary.

**Comment by MichaelSimons** [comment]
@mmitche - were all of these addressed with https://github.com/dotnet/source-build-reference-packages/pull/627?

**Comment by mmitche** [comment]
@MichaelSimons Most. I have a branch open where I am iterating right now.

**Comment by MichaelSimons** [comment]
Closing as there are no more SBRPs needed for the SDK - see https://github.com/dotnet/sdk/pull/32698 for the latest update.
