### ISSUE TITLE
Make Source Build work without a `.git` directory

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3359]
### Context

Currently, Source Link uses git metadata such as revision and remote URL so that it can reference the original source code during debugging.
When we build .NET, it doesn't have to necessarily be out of a git repository - it can be from a source tarball only (downloaded from a Release page for instance). In these cases, we work around this by asking for URL and SHA as input and artificially creating certain files in the `.git` directory and this is not ideal.

### Goal

It should be possible to build .NET without a present `.git` directory and pass the URL and SHA to Source Link directly. This will require investigation on how to pass these from SB through Arcade to Source Link (which is used for each repo and tied to targets from the SDK). It's also possible a new feature might be needed for this to work.

**Comment by tmat** [comment]
> In these cases, we work around this by asking for URL and SHA as input and artificially creating certain files in the .git directory and this is not ideal.

Why is it "not ideal"?

**Comment by tmat** [comment]
> one reason I can think of is that Source Link can take dependency on another git behaviour in the future which might rely on something more complex such as the git index 

This won't happen as that would be a breaking change. The minimal git data needed for Source Link to work are documented.
We could in future add new features that read more data but these would be opt-in.

> If we could override that always without side effects, it would be preferrable

It should be possible already to customize the build to provide input information to Source Link. You'd probably want to override `InitializeSourceControlInformationFromSourceControlManager` target, which determines what the repository root by looking for the `.git` directory. It adds `SourceRoot` items with items that represent the repo and any submodules in it. See https://github.com/dotnet/sourcelink/blob/main/src/Microsoft.Build.Tasks.Git/LocateRepository.cs#L27-L37.

To get to parity with Source Link reading info from git data, you'd also need to override target `SetEmbeddedFilesFromSourceControlManagerUntrackedFiles` that populates `EmbeddedFiles` using info from `.gitignore`.
Not sure where would you find this information though.

**Comment by premun** [comment]
This has been resolved by making the caller of the build scripts to provide the SHA and URL
