### ISSUE TITLE
init-tools fails on fresh checkout

### ISSUE THREAD

**Issue by stevedesmond-ca** [dotnet/source-build#336]
Steps to reproduce:
- check out a fresh copy of this repo on a clean Ubuntu 16.04 VM
- run `./build.sh`

Expected result:
- build completes successfully

Observed result:
- submodules are all checked out, but the init-tools step fails with the following:
```
~/source-build/packages/microsoft.dotnet.buildtools/2.0.0-servicing-02312-03/lib/tool-runtime/project.csproj : error NU1102: Unable to find package Microsoft.Net.Compilers.netcore with version (>= 2.6.0-beta1-62126-01)
~/source-build/packages/microsoft.dotnet.buildtools/2.0.0-servicing-02312-03/lib/tool-runtime/project.csproj : error NU1102:   - Found 24 version(s) in https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json [ Nearest version: 1.3.1-beta1-20160616-03 ]
~/source-build/packages/microsoft.dotnet.buildtools/2.0.0-servicing-02312-03/lib/tool-runtime/project.csproj : error NU1102:   - Found 22 version(s) in https://dotnet.myget.org/F/dotnet-core/api/v3/index.json [ Nearest version: 1.3.1-beta1-20160616-03 ]
~/source-build/packages/microsoft.dotnet.buildtools/2.0.0-servicing-02312-03/lib/tool-runtime/project.csproj : error NU1102:   - Found 13 version(s) in nuget.org [ Nearest version: 2.0.0-rc4 ]
  Generating MSBuild file ~/source-build/packages/microsoft.dotnet.buildtools/2.0.0-servicing-02312-03/lib/tool-runtime/obj/project.csproj.nuget.g.props.
  Restore failed in 2.51 sec for ~/source-build/packages/microsoft.dotnet.buildtools/2.0.0-servicing-02312-03/lib/tool-runtime/project.csproj.
```

My guess is that something is using a private/non-standard package feed that's not included in the this repo's `NuGet.Config`?

**Comment by stevedesmond-ca** [comment]
Debugging update: the myget feeds have correct versions, but some reason it's not getting picked up. Local caching? 😑

**Comment by stevedesmond-ca** [comment]
Yep, clearing local nuget cache fixed it.

**Comment by stevedesmond-ca** [comment]
I'm continuing to hit this, even after wiping `~/.nuget` and or `source-build/packages`.

**Comment by stevedesmond-ca** [comment]
Some additional debugging that may help:

When I manually call `~/source-build/Tools/dotnetcli/dotnet restore "~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj"` the restore succeeds as expected.

The `init-tools.sh` script is passing in 3 `--source`s: `~/source-build/Tools/dotnetcli/dotnet restore "~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json`

```bash
  Restoring packages for ~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj...
~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj : error NU1102: Unable to find package Microsoft.Net.Compilers.netcore with version (>= 2.6.0-beta3-62316-02)
~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj : error NU1102:   - Found 24 version(s) in https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json [ Nearest version: 1.3.1-beta1-20160616-03 ]
~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj : error NU1102:   - Found 22 version(s) in https://dotnet.myget.org/F/dotnet-core/api/v3/index.json [ Nearest version: 1.3.1-beta1-20160616-03 ]
~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj : error NU1102:   - Found 13 version(s) in nuget.org [ Nearest version: 2.0.0-rc4 ]
  Restore failed in 2.38 sec for ~/source-build/packages/microsoft.dotnet.buildtools/2.1.0-preview1-02431-03/lib/tool-runtime/project.csproj.
```

Not sure if these are what's causing it to fail or not, but at least I seem to have a reproducible workaround for now...

**Comment by dagood** [comment]
I'm not able to repro in a Docker container with this command:

```
docker run --rm microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-coredeps-d770b8b-20180323032224 \
  bash -c 'git clone https://github.com/dotnet/source-build; cd source-build; ./init-tools.sh'
```

That image is from this pretty simple Dockerfile, just installing some prereqs: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/ubuntu/16.04/coredeps/Dockerfile. Not sure what's happening in your case, but trying that same Docker command might help eliminate some potential reasons for the failure.

**Comment by omajid** [comment]
I am not able to reproduce on a fresh clone of the the `dev/release/2.1` branch on Fedora either with a simple `./build.sh`.

**Comment by stevedesmond-ca** [comment]
Confirmed fixed with the latest version of BuildTools
