### ISSUE TITLE
Release pipeline: SB tagging pattern not compatible with installer tagging

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3376]
Because the [SB tagging pattern now uses the runtime version](https://github.com/dotnet/source-build/pull/3321), this is different than the installer repo's tagging pattern (based on the SDK version). This difference causes incompatibility in the [tagging validation](https://github.com/dotnet/source-build/blob/2c32505fda133f677d07ddc66e751e4010c11a10/eng/templates/stages/release.yml#L181-L203) that occurs in the release pipeline. It's comparing the runtime version to the SDK version which is obviously not going to match.

[Example build link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2147525&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=6d20ecd5-829b-5d5e-8095-acf3eddfc277) (internal only)

**Comment by premun** [comment]
I believe this one doesn't happen in main but only happened in `dev/mthalman/release` branch which was based on `11a3223cf1f50a2551c5b0cf87d6b8672093e798` and not on top of main which already had some fixes such as this one: https://github.com/dotnet/source-build/commit/4cd2965e63aa2d23112c4bb03282a4e905977a6f
