### ISSUE TITLE
Release pipeline: Incorrect content in generated announcement

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3377]
The announcement generated by the release pipeline has the following incorrect content:

* `RELEASE_CHANNEL` is not resolved as a variable. It's inserted literally as `RELEASE_CHANNEL` in the content.
* For servicing release:
  * Tag URLs reference https://github.com/dotnet/dotnet instead of https://github.com/dotnet/installer.

For an example of this, you can see the history of the post at https://github.com/dotnet/source-build/discussions/3368.

**Comment by premun** [comment]
The tag URL is a real mystery to me. I can see the announcement text here correct:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2155290&view=logs&j=3a04dffd-22cf-5707-fa41-9bd4708cc1db&t=b8061e11-088f-53b6-e12b-b3c826bcd3af&l=79

Then, when creating the announcement, the variables that are filled in the template are outputted again: https://dev.azure.com/dnceng/internal/_build/results?buildId=2155290&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=a83d7a9e-2e19-5733-3923-52a07f576962&l=136
which comes from here:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2155290&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=a83d7a9e-2e19-5733-3923-52a07f576962&l=53

Both seem correct so I have no idea how `dotnet/installer` got its way in..

**Comment by premun** [comment]
Oh, I see, the `dev/mthalman/release` branch was based on `11a3223cf1f50a2551c5b0cf87d6b8672093e798` and not on top of main which already had some fixes such as this one: https://github.com/dotnet/source-build/commit/4cd2965e63aa2d23112c4bb03282a4e905977a6f

**Comment by mthalman** [comment]
> Oh, I see, the `dev/mthalman/release` branch was based on `11a3223cf1f50a2551c5b0cf87d6b8672093e798` and not on top of main which already had some fixes such as this one: [4cd2965](https://github.com/dotnet/source-build/commit/4cd2965e63aa2d23112c4bb03282a4e905977a6f)

I'm not seeing what you're seeing.

![image](https://user-images.githubusercontent.com/15789599/232521402-43d67b51-a10a-4149-8784-22582be54b5a.png)

**Comment by premun** [comment]
This is now fixed ([example pipeline](https://dev.azure.com/dnceng/internal/_build/results?buildId=2161182&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=a83d7a9e-2e19-5733-3923-52a07f576962&l=35))
