### ISSUE TITLE
Release pipeline: Incorrect URL to 8.0 preview release notes in announcement

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3379]
The release announcement created by the release pipeline for the 8.0 Preview 3 release generated a link to the release notes. It referenced this URL which does not exist: https://github.com/dotnet/core/blob/main/release-notes/RELEASE_CHANNEL/8.0.0-preview.3.23174.8/8.0.100-preview.3.23178.7.md. The correct URL is https://github.com/dotnet/core/blob/main/release-notes/8.0/preview/8.0.0-preview.3.md. See the history of the post at https://github.com/dotnet/source-build/discussions/3370.

**Comment by premun** [comment]
This will require the build number that we will need to create as another input as part of https://github.com/dotnet/source-build/issues/3382
