### ISSUE TITLE
Release pipeline: JSON in release announcement not relevant to VMR

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3380]
When the release pipeline generates a release announcement, it includes JSON to describe state of the release. One of the fields is `InstallerTag`. This refers to the https://github.com/dotnet/installer repo which is relevant for 8.0 releases whose source is in https://github.com/dotnet/dotnet.

Personally, I think the name of the field shouldn't be repo-specific. I think something like this would be more appropriate:

```json
"RepoTag": "https://github.com/dotnet/dotnet/releases/tag/v8.0.100-preview.3.23178.7"
```

This same field name could then be used for 6.0/7.0 servicing builds with a field value that references `installer` instead.

**Comment by premun** [comment]
Is this a change we need to communicate to the partners as they rely on this name?

**Comment by MichaelSimons** [comment]
> Is this a change we need to communicate to the partners as they rely on this name?

Yes, we should call it out in the monthly release announcement.
