### ISSUE TITLE
Release pipeline: Build number should be excluded from announcement title for preview releases

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3382]
The title of the release announcement that was generated by the release pipeline for the .NET 8 Preview 3 release was `.NET 8.0 Preview 3 April 2023 Update - .NET 8.0.0-preview.3.23174.8 and SDK 8.0.100-preview.3.23178.7`. It seems that we should be excluding the build number from this title. The expected title would be `.NET 8.0 Preview 3 April 2023 Update - .NET 8.0.0-preview.3 and SDK 8.0.100-preview.3`

**Comment by premun** [comment]
I think this will require a new input as we don't have these build-number-less versions available anywhere
