### ISSUE TITLE
Implement a mechanism to test the release pipeline

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3387]
The release pipeline is a critical piece of infrastructure.  The tolerance for issues within it are very low.   Having issues with the release can prevent customers from picking up security fixes and can erode trust.  Given the importance of this infrastructure, it is critical that we have a means to fully test the release pipeline without having to perform an actual release.

Today we utilize a notion of a "dry run" which runs as much of the pipeline logic as possible without "releasing" artifacts.  While this is good, it does not run the entire logic and therefore does not detect all issues within the pipeline.

We should consider a mechanism that will support "test runs" which utilize test locations.  In essence we swap out the real "destinations" with internal testing/sandbox locations.  This is theory will allow us to fully test the full pipeline.

**Comment by MichaelSimons** [comment]
cc @tkapin, @premun

**Comment by premun** [comment]
I agree that this is a superior approach and that this would be the proper solution to the reliability issues we're facing.

**Comment by MichaelSimons** [comment]
[Triage] cc @tkapin, @premun, Is this something someone from your team would be interesting in implementing?  If so what would be a reasonable timeframe we could expect this in?

**Comment by premun** [comment]
@MichaelSimons @mthalman @tkapin I am not very happy with how I'm doing with the release pipeline as originally I just quickly put a couple of pipelines and tools together but then we added few more capabilities and together with the fact that we also want to be able to re-run the pipeline idempotently and asking it to handle both 6.0/7.0 and 8.0, things are getting a bit complicated. I think this just speaks more to the fact that we should prioritize this issue but not until we have critical issues resolved for Preview 4.

I estimate this to be somewhere between 2 weeks and a month of work and I would like to see the following features:
- Equal staging and production environments that we would target. This means things like
    - Storage accounts
    - Staging VMRs (?)
    - A private fake "installer" repo for creation of PRs, discussions and announcements
- A PR build for `dotnet/source-build` which would not depend on the stage pipeline but get some dummy metadata injected
    - Testing the changes is the most cumbersome and time consuming part
- More reliable pipeline data initialization
    - Similarly to the stage where we load release config and associated pipelines, we need to initialize quite a lot of state which is exported as pipeline variables - I imagine we would like to solidify this critical piece and make it testable

**Comment by premun** [comment]
I am closing this as we logged a full epic for this - https://github.com/dotnet/arcade-services/issues/2668

**Comment by tkapin** [comment]
@MichaelSimons, feel free to re-open this if you want to keep this as tracking issue for yourself.
