### ISSUE TITLE
Differences in required test baseline files between stage 1 and stage 2 builds

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3389]
The release of 6.0.116 exposed an issue in the tests that make use of baseline files. That release caused a need to update the [MissingXmlDoc.txt](https://github.com/dotnet/installer/pull/16087/files#diff-fe8d3b96fa865e835a206acf8e1cd6bbb58a3f7760d12ba2ad58514bc78767f3) baseline file to include a new entry. But updating that file then caused the corresponding `VerifyTargetingPacksHaveDoc` test to fail in the [stage 2 build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2158110&view=results) (internal link) because the XML file was _not_ missing in that build. So there's a difference in the output of the stage 1 and stage 2 build such that a single baseline file cannot describe the expected output of both scenarios.

This is expected to occur for other baseline files such as SDK diff and poison leaks. We should have a general solution that can apply to all these baseline file types.

One potential solution for this is to have two baseline files: one for the stage 1 build and the other for the stage 2 build. The pipeline would indicate which one to use via an environment variable. The baseline for the stage 2 build could be optionally such that if it does not exist, the test falls back to the stage 1 baseline.

**Comment by MichaelSimons** [comment]
@mthalman - Is this issue still relevant?

1. XmlDocTests were removed from all supported branches (https://github.com/dotnet/source-build/issues/3031)
2. PoisonTests baseline is intended to be empty.  Only reason for entries is temporary and we should not be releasing with leaks
3. SdkContentTests now only run against stage 1 legs


#2 and #3 can affect servicing branches but IIRC they haven't been problematic.  It was really #1 that prompted this issue.

**Comment by mthalman** [comment]
The only known occurrence of this issue currently is SDK content diff in servicing. It's fine to ignore that for servicing.
