### ISSUE TITLE
Update release_checklist to account for new source-build-sdk-diff-tests pipeline

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3408]
The [release checklist](https://github.com/dotnet/source-build/blob/main/.github/ISSUE_TEMPLATE/releases/release_checklist.md) needs to be updated for new [source-build-sdk-diff-tests pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=1231&_a=summary)(internal Microsoft link).  The SdkContentTests are no longer being run as part of the primary CI.

**Comment by MichaelSimons** [comment]
[Triage] - For .NET 8.0 the release checklist needs updating.  The new pipeline fails on diffs which is the ideal behavior.  We should be monitoring that build and it should be green as part of our release ready criteria.

**Comment by premun** [comment]
I have thought about this some time ago and if we believe we can get the pipeline green, it would be trivially easy to look up the associated pipeline in the `Get Associated Builds` step like so:
https://github.com/premun/source-build/commit/b35927f003ee9ea87261816f9fc4b2e8299be355

Then it's a matter of checking the `Verify associated pipeline runs` to make sure it's green as well.

I never merged this as the pipeline is red always though.

**Comment by premun** [comment]
In case we'll decide to keep it manual, @mthalman you can include in the steps the pipeline can be found by tag which contains the installer SHA tied with the release.

We could also just print the build in the `Get Associated Builds` step and make the instructions point you to the link from there. Just for convenience. We would then make it not require the build to pass always.
