### ISSUE TITLE
Generator 'RazorSourceGenerator' failed to generate source

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3410]
The BlazorWasm test surfaces an issue with the RazorSourceGenerator.  It appears that is has bundled an SBRP package with it and is trying to execute code from it.

```
CSC : warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'BadImageFormatException' with message 'Could not load file or assembly 'Microsoft.Extensions.ObjectPool, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies cannot be loaded for execution. (0x80131058)' [/repos/dotnet/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202304210321071372/WebScenarioTests_BlazorWasm_CSharp/WebScenarioTests_BlazorWasm_CSharp.csproj] [/repos/dotnet/build.proj]
```

The BlazorWasm WebScenarioTests will need re-enabling once this issue is resolved.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - I see a source-build patch was introduced for this that references this issue as the backport.  I am not finding the actual backport issue/PR to Razor.  Can you link that here from traceability?  TIA  Ideally that is the issue/PR that would be linked to in the patch.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic - I see a source-build patch was introduced for this that references this issue as the backport. I am not finding the actual backport issue/PR to Razor. Can you link that here from traceability? TIA Ideally that is the issue/PR that would be linked to in the patch.

Working on `razor` PR right now - will open the issue as well and link to the main issue in `source-build`.

**Comment by NikolaMilosavljevic** [comment]
Backport PR: https://github.com/dotnet/razor/pull/8657
