### ISSUE TITLE
Package mirroring is running out of disk space

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3413]
Due to an ongoing incident (https://github.com/dotnet/arcade/issues/13036) with VMs from the 1ES pool with the `1es-ubuntu-2004` image we're using for the release pipeline, we're unable to download packages to mirror them.

We cannot switch over to the .NET images (e.g. `Build.Amd64.Ubuntu.2004`) because it's missing tools such as `gh`, `jq` and others.

**Comment by premun** [comment]
cc @mthalman

**Comment by mthalman** [comment]
Duplicate of https://github.com/dotnet/source-build/issues/3381

**Comment by premun** [comment]
Ah, apologies. Closing in favour of #3381
