### ISSUE TITLE
SourceLink build.sh options should not be required when running smoke-tests

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3419]
Changes in https://github.com/dotnet/installer/pull/16184 regressed the `./build.sh --run-smoke-test` usage scenario outside of a git repo.  The sourcelink options are now required.

This is breaking [internal CI](https://dev.azure.com/dnceng/internal/_build/results?buildId=2166871&view=results).

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/installer/pull/16241
