### ISSUE TITLE
Release pipeline: `mono` executable error when mirroring NuGet packages

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3423]
This error is showing up in the `Publish packages` task:

```
##[error]Error: Unable to locate executable file: 'mono'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

[Build link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2167811&view=logs&j=b6422d7d-1f12-5a27-5bca-0651b2848f2b&t=3ad0151c-6c6b-5312-5ed6-a86e6bc28020) (internal)

Presumably, this is because of the [change in the agent type](https://github.com/dotnet/source-build/pull/3414) which doesn't include the required `mono` executable.

Additionally, I don't think this task should be configured to continue on error. If it fails, we want the pipeline to have an error.

**Comment by mthalman** [comment]
Just installing mono isn't enough. It requires other packages as well. Otherwise, leads to this error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x000e3] in <dc1b484fc03b4c9e94db6d2032a7a13d>:0 
```

**Comment by premun** [comment]
@mthalman have you also tried to call the `NuGet authenticate` step? I believe that one gives the build access to feeds in the same AzDO organization.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v1?view=azure-pipelines

**Comment by mthalman** [comment]
> @mthalman have you also tried to call the `NuGet authenticate` step? I believe that one gives the build access to feeds in the same AzDO organization.

I tried that but it didn't help.

**Comment by mthalman** [comment]
According to the service connection description, it uses the `dn-bot-all-orgs-artifact-feeds-rw` secret. @premun - Can you confirm this is not expired?

**Comment by premun** [comment]
Will do. Btw @mthalman we've talked with Tomas that we might give Ali the task of onboarding source-build onto secret manager. Might be worth since this is a second time there's a token problem.

**Comment by premun** [comment]
Ah, so the token is not expired but was rotated without support for the `dotnet-security-partners` organization. Same as the last time we saw this issue (not sure it was the same token?).
