### ISSUE TITLE
CS1503 error in runtime during stage 2 build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3425]
The following stage 2 build error is occurring in the [internal CI](https://dev.azure.com/dnceng/internal/_build/results?buildId=2167942&view=results).

```
    /vmr/src/runtime/artifacts/source-build/self/src/src/libraries/System.Runtime.InteropServices/gen/ComInterfaceGenerator/InlinedTypes.cs(56,49): error CS1503: Argument 1: cannot convert from 'Microsoft.CodeAnalysis.SeparatedSyntaxList<Microsoft.CodeAnalysis.SyntaxNode>' to 'Microsoft.CodeAnalysis.SeparatedSyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax>' [/vmr/src/runtime/artifacts/source-build/self/src/src/libraries/System.Runtime.InteropServices/gen/ComInterfaceGenerator/ComInterfaceGenerator.csproj]
```

This smells similar to the problem this patch was addressing - https://github.com/dotnet/installer/commit/b9688fbc325c2a04a2f1ca61c70f1f7596611553#diff-3fa487719813beaa4214c99ecc5933d5f38dd5a0e99c27cb3e156625bd00a0ff

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/installer/pull/16262
