### ISSUE TITLE
Offline build support needed

### ISSUE THREAD

**Issue by xgqt** [dotnet/source-build#3432]
Hello!

The Gentoo team attempts to package .NET from-source-build for the Gentoo Linux distribution.
We have encountered many problems with achieving our goal and the most prominent are the ones related to making the dotnet build requiring constant use of the network.

Could you give a example workflow (if possible) that could satisfy our need?
We can not use the network during build and the only time where it is allowed is for downloading a **predefined** set of tarballs/artifacts before the build.

See also:
- https://github.com/gentoo/gentoo/pull/21112
- https://bugs.gentoo.org/900597

**Comment by mid-kid** [comment]
This repository allows building a source tarball, that once built contains everything the compiler needs to bootstrap itself. See: https://src.fedoraproject.org/rpms/dotnet5.0/blob/rawhide/f/build-dotnet-tarball

Also, you're in the wrong repository for anything 6.0+. This repository only goes up to 5.0.

**Comment by xgqt** [comment]
> This repository allows building a source tarball, that once built contains everything the compiler needs to bootstrap itself. See: https://src.fedoraproject.org/rpms/dotnet5.0/blob/f35/f/build-dotnet-tarball
> 
> Also, you're in the wrong repository for anything 6.0+. This repository only goes up to 5.0.

Thanks a lot! I will look into the Fedora's solution.

**Comment by MichaelSimons** [comment]
@xgqt - We support offline builds, see the instructions at https://github.com/dotnet/installer/blob/main/README.md#build-net-from-source-source-build.  Note we are making a lot of investments in .net Source Build and things will be changing some in the next version (.NET 8.0).

**Comment by xgqt** [comment]
I had successfully compiled dotnet from ebuild. Installer's README was indeed helpful but I couldn't get it to build on latest 7.0.X tag, I used the same version number as packaged in Fedora, that is 7.0.105.
