### ISSUE TITLE
Microsoft.CodeAnalysis prebuilts in aspnetcore

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3434]
[Latest internal CI build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2178324&view=results) is reporting a number of Microsoft.CodeAnalysis prebuilts coming from aspnetcore.

```
Microsoft.CodeAnalysis.Analyzers.3.3.3
Microsoft.CodeAnalysis.Common.4.5.0
Microsoft.CodeAnalysis.CSharp.4.5.0
```

Looks like new SBRPs are needed.  When fixing a follow-up is to determine why these were not caught within the aspnetcore repo's source build leg that has prebuilt detection enabled.

**Comment by mthalman** [comment]
Caused from the changes in https://github.com/dotnet/aspnetcore/pull/48179.

**Comment by mthalman** [comment]
Corresponding PR in aspnetcore to clean up prebuilt baseline: https://github.com/dotnet/aspnetcore/pull/48212

**Comment by eerhardt** [comment]
Do we also need this line for aspnetcore now?

https://github.com/dotnet/installer/blob/6a56c14821feb79f515315895c9a70b3ab8658a6/src/SourceBuild/content/repo-projects/runtime.proj#L46

We only have these 2:

https://github.com/dotnet/installer/blob/6a56c14821feb79f515315895c9a70b3ab8658a6/src/SourceBuild/content/repo-projects/aspnetcore.proj#L44-L45

We are trying to follow the same pattern for our Source Generator as what the runtime repo does.

**Comment by mthalman** [comment]
Yeah, I think so. You still need to be pinned to an older version due to the mismatch between the SDK version in the aspnetcore repo versus the installer repo, unfortunately.
