### ISSUE TITLE
Ensure changes to repo level source-build files are code reviewed by source-build experts

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3435]
Here is an [example change](https://github.com/dotnet/aspnetcore/pull/48179/files) that should have been reviewed by a source-build expert.  The changes to the SourceBuildPrebuiltBaseline.xml caused prebuilts to be added and weren't caught until internal source-build CI.

Suggestions:

1. Add comments to the repo level source-build files to promote having a source-build expert code review any changes
2. If a repo has a CODEOWNERS file, assign ownership of the repo level source-build files to the source-build team to ensure they get included in code reviews.

Repos with comments only:

 - [x] sourcelink: https://github.com/dotnet/sourcelink/pull/1038
 - [x] arcade: https://github.com/dotnet/arcade/pull/13740
 - [x] command-line-api: https://github.com/dotnet/command-line-api/pull/2204
 - [x] emsdk: https://github.com/dotnet/emsdk/pull/353
 - [x] xliff-tasks: https://github.com/dotnet/xliff-tasks/pull/793
 - [x] cecil: https://github.com/dotnet/cecil/pull/88
 - [x] runtime: https://github.com/dotnet/runtime/pull/87003
 - [x] symreader: https://github.com/dotnet/symreader/pull/290
 - [x] xdt: https://github.com/dotnet/xdt/pull/516
 - [x] msbuild: https://github.com/dotnet/msbuild/pull/8824
 - [x] aspnetcore: https://github.com/dotnet/aspnetcore/pull/48566
 - [x] deployment-tools: https://github.com/dotnet/deployment-tools/pull/279
 - [x] templating: https://github.com/dotnet/templating/pull/6660
 - [x] nuget-client: https://github.com/NuGet/NuGet.Client/pull/5196
 - [x] test-templates: https://github.com/dotnet/test-templates/pull/305
 - [x] sdk: https://github.com/dotnet/sdk/pull/32966

Repos with both the comments and `CODEOWNERS` entry:
 - [x] source-build-reference-packages: https://github.com/dotnet/source-build-reference-packages/pull/690
 - [x] source-build-externals: https://github.com/dotnet/source-build-externals/pull/153
 - [x] diagnostics: https://github.com/dotnet/diagnostics/pull/3934
 - [x] razor: https://github.com/dotnet/razor/pull/8787
 - [x] roslyn: https://github.com/dotnet/roslyn/pull/68409
 - [x] roslyn-analyzers: https://github.com/dotnet/roslyn-analyzers/pull/6666
 - [x] format: https://github.com/dotnet/format/pull/1869
 - [x] fsharp: https://github.com/dotnet/fsharp/pull/15288
 - [x] vstest: https://github.com/microsoft/vstest/pull/4503
 - [x] instaler: https://github.com/dotnet/installer/pull/16550

**Comment by MichaelSimons** [comment]
[This is an example](https://github.com/microsoft/vstest/pull/4486) of a change we should be reviewing.  These prebuilts should have been added to SBRP.

**Comment by MichaelSimons** [comment]
@oleksandr-didyk - FYI, It looks like a few repos are missing from the tracking list.  There are 26 repos that participate in source-build.

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk - FYI, It looks like a few repos are missing from the tracking list. There are 26 repos that participate in source-build.

The list contains 24 + I omitted SBRP and externals as changes to them would get reviewed by us anyways. With them its 26, or did I miss some?

**Comment by MichaelSimons** [comment]
> > @oleksandr-didyk - FYI, It looks like a few repos are missing from the tracking list. There are 26 repos that participate in source-build.
> 
> The list contains 24 + I omitted SBRP and externals as changes to them would get reviewed by us anyways. With them its 26, or did I miss some?

IMO we should still update the two source-build repos for reference purposes (referring to the comments at the top of the source-build files, not CODEOWNERS).  Our repos are a reference for others to see how to implement source-build.

**Comment by MichaelSimons** [comment]
> Is it worth asking the repo maintainers for this for the 2 files we currently have?

[Triage] - We feel like that we should try and get access if repo owners are willing as this is the best way to ensure source-build experts are included in code reviews.  If there is resistance/pushback, then we will drop the request to change CODEOWNERS.

**Comment by MichaelSimons** [comment]
FYI - It appears that you cannot grant access or mention teams cross organization boundaries.  So repos like vstest that reside in the Microsoft organization can't assign source-build-internal as a CODEOWNER.

**Comment by mthalman** [comment]
> FYI - It appears that you cannot grant access or mention teams cross organization boundaries. So repos like vstest that reside in the Microsoft organization can't assign source-build-internal as a CODEOWNER.

In that case, I suppose we could use individual usernames instead?

**Comment by MichaelSimons** [comment]
> In that case, I suppose we could use individual usernames instead?

I have thought about it but it is a maintenance concern and opted not to for now.  Let's see how effective the comment is.  If it remains a problem then we should use individuals.

**Comment by oleksandr-didyk** [comment]
`SourceBuild*` files in all 26 repos have the comment review added; where possible entries to `CODEOWNERS` for applicable files has been added

Closing as done
