### ISSUE TITLE
[SBRP] Add packages required by fsharp

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3437]
With https://github.com/dotnet/fsharp/issues/15166, we are allowing the following prebuilts in `fsharp`:
```
    <UsagePattern IdentityGlob="System.Diagnostics.DiagnosticSource/7.0.2" />
```

The following are expected and will go away when `fsharp` starts targeting net8.0:
```
    <UsagePattern IdentityGlob="Microsoft.AspNetCore.App.Ref/7.0.2" />
    <UsagePattern IdentityGlob="Microsoft.NETCore.App.Host.linux-x64/7.0.2" />
    <UsagePattern IdentityGlob="Microsoft.NETCore.App.Ref/7.0.2" />
```

**Comment by MichaelSimons** [comment]
We don't want to add the 7.0.2 targeting pack.  We already have the 7.0.0 targeting pack which is what SBRP uses to build 7.0 tfms.  The  <UsagePattern IdentityGlob="Microsoft.NETCore.App.Ref/7.0.2" /> in fsharp is because they still target net7.0 which will have be be addresses before we release.

**Comment by NikolaMilosavljevic** [comment]
Should this be closed and comment updated in `fsharp` PR? https://github.com/dotnet/fsharp/pull/15209

**Comment by MichaelSimons** [comment]
The only one I don't know about is System.Diagnostics.DiagnosticSource/7.0.2.   That would be a validate assembly to add to SBRP.

**Comment by MichaelSimons** [comment]
The rest should have an updated comment in the prebuilt baseline to reference the net8.0 upgrade issue.
