### ISSUE TITLE
[Prebuilts] New prebuilt in fsharp's source-build leg

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3438]
The following prebuilt shows up in `fsharp` branch `release/dev17.7`. This was noticed during prebuilts work for that repo: https://github.com/dotnet/fsharp/issues/15166

`    <UsagePattern IdentityGlob="Microsoft.VisualStudio.Setup.Configuration.Interop/3.2.2146" />`

This only shows in repo's source-build leg and will go away when `fsharp` starts using 8.0 SDK.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic, this issue feels like something that should be moved to the fsharp repo.  I can't transfer it because I don't have write access in fsharp.  Can you please re-open in fsharp?  TIA.

**Comment by ViktorHofer** [comment]
Was there an issue filed in fsharp for it? Asking as the SourceBuildPrebuiltBaseline.xml still links to this one: https://github.com/dotnet/fsharp/blob/28186895726a4b323b842a4426e6fbe8bc222182/eng/SourceBuildPrebuiltBaseline.xml#L25

Btw, are these also still required? https://github.com/dotnet/fsharp/blob/28186895726a4b323b842a4426e6fbe8bc222182/eng/SourceBuildPrebuiltBaseline.xml#L11-L19 The tracking issue got closed.
