### ISSUE TITLE
Release pipeline: Use of announcement gist results in `TAG_URL` variable not being set

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3447]
The release pipeline allows you the option of referencing a [gist URL](https://github.com/dotnet/source-build/blob/d4f497340a69a09d6cb58b7fd8eba5a8cc27c74e/eng/source-build-release-official.yml#L72-L75) that will be used as the content for the release announcement instead of automatically generating it. When that parameter is provided, it results in the following error when executing the [`Submit announcement discussion` task](https://github.com/dotnet/source-build/blob/d4f497340a69a09d6cb58b7fd8eba5a8cc27c74e/eng/templates/stages/release.yml#L249-L317) in the release stage:

```
line 62: TAG_URL: unbound variable
```

This is because that variable only gets set as a result of running the [`create-announcement-draft.sh` script](https://github.com/dotnet/source-build/blob/d4f497340a69a09d6cb58b7fd8eba5a8cc27c74e/eng/create-announcement-draft.sh). But that script doesn't get run when an announcement gist URL is provided.

The same applies for the use of the `RELEASE_NOTES_URL` variable.

**Comment by ali-turan7** [comment]
TAG_URL and RELEASE_NOTES_URL variables are removed from being printed in release.yml
