### ISSUE TITLE
Release pipeline: Duplicate announcement discussion posted

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3450]
In some cases, it is necessary to run the release stage multiple times, such as when there is an error at some point in the stage that requires a retry or workaround. In such a scenario, if the [`Submit announcement discussion` step](https://github.com/dotnet/source-build/blob/d4f497340a69a09d6cb58b7fd8eba5a8cc27c74e/eng/templates/stages/release.yml#L249-L317) has already been executed from a previous run of the pipeline, it will cause a duplicate announcement to be posted.

My expectation is that it should skip posting the announcement since it already exists and output a warning message instead.

**Comment by ali-turan7** [comment]
Description:
Duplication has been avoided by determining whether or not an anncoment with the identical title already exists.

Test:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2190080&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=a83d7a9e-2e19-5733-3923-52a07f576962
In addition, the code has been checked in the test repository. https://github.com/ali-turan7/test/discussions

**Comment by premun** [comment]
This has been completed by #3482
