### ISSUE TITLE
VMR build failure for nuget-client repo

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3467]
```
  /vmr/.dotnet/sdk/8.0.100-preview.4.23260.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1275,3): error MSB4019: The imported project "/vmr/.dotnet/sdk/8.0.100-preview.4.23260.1/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets" was not found. Confirm that the expression in the Import declaration ";/vmr/.dotnet/sdk/8.0.100-preview.4.23260.1/Sdks/Microsoft.NET.Sdk/targets/../../Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets" is correct, and that the file exists on disk. [/vmr/src/nuget-client/src/NuGet.Clients/NuGet.Console/NuGet.Console.csproj]
```

This was introduced by something within the range of these commits: https://github.com/dotnet/dotnet/commit/85b801612ad392328eae4ec322bdccc85ada8e31 and https://github.com/dotnet/dotnet/commit/aecc50daa66f0db0f162a2138ac161e47b23109f.

This occurs in the CentOSStream8_Online_PreviousSourceBuiltSdk_x64 build leg.

**Comment by mthalman** [comment]
This is affecting the NuGet.Console and NuGet.PackageManagement.UI projects. I'm fairly certain this is caused by https://github.com/NuGet/NuGet.Client/pull/5167. With that, my guess is that the Arcade shim we have for nuget-client is now picking up these converted projects and building them since it wasn't doing that previously. Since these are WPF projects, it leads to the failure. I did try setting `ExcludeFromSourceBuild` but that didn't seem to have an effect. This is maybe because that `ExcludeFromSourceBuild` property isn't integrated properly with the Arcade shim? I need to investigate more.

**Comment by MichaelSimons** [comment]
This issue has been fixed in nuget.client and source-build is carrying a patch until the updated nuget.client flows in.
