### ISSUE TITLE
ILMerge version not found while building VMR main

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#3472]
I'm building vmr main (at 2e71a23ab11c8480aa28ad959656dceb4020760c).

The build fails with:
```
  /home/tmds/repos/dotnet/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1102: Unable to find package ILMerge with version (>= 3.0.41) [/home/tmds/repos/dotnet/src/nuget-client/build/restorehelper.targets]
  /home/tmds/repos/dotnet/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1102:   - Found 1 version(s) in prebuilt [ Nearest version: 3.0.21 ] [/home/tmds/repos/dotnet/src/nuget-client/build/restorehelper.targets]
  /home/tmds/repos/dotnet/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1102:   - Found 0 version(s) in source-built [/home/tmds/repos/dotnet/src/nuget-client/build/restorehelper.targets]
  /home/tmds/repos/dotnet/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1102:   - Found 0 version(s) in previously-source-built [/home/tmds/repos/dotnet/src/nuget-client/build/restorehelper.targets]
  /home/tmds/repos/dotnet/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1102:   - Found 0 version(s) in reference-packages [/home/tmds/repos/dotnet/src/nuget-client/build/restorehelper.targets]
```

Is it expected for the `main` branch to not be buildable? And what can I do about it?

cc @MichaelSimons @omajid

**Comment by MichaelSimons** [comment]
This prebuilt comes from NuGet.Client and is tracked with https://github.com/NuGet/Home/issues/12604.  The prebuilts tarball was update in https://github.com/dotnet/installer/pull/16448 to include this but it looks like an updated dependency version flowed in.

@NikolaMilosavljevic - If you are not close to a solution, could you update the prebuilts tarball?  TIA.

**Comment by NikolaMilosavljevic** [comment]
> This prebuilt comes from NuGet.Client and is tracked with [NuGet/Home#12604](https://github.com/NuGet/Home/issues/12604). The prebuilts tarball was update in [dotnet/installer#16448](https://github.com/dotnet/installer/pull/16448) to include this but it looks like an updated dependency version flowed in.
> 
> @NikolaMilosavljevic - If you are not close to a solution, could you update the prebuilts tarball? TIA.

I'll update the tarball, to unblock the VMR build.

**Comment by tmds** [comment]
How do you obtain the ILMerge package? and create a new tarball?

**Comment by tmds** [comment]
I ran the `./build.sh` command without the `--online` argument. Would adding the argument have made a difference?

**Comment by NikolaMilosavljevic** [comment]
> I ran the `./build.sh` command without the `--online` argument. Would adding the argument have made a difference?

Yes, `--online` would have enabled the build to obtain packages from nuget.org and show them as warnings in your build, instead of errors.

**Comment by MichaelSimons** [comment]
> I ran the `./build.sh` command without the `--online` argument. Would adding the argument have made a difference?

Yes, the build will pass with an online build.  You can also retrieve the package from the online build to update the tarball.

**Comment by tmds** [comment]
Is it the expectation that the `main` branch is (occasionally) not working without the `--online` flag?
Or is the expected workflow to update the prebuilts as part of updating the `main` branch?

**Comment by MichaelSimons** [comment]
This was fixed by NuGet.Client in https://github.com/NuGet/NuGet.Client/pull/5178.  We added a [patch](https://github.com/dotnet/installer/blob/main/src/SourceBuild/patches/nuget-client/0002-Do-not-restore-ILMerge-in-source-build.patch) until the fix flows in.
