### ISSUE TITLE
Add test for self-contained

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#3485]
https://github.com/dotnet/installer/pull/16499 adds the runtime packs for .NET Core and ASP.NET Core.
This makes it possible for a source-build SDK to publish a self-contained application without needing packages from nuget.org.

This issue tracks adding a test for this.

cc @MichaelSimons @mthalman

**Comment by MichaelSimons** [comment]
[Triage] the changes coming in https://github.com/dotnet/source-build/issues/3386 will make it easier to validate the runtime packs are not pulled in from nuget.org during a self-contained test.
