### ISSUE TITLE
Ensure source-build tarball build can build offline

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#349]
Building the produced tarball should be possible when machine is offline.
CI for the Offline build should actually build offline.

Currently, building the tarball offline causes the following error:
`  /src/tarball-output/Tools/dotnetcli/sdk/2.1.1-preview-007094/NuGet.targets(103,5): error : Failed to download package 'NuGet.Packaging.4.3.0-preview3-4168' from 'https://api.nuget.org/v3-flatcontainer/nuget.packaging/4.3.0-preview3-4168/nuget.packaging.4.3.0-preview3-4168.nupkg'. [/src/tarball-output/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj] [/src/tarball-output/tools-local/init-build.proj]
  /src/tarball-output/Tools/dotnetcli/sdk/2.1.1-preview-007094/NuGet.targets(103,5): error : An error occurred while sending the request. [/src/tarball-output/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj] [/src/tarball-output/tools-local/init-build.proj]
  /src/tarball-output/Tools/dotnetcli/sdk/2.1.1-preview-007094/NuGet.targets(103,5): error : Couldn't resolve host name [/src/tarball-output/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj] [/src/tarball-output/tools-local/init-build.proj]
  /src/tarball-output/Tools/dotnetcli/sdk/2.1.1-preview-007094/NuGet.targets(103,5): error : Failed to retrieve information about 'NuGet.Packaging' from remote source 'https://api.nuget.org/v3-flatcontainer/nuget.packaging/index.json'. [/src/tarball-output/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj] [/src/tarball-output/tools-local/init-build.proj]
  /src/tarball-output/Tools/dotnetcli/sdk/2.1.1-preview-007094/NuGet.targets(103,5): error : An error occurred while sending the request. [/src/tarball-output/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj] [/src/tarball-output/tools-local/init-build.proj]
  /src/tarball-output/Tools/dotnetcli/sdk/2.1.1-preview-007094/NuGet.targets(103,5): error : Couldn't resolve host name [/src/tarball-output/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj] [/src/tarball-output/tools-local/init-build.proj]
  /src/tarball-output/tools-local/init-build.proj(29,5): error MSB3073: The command "/src/tarball-output/Tools/dotnetcli/dotnet build tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj" exited with code 1.`

**Comment by kasper3** [comment]
Is the fix for this going to be in this repo?
We can create a package for alpine using tarball once this is fixed.
CC @ncopa
