### ISSUE TITLE
NETSDK1195 error when building runtime in bootstrapping stage 2 build leg

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3490]
```
/vmr/.dotnet/sdk/8.0.100-preview.6.23301.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1195: Unable to optimize assemblies for size: a valid runtime package was not found. Either set the PublishTrimmed property to false, or use a supported target framework when publishing. [/vmr/src/runtime/artifacts/source-build/self/src/Build.proj]
```

Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2192289&view=logs&j=4cede3bc-29a7-5d91-52ef-402f98629c03&t=dd97ae34-3027-5020-e259-ff298adf2f8e (internal link)

**Comment by mthalman** [comment]
@sbomer - To investigate, here's the link for the [runtime binlog](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjE5MjI4OS9hcnRpZmFjdE5hbWUvRmVkb3JhMzZfT2ZmbGluZV9DdXJyZW50U291cmNlQnVpbHRTZGtfeDY0X0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fsrc%2Fruntime%2Fartifacts%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog).

**Comment by MichaelSimons** [comment]
The fix flowed in with https://github.com/dotnet/installer/pull/16621.
