### ISSUE TITLE
Release pipeline: Do not tag internal `dotnet-dotnet` repository during mirroring

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3496]
### Context

During the **Mirror** stage, we create a release in the internal `dotnet-dotnet` repository. This step actually doesn't have much effect because we never actually push that tag anywhere.
The tag in the GitHub public repo is created together when creating the release (gh release create ...) so it's an atomic operation provided by the GitHub CLI.
I don't think tags are synchronized between repos with the regular code mirroring so it could potentially happen the commit that is tagged differs between GH and AzDO.

### Goal

Remove the tagging.

### Question

1. The tags won't be mirrored from GitHub internally. Should we have a follow-up to mirror those?
2. Or should we instead just keep the tagging like it is and push the tag and not create it with the release? This way the tags would match always.

**Comment by oleksandr-didyk** [comment]
> Or should we instead just keep the tagging like it is and push the tag and not create it with the release? This way the tags would match always.

This is the state we are at with the changes introduced by https://github.com/dotnet/source-build/pull/3659, where both `mirror`ing and `release` stages tag the same VMR commit with the same tag and push it:
  - [`mirror`](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/eng/pipeline/source-build-release/stages/mirror.yml&version=GBmain&line=193&lineEnd=193&lineStartColumn=1&lineEndColumn=48&lineStyle=plain&_a=contents) to `dotnet-security-partners/dotnet`
  - [`release`](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/eng/pipeline/source-build-release/stages/release.yml&version=GBmain&line=119&lineEnd=119&lineStartColumn=1&lineEndColumn=78&lineStyle=plain&_a=contents) to public `VMR`
 
 Additionally, based on Matt's https://github.com/dotnet/source-build/issues/3652#issuecomment-1808403461 comment, we want to keep tagging for `dotnet-security-partners/dotnet`
 
Based on this I think this issue can be closed. Do you agree @premun ?

**Comment by premun** [comment]
If we are sure both repos are tagged the same then I guess we can close this

**Comment by oleksandr-didyk** [comment]
Issue for unifying the logic - https://github.com/dotnet/source-build/issues/3736

Closing as `Not planned` as the root of the problem was solved by a different task and follow-up work was logged in separately
