### ISSUE TITLE
Release pipeline: Source tarball should not be uploaded in Pre-Release stage

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3497]
### Context

For .NET 6.0/7.0, we upload the `.tar.gz` of sources to a storage account. This should happen in the mirroring stage rather than the pre-release stage.

### Goal

We should try to figure out why we do it like this and if there is no reason for it, move it into the mirroring stage.

**Comment by MichaelSimons** [comment]
[Triage] This is required for the testability.  We prefer to not make this before 8.0 GA in the public pipeline for stability reasons therefore this should be made in the new internal pipeline only.

**Comment by oleksandr-didyk** [comment]
Completed as part of https://github.com/dotnet/arcade-services/issues/2871
