### ISSUE TITLE
Document steps to build a source tarball from dotnet/installer

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#3498]
Before we had the vmr, we built a source tarball from dotnet/installer.
Now most of that is handled by automation and we get the resulting sources from the dotnet/dotnet repository.

When making some changes to the dotnet/installer repository, it can still be useful to turn those into a source tarball.

This is a request to document those steps.
Or maybe my understanding of how these pieces fit together is out-dated, and this request doesn't make sense.

cc @premun @MichaelSimons @omajid

**Comment by tmds** [comment]
My question isn't about creating a source tarball from dotnet/dotnet, but from dotnet/installer.

**Comment by premun** [comment]
Hey,

There are few ways to achieve this:

1. Initialize a new, fresh VMR from installer. This might be rusty but if you'd call  
     `./build.sh /p:InitializeVmr=true /p:VmrDir=/target-folder` from `dotnet/installer`  
    and it would initialize a new VMR. However, we don't really exercise this flow much. I see there's 2 missing parameters in [here](https://github.com/dotnet/installer/blob/3c72e0a511cdd7e85a3a35986d80345c5e43354e/src/VirtualMonoRepo/Tasks/VirtualMonoRepo_Initialize.cs#L58-L65) missing but that's an easy fix. 
2. Synchronize your new installer commit into an existing VMR (can be all done locally) via [vmr-sync.sh](https://github.com/dotnet/dotnet/blob/main/src/installer/eng/vmr-sync.sh). This is much safer and we run that dozens of time daily as it's used for the actual synchronization of `dotnet/dotnet`. (You can use the "remotes" option to point to a local installer repository)
3. Use GitHub Codespace where instructions are in the README that opens automatically when the Codespace is started (but it uses `vmr-sync.sh` in the background.
4. If you only want to test something, just go and change `src/installer` in the VMR directly - but I understand you don't want that for some reason? Such as you're changing versions of packages etc

So if you are after quick testing, I'd do 2 or 4, if you want to set up a process, maybe 1. would be the best (I can fix the problem there). If you want a full environment, 3 is the best but costs $..

Now for the ask itself to document this.. The synchronization based on installer is a [temporary thing](https://github.com/dotnet/dotnet/blob/main/src/arcade/Documentation/UnifiedBuild/VMR-Design-And-Operation.md#synchronization-based-on-declared-dependencies). However, temporary means probably next "almost a year" so I understand this could be more upfront in VMR's README so I will log an issue for that.

**Comment by premun** [comment]
Oh yeah.. why did I create a duplicate for this... It's been a long day 😅

**Comment by MichaelSimons** [comment]
@premun - Are you going to capture [these steps](https://github.com/dotnet/source-build/issues/3498#issuecomment-1582803538) formally within our documentation?  What is needed to complete this issue?

**Comment by premun** [comment]
@MichaelSimons I am not here tomorrow so that we could discuss this. If we want to support this, we'd need to think about it a bit more so that we have coverage for this as we do not really exercise this for anything. But maybe it's not an interesting feature really?

**Comment by premun** [comment]
We have discussed this and the right way to bring in new changes from the `installer` repository is via the [`vmr-sync.sh` script](https://github.com/dotnet/dotnet/blob/main/src/installer/eng/vmr-sync.sh).

We will bring this more front into VMR's README.

**Comment by MichaelSimons** [comment]
Closing as resolved by https://github.com/dotnet/installer/pull/17414.
