### ISSUE TITLE
Remove redundant `SourceBuildTrimNetFrameworkTargets` property

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3503]
We have originally added `SourceBuildTrimNetFrameworkTargets` property to most .NET repos to enable TFM trimming, in accordance with the original design: https://github.com/dotnet/source-build/issues/3014

As a consequence, the following line was added to those repos (an example from `installer`):

https://github.com/dotnet/installer/blob/f8275a0edc0a90b593f2e3f73c4b9b3e908e3e22/eng/SourceBuild.props#LL8C50-L8C50
```
    <SourceBuildTrimNetFrameworkTargets>true</SourceBuildTrimNetFrameworkTargets>
```

After original implementation, TFM trimming work was further simplified, to use the opt-out logic, with: https://github.com/dotnet/arcade/pull/13271

This property is not needed anymore, it causes unnecessary confusion and increased maintenance cost. Property should be removed at the earliest convenience.

To ensure proper tracking, for each repo, the list below should be updated with the PR link. Refer to original work (https://github.com/dotnet/source-build/issues/3014) for the full list of repos and original changes. Note that some repos never used this property, i.e. `emsdk` and `runtime`.

### Repositories

- https://github.com/dotnet/arcade/pull/13854
- https://github.com/dotnet/aspnetcore/pull/49022
- https://github.com/dotnet/cecil/pull/91
- https://github.com/dotnet/command-line-api/pull/2229
- https://github.com/dotnet/deployment-tools/pull/280
- https://github.com/dotnet/diagnostics/pull/4016
- https://github.com/dotnet/format/pull/1883
- https://github.com/dotnet/fsharp/pull/15487
- https://github.com/dotnet/installer/pull/16817
- https://github.com/dotnet/msbuild/pull/8952
- https://github.com/NuGet/NuGet.Client/pull/5278
- https://github.com/dotnet/razor/pull/8866
- https://github.com/dotnet/roslyn-analyzers/pull/6713
- https://github.com/dotnet/roslyn/pull/68772
- https://github.com/dotnet/sdk/pull/33572
- https://github.com/dotnet/sourcelink/pull/1054
- https://github.com/dotnet/symreader/pull/292
- https://github.com/dotnet/templating/pull/6801
- https://github.com/dotnet/test-templates/pull/309
- https://github.com/microsoft/vstest/pull/4577
- https://github.com/dotnet/xdt/pull/517
- https://github.com/dotnet/xliff-tasks/pull/798

**Comment by MichaelSimons** [comment]
[Triage] @v-chayan, please work with @NikolaMilosavljevic to gain an understanding of the changes needed here.

**Comment by MichaelSimons** [comment]
All PRs have been completed!  Closing.
