### ISSUE TITLE
Inner clone puts nested submodules in unexpected locations

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3513]
### Describe the Bug

I attempted to introduce xunit to source-build-externals. It has a submodule, and SBE uses submodules. When building under source build, the inner clone appears to place the inner submodule as a peer directory to the main xunit submodule.

### Steps to Reproduce

1. Clone https://github.com/mmitche/source-build-externals/tree/add-xunit-bug
2. Source build.

```
    CSC : error CS2001: Source file '/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit/src/xunit.core/../xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs' could not be found. [/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit/src/xunit.core/xunit.core.csproj]
    CSC : error CS2001: Source file '/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit/src/xunit.core/../xunit.assert/Asserts/Sdk/AssertEqualityComparerAdapter.cs' could not be found. [/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit/src/xunit.core/xunit.core.csproj]
    CSC : error CS2001: Source file '/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit/src/xunit.core/../xunit.assert/Asserts/Sdk/ArgumentFormatter.cs' could not be found. [/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit/src/xunit.core/xunit.core.csproj]
```

Expected location:

`/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit/src/xunit.assert/Asserts/Sdk/ArgumentFormatter.cs`

Actual location:

`/home/mmitche/source-build-externals/artifacts/source-build/self/src/src/xunit.assert/Asserts/Sdk/ArgumentFormatter.cs`

**Comment by MichaelSimons** [comment]
@mmitche can this be closed now that https://github.com/dotnet/arcade/pull/13819 was merged?
