### ISSUE TITLE
Proprietary/confidential license in `CustomTelemetryChannel.cs`

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#3529]
https://github.com/dotnet/dotnet/blob/826dcac6ef3a34e4e41042fb1112995fe1f21609/src/source-build-externals/src/application-insights/LOGGING/test/Shared/CustomTelemetryChannel.cs#L1-L6

has this license

```
﻿//-----------------------------------------------------------------------------------
// <copyright file='CustomTelemetryChannel.cs' company='Microsoft Corporation'>
//     Copyright (c) Microsoft Corporation. All Rights Reserved.
//     Information Contained Herein is Proprietary and Confidential.
// </copyright>
//-----------------------------------------------------------------------------------
```

**Comment by MichaelSimons** [comment]
[Triage] This is something the we should open an issue for/fix in App Insights.  We may need to carry a fix depending on what the release schedule is for app insights and if we can upgrade before GA.  If not possible we will have to cloak this file.

**Comment by oleksandr-didyk** [comment]
The license seems to have been corrected in the original repo thanks to Omair's report -> https://github.com/microsoft/ApplicationInsights-dotnet/issues/2670

In `main` the file also does not have the indicated line - https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/LOGGING/test/Shared/CustomTelemetryChannel.cs#L2-L4

So it seems we are just carrying a version that does not have the fix. I'll check the minimum version that would have the fixed header

**Comment by oleksandr-didyk** [comment]
So `source-build-externals` is on `2.21.0` and the fix is available with `2.22.0-beta1`.

Currently in NuGet the latest available version is [`2.22.0-beta3`](https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.22.0-beta3). Not sure how happy would the repos be if we were to ask them to pick-up a `beta` version.

**Comment by MichaelSimons** [comment]
I don't think we want to take a dependency on a beta version.  Can you find out/ask what when this would be released?  If it is soon, we can just wait.

**Comment by oleksandr-didyk** [comment]
The milestone that is referenced in issues for 2.22 is running late for almost a month - https://github.com/microsoft/ApplicationInsights-dotnet/milestone/50

I'll create an issue asking for some estimation we could use

**Comment by oleksandr-didyk** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/issues/2792
