### ISSUE TITLE
Non-open source licnese in AspNetCoreModule-Setup

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#3537]
https://github.com/dotnet/dotnet/blob/1326caa7a59f4b6606dc779ae07ae101285a0730/src/aspnetcore/src/Installers/Windows/AspNetCoreModule-Setup/license/license.rtf

Contains what looks like a non-open-source license:

```
You may not
...
- publish the software for others to copy
```

Is this the license for code in this repository/directory? Is it an "asset" attached to the build output when building AspNetCoreModule?

**Comment by MichaelSimons** [comment]
Closing as fixed by https://github.com/dotnet/installer/pull/17046 and https://github.com/dotnet/dotnet/pull/34
