### ISSUE TITLE
IdentityModel assemblies have incorrect assembly version

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3565]
When comparing assembly versions between the Microsoft SDK and the source-built SDK, the following diff showed up:

```diff
-sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.Abstractions.dll - 6.21.0
-sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.JsonWebTokens.dll - 6.21.0
-sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.Logging.dll - 6.21.0
-sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.Tokens.dll - 6.21.0
-sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/System.IdentityModel.Tokens.Jwt.dll - 6.21.0
+sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.Abstractions.dll - 0.0.1
+sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.JsonWebTokens.dll - 0.0.1
+sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.Logging.dll - 0.0.1
+sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/Microsoft.IdentityModel.Tokens.dll - 0.0.1
+sdk/x.y.z/DotnetTools/dotnet-user-jwts/x.y.z/tools/netx.y/any/System.IdentityModel.Tokens.Jwt.dll - 0.0.1
```

These assemblies are produced from [source-build-externals](https://github.com/dotnet/source-build-externals/blob/main/repo-projects/azure-activedirectory-identitymodel-extensions-for-dotnet.proj). The package version is being set correctly. However, the source of the external repo is configured in such a way to [default the assembly version to 0.0.1 and it must be explicitly overriden](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/9aab2749e0ac8a6b8090980c445a559b816f0cf0/build/version.props#L1-L6). The repo does contain a [script to overwrite this file](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/9aab2749e0ac8a6b8090980c445a559b816f0cf0/updateAssemblyInfo.ps1) which makes use of the settings in a [config file](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/9aab2749e0ac8a6b8090980c445a559b816f0cf0/buildConfiguration.xml) that contains the correct version. So it should just be a matter of customizing the source-build-externals build to invoke this script. This script is also called by the repo's own [release pipeline](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/9aab2749e0ac8a6b8090980c445a559b816f0cf0/build/releaseBuild.yml#L73-L78).

**Comment by mthalman** [comment]
> So it should just be a matter of customizing the source-build-externals build to invoke this script. 

Except it's not that simple. This script is authored in PowerShell. We can't be making use of non-source-built tools like this as part of the built logic. So really the only option is to reimplement the PowerShell script in Bash.

The other issue is that the script's logic uses `git` to get the current commit SHA to inject into the `AssemblyInformationVersion` attribute. That's not going to work in non-repo environments where the source has simply been extracted from a tarball.

**Comment by MichaelSimons** [comment]
@mthalman - should this issue remain open until the version test baseline has been updated to reflect the fix that went into IdentityModel is picked up?

**Comment by mthalman** [comment]
Sure, that's fine

**Comment by mthalman** [comment]
Builds are all passing now and assembly version comparisons are all good.
