### ISSUE TITLE
VMR stage 2 build fails in ILCompiler with unsupported OS error

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3568]
```
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error : Unhandled exception. System.CommandLine.CommandLineException: Target OS 'centos.8' is not supported [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.Helpers.GetTargetOS(String token) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.CliArgument`1.<>c__DisplayClass8_0.<set_CustomParser>b__0(ArgumentResult argumentResult, Object& parsedValue) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.Parsing.ArgumentResult.ValidateAndConvert(Boolean useValidators) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.Parsing.CommandResult.ValidateOptions(Boolean completeValidation) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.Parsing.CommandResult.Validate(Boolean completeValidation) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.Parsing.ParseOperation.Validate() [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.Parsing.ParseOperation.Parse() [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.Parsing.CliParser.Parse(CliCommand command, IReadOnlyList`1 arguments, String rawInput, CliConfiguration configuration) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at System.CommandLine.CliConfiguration.Invoke(String[] args) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(470,5): error :    at ILCompiler.Program.Main(String[] args) [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/vmr/.dotnet/sdk/8.0.100-rc.1.23375.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(358,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
```

[Binlog link](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjIyOTE1NS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PbmxpbmVfUHJldmlvdXNTb3VyY2VCdWlsdFNka194NjRfQnVpbGRMb2dzX0F0dGVtcHQx0/content?format=file&subPath=%2Fsrc%2Fruntime%2Fartifacts%2FbuildLogs%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog) (internal only)

**Comment by mthalman** [comment]
This is most likely caused by https://github.com/dotnet/sdk/pull/31581.

**Comment by jkotas** [comment]
> [Binlog link](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjIyOTE1NS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PbmxpbmVfUHJldmlvdXNTb3VyY2VCdWlsdFNka194NjRfQnVpbGRMb2dzX0F0dGVtcHQx0/content?format=file&subPath=%2Fsrc%2Fruntime%2Fartifacts%2FbuildLogs%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog) (internal only)

I do not see the error above in this binlog.

What are the repro steps for this build error?

**Comment by mthalman** [comment]
> > [Binlog link](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjIyOTE1NS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PbmxpbmVfUHJldmlvdXNTb3VyY2VCdWlsdFNka194NjRfQnVpbGRMb2dzX0F0dGVtcHQx0/content?format=file&subPath=%2Fsrc%2Fruntime%2Fartifacts%2FbuildLogs%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog) (internal only)
> 
> I do not see the error above in this binlog.
> 
> What are the repro steps for this build error?

Sorry about that. Picked the wrong one. The actual log is small enough that I can attach it here: 
[runtime-binlog.zip](https://github.com/dotnet/source-build/files/12172761/runtime-binlog.zip)

The repro steps are to simply build the runtime repo using the latest RC1 build of the SDK.

**Comment by sec** [comment]
I may be wrong here (and most likely I will :P), but isn't the fail because of `--targetos:centos.8` that's passed to crossgen2 tool?
The task that was changed, is (if I get it right) responsible for getting the path to that crossgen2 binary on current OS, right?

For ex. running crossgen2 from `8.0.0-preview.6.23329.7` (compiled myself under FreeBSD)  I have this:
`--targetos                                                                                               Target OS for cross compilation [default: FreeBSD]
  <FreeBSD|iOS|iOSSimulator|Linux|MacCatalyst|NetBSD|OSX|SunOS|tvOS|tvOSSimulator|Unknown|WebAssembly|Windows>`.

So shouldn't it pass `linux` instead of `centos.8` ?

**Comment by mthalman** [comment]
I should clarify the repro steps since it's not as simple as taking the Linux SDK. This is using a source-built SDK. So the SDK was built from source to be non-portable, targeting centos.8. That SDK is then used to build the runtime repo.

This previously worked up until this change.

**Comment by jkotas** [comment]
> edit: yes, I was wrong, targetOs is getting set as output from this task, so this change broke it for this case :(

Right.

@sec I am sorry I have to revert the change for now to unblock the source build on Linux.

**Comment by sec** [comment]
@jkotas  Sure, I get it. But on the other hand, it would be great to have this change somehow done, as it will unblock our unofficial builds :) So what would be the best way to approach this and not break things again, as the same change is already merged in runtime, but there's no issue in there?

@mthalman could you share more details on repro steps that led to this (or is it like you said, simple building non-portable sdk targeting centos for ex. and then building runtime using it?) - is this documented somewhere, maybe scripted?

Maybe a smaller change to this task (aka https://github.com/dotnet/sdk/pull/31581/commits/3a3c657abe7185760be9c47fa3c389e22e4e7676) would be fine to get source-build working for both Linux and FreeBSD world?

**Comment by jkotas** [comment]
@sec The problem seems to be that you have deleted RID normalization https://github.com/dotnet/sdk/pull/34277/files#diff-889b001deb80ecc440f0abd3f784b1883a8c8d7b0d5fd8ba0c1768d7e8add5efR187-R194 that is apparently important for Linux source build. I think you change was good otherwise.

**Comment by Thefrank** [comment]
This code is/was(?) mirrored from runtime. Why did it break here and not in runtime?

**Comment by mthalman** [comment]
> This code is/was(?) mirrored from runtime

Yes, it's part of the [VMR](https://github.com/dotnet/dotnet) which integrates all the relevant .NET repos into a single one.

> Why did it break here and not in runtime?

Because the runtime repo doesn't use the latest build from the sdk repo to test itself. I believe https://github.com/dotnet/runtime/issues/88675 might fix that. Correct, @ViktorHofer?
