### ISSUE TITLE
[source-build-release] Incorrect instructions in "Approval - PR merged" dialog

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3574]
Stage: `Approval - PR merged & ready for dotnet-security-partners mirroring`

When trying to approve this stage, a dialog is shown with instructions, at the bottom of the dialog, that do not match current release process. Smoke-test-prereqs get automatically packaged and uploaded during next, mirroring, stage, so it cannot be verified at this stage.

Here's the message:

![approval-smoke-test-prereqs](https://github.com/dotnet/source-build/assets/9423618/ddd24410-2755-4ccc-a35c-0d2a34c6d4d4)

Besides updating this message, it would be helpful to add a blurb about smoke-test-prereqs in the checklist's step 3.c `Mirror sources and packages`

**Comment by oleksandr-didyk** [comment]
Hey @NikolaMilosavljevic, if my understanding of the issue is correct, we would want the instructions for the approval to say something like:
```
Verify that new sources were merged into `security-partners-dotnet`
```
Or do you see value in something else / something more being there? Thanks!

**Comment by oleksandr-didyk** [comment]
Or maybe @mthalman would have more context into this issue. Thanks in advance!

**Comment by mthalman** [comment]
> Hey @NikolaMilosavljevic Nikola Milosavljevic (CLR) FTE, if my understanding of the issue is correct, we would want the instructions for the approval to say something like:
> 
> ```
> Verify that new sources were merged into `security-partners-dotnet`
> ```
> 
> Or do you see value in something else / something more being there? Thanks!

Yeah, I think that message should be sufficient.

**Comment by oleksandr-didyk** [comment]
The message has been updated, closing as `Done`

New message:
![image](https://github.com/dotnet/source-build/assets/106967057/7eef9d84-7ef0-4426-a734-c8fcfd350be1)
