### ISSUE TITLE
TargetRid default needs to be updated

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#3578]
Currently source-build determines the non-portable rid of the target platform by calling `RuntimeInformation.RuntimeIdentifier`:

```xml
<TargetRid Condition="'$(TargetRid)' == ''">$([System.Runtime.InteropServices.RuntimeInformation]::RuntimeIdentifier)</TargetRid>
```

The changes in https://github.com/dotnet/runtime/pull/89598 mean this property will no longer return the rid based on Linux's `/etc/os-release`, but instead it will return the rid the .NET runtime was built for.

So when source-building .NET with a portable Microsoft SDK, the `RuntimeIdentifier` will be the portable rid of that SDK, and not the non-portable rid of the platform the build is running on.

The `TargetRid` should continue to default to the non-portable rid of the platform so we can identify portable from non-portable assets.

cc @MichaelSimons @elinor-fung @dsplaisted @omajid

**Comment by dsplaisted** [comment]
Linking this to the change where this occurred: https://github.com/dotnet/runtime/pull/89598
