### ISSUE TITLE
[source-build-release] Repo name in 8.0 release stage is ambiguous

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3587]
`Approval - Release` stage has the following step:

_8.0: Verify the release tag in the `dnceng/dotnet-security-partners` repository matches theVMR commit to which is shown in the `Pre-Release` stage (in the `Get Associated Pipeline Run IDs` step)._

`dnceng/dotnet-security-partners` is ambiguous and does not point to the correct repo.

Correct repository should be specified instead: https://dev.azure.com/dotnet-security-partners/_git/dotnet

**Comment by premun** [comment]
There's also https://dev.azure.com/dnceng/internal/_git/security-partners-dotnet - please double check that this one is not the one

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/source-build/pull/3593
