### ISSUE TITLE
Binary scan detecting new P22DotNetHtmlLocalization.lss file

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3589]
This file path is showing up in the `Scan for binaries` task of the VMR:

```
eng/common/loc/P22DotNetHtmlLocalization.lss
```

The intention is that these lss files should be excluded from the scan by https://github.com/dotnet/installer/blob/be83e59d9c378262680a0fa0303d528f8b9bba70/src/VirtualMonoRepo/allowed-binaries.txt#L23. But apparently that's not working for this path.

**Comment by mthalman** [comment]
cc @premun

**Comment by premun** [comment]
Ignoring the file via `eng/common/..` didn't help

**Comment by premun** [comment]
Repro (run in the dotnet folder):

```
git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 --numstat . ':(exclude)src' ':(exclude)*.bmp' ':(exclude)*.docx' ':(exclude)*.gif' ':(exclude)*.ico' ':(exclude)*.jpg' ':(exclude)*.JPG' ':(exclude)*.pdf' ':(exclude)*.png' ':(exclude)*.PNG' ':(exclude)*.rtf' ':(exclude)*.snk' ':(exclude)*.vsd' ':(exclude)*.vsdx' ':(exclude)*.xlsx' ':(exclude)**/test/*' ':(exclude)**/Test/*' ':(exclude)**/Test/*' ':(exclude)**/testCert*.pfx' ':(exclude)**/TestCert*.pfx' ':(exclude)**/tests/*' ':(exclude)**/eng/common/loc/*.lss' | grep -E '^\-'
```

**Comment by premun** [comment]
Okay, so `**/whatever/*.lss` just won't work with the two asterisks, I might open a bug with git.

However, I found an unrelated bug that is ignoring the newly added rule for `eng/common`

**Comment by MichaelSimons** [comment]
Has all the issues been resolved here and follow-up issues logged as appropriate?  Can this be closed?

**Comment by premun** [comment]
Yeah, this can be closed. We had to add a duplicate rule for the top level `eng/common` as git just doesn't support it.
