### ISSUE TITLE
NETSDK1094 errors in tests when using .NET 8 RC1 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3591]
The following error occurs, for all languages, when running the source-build smoke tests with a .NET 8 RC1 source-built SDK:

Error Message:
```
System.InvalidOperationException : Failed to execute /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet publish --self-contained true -r linux-x64 /p:PublishTrimmed=true /p:PublishReadyToRun=true /bl:/vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/logs/BasicScenarioTests_Console_CSharp-publish-self-contained-linux-x64-trimmed-R2R.binlog -o /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202308111856352233/BasicScenarioTests_Console_CSharp/bin/publish
Exit code: 1
MSBuild version 17.8.0-preview-23409-01+a998492eb for .NET
  Determining projects to restore...
/vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/sdk/8.0.100-rc.1.23411.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. When targeting .NET 6 or higher, make sure to restore packages with the PublishReadyToRun property set to true. [/vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202308111856352233/BasicScenarioTests_Console_CSharp/BasicScenarioTests_Console_CSharp.csproj]
```

Stack Trace:

```
Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ValidateExitCode(ValueTuple`3 result, Int32 expectedExitCode)
Microsoft.DotNet.SourceBuild.SmokeTests.DotNetHelper.ExecuteCmd(String args, String workingDirectory, Action`1 processConfigCallback, Nullable`1 expectedExitCode, Int32 millisecondTimeout)
Microsoft.DotNet.SourceBuild.SmokeTests.DotNetHelper.ExecutePublish(String projectName, DotNetTemplate template, Nullable`1 selfContained, String rid, Boolean trimmed, Boolean readyToRun)
Microsoft.DotNet.SourceBuild.SmokeTests.TestScenario.Execute(DotNetHelper dotNetHelper)
Microsoft.DotNet.SourceBuild.SmokeTests.BasicScenarioTests.VerifyScenario(TestScenario scenario)
InvokeStub_BasicScenarioTests.VerifyScenario(Object, Span`1)
System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

This seems related to the changes in https://github.com/dotnet/sdk/pull/34429.

@sbomer - Can you provide some info on this? What's wrong with the way the test is invoking this? It's specifying a valid RID (`linux-x64`).

**Comment by mthalman** [comment]
Actually, it seems more likely that this is caused by https://github.com/dotnet/sdk/pull/34430.

@TheFrank, @jkotas - The scenario here is that we're building the SDK from source with a non-portable RID: centos.8-x64. We then use that SDK to publish a .NET project with ready-to-run, targeting a RID of `linux-x64`. That fails with: `error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. When targeting .NET 6 or higher, make sure to restore packages with the PublishReadyToRun property set to true.`

Is this a bug or is it intentional that this no longer works?

This originally repro'd in https://github.com/dotnet/installer/pull/17118. I had to work around it by disabling the tests at https://github.com/dotnet/installer/pull/17118/files#diff-aa29a7c9a653ceed0c4a6c62a2fa3ebd9b854c48ce58bd489b49bfab183ef72aL37-R38. That change would need to be reverted to repro.

**Comment by jkotas** [comment]
> Actually, it seems more likely that this is caused by https://github.com/dotnet/sdk/pull/34430.

This changed was coded very defensively to avoid changing any behaviors for non-portable RIDs. I think it is very unlikely that it introduced this issue.

>The scenario here is that we're building the SDK from source with a non-portable RID: centos.8-x64. We then use that SDK to publish a .NET project with ready-to-run, targeting a RID of linux-x64.

Can this be related to https://github.com/dotnet/sdk/pull/34279? After this change, there is no association between linux-x64 RID and non-portable RIDs like centos.8-x64 by default. Do the distro builds include any overrides for this default?

**Comment by mthalman** [comment]
> Can this be related to [dotnet/sdk#34279](https://github.com/dotnet/sdk/pull/34279)? After this change, there is no association between linux-x64 RID and non-portable RIDs like centos.8-x64 by default. Do the distro builds include any overrides for this default?

Good find. Yes, that looks to be the cause. Looks like there's [some changes that are necessary for source-build](https://github.com/dotnet/sdk/pull/34279#issuecomment-1652784662).

**Comment by lewing** [comment]
so https://github.com/dotnet/source-build/issues/3584

**Comment by MichaelSimons** [comment]
@mthalman - Has this issue been resolved now?

**Comment by mthalman** [comment]
> @mthalman - Has this issue been resolved now?

Yep. This was essentially a duplicate of https://github.com/dotnet/source-build/issues/3584.
