### ISSUE TITLE
[source-build-release] Automate custom tag mirroring

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3594]
Source-build release pipeline should incorporate steps for custom tag mirroring. This should happen as the first step after official Microsoft release.

See https://github.com/dotnet/source-build/issues/3585 for full list of steps.

**Comment by oleksandr-didyk** [comment]
The changes introduced by https://github.com/dotnet/source-build/pull/3659 are already tagging the build commit and pushing the tag to public VMR if it does not exist. 

We could simply always trigger this step. It first checks if the tags already exists, so it would just not do anything for a non-custom tag use-case.

@NikolaMilosavljevic could you please confirm that when talking about `servicing` release you mean 6.0 and 7.0 (i.e. pre-VMR)? Thanks!

**Comment by NikolaMilosavljevic** [comment]
> The changes introduced by #3659 are already tagging the build commit and pushing the tag to public VMR if it does not exist.
> 
> We could simply always trigger this step. It first checks if the tags already exists, so it would just not do anything for a non-custom tag use-case.
> 
> @NikolaMilosavljevic could you please confirm that when talking about `servicing` release you mean 6.0 and 7.0 (i.e. pre-VMR)? Thanks!

This was encountered with one of 6.0 servicing releases, so it is likely only an issue with pre-VMR releases.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35693
