### ISSUE TITLE
Investigate content differences between centos8 and centos9

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3597]
In https://github.com/dotnet/installer/pull/17233#discussion_r1303586002, it was discovered that the major differences between centos baselines appears to be that the runtimes appear as shared frameworks in centos8 and packs in centos9.

Based on this discovery, we should look into any content differences between distros and analyze these differences to ensure we understand why there are differences.

There should also possibly be a test for this scenario that checks the distro content differences.

**Comment by mthalman** [comment]
@ellahathaway - Can you attach the files that demonstrate these differences to this issue?

**Comment by ellahathaway** [comment]
@mthalman Yes! Here is a diff of the baselines from centos8 and centos9: [diff](https://www.diffchecker.com/tv4REdKL/).

**Comment by omajid** [comment]
cc @tmds 

AFAIK, the runtimes (for self-contained publishing) are supposed to be added under `packs/`. The CentOS behaviour looks wrong.

**Comment by tmds** [comment]
> the runtimes appear as shared frameworks in centos8 and packs in centos9.

The runtimes should appear both as a shared framework and as a pack since preview 6.

It would be surprising if the output differs based on the distro that gets built.

A build without a shared framework would not be able to pass smoke tests.

Afaik a smoke test has also been added for the pack to be present.

Are smoke tests failing for these builds?

**Comment by mthalman** [comment]
All smoke tests are passing for both CentOS Stream 8 and 9.

**Comment by mthalman** [comment]
We already have an [SDK comparison test](https://github.com/dotnet/installer/blob/a4807f022247eb5f0b9be6d5fab8f854ab7c0c77/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/SdkContentTests.cs#L35-L45) which should catch these differences. We have a single baseline file describing the differences between the MSFT SDK and SB SDK. The test is running for both CentOS Stream 8 and 9. So there should be differences in the passing of this test between the two versions. The only explanation is that the differences are being filtered out by the [exclusions file](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkFileDiffExclusions.txt).

**Comment by tmds** [comment]
> All smoke tests are passing for both CentOS Stream 8 and 9.

Then both directories should be part of the output.

> filtered out by the [exclusions file](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkFileDiffExclusions.txt).

This filters out the packs: https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkFileDiffExclusions.txt#L55-L56.

**Comment by ellahathaway** [comment]
[Here](https://gist.github.com/ellahathaway/20fbe064844df8671d1a5e9ea2c8842c) is a more comprehensive file of all the files that exist in Centos8 but not in Centos9 and vise-versa. It appears that while [this line in the exclusions file](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkFileDiffExclusions.txt#L55-L56.) filters out the packs, there are still numerous leftover files that are not included in the exclusions.txt, most of which are in ./sdk/*.

**Comment by ellahathaway** [comment]
It appears that the files exist in the dotnet-sdk tarballs as we would expect. As a result, I suspect that this discrepancy is an issue with the testing infrastructure not unpacking the tars correctly rather than a difference in the content between distros.

**Comment by mthalman** [comment]
@ellahathaway - Are these results consistent? I'm just wondering if there's any race condition here that may be affecting things.

**Comment by ellahathaway** [comment]
@mthalman Yes, the results are consistent. The program I've been using to generate there results should be thread-safe. That is, there shouldn't be any race conditions since the program is only reading from the tars, and all writes to the output file occur at the very end of the sequential program.

**Comment by mthalman** [comment]
I was referring to the creation of the tarball itself. Would multiple CI runs of the VMR always produce tarballs with these same differences?

**Comment by ellahathaway** [comment]
I see. No, it appears that multiple CI runs of the VMR do not always produce the same results. [Here is a diff ](https://www.diffchecker.com/9pJi0uEi/)of two different updated baselines from different dotnet-dotnet builds. Additionally, [here is a file](https://gist.github.com/ellahathaway/7807774bd7cf1f84be3b55e1d6a00eab) that lists all the files from the tarballs with size differences between the original baseline and the updated baselines.

**Comment by tmds** [comment]
> I'm still unsure of why these files do not have the same TarEntryType across distros.

During the build, some files get replaced by hard links (https://github.com/dotnet/installer/pull/16624).
When these files get tarred, the first time the file is encountered, it will be a RegularFile, and other paths to the same file (hard links) will be added as HardLink. So the tar file entries for the same path may change because they were enumerated in a different order while creating the archive.
