### ISSUE TITLE
Enable dotnet-format tests on Alpine

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3598]
Dotnet-format tests on Alpine were disabled with https://github.com/dotnet/installer/pull/17247 due to issue with dotnet-format tool on that platform - https://github.com/dotnet/format/issues/1945

This was uncovered when we enabled those tests with https://github.com/dotnet/installer/pull/17238

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - Is this now unblocked?  It looks like the msbuildLocator changes were merged.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic - Is this now unblocked? It looks like the msbuildLocator changes were merged.

I'm going to confirm and reenable the tests.
