### ISSUE TITLE
Investigate list of reference assemblies

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3599]
A list of assemblies compiled by @tmds in https://github.com/dotnet/source-build/issues/3571#issuecomment-1691388280 shows the set of reference assemblies that currently exist in the SB SDK and are represented as implementation assemblies in the MSFT SDK:

```
sdk/8.0.100-preview.7.23376.1/Microsoft.Win32.SystemEvents.dll
sdk/8.0.100-preview.7.23376.1/System.ComponentModel.Composition.dll
sdk/8.0.100-preview.7.23376.1/System.Drawing.Common.dll
sdk/8.0.100-preview.7.23376.1/System.Security.Permissions.dll
sdk/8.0.100-preview.7.23376.1/System.Windows.Extensions.dll
sdk/8.0.100-preview.7.23376.1/FSharp/Microsoft.Win32.SystemEvents.dll
sdk/8.0.100-preview.7.23376.1/FSharp/System.CodeDom.dll
sdk/8.0.100-preview.7.23376.1/FSharp/System.Drawing.Common.dll
sdk/8.0.100-preview.7.23376.1/FSharp/System.Resources.Extensions.dll
sdk/8.0.100-preview.7.23376.1/FSharp/System.Security.Cryptography.Xml.dll
sdk/8.0.100-preview.7.23376.1/FSharp/System.Security.Permissions.dll
sdk/8.0.100-preview.7.23376.1/FSharp/System.Windows.Extensions.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.DependencyInjection.Abstractions.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.DependencyInjection.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.FileSystemGlobbing.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Logging.Abstractions.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Logging.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Options.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Primitives.dll
sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/System.IO.Pipelines.dll
sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/Microsoft.Win32.SystemEvents.dll
sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/System.Drawing.Common.dll
sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/System.Security.Permissions.dll
sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/System.Windows.Extensions.dll
```

We should investigate this list to determine if there is any functional significance to the existence of these. One way to investigate this is to compare this list to the 7.0 SB SDK which has already been vetted and should, in theory, have rooted out any potential issue with the existence of a ref assembly.

One issue already known from this list is System.Security.Permissions: https://github.com/dotnet/msbuild/pull/9158

**Comment by MichaelSimons** [comment]
https://github.com/dotnet/source-build/issues/2817 is the issue tracking the enhancements to the poison infrastructure to detect these.

**Comment by mthalman** [comment]
It looks like all of these assemblies need to be addressed. All of the corresponding assemblies that exist in the source-built version of the 7.0 SDK are implementation assemblies.

**Comment by mmitche** [comment]
Looks like it will be a combo of updating the Version.Details.xml files in those repos, as well as the dependency graph in SB, if it's out of order.

**Comment by mthalman** [comment]
List of assemblies with notes that I'll be filling in during my investigation.


* sdk/8.0.100-preview.7.23376.1/Microsoft.Win32.SystemEvents.dll
* sdk/8.0.100-preview.7.23376.1/System.ComponentModel.Composition.dll
* sdk/8.0.100-preview.7.23376.1/System.Drawing.Common.dll
* sdk/8.0.100-preview.7.23376.1/System.Security.Permissions.dll
* sdk/8.0.100-preview.7.23376.1/System.Windows.Extensions.dll
* sdk/8.0.100-preview.7.23376.1/FSharp/Microsoft.Win32.SystemEvents.dll
* sdk/8.0.100-preview.7.23376.1/FSharp/System.CodeDom.dll
* sdk/8.0.100-preview.7.23376.1/FSharp/System.Drawing.Common.dll
* sdk/8.0.100-preview.7.23376.1/FSharp/System.Resources.Extensions.dll
* sdk/8.0.100-preview.7.23376.1/FSharp/System.Security.Cryptography.Xml.dll
* sdk/8.0.100-preview.7.23376.1/FSharp/System.Security.Permissions.dll
* sdk/8.0.100-preview.7.23376.1/FSharp/System.Windows.Extensions.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.DependencyInjection.Abstractions.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.DependencyInjection.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.FileSystemGlobbing.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Logging.Abstractions.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Logging.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Options.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/Microsoft.Extensions.Primitives.dll
* sdk/8.0.100-preview.7.23376.1/DotnetTools/dotnet-format/System.IO.Pipelines.dll
* sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/Microsoft.Win32.SystemEvents.dll
* sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/System.Drawing.Common.dll
* sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/System.Security.Permissions.dll
* sdk/8.0.100-preview.7.23376.1/Containers/tasks/net8.0/System.Windows.Extensions.dll

**Comment by mthalman** [comment]
Closing since all PRs being tracked by this are merged.

**Comment by tmds** [comment]
@mthalman thank you for picking this up, and fixing up all the assemblies!
