### ISSUE TITLE
No symbols archive for aspnetcore

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#3609]
### Describe the Bug

After building the .NET 8 VMR, I see this:

```
$ find -iname '*symbols*tar*'
$ find artifacts -iname '*symbols*tar*'
artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-symbols-fedora.38-x64-8.0.0-rc.2.23426.4.tar.gz
artifacts/x64/Release/dotnet-runtime-symbols-fedora.38-x64-8.0.0-rc.2.23426.4.tar.gz
```

This only shows runtime symbols. No symbol archive is produced for ASP.NET Core.

It looks like some symbols are produced for ASP.NET Core. I can see files like `src/aspnetcore/artifacts/source-build/self/src/artifacts/bin/Microsoft.AspNetCore.Mvc/Release/net8.0/Microsoft.AspNetCore.Antiforgery.pdb` on disk, but I don't know how to go from those pdb files to something that can be installed/shipped on a distro.

### Steps to Reproduce

0. `git clone https://github.com/dotnet/dotnet -b release/8.0.1xx`
1. `./prep.sh`
2. `./build.sh`
3. `find artifacts/ -iname '*symbols*tar'`

### Other Information

There's a related issue, https://github.com/dotnet/source-build/issues/3547, about how the symbols are produced and packaged. I think whatever approach we pick, we should make sure all symbols are made available post-build in the same format.

**Comment by MichaelSimons** [comment]
This issue has been resolved with the linked PRs.  Symbols will be available in RC2.
