### ISSUE TITLE
[smoke-tests] Sourcelink tests should verify all source-build symbols

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3612]
Related to https://github.com/dotnet/source-build/issues/3052

Upcoming sourcelink tests are going to verify available symbols, from runtime symbols package: `dotnet-runtime-symbols-[Version]-[RID].tar.gz`

There is a pending work to make symbols from all repos available in unified source-build artifacts location. Once that work is done, sourcelink tests should be expanded to cover all symbols.

**Comment by MichaelSimons** [comment]
This requires https://github.com/dotnet/arcade/pull/14015 to be merged and rolled out first.

**Comment by MichaelSimons** [comment]
Once this is done, it should complete the managed portion of https://github.com/dotnet/source-build/issues/3462.

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/installer/pull/17477
