### ISSUE TITLE
.NET 9 branching for SBRP and SBE

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3613]
Now that the `main` branch of [installer](https://github.com/dotnet/installer) is targeting .NET 9, there will be a need to have updates made for [SBRP](https://github.com/dotnet/source-build-reference-packages) and [SBE](https://github.com/dotnet/source-build-externals) to be specific to that version. These changes need to be kept separate from changes for .NET 8. To do that, we'll need to create `release/8.0` branches for those two repos and have darc subscriptions updated accordingly.

**Comment by MichaelSimons** [comment]
@mmitche - Is this something you can help out with?  Need to ensure the darc subscriptions get created/updated appropriately.

**Comment by mmitche** [comment]
Ack. I'm OOF tomorrow. Next week?

**Comment by mthalman** [comment]
Next week is fine

**Comment by mmitche** [comment]
This should be done, but may require some tweaking later, as more repos that haven't yet branched for .net 8 servicing need to update or add subscriptions. Triggers for this would be if SBE or SBRP dependencies in a repo were staying on .net 8 versions in a .net 9 branch, or .net 9 versions started showing up in the VMR.
