### ISSUE TITLE
Newtonsoft.Json version mismatch in stage 2 for release/8.0.1xx

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#3629]
When building stage 2 for release/8.0.1xx, our CI is failing to build runtime due to a Newtonsoft.Json version mismatch:

```
    /home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj : error NU1605: Warning As Error: Detected package downgrade: Newtonsoft.Json from 13.0.3 to 13.0.1. Reference the package directly from the project to select a different version.  [/home/tester/dotnet/src/runtime/artifacts/source-build/self/src/Build.proj]
    /home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj : error NU1605:  Microsoft.NETCore.Platforms_temp -> NuGet.ProjectModel 6.8.0-rc.32767 -> NuGet.DependencyResolver.Core 6.8.0-rc.32767 -> NuGet.Protocol 6.8.0-rc.32767 -> NuGet.Packaging 6.8.0-rc.32767 -> Newtonsoft.Json (>= 13.0.3)  [/home/tester/dotnet/src/runtime/artifacts/source-build/self/src/Build.proj]
    /home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj : error NU1605:  Microsoft.NETCore.Platforms_temp -> Newtonsoft.Json (>= 13.0.1) [/home/tester/dotnet/src/runtime/artifacts/source-build/self/src/Build.proj]
      Failed to restore /home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj (in 2.68 sec).
    
    Build FAILED.
```

The artifacts tarball from the stage 1 build contains 13.0.3, but the build prefers to have 13.0.1.

cc @MichaelSimons @mthalman @omajid

**Comment by mthalman** [comment]
@tmds - Can you provide a binlog? I see that runtime still has a reference to 13.0.1 but in our CI build, it's not attempting to load that version.

**Comment by mthalman** [comment]
Even though Microsoft.NETCore.App has a reference to 13.0.1 it still uses 13.0.3 because Microsoft.NETCore.App also has a dependency on NuGet.Packaging.6.8.0-rc.32767 which has a dependency on 13.0.3. That's why our CI build hasn't ran into this. @tmds - It's not clear why your build is behaving differently. A binlog should provide clarity there.

**Comment by tmds** [comment]
My stage 2 build is now failing due to https://github.com/dotnet/source-build/issues/3630.

**Comment by tmds** [comment]
> My stage 2 build is now failing due to https://github.com/dotnet/source-build/issues/3630.

I no longer see this issue on the stage 2 build, and the issue that I reported here also no longer reproduces.
