### ISSUE TITLE
SB Release PRs need to target release branch during RC and GA phase

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3633]
During the RC/GA timeframe, a release branch is created in the installer repo (e.g. release/8.0.1xx). All updates for that version of .NET should be targeting that branch. For the 8.0 RC 1 release, the [generated PR](https://github.com/dotnet/installer/pull/17349) for updating source-build config ended up targeting the main branch. This is because the release was marked as a preview release when queuing the build.

Marking a release as preview has the following effect in the release pipeline:
* [Updates the reference URL for the release notes to include `preview` in the path](https://github.com/dotnet/source-build/blob/d3272e646a47287bef1f1dd4b21e86f54dc863c4/eng/create-announcement-draft.sh#L112)
* [Parses out the build number for display purposes](https://github.com/dotnet/source-build/blob/d3272e646a47287bef1f1dd4b21e86f54dc863c4/eng/create-announcement-draft.sh#L114-L116)
* [Targets the main branch for the generated PR](https://github.com/dotnet/source-build/blob/d3272e646a47287bef1f1dd4b21e86f54dc863c4/eng/templates/stages/release.yml#L344)

It's the last item that is problematic here for RC/GA releases.

**Comment by oleksandr-didyk** [comment]
@mthalman I'm guessing we can't just mark RC as a non-preview release, right?

**Comment by mthalman** [comment]
> @mthalman I'm guessing we can't just mark RC as a non-preview release, right?

In my original post I point out the implications of not marking it as a preview. The effects of doing that are not what we want.

**Comment by oleksandr-didyk** [comment]
Oh, my bad, I miss-understood you

We could just look at the type of the release in the PR logic and if its `isPreviewRelease` but the `releaseName` or some other paramater contains `RC` or `GA` switch back to the other flow

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37641

**Comment by oleksandr-didyk** [comment]
PR merged, the pipeline should now target the release branch for RC releases
