### ISSUE TITLE
Upload previous artifacts for Alpine

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3635]
To address https://github.com/dotnet/source-build/issues/3463, we've decided to have one of the CI legs be Alpine317_Offline_PreviousSourceBuiltSdk (stage1/offline/musl/amd64/coreclr/poison).

In order for this leg to function, [we need to update the release automation](https://github.com/dotnet/installer/pull/17370#discussion_r1329175328) to upload the previous Alpine artifacts.

**Comment by mthalman** [comment]
It looks like the only musl-specific package in the smoke test prereqs is microsoft.netcore.app.crossgen2.linux-musl-x64.<runtime-version>.nupkg. The entire prereqs tarball is 200 MB. The musl package is 11 MB. That's a lot of baggage to carry around to just provide access to this single package. On the other hand, including musl prereqs as just another variant to be combined with the others keeps things simple.

**Comment by MichaelSimons** [comment]
> It looks like the only musl-specific package in the smoke test prereqs is microsoft.netcore.app.crossgen2.linux-musl-x64..nupkg. The entire prereqs tarball is 200 MB. The musl package is 11 MB. That's a lot of baggage to carry around to just provide access to this single package. On the other hand, including Alpine prereqs as just another variant to be combined with the others keeps things simple.

I'm not following - isn't this issue about capturing the build artifacts not the smoke-test artifacts?

**Comment by mthalman** [comment]
Yeah, my bad. This is about publishing the build artifacts to https://dotnetcli.azureedge.net/source-built-artifacts/assets. That's done here, currently, with just centos.8-x64: https://github.com/dotnet/source-build/blob/d3272e646a47287bef1f1dd4b21e86f54dc863c4/eng/templates/stages/release.yml#L300-L307

I'm not sure we want to be making these pipeline changes at this stage in the release. I think it'd be better to wait until we've migrated to the new internal pipeline with better validation.

**Comment by MichaelSimons** [comment]
[Triage]  The initial artifacts were uploaded to unblock development work.  The release automation still needs to be updated accordingly but we would prefer to hold off on making release pipeline changes until post 8.0 once we have the release pipeline validation in place.

**Comment by mthalman** [comment]
Note that these changes will need to be made in the internal release pipeline at https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/eng/pipeline/source-build-release.

**Comment by ellahathaway** [comment]
@oleksandr-didyk - Assigning you to this issue since it deals with the internal release pipeline.

We discussed the priority of this issue today during standup, and we think this issue should be resolved by the Feb 9.0 release.

**Comment by oleksandr-didyk** [comment]
Have the changes for this issue completed locally, waiting for https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/36485 to get merged as this work depends on them.

**Comment by mthalman** [comment]
This needs to be fixed for the March release.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37465

**Comment by oleksandr-didyk** [comment]
PR merged, closing
