### ISSUE TITLE
Crossgen breaking poison infra

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3641]
Crossgen is modifying reference assemblies in SBRP by removing the poison marker we added to these files. The removal of the poison marker prevents the detection of leaked files.

**Comment by MichaelSimons** [comment]
[Triage] A quick workaround is to disable crossgen in the CI leg where poison detection is enabled.  A long term solution would be to run leak detection on the assemblies being crossgened before they are actually crossgened

**Comment by ellahathaway** [comment]
If I remember correctly, we added an "originated from SBRP" marker to the source code of the SBRPs (see https://github.com/dotnet/source-build-reference-packages/pull/794). Additionally, the poison infra was adjusted to detect this marker instead of the actual poison marker (see https://github.com/dotnet/installer/pull/17339) for SBRPs.

Along those lines, since the poison infra is no longer relying on the actual poison marker to detect SBRP leaks, I think we can close this issue?

**Comment by mthalman** [comment]
Is this specific to SBRP? Don't we use the poison marker on other types of assemblies as well and wouldn't crossgen disrupt those? Or am I mistaken on how this works?

**Comment by ellahathaway** [comment]
Hm - I was thinking that this was specific to SBRP due to when the build happens & the issue description. I will have to investigate further.

**Comment by MichaelSimons** [comment]
We use the poison marker on the previous artifacts as well.  Is it possible we could crossgen one of them?  If so this issue feels applicable.

**Comment by ellahathaway** [comment]
I've been playing around with this, and it's been a bit difficult to reproduce this issue. In our current build, disabling crossgen did not yield any undetected poison leaks, and it's hard to tell if any PSB .dlls are currently being crossgenned to begin with. As a result, I think that the best path forward with this is going to be to implement a solution that detects poisoning before crossgen occurs, as Michael's original idea stated.

To do this, it will be necessary to run the poison detection before crossgen runs as part of the sdk build. This means that [the detecting target that runs as part of the VMR's finish-source-only.proj](https://github.com/dotnet/dotnet/blob/264d48ec083970a4d2a9180ea9be83725fe48fa7/eng/finish-source-only.proj#L89) will have to be conditioned to run before the [sdk crossgen target](https://github.com/dotnet/sdk/blob/a4f5e274bf21026fe4ab778e5faa9a5f6407e3eb/src/Installer/redist-installer/targets/Crossgen.targets#L4) that runs as part of building sdk. This is what I am currently figuring out how to do.

**Comment by ellahathaway** [comment]
> This means that [the detecting target that runs as part of the VMR's finish-source-only.proj](https://github.com/dotnet/dotnet/blob/264d48ec083970a4d2a9180ea9be83725fe48fa7/eng/finish-source-only.proj#L89) will have to be conditioned to run before the [sdk crossgen target](https://github.com/dotnet/sdk/blob/a4f5e274bf21026fe4ab778e5faa9a5f6407e3eb/src/Installer/redist-installer/targets/Crossgen.targets#L4) that runs as part of building sdk.

I spoke offline with Viktor about if this solution is possible, and he said that "in general this isn't possible as a target in the VMR orchestrator can't run after a specific target inside a VMR repo because of the repo boundaries". 

> Is disabling crossgen as simple as setting some switch in the build? If so, would it be reasonable to just set that switch for the job that checks for poison leaks and have that as the final implementation?

It is that simple. To disable crossgen, we just have to set the `DISABLE_CROSSGEN` property to true. We already do this when `SourceBuildUseMonoRuntime` is true: https://github.com/dotnet/sdk/blob/f5a5171ebb64cd3ea2a8bc53aa37c0a75218f49d/eng/DotNetBuild.props#L18

The simplest solution would be to set the property to true whenever we pass the `--poison` arg to the build script. When doing this, we should be sure to log a message to indicate that crossgen is disabled. That should likely go [here](https://github.com/dotnet/sdk/blob/f5a5171ebb64cd3ea2a8bc53aa37c0a75218f49d/src/SourceBuild/content/build.proj#L29).
