### ISSUE TITLE
Show VMR commit hash under dotnet --info for source-built SDKs

### ISSUE THREAD

**Issue by mateusrodrigues** [dotnet/source-build#3643]
### Describe the Problem

Currently, a source-built .NET SDK displays the commit hash of the installer repo -- the one in `prereqs/git-info/installer.props` -- when you run the command `dotnet --info`, e.g.

```
.NET SDK:
 Version:   8.0.100-rc.1.23455.1
 Commit:    e14caf947f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.10
 OS Platform: Linux
 RID:         ubuntu.23.10-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.100-rc.1.23455.1/
...
```

### Describe the Solution

It would probably make more sense to display the VMR repo commit hash equivalent to the source-tree that generated said SDK when the user types in `dotnet --info`.

### Additional Context

This issue was a result of question #3642.

**Comment by MichaelSimons** [comment]
@omajid - Any interest in picking up this item?  This would benefit distro maintainers as well as Microsoft with the unified build effort.  All builds coming out of the VMR build should be using the VMR's commit hash.

CC @mmitche

**Comment by omajid** [comment]
Is there some way to get the local commit sha inside the VMR? I know in a git repo we can run `git rev-parse HEAD` and in a tarball scenario, we can use [`GIT_DIR/HEAD`](https://github.com/dotnet/dotnet/blob/7cf74ae48c8bb032adf0b10cf106938f5692b7a0/build.sh#L298). Is there some existing generic mechanism that abstracts over these?

**Comment by MichaelSimons** [comment]
We do fake out some .git files when running in a tarball scenario for source-link.  See https://github.com/dotnet/dotnet/blob/main/build.sh#L294.

**Comment by omajid** [comment]
Thanks, that build.sh trick is what I meant by `GIT_DIR/HEAD ` above. That seems consistent with https://github.com/dotnet/sourcelink/tree/main/docs#minimal-git-repository-metadata, so I was wondering if there's a SourceLink msbuild task to extract that value.

**Comment by omajid** [comment]
It looks like the `.version` files, are intertwined with the output of `dotnet --info`.

I can get things to look like this, when building the VMR commit 7cf74ae48c8bb032adf0b10cf106938f5692b7a0 with some changes:

```
$ ./dotnet --info
.NET SDK:
 Version:           9.0.100-preview.3.24157.1
 Commit:            7cf74ae48c
 Workload version:  9.0.100-manifests.4624a33c
 MSBuild version:   17.10.0-preview-24127-03+6f44380e4

Runtime Environment:
 OS Name:     fedora
 OS Version:  39
 OS Platform: Linux
 RID:         fedora.39-x64
 Base Path:   /home/omajid/devel/dotnet/dotnet/dotnet-sdk/sdk/9.0.100-preview.3.24157.1/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.3.24156.25
  Architecture: x64
  Commit:       7cf74ae48c

.NET SDKs installed:
  9.0.100-preview.3.24157.1 [/home/omajid/devel/dotnet/dotnet/dotnet-sdk/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.3.24156.20 [/home/omajid/devel/dotnet/dotnet/dotnet-sdk/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24156.25 [/home/omajid/devel/dotnet/dotnet/dotnet-sdk/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download


$ find -iname '.version' -exec echo {} \; -exec cat {} \;
./shared/Microsoft.NETCore.App/9.0.0-preview.3.24156.25/.version
7cf74ae48c8bb032adf0b10cf106938f5692b7a0
9.0.0-preview.3.24156.25
./shared/Microsoft.AspNetCore.App/9.0.0-preview.3.24156.20/.version
7cf74ae48c8bb032adf0b10cf106938f5692b7a0
9.0.0-preview.3.24156.20
./sdk/9.0.100-preview.3.24157.1/.version
7cf74ae48c8bb032adf0b10cf106938f5692b7a0
9.0.100-preview.3.24157.1
fedora.39-x64
9.0.100-preview.3.24157.1
```

**Comment by omajid** [comment]
Various repos use commit hashes different ways:

- Used by sourcelink to point to sources
- Embedded in `.version` files (aspnetcore, SDK)
- Embedded in unmanaged binaries
- Shown in `dotnet --info`

When building the VMR in .NET 9+, do we want all of them to be the VMR hashes? Is there any reason for any of them to be the per-repo hash?

**Comment by omajid** [comment]
On https://github.com/dotnet/installer/pull/18941, @ViktorHofer said:

> The VMR's commit will be identical with the sdk's and installer's commit as part of the ongoing work during NET 9. I'm not sure if this is then needed at all
