### ISSUE TITLE
[source-build-release] Automate verification of expected release tags

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3662]
In checklist's step 3.e, as a trigger for source-build release process ,we need to verify that 6.0 and 7.0 tags exist in public repos.

There might be a way to automate this so it is integrated in the release pipeline, and aids in usability.

**Comment by oleksandr-didyk** [comment]
This is already being done by the `Validate release tag` step in the `Release` stage. Example of this in the February release run for 6.0: [run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2378136&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=13c737b6-da78-5a0a-c5a4-3c44e112dce6)

There is still a small edge-case where if the release type is manually set to `draft` the tag verification will be skipped for servicing pre-VMR runs. Will fix it

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37553

**Comment by oleksandr-didyk** [comment]
PR merged, closing
