### ISSUE TITLE
Remove net9.0 TFM patches

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3663]
New patches were created in https://github.com/dotnet/installer/pull/17524 for the following repos to update their TFMs to net9.0 explicitly instead of using the `$(NetCurrent)` because arcade still defines `NetCurrent` as `net8.0`. Once this is updated and rolled out (https://github.com/dotnet/arcade/pull/14108), these patches should be removed. 

- [ ] razor
- [x] format
- [ ] fsharp: https://github.com/dotnet/fsharp/issues/16596
- [ ] roslyn
- [x] vstest
- [ ] sdk
- [x] source-build-reference-packages
- [ ] runtime

**Comment by MichaelSimons** [comment]
Can this be linked to a tracking arcade issue/PR to updated the tfm?

**Comment by mthalman** [comment]
> Can this be linked to a tracking arcade issue/PR to updated the tfm?

Done. Updated the original description with a link.
