### ISSUE TITLE
[VMR] Create requirements around how builds should be triggered

### ISSUE THREAD

**Issue by steveisok** [dotnet/source-build#3672]
We need to make it clear the requirements that each repo in the VMR needs to fulfill in order to participate in the overall build. This serves as a tracking issue for that work.

**Comment by jaredpar** [comment]
Couple of items that I think need to be solved:

build.sh / .cmd level: 
1. method of specifying `dotnet` 
2. method of controlling the sdk version (or are we just stomping global.json)
3. method to specify it's the vmr build so full product assets should be produced. Many builds for example don't produce .nupkg by default today
4. is restoring implicit when (3) is passed?
5. do we need to support debug / release type flags?
6. are we using build.cmd/sh in the root or will we have say `eng/vmr-build.cmd/sh`?
7. method of specifying binary logs (we are **really** going to want that so we can track down build issues in this complex build)

msbuild props level: 
1. prop similar to `$(DotNetBuildFromSource)` to indicate we're in a vmr build so we can condition the build. Example is roslyn probably conditions out all of their VS integration layers for a full VMR build
2. prop specifying the ideal `<TargetFramework>` version for the vmr build. Similar in function to `$(NetCurrent)`. 
3. do we need to push down ideal RIDs?
