### ISSUE TITLE
Get application-insights updated to a production build later than 2.4.0

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#368]
app-insights in source-build it based on a special tag (v2.4.0-sourcebuild), which is a small update to a production release 9 months ago.  The cli dependency should get updated to a later release (2.5.1?) and source-build and cli should be in sync.

**Comment by MichaelSimons** [comment]
[Triage] Closing - Source-build for 7.0 is using App Insights version 2.14.1
