### ISSUE TITLE
Remove obsolete gather-prereqs script

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3692]
This script, [gather-prereqs.sh](https://github.com/dotnet/source-build/blob/main/eng/gather-prereqs.sh) is no longer referenced by release documentation and its purpose is better served anyways by [combine-tarballs.sh](https://github.com/dotnet/source-build/blob/main/eng/combine-tarballs.sh). It should be removed.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35131

**Comment by oleksandr-didyk** [comment]
> > PR - [dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35131](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35131)
> 
> The same deletion needs to be made in the GitHub repo as well.

Good point, thank you. Will do

**Comment by oleksandr-didyk** [comment]
Both PRs merged, closing as `Done`
