### ISSUE TITLE
Generated .version file for source build artifacts not working with stable versioning

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3693]
The changes in https://github.com/dotnet/installer/pull/17625 caused a test failure which validates the content of the .version file that gets generated for the source build artifacts:

```
Assert.Equal() Failure
↓ (pos 7)
Expected: 8.0.100
Actual:   8.0.100-rtm.23527.1
↑ (pos 7)

 at Microsoft.DotNet.SourceBuild.SmokeTests.SourceBuiltArtifactsTests.VerifyVersionFile() in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/SourceBuiltArtifactsTests.cs:line 61
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

This is because that PR introduced stable versioning for installer. This conflicts with the [logic which populates that .version file](https://github.com/dotnet/installer/blob/fb7c9717cfd661b120e900a073c60a8fc9e898da/src/SourceBuild/content/repo-projects/package-source-build.proj#L63). That uses the version of installer's source build intermediate which is not stable versioned.

**Comment by mthalman** [comment]
A change was made to disable this check in the test to unblock the PR: https://github.com/dotnet/installer/pull/17625/commits/b49f63c76cb30a0cf9e7bcca5d17f5681b6763ac It should be re-enabled when fixing this issue.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - Is this something you can help out with?  I'd like to see a fix if plausible be included in Dec servicing.  TIA

**Comment by mthalman** [comment]
A simpler solution would be to just extract the `.version` file from the MS SDK and use the version from that. That will always keep it in alignment.

**Comment by NikolaMilosavljevic** [comment]
> A simpler solution would be to just extract the `.version` file from the MS SDK and use the version from that. That will always keep it in alignment.

Do we still want to use the 'unstable' version in PSB artifact name, or should that also match the SDK version?

https://github.com/dotnet/installer/blob/fb7c9717cfd661b120e900a073c60a8fc9e898da/src/SourceBuild/content/repo-projects/package-source-build.proj#L57C15-L57C15
```
<SourceBuiltTarballName>$(OutputPath)$(SourceBuiltArtifactsTarballName).$(MicrosoftSourceBuildIntermediateInstallerVersion).$(TargetRid).tar.gz</SourceBuiltTarballName>
```

**Comment by mthalman** [comment]
> Do we still want to use the 'unstable' version in PSB artifact name, or should that also match the SDK version?

I think we'd want to match the SDK version.

> By 'MS SDK' I presume this was referring to dotnet-sdk-*.tar.gz package built in source-build.

Sorry, yes. I meant the source-built SDK.

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/installer/pull/17819
