### ISSUE TITLE
Provide some guidelines to package pdbs.

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#3697]
Prior to .NET 8, the pdbs that were created as part of the build weren't usable because they referenced the source files that were used during the distro packaging.

.NET 8 produces usable pdbs thanks to source-link (which makes pdbs reference the code at https://github.com/dotnet/dotnet).

The pdbs get bundled in a tarfile that is output by the vmr build.
The tarball matches the layout of the .NET installation.
For example, this is the contents of a this tarball for an 8.0 build:

```
584K	packs/Microsoft.AspNetCore.App.Ref
12M	packs/Microsoft.AspNetCore.App.Runtime.fedora.37-x64
1.3M	packs/Microsoft.NETCore.App.Ref
21M	packs/Microsoft.NETCore.App.Runtime.fedora.37-x64
92M	sdk/8.0.100-rtm.23527.1
12M	shared/Microsoft.AspNetCore.App
21M	shared/Microsoft.NETCore.App
```

We should add some guidelines to [packaging guideline](https://learn.microsoft.com/en-us/dotnet/core/distribution-packaging) that describe how to package these files.

cc @MichaelSimons @omajid @dotnet/distro-maintainers

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - Is this something you can help drive?

**Comment by omajid** [comment]
I don't know if it's possible (let alone easy), but my first thought is that we should treat pdb files (managed debug info) the same as unmanaged debug info - by putting them in the distro-specific `-debuginfo`/`-dbg` packages?

**Comment by NikolaMilosavljevic** [comment]
I believe debug packages (DEB/RPM) should follow the existing packaging guidance, for .NET content split. For instance `dotnet-sdk` package contains just the SDK content, but not the shared runtime or host content.

I was thinking of something like the following, at the end of `Recommended packages` section: https://github.com/dotnet/docs/blob/main/docs/core/distribution-packaging.md

----------
Debug content should be packaged in debug-named packages that follow the .NET package split described above. For instance, `dotnet-sdk` specific debug content should be included in a package named `dotnet-sdk-dbg`. Debug content should be installed to the same location as the binaries.

Here's one example:

In `{dotnet_root}/sdk/<sdk version>` directory, we'd expect the following two files:

`dotnet.dll` - installed with `dotnet-sdk` package
`dotnet.pdb` - installed with `dotnet-sdk-dbg` package

**Comment by mateusrodrigues** [comment]
@omajid that was our first thought, too. However, in our case at least, `-dbg` packages are meant -- or expected -- to contain ELF/DWARF files, not PDBs. Even the tooling that exists to build these packages is set up along those lines.

Not sure if there's a way to "force" the creation of such packages with arbitrary content, but I'm asking around to see what's best in this case. If not, we can always just create debug-named binary packages with their respective contents.

**Comment by tmds** [comment]
@NikolaMilosavljevic what you proposed sounds like a good solution. Can you look into updating the packaging documentation?

**Comment by tmds** [comment]
Looking a bit closer at the pdbs that are available and splitting them up.
```
584K	packs/Microsoft.AspNetCore.App.Ref
12M	packs/Microsoft.AspNetCore.App.Runtime.fedora.37-x64
1.3M	packs/Microsoft.NETCore.App.Ref
21M	packs/Microsoft.NETCore.App.Runtime.fedora.37-x64
```
I don't think the Runtime pack dlls are ever used, and that the Ref pack dlls can be usable. So it makes no sense to package them.
```
12M	shared/Microsoft.AspNetCore.App
21M	shared/Microsoft.NETCore.App
```
These are useful to allow an end-user to step into the runtime sources.
```
92M	sdk/8.0.100-rtm.23527.1
```
This is for debugging the SDK. This is of limited usability for the end-user.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic what you proposed sounds like a good solution. Can you look into updating the packaging documentation?

Sounds good - working on this now.
