### ISSUE TITLE
[VMR] linux/mac-arm64 cross build fails w/ CoreCLR runtime

### ISSUE THREAD

**Issue by steveisok** [dotnet/source-build#3698]
### Describe the Bug
When triggering a building targeting arm64 from a linux or mac x64 host, the VMR build will fail at runtime with the following error:

```
      [ 29%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/EHHelpers.cpp.o
      [ 29%] Building CXX object pal/src/CMakeFiles/coreclrpal.dir/thread/threadsusp.cpp.o
      /Users/steve/dev/dotnet-vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/pal/src/synchmgr/synchmanager.cpp:4633:6: error: "Don't know how to get hi-res current time on this platform"
          #error "Don't know how to get hi-res current time on this platform"
           ^
      [ 30%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.WorkstationGC.dir/__/MethodTable.cpp.o
      1 error generated.
      make[2]: *** [pal/src/CMakeFiles/coreclrpal.dir/synchmgr/synchmanager.cpp.o] Error 1
      make[2]: *** Waiting for unfinished jobs....
```

### Steps to Reproduce
- Apply the patch @directhex made in https://github.com/dotnet/source-build/issues/3671#issuecomment-1783079761

- Build the VMR

For Mac:
```
./prep.sh 
./build.sh --online -- /p:OverrideTargetRid=osx-arm64
```

For Linux:
```
docker run -e CROSSCOMPILE=1 -e ROOTFS_DIR=/crossrootfs/arm64 -w pwd--platform linux/amd64 -vpwd:pwd -it mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm64 
./build.sh --online -- /p:OverrideTargetRid=linux-arm64
```

**Comment by steveisok** [comment]
@jtschuster @agocke looping you guys in too

**Comment by jtschuster** [comment]
I have a build finished and the arm64 sdk runs on my machine with qemu. 
I've made a PR on my fork with the diff for reference: https://github.com/jtschuster/dotnet/pull/1

I have dotnet/dotnet cloned at /src/dotnet in wsl, then ran 
```
> docker run -e ROOTFS_DIR=/crossrootfs/arm64 -w /src/dotnet --platform linux/amd64 -v \\wsl.localhost\Ubuntu\src\dotnet:/src/dotnet -it mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm64
$ ./prep.sh && ./build.sh --online -- /p:OverrideTargetRid=linux-arm64 /p:OverrideTargetArch=arm64
```

**Comment by jtschuster** [comment]
The issue requiring workarounds is that we don't specify the build machine's runtime pack as a prerequisite and runtime is told not to download packages (`DotNetBuildOffline = true`), even using `--online` at the root. The in-build crossgen and ilc are published self-contained, but without the runtime pack, they don't run. I've added workarounds for this so that the build can finish (see mentions above), but it's probably not what we want to ship. I can't figure out how to declare source-build prerequisites to properly fix this, can anyone point me to that?

**Comment by jtschuster** [comment]
Made https://github.com/dotnet/source-build/issues/3793 to track reenabling crossgen and ilc.
