### ISSUE TITLE
Release pipeline should retain referenced tarball pipeline run

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3700]
During work on https://github.com/dotnet/arcade-services/issues/2671 we encountered an issue where the tarball pipeline run (referenced by the source-build release pipeline when working with a servicing release) was not retained and caused failures for the test / validation runs.

Unlike the `dotnet-installer-official` run that is retained by the staging pipeline, the tarball one is not used by staging and does not get retained.

We should retain the runs we used in a successful servicing release (for example, as the last optional step of the `Release` stage)

**Comment by MichaelSimons** [comment]
[Triage] We should investigate if there is a policy around this and adhere to the policy.  It feels like a good decision to retain the release builds.  This should be an automated process, not a manual step in the checklist.

@oleksandr-didyk - please follow-up to see if a similar issue exists for the VMR.

**Comment by oleksandr-didyk** [comment]
Received confirmation that input builds to the release should be retained at least 3 years (currently we just retain these builds forever in AzDO).

The staging pipeline has a dedicated command in the Release CLI for retaining builds, will try to re-use it and introduce the Release CLI into the source-build pipeline as part of this work.

**Comment by oleksandr-didyk** [comment]
Draft PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35205

**Comment by oleksandr-didyk** [comment]
Went through initial feedback, published PR

**Comment by oleksandr-didyk** [comment]
Received a suggestion on moving the retention into a different stage, working on it

**Comment by oleksandr-didyk** [comment]
PR merged, closing as `Done`
