### ISSUE TITLE
[VMR][mono] Check in AOT offsets file(s), remove offsets jobs from official build

### ISSUE THREAD

**Issue by steveisok** [dotnet/source-build#3701]
In the runtime official build, the first step in building mono cross compilers requires generating offset files in a separate job and is later consumed in another job that produces the binaries. This approach makes a VMR vertical build more difficult because we cannot express "build all artifacts for linux-arm64" in one go without depending on a separate job. 

- [x] Produce offset files locally and check them into the runtime repo
- [x] Adjust build to pick them up from the source tree instead of where azdo places them now
- [x] Add some kind of validation job to make sure the offset files are up to date

**Comment by mmitche** [comment]
@akoeplinger What's the status of this?
