### ISSUE TITLE
[VMR] CI pipelines for official Vertical Builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3709]
Create CI pipelines that run on every VMR commit that build the vertical builds. Note that this is for the productized vertical build, not the PoCs.

CI pipelines should (if possible):
- Use standard arcade templates
- Enable BAR publishing at the end of the build.

**T-Shirt Size: Medium**

**Comment by mmitche** [comment]
T-Shirt Size; Medium

**Comment by akoeplinger** [comment]
We now have pipelines, but they don't do BAR publishing yet.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/arcade-services/issues/3280
