### ISSUE TITLE
SBRP Attribute is a MethodDefinition for System.Runtime.4.3.1.nupkg/ref/netstandard1.3/System.Runtime.dll

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3713]
The SBRP attribute added in https://github.com/dotnet/source-build/issues/3639 is classified as `attribute.Constructor.Kind == HandleKind.MemberReference` for every package except for System.Runtime.4.3.1.nupkg/ref/netstandard1.3/System.Runtime.dll. For this runtime reference assembly, the SBRP attribute is classified as `attr.Constructor.Kind == HandleKind.MethodDefinition`.

This requires further investigation to determine why the attribute is classified differently in this assembly than every other assembly. Additionally, poison tests that check for the SBRP attribute should be adjusted to account for this difference.

**Comment by MichaelSimons** [comment]
[Triage] In discussing, we feel there is value in updating the poison infra to account for this different kind right away.  That change should be backported to 8.0.
