### ISSUE TITLE
Mono build leg failure: conflicting information about runtime packs

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3722]
The VMR is failing in the main branch with the following error in the `CentOSStream8_Mono_Offline_MsftSdk_x64` build leg:

```
/vmr/.dotnet/sdk/9.0.100-alpha.1.23524.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1133: There was conflicting information about runtime packs available for Microsoft.NETCore.App:Mono: [/vmr/src/runtime/artifacts/source-build/self/src/Build.proj]
/vmr/.dotnet/sdk/9.0.100-alpha.1.23524.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1133: Microsoft.NETCore.App.Runtime.Mono.**RID** [/vmr/src/runtime/artifacts/source-build/self/src/Build.proj]
/vmr/.dotnet/sdk/9.0.100-alpha.1.23524.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1133: Microsoft.NETCore.App.Runtime.Mono.**RID** [/vmr/src/runtime/artifacts/source-build/self/src/Build.proj]
```

**Comment by mthalman** [comment]
@dsplaisted - Any idea on what might be the issue here? We're still trying to get the main branch working for source build after all the net9.0 changes and this is one of them. Here's a binlog: [mono.runtime.zip](https://github.com/dotnet/source-build/files/13282501/mono.runtime.zip). Unfortunately, the failure occurs as a result of the task being called during `Restore` so the binlog doesn't show the details within the restore of the task call. But I'm hoping you might have some more insight on this.

**Comment by dsplaisted** [comment]
It looks like that error would happen if the `KnownRuntimePack` item for the Mono runtime was duplicated.  I don't see why that would be happening though.

Normally we would get more details about a task that failed during restore in the binlog.  Does that not happen with static graph?  Could you do a restore without static graph and see if the same error is generated?

**Comment by mthalman** [comment]
`RestoreUseStaticGraphEvaluation` is true and `RESTORE_TASK_BINLOG_PARAMETERS` is set to a path but that path is never written to.

When attempting to disable static graph evaluation, I get a different error:

```
/repos/dotnet/src/runtime/artifacts/source-build/self/src/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.props(179,3): error MSB4019: The imported project "/repos/dotnet/src/runtime/artifacts/source-build/self/src/artifacts/bin/Crossgen2Tasks/Release/net8.0/Microsoft.NET.CrossGen.props" was not found. Confirm that the expression in the Import declaration "/repos/dotnet/src/runtime/artifacts/source-build/self/src/artifacts/bin/Crossgen2Tasks/Release/net8.0/Microsoft.NET.CrossGen.props" is correct, and that the file exists on disk. [/repos/dotnet/src/runtime/artifacts/source-build/self/src/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
```

In that case there is no `/repos/dotnet/src/runtime/artifacts/source-build/self/src/artifacts/bin` directory at all.

**Comment by mthalman** [comment]
Thanks to @sbomer, I've got a binlog for the restore: [Restore-Build.proj.zip](https://github.com/dotnet/source-build/files/13298452/Restore-Build.proj.zip)

There are indeed two `KnownRuntimePacks` for `Microsoft.NETCore.App.Runtime.Mono.**RID**` with `net9.0` TFM:

![image](https://github.com/dotnet/source-build/assets/15789599/93de52e9-2d2c-4282-a85a-173ee251ab97)

**Comment by mthalman** [comment]
I think the second one is being produced because of this: https://github.com/dotnet/runtime/blob/ac56247d2e04d74d1e92a20b3c6c67fd3b368b8b/eng/targetingpacks.targets#L51-L58

/cc @ViktorHofer

**Comment by ViktorHofer** [comment]
A bug in our build system with a recent refactoring. Submitted https://github.com/dotnet/runtime/pull/94524 to fix this.
