### ISSUE TITLE
Offline VMR builds failing in arcade

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3729]
`
##[error]/vmr/src/arcade/artifacts/source-build/self/src/src/Microsoft.DotNet.Build.Tasks.Packaging/src/Microsoft.DotNet.Build.Tasks.Packaging.csproj(0,0): error NU1603: (NETCORE_ENGINEERING_TELEMETRY=Restore) Warning As Error: Microsoft.DotNet.Build.Tasks.Packaging depends on Microsoft.Extensions.FileProviders.Abstractions (>= 8.0.0-preview.4.23259.5) but Microsoft.Extensions.FileProviders.Abstractions 8.0.0-preview.4.23259.5 was not found. An approximate best match of Microsoft.Extensions.FileProviders.Abstractions 8.0.0-rc.2.23475.17 was resolved.
`

This is a regression that showed up in https://github.com/dotnet/dotnet/compare/3b48d00b46430d73172ea5f70b2e1569a2235925..cbb3431e4c65760b8e8bd3e1c8d3cd9be861897d

**Comment by mthalman** [comment]
This seems to be caused by the removal of a `NoWarn` for NU1603 in https://github.com/dotnet/installer/pull/17712

**Comment by mthalman** [comment]
It'd be good to understand why this isn't caught in the online builds and whether we need to reintroduce an offline leg in PR builds.

**Comment by MichaelSimons** [comment]
> It'd be good to understand why this isn't caught in the online builds and whether we need to reintroduce an offline leg in PR builds.

It was detected as a prebuild.  The problem is that the [online prebuilts check](https://github.com/dotnet/source-build/issues/3665#issuecomment-1771569337) was disabled because there are currently prebuilts.

**Comment by mthalman** [comment]
Yeah, it might be good to have offline builds turned back on until we can eliminate the prebuilts.

**Comment by NikolaMilosavljevic** [comment]
This is odd. I've validated full set of VMR builds, although that was done for release/8.0.1xx: https://dev.azure.com/dnceng/internal/_build/results?buildId=2309593&view=results

**Comment by mthalman** [comment]
That's because this dependency was only added to the main branch in arcade, not release/8.0.

**Comment by NikolaMilosavljevic** [comment]
Would it make most sense to introduce the patch for Arcade? I'd be hesitant to reintroduce global nowarns.

**Comment by NikolaMilosavljevic** [comment]
This was introduced by https://github.com/dotnet/arcade/pull/14159, which added two new package dependencies, but did not update `Version.Details.xml`.

The fix is simple - add the following to `arcade`'s `Version.Details.xml`:
```
    <Dependency Name="Microsoft.Extensions.FileProviders.Abstractions" Version="8.0.0-preview.4.23259.5">
      <Uri>https://github.com/dotnet/runtime</Uri>
      <Sha>547c506abe05e510bd43330fc8f6d4c5961e9223</Sha>
      <SourceBuild RepoName="runtime" ManagedOnly="false" />
    </Dependency>
    <Dependency Name="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0-preview.4.23259.5">
      <Uri>https://github.com/dotnet/runtime</Uri>
      <Sha>547c506abe05e510bd43330fc8f6d4c5961e9223</Sha>
      <SourceBuild RepoName="runtime" ManagedOnly="false" />
    </Dependency>
```

My local build has passed the failure point - waiting till completion.

Should we do a patch + Arcade PR, or just the Arcade PR?

**Comment by MichaelSimons** [comment]
I would just fix arcade.  It flows quickly into installer.

**Comment by MichaelSimons** [comment]
It would be good to know how come the arcade PR that introduced these prebuilts didn't fail the prebuild detection.

**Comment by NikolaMilosavljevic** [comment]
Well, hitting similar issues in `aspnetcore` - bunch of the following, same ILLInk.Tasks dependency:

  _/src/git/dotnet/src/aspnetcore/artifacts/source-build/self/src/src/Middleware/WebSockets/src/Microsoft.AspNetCore.WebSockets.csproj : error NU1603: Warning As Error: Microsoft.AspNetCore.WebSockets depends on **Microsoft.NET.ILLink.Tasks (>= 9.0.0-alpha.1.23523.13)** but Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23523.13 was not found. An approximate best match of Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23558.3 was resolved. [/src/git/dotnet/.dotnet/sdk/9.0.100-alpha.1.23524.3/NuGet.targets]_

**Comment by NikolaMilosavljevic** [comment]
> It would be good to know how come the arcade PR that introduced these prebuilts didn't fail the prebuild detection.

Puzzling - the only reported prebuilts are `Microsoft.CodeAnalysis.*` which are excluded: https://github.com/dotnet/arcade/blob/e44acabb3a3beadeb45aacfda4d0f4c33a45b5d7/eng/SourceBuildPrebuiltBaseline.xml#L18

Looking deeper into this...

**Comment by directhex** [comment]
I think I'm experiencing something related when cross-building VMR main on Mariner:

```
    /home/directhex/Projects/dotnet/src/source-build-reference-packages/artifacts/source-build/self/src/src/targetPacks/ILsrc/microsoft.netcore.app.ref/3.1.0/microsoft.netcore.app.ref.3.1.0.csproj : error NU1603: microsoft.netcore.app.ref.3.1.0 depends on runtime.linux-x64.Microsoft.NETCore.ILAsm (>= 8.0.0-rc.2.23475.17) but runtime.linux-x64.Microsoft.NETCore.ILAsm 8.0.0-rc.2.23475.17 was not found. An approximate best match of runtime.linux-x64.Microsoft.NETCore.ILAsm 8.0.0-rc.2.23479.6 was resolved. [/home/directhex/Projects/dotnet/.dotnet/sdk/9.0.100-alpha.1.23524.3/NuGet.targets]
[..]
    /home/directhex/Projects/dotnet/src/source-build-reference-packages/artifacts/source-build/self/src/src/targetPacks/Directory.Build.targets(110,5): error : Package runtime.linux-x64.microsoft.netcore.ilasm\8.0.0-rc.2.23475.17 was not restored [/home/directhex/Projects/dotnet/src/source-build-reference-packages/artifacts/source-build/self/src/src/targetPacks/ILsrc/microsoft.aspnetcore.app.ref/6.0.2/Microsoft.AspNetCore.App.Ref.6.0.2.csproj]
[..]
        0 Warning(s)
        1551 Error(s)
```

I have `./prereqs/packages/previously-source-built/runtime.centos.8-x64.Microsoft.NETCore.ILAsm.8.0.0-rc.2.23475.17.nupkg` on disk, but `--online` is offering me `./src/source-build-reference-packages/artifacts/source-build/self/package-cache/runtime.linux-x64.microsoft.netcore.ilasm/8.0.0-rc.2.23479.6/runtime.linux-x64.microsoft.netcore.ilasm.8.0.0-rc.2.23479.6.nupkg` (which is the version from nuget.org). I assume NU1603 suppression previously masked this kind of mismatch

**Comment by NikolaMilosavljevic** [comment]
> It would be good to know how come the arcade PR that introduced these prebuilts didn't fail the prebuild detection.

I believe this is due to the following: https://github.com/dotnet/arcade/blob/ca9cbe745f8fe5089fb9b8bd52c4caec21df74a1/eng/Version.Details.xml#L77-L83
```
    <!-- Latest preview version required by source-build. The dependency is loaded in during built-time
         by consumers of SharedFramework.Sdk (such as runtime), so we cannot use a ref pack for it -->
    <Dependency Name="Microsoft.Extensions.DependencyModel" Version="8.0.0-preview.4.23259.5">
      <Uri>https://github.com/dotnet/runtime</Uri>
      <Sha>547c506abe05e510bd43330fc8f6d4c5961e9223</Sha>
      <SourceBuild RepoName="runtime" ManagedOnly="false" />
    </Dependency>
```

Runtime intermediate package content would end up in source-build cache as previously source-built content. Those packages would then be excluded from prebuilt detection with: https://github.com/dotnet/arcade/blob/4e45875aa2653ec78e718431d873f5be6e9c991f/src/Microsoft.DotNet.SourceBuild/tasks/src/UsageReport/WritePackageUsageData.cs#L129

**Comment by NikolaMilosavljevic** [comment]
> Well, hitting similar issues in `aspnetcore` - bunch of the following, same ILLInk.Tasks dependency:
> 
> _/src/git/dotnet/src/aspnetcore/artifacts/source-build/self/src/src/Middleware/WebSockets/src/Microsoft.AspNetCore.WebSockets.csproj : error NU1603: Warning As Error: Microsoft.AspNetCore.WebSockets depends on **Microsoft.NET.ILLink.Tasks (>= 9.0.0-alpha.1.23523.13)** but Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23523.13 was not found. An approximate best match of Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23558.3 was resolved. [/src/git/dotnet/.dotnet/sdk/9.0.100-alpha.1.23524.3/NuGet.targets]_

@MichaelSimons @mthalman can we add this version of ILLink.Tasks package to prebuilts package? We already have these 2 in prebuilts package, so it seems that this is a known issue or at least a moving target:
```
microsoft.net.illink.tasks.8.0.0-preview.7.23375.6.nupkg
microsoft.net.illink.tasks.9.0.0-alpha.1.23470.17.nupkg
```

**Comment by NikolaMilosavljevic** [comment]
> > Well, hitting similar issues in `aspnetcore` - bunch of the following, same ILLInk.Tasks dependency:
> > _/src/git/dotnet/src/aspnetcore/artifacts/source-build/self/src/src/Middleware/WebSockets/src/Microsoft.AspNetCore.WebSockets.csproj : error NU1603: Warning As Error: Microsoft.AspNetCore.WebSockets depends on **Microsoft.NET.ILLink.Tasks (>= 9.0.0-alpha.1.23523.13)** but Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23523.13 was not found. An approximate best match of Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23558.3 was resolved. [/src/git/dotnet/.dotnet/sdk/9.0.100-alpha.1.23524.3/NuGet.targets]_
> 
> @MichaelSimons @mthalman can we add this version of ILLink.Tasks package to prebuilts package? We already have these 2 in prebuilts package, so it seems that this is a known issue or at least a moving target:
> 
> ```
> microsoft.net.illink.tasks.8.0.0-preview.7.23375.6.nupkg
> microsoft.net.illink.tasks.9.0.0-alpha.1.23470.17.nupkg
> ```

I think the correct plan is to replace `microsoft.net.illink.tasks.9.0.0-alpha.1.23470.17.nupkg` with `microsoft.net.illink.tasks.9.0.0-alpha.1.23523.13.nupkg` in our prebuilts package (v4). We have added `microsoft.net.illink.tasks.9.0.0-alpha.1.23470.17.nupkg` to prebuilts v3, with https://github.com/dotnet/installer/commit/cfc4c38e0d0eb50914cab983b7d85b4352d74f29, due to `aspnetcore` dependencies - see tracking issue: https://github.com/dotnet/source-build/issues/3665

I'm going to test this locally before sending PR.

**Comment by NikolaMilosavljevic** [comment]
> > > Well, hitting similar issues in `aspnetcore` - bunch of the following, same ILLInk.Tasks dependency:
> > > _/src/git/dotnet/src/aspnetcore/artifacts/source-build/self/src/src/Middleware/WebSockets/src/Microsoft.AspNetCore.WebSockets.csproj : error NU1603: Warning As Error: Microsoft.AspNetCore.WebSockets depends on **Microsoft.NET.ILLink.Tasks (>= 9.0.0-alpha.1.23523.13)** but Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23523.13 was not found. An approximate best match of Microsoft.NET.ILLink.Tasks 9.0.0-alpha.1.23558.3 was resolved. [/src/git/dotnet/.dotnet/sdk/9.0.100-alpha.1.23524.3/NuGet.targets]_
> > 
> > 
> > @MichaelSimons @mthalman can we add this version of ILLink.Tasks package to prebuilts package? We already have these 2 in prebuilts package, so it seems that this is a known issue or at least a moving target:
> > ```
> > microsoft.net.illink.tasks.8.0.0-preview.7.23375.6.nupkg
> > microsoft.net.illink.tasks.9.0.0-alpha.1.23470.17.nupkg
> > ```
> 
> I think the correct plan is to replace `microsoft.net.illink.tasks.9.0.0-alpha.1.23470.17.nupkg` with `microsoft.net.illink.tasks.9.0.0-alpha.1.23523.13.nupkg` in our prebuilts package (v4).
> 
> We have added `microsoft.net.illink.tasks.9.0.0-alpha.1.23470.17.nupkg` to prebuilts v3, with [dotnet/installer@cfc4c38](https://github.com/dotnet/installer/commit/cfc4c38e0d0eb50914cab983b7d85b4352d74f29), due to `aspnetcore` dependencies - see tracking issue: #3665
> 
> I'm going to test this locally before sending PR.

OK - this worked fine locally. I will create a v4 prebuilts package and send the PR.

**Comment by NikolaMilosavljevic** [comment]
Missing arcade changes (https://github.com/dotnet/arcade/pull/14214) have flown to installer with https://github.com/dotnet/installer/pull/17764

Together with https://github.com/dotnet/installer/pull/17763, it completes the fix for offline build.
