### ISSUE TITLE
Restore online tarball build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#373]
Once we have everything working and will hopefully not need to compare build errors between online and offline tarball builds, we should be able to just remove the online tarball builds.

**Comment by dleeapho** [comment]
Please do in all branches.

**Comment by crummel** [comment]
2.1 and master done, waiting for the auto-merge for 2.2.

**Comment by omajid** [comment]
As discussed in https://github.com/dotnet/source-build/pull/653, I dont think this change is a good idea if it can leave people who are building the tarball when not offline in a broken state.

**Comment by crummel** [comment]
Yup, we need to keep these.  Reversion PRs are https://github.com/dotnet/source-build/pull/705 and https://github.com/dotnet/source-build/pull/706.

**Comment by crummel** [comment]
Fixed in PRs above.
