### ISSUE TITLE
Unify tagging for mirroring and release stages

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3736]
Related to https://github.com/dotnet/source-build/issues/3496

Currently both mirroring and release stage are tagging the same build commit with the same tag and pushing it to a remote (mirroring to `dotnet-security-partners/dotnet`, release to the public `VMR`). They are also using two different scripts to achieve this.

We should unify this step under one logic to guarantee that we don't accidently change only one of them in the future, resulting in a miss-match between what we published publicly versus what we handed off to partners.

We could utilize the Release CLI for this by just adding a single command and using it in both stages.

**Comment by MichaelSimons** [comment]
Given this only affect 6.0 and 7.0 there is limited ROI.  Additionally https://github.com/dotnet/source-build/issues/4131 covers testing to ensure the tags are consistent.  Consider closing as won't fix.

**Comment by MichaelSimons** [comment]
[Triage] Will use https://github.com/dotnet/arcade-services/issues/2673 to track integrating this logic into the release CLI.
