### ISSUE TITLE
Remove temporary .NET 9 SDK bootstrapping changes

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3743]
In order to [update the VMR to consume the .NET 9 SDK](https://github.com/dotnet/source-build/issues/3721#issuecomment-1814957322), there are a number of temporary changes that are needed due to Arcade not yet being completely updated to .NET 9 (related to https://github.com/dotnet/arcade/pull/14108). These changes should all be reverted when Arcade is fully updated.

**Comment by mthalman** [comment]
The changes for this can now be worked on now that https://github.com/dotnet/installer/pull/17985 has been merged. That change removes all the Arcade patches. There's just a few hacks that need to be removed, all which reference this issue URL in the source.

**Comment by ViktorHofer** [comment]
This got completed with https://github.com/dotnet/installer/pull/18214
