### ISSUE TITLE
Winforms binaries introduced into VMR

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3745]
The following binaries from the winforms repo were introduced into the VMR by https://github.com/dotnet/installer/pull/17746:

```
src/winforms/src/System.Windows.Forms.Design/src/Resources/colordlg.data
src/winforms/src/System.Windows.Forms/src/Resources/System/Windows/Forms/Design/Thumbs.db
```

These need to be removed.

**Comment by MichaelSimons** [comment]
[Triage] @ViktorHofer is this something you can address?

**Comment by ViktorHofer** [comment]
What's the recommend pattern for these? Excluding them from the VMR sync? cc @premun

**Comment by mthalman** [comment]
Related to https://github.com/dotnet/source-build/issues/3774

**Comment by mmitche** [comment]
Also part of https://github.com/dotnet/source-build/issues/3738

This is in included in that t-shirt size costing.

**Comment by mthalman** [comment]
These files are cloaked from the VMR as part of https://github.com/dotnet/installer/pull/18280. There needs to be follow up to not rely on having these files exist in the repo.

**Comment by mmitche** [comment]
Based on conversations, it's likely that cloaking will continue to be a thing for UB.
