### ISSUE TITLE
WPF binaries introduced into the VMR

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3746]
The following binaries from the wpf repo were introduced into the VMR by https://github.com/dotnet/installer/pull/17746:

```
src/wpf/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/Hyphenation/Hyphen_en.hdict
src/wpf/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/Hyphenation/Hyphen_en.lex
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_ContentTypes.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_CoreProperties.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_DiscardControl.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_DocStructure.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_OPC_DigSig.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_Relationships.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_S0.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_SignatureDefinitions.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_Versioning.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/ReachFramework/Resources/generated/Schemas_xmldsig-core-schema.resources
src/wpf/src/Microsoft.DotNet.Wpf/src/Shared/Tracing/resources/MSG00001.bin
src/wpf/src/Microsoft.DotNet.Wpf/src/Shared/Tracing/resources/wpf-etwTEMP.BIN
src/wpf/src/Microsoft.DotNet.Wpf/src/WpfGfx/core/geometry/Scanner.doc
```

These need to be removed.

**Comment by MichaelSimons** [comment]
[Triage] @ViktorHofer is this something you can address?

**Comment by mmitche** [comment]
Also part of https://github.com/dotnet/source-build/issues/3738

This is in included in that t-shirt size costing.

**Comment by mthalman** [comment]
These files are cloaked from the VMR as part of https://github.com/dotnet/installer/pull/18280. There needs to be follow up to not rely on having these files exist in the repo.

**Comment by omajid** [comment]
Shall I do a PR to allow `Scanner.doc`? We [allow `.docx` files](https://github.com/dotnet/installer/blob/main/src/VirtualMonoRepo/allowed-binaries.txt) and IMO `.doc` files should be treated identically.

**Comment by mmitche** [comment]
Moved to In Progress.

**Comment by tkapin** [comment]
To whom this should be assigned to?

**Comment by MichaelSimons** [comment]
I think this is obsolete due to the change in direction described in https://github.com/dotnet/source-build/issues/4088.  Specifically  https://github.com/dotnet/source-build/issues/4087 will allow these and will need to modify the binary scan tool logic appropriately.

**Comment by mthalman** [comment]
Removed the ops-monitor label since this isn't causing any build issues right now.

**Comment by mthalman** [comment]
Added back the label since it's still causing a warning on builds in main.
