### ISSUE TITLE
Investigate perf improvement for license scanning

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3765]
It takes roughly 5.5 hrs for the [license scan pipeline](https://github.com/dotnet/installer/blob/main/eng/pipelines/source-build-license-scan.yml) to run currently. This involves splitting each sub-repo of the VMR into a separate job. So the longest job ends up being ~5.5 hrs for the runtime repo.

We could investigate trying to improve this execution time. The `scancode` utility does have a [`--processes` option](https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/list-options.html#all-core-scan-options) that lets you set the number of processes to spin up for the scan. That's currently left at the default of 1. That's probably the best place to start.

**Comment by MichaelSimons** [comment]
@mthalman, is there anymore planed work here or can this be closed?

**Comment by mthalman** [comment]
Nothing more, closing.
