### ISSUE TITLE
Deal with binaries excluded from source build

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3774]
There are binaries currently excluded from source build (they were checked into the git repos). Most of these are required for building tests. Since we need to be able to build tests in the VMR, we need to have access to these files in some way shape or form. However, they cannot be introduced into the VMR because this violates rules about checked-in binaries in source-build.

Where these binaries exist, they should:
- Remain excluded and deal with fallout (e.g. specific tests may never build in the VMR)
- Factor out into packages that are restored when building in non Linux source-build scenarios.

**Comment by mmitche** [comment]
Adding back into Unified Build as this needs to be dealt with for UB completion.

Related: https://github.com/dotnet/source-build/issues/3738

**Comment by mmitche** [comment]
Closing in favor of #3989

**Comment by tkapin** [comment]
I'm removing the Epic label to get this off of the roadmap, since it was closed in favor of #3989, which was in turn closed in favor of #4088.
