### ISSUE TITLE
Resolve potential disk space issue for CI agents running source-build release

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3777]
Discovered by https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullRequest/35888#1702300733

Tracking issue on `dnceng` side - https://github.com/dotnet/dnceng/issues/1537

We should make sure to resolve the described potential disk space issue on the CI agents we are using for the internal source-build release pipeline based on recommendations from `dnceng`.

This should be complete before the February release as we plan to use the internal pipeline for it.

### Release Note Description
Add Azure CLI to Ubuntu.2004 image

**Comment by mmitche** [comment]
@oleksandr-didyk I looked at this when I was working on the SB signing artifacts. Use of one of dnceng's non 1es pools works (has enough space), but we need the `gh` command line tooling for things to work properly: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/35803

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk I looked at this when I was working on the SB signing artifacts. Use of one of dnceng's non 1es pools works (has enough space), but we need the `gh` command line tooling for things to work properly: [dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/35803](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/35803)

Yeah, thanks for mentioning this.

I initially tried to use one of these images but the source-build release pipeline also needed `az` command line, which in turn needed Python packages and Supply Chain Analysis really didn't like that (I described in more in depth [here](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullRequest/35888#1702300733)).

If we can just add the tools we need to some image that would great. Can help out with that if needed, just need some confirmation that that's the long-term solution for the issue

**Comment by oleksandr-didyk** [comment]
Additionally, would be great if we mentioned the limitations of the `1es-*` images somewhere easily accessible (or just didn't use them at all). Since its quite confusing to debug these issues as by just looking at the pool configuration everything seems to be fine and to understand the root cause one has to skim through a few different `dnceng` issues

**Comment by oleksandr-didyk** [comment]
Started working on adding some of the tooling we required, at least for the `Mirror` stage - https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/36502?iteration=1&path=/definitions/shared/linux.yaml

**Comment by oleksandr-didyk** [comment]
Waiting for rollout of updates to the base VM image we are using as described in https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullRequest/36485#1705912806

The rollout should happen on 01/24

**Comment by oleksandr-didyk** [comment]
Changes rolled-out successfully, the switch to the new image for `Mirror` stage was merged. Closing as `Done`
