### ISSUE TITLE
First class support for overriding the arcade SDK version

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3785]
We need better support for overriding the Arcade SDK version. There are at least two places where the arcade SDK version is used:
- In the SDK resolvers (read from global.json) - We currently override this using a custom sdk resolver we install in the SDK. When certain envvars are set, a different SDK is used. This is awkward. Covered by https://github.com/dotnet/source-build/issues/3781.
- For restoring and finding the arcade build project that is the entry points to arcade based builds (Tools.proj and Build.proj). This is read from the global.json, restored, and then set in a variable for use later.

The issue here is that you want repos downstream of arcade to use the correct SDK when it shows up in a project file **and** the correct Tools/Build.proj. Otherwise you only used the arcade SDK partially. The way this works on Linux right now is that we **unpack** the arcade SDK to an explicit dir, and then set an environment variable `_InitializeToolset` to the Build.proj that is the build entry point. This appears to be because the bash behavior variable scoping will pick up environment variables ambiently. In powershell though, we scope most of these variables to **global**. This means that setting an outside envvar won't work. It will restore the wrong arcade and use the wrong entry point.

This brings up a couple problems overall:
- Explicitly setting the build proj variables is pretty hacky overall. It relies on Arcade's scripting 'optimizations' not doing any kind of reinitialization to stick with the desired build project.
- You need to rewrite the common scripting on windows to take into account env vars.
- The variable names may not be consistent across powershell and bash anyway.

I think ideally, we would cover the build project case by offering a standard environment variable to control the arcade **version** (overriding global.json) alone. That would then cause the correct restore to happen and the project to launch.

Ideally this could be combined with a real solution for overriding the msbuild SDKs from msbuild's standpoint so that we could also avoid manually extracting msbuild SDK packages in SB/VB mode.

**Comment by mmitche** [comment]
Matt Mitchell (.NET) MSBUILDADDITIONALSDKRESOLVERSFOLDER_NET and MSBUILDADDITIONALSDKRESOLVERSFOLDER_NETFRAMEWORK

**Comment by ericstj** [comment]
Looks like these might be interesting:
https://github.com/dotnet/sdk/blob/5ff0a5981ef9409b4b382a4b7045739a3e703d74/src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs#L142-L146

I think that just applies to the .NET SDK, not arcade.

**Comment by rainersigwald** [comment]
`DOTNET_MSBUILD_SDK_RESOLVER_SDKS_DIR` applies only when that resolver runs, which it doesn't in `dotnet build` scenarios, unfortunately.

**Comment by mmitche** [comment]
This is already opened as part of #3781 closing here.
