### ISSUE TITLE
Make internal tarballs for partners available through Azure DevOps

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3788]
There's a need to migrate away from the use of Azure Blob Storage for storing the internal tarballs (source and smoke test prereqs) available for partners so that we can avoid the need to provide SAS tokens. Since we already have a security model with Azure DevOps org membership, we can make use of the resources available within Azure DevOps instead.

The most straightforward approach is to store the tarballs as Azure DevOps Artifacts, specifically universal packages. This allows a tarball to be directly uploaded as part of our release pipeline and downloaded by our partners. The downside to universal packages is that they don't currently support direct download URLs. You must use the Azure CLI to download them; this is an extra burden on partners to install and configure.

An alternative to universal packages could be to use NuGet packages, purely as a wrapper around a tarball. This is definitely a hack but NuGet packages have the benefit of being able to be downloaded directly from the browser. Of course, there's some extra work on the partner's part by needing to crack open the NuGet package to get the underlying tarball.

Another solution would be to use Azure Pipeline artifacts. Artifacts of a pipeline run have the benefit of direct download URLs. There is more overhead involved in this approach because you'd need to have to have an actual pipeline run which would publish the tarballs as pipeline artifacts. That gets into the whole realm of compliance requirements for pipelines as well. In this scenario, we would likely still publish the tarballs as universal packages from the source build release pipeline. And then the pipeline that runs in the partner project would download those packages and publish them as pipeline artifacts. This resolves the issue of needing to manage any secrets to access something like the blob storage account, for example. This is the least desirable option, IMO.

**Comment by MichaelSimons** [comment]
[Triage] This is needed for Feb servicing.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/36485

**Comment by oleksandr-didyk** [comment]
Blocking issue resolved, changes for uploading the tarballs as universal packages were merged. Closing as `Done`
