### ISSUE TITLE
Add a CI test to each submodule repo that is a tripwire for new dependencies

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#379]
Catching new dependencies in rolling builds is too late. We need to catch new dependencies at the submodule repo level as part of their PR validation.

**Comment by dseefeld** [comment]
Adding dependency baselining would be a way of getting repo owners to consistently stay on top of additional dependencies.

**Comment by dagood** [comment]
Note, https://github.com/dotnet/source-build/issues/1503 tracks the base work of adding source-build to repo PR validation whatsoever, this issue is about tracking prebuilts and failing.

(This issue initially covered both, but now we have them split up.)

**Comment by MichaelSimons** [comment]
[Triage] Closing - This is being tracked with https://github.com/dotnet/source-build/issues/3017.
