### ISSUE TITLE
Investigate package upgrades that may be incompatble with project TFMs

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3794]
When building roslyn, we discovered that it has some projects that target net7.0. In Vertical build, though, building after runtime will upgrade the repo's dependencies via dependency flow. Some projects may build on old TFMs, but depend on packages built upstream in the VMR. When runtime removes support for old TFMs, those projects may be rolling forward onto a new TFM, or falling back to netstandard in ways we do not want.

The dependency flow logic in the VMR will only upgrade dependencies that are mentioned and unpinned in `Version.Details.xml`. This might be the right thing to do for many projects. But what should we do when we want X version for 3 projects and Y version for others? Some ways to manage this:

- Use different version properties in the various circumstances. Align those we want upgraded with the "standard format" (PackageNameVersion).

The core example here are roslyn's runtime dependencies: https://github.com/dotnet/roslyn/blob/main/eng/Version.Details.xml#L76-L81 These probably have to be upgraded in Linux source build mode due to being redistributed. But there are other parts of roslyn not built in source-build mode that would probably want to stick on a 7.0 version, like the LanguageServer.

**T-Shirt Size: Large**

**Comment by ViktorHofer** [comment]
Here's yet another case:

VS components must not reference newer versions of dependencies than what ships inside Visual Studio, i.e. S.C.I must be 7.0.0 and not the live version that comes from runtime.

In the case of msbuild, entries in Version.Details.xml exist for S.C.I which cause the dependencies to be upgraded. That must not happen for desktop msbuild which ships inside VS. Here's the failure inside the VMR:

```
    C:\git\dotnet\src\msbuild\artifacts\sb\s\s\src\MSBuild\MSBuild.csproj(313,5): error : Binding redirect for 'Microsoft.Bcl.AsyncInterfaces' redirects to a different
   version (7.0.0.0) than MSBuild ships (9.0.0.0). [TargetFramework=net472]
    C:\git\dotnet\src\msbuild\artifacts\sb\s\s\src\MSBuild\MSBuild.csproj(313,5): error : Binding redirect for 'System.Collections.Immutable' redirects to a different
  version (7.0.0.0) than MSBuild ships (9.0.0.0). [TargetFramework=net472]
    C:\git\dotnet\src\msbuild\artifacts\sb\s\s\src\MSBuild\MSBuild.csproj(313,5): error : Binding redirect for 'System.Reflection.Metadata' redirects to a different ve
  rsion (7.0.0.0) than MSBuild ships (9.0.0.0). [TargetFramework=net472]
    C:\git\dotnet\src\msbuild\artifacts\sb\s\s\src\MSBuild\MSBuild.csproj(313,5): error : Binding redirect for 'System.Reflection.MetadataLoadContext' redirects to a d
  ifferent version (7.0.0.0) than MSBuild ships (9.0.0.0). [TargetFramework=net472]
    C:\git\dotnet\src\msbuild\artifacts\sb\s\s\src\MSBuild\MSBuild.csproj(313,5): error : Binding redirect for 'System.Resources.Extensions' redirects to a different v
  ersion (7.0.0.0) than MSBuild ships (9.0.0.0). [TargetFramework=net472]
    C:\git\dotnet\src\msbuild\artifacts\sb\s\s\src\MSBuild\MSBuild.csproj(313,5): error : Binding redirect for 'System.Text.Encodings.Web' redirects to a different ver
  sion (7.0.0.0) than MSBuild ships (9.0.0.0). [TargetFramework=net472]
    C:\git\dotnet\src\msbuild\artifacts\sb\s\s\src\MSBuild\MSBuild.csproj(313,5): error : Binding redirect for 'System.Text.Json' redirects to a different version (7.0
  .0.3) than MSBuild ships (9.0.0.0). [TargetFramework=net472]
```

**Comment by mmitche** [comment]
We will be moving to a model that will does not transparently upgrade packages that should not be upgraded, and does not float TFMs in non-source-only scenarios.
