### ISSUE TITLE
Usability: Don't unzip intermediate packages every time

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3796]
The intermediate packages are getting unzipped every time in source-build. Minor issue but it's a time sink. It would be good to get rid of them overall but in the meantime getting rid of the unpack would be awesome.

**Comment by mmitche** [comment]
I think @NikolaMilosavljevic is resolving this issue via removal of the intermediate packages in SB altogether.

**Comment by MichaelSimons** [comment]
> This essentially is fixed. We just need to update arcade and SBRP with the latest arcade changes.

Unless I am mis-understanding, I don't think that is what is needed.  Source-build needs to be re-bootstrapped so that the previous source-build artifacts contains an arcade version with the change/fix.  That is the version used to build arcade and SBRP in the product source-build.

**Comment by ViktorHofer** [comment]
Righ.t My comment only captured the non source build behavior here. You are right that we also need to re-bootstrap otherwise we would break the source-build behavior.

**Comment by MichaelSimons** [comment]
FYI - @ellahathaway is currently working on https://github.com/dotnet/source-build/issues/3974 which requires a re-bootstrap.

**Comment by mmitche** [comment]
I think this is complete, @NikolaMilosavljevic?
