### ISSUE TITLE
Long paths create problems with windowsdesktop

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3799]
Windowsdesktop and other repos that use Wix tooling have a good deal of trouble with long paths. The inner clone adds a few characters to paths that are already close to the limit (240s), causing failures. This should go away once the inner clone is removed.

**T-Shirt Size: Small**

**Comment by mmitche** [comment]
#3072

**Comment by mmitche** [comment]
@NikolaMilosavljevic is probably resolving this with his inner clone removal

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic is probably resolving this with his inner clone removal

Yes, this is being resolved as part of https://github.com/dotnet/source-build/issues/3072

**Comment by ViktorHofer** [comment]
We aren't using inner clone anymore inside the VMR. This can be closed now.
