### ISSUE TITLE
[SDK DIFF] Extra System.CodeDom assembly in source-built SDK

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3803]
Failing build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2337527&view=logs&j=9ebdebc1-a11e-50fc-dfa8-efc527e54bda&t=6faae72f-bad4-57f5-43ff-88548eddc01c

The SDK diff tests for `main` seem to have found an extra  `System.CodeDom` assembly in the source-built SDK, specifically in the `dotnet-format` tooling.

Will investigate the reason for it.

**Comment by oleksandr-didyk** [comment]
Looked through the two SDKs used, it seems that the Source-Built one contains an extra `System.CodeDom` assembly under `dotnet-format`, while the Microsoft one has no such assembly in the corresponding path. Additionally, looked at the diff between the commits of the VMR where the license check was not failing and cannot identify a change that would cause this assembly to pop-up.

Will defer to other source-build team members for investigation.

@mthalman would you maybe have some ideas as to why exactly this is happening?

**Comment by mthalman** [comment]
This no longer repros.
