### ISSUE TITLE
Building .NET 8 leads to error NU3018: Package 'Microsoft.EntityFrameworkCore.InMemory 8.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's signing certificate is not trusted by the trust provider

### ISSUE THREAD

**Issue by skgoyal81** [dotnet/source-build#3811]
Recently we have migrated our application to .Net 8. I am trying to build .NET 8 using build using "--configuration $(buildConfiguration)". That fails on others (RHEL 8, offline).

I get hundreds of errors that all look like this:

<img width="756" alt="image" src="https://github.com/dotnet/source-build/assets/99733207/4197ce42-5ee6-4e43-bf81-4a4293b69eda">

**Comment by skgoyal81** [comment]
Do we have any update Team?

**Comment by mthalman** [comment]
@skgoyal81 - This repo is about building .NET from source. So it may be the wrong repo for this issue. In your case, how did you acquire .NET? This may be better suited for the [NuGet repo](https://github.com/NuGet/Home).

**Comment by MichaelSimons** [comment]
Closing per the [previous suggestion](https://github.com/dotnet/source-build/issues/3811#issuecomment-1877523489).
