### ISSUE TITLE
CentOSStream8_Online_PreviousSourceBuiltSdk_x64 fails from crossgen2 error

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3815]
The `CentOSStream8_Online_PreviousSourceBuiltSdk_x64` build leg of the VMR is failing with the error described in https://github.com/dotnet/runtime/issues/95768. That issue has been fixed but a rebootstrap of the SDK in the VMR is necessary in order to resolve the issue in the build.

**Comment by mthalman** [comment]
This [stage 2 issue](https://github.com/dotnet/source-build/issues/3814) needs to be resolved before we can rebootstrap.

**Comment by ellahathaway** [comment]
Reopening because this error is still occurring despite the changes from https://github.com/dotnet/installer/pull/18126 and https://github.com/dotnet/sdk/pull/37407. See https://dev.azure.com/dnceng/internal/_build/results?buildId=2347529&view=results.

**Comment by mthalman** [comment]
This is due to the changes not being mirrored to the internal AzDO repo. Same thing as https://github.com/dotnet/source-build/issues/3813#issuecomment-1881617678.

**Comment by mthalman** [comment]
This is working now.
