### ISSUE TITLE
Add additional missing repos into the VMR

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3818]
The following repos need to be added into the VMR:
- [ ] efcore

**T-shirt size is Small (based on the limited list above)**

**Comment by mmitche** [comment]
T-shirt size is Small (based on the limited list above)

**Comment by tkapin** [comment]
Depends on setting up the microsoft build branch in the VMR

**Comment by tkapin** [comment]
@mmitche - wrt. the recent discussion about #3989, is this still blocked on something or efcore can be added to the VMR?

**Comment by mmitche** [comment]
We should be able to add efcore now

**Comment by mmitche** [comment]
@jkoritzinsky also an option
