### ISSUE TITLE
Remove BuildNetStandardLibraryNetFramework in corefx repo build.

### ISSUE THREAD

**Issue by weshaggard** [dotnet/source-build#386]
We no longer ship the NetStandardLibraryNetFramework package in 2.1 it is only exists in 2.0 servicing branches so we should remove it from source-build https://github.com/dotnet/source-build/blob/dev/release/2.1/repos/corefx.proj#L37.

**Comment by kasper3** [comment]
Looks like it was removed from https://github.com/dotnet/source-build/blob/dev/release/2.1/repos/corefx.proj#L37, it's present in master branch though.

**Comment by weshaggard** [comment]
Yes I decided to remove it as part of my change to move corefx forward. We can keep this open until we figure out our plan for tackling the master branch.

**Comment by dseefeld** [comment]
This is completed.
