### ISSUE TITLE
Implement and Verify Product Verticals

### ISSUE THREAD

**Issue by tkapin** [dotnet/source-build#3902]
This is a tracking issue aggregating the individual "Implement Vertical Build" issues. It is used to group the Implement Vertical Build efforts in the main [.NET Unified Build (Theme)](https://github.com/dotnet/source-build/issues/3926) issue.

# Work Items

- [x] #3832
- [x] #3833
- [x] #3834
- [x] #3835
- [x] #3836
- [x] #3837
- [x] #3838
- [x] #3839
- [x] #3840
- [x] #3841
- [x] #3842
- [x] #3843
- [x] #3844
- [x] #3845
- [x] #3846
- [x] #3847
- [x] #3848
- [x] #3849
- [x] #3850
- [x] #3851
- [x] #3852
- [x] #3853
- [x] #3854
- [x] #3855
- [x] #3856
- [x] #3857
- [x] #3858
- [x] #3859
- [x] #3860
- [x] #3861
- [x] #3862
- [x] #3863
- [x] #3864
- [x] #3865
- [x] #3866
- [x] #3867
- [x] #3868
- [x] #3869
- [x] #3870
- [x] #3871
- [x] #3872
- [x] #3873
- [x] #3874
- [x] #3875
- [x] #3876
- [x] #3877
- [x] #3878
- [x] #3879
- [x] #3880
- [x] #3881
- [x] #3882
- [x] #3883
- [x] #3884
- [x] #3885
- [x] #3886
- [x] #3887
- [x] #3888
- [x] #3889
- [x] #3890
- [x] #3891
- [x] #3892
- [x] #3893
- [x] #3894
- [x] #3895
- [x] #3896
- [x] #4760

**Comment by mmitche** [comment]
@tkapin The following addition build related issues will also be required. Should we link these or keep them separate?

**Comment by tkapin** [comment]
Feel free to add them to have a one stop tracker for everything VB.

**Comment by tkapin** [comment]
Let's break this into Implement Verticals, individual epics (already identified) and then group the rest if appropriate into another epics.

**Comment by akoeplinger** [comment]
This is done now.
