### ISSUE TITLE
Poison leaks leaks in dotnet-format

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3909]
VMR has the following poison leaks for .NET 9:

```xml
<PrebuiltLeakReport>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/Microsoft.Win32.SystemEvents.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.CodeDom.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Configuration.ConfigurationManager.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Drawing.Common.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Reflection.MetadataLoadContext.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Resources.Extensions.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Cryptography.Pkcs.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Cryptography.ProtectedData.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Cryptography.Xml.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Permissions.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Windows.Extensions.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/Microsoft.Win32.SystemEvents.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.CodeDom.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Configuration.ConfigurationManager.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Drawing.Common.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Reflection.MetadataLoadContext.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Resources.Extensions.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Cryptography.Pkcs.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Cryptography.ProtectedData.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Cryptography.Xml.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Permissions.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Windows.Extensions.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
</PrebuiltLeakReport>
```

**Comment by ellahathaway** [comment]
Here are the updates from my current investigation:

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/Microsoft.Win32.SystemEvents.dll**
    - Windows
    - Dependency of System.Drawing.Common

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.CodeDom.dll**
    - Brought in by MSBuild

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Configuration.ConfigurationManager.dll**
    - Brought in by MSBuild

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Drawing.Common.dll**
    - Windows

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Reflection.MetadataLoadContext.dll**
    - Brought in by MSBuild

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Resources.Extensions.dll**
    - Brought in by MSBuild

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Cryptography.Pkcs.dll**
    - Brought in by MSBuild

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Cryptography.ProtectedData.dll**
    - Brought in by MSBuild
    - Dependency of System.Configuration.ConfigurationManager

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Cryptography.Xml.dll**
    - Brought in by MSBuild

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Security.Permissions.dll**
    - Brought in by MSBuild
    - Dependency of System.Configuration.ConfigurationManager

- **dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Windows.Extensions.dll**
    - Windows

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/Microsoft.Win32.SystemEvents.dll**
    - Windows
    - Dependency of System.Drawing.Common

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.CodeDom.dll**
    - Brought in by MSBuild

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Configuration.ConfigurationManager.dll**
    - Brought in by MSBuild

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Drawing.Common.dll**
    - Windows

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Reflection.MetadataLoadContext.dll**
    - Brought in by MSBuild

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Resources.Extensions.dll**
    - Brought in by MSBuild

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Cryptography.Pkcs.dll**
    - Brought in by MSBuild

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Cryptography.ProtectedData.dll**
    - Brought in by MSBuild
    - Dependency of System.Configuration.ConfigurationManager

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Cryptography.Xml.dll**
    - Brought in by MSBuild

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Security.Permissions.dll**
    - Brought in by MSBuild
    - Dependency of System.Configuration.ConfigurationManager

- **Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Windows.Extensions.dll**
    - Windows

**Comment by ellahathaway** [comment]
Closing per https://github.com/dotnet/format/pull/2063 being merged.
