### ISSUE TITLE
Tracking: SSCA violations in Aspire

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3913]
- [x] https://github.com/dotnet/aspire/issues/1419
- [x] https://github.com/dotnet/aspire/issues/1670

**Comment by eerhardt** [comment]
Should be resolved with the following PRs:

https://github.com/dotnet/aspire/pull/1721
https://github.com/dotnet/aspire/pull/1722

**Comment by MichaelSimons** [comment]
Tracking issue were resolved.  SSCA steps in main VMR are green.  Closing.

**Comment by ellahathaway** [comment]
Reopening since the issue in https://github.com/dotnet/aspire/issues/1419 is now occurring in 8.0.1xx builds. [Link to internal build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2368577&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=edf6ea5d-8fa9-5661-2fd8-1370b24b9911).
