### ISSUE TITLE
`ArtifactsSizeTest` should output warnings to a log or artifacts file

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3921]
Currently, the only way to view the warnings that are produced by the `ArtifactsSizeTest` is in the window where the tests are run in AzDo. This makes the readability extremely difficult if there are multiple warnings. It would be helpful to output these warnings to an file that could be downloaded and inspected.

**Comment by ellahathaway** [comment]
Some possible solutions:

- Output current warnings to a text file. This is the simplest solution.
- Output notable diffs to an XML file. Results in this file could look like:
  ```
  <File Path="packs/Microsoft.AspNetCore.App.Ref/x.y.z/analyzers/dotnet/roslynx.y/cs/cs/Microsoft.Extensions.Options.SourceGeneration.resources.dll">
      <Type>Increase</Type>
      <OriginalSize>0</OriginalSize>
      <UpdatedSize>3121793</UpdatedSize>
   </File>
  ```

**Comment by MichaelSimons** [comment]
With the changes proposed in https://github.com/dotnet/installer/pull/18766, you can see the output at https://dev.azure.com/dnceng/internal/_build/results?buildId=2386654&view=ms.vss-test-web.build-test-results-tab&runId=53124155&resultId=100001&paneView=attachments.  This provides an option to download the log as well.

@ellahathaway do you see this as being sufficient?
