### ISSUE TITLE
Enable building VMR in dev and CI configurations

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3934]
We need to be able to build the VMR in dev and CI configurations. In arcade terms, this means not using official build id branding. Dev modes build packages and binaries with -dev, while -ci builds with -ci. The purpose here is to enable these modes, **but also identify any issues that fall out.**

Primarily, this involved **not** passing `OfficialBuildId` to each component build. In addition, in dev configurations, ContinuousIntegrationBuild should not be passed.

## Identified Work
- [x] #4036

**Comment by mmitche** [comment]
Related: #3786

**Comment by mmitche** [comment]
I took a quick look into this today to see what I could find:
- Official build ids and other repo info (e,g. final package versions) are passed by importing the repo property files.
- There are quite a few parameters always passed that put repos into official build mode (e.g. OfficialBuildId)

After removing this, the next hurdle is that source-build attempts to extract the arcade tooling packages that will be used downstream based on finding the arcade nupkgs using their name + version that is in AllRepoVersions.props. More coding to treat everything as "official". This of course would have to change. Really, the build should be smart and go find the output versions of the packages it needs, based on what was produced, rather than what the version file says.

**Comment by mmitche** [comment]
This may actually overall be not toooo hard. It got through a few repos, passing versions as expected. What this really is, is a test of whether we can dictate version numbers out of the VMR and have things work as expected. We need to be able to do this to ship.

**Comment by mmitche** [comment]
@jkoritzinsky

**Comment by tmds** [comment]
Does this issue impact the configuration used when calling `./build.sh --source-build`?

**Comment by mmitche** [comment]
@tmds For now, we don't think dev will be the default. At some point, it will be the default because the VMR will stop pre-determining the exact version numbers of most components. Today, because of the way dependency flow happens, we know the official build id that was passed to each of the input repos before they built, so this info gets baked into the VMR.

After we switch to the new flat code flow (in .NET 10 sometime), we won't know what those official build ids are, because officail buidls haven't happened prior to code flow. This means that ./build.sh -source-build won't be able to produce an official build without additional info. At that point, the default invocation becomes -dev, and passing --official-build or something along those lines (with either a date provided by you, or one that matches what we built) will be required to produce the shipping assets.

**Comment by tmds** [comment]
ok, that makes sense.

We should try to minimize the differences between "dev" and "release" to avoid unexpected "surprises" when we make a release build. For example: not setting `ContinuousIntegrationBuild` might disable `DeterministicSourcePaths`, but that is perhaps a difference that is not actually desired between "dev" and "release".
