### ISSUE TITLE
Introduce output controls into arcade if necessary

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3961]

**Comment by ViktorHofer** [comment]
We should consider upstreaming common properties into the Arcade SDK that multiple repositories need, i.e. `*OS` and `*Architecture` ones that recently got added to the VMR: https://github.com/dotnet/dotnet/blob/002d01eeae9f40bc6d021971cac07501928de3fc/Directory.Build.props#L8-L57

@directhex @steveisok @akoeplinger Do these newly added OS, Arch and RID properties in the VMR cover all our scenarios for cross-building? Do we still need the `Override...` properties i.e. [here](https://github.com/dotnet/dotnet/blob/002d01eeae9f40bc6d021971cac07501928de3fc/repo-projects/sdk.proj#L6-L9)?

**Comment by mmitche** [comment]
Closing as not necesssary.
