### ISSUE TITLE
Unify defaults for logging and binlog creation when building the VMR

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#3966]
Feedback from @MichaelSimons from the [Windows VMR PR](https://github.com/dotnet/installer/pull/18214).

> I think we should consider adding a timestamp to the binlog and log files just as we do in the main build script for a better UX.

The arcade defaults when building an arcade-ified repository are the following:
- Binlogs are only created when the `-bl` or `-ci` switches are passed in: https://github.com/dotnet/arcade/blob/4f2b77e1d281cdcc9af0892b7768f9ce6d34fdd4/eng/common/tools.ps1#L13-L14
- Text log files aren't created
- The timestamp isn't part of the binlog's file name

Should the VMR repository follow those defaults? If not, should binlogs and log files contain timestamps?

cc @mmitche 

Size: S

**Comment by mmitche** [comment]
I think I lean towards using the same defaults that Arcade uses. But, the VMR repo is a bit more special. However, if you're not working on infrastructure related changes, what value does the binlog add? Aren't you normally just looking at the compile errors for guidance on what to do next?

**Comment by ViktorHofer** [comment]
I'm also for using the Arcade defaults which is no binlogs and no logs locally (and not using the minimal log feature from the VMR). In CI we should always create binlogs and IMO use the minimal log feature. So, not really any changes aside from disabling logs locally.

**Comment by MichaelSimons** [comment]
Sharing my perspective, Yes the default behavior is attractive yet building source-build is a little different in complexity (often caused by integration).  From a practical development perspective, source-build devs always want to have binlogs enabled.  Because of that, it feels wrong to not tune the defaults to meet how developers are building.

**Comment by ViktorHofer** [comment]
Right now in main when building the VMR without source-only, binlogs and logs aren't created. They are only created if someone specifies the `-bl` flag or when running in CI.

When building source-only in the VMR, binlogs are always created.

If that's the desired experience, we can just close this issue then.

**Comment by MichaelSimons** [comment]
@mthalman, @ellahathaway, @NikolaMilosavljevic - please share your input.

**Comment by mthalman** [comment]
My default position on things like this is that the VMR should have the same defaults as the product repos. Is that standardized?

I agree that, for source build, binlogs are essential. If it's not already, we should make that the default mode for source build across all the repos.

**Comment by ellahathaway** [comment]
Binlogs are essential when source-build. This should be the default mode across all repos.

As far as the timestamp, I lean towards adding a timestamp to the binlogs when they're enabled as it aids in the developer workflow and eliminates unnecessary confusion about when the binlog was created.

At the same time, I agree that it makes sense for the VMR to have the same defaults as the product repos. Is there the option to update the arcade infra to add a timestamp to the binlog when the `-bl` switch is used? Then the VMR can follow this particular default.

**Comment by ViktorHofer** [comment]
Here's my take on this from the product side perspective.

We want our builds to be as fast as possible. The times that we hit msbuild issues are neglectable in comparison to the times that we face compiler errors or other toolset issues for which binlogs aren't helpful. We always want binlogs created as part of CI builds that happen on a remote, inaccessible machine as it might not be clear where the error is coming from.
Those expectations are nicely met by Arcade's current binlog defaults.

For CI, we don't need timestamps in the binlogs as the binlog format itself already records timestamps. In the case of flakiness we sometimes rerun a leg which then creates a new attempt in AzDO. For that, we already have to record the attempt number in the published artifact payload otherwise we would encounter clashes for any uploaded artifact.

Locally, we don't need/want timestamps encoded in the binlog's name either, as the creation of binlogs is opt-in. FWIW this behavior isn't controllable anyways when devs use the `/bl` flag which uses the default `msbuild.binlog` name and places it in the current working directory. I myself more often use `/bl` than the `-bl` flag.

I think it makes sense for the VMR / orchestrator to follow these defaults so that dotnet/dotnet doesn't artificially feel different to the individual repositories in terms of build entry-points (parameters and actions).

**Comment by mmitche** [comment]
I generally agree with Viktor here. When doing infra changes, I'll pretty much always pass -bl. But for normal operation, I would not expect a dev to do so. Certainly I am not asking for binlogs whenever I build arcade.

**Comment by MichaelSimons** [comment]
In an effort to unify around a standard set of behavior I am alright with changing the -bl behavior for the source-build dev experience.  IMO this should however be treated as lower priority in the grand scheme of delivering the UB project in .NET 9.0
