### ISSUE TITLE
SBRP Build -sb fails on fresh checkout on Debian

### ISSUE THREAD

**Issue by kg** [dotnet/source-build#3969]
After doing a git clone of source-build-reference-packages, `./build.sh -sb` fails with over 4000 build errors. It looks to me like they're all related to changes in Roslyn's API, but I don't understand this part of the product very well. I'll upload a full build log, but here's a couple sample errors:

```
  /home/kate/Projects/source-build-reference-packages/artifacts/sb/src/src/referencePackages/src/microsoft.codeanalysis.csharp/3.7.0/lib/netstandard2.0/Microsoft.CodeAnalysis.CSharp.cs(9972,33): error CS0534: 'RefTypeExpressionSyntax' does not implement inherited abstract member 'SyntaxNode.GetNodeSlot(int)' [/home/kate/Projects/source-build-reference-packages/artifacts/sb/src/src/referencePackages/src/microsoft.codeanalysis.csharp/3.7.0/Microsoft.CodeAnalysis.CSharp.3.7.0.csproj::TargetFramework=netstandard2.0]
  /home/kate/Projects/source-build-reference-packages/artifacts/sb/src/src/referencePackages/src/microsoft.codeanalysis.csharp/3.7.0/lib/netstandard2.0/Microsoft.CodeAnalysis.CSharp.cs(9972,33): error CS0534: 'RefTypeExpressionSyntax' does not implement inherited abstract member 'SyntaxNode.GetCachedSlot(int)' [/home/kate/Projects/source-build-reference-packages/artifacts/sb/src/src/referencePackages/src/microsoft.codeanalysis.csharp/3.7.0/Microsoft.CodeAnalysis.CSharp.3.7.0.csproj::TargetFramework=netstandard2.0]
```

[sbrp-build-failure.txt](https://github.com/dotnet/source-build/files/13924922/sbrp-build-failure.txt)

**Comment by mthalman** [comment]
The CI builds all look good. I also tried repro'ing myself and was unable to. Are you sure you don't have any local changes you've made? Can you provide more details on your environment?

Here's what I tried:

1. Create a fresh WSL instance of Debian by installing from Microsoft Store.
2. `sudo apt update && sudo apt install -y git wget libicu72`
3. `git clone https://github.com/dotnet/source-build-reference-packages`
4. `cd source-build-reference-packages`
5. `./build.sh -sb`

Build was successful.

**Comment by kg** [comment]
Deleting artifacts and rebuilding from scratch emitted the messages into the binlog, but in the binlog viewer they don't appear as errors. Kinda strange. A sub-build maybe?
[msbuild.zip](https://github.com/dotnet/source-build/files/13954704/msbuild.zip)

**Comment by kg** [comment]
Here's the binlogs from the sub-build, it looks like the errors are in sourcebuild.binlog.
https://www.dropbox.com/scl/fi/b7acnj5rk4c7nbwqrrqpz/sb-binlogs.zip?rlkey=u2j1rgp517w7nvahmhmtdourg&dl=0

**Comment by MichaelSimons** [comment]
[Triage] @kg - Would you be willing to try the steps mentioned in https://github.com/dotnet/source-build/issues/3969#issuecomment-1893826360?

**Comment by kg** [comment]
Creating a new linux VM using WSL won't really solve anything for me, so I'm willing to just treat this as another "linux never works for me" incident and close the ticket if it works for other people on Debian. I tried deleting ~/.nuget/ so I have no idea what part of my system state could cause this.
