### ISSUE TITLE
Prep script not failing when installing non-existent SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3975]
Related to https://github.com/dotnet/source-build/issues/3974

If a non-existent path to the .NET SDK is specified to the prep script, it silently fails when trying to extract the tarball. It should fail the script instead.

**Comment by omajid** [comment]
I am a bit confused because prep.sh doesn't take any paths to the .NET SDK. Is https://github.com/dotnet/installer/pull/18812 a sensible fix?

**Comment by mthalman** [comment]
It doesn't take any paths as input, no. But it constructs a URL from which to download the SDK. That's the issue. The URL doesn't point to anything and it silently fails.
