### ISSUE TITLE
Implement subset source-only build branches

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3989]
Follow on work from discussions here: https://github.com/dotnet/source-build/issues/3738

Based on this discussion, the following will happen:

- We will change the VMR sync such that it will sync into a branch without cloaking. Let's call this the VMR-All branch
- We will provide a distro-maintainer-centric branch which will comply with your requirements like the existing branch does.
- This branch will be a subset of the VMR-All branch, related in git history. Let's call this a VMR-SourceOnly branch. It will have the cloaked set of files removed.
- These cloaked files may also include repos that are not interesting for distro maintainers, e.g. winforms
- PRs that update a VMR-All branch will also test updates to the corresponding VMR-SourceOnly branch.
- Upon checkin, the VMR-SourceOnly branch will be immediately updated (no lag) via a merge process.
- On release day, we will create two tags and two releases. One tag will point to the VMR-All content for the release, and the other to the source only compatible content.

## Design Details

**Branch Naming**

- Primary branch names (e.g. `main` and `release/8.0.1xx`) remain unchanged.
- Source-only branches are named with a `/source-only` suffix: (e.g. `main/source-only` and `release/8.0.1xx/source-only`)

**Release Tag Naming**

- Primary tag names are unchanged from previous names. (e.g. `v8.0.1`)
- Source-only tags are named with a -source-only suffix (e.g. v8.0.0-source-only).

**Release content**

- Release content for the primary tag is updated to indicate the tag that should be used for source-only builds
- Source-build release content is updated to indicate that the tag should be used for source-only builds.

## Work Items

- [x] #3990 
- [x] #3997
- [x] #3991 
- [x] #3992 
- [x] #3993 
- [x] #3994 
- [x] #3995 
- [x] #3996

**Comment by mmitche** [comment]
@premun

**Comment by jkotas** [comment]
> Source-only branches are named with a /source-only suffix:

The key characteristic of these branches is that they are tailored to the needs of Unix distros. Should the suffix naming reflect that? E.g. unix-distro suffix?

**Comment by mmitche** [comment]
> > Source-only branches are named with a /source-only suffix:
> 
> The key characteristic of these branches is that they are tailored to the needs of Unix distros. Should the suffix naming reflect that? E.g. unix-distro suffix?

Maybe distro-maintainer? I'm fine with any naming here as long as it's pretty clear to users.

**Comment by premun** [comment]
Maybe it's better to say what is in the branch (like `/source-only`) rather than trying to describe the purpose of how it should be used as that can grow/change over time?
E.g. we might start using these for some non-distro-related purpose?

**Comment by mmitche** [comment]
Possibly. @MichaelSimons and I chatted more about this yesterday and he doesn't love the delta-branch approach much. Let's chat more tomorrow. It's possible that we could keep a set of cloaking and use the same branch, but this will require time to evaluate.

**Comment by mmitche** [comment]
It's likely this work will not be required as we may use a pre-build script for distro maintainers. If not, we should close all items and open a new Epic + items for that.

**Comment by mmitche** [comment]
Going with a different solution in #4088

**Comment by tkapin** [comment]
> Going with a different solution in [#4088](https://github.com/dotnet/source-build/issues/4088)

Since we are going with a different solution, I'm removing the Epic label to get this off of the roadmap.
