### ISSUE TITLE
Implement mechanism to merge to source-only branch from primary branch and apply exclusions

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3991]
When the primary VMR branch is updated via VMR sync, we should add an operation that can:
- Merge from that branch into the source-only branch, applying cloaking. The cloaking list should basically be the same as it is today.
- Automatically resolve any conflicts in cloaked files (edited in source) by accept-ours.

**Comment by MichaelSimons** [comment]
This is superseded by https://github.com/dotnet/source-build/issues/4088.
