### ISSUE TITLE
Update VMR build scripting to suggest correct branches to use when building

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3992]
Update the VMR build scripting to improve UX. For instance:
- If a non-source-only build is attempted from a source-only branch (e.g. look for some file that wouldn't exist in the source-only branch), print a helpful message to the user.

**Comment by ViktorHofer** [comment]
As mentioned offline, I don't think we should be going that route. I think it's important to make it possible to source-build from the "main"  branch.

**Comment by mmitche** [comment]
Going with a different solution in #4088
