### ISSUE TITLE
Retarget VMR CI source-only build pipelines to source-only branches

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3994]
VMR CI source-only build pipelines should use the source-only branches.

**Comment by premun** [comment]
I think this issue is backwards as we did `main-ub` instead of `main-source-only` but @akoeplinger is essentially doing this, right?

**Comment by mmitche** [comment]
The parent Epic is for a full solution with the main branch being UB. So at that point we would retarget pipelines

**Comment by premun** [comment]
Sorry, my bad
