### ISSUE TITLE
Remove dependency on build.sh passing SDK_VERSION in env

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#400]
PR cleanup, will make it easier to get Windows build going:

https://github.com/dotnet/source-build/pull/397#pullrequestreview-110122867:

https://github.com/dotnet/source-build/blob/ab034cff2bf6389be553d050dc4db370b95c001b/dir.props#L21

> [@weshaggard] I'm not too key on depending on the env variable here it does mean that it will only work when you call build.sh it won't even work for build.cmd.

> [@dagood] Hmm, yeah, I should have just added a `/p`. Maybe there's even a property that MSBuild sets itself with the location of the SDK that I could have used, didn't look for that either.

**Comment by MichaelSimons** [comment]
Closing as obsolete.  DotNetSdkDir no longer exists.  The VMR is also now building for Windows.
