### ISSUE TITLE
[SBRP] System.Runtime.InteropServices references the wrong System.Reflection assembly

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4000]
![image](https://github.com/dotnet/sdk/assets/7412651/71025076-83d0-4520-8501-d95603b66725)

Repro: `./generate.sh --package System.IO.Pipelines,8.0.0`
Observe changes in "src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netcoreapp1.1/System.Runtime.InteropServices.cs"

The GenAPI version used is a week old.

cc @ericstj

**Comment by ViktorHofer** [comment]
@MichaelSimons looks like the removal of the `netcore50` asset for System.Reflection broke this. I see a couple of options:
- Bring netcore50 for System.Reflection back
- Don't do anything and live with the delta. Document that the removal of the API should be undone. This is the worst option from a correctness standpoint as the API shouldn't be defined for `netcoreapp1.1`: https://apisof.net/catalog/daf24a6e-c08e-a231-1f13-f25206465b78
- Remove `netcoreapp1.x` assemblies from SBRP.

**Comment by ViktorHofer** [comment]
OK I need to take a closer look. Eric just corrected me that the `netcore50` TFM should not be chosen by `netcoreapp1.1`.

**Comment by MichaelSimons** [comment]
Removal of `netcoreapp1.x` assemblies from SBRP seems like the best long term solution.  I thought there were downstream dependencies that needed to be upgraded first.  Until removal is possible, I think status quo with a tracking issue seems adequate.
