### ISSUE TITLE
Large SDK diff in 8.0.1xx branch

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4002]
Many (all?) files are showing in SDK diff in 8.0.1xx branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=2358818&view=results

**Comment by NikolaMilosavljevic** [comment]
This should be fixed by latest coherency update: https://github.com/dotnet/installer/pull/18305

Will monitor the SDK diff pipeline for results.

**Comment by mthalman** [comment]
The links you point to are in the context of the main branch, but you're also referring to 8.0.1xx branch. Can you clarify that?

**Comment by NikolaMilosavljevic** [comment]
> The links you point to are in the context of the main branch, but you're also referring to 8.0.1xx branch. Can you clarify that?

I've updated the link in initial comment. Coherency update is indeed for `main` branch - will update that comment with correct link if it's available.

**Comment by NikolaMilosavljevic** [comment]
Investigating...

**Comment by mthalman** [comment]
In general, there can often times be diffs that show up in the public release/8.0.1xx branch due to incoherency that is later resolved in internal/release/8.0.1xx. As long as diffs in internal/release/8.0.1xx are ok, we should be good for release.
