### ISSUE TITLE
Red Hat’s wishlist for .NET for 2024

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#4005]
Over at Red Hat, we have been thinking about the most important things we would like to see from the .NET project in 2024. This is the list that we ended up with, roughly sorted in order of priority/importance to Red Hat.

## Minimize differences between different builds of .NET 9

Issue: https://github.com/dotnet/source-build/issues/4010

This includes both how the product is built, and what product is built.

We know that Microsoft also intends to move to using the VMR for releases, but there are still differences between how (and what) things are built by Microsoft vs source-build. We would like to see everyone building out of one repo/commit/tag as much as possible and minimize the differences in sources between the sources used for various builds of .NET.

There is also a difference between the contents of the generated SDK, such as which files are in the SDK (see [the baseline diff](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/baselines/MsftToSbSdkFiles.diff)) as well as contents of the files (eg, optimization levels, or the .NET TFMs they are targeting). 

## Support building SDKs that can build self-contained, ReadyToRun and NativeAOT without nuget.org.

Issue: https://github.com/dotnet/source-build/issues/1215

Customers like to create smaller self-contained applications, and we would like to be able to support them by making sure that the components used are from the SDK, and we can fix any issues that come up.

This is a left-over from last year.

## Finished/polished user story for sources, binaries and symbols for debugging.

Issue: https://github.com/dotnet/source-build/issues/3225 

We would like for users using .NET tools (like VSCode) to be able to build/debug their .NET applications using a source-build SDK, and have the same experience. 

We want to make sure any customers running .NET workloads in production can use standard tools like dotnet-dump (and others suggested by Microsoft support) against .NET running on RHEL and containers.

**Comment by ashnaga** [comment]
Discussions and progress -
Minimize differences between different builds of .NET 9 - 
Unified build is foundational and will be step-by-step process to minimize the differences.

Support building SDKs that can build self-contained, ReadyToRun and NativeAOT without nuget.org. -
This is in progress where bug-fix level work is in-progress - https://github.com/dotnet/source-build/issues/1215#issuecomment-1964759735
Last step would be to enable acquiring source built ILCompiler pack. @tmds on it.

Finished/polished user story for sources, binaries and symbols for debugging -
With this being broad topic, starting to investigate with VSCode and will share the learnings.

**Comment by omajid** [comment]
Given that we are close to the end of 2024, and it's far too late for any major changes to .NET 9, I am going to close this issue.

I have opened a follow up (but Work in Progress) issue for 2025: https://github.com/dotnet/source-build/issues/4697
