### ISSUE TITLE
SourceBuild.MSBuildSdkResolver task - is it used or should it be removed?

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4006]
This custom resolver was used in the past, but there were issues, especially with `--with-sdk` option (https://github.com/dotnet/source-build/issues/1532).

It should be investigated further if this resolver can be used for file mutations work. If not, the code should be deleted.

Clarification: the task is built and copied to the SDK, but the question is if it provides any functionality.

**Comment by MichaelSimons** [comment]
[Triage]  This is being used.
