### ISSUE TITLE
Introduce control into root build scripts to disable building tests

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4008]
The Unified Build Controls epic changes the default for building tests when just building a normal VMR build.. Instead, tests are built. A build option should be added that will skip tests.

Source only builds have the same defaults.

**Comment by mmitche** [comment]
All the supporting functionality hasn't been added yet but the switch can be added prior to that.

**Comment by tkapin** [comment]
Depends on Viktor's work on source-build defaults.

**Comment by mmitche** [comment]
Waiting on control rename that Viktor made in arcade yesterday.

**Comment by mmitche** [comment]
https://github.com/dotnet/installer/pull/18464

**Comment by mmitche** [comment]
Resolved conflicts, re-validating.

**Comment by mmitche** [comment]
Completed
