### ISSUE TITLE
aspnetcore license scan failure on package-lock.json

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4014]
The source-build-license-scan pipeline has a [failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=2358819&view=results) (internal link) for the aspnetcore repo with these results:

```json
{
  "files": [
    {
      "path": "package-lock.json",
      "detected_license_expression": "mit AND apache-2.0 AND python AND (mit AND cc0-1.0) AND bsd-new AND bsd-simplified AND (mit OR apache-2.0) AND cc-by-4.0 AND blueoak-1.0.0 AND cc-by-3.0 AND cc0-1.0"
    }
  ]
}
```

**Comment by mthalman** [comment]
@omajid - This showed up because of a new referenced license: https://blueoakcouncil.org/license/1.0.0. Does that look ok to you?

**Comment by omajid** [comment]
It's on the list of licenses allowed in Fedora:

- https://docs.fedoraproject.org/en-US/legal/allowed-licenses/#_allowed_licenses
- https://gitlab.com/fedora/legal/fedora-license-data/-/issues/148
- https://gitlab.com/fedora/legal/fedora-license-data/-/blob/main/data/BlueOak-1.0.0.toml

It's under some discussion by OSI: http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-December/005452.html. I am not familiar with their process so I am not sure what the conclusion is.

**Comment by omajid** [comment]
FYI, Blue Oak was approved by OSI: https://opensource.org/license/blue-oak-model-license/
