### ISSUE TITLE
source-build-externals license scan failure on spectre-console README

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4015]
The source-build-license-scan pipeline has a [failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=2358819&view=results) (internal link) for the source-build-externals repo with these _new_ results:

```json
{
  "files": [
    {
      "path": "src/spectre-console/README.md",
      "detected_license_expression": "mit AND unknown-license-reference AND apache-2.0"
    }
  ]
}
```

**Comment by omajid** [comment]
The scan results seem correct:

> Spectre.Console is provided as-is under the MIT license. For more information see LICENSE.
>
> - SixLabors.ImageSharp, a library which Spectre.Console relies upon, is licensed under Apache 2.0 when distributed as part of Spectre.Console. The Six Labors Split License covers all other usage, see: https://github.com/SixLabors/ImageSharp/blob/master/LICENSE

So that does sound like MIT, Apache-2.0 and an unknown license. Given that we don't use SixLabors.ImageSharp, we should probably filter out the unknown license? Would it be worth it to report to this SPDX to get an ID?
