### ISSUE TITLE
SDK content diffs - .NET 9 - roslyn

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4016]
Microsoft and source-built SDKs contain the following difference related to `roslyn` content and packages. There should be no unintentional differences.

All intentional differences should be captured in SDK diff exclusion file: 

Related files only present in Source-built SDK:
```
./sdk/x.y.z/Roslyn/bincore/System.Collections.Immutable.dll
./sdk/x.y.z/Roslyn/bincore/System.Reflection.Metadata.dll
```

Related to https://github.com/dotnet/source-build/issues/4013

**Comment by ellahathaway** [comment]
I believe that this may be related to https://github.com/dotnet/roslyn/pull/71579.

**Comment by mthalman** [comment]
This is because of https://github.com/dotnet/format/issues/2075.

The reason it's not in the VMR is because we have a [patch that removes it](https://github.com/dotnet/installer/blob/main/src/SourceBuild/patches/format/0001-Remove-RazorCompiler-dependency.patch).

This is essentially a version coherency issue. The format repo needs to update its dependency to be a newer version of Roslyn.

Because of that, this SDK diff is expected.

**Comment by ellahathaway** [comment]
Possibly added back in by https://github.com/dotnet/roslyn/pull/73697?

**Comment by mthalman** [comment]
In general, it's preferred to open a new issue in this case since the original issue was successfully resolved.

**Comment by ellahathaway** [comment]
> In general, it's preferred to open a new issue in this case since the original issue was successfully resolved.

Good to know! I'll be sure to do that next time :)

**Comment by ellahathaway** [comment]
The diffs are no longer appearing in [the latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2502184&view=results) (internal Microsoft link). This is the second time these diffs have appeared and disappeared, so I think that it is still worth investigating what is causing these diffs.

**Comment by ellahathaway** [comment]
Diffs removed from baseline in https://github.com/dotnet/sdk/pull/42393 - continuing to investigate

**Comment by ellahathaway** [comment]
The diffs were removed with the rebootstrapping that occured: https://github.com/dotnet/dotnet/commit/2053724a494c1746adda86b3e0a014390013c1d2. Closing this issue.
