### ISSUE TITLE
Remove 'aspnetcore' repo exclusion in non-source build scenario

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4022]

**Comment by mmitche** [comment]
@wtgodbe

**Comment by wtgodbe** [comment]
@mmitche can you elaborate what exactly this means/what the ask is here? Is this blocked on anything?

**Comment by mmitche** [comment]
Removing https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/repo-projects/Directory.Build.targets#L34.

Right now aspnetcore doesn't fully build on Windows in the unified build mode.

**Comment by mmitche** [comment]
Note that some of this work (aspnetcore...probably?) may require the work by @mthalman to separate the inputs of each repo so that we don't override versions of all components that happen to build before aspnetcore.

**Comment by mmitche** [comment]
Initial interesting findings:
- aspnetcore kills builds host build processes.
- It generates a warning when ONlyBuildRepoTasks is passed (and nothing else)

https://github.com/dotnet/aspnetcore/pull/54081 covers these.

Additionally, the following problems have been found in testing:
- The repo seems to rely on a locally installed dotnet runtime to find the apphost headers. This won't work. I've temporarily worked aournd this by pointing at DotNetRoot, but this is not the correct version of the runtime. The apphost headers don't change much so it's a decent workaround for now.
- The repo wants to mutate that local SDK and then do a build afterward based on a newly built ref pack. This isn't a great approach (you can't modify the root SDK).

**Comment by mmitche** [comment]
Complete!
