### ISSUE TITLE
Remove 'installer' repo exclusion in non-source build scenario

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4033]

**Comment by mmitche** [comment]
Installer is on its way, but needs some additional work.

**Comment by MichaelSimons** [comment]
@mmitche - Can you clarify what exclusions you are referring to here?  Is this source-mapping exclusions or something else?

**Comment by mmitche** [comment]
The parent mini-epic links to a PR that added exclusions for repos that don't currently work when building in non-source build configurations (typically on Windows). https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/repo-projects/Directory.Build.targets#L29-L46

We're working on driving this down to zero.
