### ISSUE TITLE
Figure out how to restore internal tooling when building via VMR.

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4039]
When building via VMR in non-SB mode (official builds), some projects require internal tooling. This is usually repos that use IBC training data. This restore is through `eng/common/internal/Tools.proj`. Most of the time today this is run as a separate YAML step. This is pretty awkward to do in VMR land.

Figure out how to restore the internal tools when needed.

**Comment by mmitche** [comment]
I'm exploring option A.

**Comment by ViktorHofer** [comment]
Tools.proj is probably really the best location for this. It's just sad that we would invoke this 30 times, for every repository without any kind of shared cache. But this already applies to any NuGet restore operation in the repo builds.

**Comment by mmitche** [comment]
We only need it if you need IBC data, so it's only like 5 times.

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/pull/14418 may do it. At least, it works in the VMR.
