### ISSUE TITLE
CI legs with PreviousSourceBuiltSdk are failing

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4044]
The error (internal link): https://[dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2361916/logs/157](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2361916/logs/157)

It appears that the issue is with `--with-sdk` switch.

**Comment by NikolaMilosavljevic** [comment]
@ViktorHofer your PR (https://github.com/dotnet/installer/pull/18358) seems to have modified `build.sh` and is a likely culprit. Can you take a look?

**Comment by ViktorHofer** [comment]
Yes
