### ISSUE TITLE
[release/9.0.1xx-preview1] Poison test is failing

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4046]
Poison test is failing for the Alpine319_Offline_PreviousSourceBuiltSdk_x64 build leg. This is because all poison leaks are fixed so the baseline needs to reflect that.

**Comment by MichaelSimons** [comment]
[Triage] @mthalman - Is there anything remaining here to fix or can this be closed?

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/installer/pull/18443
