### ISSUE TITLE
Release pipeline generates invalid build number on successive retries

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4049]
The [logic to update the release build number](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/eng/pipeline/source-build-release/stages/pre-release.yml&version=GBmain&line=165&lineEnd=166&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) (internal link) can fail if you retry the build too many times. The build number keeps stacking on top of each other until it hits the character limit.

An example of the error produced by this:

```
##[error]TF209010: The build number format 20240122.3-7.0.406-servicing.24069.16,7.0.313-servicing.24069.17,7.0.116-servicing.24069.15-208911,208910,208909-3-7.0.406-servicing.24069.16,7.0.313-servicing.24069.17,7.0.116-servicing.24069.15-208911,208910,208909-3-7.0.406-servicing.24069.16,7.0.313-servicing.24069.17,7.0.116-servicing.24069.15-208911,208910,208909-7 contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'.
```

**Comment by oleksandr-didyk** [comment]
Changed the logic to only use the revision number
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37216

**Comment by oleksandr-didyk** [comment]
PR merged, should work as expected starting from March release
