### ISSUE TITLE
[release pipeline] Tag is missing "v" prefix in DSP repo

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4052]
When the source build release pipeline mirrors the source to dotnet-security-partners, it generates a tag without the "v" prefix (e.g. `8.0.2` instead of `v8.0.2`). This is inconsistent with the behavior of the legacy pipeline.

**Comment by omajid** [comment]
This also affects the release.json.

**Comment by oleksandr-didyk** [comment]
PR merged, Preview 2 should have the proper tag
