### ISSUE TITLE
Ensure that repos that do not need to sign in the VMR (e.g. arcade) have empty ItemsToSign lists

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4063]
Some repositories don't require signing in VMR builds. Repos that we know do not contribute any artifacts that will be redisted by shipping packages in other components should have their ItemsToSign lists emptied.

I think arcade may be the only case of this.

This does not require any of the rest of the signing work to be complete.

**Comment by ellahathaway** [comment]
**T-Shirt Size: XS**

**Comment by ellahathaway** [comment]
I think arcade might be the only one as well. Looking through the repos defined in the source-manifest.json, I don't see any other repos that would fit this requirement: https://github.com/dotnet/dotnet/blob/main/src/source-manifest.json
