### ISSUE TITLE
Enable signing for arcade repos in the VMR build

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4064]
Enable signing for arcade repos in the VMR build. This may be as simple as ensuring that -sign gets passed? This may not be sufficient though, as signing may have been disabled under UB modes in Arcade at some point. Investigate and fix.

It should be possible to do this work on Windows VMR legs without the other SignTool work being completed.

**Comment by ellahathaway** [comment]
As part of this work, we should adjust eng/common/cibuild.sh to include the `--sign` flag by default: https://github.com/dotnet/arcade/blob/7e8b8f4f321c8671aa01b53567d31aaa4950706f/eng/common/cibuild.sh#L16

This is current included in windows by default: https://github.com/dotnet/arcade/blob/7e8b8f4f321c8671aa01b53567d31aaa4950706f/eng/common/CIBuild.cmd#L2

**Comment by mmitche** [comment]
That's a good idea. We explicitly pass the switches for sign and pack and whatnot in the VMR `BuildActions` property today

**Comment by ellahathaway** [comment]
**T-Shirt Size: XS/S**
