### ISSUE TITLE
Ensure that files from NuGet.Client (non-arcade repo) gets signed when building SDK

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4065]
Verify that NuGet.Client files are getting signed when the SDK repo signs. Generally sdk has picked up any signing "slack" from other repos, so this work item is just to call this out explicitly.

Depends on #4064

**Comment by ellahathaway** [comment]
T-Shirt Size: ?

I think that this could be as simple as verifying that these get signed when SDK signs to adding these as items to sign in sdk & have them recognized by signtool to having to add infra to SDK to produce these files? I'm not very familiar with the current infra to estimate the size of this work.
