### ISSUE TITLE
[release pipeline] 6.0/7.0 branches are named incorrectly

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4071]
Branches for 6.0 and 7.0 end in `-` (example: `dev/6.0.127-feb2024-`). This trailing dash should be removed.

**Comment by oleksandr-didyk** [comment]
Unquoted variable in a conditional in the mirroring script led to the trailing dash
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37216

**Comment by oleksandr-didyk** [comment]
PR merged, should work as expected starting from March release
