### ISSUE TITLE
Source-build tasks should use `System.Text.Json`

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4078]
At least two tasks are not using System.Text.Json yet:
- `UpdateJson` - https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UpdateJson.cs
- `GetJsonAttributeValue` - added with https://github.com/dotnet/installer/pull/18478

Please fix.

**Comment by MichaelSimons** [comment]
This is a duplicate of https://github.com/dotnet/source-build/issues/921
