### ISSUE TITLE
VMR builds based on N-1 SDK failing on ILCompiler

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4083]
[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2368347&view=results)

```
/vmr/src/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64. No packages exist with this id in source(s): prebuilt, previously-source-built, reference-packages, source-built [/vmr/src/runtime/Build.proj]
/vmr/src/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Crossgen2.linux-musl-x64. No packages exist with this id in source(s): prebuilt, previously-source-built, reference-packages, source-built [/vmr/src/runtime/Build.proj]
/vmr/src/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.linux-x64. No packages exist with this id in source(s): prebuilt, previously-source-built, reference-packages, source-built [/vmr/src/runtime/Build.proj]
```

This is a regression caused by https://github.com/dotnet/installer/pull/18476.

**Comment by directhex** [comment]
Let me see if I can reproduce this. I did think Musl was problematic, but didn't see it in the CI runs

**Comment by mthalman** [comment]
Alpine doesn't run in the CI build; only CentOS. But it's not specific to Alpine either. It's specific to the N-1 scenario. You can see this failing for CentOS as well in the [internal CI](https://dev.azure.com/dnceng/internal/_build/results?buildId=2368375&view=results) (internal link).

**Comment by directhex** [comment]
`Unable to find image 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8' locally` https://dev.azure.com/dnceng/internal/_build/results?buildId=2368375&view=logs&j=273502c4-a2ec-5aef-1ae2-d1442236a3bf&t=ec74e70b-0182-5ebe-fbc0-ee1ba2cedc2b

Not taking the blame for _that_ failure! 

I'll try and repro N-1 for Fedora though, that should be an easier clearer repro than adding Musl to the mix

**Comment by mthalman** [comment]
Right, not that one but this CentOS one is relevant: https://dev.azure.com/dnceng/internal/_build/results?buildId=2368375&view=logs&j=9ef76f09-17e5-5a2c-f362-f1b1e929de60&t=eb2f7916-e428-5f84-d98b-11a989889428

**Comment by directhex** [comment]
Is it possible to trigger the N-1 tests on a PR?

**Comment by mthalman** [comment]
> Is it possible to trigger the N-1 tests on a PR?

No, not without changing the pipeline. Those legs get conditioned out in https://github.com/dotnet/installer/blob/db6f1a6e177875ae76b8195717ce5a0765ce5d46/eng/pipelines/templates/stages/vmr-build.yml#L92

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/installer/pull/18501
