### ISSUE TITLE
Update source-build/unified-build to newer Ubuntu AzDO image

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/source-build#4084]
Right now we get this warning because we're still using Ubuntu 18.04 AzDO VMs:
> ##[warning]The agent operating system doesn't support Node20. Using Node16 instead. Please upgrade the operating system of the agent to remain compatible with future updates of tasks

We should fix this to use e.g. Ubuntu 20.04 or 22.04 (the actual builds run in containers anyway):
```
ImageOverride -equals Build.Ubuntu.1804.Amd64.Open
```

**Comment by MichaelSimons** [comment]
It looks like we are already using [Ubuntu 22.04 container images](https://github.com/dotnet/installer/blob/main/eng/pipelines/templates/variables/vmr-stage.yml#L22) yet this warning is still present.

**Comment by akoeplinger** [comment]
Yes because this is about the host, not the container. The host is still using 18.04:
https://github.com/dotnet/installer/blob/5003feccb9f5906d04feba63625c47f6b08121ea/eng/pipelines/templates/variables/vmr-stage.yml#L40
