### ISSUE TITLE
Provide a script to remove all checked binaries from your local environment

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4089]
This is needed to support distro-maintainers who have policies the prohibit checked-in binaries.  See https://github.com/dotnet/source-build/issues/4088 for additional details.

The existing binary detector tool/test may be useful in detecting which binaries to strip.

**Comment by ellahathaway** [comment]
Do we need any binaries for SB at all? I'm currently thinking that this script will remove all checked in binaries of types .dll, .Dll, .exe, .mdb, .nupkg, .pbd, .tgz, .zip, regardless of the binaries in the allowed list. The allowed list will only be used for the non-sourcebuild builds in this case.

**Comment by ellahathaway** [comment]
Per https://github.com/dotnet/installer/pull/18563#discussion_r1486476087, the direction of this work has changed. 

We will now have a separate list of files/patterns that should be deleted with a provided script. This list will be easily parseable in bash. The list will be located in each repo, and if that repo has submodules, then the exclusion file 'speaks' for the inlined submodules. The binary check keys off this in repo legs, and the exclusion script just reads patterns from the file to delete. This binary check will also check for any additional binaries not in the list. This work should be completed alongside https://github.com/dotnet/source-build/issues/4108

As such, the work for this issue will be part of building up the binary removal and validation infra in Arcade.
