### ISSUE TITLE
Delete the main-ub branch

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4090]
Once the binary cloaks have been removed from the main branch (see https://github.com/dotnet/source-build/issues/4087).  The main-ub branch as well as the backing infrastructure to sync it should be removed/cleaned up.

**Comment by ViktorHofer** [comment]
As part of this work, pipeline triggers in AzDO dnceng-public/public and dnceng/internal need to be updated. Otherwise unified build pipelines would stop running. In the pipeline settings, the default branch needs to be updated as well.
