### ISSUE TITLE
CentOSStream8_Mono_Offline_MsftSdk_x64 leg is failing due to missing ROOTFS_DIR

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4092]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2368375&view=results

Last successful run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2367435&view=results

There are 5 commits in new run, most for dependency flow.

Suspect PR: https://github.com/dotnet/installer/pull/18476

cc @directhex 

Error:
```
      Commencing build of "  iltools " target in "CoreCLR component" for linux.x64.Release in /vmr/src/runtime/artifacts/obj/coreclr/linux.x64.Release
      Invoking "/vmr/src/runtime/eng/native/gen-buildsys.sh" "/vmr/src/runtime/src/coreclr" "/vmr/src/runtime/artifacts/obj/coreclr/linux.x64.Release" x64 linux clang Release ""  -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_PATH= -DCLR_CMAKE_PGO_OPTIMIZE=0 -DCLI_CMAKE_FALLBACK_OS="centos.8" -DFEATURE_DISTRO_AGNOSTIC_SSL=0  -DCLR_CMAKE_KEEP_NATIVE_SYMBOLS=true
      ROOTFS_DIR not set for crosscompile
##[error]Failed to generate "CoreCLR component" build project!
```

**Comment by NikolaMilosavljevic** [comment]
This also reproes in my private VMR build (https://dev.azure.com/dnceng/internal/_build/results?buildId=2368922&view=results) which includes more changes from `installer` repo (up to 7a829e58d30ff9b8de6d5c0a8c160059ff40c917)

**Comment by ViktorHofer** [comment]
@directhex looks like [your change](https://github.com/dotnet/installer/commit/cca2b7bedef771c45eec62492017dde51199378d#diff-3de696aba794a0ce36c0c339dd1fbc20d57d494f6b161eb005cb1655d71b3079) caused the regression. PTAL.

**Comment by ViktorHofer** [comment]
I just noticed this difference in the last passing build and the currently failing one:

```
+ [[ True == \T\r\u\e ]]
+ customEnvVars='BUILD_SOURCEVERSION=ababfa8c60f99a23f07e5bd03ad2e0cc4a9fddb3 CROSSCOMPILE=1'
```

In the last passing build, `CROSSCOMPILE=1` wasn't passed in as an env var: https://dev.azure.com/dnceng/internal/_build/results?buildId=2367435&view=logs&j=6a27b9b5-d8ec-5163-169b-8b2be859a5ea&t=787e31b3-ac99-5202-0798-f52b20936314

Probably caused by this https://github.com/dotnet/installer/commit/cca2b7bedef771c45eec62492017dde51199378d#diff-dc549eeb99aa73960e74c9d4c160a3c76e3e414398bb348c1d5365aac0369ad5L250-R259

**Comment by ViktorHofer** [comment]
Before the change, `targetRid` not empty and `useMonoRuntime` true meant => this is a cross-build. Now, without targetRid, all builds that set `useMonoRuntime` true are considered cross-builds.

Should a new parameter be added, i.e. `isCrossBuild: true` or should the logic be conditioned on the already existing `crossRootFs` parameter?

**Comment by directhex** [comment]
Hm. Normally I'm a believer in not using conditional A to control behaviour B, but I think in this case conditioning on `crossRootFs` is correct and adding a new parameter would be needlessly duplicative

**Comment by ViktorHofer** [comment]
Agreed. I think you would only ever set crossRootFs when cross-building.
