### ISSUE TITLE
SDK Diff and License pipelines should publish PRs for updated baselines

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4093]
Currently, updating and investigating changes to the sdk diff and license test baselines is a time-consuming process, especially when differences are occurring daily. We need some way to automate the process for updating these baselines. I propose having the pipelines publish a PR for the diffs when there is a failing test.

**Comment by MichaelSimons** [comment]
Related to https://github.com/dotnet/source-build/issues/3910

**Comment by MichaelSimons** [comment]
[Triage] @ellahathaway - Can you split this issue apart as I think we would implement the two parts independently.

**Comment by ellahathaway** [comment]
Closed by https://github.com/dotnet/sdk/pull/40753
