### ISSUE TITLE
Ubuntu2204Arm64_Offline_MsftSdk_arm64 timout for internal/8.0.1xx

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4098]
The internal 8.0.1xx branch is timing out in the Ubuntu2204Arm64_Offline_MsftSdk_arm64 leg. [Link to build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2368578&view=logs&j=0bf36158-843f-57d9-fe78-bca5fcea110c) (internal link). The timeout occurs after roslyn has finished building.

**Comment by mthalman** [comment]
Does a retry work? These Arm machines have occasionally been know to just sit there indefinitely.

**Comment by ellahathaway** [comment]
That worked! Closing the issue.
