### ISSUE TITLE
Put the final artifacts in the arcade well known output locations

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4104]
The VMR currently puts _some_ of the final artifacts under `artifacts/<arch>/<configuration>/...`. This includes the source-build tarball and other artifacts but none of the nuget packages (which are missing when not building from source).

It would be good to change that to the Arcade convention which is `artifacts/packages/<configuration>/<Shipping|NonShipping>/` so that we can use the default Arcade templates for publishing artifacts to the pipeline and for publishing to BAR.

As part of this, the README.md should also be updated.

**Comment by MichaelSimons** [comment]
We should include a note in the source-build release announcement for this as it will impact distro-maintainers.
