### ISSUE TITLE
Wire up package diffing tool into official build CI

### ISSUE THREAD

**Issue by jtschuster** [dotnet/source-build#4106]
The package diffing tool (https://github.com/dotnet/source-build/issues/4051) needs to run during official VMR builds and compare to the current official build and a baseline.

**Comment by mmitche** [comment]
I think this has been completed. Verifying.

**Comment by mmitche** [comment]
The current setup compares the just-built assets to themselves, it appears.

**Comment by mmitche** [comment]
But it is wired up, so I'm going to open a new issue for this.
