### ISSUE TITLE
Offline builds fail trying to access online feeds

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4107]
```
  /vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json.
```

Failing build (internal microsoft link) - https://dev.azure.com/dnceng/internal/_build/results?buildId=2373582&view=logs&j=a361eaf5-91c0-5b8d-1f36-c97d0865c360&t=8198a24c-af12-5a92-d480-67a88a3b425d

**Comment by ellahathaway** [comment]
For source build monitoring - the latest run of source-build-sdk-diff-tests is failing in all legs due to this issue; latest run cannot find any associated artifacts from the full build.

**Comment by MichaelSimons** [comment]
> I think this is what was fixed by [dotnet/installer#18565](https://github.com/dotnet/installer/pull/18565). The full VMR build hasn't run since that came in. The lite pipeline is passing.

I triggered a new run this morning after those changes. - I updated the linked build.

**Comment by MichaelSimons** [comment]
@jkoritzinsky, can you take a look?

**Comment by jkoritzinsky** [comment]
Looks like it's failing to find the Microsoft.Dotnet.SourceBuild.Tasks library locally. I'll try to figure out how this was working beforehand.

**Comment by jkoritzinsky** [comment]
@MichaelSimons looks like the RestoreConfigFile isn't being passed down. The fix for this is in https://github.com/dotnet/runtime/pull/97778, which is newer than the dotnet/runtime currently in the VMR (https://github.com/dotnet/runtime/commits/d40c654c274fe4f4afe66328f0599130f3eb2ea6).

Once this change flows through (https://github.com/dotnet/installer/pull/18457), then this should be fixed.

**Comment by MichaelSimons** [comment]
Interesting, I thought we were already carrying the fix for https://github.com/dotnet/runtime/pull/97778 as a patch - https://github.com/dotnet/installer/blob/main/src/SourceBuild/patches/runtime/0001-Enable-use-of-RestoreConfigFile-property-in-source-b.patch

When I look at the tip of the VMR, This doesn't appear to be applied.

**Comment by MichaelSimons** [comment]
That patch somehow didn't get applied in https://github.com/dotnet/dotnet/commit/02e37034dd960698a4fc96337e650b82313be224.  @premun, Can you explain what happened here?
