### ISSUE TITLE
ArPow source-build publishing infrastructure shouldn't filter artifacts

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4110]
Right now, at least `symbols.nupkg` files are filtered out: https://github.com/dotnet/arcade/blob/05c02be5e2ac7e7ec2dafc59652f2b22f0e22550/src/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuild/SourceBuildArcade.targets#L114-L115

We need these files to ship the product when not building from source. UB doesn't use the repo symbol archives.

Not sure about the source-build intermediate packages, they probably don't need the symbol packages but the manifest should list them.

I know there are separate issues talking about unifying the publishing infrastructure but I think we should fix this meanwhile.

@NikolaMilosavljevic as you know the code base best, can you please take a look?

cc @mmitche

**Comment by NikolaMilosavljevic** [comment]
This is intentional. Filtering could be modified for not source-only builds. It should be easy.

However, I am working on https://github.com/dotnet/source-build/issues/4101 which will update ArPow to support proper publishing and get rid of this filtering, even in source-only builds.

**Comment by NikolaMilosavljevic** [comment]
Fixed with VMR publishing work: https://github.com/dotnet/source-build/issues/4101
