### ISSUE TITLE
Repo binlogs should be copied to artifacts/log in the product build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4112]
The current artifacts log layout is bizarre:

![image](https://github.com/dotnet/source-build/assets/7412651/413200fc-557c-4997-87a4-cb4483158442)

I think it would make more sense if the inner and outer repo build would put their binlog directly into the VMR's `artifacts/log/<configuration>/` folder.

Example:
- artifacts/log/Release/arcade-outer-build.binlog
- artifacts/log/Release/arcade-inner-build.binlog

We will introduce a new environment variable that specifies the log folder to write into. If a repository produces more binlogs, they should respect that env var and write to that folder. I.e. fsharp

**Comment by omajid** [comment]
Is there an arcade/source-build variable that can be used to find the top-level artifacts/log directory from each repo? Or should we introduce the environment variable and then teach arcade to use for `CurrentRepoSourceBuildBinlogFile`?

**Comment by ViktorHofer** [comment]
Hey thanks for picking this up 👍 No, we don't yet have an env var for that. Naming suggestions? :)

**Comment by omajid** [comment]
Some random suggestions:

- DotNetOutputBinlogDir
- DotNetBuildOutputBinlogDir
- DotNetBuildOutputLogDir 
- DotNetArtifactsLogDir

**Comment by ViktorHofer** [comment]
One more: DotNetBuildBinlogDir

Implies that this affects the product build and binlogs.

**Comment by ViktorHofer** [comment]
The desired end result is that we have all binlogs and possibly other logs in a common location at the end of the VMR build.

```
└── artifacts       
        └── log
            └── Release
                ├── Build.binlog                        <-- The VMR orchestrator binlog
                ├── init-source-only.binlog             <-- The VMR orchestrator source-build init binlog
                └── fsharp   
                    ├── Build.binlog
                    ├── source-inner-build.binlog
                    ├── Build.binlog+.proto.binlog

 Giving this a bit more though, `DotNetBuildArtifactsLogDir` sounds good to me as we could have other logs than just binlogs and the logs dir is called ArtifactsLogDir today.

**Comment by Winniexu01** [comment]
Hi @ViktorHofer, I backport this from main to release/9.0.1xx to maintain consistency in the file structure. Now I want to know should I backport this to release/8.0.1xx?

**Comment by MichaelSimons** [comment]
> Now I want to know should I backport this to release/8.0.1xx?

No, The build infrastructure changed a lot with the Unified Build project during 9.0.  It take a significant effort to backport for little ROI.
