### ISSUE TITLE
Repo source-build should copy sources instead of git clone

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4117]
https://github.com/dotnet/arcade/blob/b372abae012cab2dbf011bd39c395e940e35da86/src/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuild/SourceBuildArcadeBuild.targets#L98

`CopySrcInsteadOfClone` should probably default to true?

cc @NikolaMilosavljevic

**Comment by MichaelSimons** [comment]
Why is copy preferred over clone?

**Comment by ViktorHofer** [comment]
When I talked with @NikolaMilosavljevic offline he mentioned that copying should be preferred over git clone. @NikolaMilosavljevic can you please provide some arguments on that?

For me the obvious ones are avoiding the unnecessary networking calls and the extra work to resolve the git deltas.

**Comment by NikolaMilosavljevic** [comment]
I don't have any "hard" data myself. I've heard few times that copy would solve some issues, but I don't have a preference here.

**Comment by MichaelSimons** [comment]
@ViktorHofer points out in https://github.com/dotnet/runtime/pull/98476 how some sourcelink changes require copy instead of clone.  This raises a question to me if the clone option should be retained or if we should only support the copy option?

**Comment by MichaelSimons** [comment]
Per in-person discussion we would like to validate to ensure there are no scenarios that require the clone - e.g. repos with submodules.  If no repos require clone, we feel it is best to remove it and only have the copy path.
