### ISSUE TITLE
Automate tarball creation validation for .NET 6/7 in release pipeline

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4122]
One of the manual steps in the release pipeline for 6.0 and 7.0 is to validate that the tarball can be created from the installer repo: https://github.com/dotnet/release/blob/e61071c1146757ac5d0e02909961a4e5048b25fc/.github/ISSUE_TEMPLATE/source-build-release.md?plain=1#L153-L156. Automating this would be helpful.

**Comment by MichaelSimons** [comment]
[Triage] This should be in a separate stage due to the number of failures we find in mirroring failures.

**Comment by MichaelSimons** [comment]
[Traige] This is worth doing if the cost it low.  If that is not the case, we should reconsider given the EOL timeframes of these versions.

**Comment by oleksandr-didyk** [comment]
PR for removing the manual step in the release checklist - https://github.com/dotnet/release/pull/825

**Comment by oleksandr-didyk** [comment]
Both PRs merged, closing
