### ISSUE TITLE
Incorrect use of "Release Name" in release pipeline

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4127]
The [release checklist](https://github.com/dotnet/release/blob/e61071c1146757ac5d0e02909961a4e5048b25fc/.github/ISSUE_TEMPLATE/source-build-release.md?plain=1#L46) indicates that the release name should be in the form of `X.0` for a VMR-based servicing release. This is incorrect because it creates a GH release in the dotnet/dotnet repo with that title. For example, it originally created this [8.0.2 release](https://github.com/dotnet/dotnet/releases/tag/v8.0.2) with a title of ".NET 8.0" when it should have been ".NET 8.0.2".

Changing the checklist to use a three-part version number is simple enough. However, changing that impacts the release announcement that gets created in the dotnet/source-build repo. For example, the corresponding announcement of the 8.0.2 release is here: https://github.com/dotnet/source-build/discussions/4126. This has a title of ".NET 8.0 February 2024 Update - .NET 8.0.2 and SDK 8.0.102". If we changed the checklist to say that the release name should be ".NET 8.0.2", that would impact the beginning portion of this title by changing it from ".NET 8.0" to ".NET 8.0.2".

We either need to change the pipeline to vary the value according between the release title and announcement title OR we need to change the naming patterns between these two titles to more closely align so that no variation is needed.

**Comment by oleksandr-didyk** [comment]
I guess we can switch the release title to use `ReleaseVersion` from the release config, which in this example would be equal to `8.0.2`, and leave the announcement to use `releaseName` parameter mentioned in the release checklist

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37633

**Comment by oleksandr-didyk** [comment]
PR merged, closing
