### ISSUE TITLE
Release pipeline should allow Mirroring stage to be skipped

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4128]
For the release yesterday we had a need to rerun a pipeline that had already completed the Mirror stage. Since the Mirror stage had already been completed, there was no need to run it again. The only new stage that needed to be completed was the Release stage. I had configured the pipeline to skip the Mirror stage in order to make the process go faster and not use unnecessary compute. However, that caused the [Release stage to fail](https://dev.azure.com/dnceng/internal/_build/results?buildId=2378161&view=results) (internal link) in the `Download release manifest` step with this error:

```
##[error]Artifact ReleaseManifest was not found for build 2378161.
```

This is because it depends on the Mirror stage to create the ReleaseManifest artifact that gets published to the pipeline. Ideally, this would be moved to the Pre-Release stage so that the Mirror stage could be skipped.

This will be especially useful once signing is added into the Mirror stage which is going to really make that a slow stage.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37493

**Comment by oleksandr-didyk** [comment]
PR merged, closing
