### ISSUE TITLE
Incorrect SDK version for preview release in announcement

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4133]
The [.NET 9 Preview 1 release announcement](https://github.com/dotnet/source-build/discussions/4132) created by the release pipeline used an incorrect SDK version. In the title, it used `9.0.100` instead of `9.0.100-preview.1`. In the body, it used `9.0.100` instead of `9.0.100-preview.1.24101.2`.

**Comment by oleksandr-didyk** [comment]
This was fixed with https://github.com/dotnet/source-build/issues/4146

Example (test runs have an additional numeric suffix hence the difference in tag):


![Image](https://github.com/dotnet/source-build/assets/106967057/3fa41b62-512c-46e6-bfc3-7dfdabb8aef7)
