### ISSUE TITLE
Incorrect release notes link for preview release announcement

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4134]
The [.NET 9 Preview 1 release announcement](https://github.com/dotnet/source-build/discussions/4132) created by the release pipeline generated an incorrect URL for the release notes. It missed adding the `preview1` directory in the URL. It used `https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/9.0.0-preview.1.md` instead of `https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview1/9.0.0-preview.1.md`.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37636

**Comment by oleksandr-didyk** [comment]
PR merged, closing
