### ISSUE TITLE
Release PR submission failed for .NET 9 Preview 1

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4135]
The [release pipeline failed](https://dev.azure.com/dnceng/internal/_build/results?buildId=2378642&view=results) (internal link) in the `Submit Release PR` step with this error:
```
##[error] Element '\''PrivateSourceBuiltArtifactsUrl'\'' not found in the Versions.props file.'
```

**Comment by oleksandr-didyk** [comment]
The elements containing the links to the uploaded SDK were changed in https://github.com/dotnet/installer/pull/17370, but this was not reflected in the release pipeline for 9.0

PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37465

**Comment by oleksandr-didyk** [comment]
PR merged, closing
