### ISSUE TITLE
Add .NET 9 release pipeline validation build

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4136]
PRs for changes to the release pipeline run validation builds for each .NET version (6, 7, 8). It's missing .NET 9 which is important because it's a preview version which requires different code paths. We should add a .NET 9 build to the set.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37465

**Comment by oleksandr-didyk** [comment]
PR merged, closing
