### ISSUE TITLE
What is the expected name of the detached tarball signature from github?

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#4139]
For .NET 8.0.1, we had:  [`dotnet-8.0.1.tar.gz.sig`](https://github.com/dotnet/dotnet/releases/tag/v8.0.1)

For .NET 8.0.2, we have:  [`8.0.2.tar.gz.sig`](https://github.com/dotnet/dotnet/releases/tag/v8.0.2)

What is the expected file name of this file going forward?

**Comment by MichaelSimons** [comment]
[Triage] Aligning the name with the tarball is the desired behavior - `dotnet-8.0.1.tar.gz.sig`

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37492

**Comment by oleksandr-didyk** [comment]
Abandoned the PR until changes from https://github.com/dotnet/source-build/issues/3316 get in

**Comment by oleksandr-didyk** [comment]
PR with changes from https://github.com/dotnet/source-build/issues/3316 in place - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37605

**Comment by oleksandr-didyk** [comment]
PR merged, should be set correctly for `Preview 2`
