### ISSUE TITLE
8.0.2 release.json contains tag without v prefix

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#4140]
The [release.json](https://github.com/dotnet/dotnet/releases/download/v8.0.2/release.json) file for the [8.0.2 release](https://github.com/dotnet/dotnet/releases/tag/v8.0.2) looks like this:

```json
{
  "release": "8.0.2",
  "channel": "8.0",
  "tag": "8.0.2",
  "sdkVersion": "8.0.102",
  "runtimeVersion": "8.0.2",
  "sourceRepository": "https://github.com/dotnet/dotnet",
  "sourceVersion": "d396b0c4d3e51c2d8d679b2f7233912bc5bfc2fa"
}
```

The tag is listed as `8.0.2`, even though the tags page shows the tag is actually `v8.0.2` (with a `v` prefix).

Is this an issue in release.json? Or does the build system add a `v` prefix automagically?

**Comment by mthalman** [comment]
Yes, it's an issue in the release.json. This is related to https://github.com/dotnet/source-build/issues/4052. I've manually fixed the JSON file for both [8.0.2](https://github.com/dotnet/dotnet/releases/tag/v8.0.2) and [9.0.0-preview.1.24080.9](https://github.com/dotnet/dotnet/releases/tag/v9.0.0-preview.1.24080.9).

I'll keep this issue open until we manually verify this is fixed in our test builds.

**Comment by oleksandr-didyk** [comment]
This is fixed in our validation builds, but as Matt said is definitely worth checking manually in March test builds. Moving back to `On Radar` until closer to the March release start

**Comment by corngood** [comment]
This is sort of off-topic, but in 9.0 preview-1 we have `"sdkVersion": "9.0.100"`.  Should this instead be `"sdkVersion": "9.0.100-preview.1.24101.1"`?

The packaging guidelines say:

> In the `{dotnet_root}/sdk/<sdk version>` directory, the following two files are expected:

> Starting with .NET 8.0, all .NET debug content (PDB files), produced by source-build, is available in a tarball named `dotnet-symbols-sdk-<version>-<rid>.tar.gz`.

Both of these things include the preview version tag.  `runtimeVersion` includes the full version, which allows me to predict the names of the tarballs in the output, but I can't find a way to do the same for the sdk packages, without extracting something like this:

```
prereqs/git-info/sdk.props
6:    <OutputPackageVersion>9.0.100-preview.1.24101.1</OutputPackageVersion>
```

**Comment by mthalman** [comment]
Thanks for pointing that out, @corngood. I've logged https://github.com/dotnet/source-build/issues/4146.

**Comment by oleksandr-didyk** [comment]
The tag is correctly set in `test` builds, should work as expected for `Preview 2`:
```json
{
  "release": "8.0.3",
  "channel": "8.0",
  "tag": "v8.0.3",
  "sdkVersion": "8.0.103",
  "runtimeVersion": "8.0.3",
  "sourceRepository": "https://github.com/maestro-auth-test/private-dotnet",
  "sourceVersion": "xxx"
}
```
