### ISSUE TITLE
Update NuGet.Packaging versions in SBRP

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4141]
[SBRP](https://github.com/dotnet/source-build-reference-packages) currently defines NuGet.Packaging.6.6.1 and NuGet.Packaging.6.7.0, both of which are defined as vulnerable versions: https://github.com/advisories/GHSA-68w7-72jg-6qpp. This triggers component governance alerts on this repo. These should be updated to the next non-vulnerable patch version.

**Comment by mthalman** [comment]
6.8.0 is also affected by this.

**Comment by MichaelSimons** [comment]
@mthalman  - Is this work complete?

**Comment by mthalman** [comment]
yep

**Comment by ellahathaway** [comment]
[ NuGet.Packaging.6.6.1](https://github.com/dotnet/source-build-reference-packages/tree/release/8.0/src/referencePackages/src/nuget.packaging/6.6.1) is still an [active alert in 8.0](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-source-build-reference-packages/alert/9299603?typeId=17099473).

**Comment by mthalman** [comment]
I think what's happening is that it's picking up the old version from the SBRP self-reference. I'll update that.

**Comment by ellahathaway** [comment]
Closing since the CG alert is now resolved.
