### ISSUE TITLE
[release pipeline] SDK version not set correctly for preview version in release manifest

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4146]
For .NET 9 Preview 1, the [release manifest JSON](https://github.com/dotnet/dotnet/releases/download/v9.0.0-preview.1.24080.9/release.json) file was generated with an `sdkVersion` value of `9.0.100`. It should have been `9.0.100-preview.1.24101.1`. The `runtimeVersion` is correctly set.

See https://github.com/dotnet/source-build/issues/4140#issuecomment-1954263601

**Comment by corngood** [comment]
In 9.0 preview 1 I get:

```
dotnet-sdk-9.0.100-preview.1.24101.1-linux-x64
dotnet-symbols-all-9.0.100-preview.1.24101.1-linux-x64
dotnet-symbols-sdk-9.0.100-preview.1.24101.1-linux-x64
Private.SourceBuilt.Artifacts.9.0.100-preview.1.24101.1.linux-x64
Private.SourceBuilt.Prebuilts.9.0.100-preview.1.24101.1.linux-x64
```

However, in 8.0.2 I get:

```
dotnet-sdk-8.0.102-linux-x64
dotnet-symbols-all-8.0.102-servicing.24073.1-linux-x64
dotnet-symbols-sdk-8.0.102-servicing.24073.1-linux-x64
Private.SourceBuilt.Artifacts.8.0.102-servicing.24073.1.linux-x64
Private.SourceBuilt.Prebuilts.8.0.102-servicing.24073.1.linux-x64
```

The -servicing versions seem to be derived from `src/installer`, but `installer.props` has:

```
    <OfficialBuildId>20240123.1</OfficialBuildId>
    <OutputPackageVersion>8.0.100</OutputPackageVersion>
```

`sdk.props` has:

```
    <OfficialBuildId>20240119.16</OfficialBuildId>
    <OutputPackageVersion>8.0.102-servicing.24069.16</OutputPackageVersion>
```

In 9.0 preview 1, both the sdk and installer currently just happen to use `24101.1` (derived from 20240201.1).

The packaging docs say:

> Starting with .NET 8.0, all .NET debug content (PDB files), produced by source-build, is available in a tarball named dotnet-symbols-sdk-<version>-<rid>.tar.gz. This archive contains PDBs in subdirectories that match the directory structure of the .NET SDK tarball - dotnet-sdk-<version>-<rid>.tar.gz.

To me that sounds like they should use the same version.

**Comment by oleksandr-didyk** [comment]
The release automation mistakenly stripped the `-preview-*` part of the SDK version, hence this issue and some other related issues with wrong tags / titles in announcement and release.

Will have it fixed for Preview 2

**Comment by corngood** [comment]
Something else I just noticed is that the `aspnetcore-runtime` version (`9.0.0-preview.1.24081.5`) doesn't match `dotnet-runtime` (`9.0.0-preview.1.24080.9`) in 9.0 preview 1.

I was previously using `runtimeVersion` for both `dotnet-runtime` and `aspnetcore-runtime` packages.

The distribution docs mention: `<sdk version>`, `<runtime version>`, and `<aspnetcore runtime version>`, so that was probably a bad assumption.  However, I haven't found a way to determine the latter without unpacking the source.  Perhaps it should be in the manifest as well?

**Comment by mthalman** [comment]
> Something else I just noticed is that the `aspnetcore-runtime` version (`9.0.0-preview.1.24081.5`) doesn't match `dotnet-runtime` (`9.0.0-preview.1.24080.9`) in 9.0 preview 1.
> 
> I was previously using `runtimeVersion` for both `dotnet-runtime` and `aspnetcore-runtime` packages.
> 
> The distribution docs mention: `<sdk version>`, `<runtime version>`, and `<aspnetcore runtime version>`, so that was probably a bad assumption. However, I haven't found a way to determine the latter without unpacking the source. Perhaps it should be in the manifest as well?

For preview versions there is no guarantee for those versions will match. If you'd like this information to be available, feel free to log a separate issue for it. Please provide context on how you'll be using that information as well.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37563

**Comment by oleksandr-didyk** [comment]
PR merged, will keep in `Preview 2` as a reminder to double-check this in the March test runs

**Comment by oleksandr-didyk** [comment]
Confirmed fixed in Preview 2
