### ISSUE TITLE
License scan is failing for aspnetcore repo

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4149]
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2382524&view=logs&j=445245b6-131b-5dfe-1bd3-34dea54a62a7&t=4f04196d-5fec-5350-db55-c8d92d2e9f52

Error:
`
2024-02-19T09:22:30.4862212Z VSTESTTASK2 : error Message:  [/mnt/vss/_work/1/s/test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj]
2024-02-19T09:22:30.4940306Z /mnt/vss/_work/1/s/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs(129): error VSTEST1: (Microsoft.DotNet.SourceBuild.SmokeTests.LicenseScanTests.ScanForLicenses) Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ValidateExitCode(ValueTuple`3 result, Int32 expectedExitCode) System.InvalidOperationException : Failed to execute scancode --license --processes 4 --timeout 240 --strip-root --only-findings --ignore *.bin --ignore *.bmp --ignore *.bson --ignore *.db --ignore *.dic --ignore *.eot --ignore *.gif --ignore *.ico --ignore *.jpg --ignore *.il --ignore *.ildump --ignore *.lss --ignore *.nlp --ignore *.otf --ignore *.pdf --ignore *.pfx --ignore *.png --ignore *.snk --ignore *.ttf --ignore *.vsd --ignore *.vsdx --ignore *.winmd --ignore *.woff --ignore *.woff2 --ignore *.xlsx --json-pp /mnt/vss/_work/1/s/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/logs/scancode-results.json /mnt/vss/_work/1/s/src/aspnetcore/ Exit code: 1  Setup plugins... Collect file inventory... Scan files for: licenses with 4 process(es)... Scanning done. Some files failed to scan properly: Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/02/e6/de389e546ea1b5c32fc02ca568b9ad784c180279f962100310e1f2a3bc7ca1205d22d42f7f7405806a4beedf9cb [/mnt/vss/_work/1/s/test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj]
`

**Comment by NikolaMilosavljevic** [comment]
@mthalman have you seen this before? It seems to be an infra failure.

**Comment by mthalman** [comment]
This just indicates that the scanning tool had an error during its execution. Digging into its output file (which in this case is uploaded to the aspnetcore artifacts), its log file shows this:

```json
"errors": [
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/02/e6/de389e546ea1b5c32fc02ca568b9ad784c180279f962100310e1f2a3bc7ca1205d22d42f7f7405806a4beedf9cb308e7030aa6a69c7ed7b74ad82f97c300",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/0f/e0/dfab595e8c13204ea5b7573890b7e76b29f4243ba746d71e6d023733fda554285f9e69271fa75aecf3e973decc72edfccdc3f8bbb9a02b999b7d4ad29527",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/15/48/318173963bec0cb20f30e2093c47c4b2c9ed3226855eeae9978a7752219cfd29ad5635662ecd7de515a575af9ef6fc33ac3fcb11727609fd01d3494d1b13",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/21/59/f625032cec5ae5be1c7dbe5dba18a48a6d4bef952129394b0042f3076f0d8c1e9e097925c5ef28482caec22e78e82f753cc6cf00eb086b8905f014a3718c",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/38/8b/b4a7f6dc4e82240cc5ac3bbe45cf45493b885493da3b7dc7da70d0e64b1bfa145732ff3d0587acb64409a638ba02a4d05ee24165ebe31e19659f3556c034",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/3b/04/de67453e48d3f7f3fcc356f845dc13a0af76aad2e3bb41ea287e95ba3f694f5538ec419aa0962e374efce17e50f5653511331a9c2606cc540bfa0688a660",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/49/9c/f722fad87d3b429e5ac1c69c2f324162d8678616fb416661c4aa1e0b73c8f5f76b7349e19b2688f4ade9dd7d6299932c0a4818142e99169bc2e998314757",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/50/3c/e6924779851ae2f8c03de8e575491968e6307cd90928abc02eb63e76e4a5811a70643f0f10b989d9661de21038e6d0016474de1a341c3af0d4578af8e161",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/5b/6c/58cc6565622fb384702be718761c7e0b1d6abaeb2b7c8bd23d46bb7ba7337073d1e5fd56728329297c91b0e5ac01d9cfd9bfcd94aaf867b38d9e1acf3470",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/70/ff/729814a3b5aae863debc8494b2bf16710e89bd304835070f57d9da2fe48c4e3d27409f9458338ddcb92fcae70e7486c3a9720bc6b6608dad0c64793637fb",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/8c/8e/8be935abbda32ab288988940a55971310025cd22a02150d57c62261b523b7065ec656d61f3d4d93cd73da708bd89414e2482dc64fe76db8b339b281983ea",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/8d/26/dfab8e126f3869f90ddf536db7376b3152ed1dc374912ebde8e72b2b2504cc68741572a2d7ec2d541dc735bf66d2353cde75e80174aa013cfdaddf6123ba",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/9e/18/1826a38ffbbbe83ce288aa472f3c392264d9fbaa7d9407680fe2e8a45186a61fa1d0d6edf2c30d6bea37600059982e45acaf835c68d0a2018bed2af67ed7",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/ac/40/b6d0992fefac8903c2276bf52cc6a7e2bbcd5fae714c79c25c874b09f69d8e40b8280498dd530078d61ec3fccf926f53fd2b0751903ffa6908e2d2869e25",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/b0/14/b322ab4baf98c961c927c1839cad86ccef2a468be0c2ff1fdf5c648b8047323c5a9f940da323899a07cb282ec25a285b674042d52103c0e099bcb5dbf4bc",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/bc/cd/bd1c099c93164e61d9b4d110f4add2f09731f808f0955bcf5692b97fcdef95a22523973496bf84776722b36fa9b12db6aaf94cb78cd79f4f44c1a0eefd6f",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/e9/d4/5ae18b72f9a3cb14cd4010f2fc665690f43aa9e57fe1ec9333ea01baceabae34fd100674ed9394bde242dd86af195573de9a4f0fa72b24c6db562868873b",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/ee/ed/e8de35b1eb2966a889eb7dc163a7884318cff4b7ab20387ab9fa4cd30f45209d93d3650c351a292b5ecb538e43796335cef4514d5f78e5ca0379004212f2",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/fe/14/3bbf3cc55e7cc0b052e8fc826c0c6cc5103421d436700ed2cb41d1381739ffe78577cd895bdf086ec3c0d4a5b60592f77cc4c7c04e68ca7e5ff98afacd37",
  "Path: aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/ff/a2/6642a99c952977de9f6ab9ab06d8d16cb55fc15bad38ae20ec36f810e50894ea740a13d20796574dd46cc8301fb86f168ddf18cf7145ad50d66ddbb8a34a"
],
```

So it looks related to https://github.com/dotnet/aspnetcore/pull/53975 which adds this `Node-Externals` submodule.

Digging into this further, we can search for the actual scan result of each of these files. Example:

```json
{
  "path": "src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/02/e6/de389e546ea1b5c32fc02ca568b9ad784c180279f962100310e1f2a3bc7ca1205d22d42f7f7405806a4beedf9cb308e7030aa6a69c7ed7b74ad82f97c300",
  "type": "file",
  "detected_license_expression": null,
  "detected_license_expression_spdx": null,
  "license_detections": [],
  "license_clues": [],
  "percentage_of_license_text": 0,
  "scan_errors": [
    "ERROR: for scanner: licenses:\nERROR: Processing interrupted: timeout after 240 seconds."
  ]
},
```

And there we go. These must be large files that are causing a timeout for the scan. That's configured here: https://github.com/dotnet/installer/blob/5a97c9f21b59917eb5efcff6a119e6b52ae54ff7/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/LicenseScanTests.cs#L148

**Comment by mthalman** [comment]
Yes, these are used in source build. We may need to exclude them from the scan anyway since these are all just minified JS anyway without license info. The license info should be in the package-lock.json file ([or at least it was](https://github.com/dotnet/aspnetcore/pull/53986#issuecomment-1957863116)) which will be scanned.

**Comment by mthalman** [comment]
It turns out I was wrong. There is license information contained in the cache directory. For example, this file references the `BlueOak` license: https://github.com/dotnet/dotnet/blob/69f964d066db852843661fd41045995088120059/src/aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/38/ec/c58e70968f48113fea5ef71ead16953b4d741bc25656b745be45f8f86c1fb9aa621f7fa16dddeaed2f39b4dade3a0f27dafa4ec71ca1762e05e06cf4171a. So we do need to scan these files.

**Comment by NikolaMilosavljevic** [comment]
> It turns out I was wrong. There is license information contained in the cache directory. For example, this file references the `BlueOak` license: https://github.com/dotnet/dotnet/blob/69f964d066db852843661fd41045995088120059/src/aspnetcore/src/submodules/Node-Externals/cache/_cacache/content-v2/sha512/38/ec/c58e70968f48113fea5ef71ead16953b4d741bc25656b745be45f8f86c1fb9aa621f7fa16dddeaed2f39b4dade3a0f27dafa4ec71ca1762e05e06cf4171a. So we do need to scan these files.

Oh, wow. I can try to increase the timeout to 1 hour per file to see if scanning of any of these 19 files would still time out.

**Comment by wtgodbe** [comment]
> are these files used in source-build? One solutions would be to exclude them if they're not needed.

Those files were recently added explicitly to solve a problem in source build - if this is a blocking issue, there was another potential solution to the problem that would be a little less convenient for our source build partners, but a little more convenient for us. We could consider discussing it with them at Wednesday's partner sync. Related: https://github.com/dotnet/source-build/issues/4161

CC @javiercn @mthalman @MichaelSimons

**Comment by mthalman** [comment]
@javiercn - Per your comment here: https://github.com/dotnet/source-build/issues/4161#issuecomment-1968735954:

> License scanning should happen against the packages described in package-lock.json since the contents of the cache are an exact copy of the packages described in there.

Scanning the package-lock.json file is now useless as a result of a [change that removed the license info](https://github.com/dotnet/aspnetcore/pull/53986#issuecomment-1957863116).

**Comment by ViktorHofer** [comment]
I see that the license scan pipeline is still failing on main because of aspnetcore: Is someone already looking into why? cc @ellahathaway

**Comment by mthalman** [comment]
We know why. It's because of these large files in the cache directory causing timeouts. @wtgodbe and team are working on a different solution that won't require this cache directory anymore.

**Comment by ViktorHofer** [comment]
Ok, thanks. Do we have a tracking issue on their side?

**Comment by MichaelSimons** [comment]
@wtgodbe ^^^.  There is https://github.com/dotnet/aspnetcore/issues/54541.

**Comment by ViktorHofer** [comment]
Ok, so the license scan test is still failing for aspnetcore. Should we disable the job meanwhile or keep it failing?

**Comment by ellahathaway** [comment]
@wtgodbe - do you have a status update on this?

**Comment by mthalman** [comment]
> [dotnet/aspnetcore#56864](https://github.com/dotnet/aspnetcore/pull/56864) suggested that the entire Node-Externals repo can be removed. Would that resolve this issue?

Yes. I see there's an issue for that: https://github.com/dotnet/aspnetcore/issues/56933.

**Comment by wtgodbe** [comment]
Correct, we're removing the submodule in RC1

**Comment by MichaelSimons** [comment]
Is there any reason this can't be included in P7?  Is there substantial risk?  It would be nice to get the license scan passing again, it has been failing since this change went in.

**Comment by wtgodbe** [comment]
I can try to get the PR up in time to ask for tactics approval, but no guarantees

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/56982, if I can get this green & approved I'll open a backport to p7

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/56995 is merged for Preview7, closing as this should fix the issue - if the license scan keeps failing after dependencies flow to SDK, feel free to re-open
