### ISSUE TITLE
Release PR should include Arcade update

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4153]
Now that the VMR is becoming supported for the unified build, it's necessary to update the Arcade version in Version.Details.xml with each release to keep it up-to-date and consistent. The SB release pipeline handles the generation of the release PR (example: https://github.com/dotnet/installer/pull/18655). As part of that PR, it should also be updating the Arcade version (example: https://github.com/dotnet/installer/pull/18504).

/cc @ViktorHofer

**Comment by ViktorHofer** [comment]
Interesting. @mmitche and I have been doing this manually in Arcade. Would be nice if we could integrate this into the automation. This will avoid the manual work when we start shipping Arcade from the VMR.

**Comment by MichaelSimons** [comment]
> Note that upgrading to a newer SDK isn't friction free for repositories. I.e. runtime and some other often need to respond. So this might need some coordination until we start flowing into and from the VMR.

To be clear, source-build has always had to do this.  The product must be buildable with the latest SDK version to be source-buildable.  This is in essence what is done in a stage 2 build of the source-build bootstrap process.

**Comment by oleksandr-didyk** [comment]
The release pipeline should be able to just use the logic that will be introduced with https://github.com/dotnet/source-build/issues/4246

**Comment by ellahathaway** [comment]
Blocked on https://github.com/dotnet/source-build/issues/4357 and more specifically https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39308.

The PR with the changes is https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39424. It is drafted until the Staging pipeline work is completed.

**Comment by ellahathaway** [comment]
Closing this issue since the [PR ](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39424)(internal Microsoft link) was merged.
