### ISSUE TITLE
release.json for 9.0 Preview 1 says `sdkVersion` is `9.0.100`

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#4156]
https://github.com/dotnet/dotnet/releases/download/v9.0.0-preview.1.24080.9/release.json contains:

```
{
  "release": "9.0.0-preview.1",
  "channel": "9.0",
  "tag": "v9.0.0-preview.1.24080.9",
  "sdkVersion": "9.0.100",
  "runtimeVersion": "9.0.0-preview.1.24080.9",
  "sourceRepository": "https://github.com/dotnet/dotnet",
  "sourceVersion": "1337fabdb46697adfbfe4a6f681fc1c2cb5d5b66"
}
```

The runtime version is marked as preview 1, but SDK is marked as 9.0.100, with no indication that this is a preview.

**Comment by mthalman** [comment]
For clarity, I've set the `sdkVersion` to `9.0.100-preview.1.24101.1`.

**Comment by omajid** [comment]
Thanks!
