### ISSUE TITLE
Implement a strategy to select the assets to publish per vertical

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4157]
Verticals produce duplicate assets, i.e. nuget packages like System.CommandLine.nupkg. We need a strategy to select assets per vertical to publish to BAR. A good default might be to publish all nuget packages by default on win-x64 and only publish others that don't exist on win-x64.

I assume that this asset selection strategy needs to run in the join point at the very end after all the verticals.

cc @mmitche

**Comment by mmitche** [comment]
Assigned to @MilenaHristova

**Comment by pavel-purma** [comment]
Asset selection is already done. I will continue on publishing part
