### ISSUE TITLE
Verify tarball step failing in release pipeline

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4171]
The issue was discovered when doing the servicing builds for 6.0 and 7.0 in the release test pipeline.

It appears to be failing at the 'Verify Tarball' step. When investigating, I found that the URLs linked in this step for downloading the resources are returning 404 errors, indicating that the resources at these locations could not be found.

As part of this fix, we should validate how we are verifying the changes we are making to the pipeline.

**Comment by oleksandr-didyk** [comment]
Hmm, even if we point the install script to the correct runtime location, the following tarball creation will just fail on restore. And I'm guessing there could be more issues with missing sources down the line.

We could just try creating the tarball from the private installer, but not sure if that would bring much value + would require some changes to the step.

Will simply hide the task behind a set-by-default flag for now. Should still work as expected in `validation` and `official` runs

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37699

**Comment by oleksandr-didyk** [comment]
PR merged, agreed to have the tarball creation validation turned off for `test` runs and on for the rest
