### ISSUE TITLE
[UX Improvement] Print path of the SDK tarball that was built at the end of the build.

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#4172]
When I do a build, I'm used to seeing something like this at the end:
```
...
    
    Build succeeded.
        0 Warning(s)
        0 Error(s)
    
    Time Elapsed 00:00:03.69
    Determining projects to restore...
    Restored /home/tmds/repos/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj (in 106 ms).
    Writing package usage data...
    Writing package usage data... done. Took 00:00:00.2552241
    Packaged symbols to /home/tmds/repos/dotnet/src/scenario-tests/artifacts/packages/Release/Symbols.scenario-tests.tar.gz
  
  Build succeeded.
      0 Warning(s)
      0 Error(s)
  
  Time Elapsed 00:00:04.73
  [10:19:49.55] Building scenario-tests...done
  New artifact(s) after building scenario-tests:
    -> Microsoft.DotNet.ScenarioTests.SdkTemplateTests.9.0.0-preview.24057.2.nupkg
  Finding project directories...
  Writing package usage data...
  Writing package usage data... done. Took 00:00:03.3874756
  Packaged all symbols in '/home/tmds/repos/dotnet/artifacts/assets/Release/dotnet-symbols-all-9.0.100-preview.3.24126.1-fedora.39-x64.tar.gz'
  Packaged sdk symbols in '/home/tmds/repos/dotnet/artifacts/assets/Release/dotnet-symbols-sdk-9.0.100-preview.3.24126.1-fedora.39-x64.tar.gz'
  Found 0 files in prebuilt packages dir.
```

Then I copy one of the paths for the dotnet-symbols tarballs, and modify it to get the SDK tarball path.

Since it's one of the primary build outputs, it would be nice if we print out the full path of the SDK tarball that got built at the end of the build.

cc @MichaelSimons @ViktorHofer @omajid

**Comment by ViktorHofer** [comment]
IMO there are two ways to approach this:
1. Remove the scenario-tests repo from the default build. Only build it when passing the `--test` switch in. Add that logging to installer.proj as an AfterTargets="Build" target. This will make the message be one of the last few lines.
2. Add the logging to build.proj in the repo root. This has the downside that build.proj doesn't necessarily build the whole SDK. I.e. we now have short-stack builds that only build up to runtime.

FWIW I wouldn't directly link to the sdk archive, but to the `artifacts/assets/<config>/` folder as everything in there is considered a primary build output. The same is true for `artifacts/packages/<config>/Shipping/`. With that, adding the logging to build.proj seems like the right solution.

**Comment by MichaelSimons** [comment]
I like the approach of emitting the output directories as part of build.proj.  This feels more robust.
