### ISSUE TITLE
Reconsider location of SB-specific scripts in VMR

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4174]
Now that the unified build project is underway, the VMR is no longer specific to source build. We should reconsider the location of the `prep.sh` script. This file is specific to source build and is located at the root of the repo. Perhaps it should be moved to the `eng` directory or even `eng/source-build`. There is also another script related to source build in development at https://github.com/dotnet/installer/pull/18726 that this would apply to.

**Comment by tmds** [comment]
> This file is specific to source build and is located at the root of the repo.

My 2 cents: this script is meant to be called by all maintainers that build .NET from source.
At the root of the repo it is more accessible, and it has more visibility.

cc @omajid

**Comment by omajid** [comment]
I don't have strong feelings about this change.

> this script is meant to be called by all maintainers that build .NET from source.

In a distro-build scenario, such as building .NET 8 for Fedora, we don't invoke prep.sh at all. The majority of work that prep.sh does is downloading dependencies, which is something we want to avoid in distro build scenarios.

That said, for development on the VMR itself, prep.sh is very useful indeed.

**Comment by tmds** [comment]
> In a distro-build scenario, such as building .NET 8 for Fedora, we don't invoke prep.sh at all. The majority of work that prep.sh does is downloading dependencies, which is something we want to avoid in distro build scenarios.

It's used for bootstrapping the initial build, right?

**Comment by mthalman** [comment]
Those of us on the source build team use it A LOT. However, the fact is that the VMR's primary scenario is changing away from source build. As evidence to this, it no longer builds in source build configuration by default. There's always been a strong desire to limit the amount of files at the root of a repo. It's basically a given that onboarding new source build developers is something that will require a read through documentation. So trying to enable discoverability for this script isn't really a goal, IMO.

**Comment by tmds** [comment]
Let's consider source-build also a primary scenario, and not make it secondary to Microsoft's build.

**Comment by MichaelSimons** [comment]
We discussed this in the source-build planning meeting today and agreed with @tmds that we should keep the prep script at the root of the VMR.
