### ISSUE TITLE
[9.0.1xx/preview2] R2R test failures: a valid runtime package was not found

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4176]
The Microsoft.DotNet.SourceBuild.SmokeTests.BasicScenarioTests.VerifyScenario tests are failing for R2R scenarios:

```
System.InvalidOperationException : Failed to execute /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/dotnet publish --self-contained true -r linux-x64 /p:PublishTrimmed=true /p:PublishReadyToRun=true /bl:/vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/logs/BasicScenarioTests_Console_CSharp-publish-self-contained-linux-x64-trimmed-R2R.binlog -o /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/projects-202402272116299402/BasicScenarioTests_Console_CSharp/bin/publish
Exit code: 1
Determining projects to restore...
/vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/sdk/9.0.100-preview.2.24127.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. When targeting .NET 6 or higher, make sure to restore packages with the PublishReadyToRun property set to true. [/vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/projects-202402272116299402/BasicScenarioTests_Console_CSharp/BasicScenarioTests_Console_CSharp.csproj]
```

This was introduced by https://github.com/dotnet/installer/pull/18792

[Example pipeline](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581566&view=logs&j=8e1d7f5f-2dd9-5bba-3568-6eebce65bc74&t=a8f9fb18-43e6-5d18-cb2e-d8cac8cb066e)

**Comment by mthalman** [comment]
Interestingly, these test failures are intermittent. I see two different pipeline runs with different results.

[Build 1](https://dev.azure.com/dnceng/internal/_build/results?buildId=2389012&view=results) (internal only):
Fails in `CentOSStream9_Offline_MsftSdk_x64` and `Ubuntu2204_Offline_MsftSdk_x64`

[Build 2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581566&view=logs&j=8e1d7f5f-2dd9-5bba-3568-6eebce65bc74&t=a8f9fb18-43e6-5d18-cb2e-d8cac8cb066e):
Fails in `Ubuntu2204Arm64_Offline_MsftSdk_arm64`

**Comment by MichaelSimons** [comment]
[Triage] The bootstrap was reverted.  If this surfaces with the next bootstrap we should open a new updated issue.
