### ISSUE TITLE
Internal 8.0.1 SDK diff failing to find Arm64 SB Artifacts

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4183]
Despite a successful associated build of the Ubuntu Arm 64 leg in the dotnet-source-build pipeline for internal/8.0.1xx, the SDK diff pipeline run is failing to find the associated artifacts. Usually when this happens, it is due to one of two things:

1. The associated pipeline run failed for the relevant build leg
2. The associated pipeline run has a different name for the build leg than the SDK diff pipeline leg does

Neither of these things appear to be the case for this issue.

[SDK diff pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2394032&view=logs&j=8c37bef5-b8fb-50ee-d40a-a174b95d6bdf&t=e3c589ef-cb65-53ec-421a-d9cabe484450) (internal link)
[Associated dotnet source build pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2393393&view=logs&j=48f70f0d-6e60-5f3f-20b6-a737f6b57504) (internal link)

**Comment by mthalman** [comment]
Ah, this is because the original source build run failed. I retried it and it succeeded. But that was before the SDK diff pipeline ran, so the Arm64 leg was not successful at that time.

**Comment by ellahathaway** [comment]
Thanks for explaining! Closing this per Matt’s explanation.
