### ISSUE TITLE
Prebuilt in CentOSStream8 Stage 2 Leg

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4191]
The stage 2 Centos build leg is showing a new prebuilt.

[Link to build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2396581&view=logs&j=e690eb20-f225-5013-36f6-f0b956524e66&t=8cfc410d-90c7-5e96-39ba-afa52aad7b7b&l=2915) (internal)

Prebuilt usage report:

```xml
  <Usages>
    <Usage Id="Microsoft.ApplicationInsights" Version="2.21.0" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.SignTool/project.assets.json" IsDirectDependency="true" />
  </Usages>
```

**Comment by ellahathaway** [comment]
Arcade is using v2.22.0 of this package: https://github.com/dotnet/arcade/blob/2215d18d04a6565e9133c15ece7df7161fdf1e8e/Directory.Packages.props#L79.

**Comment by ellahathaway** [comment]
It looks like the changes from SBE into Arcade had not yet flowed into the VMR when the offending build kicked off. https://github.com/dotnet/arcade/commit/ae62c8d33c26fead308f9ad0f3bbc2018ecd1c14 updated the dependency in Arcade, so once this change flows into the VMR, the error described in this issue and in https://github.com/dotnet/source-build/issues/4192 should resolve. I will close this once I've confirmed that the flow into the VMR fixed the issue.

**Comment by MichaelSimons** [comment]
I don't think that Arcade update to update it's app insights version can flow into the VMR before a bootstrap happens.  Arcade referencing 2.22 will fail because it is not in the n-1 artifacts.

**Comment by ellahathaway** [comment]
> 3. Build and release (which updates n-1 artifacts)

Does this mean we rebootstrap with the Stage 1 artifacts from [the build that has the prebuilt issue](https://dev.azure.com/dnceng/internal/_build/results?buildId=2396581&view=results) (internal link)?

**Comment by MichaelSimons** [comment]
> > 3. Build and release (which updates n-1 artifacts)
> 
> Does this mean we rebootstrap with the Stage 1 artifacts from [the build that has the prebuilt issue](https://dev.azure.com/dnceng/internal/_build/results?buildId=2396581&view=results) (internal link)?

I think so.

**Comment by mthalman** [comment]
Why do we need to rebootstrap at all? Why don't we add back the old app-insights version to SBE? That should prevent any prebuilts and allows us to continue from [step 3](https://github.com/dotnet/source-build/issues/4191#issuecomment-1984552053).

**Comment by MichaelSimons** [comment]
> Why do we need to rebootstrap at all? Why don't we add back the old app-insights version to SBE (and continue to have the old and new version temporarily)? That should prevent any prebuilts and allows us to continue from [step 3](https://github.com/dotnet/source-build/issues/4191#issuecomment-1984552053).

Yes, agreed.
