### ISSUE TITLE
Migrate off of CentOS Stream 8 in CI, EOL is May 31st, 2024

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4193]
CentOS Stream 8 is used in the source-build/VMR CI.  It is also the distro used by default in the arcade source-build repo templates.  CentOS Stream 8 EOL is May 31st, 2024.

For .NET 8+, Stream 8 should be replaced with Stream 9.
For .ENT 6, we ideally would test on a distro in the RHEL 8 family.

**Comment by omajid** [comment]
I was doing some quick testing, and if there is some way to disable runtime's build-time dependency on lttng-ust-devel, it should be possible to use UBI8 as an alternative to Stream 8

**Comment by MichaelSimons** [comment]
This was resolved by the work done in https://github.com/dotnet/source-build/issues/4399.
