### ISSUE TITLE
Runtime build fails in Mono when hitting a warning despite warnAsError=false

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/source-build#4197]
This build had a warning in the Mono runtime build which caused the build to fail even though we're passing `--warnAsError false`:

https://dnceng.visualstudio.com/internal/_build/results?buildId=2398981&view=logs&j=772df19d-2788-50a3-ff88-b0cb2cc9f1cf&t=f0be4429-cdc6-535c-1b57-baea1ab27b5a

CoreCLR passes`IgnoreStandardErrorWarningFormat="true"` in runtime.proj to disable translating warning/errors but I'm not sure this should even happen since we're explicitly disabling warnAsError.

/cc @directhex @ViktorHofer

**Comment by ViktorHofer** [comment]
You mean this one, right? Is this really a warning? Asking as the log says it's an error:

![image](https://github.com/dotnet/source-build/assets/7412651/41a830cb-ee43-41c4-9f64-fb1c64a56368)

**Comment by akoeplinger** [comment]
Ahh interesting, it looks like we're setting -Werror explicitly for CI builds here:
https://github.com/dotnet/runtime/blob/9c828a17c347118968d7a1a170178daf4a9ce126/src/mono/mono.proj#L99-L102

So I think I know what happened: the assumption was that this would break the dotnet/runtime build but we're using the arm64 Mac pool in the VMR build and that uses a new Xcode with a newer compiler so the warning didn't show up in the dotnet/runtime build but it did in the VMR build.

I think we should disable that logic when building in the VMR.
