### ISSUE TITLE
Create and Publish VerticalManifests during unified builds

### ISSUE THREAD

**Issue by dkurepa** [dotnet/source-build#4198]
During unified builds, we run many legs on different OSes. Each of these legs builds multiple repos, and every repo build produces an `Asset Manifest`, that's later used in the publishing. Based on https://github.com/dotnet/source-build/issues/4158, we want to use these `Asset Manifests` to create a `Vertical Manifest` that will contain information about all assets built in a unified build leg.
We will exclude all of the information about signing, we don't need it

**Comment by dkurepa** [comment]
I discussed the implementation details with @ViktorHofer. We'll be adding `Publishing.props` to the dotnet/dotnet repo that will call a task that will create the `VerticalManifest`, and initialize a list of files that we want to publish to the remote storage for a given leg

**Comment by ViktorHofer** [comment]
What I still want to double check with @mmitche is if the task should live in Arcade of the VMR orchestrator. When we invoke the publish action on the VMR we will call into the VMR and will need to make it not again produce a repo manifest. Alternatively if we implement this in Arcade we could add a new mode to the manifest generation that just accepts the other manifest files as an input. I'm not sure which approach is better.

**Comment by mmitche** [comment]
> When we invoke the publish action on the VMR we will call into the VMR and will need to make it not again produce a repo manifest

What do you mean by it producing a repo manifest again?

**Comment by ViktorHofer** [comment]
@dkurepa, @mmitche and I discussed this offline. Just to add to what @dkurepa mentioned above:

> We'll be adding Publishing.props to the dotnet/dotnet repo that will call a task that will create the VerticalManifest, and initialize a list of files that we want to publish to the remote storage for a given leg

@dkurepa given that we won't use Arcade's publishing infrastructure and our current build entry points, it would be easier if we just invoke the merge manifests build task in a target in build.proj that runs AfterTargets="Build" in the VMR orchestrator and write that new file directly into the artifacts folder.

**Comment by dkurepa** [comment]
The PR for this change is in https://github.com/dotnet/installer/pull/19062. We'll have to wait for https://github.com/dotnet/installer/pull/18917 to get merged before merging this tho

**Comment by dkurepa** [comment]
The pr was merged. Every VMR build leg is now producing it's own artifact that has the packages, and vertical manifests. There's a small bug with the VmrBuildNumber attribute, we opened up https://github.com/dotnet/source-build/issues/4263 for it
