### ISSUE TITLE
[VMR] Add BuildPass parameter to vmr-build.yml

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4217]
Contributes to https://github.com/dotnet/source-build/issues/3739
Depends on https://github.com/dotnet/source-build/issues/4215

1. Add the `BuildPass` parameter to vmr-build.yml job template
2. If set, pass the `DotNetBuildPass` msbuild property in with the value.
3. Add the build pass number to the AzDO pipeline artifact's name if set, i.e. `windows_x64_artifacts_buildpass2`.

**Comment by directhex** [comment]
I'm trying to figure out how bullet 3 is possible without adding a parameter to define it.

The job name https://github.com/dotnet/sdk/blob/main/eng/pipelines/templates/jobs/vmr-build.yml#L105 is composed of compile-time (`${{}}`) properties from parameters. We can't use runtime (`$()`) properties in its construction, and it's not valid to put conditionals in the `parameters:` block. So we'd need a parameter (e.g. `jobNameSuffix`), default empty, calculated and passed by the parent stage template.

**Comment by directhex** [comment]
Wait, you're only asking for it on the pipeline artifact's name, not the whole job's name. That's much easier.
