### ISSUE TITLE
[VMR] Add support for join point vertical job in vmr-build.yml

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4218]
Contributes to https://github.com/dotnet/source-build/issues/3739
Depends on https://github.com/dotnet/source-build/issues/4215

A join point vertical job isn't much different to a normal vertical vmr-build job aside from:

**Two new parameters**
1. reuseBuildArtifactsFrom: This parameter lists the jobs that the join point job depends on. This parameter should support multiple values and the order is important. Artifacts from the job name listed first are preferred in case of duplicates with other jobs listed here.
2. buildPhase: This parameter identifies the build phase of the join point job. This should be a value > 1.

The existing job steps need to be updated to also work in a non-source-only build mode: https://github.com/dotnet/installer/blob/986cd8e87e84681dfa2dc11efa85ce2a2b15176e/eng/pipelines/templates/jobs/vmr-build.yml#L168-L210

The artifacts from the previously built verticals should be copied into the VMR's root artifacts folder. If a file already exists then it should not overwritten. This enables the priority system so that i.e. `win-x64` artifacts are preferred over `win-x86`.

**Comment by directhex** [comment]
I'm assuming use of "Phase" here is a typo, the other issues (including the design doc) seem to have settled on "Pass"

**Comment by directhex** [comment]
`reuseBuildArtifactsFrom` is already a (single string) parameter, I assume the intent here is to replace that with an array so things scale, and fix up all existing usages to work with the modified syntax
