### ISSUE TITLE
Add Microsoft/DockerTools as a submodule

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#422]
With cli incorporating Microsoft.Docker.Sdk as a bundled sdk https://github.com/dotnet/cli/pull/8416/files source-build needs to add https://github.com/Microsoft/DockerTools as a source buildable submodule. This is to prevent https://github.com/dotnet/cli/issues/6178 from happening in the source-build distribution, ie non-VS `dotnet restore` and `dotnet build` should NOP when a .dcproj is present in the solution.

**Comment by dleeapho** [comment]
We might consider keeping this as a prebuilt since the content is textual and not going to change often.

**Comment by dleeapho** [comment]
Moving out of RC, instead we'll do #432 as prebuilt.

**Comment by dseefeld** [comment]
This is complete.  This is fine as a prebuilt, since it is text only.
