### ISSUE TITLE
Incorrect Artifacts Versions in VMR Release PRs

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4221]
The final release PRs for the VMR had incorrect artifacts versions:

Final release PR had incorrect artifacts: https://github.com/dotnet/installer/pull/19010/commits/4f3cce82a010b3ad90dfe8b4b3896c6aff121d4d#diff-03917dc2c8b218f596449dea0b068769ce2aa2493bf945873e6673eddbc6e6d9L25

For example, in 9.0 the PR showed:
```
<PrivateSourceBuiltSdkVersion>/dotnet-sdk-*.tar.gz</PrivateSourceBuiltSdkVersion>
<PrivateSourceBuiltArtifactsVersion>/Private.SourceBuilt.Artifacts.*.tar.gz</PrivateSourceBuiltArtifactsVersion>
```

It should have been:
```
<PrivateSourceBuiltSdkVersion>9.0.100-preview.2.24157.14</PrivateSourceBuiltSdkVersion>
<PrivateSourceBuiltArtifactsVersion>9.0.100-preview.2.24157.14</PrivateSourceBuiltArtifactsVersion>
```

A similar issue was observed in the [8.0 release PR](https://github.com/dotnet/installer/pull/19007)

cc @oleksandr-didyk

**Comment by oleksandr-didyk** [comment]
There seems to have been a bad substitution due to the wrong parameter order for one of the scripts. Will fix

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/38097

**Comment by oleksandr-didyk** [comment]
PR merged, should be fixed for Preview 3
