### ISSUE TITLE
Release pipeline failed to upload Alpine artifacts

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4222]
The release pipeline only uploaded the centos.8 artifact tarball, but it failed to upload the Alpine one. The Alpine tarball is required for the dotnet-source-build Alpine319_Offline_PreviousSourceBuiltSdk_x64 leg.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/38462

**Comment by oleksandr-didyk** [comment]
PR merged, should be fixed for `Preview 3`
