### ISSUE TITLE
.NET 9 Preview 2 has wrong sdk version number in release.json

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#4231]
### Describe the Bug

The release.json file contains SDK version of `9.0.100-preview.2.24157.14`:

```json
{
  "release": "9.0.0-preview.2",
  "channel": "9.0",
  "tag": "v9.0.0-preview.2.24128.5",
  "sdkVersion": "9.0.100-preview.2.24157.14",
  "runtimeVersion": "9.0.0-preview.2.24128.5",
  "sourceRepository": "https://github.com/dotnet/dotnet",
  "sourceVersion": "14eb446d301de0fa50afd32daf0dcbf1b3716ae5"
}
```

But building the SDK produces `dotnet-sdk-9.0.100-preview.2.24158.1-fedora.39-x64.tar.gz`, that is, SDK version 9.0.100-preview.2.24158.1. The contents of the tarball agree: 

```
$ tar tf ./dotnet-9.0.0-preview.2.24128.5/artifacts/assets/Release/dotnet-sdk-9.0.100-preview.2.24158.1-fedora.39-x64.tar.gz | grep 'sdk/9.0.100' | head -1
./sdk/9.0.100-preview.2.24158.1/
```

Is it expected that there might be a difference between the `sdkVersion` in release.json file and the built SDK?

**Comment by MichaelSimons** [comment]
> Is it expected that there might be a difference between the sdkVersion in release.json file and the built SDK?

They should be the same.  I would venture this is a difference caused by the MSFT version and source-build diverging.

**Comment by mthalman** [comment]
Yes, this is https://github.com/dotnet/source-build/issues/3521.

**Comment by omajid** [comment]
Thanks. Closing as Duplicate.

**Comment by corngood** [comment]
I just hit this as well.  I'm worried that #3521 doesn't have any sort of short term solution.  I'm left with hacking the release json for now.
