### ISSUE TITLE
[8.0] Onboard dotnet-source-build pipeline to 1ES templates 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4232]
The [dotnet-source-build pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=1219) (Microsoft internal link)  needs to be converted to use the 1ES templates.

This applies to 8.0

**Comment by premun** [comment]
@mthalman will you be handling this? I remember on Wednesday that MattM offered to do it and I said I can do it instead.

**Comment by MichaelSimons** [comment]
> @mthalman will you be handling this? I remember on Wednesday that MattM offered to do it and I said I can do it instead.
> 
> I logged this on Wed: #4223

@premun - This issue is about updating the 8.0 pipeline.  With the UB work, the pipeline was majorly refactored so the changes you are working on won't backport to 8.0.  There may be some overlap though.

**Comment by mthalman** [comment]
@premun - This is specifically for the 8.0 branch which differs significantly in implementation from main which adds support for UB. So you can handle the main branch. I'll do 8.0 branch.

**Comment by premun** [comment]
Ah, okay. Let's split this way then.

I did this btw: https://github.com/dotnet/installer/pull/19064 
Seems like a good first step?
