### ISSUE TITLE
dotnet-unified-build official builds are failing probably due to the publishing infra change

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4236]
> /Users/runner/work/1/s/src/installer/src/redist/targets/GenerateLayout.targets(406,5): error : Download from all targets failed. List of attempted targets: file:///Users/runner/work/1/s/artifacts/assets/Release/Runtime/9.0.0-preview.3.24162.24/dotnet-runtime-internal-9.0.0-preview.3.24162.24-osx-x64.pkg [/Users/runner/work/1/s/src/installer/src/redist/redist.csproj]
##[error]src/installer/src/redist/targets/GenerateLayout.targets(406,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Download from all targets failed. List of attempted targets: file:///Users/runner/work/1/s/artifacts/assets/Release/Runtime/9.0.0-preview.3.24162.24/dotnet-runtime-internal-9.0.0-preview.3.24162.24-osx-x64.pkg
    /Users/runner/work/1/s/src/installer/src/redist/targets/GenerateLayout.targets(406,5): error : Failed to download file using addresses in Uri and/or Uris. [/Users/runner/work/1/s/src/installer/src/redist/redist.csproj]
##[error]src/installer/src/redist/targets/GenerateLayout.targets(406,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Failed to download file using addresses in Uri and/or Uris.

from https://dev.azure.com/dnceng/internal/_build/results?buildId=2405605&view=logs&j=5551d7c4-237a-5520-de91-e8efe1228738&t=9c43b4cf-3041-5751-e0a5-f72a63a3cbf3

Started failing last Friday. @NikolaMilosavljevic can you please take a look? This is blocking our official builds right now.

**Comment by NikolaMilosavljevic** [comment]
OK - we need to add `*.pkg` files for publishing - I'll update the patch: https://github.com/dotnet/installer/blob/main/src/SourceBuild/patches/runtime/0001-Enable-publishing-in-VMR.patch

I'll also create a PR for runtime repo, where the change is a little different (better).

**Comment by ViktorHofer** [comment]
This should now be fixed with the latest dependency flow.
