### ISSUE TITLE
Internal/release/8.0.1xx build failing in Ubuntu Arm64 leg

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4238]
Log: https://dev.azure.com/dnceng/internal/_build/results?buildId=2405682&view=logs&j=48f70f0d-6e60-5f3f-20b6-a737f6b57504&t=63323c42-21c8-51ec-b413-1a088972dd93

```
    CSC : error AD0001: Analyzer 'Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/System.Security.Cryptography.Pkcs.7.0.2.csproj::TargetFramework=net7.0]
##[error]CSC(0,0): error AD0001: (NETCORE_ENGINEERING_TELEMETRY=Build) Analyzer 'Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

`CSC : error AD0001: Analyzer 'Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/System.Security.Cryptography.Pkcs.7.0.2.csproj::TargetFramework=net7.0]`

**Comment by NikolaMilosavljevic** [comment]
Failure in `source-build-sdk-diff-tests` is related to this - the build is missing - https://dev.azure.com/dnceng/internal/_build/results?buildId=2406853&view=logs&j=8c37bef5-b8fb-50ee-d40a-a174b95d6bdf&t=26927235-b994-5e6d-5050-58d34708b9f7

**Comment by NikolaMilosavljevic** [comment]
@dotnet/roslyn-analysis

**Comment by mthalman** [comment]
@NikolaMilosavljevic - It looks like there's been many successful builds since this failing one. Was there a known fix made or is this just "no repro" now?
