### ISSUE TITLE
Create automation for re-bootstrapping

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4246]
The VMR often needs to be re-bootstrapped during the preview timeframe.  We have automation that creates a re-bootstrap PR as part of the release pipeline.  It would be ideal if this logic could be refactored in such a way that it can be shared with a new pipeline that we can use to create a re-bootstrap PR at any time.  This new pipeline would need to take in a reference to a source-build to pull artifacts from and an installer build to pull the SDK from.

**Comment by ViktorHofer** [comment]
+1. Adding to that: Update the automation to also change the Version.Details.xml file and the global.json msbuild sdk entry for the Arcade dependency.

**Comment by ViktorHofer** [comment]
One more though, are the steps necessary to bootstrap documented? Especially the part that deals with uploading the artifacts to blob storage. Asking as it would be nice if the product-construction team could also trigger a re-bootstrap so that we don't have to ping your team every time we need a newer Arcade change in arcade or SBRP.

**Comment by mthalman** [comment]
> +1. Adding to that: Update the automation to also change the Version.Details.xml file and the global.json msbuild sdk entry for the Arcade dependency.

See https://github.com/dotnet/source-build/issues/4153

**Comment by ellahathaway** [comment]
Draft PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39424 (internal microsoft link)

Working out some final tweaks, but the main functionality is all there and is 95% debugged.

**Comment by ellahathaway** [comment]
Closing since the [PR ](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39424)(internal Microsoft link) was merged
