### ISSUE TITLE
WPF binary in VMR main

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#4250]
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2413372&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=2a0bd486-3f67-5c59-da0c-b84d88848a4b

A new binary from WPF has been introduced to the VMR's `main`:
```
src/wpf/src/Microsoft.DotNet.Wpf/src/Shared/Tracing/resources/MSG00001.bin
```

**Comment by MichaelSimons** [comment]
@ellahathaway - Can you please investigate?

**Comment by oleksandr-didyk** [comment]
Build with passing binary scan: https://dev.azure.com/dnceng/internal/_build/results?buildId=2414648&view=results
