### ISSUE TITLE
License scan failing on Arcade and runtime docs

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#4251]
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2413356&view=results

The license scan tooling seems to have picked-up two documentation files in `Arcade` and `runtime` due to licensing mentions

`Arcade`:
```json
    {
      "path": "Documentation/UnifiedBuild/VMR-Permissible-Sources.md",
      "detected_license_expression": "free-unknown"
    }
```

`runtime`:
```json
    {
      "path": "docs/design/mono/web/llvm-backend.md",
      "detected_license_expression": "llvm-exception"
    }
```

**Comment by oleksandr-didyk** [comment]
@mthalman should these just be added to their respective license baselines or is there some other flow for these types of issues? Thanks!

**Comment by MichaelSimons** [comment]
@ellahathaway - Can you please investigate?
