### ISSUE TITLE
Tag release build with SDK version for pre-VMR releases

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#4257]
Brought up by https://github.com/dotnet/release/issues/864#issuecomment-2018589513

Currently the release builds are tagged with the `Release` version, which normally corresponds to the `runtime` version being released.

This can be confusing for pre-VMR releases that mostly use the SDK version for tagging / artifact naming purposes.

**Comment by mthalman** [comment]
Yeah, this isn't relevant anymore since it was specifically for pre-VMR releases.
