### ISSUE TITLE
Remove patches from cli

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#426]
Remove patches added by https://github.com/dotnet/source-build/pull/418.

**Comment by dseefeld** [comment]
CLI Issue: https://github.com/dotnet/cli/issues/9176

**Comment by dagood** [comment]
I think it makes sense for me to take this since I have outstanding issue #496 to remove the 003 patch specifically, and I can just remove them all at once.

**Comment by dagood** [comment]
Done with https://github.com/dotnet/source-build/pull/524.
