### ISSUE TITLE
Considering moving ymls that only run against the VMR

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4261]
We should consider moving ymls that only run against the VMR into `src/SourceBuild/content/eng/pipelines`.

Currently, there are a few ymls in `installer/eng/common/pipelines` that we should consider moving, including `vmr-license-scan.yml` and [`source-build-sdk-diff-tests.yml`](https://github.com/dotnet/dotnet/blob/main/src/installer/eng/pipelines/source-build-sdk-diff-tests.yml)

This was originally brought up in https://github.com/dotnet/installer/pull/19201#discussion_r1539852807

**Comment by oleksandr-didyk** [comment]
Changes mirrored, switched the source in the pipelines, waiting for the builds to finish to verify the move

**Comment by oleksandr-didyk** [comment]
Both builds passed without visible regressions, closing
