### ISSUE TITLE
VMR build broken: Unexpected value 'publish alias is not allowed

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/source-build#4264]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2415156&view=results

This was added by https://github.com/dotnet/installer/pull/19062, eng/pipelines/templates/jobs/vmr-build.yml contains `publish` which is not allowed by the 1ES PT templates.

**Comment by dkurepa** [comment]
Here's the PR that should fix this https://github.com/dotnet/installer/pull/19212

**Comment by akoeplinger** [comment]
That fixed it, thanks!
