### ISSUE TITLE
New binary introduced into VMR from razor

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4265]
The `Scan for binaries` build step for VMR pipelines is getting a warning from a newly introduced binary file:

```
12:34:02 dbug: BinaryTool[0] New binaries:
12:34:02 dbug: BinaryTool[0]     src/razor/src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Resources/project.razor.bin
```

File link: https://github.com/dotnet/razor/blob/main/src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Resources/project.razor.bin

**Comment by ellahathaway** [comment]
This was introduced into the VMR with https://github.com/dotnet/razor/pull/10163. The PR describes the binary being added as part of the introduction of a new test case, so we should be able to add the binary to `allowed-vmr-binaries.txt`.
