### ISSUE TITLE
Pipeline artifacts are missing from public VMR CI builds

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4271]
![image](https://github.com/dotnet/source-build/assets/7412651/9b33e154-86d9-4a9b-a15f-7191a74abfd5)

Example build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=621432&view=results

Pipeline artifacts (packages, assets, log and binlogs) are missing from public CI builds. Those artifacts are crucial for debugging issues in PRs, especially related to msbuild.

@premun

**Comment by premun** [comment]
Artifacts are back: https://dev.azure.com/dnceng-public/public/_build/results?buildId=622216&view=artifacts&pathAsName=false&type=publishedArtifacts
