### ISSUE TITLE
Alpine leg failing in VMR CI over missing ReadNuGetPackageInfos task

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#4273]
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2416861&view=logs&j=b9abe003-a5da-5729-0444-865506f15e35&t=87f9da6e-f2d4-54fa-c5d2-00fb4a6fed67

`Alpine` leg `Build` stage failing on:
```
Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/MarkAndCatalogPackages.cs(82,43): error CS0103: The name 'ReadNuGetPackageInfos' does not exist in the current context
```

**Comment by oleksandr-didyk** [comment]
@ViktorHofer could this be related to your changes from yesterday? Specifically https://github.com/dotnet/installer/pull/19210

**Comment by MichaelSimons** [comment]
The namespace of the XPlat tasks changed.  MarkAndCatalogPackages is assuming it's namespace is the same.  All that needs to change is a using needs to be added so that it can resolve the ReadNuGetPackageInfos.  @oleksandr-didyk, would you mind fixing?  TIA.
