### ISSUE TITLE
VMR build script errors for `--test`

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4278]
When running `./build.sh --test`, the following error appears:

```bash
root@cb7aa5f1f384:~/repos/dotnet# ./build.sh --test

/root/repos/dotnet/build.proj : error MSB4057: The target "RunSmokeTest" does not exist in the project.

Build FAILED.

/root/repos/dotnet/build.proj : error MSB4057: The target "RunSmokeTest" does not exist in the project.
    0 Warning(s)
    1 Error(s)

```

Looking at the build script for the test option:
```bash
    -test|-t)
      export NUGET_PACKAGES=$NUGET_PACKAGES/smoke-tests
      properties="$properties /t:RunSmokeTest"
      test=true
      ;;
```

The `RunSmokeTest` target exists in `build.sourcebuild.targets`.

It looks like https://github.com/dotnet/installer/pull/18358 brought in the changes that are causing this error.

**Comment by mthalman** [comment]
Yeah, the `--test` optional is essentially non-functional without also specifying source build `--sb`. This will be fixed by https://github.com/dotnet/installer/pull/19222.
