### ISSUE TITLE
Enable (some?) cli bundled tools

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#428]
Bundled tool skip added in https://github.com/dotnet/source-build/pull/418. I'm not sure how many bundled tools are skipped due to this:

https://github.com/dotnet/source-build/blob/a184e0b053beeaa64ed5321f06f7eded3ad1c8ee/repos/cli.proj#L73-L82

The intention is to skip any that aren't built from source, but I don't know if there are some being skipped that don't need to be.

/cc @dleeapho @dseefeld @peterhuene

**Comment by peterhuene** [comment]
I think the plan was to skip these for source-build anyway since they aren't yet source-buildable.  Users of source-built will need to manually install them as global tools and we were going to "include-list" these commands to warn users they need to install them.

**Comment by dagood** [comment]
That sounds right to me. My concern is that there might be some bundled tools that are already source-buildable which are skipped because of the flag. I just noticed that these 5 are the only tools mentioned in `BundledDotnetTools.props` though, so it's probably fine.

**Comment by omajid** [comment]
I think we can close this. This is fixed in 3.1, right?

**Comment by dagood** [comment]
@dseefeld @crummel @adaggarwal, can you confirm this was fixed in 3.1 (tools are included) and close?

**Comment by MichaelSimons** [comment]
Closing as all bundled tools that the MSFT build does - dev-certs, format, user-jwts, user-secrets, and watch.
