### ISSUE TITLE
8.0 SDK diff pipeline cannot find associated installer build

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4283]
The [sdk-diff-tests pipeline is failing to find the associated builds for 8.0](https://dev.azure.com/dnceng/internal/_build/results?buildId=2419167&view=results) (internal Microsoft link):

```
Could not find a build of installer for commit '1ES.PT.Official
ES365AIMigrationTooling
8dfcac5e401437cfe5ab5ae3a3a64e011c4f9c57'
```

Looking at the latest run of installer for 8.0, the run is not tagged with any one of the three tags expected by the sdk diff pipeline.

This failure was introduced by https://github.com/dotnet/installer/pull/19073.

**Comment by mthalman** [comment]
@oleksandr-didyk has a fix for this

**Comment by oleksandr-didyk** [comment]
The fix is in `main`, completed by https://github.com/dotnet/source-build/issues/4275

I have the branch locally so I'll just open a PR for `8.0` as well

**Comment by oleksandr-didyk** [comment]
PR with the fix from `main` was merged, should be resolved once the change gets mirrored

**Comment by ellahathaway** [comment]
Awesome, thanks Alex!
