### ISSUE TITLE
Manifests are being duplicated in CI pipeline artifacts

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4285]
The `_manifest` folder content is being duplicated in the CI pipeline artifacts in both the *_Artifacts and *_BuildLogs

![image](https://github.com/dotnet/source-build/assets/8290530/658d1315-6e76-400a-b696-052c48842672)

**Comment by MichaelSimons** [comment]
@dkurepa - Is this an outcome of the vertical manifest work?

**Comment by ViktorHofer** [comment]
No, that's 1ES PT.

**Comment by dkurepa** [comment]
yeah, I think these are auto generated manifests that get created during artifact publishing

**Comment by MichaelSimons** [comment]
Thanks for the explanation.
