### ISSUE TITLE
Reduce Developer Overhead of SBE Dependencies in Pre-SBE repos

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4286]
If a repo is built before source-build externals (a pre-SBE repo), that repo runs the risk of introducing a prebuilt if source-build externals updates the component and removes the old version.

In order to prevent a prebuilt, it was originally thought that two versions of the component would have to exist in source-build externals: the old version use by the pre-SBE repo, and the new version. Once the VMR has been updated with the new SBE version, the VMR must be rebootstrapped so that the pre-SBE repo consumes the most recent version of the component instead of the old version. While this is a valid solution, it introduces a lot of developer overhead; the developer must maintain two versions of the component in SBE, monitor the flow of SBE into the VMR, rebootstrap the VMR, update the pre-SBE repo to consume the new version of the dependency, and remove the old version of the component from SBE.

A better way of doing this would be to have the pre-SBE repo define a version property for the dependency coming from SBE. The pre-SBE repo should also add an entry for the dependency in its Version.Details.xml file. This means that the version property will be overridden by the version defined in the n-1 repo. This approach allows the developer to only have to maintain a single version of the component in SBE and not have to manually rebootstrap the VMR.

To fix resolve this issue, two things must occur:
1) Update the documentation in source-build externals to describe this process
2) Update any pre-SBE repos using dependencies from SBE (focusing on AppInsights and Newtonsoft):
   1) Define version properties for dependencies originating from SBE
   2) Add entries for the dependencies in the repo's Version.Details.xml file

**Comment by ellahathaway** [comment]
Working to confirm if the version prop can be pulled from previous version props.

If it can be pulled from previous version props, I'm wondering if I would have to wait for my changes from https://github.com/dotnet/arcade/pull/14678 to be included in a rebootstrap in order to see the `MicrosoftApplicationInsightsVersion` prop show up in PVP?

On investigating the PVP for arcade, I didn't see `MicrosoftApplicationInsightsVersion` in the file.

**Comment by MichaelSimons** [comment]
The extra version property would required msbuild logic to retrieve the version from n-1. I discussed this with @mmitche, and we both felt this was not desirable and that the preferred solution is to use the existing Version.Details.xml construct.  Yes it is a bit odd because the dependency is external but it is the better solution.  We should comment this dependency well.  If this becomes a common pattern it may warrant a new type of  Version.Details.xml dependency - e.g. ExternalDependencies.
