### ISSUE TITLE
SDK comparison tests are failing on macOS

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4291]
See https://dnceng.visualstudio.com/internal/_build/results?buildId=2422159&view=results

@jtschuster

**Comment by jtschuster** [comment]
Is it possible to run this pipeline on an installer PR to test the fix?

**Comment by MichaelSimons** [comment]
> Is it possible to run this pipeline on an installer PR to test the fix?

You'd have to sync the changes to a VMR branch and trigger the pipeline on that branch.  If the changes aren't trivial you can use the [sync script](https://github.com/dotnet/installer/blob/main/eng/vmr-sync.sh).

**Comment by ViktorHofer** [comment]
Reopening as osx-arm64 is still failing.
