### ISSUE TITLE
Alpine Legs failing to build CoreCLR

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4298]
The Alpine legs are failing due to issues building runtime's CoreCLR component. There are many errors for this component, but most of them are related to null values and null pointers. Below are two examples of errors that appeared in the build:

- `error: value of type 'std::nullptr_t' is not implicitly convertible to 'UINT_PTR' (aka 'unsigned long')`
- `error: cannot initialize a member subobject of type 'COUNT_T' (aka 'unsigned int') with an rvalue of type 'std::nullptr_t'`

I believe that https://github.com/dotnet/runtime/pull/98336 may have introduced these errors.

[Link to failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2423233&view=logs&j=7830363c-9761-5497-b6c6-e8d55da0c426&t=8113443e-6df1-5d6a-2d5b-ae8e3898266f) (internal Microsoft link)

**Comment by ellahathaway** [comment]
cc @khushal1996 - pinging since I believe you originally opened the PR linked into the issue. Let me know if I should ping someone else.

**Comment by BruceForstall** [comment]
@ellahathaway How did you determine that https://github.com/dotnet/runtime/pull/97529 might be at fault?

This seems very likely related to https://github.com/dotnet/runtime/pull/98336 -- @jkoritzinsky

**Comment by ellahathaway** [comment]
Ah you're right. The commit hash pulled from the VMR build doesn't even include https://github.com/dotnet/runtime/pull/97529 in the log history yet (hadn't been synced to the VMR as of that build).

I had looked through the git history of the files and saw that https://github.com/dotnet/runtime/pull/98336 was merged two days ago, so I assumed that this would've gone into the VMR yesterday given that runtime syncs to sdk every day which syncs to installer every day. I've updated the issue comment to reflect the correct PR.

**Comment by jkoritzinsky** [comment]
Ill take a look. I'm amazed this is only causing failures in the VMR. Don't know why that would be.

**Comment by jkoritzinsky** [comment]
Looks like it's failing due to Clang 17 introducing more strict checking for nullptr->integer conversions in compile-time-constant scenarios. I was hoping to avoid having to handle this now (and instead rewriting the infrastructure that hits this) but it should be fixable without too much trouble.
