### ISSUE TITLE
Discover dependent project package versions through asset manifests instead of package inspection

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/source-build#4302]
Today, we discover which package versions to insert into project's Versions.props files by inspecting all nupkg files in the project's artifacts folder (filtering to the newest version of each asset).

When we move to allowing dev builds, developers can end up in a state where they've done a development build and now all future builds (official or otherwise) only pick up dev builds as they're versioned 42.42.42.42. Additionally, switching between dev branches could end up in a bad state selecting the wrong version of packages.

We already have a known-accurate manifest of all produced assets, the asset manifest. We can extract package versions from the manifest and use that information to update the Versions.props files. Additionally, we can use this same logic to solve https://github.com/dotnet/source-build/issues/4297 and a similar scenario in the arcade repo project.

**Comment by ViktorHofer** [comment]
Note that there are multiple variants of (build) asset manifests.

### Repo manifests
We produce 1 to n repo manifests per inner-repo in a VMR vertical build. In most cases it's just 1 manifest but a few repos like sdk produce multiple ones.

### Merged vertical manifest
This one gets produced at the end of the VMR vertical build

### Final merged verticals manifest
This one is the manifest that gets uploaded to BAR and can only be created at a join point.

The ones that we should as an input for this are the repo manifests: https://github.com/dotnet/installer/blob/0bfd2dd757482b30745b799ee0a92cad3d8f5b50/src/SourceBuild/content/repo-projects/Directory.Build.props#L41
