### ISSUE TITLE
Investigate core-setup putting prebuilt MSBuild nupkg in its output directory, which is copied to blob-feed

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#431]
This package being in the blob feed causes the package version props to pick it up, if the version is higher than the source-built msbuild package.

@dseefeld noticed this happening in a local build. (Can you edit this to include the core-setup path these are ending up at?)

**Comment by dseefeld** [comment]
This issue will clean up a large portion of the poisoned files getting into the built product.

**Comment by dseefeld** [comment]
This is no longer an issue since the build is now building without prebuilts.
