### ISSUE TITLE
Public builds for 8.0 VMR are not uploading pipeline artifacts

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4315]
The public builds of the VMR for the release/8.0.1xx branch are not uploading pipeline artifacts. This is necessary in order to have access to build logs. This is likely a regression from the [1ES template migration](https://github.com/dotnet/installer/pull/19073).

**Comment by MichaelSimons** [comment]
The two publish steps were removed and replaced with outputs in the templateContext.  This works for internal builds but not for PR validation where no 1ES templates are used.  Should the two publish steps be added back within conditionals for PRs?

**Comment by ellahathaway** [comment]
Is there a reason that the PR validation does not use the 1ES templates for 8.0? It looks like the main branch uses them.

**Comment by MichaelSimons** [comment]
Mainly because 1ES templates are only a requirement for internal builds and because arcade support (although that doesn't apply here)

**Comment by ellahathaway** [comment]
I see. I think adding the two publish steps back in conditionally is the fastest/easiest fix. Since it doesn't seem like adding support for 1ES templates is necessary, I'll go the conditional route instead.
