### ISSUE TITLE
Guardian analysis errors in VMR

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4317]
There are various analysis errors showing up from Guardian: [build link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2427205&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca&t=d1aba2c3-5b21-511d-f336-affeabd629f9) (internal only). To resolve this, the [Guardian baseline file](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/.config/guardian/.gdnbaselines) needs to be updated. The [latest autobaselining PR](https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/pullrequest/38640) (internal link) is not up-to-date enough to resolve these errors. We'll need to wait for the next PR.

**Comment by tkapin** [comment]
@tkapin - check with the Prague Guardian team on what is their recommendation on handling vendored code and submodules

**Comment by MichaelSimons** [comment]
Latest builds are Guardian clean.  Closing.
