### ISSUE TITLE
Update artifact leg in release pipeline

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#4321]
Several artifact legs in VMR / Source-build were updated recently due to OS EOL. We need to reflect this change in the source-build release pipeline

**Comment by MichaelSimons** [comment]
The 8.0 changes were merged so that release also needs updating.

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39280
