### ISSUE TITLE
9.0.0-preview.3 fails to build when package source (`--with-packages`) is read-only

### ISSUE THREAD

**Issue by corngood** [dotnet/source-build#4325]
### Describe the Bug

If I use build.sh with `--with-packages [path]` and point it to a directory on a read-only file-system, I get an error like:

eng/tools/init-build.proj(53,5): error MSB3677: Unable to move file "[path]/SourceBuildReferencePackages/Humanizer.Core.2.2.0.nupkg" to "prereqs/packages/reference/Humanizer.Core.2.2.0.nupkg". Moving target is read-only

This hasn't been a problem on previous versions, including: 8.0.4, 9.0.0-preview.2.

**Comment by corngood** [comment]
https://github.com/dotnet/dotnet/blob/dd82ae7012234d2a447fd8db22353629c395ac48/eng/tools/init-build.proj#L53

If I change this to use `<Copy>`, I no longer get the error.

**Comment by MichaelSimons** [comment]
[Triage] This was a regression introduced in https://github.com/dotnet/installer/pull/19143.  The intent was to use move over copy for performance reasons.  We should go back to using copy but use the symbolic link option (UseSymbolicLinksIfPossible).
