### ISSUE TITLE
aspnetcore not publishing all outputs

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4331]
ASPNetCore is not publishing all its outputs as part of UB. Right now it only appears to publish the product version files:

![Image](https://github.com/dotnet/source-build/assets/8725170/76904f2c-5840-42ef-8a7d-e798d2a829f4)

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/source-build/issues/4338
