### ISSUE TITLE
Runtime windows verticals failing to build in the VMR

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4335]
> CSC : error CS0016: Could not write to output file 'D:\a\_work\1\s\src\runtime\artifacts\obj\cdacreader\Release\net9.0\win-x64\generated\Microsoft.Interop.ComInterfaceGenerator\Microsoft.Interop.ComClassGenerator\Microsoft.Diagnostics.DataContractReader.SOSDacImpl.cs' -- 'Could not find a part of the path 'D:\a\_work\1\s\src\runtime\artifacts\obj\cdacreader\Release\net9.0\win-x64\generated\Microsoft.Interop.ComInterfaceGenerator\Microsoft.Interop.ComClassGenerator\Microsoft.Diagnostics.DataContractReader.SOSDacImpl.cs'.' [D:\a\_work\1\s\src\runtime\src\native\managed\cdacreader\src\cdacreader.csproj]
    CSC : error CS0016: Could not write to output file 'D:\a\_work\1\s\src\runtime\artifacts\obj\cdacreader\Release\net9.0\win-x64\generated\Microsoft.Interop.ComInterfaceGenerator\Microsoft.Interop.ComInterfaceGenerator\Microsoft.Diagnostics.DataContractReader.ISOSDacInterface9.cs' -- 'Could not find a part of the path 'D:\a\_work\1\s\src\runtime\artifacts\obj\cdacreader\Release\net9.0\win-x64\generated\Microsoft.Interop.ComInterfaceGenerator\Microsoft.Interop.ComInterfaceGenerator\Microsoft.Diagnostics.DataContractReader.ISOSDacInterface9.cs'.' [D:\a\_work\1\s\src\runtime\src\native\managed\cdacreader\src\cdacreader.csproj]

https://dnceng-public.visualstudio.com/public/_build/results?buildId=646322&view=logs&j=9050e078-31bf-5111-d8ec-8b6fa95caf9c&t=4df1dbeb-294c-5d6e-97b8-581fe506c270

@elinor-fung

**Comment by jeffschwMSFT** [comment]
this is also impacting dotnet/runtime official build (though is non-deterministic) 

https://dnceng.visualstudio.com/internal/_build/results?buildId=2430979&view=logs&j=bdec34cc-8c67-558e-657b-d36a4105119f&t=57c2fa6d-d2d0-5d36-e636-8657b10bc2de&l=599

**Comment by RikkiGibson** [comment]
`Could not find a part of the path` makes it sound like the output directory is not present. But the compiler and compiler tasks should create the directory (both the /generated directory and the individual generator output directories within it).

https://github.com/dotnet/roslyn/blob/d5b9aaa7e984890c9a8d967bde68d1c62d4858fa/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L339-L340

https://github.com/dotnet/roslyn/blob/d5b9aaa7e984890c9a8d967bde68d1c62d4858fa/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L1173-L1176

However it looks like the task linked above didn't run in the cdacreader build. binlog says:

> Target Name=CreateCompilerGeneratedFilesOutputPath Project=cdacreader.csproj
>     Target "CreateCompilerGeneratedFilesOutputPath" skipped, due to false condition; ('$(EmitCompilerGeneratedFiles)' == 'true' and !('$(DesignTimeBuild)' == 'true' OR '$(BuildingProject)' != 'true')) was evaluated as ('true' == 'true' and !('' == 'true' OR 'false' != 'true')).

I'm confused by this :) as `'true' == 'true' and !('' == 'true' OR 'false' != 'true')` seems like it ought to evaluate to true.

**Comment by chsienki** [comment]
@RikkiGibson Lol I just spent like a genuine 5 minutes working through the logic of that condition, then did a git blame to see who wrote it and well, well we meet again past Chris.

Something in the authoring is off definitely, but it also seems odd that the compiler still tries to write the files out, even if the directory isn't there, so we should probably file a bug on Roslyn for that.

**Comment by RikkiGibson** [comment]
Opened dotnet/roslyn#73075

**Comment by akoeplinger** [comment]
Indeed: https://github.com/github/codeql/blob/a108fcd2b49eec5dacde7636cf1c781b04ee5aa9/csharp/tools/tracing-config.lua#L117-L121

**Comment by akoeplinger** [comment]
@jaredpar another case were CodeQL is messing with us :)
