### ISSUE TITLE
AspNetCore fails to build inside the VMR on Windows

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4338]
> D:\a\_work\1\s\src\aspnetcore\src\Components\WebAssembly\WebAssembly\src\Microsoft.AspNetCore.Components.WebAssembly.csproj(65,5): error : '..\..\..\Web.JS\dist\Release\blazor.webassembly.js' does not exist. Enable NodeJS to pack this project.
  D:\a\_work\1\s\src\aspnetcore\src\Components\WebView\WebView\src\Microsoft.AspNetCore.Components.WebView.csproj(67,5): error : 'D:\a\_work\1\s\src\aspnetcore\src\Components\WebView\WebView\src\..\..\..\Web.JS\dist\Release\blazor.webview.js' does not exist. Ensure the JS assets have been build by running 'npm run build' from the repository root.
  CSC : error CS1566: Error reading resource '_framework/blazor.webview.js' -- 'Could not find a part of the path 'D:\a\_work\1\s\src\aspnetcore\src\Components\Web.JS\dist\Release\blazor.webview.js'.' [D:\a\_work\1\s\src\aspnetcore\src\Components\WebView\WebView\src\Microsoft.AspNetCore.Components.WebView.csproj]
  D:\a\_work\1\s\src\aspnetcore\src\Components\Endpoints\src\Microsoft.AspNetCore.Components.Endpoints.csproj(67,5): error : 'D:\a\_work\1\s\src\aspnetcore\src\Components\Endpoints\src\..\..\Web.JS\dist\Release\blazor.web.js' does not exist. Ensure the JS assets have been build by running 'npm run build' from the repository root.
  CSC : error CS1566: Error reading resource '_framework/blazor.web.js' -- 'Could not find a part of the path 'D:\a\_work\1\s\src\aspnetcore\src\Components\Web.JS\dist\Release\blazor.web.js'.' [D:\a\_work\1\s\src\aspnetcore\src\Components\Endpoints\src\Microsoft.AspNetCore.Components.Endpoints.csproj]
      0 Warning(s)
      5 Error(s)

Those errors are currently not propagated correctly back into the VMR orchestrator due to https://github.com/dotnet/source-build/issues/4277

**Comment by ViktorHofer** [comment]
@mmitche mentioned:

> I think the issue is that the YAML file needs to install node20 (via AzDO task) prior to running

**Comment by MichaelSimons** [comment]
@ViktorHofer - Is there any work to complete here or was it all done with https://github.com/dotnet/installer/pull/19536?

**Comment by ViktorHofer** [comment]
All done
