### ISSUE TITLE
SDK diff tests not triggered for failing VMR release builds

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#4349]
The SDK diff tests are now getting triggered on every VMR release build. If the said VMR build fails, the tests do not get triggered. This is a regression from how they used to behave before the trigger change, where the pipeline would run regardless of the latest build succeeding or not.

A potential issue here is that the VMR pipeline run consists of multiple different builds and there could be value in running the tests for those that did succeed even if the run itself fails. This could be done with either trying to limit the trigger to just one stage (like the `Tag & Scan` one) or falling back to triggering the tests from the VMR build.

CC: @MichaelSimons

**Comment by MichaelSimons** [comment]
[Triage] We believe the pipeline trigger is the better approach over a scheduled trigger.  If the pipeline fails and you want to run the sdk diff off of the failed build, you can queue it manually.  Closing as won't fix.
