### ISSUE TITLE
[6.0.1xx] Remove System.Security.Cryptography 4.7.0 from SBRP

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4350]
[The Stage 2 tarball build failed](https://github.com/dotnet/source-build/issues/4347#issue-2256050222) due to msbuild 17.0.1's dependency on System.Security.Cryptography.4.7.0, which was removed from 6.0 in https://github.com/dotnet/source-build-reference-packages/pull/939.

This wasn't an issue in Stage 1 as the required package was in the previously-source-built artifacts. To fix the Stage 2 build, System.Security.Cryptography.4.7.0 was added back to SBRP temporarily. Since msbuild fixed its dependency on this package in https://github.com/dotnet/msbuild/pull/9867, we can remove System.Security.Cryptography.4.7.0 from SBRP once the next release occurs and the previously-source-built artifacts have been updated.

**Comment by MichaelSimons** [comment]
[triage] This can be removed once we rebootstrap after the May servicing release.
