### ISSUE TITLE
Start using the `sdk [SHA]` tag in the release pipeline

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#4360]
Once we switch the `main` of the VMR to be synchronized from `dotnet/sdk`, the tag on the VMR pipelines will change from `install [SHA]` to `sdk [SHA]`.
We use this tag to find the associated pipeline runs. We will need to make 9.0 release look for this tag.

**Comment by ellahathaway** [comment]
Related to https://github.com/dotnet/source-build/issues/4357. Draft PR with changes: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39308 (internal Microsoft link). Planning on updating/publishing the PR once we switch the VMR to sync from dotnet/sdk.

**Comment by ellahathaway** [comment]
Update: Waiting to update the draft PR until the Staging pipeline is releasing from SDK.

**Comment by ellahathaway** [comment]
Closing since the PR was merged https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39308
