### ISSUE TITLE
Update 2.0 branch

### ISSUE THREAD

**Issue by ghost** [dotnet/source-build#437]
Core-setup has 2.0.7 tag available https://github.com/dotnet/core-setup/tree/v2.0.7 with bunch of fixes including ncurses6.1 support in corefx.

**Comment by dagood** [comment]
@crummel to answer for sure, but I don't think the `release/2.0` or `dev/release/2.0` branches in this repo are active, so updating the core-setup submodule wouldn't have any effect.

**Comment by crummel** [comment]
Yes, these branches are inactive.  This is something we'd like to look into but haven't had a chance yet.

**Comment by kasper3** [comment]
Thanks! Downstream consumers have started to evaluate source-build https://github.com/gentoo/dotnet/blob/ea3a6db8733a74eb9c20d7b7c67fb23baa43c804/Documentation/DotnetCore-Src.md. It would be great if servicing updates are applied automatically (@dotnet-bot's PRs?) in released branches in this repo, so we get the updates at the same time.

**Comment by dseefeld** [comment]
Not needed for 2.0.
