### ISSUE TITLE
Alpine319_Online_MsftSdk_x64 failing due to prebuilt issue: 2 Prebuilts Exist

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4379]
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2446519&view=logs&j=7830363c-9761-5497-b6c6-e8d55da0c426&t=1e170c11-e4db-59a8-3304-04a8c0605512

/vmr/eng/finish-source-only.proj(171,5): error : 2 Prebuilts Exist:

      <NeverRestoredTarballPrebuilts>
        <PackageIdentity Id="Microsoft.NETCore.App.Runtime.linux-x64" Version="9.0.0-preview.4.24251.3" />
        <PackageIdentity Id="runtime.linux-x64.Microsoft.DotNet.ILCompiler" Version="9.0.0-preview.4.24251.3" />
      </NeverRestoredTarballPrebuilts>
      <Usages>
        <Usage Id="Microsoft.NET.ILLink.Tasks" Version="9.0.0-preview.4.24251.3" IsDirectDependency="true" IsAutoReferenced="true" />
        <Usage Id="Microsoft.NETCore.App.Runtime.linux-musl-x64" Version="9.0.0-preview.4.24251.3" />
        <Usage Id="runtime.linux-musl-x64.Microsoft.DotNet.ILCompiler" Version="9.0.0-preview.4.24251.3" Rid="linux-musl-x64" />
      </Usages>

More information: 
[generated-new-baseline.xml](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ0NjUxOS9hcnRpZmFjdE5hbWUvQWxwaW5lMzE5X09ubGluZV9Nc2Z0U2RrX3g2NF9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2Fprebuilt-report%2Fgenerated-new-baseline.xml)
[prebuilt-packages](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ0NjUxOS9hcnRpZmFjdE5hbWUvQWxwaW5lMzE5X09ubGluZV9Nc2Z0U2RrX3g2NF9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=zip&subPath=%2Fartifacts%2Fprebuilt-report%2Fprebuilt-packages)

**Comment by MichaelSimons** [comment]
This was fixed by https://github.com/dotnet/sdk/pull/40773.
