### ISSUE TITLE
Allow non-portable build on OSX

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#438]
CLI expects the Core-Setup (.NET Runtime) output tarball to always have the portable runtime name (`osx`, not `osx.10.12`). Either:

 * Add to Core-Setup a way to use the short name even when building non-portable OR
 * Add to CLI a way to pick up the non-portable OSX Runtime assets.

Lets us remove this workaround:

https://github.com/dotnet/source-build/blob/009da49ed54eb09a6fc5dda44e6bc62b935f5d6b/dir.props#L75-L78

**Comment by dseefeld** [comment]
This is fixed in Master.
