### ISSUE TITLE
[Release/9.0.1xx-preview4] All SDK diff tests are failing

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4389]
`Release/9.0.1xx-preview4` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2446888&view=results

Below issues has been fixed in `main` build, but they are failing in `9.0` build now, related to https://github.com/dotnet/source-build/issues/4342
`ArtifactsSizeTest.CompareArtifactsToBaseline` failing in [centos9](https://dev.azure.com/dnceng/internal/_build/results?buildId=2446888&view=ms.vss-test-web.build-test-results-tab&runId=53577383&resultId=100002&paneView=debug):

    Executing: tar xzf /mnt/vss/_work/1/Artifacts/dotnet-sdk-9.0.100-preview.4.24257.1-centos.9-x64.tar.gz -C /tmp/nsxz5qnp.a4r
    Executing: tar xzf /mnt/vss/_work/1/Artifacts/Private.SourceBuilt.Artifacts.9.0.100-preview.4.24257.1.centos.9-x64.tar.gz -C /tmp/nsxz5qnp.a4r
    VerticalManifest.xml does not exist in baseline. It is 73758 bytes. Adding it to the baseline file.
    'sdk/x.y.z/NuGet.Versioning.dll' decreased in size by more than 25%. It was originally 207360 bytes and is now 146944 bytes.
    'sdk/x.y.z/NuGet.Packaging.dll' decreased in size by more than 25%. It was originally 2325504 bytes and is now 1693696 bytes.
    'sdk/x.y.z/NuGet.Commands.dll' decreased in size by more than 25%. It was originally 2049536 bytes and is now 1510400 bytes.
    'sdk/x.y.z/NuGet.Frameworks.dll' decreased in size by more than 25%. It was originally 454144 bytes and is now 338944 bytes.
    'sdk/x.y.z/NuGet.CommandLine.XPlat.dll' decreased in size by more than 25%. It was originally 936960 bytes and is now 701952 bytes.
    'sdk/x.y.z/NuGet.Protocol.dll' decreased in size by more than 25%. It was originally 2831872 bytes and is now 2048000 bytes.
    'shared/Microsoft.AspNetCore.App/x.y.z/Microsoft.AspNetCore.Identity.dll' decreased in size by more than 25%. It was originally 531456 bytes and is now 380416 bytes.
    'sdk/x.y.z/Containers/tasks/netx.y/NuGet.Versioning.dll' decreased in size by more than 25%. It was originally 207360 bytes and is now 146944 bytes.
    'sdk/x.y.z/Containers/tasks/netx.y/NuGet.Packaging.dll' decreased in size by more than 25%. It was originally 2325504 bytes and is now 1693696 bytes.
    'sdk/x.y.z/Containers/tasks/netx.y/NuGet.Frameworks.dll' decreased in size by more than 25%. It was originally 454144 bytes and is now 338944 bytes.
    'sdk/x.y.z/Containers/tasks/netx.y/NuGet.Protocol.dll' decreased in size by more than 25%. It was originally 2831872 bytes and is now 2048000 bytes.
    'sdk/x.y.z/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Versioning.dll' decreased in size by more than 25%. It was originally 215040 bytes and is now 153088 bytes.
    'sdk/x.y.z/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Packaging.dll' decreased in size by more than 25%. It was originally 2081280 bytes and is now 1520640 bytes.
    'sdk/x.y.z/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Commands.dll' decreased in size by more than 25%. It was originally 2041856 bytes and is now 1502720 bytes.
    'sdk/x.y.z/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Frameworks.dll' decreased in size by more than 25%. It was originally 461824 bytes and is now 345088 bytes.
    'sdk/x.y.z/Sdks/NuGet.Build.Tasks.Pack/CoreCLR/NuGet.Protocol.dll' decreased in size by more than 25%. It was originally 2832384 bytes and is now 2046976 bytes.
    'sdk/x.y.z/Sdks/Microsoft.NET.Sdk.WebAssembly/targets/Microsoft.NET.Sdk.WebAssembly.9_0.temp.targets' increased in size by more than 25%. It was originally 5479 bytes and is now 8780 bytes.
    'sdk/x.y.z/Sdks/Microsoft.NET.Sdk.WebAssembly/targets/Microsoft.NET.Sdk.WebAssembly.6_0.temp.targets' increased in size by more than 25%. It was originally 5451 bytes and is now 8752 bytes.
    'sdk/x.y.z/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.References.targets' increased in size by more than 25%. It was originally 10427 bytes and is now 13108 bytes.
    'sdk/x.y.z/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets' increased in size by more than 25%. It was originally 11399 bytes and is now 15080 bytes.
    sdk/x.y.z/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.ContentTypeMappings.props does not exist in baseline. It is 48811 bytes. Adding it to the baseline file.
    'sdk/x.y.z/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets' increased in size by more than 25%. It was originally 10368 bytes and is now 13653 bytes.
    'sdk/x.y.z/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.Publish.targets' increased in size by more than 25%. It was originally 10699 bytes and is now 14188 bytes.
    'packs/Microsoft.AspNetCore.App.Ref/x.y.z/ref/netx.y/Microsoft.AspNetCore.Identity.dll' decreased in size by more than 25%. It was originally 78848 bytes and is now 57856 bytes.
    'sdk/x.y.z/Sdks/Microsoft.NET.Sdk.StaticWebAssets/tasks/netx.y/Microsoft.NET.Sdk.StaticWebAssets.Tasks.dll' increased in size by more than 25%. It was originally 135168 bytes and is now 175616 bytes.
    `sdk/x.y.z/Containers/tasks/netx.y/NuGet.Packaging.Core.dll` is no longer being produced. It was 7168 bytes.
    `sdk/x.y.z/NuGet.Packaging.Core.dll` is no longer being produced. It was 7168 bytes.
`SdkContentTests.CompareMsftToSbFileList` failing in [all legs](https://dev.azure.com/dnceng/internal/_build/results?buildId=2446888&view=artifacts&pathAsName=false&type=publishedArtifacts):
[MsftToSbSdkFiles.diff](https://github.com/dotnet/dotnet/blob/release/9.0.1xx-preview4/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/baselines/MsftToSbSdkFiles.diff)
[UpdatedMsftToSbSdkFiles.diff](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ0Njg4OC9hcnRpZmFjdE5hbWUvQWxwaW5lMzE5X09ubGluZV9Nc2Z0U2RrX3g2NF9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2FUpdatedMsftToSbSdkFiles.diff)

`./sdk/x.y.z/<lang>/Microsoft.Build.NuGetSdkResolver.resources.dll` is missing for all languages.

**Comment by MichaelSimons** [comment]
I don't think we should do anything here.  Preview 4 builds are done.
