### ISSUE TITLE
Building roslyn in the VMR fails non-deterministically

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4390]
Sometimes roslyn fails to build in the VMR because of a race condition:

> CSC : error CS2012: Cannot open 'D:\a\_work\1\vmr\src\roslyn\artifacts\obj\SemanticSearch.ReferenceAssemblies\Release\net8.0\SemanticSearch.ReferenceAssemblies.dll' for writing -- 'The process cannot access the file 'D:\a\_work\1\vmr\src\roslyn\artifacts\obj\SemanticSearch.ReferenceAssemblies\Release\net8.0\SemanticSearch.ReferenceAssemblies.dll' because it is being used by another process.' [D:\a\_work\1\vmr\src\roslyn\src\Tools\SemanticSearch\ReferenceAssemblies\SemanticSearch.ReferenceAssemblies.csproj]

Example build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=669255&view=logs&jobId=9050e078-31bf-5111-d8ec-8b6fa95caf9c&j=9050e078-31bf-5111-d8ec-8b6fa95caf9c&t=523d8a07-ca4d-5c7a-367a-d86c5fc4038b

This is probably due to the project being built twice with the same outputs (an anti-pattern in msbuild). The binlog should tell. @jaredpar who would be a good person on the roslyn team to take a look?

**Comment by jaredpar** [comment]
> This is probably due to the project being built twice with the same outputs (an anti-pattern in msbuild). The binlog should tell. @jaredpar who would be a good person on the roslyn team to take a look?

I only see one binlog attached to that pipeline and it's for the outer build. The inner builds only seem to have non-binary logs. Am I looking in the wrong place? 

![image](https://github.com/dotnet/source-build/assets/146967/967961bf-0d54-4116-a358-7c553240039e)

**Comment by ViktorHofer** [comment]
Yes. It's the "source-inner-build.binlog".

**Comment by jaredpar** [comment]
I've looked at the binlog and it does seem like there are two paths to building SemnaticSearch.ReferenceAsesmblies.csproj

![image](https://github.com/dotnet/source-build/assets/146967/b44fbfc3-5d93-4123-82b1-b931d2ab9b22)

![image](https://github.com/dotnet/source-build/assets/146967/4d55164e-8be0-4155-aab4-f17320e496aa)

At the same time though ... I don't see how that is a build authoring error on our part. There is nothing particularly special I can see here. The relationship between Roslyn.VisualStudio.Setup.csproj to SemanticSearch.ReferenceAssemblies.csproj is a simple ProjectReference. 

It does seem odd that Microsoft.VisualStudio.LanguageServices.New.IntegrationTests.csproj has a .metaproj. That's beyond my understanding of  msbuild.

**Comment by ViktorHofer** [comment]
I see that the csc task is invoked twice non-incrementally on the non-multi-targeting project via this msbuild binlog viewer query:

> $task csc under($project SemanticSearch.ReferenceAssemblies.csproj)

![image](https://github.com/dotnet/source-build/assets/7412651/c1ef938d-8091-4240-8fd8-093d777a68b9)

Here's the global property diff for those two project evaluations: https://www.diffchecker.com/YbB9Ksu0/
Because the global properties differ, the project builds twice.

One evaluation has an additional `TargetFramework` global property which is wrong as single targeting projects shouldn't have that. This is because of this code: https://github.com/dotnet/roslyn/blob/324e078a9b47b62cd6dec6c78c6308c4540aa1e5/src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj#L311-L312

Remove `SetTargetFramework` and the overbuilding and race condition will go away. FWIW the msbuild team is adding analyzers that will detect such cases.

**Comment by tmat** [comment]
> FWIW the msbuild team is adding analyzers that will detect such cases.

We need to enable these analyzers for all our repos asap. 
@rainersigwald

**Comment by rainersigwald** [comment]
They don't exist yet, but @JanKrivanek will be happy to have eager customers when they do.

**Comment by jaredpar** [comment]
In this case it looks like the problem is that `SemanticSearch.Reference.Assemblies` targets `net8.0` while the VS project targets `net472`. Assume the `SetTargetFramework` element is trying to resolve that problem. What is the correct way to solve that?

@tmat

**Comment by ViktorHofer** [comment]
A `ProjectReference` pointing to a single targeting project doesn't need and shouldn't have the `SetTargetFramework` metadata as there's only one TFM in the project. The important part is the `SkipGetTargetFrameworkProperties` metadata which silences NuGet's compatibility analysis. For multi-targeting projects, the usage of `SetTargetFramework` is valid if you want to choose the nearest compatible TFM yourself (instead of NuGet).
