### ISSUE TITLE
Binaries are not being removed from VMR when building from archive

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4391]
When building the VMR from archive, the binaries are not removed from the VMR by the prep script.  The binary tool still runs, it just isn't removing any binaries. See [this run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2447398&view=logs&j=a5ccaa14-6811-5159-45fe-06b91679b5f1&t=88f87c3f-10bc-5f04-4d62-16700c86fdcc&l=99) as an example (internal Microsoft link)

**Comment by ellahathaway** [comment]
It's because the `/.git` directory is being removed when we copy over the sources. This results in the .gitignore file not being used when the tool looks for ignored files. To fix this, all files must be added via `git add .` when a fake git repo is configured by the tool.

**Comment by omajid** [comment]
FWIW, when we use the tarball from a release on github, we may not have the original source (and the .gitignore files) to copy over.

**Comment by ellahathaway** [comment]
Further issue, some repo has been including binaries in their .gitignore files. This has resulted in those binaries going undetected. I think that the best way forward is to just hardcode common paths that we know should be ignored.

**Comment by omajid** [comment]
On the Fedora side of things, I am looking at never running prep-source-build.sh (outside of a bootstrap scenario) and manually running a delete. It's looking like this: https://pagure.io/dotnet-sig/dotnet9.0/blob/main/f/dotnet9.0.spec#_427

```
# Remove all prebuilts and binaries
rm -rf .dotnet/
rm -rf packages/source-built
find -type f \( \
    -iname '*.bin' -or \
    -iname '*.db' -or \
    -iname '*.dll' -or \
    -iname '*.doc' -or \
    -iname '*.docx' -or \
    -iname '*.exe' -or \
    -iname '*.mdb' -or \
    -iname '*.mod' -or \
    -iname '*.msi' -or \
    -iname '*.netmodule' -or \
    -iname '*.nupkg' -or \
    -iname '*.obj' -or \
    -iname '*.p7b' -or \
    -iname '*.p7s' -or \
    -iname '*.pdb' -or \
    -iname '*.pfx' -or \
    -iname '*.so' -or \
    -iname '*.tar.gz' -or \
    -iname '*.tlb' -or \
    -iname '*.winmd' -or \
    -iname '*.zip' \
    \) \
    -delete
```
