### ISSUE TITLE
Alpine Artifact Changed from 3.19 to 3.19.1

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4393]
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2448227&view=logs&j=c2a3fba4-babc-5882-e82a-8e0dc9edd6ec&t=57388f91-aa71-56c7-7172-a3ccb720198f

**For all legs:**
`Prepare Tests` step fails with:

    Microsoft SDK tarball does not exist in '/mnt/vss/_work/1/Artifacts'. The associated build https://dev.azure.com/dnceng/internal/_build/results?buildId=2447623 might have failed.

`Download MSFT SDK` step fails with:

    Pattern: **/dotnet-sdk-+([0-9]).+([0-9]).+([0-9])?(-@(alpha|preview|rc|rtm)*)-linux*-x64.tar.gz
    Minimatch patterns: [**/dotnet-sdk-+([0-9]).+([0-9]).+([0-9])?(-@(alpha|preview|rc|rtm)*)-linux*-x64.tar.gz]
    Applying include pattern against original list.
    0 matches
    0 final results

The associated builds:

    Dotnet-dotnet build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2447655&view=results
    Sdk build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2447623&view=results 
There are no dotnet-sdk*.tar.gz files published in Sdk build link.

**Only for `Alpine319_Online_MsftSdk_x64`:**
`Download Source Build SDK` and `Download Source Built Artifacts` steps fail with:

    Minimatch patterns: [**/assets/Release/dotnet-sdk-+([0-9]).+([0-9]).+([0-9])?(-@(alpha|preview|rc|rtm)*)-alpine.3.19-x64.tar.gz]
    Filtered 0 files from the Minimatch filters supplied.

    Minimatch patterns: [**/assets/Release/Private.SourceBuilt.Artifacts.+([0-9]).+([0-9]).+([0-9])?(-@(alpha|preview|rc|rtm)*).alpine.3.19-x64.tar.gz]
    Filtered 0 files from the Minimatch filters supplied.

File name changed:
[Private.SourceBuilt.Artifacts.9.0.100-preview.5.24258.1.alpine.3.19.1-x64.tar.gz](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ0NzY1NS9hcnRpZmFjdE5hbWUvQWxwaW5lMzE5X09ubGluZV9Nc2Z0U2RrX3g2NF9BcnRpZmFjdHM1/content?format=file&subPath=%2Fassets%2FRelease%2FPrivate.SourceBuilt.Artifacts.9.0.100-preview.5.24258.1.alpine.3.19.1-x64.tar.gz) 
[dotnet-sdk-9.0.100-preview.5.24258.1-alpine.3.19.1-x64.tar.gz](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ0NzY1NS9hcnRpZmFjdE5hbWUvQWxwaW5lMzE5X09ubGluZV9Nc2Z0U2RrX3g2NF9BcnRpZmFjdHM1/content?format=file&subPath=%2Fassets%2FRelease%2Fdotnet-sdk-9.0.100-preview.5.24258.1-alpine.3.19.1-x64.tar.gz)

**Comment by ViktorHofer** [comment]
@ellahathaway should we close this issue now that you disabled the pipeline on main with https://github.com/dotnet/sdk/commit/51e1c31a875ff7c9652451f5e5b8875cf7127ada?

**Comment by ellahathaway** [comment]
Actually, reopening this because the Alpine artifact name is now different. Is was `**/assets/Release/dotnet-sdk-+([0-9]).+([0-9]).+([0-9])?(-@(alpha|preview|rc|rtm)*)-alpine.3.19-x64.tar.gz` and is now `**/assets/Release/dotnet-sdk-+([0-9]).+([0-9]).+([0-9])?(-@(alpha|preview|rc|rtm)*)-alpine.3.19.1-x64.tar.gz`

**Comment by MichaelSimons** [comment]
[Triage] It would be nice if the RID could be portable so that the SB artifacts would be usable across alpine version upgrades.
