### ISSUE TITLE
SdkTemplateTests timeout

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4394]
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2448147&view=logs&j=8e1d7f5f-2dd9-5bba-3568-6eebce65bc74&t=a8f9fb18-43e6-5d18-cb2e-d8cac8cb066e

`Microsoft.DotNet.ScenarioTests.SdkTemplateTests` test timeout:

    Restored /vmr/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/Microsoft.DotNet.ScenarioTests.SdkTemplateTests.csproj (in 8.92 sec).
    Test environment:
      Dotnet Root: /vmr/artifacts/obj/extracted-dotnet-sdk/
      Test root: /vmr/artifacts/scenario-tests/artifacts/
      Target RID: ubuntu.22.04-arm64
      Sdk Version: 9.0.100-preview.5.24259.1
      Platform: LINUX
    ##[error]The task has timed out.

**Comment by MichaelSimons** [comment]
This was already address by https://github.com/dotnet/sdk/pull/40790
