### ISSUE TITLE
3774 new binaries introduced into VMR

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4395]
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2449450&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=2a0bd486-3f67-5c59-da0c-b84d88848a4b

    New binaries:
      src/sdk/.dotnet/dotnet
      src/sdk/.dotnet/host/**
      src/sdk/.dotnet/packs/**
      src/sdk/.dotnet/sdk/**
      src/sdk/.dotnet/shared/**
      src/sdk/.dotnet/templates/**
      artifacts/bin/**
      artifacts/obj/**

More information:
[NewBinaries.txt](https://github.com/dotnet/source-build/files/15282375/NewBinaries.txt)
[allowed-sb-binaries.txt](https://github.com/dotnet/dotnet/blob/main/eng/allowed-sb-binaries.txt)
[allowed-vmr-binaries.txt](https://github.com/dotnet/dotnet/blob/main/eng/allowed-vmr-binaries.txt)

**Comment by mthalman** [comment]
@ellahathaway - PTAL. These binaries don't exist in the repo.

**Comment by ViktorHofer** [comment]
Potentially regressed with https://github.com/dotnet/sdk/commit/d5cb00f7dcb79b9cfc6c528f5b574ba4fd5ffd7a?

**Comment by ellahathaway** [comment]
The BinaryToolKit binaries make sense. I'll add those to the ignore file.

As far as the rest of the binaries, it looks like the `Initialize Tooling` step of Tag & Scan installs dotnet into `src/sdk` in order to use darc: `Adding to current process PATH: /mnt/vss/_work/1/s/src/sdk/.dotnet` To fix that, I'll make the ignored `.dotnet/` be `**/.dotnet/`.

**Comment by akoeplinger** [comment]
@ellahathaway hm interesting, the --tool-manifest option looks a bit pointless then :)
You can make it work if you run the commands in the src/sdk directory but with the dotnet from the root:

```
source eng/common/tools.sh
InitializeDotNetCli true

cd src/sdk
../../.dotnet/dotnet tool restore
../../.dotnet/dotnet darc
```
