### ISSUE TITLE
[Release/9.0.1xx-preview4] License Scan is failing for sdk and wpf repo

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4398]
`Release/9.0.1xx-preview4` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2449897&view=results

Below issues have been fixed in `main` build, but they are still failing in `preivew4` build, related to https://github.com/dotnet/source-build/issues/4346 and https://github.com/dotnet/source-build/issues/4373

`LicenseScan sdk` failed with error:

    {
      "files": [
        {
          "path": "src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/LicenseScanTests.cs",
          "detected_license_expression": "mit AND unknown-license-reference AND (apache-1.1 AND apache-2.0 AND llvm-exception AND apsl-2.0) AND (boost-1.0 AND bsd-new AND bsd-original-uc AND bsd-simplified AND cc0-1.0 AND cc-by-3.0 AND cc-by-4.0 AND cc-by-sa-3.0 AND cc-by-sa-4.0 AND epl-1.0 AND gpl-1.0 AND gpl-2.0 AND gpl-2.0-plus AND isc AND lgpl-2.0 AND lgpl-2.1 AND lgpl-2.1-plus AND mit AND ms-pl AND ms-rl AND ngpl AND ofl-1.1 AND public-domain AND python AND rpl-1.5 AND sax-pd AND unicode AND w3c AND x11-xconsortium AND zlib) AND (mit OR apache-2.0)"
        },
        {
          "path": "src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseExclusions.txt",
          "detected_license_expression": "cecill-c AND (cecill-c AND proprietary-license) AND proprietary-license AND llvm-exception"
        },
        {
          "path": "src/VirtualMonoRepo/THIRD-PARTY-NOTICES.template.txt",
          "detected_license_expression": "unknown-license-reference"
        }
      ]
    }
More information: [scancode-results.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ0OTg5Ny9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rc2RrX0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2Fscancode-results.json)

`LicenseScan wpf` failed with error:

    {
      "files": [
        {
          "path": "src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/WindowBackdropType.cs",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Accent.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/DefaultContextMenu.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/DefaultFocusVisualStyle.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Fluent.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Fonts.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/StaticColors.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC1.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC2.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCBlack.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCWhite.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml",
          "detected_license_expression": "mit AND mpl-2.0"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ContextMenu.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml",
          "detected_license_expression": "mit AND (mpl-2.0 AND mit)"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml",
          "detected_license_expression": "mit AND mpl-2.0"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Frame.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Label.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListBox.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListBoxItem.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListView.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListViewItem.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Menu.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/MenuItem.xaml",
          "detected_license_expression": "mit AND mpl-2.0"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Page.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml",
          "detected_license_expression": "mit AND mpl-2.0"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ProgressBar.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ScrollBar.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ScrollViewer.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Separator.xaml",
          "detected_license_expression": "mit AND mpl-2.0"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Slider.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/StatusBar.xaml",
          "detected_license_expression": "mit AND mpl-2.0"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBlock.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml",
          "detected_license_expression": "mit AND mpl-2.0"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToggleButton.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolBar.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolTip.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TreeView.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TreeViewItem.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        },
        {
          "path": "src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Window.xaml",
          "detected_license_expression": "mit AND bsd-2-clause-views"
        }
      ]
    }
More information: [scancode-results.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ0OTg5Ny9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rd3BmX0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2Fscancode-results.json)

**Comment by MichaelSimons** [comment]
@Winniexu01, We will not be making any fixes for these in Preview 4, as you noted, they have been fixed in main.
