### ISSUE TITLE
Update CI Distro Matrix

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4399]
## Current CI Distro Matrix

| 6.0 | 8.0 | 9.0 |
| ---- | ---- | ---- |
| Alpine 3.17 | Alpine 3.19 | Alpine 3.19 |
| Debian 11 |
| CentOS 7 |  |  |
| | CentOS Stream 8 | |
| CentOS Stream 9  | CentOS Stream 9 | CentOS Stream 9 |
| Fedora 38 | Fedora 38 | Fedora 39 |
| Ubuntu 18.04 | Ubuntu 22.04 | Ubuntu 22.04 |

### 6.0

- [x] Drop Debian 11
- [x] Upgrade Fedora 38 -> 40
- [x] Ubuntu 18.04 -> 20.04

### 8.0

- [x] Drop CentOS Stream 8
- [x] Upgrade Fedora 38 -> 40
- [x] Update Alpine 3.19 -> 3.20
- [x] Add Alma Linux 8

### 9.0

- [x] Upgrade Fedora 39 -> 40
- [x] Ubuntu 22.04 -> 24.04
- [x] Update Alpine 3.19 -> 3.20
- [x] Add Alma Linux 8

## Proposed CI Distro Matrix

| 6.0 | 8.0 | 9.0 |
| ---- | ---- | ---- |
| Alpine 3.17 | Alpine 3.20 | Alpine 3.20 |
|  | Alma Linux 8 | Alma Linux 8 |
| CentOS 7 |  |  |
| CentOS Stream 9  | CentOS Stream 9 | CentOS Stream 9 |
| Fedora 40 | Fedora 40 | Fedora 40 |
| Ubuntu 20.04 | Ubuntu 22.04 | Ubuntu 24.04 |

**Comment by MichaelSimons** [comment]
[Triage] The point of @omajid's suggestion is to ensure SB builds on the lowest supported glibc version.

**Comment by MichaelSimons** [comment]
The 6.0 runtime doesn't support Clang 18+ so 6.0 can only be built on Fedora 39 not Fedora 40.  https://github.com/dotnet/runtime/pull/100258 would need to be back ported if we wanted to support this.  The .NET Fedora project has a [patch](https://src.fedoraproject.org/rpms/dotnet6.0/blob/rawhide/f/runtime-clang-18.patch) to support this.

**Comment by omajid** [comment]
I submitted the Fedora patch to 6.0: https://github.com/dotnet/runtime/pull/102529

**Comment by MichaelSimons** [comment]
> I submitted the Fedora patch to 6.0: [dotnet/runtime#102529](https://github.com/dotnet/runtime/pull/102529)

I am going to proceed with the Fedora 39 upgrade since I have everything tested and it includes other changes to get us off EOL distros.  Once the runtime change is merged and flows in, I will upgrade.
