### ISSUE TITLE
Align docker images between VMR unified build and runtime

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/source-build#4405]
In dotnet/runtime we bumped most docker images to azurelinux-3.0 ones:
https://github.com/dotnet/runtime/blob/2a80808f86459a95229c6f9c85ce32b62636fceb/eng/pipelines/common/templates/pipeline-with-resources.yml#L20

However the VMR unified build still uses the cbl-mariner-2.0 ones:
https://github.com/dotnet/sdk/blob/5a8b156bcc5b496d6de43c8cece1bacbb7fee46f/eng/pipelines/templates/variables/vmr-build.yml#L25-L42

We should make sure to keep these images aligned.

/cc @jkoritzinsky @ViktorHofer

**Comment by ViktorHofer** [comment]
Sounds reasonable. Do we just need to update the docker images  in vmr-build.yml or is there more to it?

**Comment by akoeplinger** [comment]
That should be it. We just need to remember to consistently do this until the VMR goes live and we remove the runtime official build.
