### ISSUE TITLE
Add --target-rid / -targetRid as a build script argument

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#4413]
https://github.com/dotnet/runtime/pull/100580 removed the distro specific handling of rids in favor of distro packagers provide their rid when building .NET.

We should facilitate distro packagers in providing this value by making it a setting on the top-level build script.

cc @am11 @omajid @elinor-fung @ViktorHofer @mthalman

**Comment by ViktorHofer** [comment]
See https://github.com/dotnet/sdk/pull/40843#issuecomment-2122450531

**Comment by tmds** [comment]
> See https://github.com/dotnet/sdk/pull/40843#issuecomment-2122450531

From that:

>  make --outputrid a required arg (maps to -p:TargetRID) to keep things really explicit

I don't think we should make it required as it forces anyone that calls `build.sh` to come up with a name.

> outputrid CLI arg should probably just be called --target-rid / -targetRid.

nit: I prefer `output-rid` over `target-rid` because it names the output and it doesn't identify the target (except for the architecture).

Most package maintainers are expected to build for the build host architecture. It would be nice if they don't need to include it in the argument value. Then the same package script works across architectures without the maintainer having to write some code to map the system architecture to the rid arch.

**Comment by am11** [comment]
> nit: I prefer output-rid over target-rid because it names the output and it doesn't identify the target (except for the architecture).

Sounds good.

> I don't think we should make it required as it forces anyone that calls build.sh to come up with a name.

It is not for everyone, only someone doing a (very targeted) non-portable build which is usually a distro maintainer running it via their CI/CD automation using a manifest file. `./build.sh --output-rid ubuntu.24-arm64`. It is as explicit as it comes.

They can also use this helper if providing rid for :
```sh
#!/bin/sh

_distroId="$(grep -oP '^ID=\K.*' /etc/os-release | tr '[:upper:]' '[:lower:]')"
_version="$(grep -oP '^VERSION_ID="\K[0-9]+' /etc/os-release | tr -d '.')"
arch=$(uname -m | { read -r arch; case $arch in x86_64) echo x64 ;; aarch64) echo arm64 ;; armv7*) echo arm ;; i*86) echo x86 ;; *) echo "$arch" ;; esac; })

_calculated_rid="$_distroId.$_version${_version:+-}$_arch"
```

This will put the responsibility on a small subset of non-portable builders, yes, but it is trivial compared to dotnet infra maintaining the whole list of distros and their preferred style (no version, 1-part version, 2 or 3 parts). This will free them to change the format, and us free from maintenance.

**Comment by am11** [comment]
> nit: I prefer output-rid over target-rid because it names the output and it doesn't identify the target (except for the architecture).

Sounds good.

> I don't think we should make it required as it forces anyone that calls build.sh to come up with a name.

It is not for everyone, only someone doing a (very targeted) non-portable build which is usually a distro maintainer running it via their CI/CD automation using a manifest file. `./build.sh --output-rid ubuntu.24-arm64`. It is as explicit as it comes.

They can also use this helper if providing rid for non-portable build is a pain point:
```sh
#!/bin/sh

_distroId="$(grep -oP '^ID=\K.*' /etc/os-release | tr '[:upper:]' '[:lower:]')"
_version="$(grep -oP '^VERSION_ID="\K[0-9]+' /etc/os-release | tr -d '.')"
arch=$(uname -m | { read -r arch; case $arch in x86_64) echo x64 ;; aarch64) echo arm64 ;; armv7*) echo arm ;; i*86) echo x86 ;; *) echo "$arch" ;; esac; })

_calculated_rid="$_distroId.$_version${_version:+-}$_arch"
```

This will put the responsibility on a small subset of non-portable builders, yes, but it is trivial compared to dotnet infra maintaining the whole list of distros and their preferred style (no version, 1-part version, 2 or 3 parts). This will free them to change the format, and us free from maintenance.

**Comment by tmds** [comment]
> It is not for everyone, only someone doing a (very targeted) non-portable build 

I'm not sure what you mean exactly.

My preference is that a non-portable build uses a non-portable rid, and if a user wants he can control it using the argument. If the argument is not provided, the `/etc/os-release` based non-portable rid gets used.

**Comment by am11** [comment]
> I'm not sure what you mean exactly.

You sounded like as if everyone will have to part --output-rid, and I was clarifying it's not the case, it only applies to non-portable build.

> If the argument is not provided, the /etc/os-release based non-portable rid gets used.

The problem with this is not all distro use the same  scheme which I explained, so we will need to maintain the never-ending mappings. Is this little inconvenience really worth it? I don't think it is and we should just make `--output-rid` mandatory for non-portable builds. The error message can give a few example to help user familiarize with various styles.

To me, the benefits of making the argument mandatory outweigh this convenience.

**Comment by tmds** [comment]
I don't think we should force everyone that does a non-portable to have to understand and pick a rid when the build script can pick a very sensible value for it.

**Comment by am11** [comment]
OK. If your suggestion is to use `$ID.$VERSION-$(uname -m)`, I agree. My rub is when we start maintain this kind of mapping: `distroA => majorVersion, distroB => majorAndMinorVersions, distroC => majorMinorPatchVersions, distroD => noVersion`. That just opens a pandora box.

I think it would be reasonable to make lack of `--output-rid` defaults to just `$ID.$VERSION-$(uname -m)`. WDYT?

**Comment by tmds** [comment]
Yes, what we have left in `init-distro-rid.sh`.

**Comment by tmds** [comment]
It would have been nicer if we had added the argument before removing the special distro handling from `init-distro-rid.sh`.

Now we require maintainers to figure out on their own how to get back to the rid they were building previously.
