### ISSUE TITLE
source-build-sdk-diff-tests failing with `A value for the 'vmrBranch' parameter must be provided`

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4417]
[Failing run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2458085&view=results) (Microsoft internal link)

This is likely fallout from the sdk-installer repo merge.  The tests were just re-enabled in #4396

**Comment by ellahathaway** [comment]
Assigning Viktor since he has a PR out with a fix

**Comment by MichaelSimons** [comment]
Fixed by https://github.com/dotnet/sdk/pull/41090
