### ISSUE TITLE
LicenseScan Tests failed

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4426]
https://github.com/dotnet/sdk/pull/41016 is fixed the issues in runtime repo but caused other issues https://dev.azure.com/dnceng/internal/_build/results?buildId=2456048&view=results in `arcade`, `aspnetcore`, `roslyn-analyzers` and `source-build-reference-packages` repo

`arcade` repo:
[UpdatedLicenses.arcade.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ1NjA0OC9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rYXJjYWRlX0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2FUpdatedLicenses.arcade.json)
[scancode-results.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ1NjA0OC9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rYXJjYWRlX0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2Fscancode-results.json)

`roslyn-analyzers` repo:
[UpdatedLicenseExclusions.roslyn.txt](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ1NjA0OC9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rcm9zbHluX0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2FUpdatedLicenseExclusions.roslyn.txt)
[scancode-results.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ1NjA0OC9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rcm9zbHluX0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2Fscancode-results.json)

**Comment by mthalman** [comment]
@ellahathaway - Can you take a look at this? Something weird is going on. Just looking at the arcade result, I see this in UpdatedLicenses.arcade.json:

```json
{
  "files": [
    {
      "path": "eng/xcopy-msbuild/msbuild.nuspec",
      "detected_license_expression": "ms-visual-2015-sdk"
    }
  ]
}
```

That happens in spite of an exclusion existing for that file: https://github.com/dotnet/dotnet/blob/6a63fb085655a71e23a637cd3d37111a32da1894/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseScanTests/LicenseExclusions.txt#L20

**Comment by ellahathaway** [comment]
Hm, that's very odd. It shouldn't cause an error if the exclusion is listed. I'll investigate.

**Comment by ellahathaway** [comment]
Oh - it's because the linked run is my test run off of my Azdo branch, not the latest run off of main. I think we can close this issue.
