### ISSUE TITLE
SDK Diff pipeline not triggering for branches other than main

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4439]
I noticed that the sdk-diff pipeline has not been running automatically for release/ and internal/release/ branches, as the yaml suggests should happen.

For example, there has not yet been a run of the diff pipeline on release/9.0.1xx-preview5, and the last run on the preview4 branch was 05/11/2024. The latest push to the preview5 branch was today, and the latest push to the preview4 branch was 05/17/2024. Similarly, when the servicing updates were made to the 8.0.1xx branches the other day, no runs of the pipeline were automatically triggered. The results described in https://github.com/dotnet/source-build/issues/4438 were pulled from manually triggered runs of the pipeline against the branches.

**Comment by ellahathaway** [comment]
Quick investigation - the issue is not caused by differing yaml names among the branches (all the branches have the yaml in the same location with the same name).

**Comment by ViktorHofer** [comment]
I see that the cron job only runs for main: https://github.com/dotnet/sdk/blob/ae5c9d322f16aafd16e860c27166bf29216b89ac/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L6

I'm not familiar with [this block](https://github.com/dotnet/sdk/blob/ae5c9d322f16aafd16e860c27166bf29216b89ac/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L8-L18). Does this mean that the sdk-diff-tests pipeline should be triggered when there's a new build triggered from the specified branches in the "dotnet-source-build" pipeline?

**Comment by MichaelSimons** [comment]
The intent is to run the pipeline on a schedule for main but in release branches we would like to run it on every commit.  That is why the cron is for main only and the resource trigger is for release branches.  That all said, I don't understand why this is not working for the preview 5 branch.  It has worked in the past for the preview release branches.  Diffing the pipeline does not yield anything obvious to me.

**Comment by ellahathaway** [comment]
> That all said, I don't understand why this is not working for the preview 5 branch. It has worked in the past for the preview release branches. Diffing the pipeline does not yield anything obvious to me.

I spent some more time digging into this yesterday towards the EOD, and I also don't see anything obvious in the diff. I'm going to try to override the yaml settings from the UI to see if that fixes anything.

**Comment by ellahathaway** [comment]
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops says

```
If your branch filters aren't working, try using the prefix refs/heads/. For example, use refs/heads/releases/old*instead of releases/old*.
```

This might be worth a shot.

**Comment by ellahathaway** [comment]
Opened https://github.com/dotnet/sdk/pull/41350 to try to change the filtering branches. I'm not seeing anything that would've caused this issue to start, so if this change doesn't work, I propose going back to scheduled builds or using the az cli to trigger the sdk diff pipeline from a build in dotnet-source-build pipeline.

**Comment by ellahathaway** [comment]
Closing since the runs are now triggering automatically.
