### ISSUE TITLE
[9.0.1xx-preview5] sdk-dotnet-dotnet-synchronization pipeline failed to apply the patch 0001-fix-fsharp-r2r-rid.patch to src/fsharp

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4440]
`release/9.0.1xx-preview5` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2463816&view=logs&j=ac868591-5f39-5047-4b1f-0ffa6f6c3268&t=97961c92-5b76-590a-3f4c-bdbad6479e18

Error:

    dbug: Executing command: 'git -C /mnt/vss/_work/1/vmr apply --cached --ignore-space-change --directory src/fsharp /mnt/vss/_work/1/vmr/src/sdk/src/SourceBuild/patches/fsharp/0001-fix-fsharp-r2r-rid.patch'
    warn: A new branch was created for the sync and didn't get merged as the sync was interrupted. A new sync should start from release/9.0.1xx-preview5 branch.
    fail: Failed to synchronize repo sdk
          Failed to apply the patch 0001-fix-fsharp-r2r-rid.patch to src/fsharp.
          
          Exit code: 1
          Std err:
          error: patch failed: src/fsharp/Directory.Build.targets:21
          error: src/fsharp/Directory.Build.targets: patch does not apply
          error: patch failed: src/fsharp/buildtools/AssemblyCheck/AssemblyCheck.fsproj:8
          error: src/fsharp/buildtools/AssemblyCheck/AssemblyCheck.fsproj: patch does not apply
          error: patch failed: src/fsharp/buildtools/fslex/fslex.fsproj:9
          error: src/fsharp/buildtools/fslex/fslex.fsproj: patch does not apply
          error: patch failed: src/fsharp/buildtools/fsyacc/fsyacc.fsproj:9
          error: src/fsharp/buildtools/fsyacc/fsyacc.fsproj: patch does not apply
          error: patch failed: src/fsharp/src/fsc/fscProject/fsc.fsproj:11
          error: src/fsharp/src/fsc/fscProject/fsc.fsproj: patch does not apply
          error: patch failed: src/fsharp/src/fsi/fsiProject/fsi.fsproj:11
          error: src/fsharp/src/fsi/fsiProject/fsi.fsproj: patch does not apply

**Comment by ViktorHofer** [comment]
That got fixed with https://github.com/dotnet/sdk/pull/41298
