### ISSUE TITLE
[SB Release] NuGet Auth Issue

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4441]
In the mirroring stage, we use https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v1?view=azure-pipelines to access the artifact feeds. We currently configure a PAT to help us do this, but we should figure out how to remove the use of the PAT.

**Comment by ellahathaway** [comment]
Pinged FR, according to https://learn.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#permissions-table we may have to reconfigure some permissions.

**Comment by ellahathaway** [comment]
Deemed non-fixable by source-build. We will have to continue to ping FR when we need help with this PAT.

**Comment by mthalman** [comment]
This is related to https://github.com/dotnet/source-build/issues/3444. Ideally, we can remove the use of a service connection altogether. Then PAT rotation wouldn't require any further intervention.
