### ISSUE TITLE
[9.0.1xx-preview5] SDK diff tests failing with "Didn't find an SDK archive"

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4442]
`release/9.0.1xx-preview5` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2464539&view=logs&j=c2a3fba4-babc-5882-e82a-8e0dc9edd6ec&t=c2a95e7e-b619-54b2-c512-fcefc49a38ba

Below issues has been fixed in `main` build, but the tests failing in `9.0.1xx-preview5` build now, related to https://github.com/dotnet/source-build/issues/4420:

    /mnt/vss/_work/1/s/Directory.Build.targets(15,5): error : Didn't find an SDK archive. [/mnt/vss/_work/1/s/eng/extract-sdk-archive.proj]

**Comment by MichaelSimons** [comment]
Closing as fixed by https://github.com/dotnet/sdk/pull/41339
