### ISSUE TITLE
[9.0.1xx-preview5] LicenseScanTests failing to upload .trx files

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4443]
Related to https://github.com/dotnet/source-build/issues/4430

[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2465238&view=logs&j=280a01c8-006d-5537-2980-fc0860fb6840&t=8c5c7c98-db07-56c7-5f69-77b9074e6633&l=11):

`Publish Test Results` finished with warning: 

    ##[warning]No test result files matching '[ '*.trx' ]' were found.

**Comment by MichaelSimons** [comment]
Closing as fixed by https://github.com/dotnet/sdk/pull/41340
