### ISSUE TITLE
[internal/8.0.1xx] License scan test run time out for runtime repo

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4447]
`internal/release/8.0.1xx` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2465243&view=logs&j=ab6b9953-d92d-5494-251d-2f65ef31076b&t=85639492-c741-55bd-2122-235bc09e1e75

**Comment by MichaelSimons** [comment]
Closed as fixed by https://github.com/dotnet/installer/pull/19879
