### ISSUE TITLE
[9.0.1xx] License Scan Tests failing for runtime repo

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4460]
`release/9.0.1xx-preview5` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2469681&view=logs&j=ab6b9953-d92d-5494-251d-2f65ef31076b&t=85639492-c741-55bd-2122-235bc09e1e75

    "files": [
      {
        "path": "src/native/external/zlib-ng/cmake/detect-arch.cmake",
        "detected_license_expression": "zlib AND unknown-license-reference"
      },
      {
        "path": "src/native/external/zlib-ng/cmake/detect-coverage.cmake",
        "detected_license_expression": "(apache-2.0 OR other-permissive OR tsl-2020) AND unknown-license-reference"
      },
      {
        "path": "src/native/external/zlib-ng/cmake/detect-intrinsics.cmake",
        "detected_license_expression": "zlib AND unknown-license-reference"
      },
      {
        "path": "src/native/external/zlib-ng/cmake/detect-sanitizer.cmake",
        "detected_license_expression": "zlib AND unknown-license-reference"
      },

[scancode-results.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ2OTY4MS9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rcnVudGltZV9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2Fscancode-results.json),
[UpdatedLicenses.runtime.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ2OTY4MS9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rcnVudGltZV9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2FUpdatedLicenses.runtime.json),
Baseline: [Licenses.runtime.json](https://github.com/dotnet/dotnet/blob/main/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseScanTests/Licenses.runtime.json)

**Comment by mthalman** [comment]
This is known. See https://github.com/dotnet/sdk/pull/41504#issuecomment-2158472272. We won't be addressing this in the preview5 branch since the release is locked down.
