### ISSUE TITLE
Re-enable sdk-diff approval stage

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4461]
Sdk-diff approval stage was disabled with https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/40256

`Mirror` and `Release` stages where being skipped, when sdk-diff run was successful.

Sample build where stages were blocked (skipped): https://dev.azure.com/dnceng/internal/_build/results?buildId=2470263&view=results

**Comment by ellahathaway** [comment]
I have some changes to fix the skipping issue. They haven't been tested due to the release taking priority, but I'll update my branch with these changes once https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/40256 gets merged.

**Comment by ellahathaway** [comment]
This is a bit tricky. Azdo templates do not currently allow for the conditioning of approval gates, meaning that the gate either gets skipped (and subsequent gates that depend on that approval gate also get skipped) or we force approval regardless of the outcome of the SDK diff tests.

I see a few paths forward here:
1) Remove the sdk-diff approval stage entirely and go back to the manual checking of the tests
2) Always force approval for the sdk-diff tests in official runs regardless of the test outcome & warn of failures in test runs
3) Always force approval for the sdk-diff tests in test runs (non-validation) regardless of the test outcome and warn of failures in official runs

I like the 3rd option the best, but I'd like to hear others' thoughts.

cc @dotnet/source-build-internal

**Comment by mthalman** [comment]
@ellahathaway - For the 3rd option, can you describe what the UX would be for the 3 pipeline types (validation, test, official), both for a successful and failed diff result?

**Comment by ellahathaway** [comment]
> I lean towards keeping the Official and Test builds as similar as possible. Is there a compelling reason to skip the approval for Official?

That makes sense. I don't have a very compelling reason to skip the approval stage for official runs other than that it'd be a repeat from the test run. I'm okay with requiring the approval in test and official runs and skipping the approval in validation runs.

**Comment by ellahathaway** [comment]
[PR with fix](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/41216) (internal Microsoft link)
