### ISSUE TITLE
Rebootstrap SDK for VMR build

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/source-build#4466]
Since the last rebootstrapping to a preview6 SDK we started seeing frequent failures during the VMR build with the RestoreTask from nuget: https://github.com/dotnet/sdk/issues/41477

There was a fix in nuget related to that: https://github.com/NuGet/Home/issues/13460
We'd like to rebootstrap again to see if that helps with this issue. The nuget fix flowed into the sdk repo already.

**Comment by ellahathaway** [comment]
Do you have the sdk commit or PR for when the nuget fix flowed in? That'll help me find a build + artifacts to rebootstrap with.

**Comment by akoeplinger** [comment]
@ellahathaway this one: https://github.com/dotnet/sdk/pull/41527

**Comment by ellahathaway** [comment]
Thanks! I'll work get working on a rebootstrap.
