### ISSUE TITLE
VMR servicing - Incremental package servicing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4474]
Runtime has an incremental servicing model which only publishes packages that changed in a given servicing cycle. For the VMR, we are always live building and therefore downstream repos need all runtime packages produced, not just the ones that changed.

We need to come up with a solution to support incremental package servicing. I see a few options:
1. Mark the packages that don't ship in a given servicing non-shipping
2. Let runtime generate a file that lists the packages to ship

There are probably more and I'm not sure if 1) will work.

cc @ericstj @carlossanlop @mmitche

**Comment by ericstj** [comment]
3. Let repo build produce the shipping packages, everything from VMR is just ignored.  That's effectively what source-build does today.  
4. Keep incremental servicing in place and allow downstream repos to restore packages that aren't shipping.

**Comment by ViktorHofer** [comment]
Closing as not planned for the initial release of the VMR as runtime doesn't do incremental servicing anymore and we aren't aware of any other repository that needs such a functionality.
