### ISSUE TITLE
VMR Stage 2 building failed in fsharp with package downgrade

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4477]
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2478805&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7

VMR Stage2 building fsharp failed with the following errors:

      /vmr/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: Detected package downgrade: System.Reflection.Metadata from 9.0.0-preview.6.24319.11 to 8.0.0. Reference the package directly from the project to select a different version. [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/src/fsc/fscProject/fsc.fsproj(0,0): error NU1605: Detected package downgrade: System.Reflection.Metadata from 9.0.0-preview.6.24319.11 to 8.0.0. Reference the package directly from the project to select a different version.
      /vmr/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: fsc -> Microsoft.Build.Tasks.Core 17.11.0-preview-24318-05 -> System.Reflection.Metadata (>= 9.0.0-preview.6.24319.11) [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/src/fsc/fscProject/fsc.fsproj(0,0): error NU1605: fsc -> Microsoft.Build.Tasks.Core 17.11.0-preview-24318-05 -> System.Reflection.Metadata (>= 9.0.0-preview.6.24319.11)
      /vmr/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: fsc -> System.Reflection.Metadata (>= 8.0.0) [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/src/fsc/fscProject/fsc.fsproj(0,0): error NU1605: fsc -> System.Reflection.Metadata (>= 8.0.0)

**Comment by MichaelSimons** [comment]
@ViktorHofer, can you take a look?  TIA.

**Comment by ViktorHofer** [comment]
Interesting. I thought that https://github.com/dotnet/sdk/commit/05abdc5c0746c17290292897ca65a2e92e91f8de would prevent this. I would need to check why msbuild and runtime dependencies are still auto-upgraded.

**Comment by ViktorHofer** [comment]
Fixed via https://github.com/dotnet/fsharp/pull/17344. https://github.com/dotnet/sdk/pull/41788 fixes it for P6.

**Comment by ViktorHofer** [comment]
Reopening until the next source-build(-lite) build is green. The changes still need to flow into sdk.

**Comment by ViktorHofer** [comment]
Closing as fixed
