### ISSUE TITLE
Reduce CI turnaround time: look for low-hanging fruit

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#448]
CI turnaround time for the tarball legs in particular is more than 2 hours. A lot of this is because we've been adding a lot of product to the build, but we should try (briefly) finding some low-hanging fruit.

One thing that comes to mind is that CLI is printing out diag MSBuild output, which helps make our jenkins console output > 200 MB. I don't know if or how much this affects performance. (Doesn't seem to help, tried in https://github.com/dotnet/source-build/issues/448.)

/cc @dseefeld @crummel @dleeapho

**Comment by kasper3** [comment]
or the more recent one: `tmpfs`  https://askubuntu.com/a/173294

https://www.jamescoyle.net/knowledge/951-the-difference-between-a-tmpfs-and-ramfs-ram-disk

**Comment by dagood** [comment]
Interesting ideas, they don't seem to me like low-hanging right now, though.

For `ramfs`, our build expands quite a bit, and I'm not sure what the machine specs are. `tmpfs` looks like it at least wouldn't kill the machine if it doesn't fit. We could try building in `/tmp`, normally set up as a `tmpfs`. Not sure what the repercussions are for building outside the workspace we're given, or if there's some "real" way to do this. I heard a while back that RAM filesystems are less worthwhile recently with fast SSDs, which I'm pretty sure the CI agents use.

Parallelizing sounds nice, but we're pretty limited. At the repo level, we only have the amount of parallel work each repo can support with its toolset. Above that, building entire repos in parallel to each other seems likely to have weird races. (Even if we don't hit any at first, changing the build order or even just slightly different timing could cause one.) Maybe we could be more sure if we broke the build down into a bunch of isolated Docker container builds. Even then, our long pole is CoreCLR => CoreFX => Core-Setup => FSharp => CLI, and these are our longest individual builds anyway.
