### ISSUE TITLE
The new netstandard1.x warning fails the stage2 build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4481]
At least SBRP, but probably also a few other repos.

Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2481839&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7

I'm investigating...

**Comment by MichaelSimons** [comment]
Fixed by https://github.com/dotnet/source-build-reference-packages/pull/973.  Still needs to flow into the SDK repo.
