### ISSUE TITLE
SBRP CI Failing to Publish Using Darc

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4483]
Our SBRP pipeline encounters an error when attempting to publish using darc:

```bash
fail: Error: Failed to assign build '230169' to channel ''.
      Azure.Identity.CredentialUnavailableException: Please run 'az login' to set up account
```

[Link to failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=2483073&view=logs&j=d17d50ef-afac-5d4b-95a6-3014ce5cf7a4&t=1c75297b-9215-5569-8bf5-00b624c647d3&l=18) (internal Microsoft link)

We suspect that this was an issue with the way we are configuring an arcade template to publish using darc.

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
Note that fixing this is important to fix the currently failing source build pipelines.

**Comment by ellahathaway** [comment]
Found the issue:

I noticed that https://github.com/dotnet/arcade/pull/14880/files changed the [`Publish Using Darc` task](https://github.com/dotnet/arcade/pull/14880/files#diff-7497e1a0ab3f97cf070d583c20ebde8deea806c58a17e8f8a8373fc568901e27R303-R309) in `eng/common/core-templates/post-build/post-build.yml` to use the AzureCLI. This is not the template we use, but it is the same command.

This same change was not ported to the [`Publish Using Darc` task](https://github.com/dotnet/arcade/pull/14880/files#diff-02566fa472aae261a77ce16e1282063deda281ada97bc5e26b7e8386c204584dR158-R167) in `eng/common/core-`templates/job/publish-build-assets.yml`. This is the template we use & the task that's failing.

Changing the task in `eng/common/core-`templates/job/publish-build-assets.yml` to use the AzureCLI task fixed the issue. I'll open a PR in arcade.
