### ISSUE TITLE
VMR Credential Scanner failed

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4486]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2485815&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca&t=d1aba2c3-5b21-511d-f336-affeabd629f9) (internal Microsoft link)

`Guardian: Post Analysis` failed:

    ##[error]141. Credential Scanner Error CSCAN-GENERAL0020 - File: src/runtime/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/TestData.cs. Line: 2745. Column 1. 
    Signature: 021fed5848180fe5621ad74694ec18568bec71289fa7d8451a52b4d758264428
    Tool: Credential Scanner: Rule: CSCAN-GENERAL0020 (Found X.509 Certificate Private Key.). 
    {Searcher}CSCAN-GENERAL0020
    {Code}See TestData.cs line 2745 for the code resulting in match
    {Info}Found X.509 Certificate Private Key.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]142. Credential Scanner Error CSCAN-GENERAL0020 - File: src/runtime/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/TestData.cs. Line: 2881. Column 1. 
    Signature: 3ede7dcbf68154b1d70720520f28286d2f23e67941ea8c61975ecce559bdc7eb
    Tool: Credential Scanner: Rule: CSCAN-GENERAL0020 (Found X.509 Certificate Private Key.). 
    {Searcher}CSCAN-GENERAL0020
    {Code}See TestData.cs line 2881 for the code resulting in match
    {Info}Found X.509 Certificate Private Key.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]143. Credential Scanner Error CSCAN-GENERAL0020 - File: src/runtime/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/TestData.cs. Line: 2964. Column 1. 
    Signature: 99ae1c49501757abc08f033236305eb273f96f58e4f636d38c4a4fa81fc15980
    Tool: Credential Scanner: Rule: CSCAN-GENERAL0020 (Found X.509 Certificate Private Key.). 
    {Searcher}CSCAN-GENERAL0020
    {Code}See TestData.cs line 2964 for the code resulting in match
    {Info}Found X.509 Certificate Private Key.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan

**Comment by mthalman** [comment]
I see some work was done in https://github.com/dotnet/runtime/pull/104086 as part of addressing credscan issues. But I don't see any suppressions for these particular failures. Not sure why runtime isn't encountering these. /cc @akoeplinger

**Comment by akoeplinger** [comment]
> But these suppressions for the private keyes are not new so I'm a bit confused why this only shows up now?

Ah I know why, we suppressed them in the VMR via
Looks likehttps://github.com/dotnet/sdk/blob/main/src/SourceBuild/content/.config/guardian/.gdnbaselines#L1004-L1031

**Comment by Winniexu01** [comment]
Reopen the issue, the [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2487715&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca&t=d1aba2c3-5b21-511d-f336-affeabd629f9) (internal Microsoft link) is still failed with new credential scanner errors:

    ##[error]1. Credential Scanner Error CSCAN-GENERAL0130 - File: src/aspire/tests/Aspire.Dashboard.Tests/Integration/OtlpServiceTests.cs. Line: 128. Column 1. 
    Signature: 0a527cd60eacba9f7c0c83e3a97e25270578b40a637372cdf80b702b9b87b261
    Tool: Credential Scanner: Rule: CSCAN-GENERAL0130 (Found Client Secret / Api Key.). 
    {Searcher}CSCAN-GENERAL0130
    {Code}See OtlpServiceTests.cs line 128 for the code resulting in match
    {Info}Found Client Secret / Api Key.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]2. Credential Scanner Error CSCAN-MSFT0090 - File: src/aspire/tests/Aspire.Hosting.Tests/RabbitMQ/AddRabbitMQTests.cs. Line: 66. Column 1. 
    Signature: 6ddef357a244a95890f464728bfe7d498172c7d0a154a1b7505de8cf5d2e6940
    Tool: Credential Scanner: Rule: CSCAN-MSFT0090 (Found Internal Common Default Password.). 
    {Searcher}CSCAN-MSFT0090
    {Code}See AddRabbitMQTests.cs line 66 for the code resulting in match
    {Info}Found Internal Common Default Password.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]3. Credential Scanner Error CSCAN-MSFT0090 - File: src/aspire/tests/Aspire.Hosting.Tests/RabbitMQ/AddRabbitMQTests.cs. Line: 81. Column 1. 
    Signature: 7b17c8b64bd83dc326d4257677bed760c9cf6ab817acfbc7472f13f64b855e40
    Tool: Credential Scanner: Rule: CSCAN-MSFT0090 (Found Internal Common Default Password.). 
    {Searcher}CSCAN-MSFT0090
    {Code}See AddRabbitMQTests.cs line 81 for the code resulting in match
    {Info}Found Internal Common Default Password.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]4. Credential Scanner Error CSCAN-MSFT0090 - File: src/aspire/tests/Aspire.Hosting.Tests/SqlServer/AddSqlServerTests.cs. Line: 76. Column 1. 
    Signature: 5c2b6a4651bcb596fc2e5db714b851d389abfea6e55903a8d0582ce51da047ff
    Tool: Credential Scanner: Rule: CSCAN-MSFT0090 (Found Internal Common Default Password.). 
    {Searcher}CSCAN-MSFT0090
    {Code}See AddSqlServerTests.cs line 76 for the code resulting in match
    {Info}Found Internal Common Default Password.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]5. Credential Scanner Error CSCAN-MSFT0090 - File: src/aspire/tests/Aspire.Hosting.Tests/SqlServer/AddSqlServerTests.cs. Line: 84. Column 1. 
    Signature: 80a85deb6369e399563ca12ec488875ae9fadc6a4c8d4a4343fe2294ddf2a7a4
    Tool: Credential Scanner: Rule: CSCAN-MSFT0090 (Found Internal Common Default Password.). 
    {Searcher}CSCAN-MSFT0090
    {Code}See AddSqlServerTests.cs line 84 for the code resulting in match
    {Info}Found Internal Common Default Password.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]6. Credential Scanner Error CSCAN-MSFT0090 - File: src/aspire/tests/Aspire.Hosting.Tests/SqlServer/AddSqlServerTests.cs. Line: 100. Column 1. 
    Signature: 0b30610f2eb9817ff650cd53154bc2ac98d6209750a9d628c5af700608bdb36e
    Tool: Credential Scanner: Rule: CSCAN-MSFT0090 (Found Internal Common Default Password.). 
    {Searcher}CSCAN-MSFT0090
    {Code}See AddSqlServerTests.cs line 100 for the code resulting in match
    {Info}Found Internal Common Default Password.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan 
    ##[error]7. Credential Scanner Error CSCAN-GENERAL0020 - File: src/aspire/tests/Shared/TestCertificates/eku.client.pfx. Line: 1. Column 1. 
    Signature: 52cfa490ade643a3ec287dec67888d444752a73f7e4355a7f1924b0af54df466
    Tool: Credential Scanner: Rule: CSCAN-GENERAL0020 (Found X.509 Certificate Private Key.). 
    {Searcher}CSCAN-GENERAL0020
    {Code}See eku.client.pfx line 1 for the code resulting in match
    {Info}Found X.509 Certificate Private Key.
    {Suggest}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan

**Comment by akoeplinger** [comment]
Will be fixed by https://github.com/dotnet/sdk/pull/41943
