### ISSUE TITLE
LicenseScan Tests failing for runtime repo

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4488]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2485829&view=logs&j=ab6b9953-d92d-5494-251d-2f65ef31076b&t=85639492-c741-55bd-2122-235bc09e1e75) (internal Microsoft link):

    "files": [
      {
        "path": "src/mono/browser/runtime/package-lock.json",
        "detected_license_expression": "mit AND apache-2.0 AND bsd-new AND bsd-simplified AND python AND lgpl-3.0"
      },

Related to https://github.com/dotnet/runtime/pull/103639/files#diff-dc8a990f55517fbcdeb08a4d6890e6dc9a5936b08a9353c65847a494e2a22ee4

[Licenses.runtime.json](https://github.com/dotnet/sdk/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseScanTests/Licenses.runtime.json)
[UpdatedLicenses.runtime.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ4NTgyOS9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rcnVudGltZV9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2FUpdatedLicenses.runtime.json)
[scancode-results.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ4NTgyOS9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rcnVudGltZV9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2Fscancode-results.json)

**Comment by ellahathaway** [comment]
I was wondering why the PR Creator did not publish these test results, and I discovered that it's failing to install the .NET SDK. The errors in the tool when installing the SDK are also showing up in [this SBRP PR](https://github.com/dotnet/source-build-reference-packages/pull/975).

- [SBRP PR failures](https://dev.azure.com/dnceng-public/public/_build/results?buildId=726078&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=4607427e-2085-572d-4b25-975ef0413f8f&l=47) (internal Microsoft link)
- [PR Creator tool failures](https://dev.azure.com/dnceng/internal/_build/results?buildId=2485829&view=logs&j=057183d2-e4ce-52e2-9404-d461bafbc739&t=adcf3ae5-75b0-5363-1643-f37048afcf25&l=13) (internal Microsoft link)

I opened https://github.com/dotnet/source-build/issues/4490 in response to this.
