### ISSUE TITLE
VMR Stage2 build failed

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4492]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2487651&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7) (internal Microsoft link)

    /vmr/src/templating/src/Microsoft.TemplateEngine.Core.Contracts/Microsoft.TemplateEngine.Core.Contracts.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Abstractions does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateSearch.Common/Microsoft.TemplateSearch.Common.csproj : error NU1604: Warning As Error: Project dependency Newtonsoft.Json does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateSearch.Common/Microsoft.TemplateSearch.Common.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Abstractions does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Utils/Microsoft.TemplateEngine.Utils.csproj : error NU1604: Warning As Error: Project dependency Microsoft.Extensions.Logging.Abstractions does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Utils/Microsoft.TemplateEngine.Utils.csproj : error NU1604: Warning As Error: Project dependency Newtonsoft.Json does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Utils/Microsoft.TemplateEngine.Utils.csproj : error NU1701: Warning As Error: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateSearch.Common/Microsoft.TemplateSearch.Common.csproj : error NU1701: Warning As Error: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.csproj : error NU1604: Warning As Error: Project dependency Newtonsoft.Json does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Abstractions does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Utils does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.csproj : error NU1701: Warning As Error: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Core/Microsoft.TemplateEngine.Core.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Abstractions does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Core/Microsoft.TemplateEngine.Core.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Utils does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Core/Microsoft.TemplateEngine.Core.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Utils does not provide an inclusive lower bound for dependency Newtonsoft.Json. An approximate best match of Newtonsoft.Json 3.5.8 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Core/Microsoft.TemplateEngine.Core.csproj : error NU1701: Warning As Error: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Abstractions/Microsoft.TemplateEngine.Abstractions.csproj : error NU1604: Warning As Error: Project dependency Microsoft.Extensions.Logging.Abstractions does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Abstractions does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Edge does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Utils does not provide an inclusive lower bound for dependency Microsoft.Extensions.Logging.Abstractions. An approximate best match of Microsoft.Extensions.Logging.Abstractions 1.0.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Edge does not provide an inclusive lower bound for dependency Newtonsoft.Json. An approximate best match of Newtonsoft.Json 3.5.8 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Orchestrator.RunnableProjects does not provide an inclusive lower bound for dependency Newtonsoft.Json. An approximate best match of Newtonsoft.Json 3.5.8 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Utils does not provide an inclusive lower bound for dependency Newtonsoft.Json. An approximate best match of Newtonsoft.Json 3.5.8 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Edge does not provide an inclusive lower bound for dependency NuGet.Configuration. An approximate best match of NuGet.Configuration 3.2.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Edge does not provide an inclusive lower bound for dependency NuGet.Credentials. An approximate best match of NuGet.Credentials 4.4.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1602: Warning As Error: Microsoft.TemplateEngine.Edge does not provide an inclusive lower bound for dependency NuGet.Protocol. An approximate best match of NuGet.Protocol 4.3.0 was resolved. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1604: Warning As Error: Project dependency Microsoft.Extensions.Logging.Abstractions does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1604: Warning As Error: Project dependency Newtonsoft.Json does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1604: Warning As Error: Project dependency NuGet.Configuration does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1604: Warning As Error: Project dependency NuGet.Credentials does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1604: Warning As Error: Project dependency NuGet.Protocol does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1701: Warning As Error: Package 'Microsoft.Web.Xdt 2.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1701: Warning As Error: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1701: Warning As Error: Package 'Microsoft.Web.Xdt 2.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1701: Warning As Error: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1701: Warning As Error: Package 'NuGet.Configuration 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1701: Warning As Error: Package 'NuGet.Credentials 4.4.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1701: Warning As Error: Package 'NuGet.Configuration 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1701: Warning As Error: Package 'NuGet.Credentials 4.4.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.IDE/Microsoft.TemplateEngine.IDE.csproj : error NU1701: Warning As Error: Package 'NuGet.PackageManagement 4.4.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
    /vmr/src/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj : error NU1701: Warning As Error: Package 'NuGet.PackageManagement 4.4.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/vmr/src/templating/Microsoft.TemplateEngine.sln]
        0 Warning(s)
        40 Error(s)

**Comment by ellahathaway** [comment]
Followed up in https://github.com/dotnet/source-build/issues/4487#issuecomment-2207202453 since this discussion was partially occurring there as well.

**Comment by tmds** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
This will get fixed with https://github.com/dotnet/sdk/pull/41976 (https://github.com/dotnet/templating/commit/c3ab97f976154f6ddd0bd2fba89f52134a91c2cc)

**Comment by Winniexu01** [comment]
The [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2489030&view=logs&j=9f4c4083-9864-5575-dedd-fb296084d8e2&t=57338db5-dbe1-5b87-71dd-1b46625917ea) (internal Microsoft link) is green, close the issue.
