### ISSUE TITLE
VMR Stage 2 Builds Failing in Arcade with Obsolete Reference

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4494]
[The latest run of the VMR](https://dev.azure.com/dnceng/internal/_build/results?buildId=2490576&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7&l=663) is failing stage 2 builds with the following error:

```bash
/vmr/src/arcade/src/Microsoft.DotNet.SignTool/src/VerifySignatures.cs(104,42): error SYSLIB0057: 'X509Certificate.CreateFromSignedFile(string)' is obsolete: 'Loading certificate data through the constructor or Import is obsolete. Use X509CertificateLoader instead to load certificates.' (https://aka.ms/dotnet-warnings/SYSLIB0057) [/vmr/src/arcade/src/Microsoft.DotNet.SignTool/Microsoft.DotNet.SignTool.csproj::TargetFramework=net9.0]
##[error]/vmr/src/arcade/src/Microsoft.DotNet.SignTool/src/VerifySignatures.cs(104,42): error SYSLIB0057: (NETCORE_ENGINEERING_TELEMETRY=Build) 'X509Certificate.CreateFromSignedFile(string)' is obsolete: 'Loading certificate data through the constructor or Import is obsolete. Use X509CertificateLoader instead to load certificates.' (https://aka.ms/dotnet-warnings/SYSLIB0057)
```

This error is the result of [these changes](https://github.com/dotnet/runtime/pull/104165) being brought in by https://github.com/dotnet/sdk/pull/41988.

We need to update the code in `arcade/src/Microsoft.DotNet.SignTool/src/VerifySignatures.cs` to remove the obsolete reference.

**Comment by ellahathaway** [comment]
From https://github.com/dotnet/docs/issues/41662:

> If you are loading X.509 content, X509CertificateLoader.LoadCertificate and X509CertificateLoader.LoadCertificateFromFile can be used.

**Comment by ViktorHofer** [comment]
Oh nice, the next breaking change. @ellahathaway will you take care of it or should I?

**Comment by ellahathaway** [comment]
> Oh nice, the next breaking change. @ellahathaway will you take care of it or should I?

@ViktorHofer Ikr. I've got this one, but thanks for offering to help :)
