### ISSUE TITLE
Core-Setup sometimes fails to build

### ISSUE THREAD

**Issue by chcosta** [dotnet/source-build#45]
I encountered an error building core-setup from a clean source-build repo.  The error was exactly the error described in https://github.com/dotnet/core-setup/issues/1461.

Initially I tried to delete the obvious things like "artifacts", ".dotnet_stage0", all "project.lock.json" files, all "bin" and "obj" directories.  My build still failed.  After finding the linked core-setup issue, I ran "git clean -xdf" and my build passed.  

"git clean -xdf" may be a workable solution when building the core-setup repo, but in a source-build world where git is not available, we will need some other solution.  Additionally, a flakey build late in the build phases is going to be extremely troublesome.

/cc @ellismg

**Comment by karajas** [comment]
Not reproed.
