### ISSUE TITLE
[release/6.0.1xx] Building sdk fails non-deterministically

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4500]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2491583&view=logs&j=cd18f07a-0eff-5b1f-ddc2-be2e681458a1&t=7030a823-c29b-57ab-10e4-fa6ba4280626) (internal Microsoft link)

Building sdk fails for `Build_Tarball_x64 CentOSStream9-Offline` because of a race condition:

    /tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Tasks/Microsoft.NET.Sdk.Razor.Tasks.csproj(107,5): error MSB3026: Could not copy "/tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props" to "/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props". Beginning retry 1 in 1000ms. The process cannot access the file '/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props' because it is being used by another process. 
    /tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Tasks/Microsoft.NET.Sdk.Razor.Tasks.csproj(107,5): error MSB3026: Could not copy "/tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props" to "/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props". Beginning retry 1 in 1000ms. The process cannot access the file '/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props' because it is being used by another process. 
    /tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Tasks/Microsoft.NET.Sdk.Razor.Tasks.csproj(107,5): error MSB3026: Could not copy "/tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Sdk/Sdk.props" to "/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.props". Beginning retry 1 in 1000ms. The process cannot access the file '/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.props' because it is being used by another process. 
    /tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Tasks/Microsoft.NET.Sdk.Razor.Tasks.csproj(107,5): error MSB3026: Could not copy "/tarball/src/sdk/artifacts/source-build/self/src/src/RazorSdk/Sdk/Sdk.props" to "/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.props". Beginning retry 1 in 1000ms. The process cannot access the file '/tarball/src/sdk/artifacts/source-build/self/src/artifacts/bin/Release/Sdks/Microsoft.NET.Sdk.Razor/Sdk/Sdk.props' because it is being used by another process.

**Comment by ellahathaway** [comment]
Note that this happens for 6.0.131 (May release)

**Comment by MichaelSimons** [comment]
[Triage]  Re-running got a passing build.  Given this is incremental, something we don't see in 8.0 and main, and that 6.0 is EOL in Nov we will close with no plans to investigate/fix.
