### ISSUE TITLE
The patching guidelines doc needs an update

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/source-build#4505]
https://github.com/dotnet/source-build/blob/main/Documentation/patching-guidelines.md

It still mentions steps involving dotnet/installer but that repo is no longer useful. I am not sure what the replacement steps should be for the sdk repo instead (or this repo).

**Comment by MichaelSimons** [comment]
For .NET 9+, the patches would be checked into the sdk repo.  When updating the document, it should have versioned guidance added as the document is intended to serve all in-support versions.  e.g. for .NET 8.0 do this, for .NET 9.0+ do this.
