### ISSUE TITLE
Update to latest ScanCode version

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4506]
The [current version of ScanCode being used](https://github.com/dotnet/sdk/blob/f954c28f215047f324f9bf6606cc11cff05e40ef/eng/install-scancode.sh#L8) is out of date and needs to be updated to the latest version: https://github.com/nexB/scancode-toolkit/releases.

This needs to be backported to servicing branches as well.

**Comment by ellahathaway** [comment]
https://github.com/dotnet/sdk/pull/42079 and https://github.com/dotnet/installer/pull/19984 update scancode in sdk and installer. I haven't had the opportunity to investigate the failing runtime tests yet, but I should get to it today.
