### ISSUE TITLE
SDK diff failing for Alma Linux 8

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4509]
It's searching for a source built SDK tarball containing `almalinux.8-x64` but the actual tarball name contains `almalinux.8.10-x64`.

[Failed build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2493926&view=logs&j=2de8b33d-5181-5b3b-35a7-96ee607d2e7f&t=a4cf1e3e-cfd0-5fd1-b28b-36fe5b4e8a70) (internal link)

Regression from https://github.com/dotnet/sdk/pull/42106

**Comment by Winniexu01** [comment]
Reopen this issue. The [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2495978&view=logs&j=2de8b33d-5181-5b3b-35a7-96ee607d2e7f&t=50f427d6-f782-5336-abd1-4866be2a53ac) (internal Microsoft link) in VMR still failing with incorrect tarball name `almalinux.8-x64`

**Comment by mthalman** [comment]
Ah, I didn't realize we had backported an AlmaLinux build leg to 8.0. I'll get my fix backported as well then.
