### ISSUE TITLE
VMR Stage 2 Builds Failing in Runtime with Python not found

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4513]
[Failing build in VMR](https://dev.azure.com/dnceng/internal/_build/results?buildId=2495813&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7) (internal Microsoft link) failing in `runtime` with error:

    /vmr/src/runtime/eng/python.targets(28,7): error : Python not found. Please add Python 3 to your path and try again. [/vmr/src/runtime/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]

**Comment by Winniexu01** [comment]
Reopen this issue, the [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2496361&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7) in VMR fails.

**Comment by mthalman** [comment]
This is an odd issue. The behavior is very inconsistent. The [logic which checks for Python installation](https://github.com/dotnet/runtime/blob/main/eng/python.targets) hasn't been changed in a very long time. It just executes this command: `command -v python3 || command -v python || command -v py`. The container in which this executes definitely has Python installed and always has. The only possible explanation I have is that there is some weird MSBuild behavior where the [command output](https://github.com/dotnet/runtime/blob/8602bb3b4003dbf5187385f58b29bd87e9468670/eng/python.targets#L24) isn't getting set correctly from the `Exec` task. /cc @rainersigwald

**Comment by mthalman** [comment]
![image](https://github.com/user-attachments/assets/842dc938-762a-470e-bc4b-fc99ea2177e2)

**Comment by rainersigwald** [comment]
Almost certainly https://github.com/dotnet/msbuild/issues/10378

cc @MichalPavlik

**Comment by MichaelSimons** [comment]
The msbuild change that caused this was reverted and flowed into the VMR with https://github.com/dotnet/dotnet/commit/445936c27d981124b437fde2c56052c108ab3bed.  Closing issue.
