### ISSUE TITLE
msbuild fails from invalid LoggingContext

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4515]
```
    MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTemproot/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
    MSBUILD : error MSB4166: /tmp/MSBuildTemproot/MSBuild_pid-86765_ae807cc80b1b4d5e9b44616aba701e05.failure.txt:
    MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 86765:
    MSBUILD : error MSB4166: =====================
    MSBUILD : error MSB4166: 07/16/2024 10:54:06
    MSBUILD : error MSB4166: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: LoggingContext (type: Microsoft.Build.BackEnd.Logging.TaskLoggingContext) was not valid during logging attempt.
    MSBUILD : error MSB4166:    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
    MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Logging.LoggingContext.CheckValidity()
    MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Logging.LoggingContext.LogBuildEvent(BuildEventArgs buildEvent)
    MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args)
    MSBUILD : error MSB4166: ===================
```

[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2495880&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7) (internal link)

[binlog](https://github.com/user-attachments/files/16250114/vstest.zip)

This seems related to https://github.com/dotnet/msbuild/pull/10348. The issue was introduced between these commits: https://github.com/dotnet/msbuild/compare/bcfd010eb81cb552feeb52156479c8d9abd21502...0be32ba36269fa53702d6dea02a24bcc9d1410e5
/cc @JanKrivanek

**Comment by JanKrivanek** [comment]
@mthalman - can you please help me locating a matching vstest.binlog for a successful build?

**Comment by mthalman** [comment]
> @mthalman - can you please help me locating a matching vstest.binlog for a successful build?

[vstest-success.zip](https://github.com/user-attachments/files/16255333/vstest-success.zip)

**Comment by mthalman** [comment]
FWIW, this issue is intermittent. It's popped up in all sorts of builds, never consistently.

**Comment by ellahathaway** [comment]
I haven't seen this issue resurface since we rebootstrapped. Because of that, I'm closing this issue.
