### ISSUE TITLE
SBRP CG alerts for System.Formats.Asn1.6.0.0 in 8.0 and main

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4518]
See [8.0](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-source-build-reference-packages/alert/9969521?typeId=17099473) and [main](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-source-build-reference-packages/alert/9969521?typeId=10885472) alerts.

We should upgrade System.Formats.Asn1 from 6.0.0 to 6.0.1 to fix the vulnerability.

**Comment by mthalman** [comment]
This stems from Arcade's dependencies. Arcade has the same CG alert. IMO, the right thing to do is to wait for Arcade to be updated and then upgrade our Arcade dependency.

**Comment by mthalman** [comment]
Oh, never mind. This is because this package version is defined as a package in SBRP. Sorry, we had a similar alert for the docker repos and I thought this was the same thing.

**Comment by ellahathaway** [comment]
The alert has resolved for main builds using linux, but the main builds for windows still show the alerts; it turns out that our test projects reference a version of Nuget.Packaging that uses asn1 6.0.0. This only appears in the windows builds because the CG detection gets skipped for test projects in linux builds.

To resolve this, we could bump the version of Nuget.Packaging, but I worry about it introducing a prebuilt. If I bump Nuget.Packaging to a version that doesn't require asn1.6.0.0, would I also have to add that version of Nuget.Packaging as a ref package in the repo?
