### ISSUE TITLE
CentOS9 mono time out in VMR

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4520]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2498132&view=logs&j=a5ccaa14-6811-5159-45fe-06b91679b5f1&t=bfe7fb12-3e92-5a9e-a5b9-1cf73ee8fba4) (internal Microsoft link)

The task `Run Tests` is timing out in CentOS9 mono leg:

    ##[error]The task has timed out.

**Comment by ellahathaway** [comment]
Failed again on retry.

**Comment by ellahathaway** [comment]
```
docker run --rm -v /mnt/vss/_work/1/a/dotnet-sources/:/vmr -w /vmr mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9 ./build.sh --test --excludeCIBinarylog /bl:artifacts/log/Release/Test.binlog --source-only /p:SmokeTestsWarnOnSdkContentDiffs=true /p:SmokeTestsExcludeOmniSharpTests=True
```

Is there a reason we don't produce the trx file as part of the scenario tests? Publishing the test results would be helpful to diagnose if this timeout is related to a test failure or not... going through the individual binlogs is quite time consuming.

cc @mthalman

**Comment by mthalman** [comment]
There is a test output file: https://github.com/dotnet/dotnet/blob/5b7c2cf312c1c69c6bb780ecae802d7145b03490/repo-projects/scenario-tests.proj#L35. It's xUnit XML test format, not trx. But AzDO is capable of parsing either.

But if there's a timeout, no log file gets produced (xml/trx or otherwise).

**Comment by ellahathaway** [comment]
I'm not able to repro the timeout issue locally. I'm continuing to investigate.

**Comment by ellahathaway** [comment]
It didn't time out on a new build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2498486&view=logs&j=a5ccaa14-6811-5159-45fe-06b91679b5f1&t=bfe7fb12-3e92-5a9e-a5b9-1cf73ee8fba4

**Comment by ellahathaway** [comment]
I am unable to repro this locally or in CI. Here is an[ example of a build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2500013&view=logs&j=541ad6af-b63e-5da0-de3e-7ac5f21531ca) that I did based on the same VMR commit where the test originally timed out. I'm closing this issue as a result. If the issue resurfaces we can reopen.
