### ISSUE TITLE
Secrets download failing for `dnceng-pipeline-secrets`

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4525]
This issue affects multiple platforms: 

[sdk-dotnet-dotnet-synchronization](https://dev.azure.com/dnceng/internal/_build/results?buildId=2501234&view=logs&j=f94b1352-8074-534d-f024-dae8a910f9a5&t=4c33ede4-7067-5a41-05f9-762be89e23fb) in Main and preview7:

    Downloading secret value for: BotAccount-dotnet-maestro-bot-no-scopes-PAT.
    ##[error]
    BotAccount-dotnet-maestro-bot-no-scopes-PAT: "Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=***;oid=e54fa0b4-a8bd-4a5a-8685-331cf8457e87;iss=[https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/\r\nAction](https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47//r/nAction): 'Microsoft.KeyVault/vaults/secrets/getSecret/action'\r\nResource: '/subscriptions/a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1/resourcegroups/keyvaults/providers/microsoft.keyvault/vaults/dnceng-pipeline-secrets/secrets/botaccount-dotnet-maestro-bot-no-scopes-pat'\r\nAssignment: (not found)\r\nDenyAssignmentId: null\r\nDecisionReason: null \r\nVault: dnceng-pipeline-secrets;location=westus2\r\n. The specified Azure service connection needs to have Get, List secret management permissions on the selected key vault. To set these permissions, download the ProvisionKeyVaultPermissions.ps1 script from build/release logs and execute it, or set them from the Azure portal."
    
[SBRP](https://dev.azure.com/dnceng/internal/_build/results?buildId=2501043&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=bc53115d-ed93-59a3-5103-835417fbe7cd) in Main and 8.0:

    Downloading secret value for: dotnetcli-storage-key.
    Downloading secret value for: dotnetclichecksums-storage-key.
    Uploading D:\a\_work\1\ProvisionKeyVaultPermissions.ps1 as attachment
    ##[error]
    dotnetclichecksums-storage-key: "Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=***;oid=e54fa0b4-a8bd-4a5a-8685-331cf8457e87;iss=[https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/\r\nAction](https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47//r/nAction): 'Microsoft.KeyVault/vaults/secrets/getSecret/action'\r\nResource: '/subscriptions/a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1/resourcegroups/keyvaults/providers/microsoft.keyvault/vaults/dnceng-pipeline-secrets/secrets/dotnetclichecksums-storage-key'\r\nAssignment: (not found)\r\nDenyAssignmentId: null\r\nDecisionReason: null \r\nVault: dnceng-pipeline-secrets;location=westus2\r\n. The specified Azure service connection needs to have Get, List secret management permissions on the selected key vault. To set these permissions, download the ProvisionKeyVaultPermissions.ps1 script from build/release logs and execute it, or set them from the Azure portal."
    dotnetcli-storage-key: "Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=***;oid=e54fa0b4-a8bd-4a5a-8685-331cf8457e87;iss=[https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/\r\nAction](https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47//r/nAction): 'Microsoft.KeyVault/vaults/secrets/getSecret/action'\r\nResource: '/subscriptions/a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1/resourcegroups/keyvaults/providers/microsoft.keyvault/vaults/dnceng-pipeline-secrets/secrets/dotnetcli-storage-key'\r\nAssignment: (not found)\r\nDenyAssignmentId: null\r\nDecisionReason: null \r\nVault: dnceng-pipeline-secrets;location=westus2\r\n. The specified Azure service connection needs to have Get, List secret management permissions on the selected key vault. To set these permissions, download the ProvisionKeyVaultPermissions.ps1 script from build/release logs and execute it, or set them from the Azure portal."

**Comment by MichaelSimons** [comment]
@ellahathaway can you investigate?  TIA

**Comment by ellahathaway** [comment]
Looks like the pipelines are now passing on retry, so I'm closing this issue.
