### ISSUE TITLE
Reduce Developer Time Spent on Artifact Size Tests

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4528]
Based on https://github.com/dotnet/source-build/issues/4517
Related to https://github.com/dotnet/source-build/issues/4475

We've made some improvements to the time we're spending on getting green sdk-diff-test pipeline runs, but we are still spending a good amount of time investigating the diffs when changes occur. We should try to cut down on this time.

For the artifact size tests, here are some proposed solutions:
- Only look for artifacts that were previously non-zero sized and are now zero-sized (but not deleted).
- Push this test onto the product repos. As a product developer, I would want to know how my changes affect the product. Generally, product developers would know how their changes should impact the size. If something is unexpected regarding the size, they can know and address it themselves.
- Check sizes of larger/bundled artifacts (e.g., check the size of the entire `packs/` rather than the sizes of each individual artifact inside of `packs/`).

**Comment by ellahathaway** [comment]
Here is a proposed plan of attack to solve this issue:

1) Break this test into two sub-tests (this stays in the source-build context):
   1) Test 1: Check for individual artifacts that are now zero-sized
   2) Test 2: Check the size of larger artifacts. We would keep the implementation of only alerting for size changes of more than 25%.
2) Push the current implementation of this test (checking the size of each individual artifact) onto the product repos

For 1) the source-build developers would still maintain baselines, but the hope is that the baselines would be updated less frequently.

For 2) we could include the baseline as part of the arcade infra. The test would run as part of the source-build managed job for each repo. If the test fails, the product develops would be alerted to the failure and would have to update the baseline.

cc @MichaelSimons @mthalman @omajid

**Comment by MichaelSimons** [comment]
> 1. Break this test into two sub-tests (this stays in the VMR source-build context):
>    
>    1. Test 1: Check for individual artifacts that are now zero-sized
>    2. Test 2: Check the size of larger artifacts. We would keep the implementation of only alerting for size changes of more than 25%.
> 2. Push the current implementation of this test (checking the size of each individual artifact) onto the product repos

1.i makes sense
1.ii I think this is going to have minimal ROI  I am not keen on the reactionary tasks we would still have from this type of test.  At this point I am not in favor of this.
2. I have a feeling this is going to receive pushback from the product teams.  It is not going to have worthwhile ROI.  I don't see this as something we should push on.  I definitely don't want to see this as a source-build only test.
