### ISSUE TITLE
Establish Guidelines for Retaining Artifacts in Blob Storage

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4530]
Related to https://github.com/dotnet/source-build/issues/4511

We should aim to keep only necessary artifacts in the blob storage. As part of this issue, we should identify which artifacts are necessary and establish guidelines for what should be retained in the blob storage. We should also investigate strategies for cleaning up unnecessary artifacts in the official blob storage.

**Comment by MichaelSimons** [comment]
[Triage] This would need to be automated given the restricted access to blob storage.  There is minimal ROI from this clean given the cost to automate.  Closing as won't fix.
