### ISSUE TITLE
Investigate zero-sized file `nonportable.txt` in sdk tarball

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4533]
See https://github.com/dotnet/sdk/pull/42447#discussion_r1696990801

In refactoring the artifact size test to detect zero-sized files in the sdk, it was uncovered that we produce this zero-sized file:

`packs/runtime.banana-rid.Microsoft.DotNet.ILCompiler/x.y.z/sdk/nonportable.txt`

We should investigate why we produce this file and what purpose it serves.

**Comment by omajid** [comment]
https://github.com/dotnet/runtime/blob/39dd2e1eaa2461df01b0e06157c573f9ce649c4f/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L162-L165:

```
    <ItemGroup Condition="'$(StaticOpenSslLinking)' != 'true' and Exists('$(IlcSdkPath)nonportable.txt')">
      <NativeSystemLibrary Include="ssl" />
      <NativeSystemLibrary Include="crypto" />
    </ItemGroup>
```

Looks like native AOT uses that file as a marker to decide whether to link against some system libraries or not.

**Comment by MichaelSimons** [comment]
[Triage] @omajid provided the insight needed.  No further action is needed.
