### ISSUE TITLE
SDK Content Diffs - Roslyn

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4534]
The following content diffs are appearing between the MSFT SDK and the Source-Build SDK. This content diff has been known to appear, disappear, and resurface.

Files appearing in the source-build SDK and not in the MSFT sdk:
```diff
+./sdk/x.y.z/Roslyn/bincore/System.Collections.Immutable.dll
+./sdk/x.y.z/Roslyn/bincore/System.Reflection.Metadata.dll
```

I have tracked the diffs down to the following commits and builds:
- [dotnet/dotnet commits](https://github.com/dotnet/dotnet/compare/b96dd043bc8cc103cf86370f4760822ff9515755...c483106fdf29bf237a06180fc5e914b08be21117)
- [dotnet-source-build build without diff](https://dev.azure.com/dnceng/internal/_build/results?buildId=2503735&view=results) (internal Microsoft link)
- [dotnet-source-build build with diff](https://dev.azure.com/dnceng/internal/_build/results?buildId=2503783&view=results) (internal Microsoft link)

**Comment by MichaelSimons** [comment]
[Triage] This is likely caused by version lifting and the transient nature is due to version alignment.  We do not see the ROI for an in-depth investigation as there is no evidence of behavior issues.  We think the bincore directory is a candidate to add an exclusion for.
