### ISSUE TITLE
[9.0.1xx-Preview7] Azure DevOps YAML pipeline authorization fails for `NetCore1ESPool-Svc-Internal` pool 

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4535]
Failing build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2505866&view=logs&s=806e3c52-196a-5daf-13a8-118664e8ec26&j=f94b1352-8074-534d-f024-dae8a910f9a5

    ##[error]Pipeline does not have permissions to use the referenced pool(s) NetCore1ESPool-Svc-Internal. For authorization details, refer to https://aka.ms/yamlauthz.
    Pool: [NetCore1ESPool-Svc-Internal](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_settings/agentqueues?poolId=&queueId=392)

**Comment by mthalman** [comment]
I've submitted a request to get permissions fixed for this pipeline.

**Comment by mthalman** [comment]
Pool permission issue is resolved.
