### ISSUE TITLE
VMR builds failing in `runtime`  with Command not found

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4538]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2506686&view=logs&j=609589e2-4f74-5576-cdb7-914bcaea778b&t=8309e960-3e55-5314-da53-c9e47ab6c0d0) (internal Microsoft link)

All legs are building failed for `runtime` repo with error:

      /vmr/src/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj(57,5): error MSB3073: The command "..." exited with code 127.
      
      Build FAILED.

**Comment by omajid** [comment]
I am also seeing this, across a number of operating systems and architectures.

**Comment by MichaelSimons** [comment]
I am seeing this in some PR validation legs as well - [example](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762812&view=results)

**Comment by NikolaMilosavljevic** [comment]
Investigating...

**Comment by omajid** [comment]
Could https://github.com/dotnet/runtime/pull/105785 be related?

**Comment by MichaelSimons** [comment]
The runtime fix is flowing in with https://github.com/dotnet/sdk/pull/42496.

**Comment by MichaelSimons** [comment]
https://github.com/dotnet/sdk/pull/42496. was merged and builds are now passing.  Closing.
