### ISSUE TITLE
Pipeline does not have permissions to use `NetCore1ESPool-Svc-Internal` pool

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4541]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2510224&view=logs&s=806e3c52-196a-5daf-13a8-118664e8ec26&j=f94b1352-8074-534d-f024-dae8a910f9a5)

These two pipelines need to be added to `NetCore1ESPool-Svc-Internal` pool: `installer-dotnet-dotnet-synchronization` and `installer-dotnet-dotnet-synchronization-internal`

    ##[error]Pipeline does not have permissions to use the referenced pool(s) NetCore1ESPool-Svc-Internal. For authorization details, refer to https://aka.ms/yamlauthz.
    Pool: [NetCore1ESPool-Svc-Internal](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_settings/agentqueues?poolId=&queueId=392)

**Comment by mthalman** [comment]
I submitted a request to get permissions for these pipelines.

**Comment by mthalman** [comment]
Issue is resolved.
