### ISSUE TITLE
couldn't build sdk from sources

### ISSUE THREAD

**Issue by bykvaadm** [dotnet/source-build#4542]
following the guide - clone (v6.0.424) - build.sh -> cd to folder with sources, ./prep.sh, ./build.sh

getting always one error:

/opt/dotnet/build_sdk/uplevel_repo/.dotnet/sdk/6.0.200/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): error : Could not find a part of the path '/opt/dotnet/build_sdk/uplevel_repo/src/source-build/artifacts/source-build/self/src/src/MSBuildLocator/src/MSBuildLocator/build'. [/opt/dotnet/build_sdk/uplevel_repo/src/source-build/artifacts/source-build/self/src/src/MSBuildLocator/src/MSBuildLocator/Microsoft.Build.Locator.csproj]

**Comment by MichaelSimons** [comment]
@bykvaadm - This makes sense.  Have you looked at the changes to source-build post 6.0 (e.g. 8.0)?  The source is now gathered into a VMR (Virtual Mono Repo) located at https://github.com/dotnet/dotnet.  This is the repo you would use to build .NET source-build from.  I suspect this may provide the same thing you are doing.

**Comment by MichaelSimons** [comment]
[Triage] We noticed you are trying to build v6.0.424.  Just want to note that source-build is only supported on the 1xx feature band branches at this point in time.  Of course you are free to build any feature branch but just be aware it will likely require work.

Given .NET 6 is nearing EOL (Nov 12, 2024), this documentation request doesn't meet the criteria for changes we would make.

**Comment by bykvaadm** [comment]
>> Have you looked at the changes to source-build post 6.0
Nope, as our product is build by 6.x

Ok, anyway thanks for reply
