### ISSUE TITLE
VMR build fails with warning NU1905: `Audit source 'nuget.org' did not provide any vulnerability data`

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4548]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2514219&view=logs&j=391e3a46-1d0e-50f6-4b48-986aa9de4d73&t=75e2e54a-7893-5462-35f2-6162ecd1ec31)

 'nuget-client' failed during build:

    /vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj : warning NU1905: Audit source 'nuget.org' did not provide any vulnerability data.
    /vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json.
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Common/NuGet.Common.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Commands/NuGet.Commands.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Credentials/NuGet.Credentials.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Commands/NuGet.Commands.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Common/NuGet.Common.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Credentials/NuGet.Credentials.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Resolver/NuGet.Resolver.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Resolver/NuGet.Resolver.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Protocol/NuGet.Protocol.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Protocol/NuGet.Protocol.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Packaging/NuGet.Packaging.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.ProjectModel/NuGet.ProjectModel.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Packaging/NuGet.Packaging.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.ProjectModel/NuGet.ProjectModel.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Frameworks/NuGet.Frameworks.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Frameworks/NuGet.Frameworks.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.LibraryModel/NuGet.LibraryModel.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.LibraryModel/NuGet.LibraryModel.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.DependencyResolver.Core/NuGet.DependencyResolver.Core.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.DependencyResolver.Core/NuGet.DependencyResolver.Core.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/Microsoft.Build.NuGetSdkResolver.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/Microsoft.Build.NuGetSdkResolver.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
        2 Warning(s)
        36 Error(s)
    
    Time Elapsed 00:00:17.06

**Comment by NikolaMilosavljevic** [comment]
Offline builds are failing, online builds are working fine. Offline builds do not even have nuget.org in the list of sources. Nuget.config seems correct. Trying to get a local repro to investigate further.

**Comment by NikolaMilosavljevic** [comment]
The issue was likely introduced with the latest `nuget.client` update that was merged yesterday: https://github.com/dotnet/sdk/pull/42679

Source-build validation was successful, but we only do one `online` validation build.

**Comment by NikolaMilosavljevic** [comment]
This nuget.client change might be related: https://github.com/NuGet/NuGet.Client/pull/5963

**Comment by NikolaMilosavljevic** [comment]
OK - backtracking. Other changes in nuget.client have caused this. Here's the full set of changes, and some of them are introducing source auditing: https://github.com/nuget/nuget.client/compare/5485ea6..e68fb0f

**Comment by mthalman** [comment]
Reopening as this was not applied to release/9.0.1xx branch.

**Comment by NikolaMilosavljevic** [comment]
Created a backport of the real fix to `release/9.0.1xx` - https://github.com/dotnet/sdk/pull/42800

**Comment by Winniexu01** [comment]
Created a backport of the real fix to `release/9.0.1xx-rc1` - https://github.com/dotnet/sdk/pull/42826
