### ISSUE TITLE
.NET 9 Preview 7 often fails to build on arm64

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#4555]
### Describe the Bug

I have been trying to build the .NET 9 Preview 7 release on a number of OS/architecture combinations. I have noticed that VMR builds often fail on arm64.

1. arm64 + CentOS Stream 10 fails with `Analyzer 'Microsoft.Interop.Analyzers.CustomMarshallerAttributeAnalyzer'
 threw an exception of type 'System.InvalidProgramException' with message 'Common Language Runtime detected an invalid program`.
   - Full log: https://download.copr.fedorainfracloud.org/results/@dotnet-sig/dotnet-preview/centos-stream-10-aarch64/07905791-dotnet9.0/builder-live.log.gz
   - Also reported as https://github.com/dotnet/roslyn-analyzers/issues/7376

2. arm64 + RHEL 9 failed with `CSC : error AD0001: Analyzer 'Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDetectPreviewFeatureAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'`
   - Full log: https://download.copr.fedorainfracloud.org/results/@dotnet-sig/dotnet-preview/rhel-9-aarch64/07905791-dotnet9.0/builder-live.log.gz

3. arm64 + Fedora ELN and arm64 + Fedora Rawhide failed with a crash: `error MSB6006: "csc.dll" exited with code 139`.
   - Full log: https://download.copr.fedorainfracloud.org/results/@dotnet-sig/dotnet-preview/fedora-eln-aarch64/07905791-dotnet9.0/builder-live.log.gz

This doesn't seem to affect every build or every arm64 platform. As an example, an attempt on arm64 + Fedora 39 worked, as did arm64 + RHEL 8. 

### Steps to Reproduce

On an arm64 machine, the following sequence of steps can fail:

```
git clone https://github.com/dotnet/dotnet
cd dotnet
git checkout v9.0.0-preview.7.24405.7
./prep-source-build.sh
./build.sh --source-only
```

**Comment by mthalman** [comment]
This is the tracking issue for that: https://github.com/dotnet/dnceng/issues/3305. We had previously encountered it in our VMR builds: https://github.com/dotnet/source-build/issues/4451. But it went away. Other builds are still seeing it apparently. It's not limited to the VMR.

**Comment by MichaelSimons** [comment]
@omajid - Can you clarify what SDK you are using to build?  Are you using the version prep retrieves (e.g. 9.0.100-preview.7.24380.2)?

**Comment by omajid** [comment]
> Are you using the version prep retrieves (e.g. 9.0.100-preview.7.24380.2)?

Yes. All the build logs show:

```
Welcome to .NET 9.0!
---------------------
SDK Version: 9.0.100-preview.7.24380.2
```

**Comment by omajid** [comment]
> This is the tracking issue for that: https://github.com/dotnet/dnceng/issues/3305.

Ah, I didn't see that. Shall I close this issue in source-build, then?

**Comment by MichaelSimons** [comment]
> Ah, I didn't see that. Shall I close this issue in source-build, then?

My preference would be for you to add a comment to https://github.com/dotnet/dnceng/issues/3305 and then close this one.

**Comment by omajid** [comment]
Okay, comment added there.
