### ISSUE TITLE
[release/9.0.1xx] VMR build fails with warning NU1905: Audit source 'nuget.org' did not provide any vulnerability data

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4558]
Related to https://github.com/dotnet/source-build/issues/4548 and https://github.com/dotnet/source-build/issues/4553, [Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2516801&view=logs&j=b9abe003-a5da-5729-0444-865506f15e35&t=3e16c345-0385-5f7a-129a-e4c24e1d773d) in release/9.0.1xx

'nuget-client' failed during build:

    /vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj : warning NU1905: Audit source 'nuget.org' did not provide any vulnerability data.
    /vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json.
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Resolver/NuGet.Resolver.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Protocol/NuGet.Protocol.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Protocol/NuGet.Protocol.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Resolver/NuGet.Resolver.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.ProjectModel/NuGet.ProjectModel.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.ProjectModel/NuGet.ProjectModel.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Packaging/NuGet.Packaging.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Packaging/NuGet.Packaging.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Common/NuGet.Common.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Common/NuGet.Common.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Commands/NuGet.Commands.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Commands/NuGet.Commands.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.LibraryModel/NuGet.LibraryModel.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.LibraryModel/NuGet.LibraryModel.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Frameworks/NuGet.Frameworks.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Frameworks/NuGet.Frameworks.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.DependencyResolver.Core/NuGet.DependencyResolver.Core.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.DependencyResolver.Core/NuGet.DependencyResolver.Core.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Credentials/NuGet.Credentials.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Credentials/NuGet.Credentials.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/Microsoft.Build.NuGetSdkResolver.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/Microsoft.Build.NuGetSdkResolver.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1905: Warning As Error: Audit source 'nuget.org' did not provide any vulnerability data. [/vmr/src/nuget-client/build/restorehelper.targets]
    /vmr/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/vmr/src/nuget-client/build/restorehelper.targets]
        2 Warning(s)
        36 Error(s)

**Comment by mthalman** [comment]
Duplicate of https://github.com/dotnet/source-build/issues/4548.

**Comment by NikolaMilosavljevic** [comment]
This is in `release/9.0.1xx`. Neither this branch, nor `release/9.0.1xx-rc1` have the fix.
