### ISSUE TITLE
New branches have been added to VMR pipeline

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4559]
There are two new branches under 'release' folder that have been added to VMR pipelilne:
New branch `release/9.0.1xx`: [release/9.0.1xx](https://dev.azure.com/dnceng/internal/_build/results?buildId=2516801) (internal Microsoft link)
New branch `release/9.0.1xx-rc1`: [release/9.0.1xx-rc1](https://dev.azure.com/dnceng/internal/_build/results?buildId=2515935) (internal Microsoft link)

Do we need to add 'release/9.0.1xx' and 'release/9.0.1xx-rc1' to [License Scan Test Pipeline](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build?definitionId=1301) and [SDK Diff Test Pipeline](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build?definitionId=1231)?

**Comment by ellahathaway** [comment]
Based on https://github.com/dotnet/sdk/pull/42784#discussion_r1721790415, is this a necessary issue to solve? We say in the yml that we only want to run the tests on internal branches when possible because that's where dependencies flow.

**Comment by Winniexu01** [comment]
Since there will be an internal/release/9.0.1xx-rc1 build,  no changes are necessary.
