### ISSUE TITLE
[9.0.1.xx-rc1] SDL Analysis Fails to Checkout VMR

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4568]
`Checkout dotnet-dotnet@release/9.0.1xx-rc1` fails in 9.0.1xx-rc1 builds with the following error:

```bash
fatal: No url found for submodule path 'src/wpf/origin/wpf' in .gitmodules
##[error]Git submodule update failed with exit code: 128
```

Checkout succeeds in other stages, it's only the SDL Analysis stage that encounters this error.

**Comment by ellahathaway** [comment]
This is a result of the submodule being added in this PR: https://github.com/dotnet/wpf/pull/9601

@singhashish-wpf - can you please take a look? TIA

**Comment by MichaelSimons** [comment]
cc @premun - Submodules get flattened out in the VMR so I wouldn't expect an issue.  Is there something special going on here?

**Comment by premun** [comment]
They do.. It's weird, though, there's no `.gitmodules` file in the repo so I have no idea how is there a submodule even in the first place

**Comment by premun** [comment]
Okay, so it seems like wpf has a broken submodule. The submodule was added, so the git tree has the COMMIT item inside but the `.gitmodule` file has not been added into git so there's no information where to get the submodule from.
Even trying to initialize it locally does not work:

```
> git submodule init
fatal: No url found for submodule path 'origin/wpf' in .gitmodules
```

**Comment by ellahathaway** [comment]
@singhashish-wpf or @dotnet/dotnet-wpf - friendly ping :) Do you know why this submodule was adding in https://github.com/dotnet/wpf/pull/9601? It's breaking our builds.

**Comment by singhashish-wpf** [comment]
> @singhashish-wpf or @dotnet/dotnet-wpf - friendly ping :) Do you know why this submodule was adding in [dotnet/wpf#9601](https://github.com/dotnet/wpf/pull/9601)? It's breaking our builds.

This got added by mistake. Deleted.

**Comment by ellahathaway** [comment]
This will be fixed once https://github.com/dotnet/sdk/pull/42997 is merged.
