### ISSUE TITLE
Upgrade NuGet Packages and Dependencies in SBRP

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4571]
As a result of https://github.com/dotnet/arcade/pull/15010, we need to take the following action in SBRP:

- [x] Add NuGet 6.11.0 packages and dependencies to the following branches (there are 11 packages being detected as prebuilts):
  - [x] main
  - [x] release/9.0.1xx
- [x] Remove nuget.commands.6.8.1, nuget.dependencyresolver.core.6.8.1, nuget.librarymodel.6.8.1, and nuget.projectmodel.6.8.1 from the following SBRP branches (the remaining 6.8.1 packages are still used by sdk's TemplateEngine + stem from usage in [the templating repo](https://github.com/dotnet/templating/blob/main/Directory.Packages.props#L19)):
  - [x] main
  - [x] release/9.0.1xx

Related to https://github.com/dotnet/sdk/pull/42900, https://github.com/dotnet/sdk/pull/42910

**Comment by MichaelSimons** [comment]
[Triage] SBRP is a self-service repo.  Since your arcade changes require the addition of these new packages, can you please add them?  TIA

**Comment by MilenaHristova** [comment]
> [Triage] SBRP is a self-service repo. Since your arcade changes require the addition of these new packages, can you please add them? TIA

opened a PR https://github.com/dotnet/source-build-reference-packages/pull/1015

**Comment by ellahathaway** [comment]
@MilenaHristova @dotnet/source-build-internal - heads up that we will also have to track these into the internal rc1 branch; it looks like mirroring synced the arcade changes in and are now our VMR builds are breaking for that branch: https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/commit/e41668e5f25d4142b4cc56c3b713ad347f77aa6c?path=/src/arcade/eng/Versions.props

**Comment by MilenaHristova** [comment]
> @MilenaHristova @dotnet/source-build-internal - heads up that we will also have to track these into the internal rc1 branch; it looks like the arcade changes flowed into sdk internally [via this PR](https://dev.azure.com/dnceng/internal/_git/dotnet-sdk/pullrequest/41879) (internal Microsoft link), so now our VMR builds are breaking for that branch: https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/commit/e41668e5f25d4142b4cc56c3b713ad347f77aa6c?path=/src/arcade/eng/Versions.props

How does it work, does the main branch of SBRP get copied into the VMR internal rc1 branch? I don't have context on the vmr anymore. Also for `release/9.0.1xx` should I open a pr to `release/9.0` branch of SBRP?

**Comment by mthalman** [comment]
This applies to both main and 9.0 so the change should be applied to both the main and release/9.0 branches of SBRP. That will all get flowed to consuming repos via dependency flow as well as the VMR.

**Comment by MilenaHristova** [comment]
here is the pr for 9.0: https://github.com/dotnet/source-build-reference-packages/pull/1020
