### ISSUE TITLE
2 new binaries introduced into VMR

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4587]
2 new binaries introduced into VMR on both [main](https://dev.azure.com/dnceng/internal/_build/results?buildId=2526543&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=2a0bd486-3f67-5c59-da0c-b84d88848a4b) and [release/9.0.1xx](https://dev.azure.com/dnceng/internal/_build/results?buildId=2526529&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=2a0bd486-3f67-5c59-da0c-b84d88848a4b) (internal Microsoft link):

    06:41:04 dbug: BinaryTool[0] New binaries:
    06:41:04 dbug: BinaryTool[0]     src/roslyn/src/Workspaces/CoreTest/Resources/Microsoft.CodeAnalysis.TestAnalyzerReference.dll.v1
    06:41:04 dbug: BinaryTool[0]     src/roslyn/src/Workspaces/CoreTest/Resources/Microsoft.CodeAnalysis.TestAnalyzerReference.dll.v2
    06:41:04 fail: BinaryTool[0] ERROR: 2 new binaries. Check '/mnt/vss/_work/1/s/artifacts/log/binary-report/NewBinaries.txt' for details.

**Comment by ellahathaway** [comment]
Looks like these were already in the VMR, they just got renamed: https://github.com/dotnet/roslyn/commit/f01eaf89943ddc8fe283c992f10b8275ca68b30b#diff-febe070233912cf8ad9aea8fecc38e8619f4573744fcc6e48620b7a656386513

**Comment by Winniexu01** [comment]
These two files were recently added: https://github.com/dotnet/roslyn/commit/18b58931b44e6d113c7e0dcafbda7c5e7f7523ec, and their name were changed later before being synchronized to VMR: https://github.com/dotnet/dotnet/commit/219fa88e3331db648ca0f67fe1223134d75e453b#diff-377097d80d0ad8a07341e476475157290aae1707bc8f67dcea1d417074c9f8ce
