### ISSUE TITLE
9.0 Stage 2 Builds Failing in Arcade due to `System.Security.Cryptography.Pkcs` Package Downgrade

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4601]
The 9.0 builds are encountering the following error when attempting to arcade build:

```
##[error]/vmr/src/arcade/src/Microsoft.DotNet.SourceBuild/tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj(0,0): error NU1605: (NETCORE_ENGINEERING_TELEMETRY=Restore) Warning As Error: Detected package downgrade: System.Security.Cryptography.Pkcs from 9.0.0-rc.2.24459.11 to 7.0.2. Reference the package directly from the project to select a different version. 
```

This error occurs in more than one place in the arcade, including `/vmr/src/arcade/src/Microsoft.DotNet.PackageTesting/Microsoft.DotNet.PackageTesting.csproj` and `/vmr/src/arcade/src/Microsoft.DotNet.Build.Tasks.TargetFramework/src/Microsoft.DotNet.Build.Tasks.TargetFramework.csproj`, so I suspect that this is due to a package version change in the arcade versions props file.

The Stage 1 builds have no prebuilts in their prebuilt packages directories.

**Comment by ellahathaway** [comment]
Here is the diff of the SDK commits from a successful run to the failing run - https://github.com/dotnet/sdk/compare/f1fc83d996a725122b74f355ed6e7077c82ffac7...78b2e7285e1e92a95e5a35ca41a554d8a0141519

Oddly, there's no changes. I'm continuing to investigate

**Comment by ellahathaway** [comment]
I've confirmed that `System.Security.Cryptography.Pkcs.9.0.0-rc.2.24459.11` is in the PSB artifacts from the stage 1 leg. The stack shows that the downgrade is because Microsoft.Build.Tasks.Core 17.8.3 references System.Security.Cryptography.Pkcs >= 7.0.2. This reference is also defined in arcade's Version.Details.

**Comment by ellahathaway** [comment]
Testing a fix in this pipeline run https://dev.azure.com/dnceng/internal/_build/results?buildId=2536490&view=results

**Comment by MichaelSimons** [comment]
@ellahathaway - is there remaining work here or can this be closed?

**Comment by ellahathaway** [comment]
This can be closed.
