### ISSUE TITLE
9.0 Stage 2 Builds Failing in fsharp with `error FS0064`

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4603]
[Link to failues](https://dev.azure.com/dnceng/internal/_build/results?buildId=2536490&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7&l=1072) (internal Microsoft link)

```
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,36): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_codeopt has been constrained to be type 'Code'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,36): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_codeopt has been constrained to be type 'Code'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,46): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Macros has been constrained to be type 'Macro list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,46): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Macros has been constrained to be type 'Macro list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,55): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Rules has been constrained to be type 'Rule list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,55): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Rules has been constrained to be type 'Rule list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(36,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_macro has been constrained to be type 'Macro'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(36,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_macro has been constrained to be type 'Macro'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(41,31): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_regexp has been constrained to be type 'Regexp'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(41,31): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_regexp has been constrained to be type 'Regexp'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(46,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_rule has been constrained to be type 'Rule'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(46,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_rule has been constrained to be type 'Rule'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,30): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_args has been constrained to be type 'RuleArgument list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,30): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_args has been constrained to be type 'RuleArgument list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,33): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clauses has been constrained to be type 'Clause list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,33): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clauses has been constrained to be type 'Clause list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fs(411,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_optbar has been constrained to be type 'unit'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fs(411,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_optbar has been constrained to be type 'unit'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(65,44): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clause has been constrained to be type 'Clause'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(65,44): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clause has been constrained to be type 'Clause'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(84,78): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_charset has been constrained to be type ''a -> 'b'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(84,78): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_charset has been constrained to be type ''a -> 'b'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
  /vmr/src/fsharp/buildtools/fslex/fslexpars.fs(260,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype__startspec has been constrained to be type 'obj'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fs(260,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype__startspec has been constrained to be type 'obj'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]

```

**Comment by ellahathaway** [comment]
@dotnet/fsharp - can you please take a look?

**Comment by vzarytovskii** [comment]
Feel free to put ignore for this error when builds (we have it as warning). Not yet sure what caused it.

**Comment by ellahathaway** [comment]
Had a discussion with @KevinRansom about this issue - it's likely related to [this line](https://github.com/dotnet/fsharp/blob/ac3d3c8bac5645c79c0aba47eabac60b453ff63f/src/Compiler/AbstractIL/ilpars.fsy#L5)  from https://github.com/dotnet/fsharp/pull/17649. The fsharp team is investigating.

**Comment by ellahathaway** [comment]
fsharp team confirmed that they think there's a bug to fix. I'll make the change to disable the warnings on our end and close this issue with that PR. I'm also going to link the PR to the issue in the fsharp repo so that we can remove the ignore once the fsharp team has a fix for the bug.

**Comment by Winniexu01** [comment]
The Stage 2 builds of [9.0.1xx-rc2](https://dev.azure.com/dnceng/internal/_build/results?buildId=2541175&view=logs&j=76d03db3-bc49-53a7-a20b-1050f0eb5e47&t=80dfeb20-733a-54b8-db3c-7b11261d6ba4) (internal Microsoft link) also failed with the same issue:

      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,36): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_codeopt has been constrained to be type 'Code'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,36): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_codeopt has been constrained to be type 'Code'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,46): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Macros has been constrained to be type 'Macro list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,46): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Macros has been constrained to be type 'Macro list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,55): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Rules has been constrained to be type 'Rule list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(26,55): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_Rules has been constrained to be type 'Rule list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(36,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_macro has been constrained to be type 'Macro'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(36,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_macro has been constrained to be type 'Macro'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(41,31): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_regexp has been constrained to be type 'Regexp'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(41,31): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_regexp has been constrained to be type 'Regexp'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(46,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_rule has been constrained to be type 'Rule'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(46,26): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_rule has been constrained to be type 'Rule'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,30): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_args has been constrained to be type 'RuleArgument list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,30): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_args has been constrained to be type 'RuleArgument list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,33): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clauses has been constrained to be type 'Clause list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(52,33): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clauses has been constrained to be type 'Clause list'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fs(411,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_optbar has been constrained to be type 'unit'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fs(411,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_optbar has been constrained to be type 'unit'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(65,44): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clause has been constrained to be type 'Clause'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(65,44): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_clause has been constrained to be type 'Clause'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(84,78): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_charset has been constrained to be type ''a -> 'b'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fsy(84,78): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype_charset has been constrained to be type ''a -> 'b'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]
      /vmr/src/fsharp/buildtools/fslex/fslexpars.fs(260,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype__startspec has been constrained to be type 'obj'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj] [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
    ##[error]/vmr/src/fsharp/buildtools/fslex/fslexpars.fs(260,20): error FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'gentype__startspec has been constrained to be type 'obj'. [/vmr/src/fsharp/buildtools/fslex/fslex.fsproj]

**Comment by vzarytovskii** [comment]
I think sdk workaround wasn't merged yet

**Comment by MichaelSimons** [comment]
I opened a backport PR - https://github.com/dotnet/sdk/pull/43548
