### ISSUE TITLE
[release/9.0] Stage 2 prebuilt - Microsoft.NETCore.Platforms.3.1.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4617]
The following stage 2 prebuilt is being detected.  This was discovered after fixing - https://github.com/dotnet/sdk/pull/43436

```
<Usage Id="Microsoft.NETCore.Platforms" Version="3.1.0" />
```

This was caught in a [Microsoft internal test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2540161&view=results)

**Comment by ellahathaway** [comment]
The prebuilt usage report does not indicate which repo this prebuilt is originating from:

```
<Usage Id="Microsoft.NETCore.Platforms" Version="3.1.0" />
```
