### ISSUE TITLE
[release/9.0.1xx-rc2] Synchronize VMR failed

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4621]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2541785&view=logs&j=cb61b4f6-36b5-5f40-8557-988b6891120d&t=eca77ce2-6e32-5710-84cc-28a3b75c2030) (internal Microsoft link)

Error:

    fail: Commit 83df353aff8147f431372b13ebd4c31f9de84b30 was not found in https://github.com/dotnet/sdk!
    fail: Pushing to the VMR failed. 
          Not all pushed commits are publicly available
    
    ##[error]Bash exited with code '42'.

**Comment by MichaelSimons** [comment]
The commit in question comes from this AxDO PR https://dev.azure.com/dnceng/internal/_git/dotnet-sdk/pullrequest/43013.

It looks like these same changes were also made to GH via this PR https://github.com/dotnet/sdk/pull/43562.

I'm not sure why two PRs were opened?  @marcpopMSFT?

@premun, @mmitche - please advise on how to unblock the synchronization pipeline.

**Comment by Winniexu01** [comment]
The [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2544277) is green, close the issue.
