### ISSUE TITLE
[internal/release/9.0.1xx-rc2] License Scan tests failing for SDK repo

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4627]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2544608&view=logs&j=6743a87c-2e18-5ff9-0f6c-56bd82018320 (internal Microsoft link)

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/sdk/pull/43623

**Comment by mthalman** [comment]
Oh, sorry. That was only for 9.0.1xx branch.

**Comment by Winniexu01** [comment]
The  [latest build](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=2545791) is green, close the issue.
