### ISSUE TITLE
Include .NET 10.0 in Rebootstrap and Release Pipelines

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4629]
Our release and rebootstrap pipelines currently require the user to select the version of .NET being released/rebootstrapped. The highest this version number goes to for both pipelines is 9.0, so we will have to update these pipelines once we move on to 10.0.

**Comment by MichaelSimons** [comment]
[Triage] When fixing this, if 6.0 is EOL, it would be good to cleanup the net6.0 references in these locations.

**Comment by MichaelSimons** [comment]
The rebootstrap pipeline was updated with https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/44748.

**Comment by mthalman** [comment]
Fixed by https://dev.azure.com/dnceng/internal/_git/c02a7e43-a426-455b-bba9-335409c459ba/pullrequest/45662 (internal link)
