### ISSUE TITLE
Error getting vulnerability data for msbuild repo

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4634]
The dotnet-source-build-lite pipeline is failing with the following error:

```
   /vmr/src/msbuild/src/Build/Microsoft.Build.csproj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/src/msbuild/MSBuild.SourceBuild.slnf]
    /vmr/src/msbuild/src/Framework/Microsoft.Build.Framework.csproj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/src/msbuild/MSBuild.SourceBuild.slnf]
    /vmr/src/msbuild/src/Utilities/Microsoft.Build.Utilities.csproj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/src/msbuild/MSBuild.SourceBuild.slnf]
    /vmr/src/msbuild/src/Tasks/Microsoft.Build.Tasks.csproj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/src/msbuild/MSBuild.SourceBuild.slnf]
    /vmr/src/msbuild/src/Package/Localization/Localization.csproj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/src/msbuild/MSBuild.SourceBuild.slnf]
    /vmr/src/msbuild/src/MSBuild/MSBuild.csproj : warning NU1900: Error occurred while getting package vulnerability data: Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/src/msbuild/MSBuild.SourceBuild.slnf]
    /vmr/src/msbuild/src/StringTools/StringTools.csproj : error NU1900: Warning As Error: Error occurred while getting package vulnerability data: Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/src/msbuild/MSBuild.SourceBuild.slnf]
        7 Warning(s)
        1 Error(s)
```

[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2546576&view=logs&j=1d0f2ce7-a8ca-596f-a60f-32004bcd1f4a&t=78a76fa6-5c8e-5f23-aef7-18f3ac1c951f) (internal link)

**Comment by mthalman** [comment]
This is also failing in Unified Build: [example](https://dev.azure.com/dnceng/internal/_build/results?buildId=2546577&view=logs&j=f0f4e1eb-2872-579b-17f7-75dc26fbb285&t=781c21d8-2065-5cb7-b2bc-7bade902314f) (internal link). It doesn't seem to be associated with a code change but rather a feed or network change?

pinging @jeffkl, @nkolev92 for any insight

**Comment by nkolev92** [comment]
Hard to tell on a first look. 

Seems like the source wasn't accessible.

Did the SDK version change recently?

**Comment by zivkan** [comment]
Just as a test, can you run `dotnet add package DoesNotExist` to some project?   It will show inner exceptions, and therefore explain why the service index can't be loaded.

However, I don't see the Azure Pipelines `NuGetAuthenticate` task being run, so I suspect that it isn't sending credentials to the private feed. If this worked before, I don't know how or why. My understanding is that it's always been necessary to set up the credentials in Azure Pipelines before trying to access the private feed.

**Comment by mthalman** [comment]
It looks like this was a transient error. Builds are passing now.

**Comment by mthalman** [comment]
Yes, it also showed up in https://github.com/dotnet/sdk/pull/44174.

**Comment by mthalman** [comment]
In the 8.0 builds, it gets the following error which provides the extra context of 401 (Unauthorized):

```
    /vmr/.dotnet/sdk/8.0.110/NuGet.targets(156,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json. [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj]
    /vmr/.dotnet/sdk/8.0.110/NuGet.targets(156,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj]
##[error]/vmr/.dotnet/sdk/8.0.110/NuGet.targets(156,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) Unable to load the service index for source https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).
```

This feed is referenced here: https://github.com/dotnet/dotnet/blob/35bcded9665f1c24cb3fe3622290a322a6faf278/src/msbuild/NuGet.config#L21

@rainersigwald - Do you have context on this feed and know what's going on here?

**Comment by mthalman** [comment]
This also affects main. It showed up in the unified build run of this PR: https://github.com/dotnet/sdk/pull/44192

**Comment by jeffkl** [comment]
Did an auth token expire or something?  The feed https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json requires authentication, what is configuring authentication for feeds?

**Comment by rainersigwald** [comment]
That feed no longer exists and shouldn't be referenced in current branches. But the flow of that removal into SDK has been held up on unrelated problems (https://github.com/dotnet/sdk/pull/44011).

**Comment by mthalman** [comment]
@rainersigwald - That flow is for main branch but this also applies to both 8.0 and 9.0. Has a similar feed removal been made for those branches? Because no such removal has reached the VMR yet.

**Comment by rainersigwald** [comment]
It may not have but I was just talking to @MichalPavlik about how we needed it.

**Comment by mthalman** [comment]
VMR patches created to workaround this:
* main: https://github.com/dotnet/sdk/pull/44194
* 9.0: https://github.com/dotnet/sdk/pull/44199
* 8.0: https://github.com/dotnet/installer/pull/20202

**Comment by mthalman** [comment]
All the PRs mentioned in https://github.com/dotnet/source-build/issues/4634#issuecomment-2414852822 have been merged so this should be resolved now.
