### ISSUE TITLE
[9.0] VerifyBlazorWasmTemplate test failing during publish command

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4636]
```
    [FAIL] Microsoft.DotNet.ScenarioTests.SdkTemplateTests.SdkTemplateTests.VerifyBlazorWasmTemplate(language: CSharp)
    System.InvalidOperationException : Failed to execute /vmr/artifacts/obj/extracted-dotnet-sdk/dotnet publish  /bl:/vmr/artifacts/scenario-tests/artifacts/SdkTemplateTest_BlazorWasm_CSharp/publish.binlog
    Exit code: 1
    Determining projects to restore...
      Restored /vmr/artifacts/scenario-tests/artifacts/SdkTemplateTest_BlazorWasm_CSharp/SdkTemplateTest_BlazorWasm_CSharp.csproj (in 362 ms).
    /vmr/artifacts/obj/extracted-dotnet-sdk/sdk/9.0.100-rc.2.24476.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(326,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/vmr/artifacts/scenario-tests/artifacts/SdkTemplateTest_BlazorWasm_CSharp/SdkTemplateTest_BlazorWasm_CSharp.csproj]
      SdkTemplateTest_BlazorWasm_CSharp -> /vmr/artifacts/scenario-tests/artifacts/SdkTemplateTest_BlazorWasm_CSharp/bin/Release/net9.0/SdkTemplateTest_BlazorWasm_CSharp.dll
      SdkTemplateTest_BlazorWasm_CSharp (Blazor output) -> /vmr/artifacts/scenario-tests/artifacts/SdkTemplateTest_BlazorWasm_CSharp/bin/Release/net9.0/wwwroot
      Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
      Optimizing assemblies for size. This process might take a while.
      Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
      Compiling native assets with /root/.dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Sdk.linux-x64/9.0.0-rtm.24469.1/Sdk/../tools/emscripten/emcc with -Oz. This may take a while ...
      [1/4] corebindings.c -> corebindings.o [took 0.38s]
      [2/4] pinvoke.c -> pinvoke.o [took 0.41s]
      [3/4] driver.c -> driver.o [took 0.43s]
      [4/4] runtime.c -> runtime.o [took 0.43s]
      Linking for initial memory $(WasmInitialHeapSize)=33554432 bytes. Set this msbuild property to change the value.
      Linking with emcc with -O2. This may take a while ...
       /root/.dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Sdk.linux-x64/9.0.0-rtm.24469.1/tools/bin/clang --version
       /root/.dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Node.linux-x64/9.0.0-rtm.24469.1/tools/bin/node /root/.dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Sdk.linux-x64/9.0.0-rtm.24469.1/tools/emscripten/src/compiler.mjs /tmp/tmpqqy9fpls.json --symbols-only
      /root/.dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Node.linux-x64/9.0.0-rtm.24469.1/tools/bin/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
emcc : error : '/root/.dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Node.linux-x64/9.0.0-rtm.24469.1/tools/bin/node /root/.dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Sdk.linux-x64/9.0.0-rtm.24469.1/tools/emscripten/src/compiler.mjs /tmp/tmpqqy9fpls.json --symbols-only' failed (returned 127) [/vmr/artifacts/scenario-tests/artifacts/SdkTemplateTest_BlazorWasm_CSharp/SdkTemplateTest_BlazorWasm_CSharp.csproj] [/vmr/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/Microsoft.DotNet.ScenarioTests.SdkTemplateTests.csproj] [/vmr/repo-projects/scenario-tests.proj]
```

[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2547119&view=results) (internal link)

This is only occurring in the `AlmaLinux8_Offline_MsftSdk_x64` and `Fedora40_Offline_MsftSdk_x64` legs.

**Comment by mthalman** [comment]
The reason this only occurs for `AlmaLinux8_Offline_MsftSdk_x64` and `Fedora40_Offline_MsftSdk_x64` is because the container images used by those legs do not have `libatomic` installed while the other images do.

**Comment by mthalman** [comment]
It is not clear why this dependency is popping up now. This is the VMR commit where this started to fail: https://github.com/dotnet/dotnet/commit/bc0af453ad3bb1f04d9bd3354c7d18587723b4b3. The only thing that affects source build in those changes in the scenario-tests change: https://github.com/dotnet/scenario-tests/pull/114. Is it possible that removing the workload uninstall has side effects that would affect the behavior of other tests?

**Comment by mthalman** [comment]
> The only thing that affects source build in those changes in the scenario-tests change: [dotnet/scenario-tests#114](https://github.com/dotnet/scenario-tests/pull/114). Is it possible that removing the workload uninstall has side effects that would affect the behavior of other tests?

Yes, that appears to be the case. I've compared the publish binlog between a working and failing test. In the failing test, it ends up calling the [`WasmTriggerPublishApp` target](https://github.com/dotnet/runtime/blob/d22c74dc974a757b48380a01dd0450efba31db64/src/mono/wasm/build/WasmApp.Common.targets#L438) which leads to the failure. It does not call that target in the working test because that targets file belongs to the `Microsoft.NET.Runtime.WebAssembly.Sdk` pack which is part of the wasm-tools workload. In the working test, that workload is not installed. But since we don't uninstall it now, it ends up impacting other tests.

cc @marcpopMSFT

We can certainly update the container images to have `libatomic` installed which would resolve this. But that still leaves the unfortunate situation where having workloads left installed can impact other tests. @marcpopMSFT - How temporary is this https://github.com/dotnet/scenario-tests/pull/114 change?

**Comment by marcpopMSFT** [comment]
@dsplaisted did you end up being able to reproduce the uninstall bug with the full installer of SDK with the unstable rtm build?

It sounds like the test runs were depending on uninstalling the workload. As an aside, that's bad test run design. Is there a way to isolate the workload tests or install the workloads to a custom location that aren't seen by other tests? Could the test configure this and then delete it after (assuming you're using a zip version of the SDK): https://github.com/dotnet/sdk/blob/main/documentation/general/workloads/user-local-workloads.md

**Comment by dsplaisted** [comment]
@marcpopMSFT I reproduced the uninstall error, understand what is going on, and am working on fixing it.

The installer build was creating a baseline workload set with an invalid feature band folder, which causes garbage collection to fail.  For most workload installation commands, the garbage collection failure would be displayed as a warning, but for uninstall it is reported as an actual error.

**Comment by mthalman** [comment]
@dsplaisted - Please provide a link to your fix when it's ready.

**Comment by dsplaisted** [comment]
Here is the PR with the fix: https://github.com/dotnet/sdk/pull/43797

**Comment by marcpopMSFT** [comment]
Here's the PR to add back the uninstall to the scenario tests now that 43797 is in: https://github.com/dotnet/scenario-tests/pull/116

**Comment by marcpopMSFT** [comment]
@mthalman not sure who can approve my scenario-tests revert but it's ready whenever ya'll want to merge it to unblock this.

**Comment by mthalman** [comment]
> @mthalman not sure who can approve my scenario-tests revert but it's ready whenever ya'll want to merge it to unblock this.

Merged it.
