### ISSUE TITLE
[9.0] VMR Stage2 build failing in `vstest`

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4641]
Original issue covers similar issues in `runtime` repo: https://github.com/dotnet/source-build/issues/4639

New test build with runtime fix uncovered similar issues in `vstest`: https://dev.azure.com/dnceng/internal/_build/results?buildId=2550295&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7

```
    /vmr/src/vstest/src/Microsoft.TestPlatform.PlatformAbstractions/common/Tracing/PlatformEqtTrace.cs(87,5): error IDE0032: Use auto property (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032) [/vmr/src/vstest/src/Microsoft.TestPlatform.PlatformAbstractions/Microsoft.TestPlatform.PlatformAbstractions.csproj::TargetFramework=net9.0]
```

**Comment by NikolaMilosavljevic** [comment]
Another `vstest` issue: https://dev.azure.com/dnceng/internal/_build/results?buildId=2551180&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7

```
    /vmr/src/vstest/src/Microsoft.TestPlatform.CoreUtilities/Output/ConsoleOutput.cs(15,5): error IDE0032: Use auto property (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032) [/vmr/src/vstest/src/Microsoft.TestPlatform.CoreUtilities/Microsoft.TestPlatform.CoreUtilities.csproj::TargetFramework=net9.0]
```

**Comment by nohwnd** [comment]
I downgraded the severity of the problem in our .editorconfig, is that enough?  Which branch are you taking the sources from? I only merged into main, but if this will be released with net9 then probably you should probably take sources from rel/17.12 which is what we insert into dotnet/sdk and VS. The fix is not backported there yet.

**Comment by NikolaMilosavljevic** [comment]
> I downgraded the severity of the problem in our .editorconfig, is that enough? Which branch are you taking the sources from? I only merged into main, but if this will be released with net9 then probably you should probably take sources from rel/17.12 which is what we insert into dotnet/sdk and VS. The fix is not backported there yet.

The fix works, I've tested it in a private validation run - https://dev.azure.com/dnceng/internal/_build/results?buildId=2551948&view=logs&s=9b073b6c-199e-5782-2adb-83c30ea48e21&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9

We need this for 9.0, so it would need to be backported to `rel/17.12`.

**Comment by NikolaMilosavljevic** [comment]
Repo issue was fixed: https://github.com/microsoft/vstest/issues/10364
