### ISSUE TITLE
Package source mapping causes problems with VMR restores

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4651]
Seen https://github.com/dotnet/sdk/pull/43239

I think what is going on is when PSM is enabled in a repo, the VMR infra will see these and add PSM mappings for the local feeds that are added to nuget.config. But these additional mappings are often more specific than the ones in the repo already, so the repo's feeds are often ignored.

**Comment by mmitche** [comment]
@dotnet/source-build-internal and I think @NikolaMilosavljevic who did the VMR PSM work.

**Comment by NikolaMilosavljevic** [comment]
We do add all specific mappings to original (online) sources, as well. So, VMR would be able to find them in all available sources. I could not repro this issue locally. Investigating further.
