### ISSUE TITLE
[main] All legs: `Did not find PDBs for the following SDK files` while building

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4653]
[All legs](https://dev.azure.com/dnceng/internal/_build/results?buildId=2555134&view=logs&j=609589e2-4f74-5576-cdb7-914bcaea778b&t=8309e960-3e55-5314-da53-c9e47ab6c0d0) (internal Microsoft link): the build steps did not fail because of these warnings.

    /vmr/eng/finish-source-only.proj(74,5): warning : Did not find PDBs for the following SDK files:
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/System.Formats.Nrbf.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/System.Reflection.MetadataLoadContext.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/System.Resources.Extensions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/Microsoft.AspNetCore.DeveloperCertificates.XPlat.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/FSharp/System.Formats.Nrbf.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/FSharp/System.Resources.Extensions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/System.Diagnostics.EventLog.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/System.Formats.Nrbf.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/System.Windows.Extensions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/System.Reflection.MetadataLoadContext.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/System.Security.Permissions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/System.Resources.Extensions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/BuildHost-netcore/System.CommandLine.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-watch/10.0.100-alpha.1.24508.1/tools/net9.0/any/System.Formats.Nrbf.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-watch/10.0.100-alpha.1.24508.1/tools/net9.0/any/System.Windows.Extensions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-watch/10.0.100-alpha.1.24508.1/tools/net9.0/any/System.Reflection.MetadataLoadContext.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-watch/10.0.100-alpha.1.24508.1/tools/net9.0/any/System.Security.Permissions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-watch/10.0.100-alpha.1.24508.1/tools/net9.0/any/System.Resources.Extensions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/runtimes/win/lib/net9.0/System.Diagnostics.EventLog.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/runtimes/win/lib/net9.0/System.Windows.Extensions.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-format/runtimes/win/lib/net9.0/System.Diagnostics.EventLog.Messages.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-watch/10.0.100-alpha.1.24508.1/tools/net9.0/any/BuildHost-netcore/System.CommandLine.dll
    /vmr/eng/finish-source-only.proj(74,5): warning : dk/10.0.100-alpha.1.24508.1/DotnetTools/dotnet-watch/10.0.100-alpha.1.24508.1/tools/net9.0/any/runtimes/win/lib/net9.0/System.Windows.Extensions.dll

**Comment by MichaelSimons** [comment]
This is likely a temporary issue during the transition period as the new net10.0 TFM is stood up.  This work is targeting to be completed at the end of Oct.  My recommendation is to set this aside until this work is complete.

**Comment by Winniexu01** [comment]
The [latest pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2585477) is green without this warning. Close this issue.
