### ISSUE TITLE
[main] All legs: `3 forbidden test usages found in 1 projects` while building

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4654]
[All legs](https://dev.azure.com/dnceng/internal/_build/results?buildId=2555134&view=logs&j=609589e2-4f74-5576-cdb7-914bcaea778b&t=8309e960-3e55-5314-da53-c9e47ab6c0d0) (internal Microsoft link): the build steps did not fail because of these warnings.

      13 packages used as expected in the baseline.
    /vmr/repo-projects/Directory.Build.targets(778,5): warning : 3 forbidden test usages found in 1 projects: [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(778,5): warning : src/sdk/artifacts/buildObj/obj/Tests/Microsoft.DotNet.Cli.Utils/project.assets.json [/vmr/repo-projects/dotnet.proj]

**Comment by ellahathaway** [comment]
Error is from here: https://github.com/dotnet/dotnet/blob/6f67bc6f8bcd2de81055864cfd2ab01d2b38310b/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/UsageReport/ValidateUsageAgainstBaseline.cs#L90-L101.

This seems related to the prebuilts?
