### ISSUE TITLE
[internal/release/9.0.1xx] Failed to install NuGet package: Microsoft.Security.CodeAnalysis.Policy.Microsoft.Internal vlatest

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4665]
`Guardian: Security Analysis Report` step failed for `internal/release/9.0.1xx`: https://dev.azure.com/dnceng/internal/_build/results?buildId=2556976&view=logs&j=b1caa8c7-837c-5a0e-fa2b-360b4dfa6cb4&t=1c0abfe9-33f2-546b-e052-2b085ed685ed (internal Microsoft link)

**Comment by ellahathaway** [comment]
This does not appear in a later build, so I'm going to close. If it occurs again we can reopen.
