### ISSUE TITLE
Occasional "cannot remove directory" during VMR build

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4677]
D:\a\_work\1\vmr\repo-projects\Directory.Build.targets(606,5): error MSB3231: Unable to remove directory "D:\a\_work\1\vmr\src\vstest\artifacts\sb\". Access to the path 'Microsoft.CodeAnalysis.dll' is denied. [D:\a\_work\1\vmr\repo-projects\vstest.proj]

From https://dev.azure.com/dnceng-public/public/_build/results?buildId=843915&view=results (retained)

**Comment by MichaelSimons** [comment]
[Triage] We haven't seen this on the source-build side.  Assigning to area-unified-build.

**Comment by ViktorHofer** [comment]
Closing as this got worked around via https://github.com/dotnet/sdk/pull/44361
