### ISSUE TITLE
[8.0] All SDK diff tests are failed

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4680]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2563555&view=results (internal Microsoft link)

**Comment by Winniexu01** [comment]
Hi @mthalman, one of the errors is checking whether the files in the source built SDK match those in the Microsoft SDK. Should I replace the assert logic with a message that the file was not found, just like you did in https://github.com/dotnet/sdk/pull/44156?

**Comment by mthalman** [comment]
I have a backport PR to fix the assembly version check: https://github.com/dotnet/installer/pull/20212. This doesn't resolve the SDK file diffs those.

**Comment by Winniexu01** [comment]
The [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2566878&view=results) (internal Microsoft link) is green.
