### ISSUE TITLE
[release 9.0.1xx] `VerifyVersionFile` Failing Due to Mismatched Version

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4682]
Regression caused by https://github.com/dotnet/sdk/pull/44289

The `SourceBuiltArtifactsTests.VerifyVersionFile` is failing in all 9.0.1xx builds because the test expects the SDK version to be `9.0.100-rtm.24517.1` but it is `9.0.100`.

The expected version is pulled from the source-built SDK, and the actual version is pulled from the private-source-built artifacts. This means that the SDK version is still `9.0.100-rtm.24517.1`.

cc @marcpopMSFT

**Comment by ellahathaway** [comment]
The expected SDK version is being pulled as the unique, non-stable version.

I think that to fix this we can either 1) adjust the `DetermineSourceBuildSdkVersion` to be the non-stable version (this would lead to a mismatch in artifact versions between the source-built SDK and the Private.SourceBuilt.Artifacts), 2) adjust the test to use the stable version if we are using an rtm version for the non-stable SDK version, or 3) something I'm not thinking of.

cc @dotnet/source-build

**Comment by NikolaMilosavljevic** [comment]
The issue is with version in PSB archive, it is `9.0.100`
