### ISSUE TITLE
Onboard maintenance-packages to source-build

### ISSUE THREAD

**Issue by ericstj** [dotnet/source-build#4684]
### Describe the Problem
The https://github.com/dotnet/maintenance-packages repository is being created as a place for packages that are still in support but no longer built elsewhere to continue to build.

The packages produced here will be referenced by packages that are part of the product on down-level platforms (eg: .NETFramework, .NETStandard).  

Rather than copy the packages from here to SBRP, we should consider bringing maintenance-packages into source-build.

### Describe the Solution

Onboard maintenance-packages into source-build and allow it's packages to flow into runtime and other repos.  Note that maintenance-packages isn't expected to branch with the product, but instead be in perpetual LTS.   As such its expected that `tip` will always be correct for all versions of .NET that are still in support.

### Additional Context

https://github.com/dotnet/runtime/pull/108806

cc @ViktorHofer @carlossanlop

**Comment by ViktorHofer** [comment]
I think that would mean that the maintenance-packages repo would need to be added to the VMR.

**Comment by MichaelSimons** [comment]
[Adding new repos to source-build](https://github.com/dotnet/source-build/blob/main/Documentation/sourcebuild-in-repos/new-repo.md) is a repo owner responsibility - it is intended to be a self-servicing task.  @dotnet/source-build will certainly provide guidance when needed.

**Comment by ericstj** [comment]
> I think that would mean that the maintenance-packages repo would need to be added to the VMR.

Not necessarily. There are other repos t hat are part of source build but not vmr.

**Comment by MichaelSimons** [comment]
> Not necessarily. There are other repos t hat are part of source build but not vmr.

I'm not following.  Source build works on the VMR so by definition, everything that is source-built must be part of the VMR.

**Comment by MichaelSimons** [comment]
Closing per the discussion in https://github.com/dotnet/maintenance-packages/pull/140.  Summary: maintenance-packages is not required in SB.  SBRP satisfies the requirements.
