### ISSUE TITLE
aspnetcore isn't building installers in the VMR

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4692]
The `BuildInstallers` switch defines if installers should be built which defaults to false. We should pass the switch in here: https://github.com/dotnet/dotnet/blob/eb82b31516b032924126ac2c81f3edca80911619/repo-projects/aspnetcore.proj#L12

-buildinstallers (Unix) / - BuildInstallers (Windows)

Note that there's also a join point on Windows in the installers which will fail the Windows dev leg when it gets enabled: https://github.com/dotnet/aspnetcore/issues/52884

cc @jkoritzinsky @NikolaMilosavljevic

**Comment by jkoritzinsky** [comment]
I'm working on re-writing aspnetcore's installer infra to be based on the Arcade tooling as we speak. I'll take this on once I finish the rewrite.

**Comment by ViktorHofer** [comment]
The Windows part is now completed. @jkoritzinsky will continue working on the Unix part.
