### ISSUE TITLE
[9.0] Smoke tests failing due to `error NU1301: feed doesn't exist`

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4698]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2567862&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=5c4cdfd0-f4b4-5b61-429a-9a8b8d5afea8) (internal Microsoft link)

Smoke tests `**_CSharp.csproj` failed:

    error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/darc-int-dotnet-runtime-e77011b3-1/nuget/v3/index.json.
    error NU1301:   Response status code does not indicate success: 404 (Not Found - The feed with ID 'darc-int-dotnet-runtime-e77011b3-1' doesn't exist. (DevOps Activity ID: 197B9F2F-4D66-449E-8E52-4E24440F3F4B)).

**Comment by MichaelSimons** [comment]
The feed was restored which resolved the issues.  closing.
