### ISSUE TITLE
[Main]  All offline builds are building `source-build-reference-packages` failed due to `error NU1100`

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4701]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2568649&view=logs&j=391e3a46-1d0e-50f6-4b48-986aa9de4d73&t=75e2e54a-7893-5462-35f2-6162ecd1ec31) (internal Microsoft link)

All offline builds are building `source-build-reference-packages` failed:

    /vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Tools.proj : error NU1100: Unable to resolve 'Microsoft.SourceBuild.Intermediate.source-build-externals (= 8.0.0-alpha.1.23518.1)' for '.NETFramework,Version=v4.7.2'. PackageSourceMapping is enabled, the following source(s) were not considered: prebuilt, previously-source-built, reference-packages, source-build-reference-package-cache. [/vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Build.proj]
    /vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Tools.proj : error NU1100: Unable to resolve 'Microsoft.SourceBuild.Intermediate.source-build-reference-packages (= 9.0.0-alpha.1.24405.2)' for '.NETFramework,Version=v4.7.2'. PackageSourceMapping is enabled, the following source(s) were not considered: prebuilt, previously-source-built, reference-packages, source-build-reference-package-cache. [/vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Build.proj]
    /vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Tools.proj : error NU1100: Unable to resolve 'Microsoft.SourceBuild.Intermediate.arcade (= 10.0.0-beta.24515.3)' for '.NETFramework,Version=v4.7.2'. PackageSourceMapping is enabled, the following source(s) were not considered: prebuilt, previously-source-built, reference-packages, source-build-reference-package-cache. [/vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Build.proj]
    /vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Tools.proj : error NU1100: Unable to resolve 'Microsoft.SourceBuild.Intermediate.source-build-externals (= 8.0.0-alpha.1.23518.1)' for '.NETFramework,Version=v4.7.2'. PackageSourceMapping is enabled, the following source(s) were not considered: prebuilt, previously-source-built, reference-packages, source-build-reference-package-cache. [/vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Build.proj]
    /vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Tools.proj : error NU1100: Unable to resolve 'Microsoft.SourceBuild.Intermediate.source-build-reference-packages (= 9.0.0-alpha.1.24405.2)' for '.NETFramework,Version=v4.7.2'. PackageSourceMapping is enabled, the following source(s) were not considered: prebuilt, previously-source-built, reference-packages, source-build-reference-package-cache. [/vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Build.proj]
    /vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Tools.proj : error NU1100: Unable to resolve 'Microsoft.SourceBuild.Intermediate.arcade (= 10.0.0-beta.24515.3)' for '.NETFramework,Version=v4.7.2'. PackageSourceMapping is enabled, the following source(s) were not considered: prebuilt, previously-source-built, reference-packages, source-build-reference-package-cache. [/vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Build.proj]
    /vmr/src/source-build-reference-packages/eng/DotNetBuild.props(28,5): error MSB3073: The command "./build.sh --configuration Release /bl:/vmr/src/source-build-reference-packages/artifacts/sourcebuild-dependency-projects.binlog /p:LocalNuGetPackageCacheDirectory=/vmr/artifacts/obj/source-build-reference-package-cache /p:SourceBuildOutputDir=/vmr/src/source-build-reference-packages/artifacts/sb/ /p:BuildDependencyPackageProjects=true /p:SetUpSourceBuildIntermediateNupkgCache=true /p:DotNetBuildSourceOnly=true /p:DotNetBuildInnerRepo=true /p:MicrosoftNetCoreIlasmPackageRuntimeId=linux-x64  /p:RestoreConfigFile=/vmr/artifacts/obj/source-build-reference-packages/NuGet.config" exited with code 1. [/vmr/.packages/BootstrapPackages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24368.9/tools/Build.proj]
        0 Warning(s)
        7 Error(s)

**Comment by ellahathaway** [comment]
I've narrowed this failure down to [this set of commits](https://github.com/dotnet/arcade/compare/1ccd352f12e845d89e5b5a9b800e2be88f8a6d98...89040b649a6aa8fa9b6bd6ddaad5a637cf091b07.

Investigating this, it seems like bootrapping/PVP flow is not working for offline builds of SBRP in the VMR. Looking at the diff, I see changes made to the arcade infra that could have potentially caused this.

@ViktorHofer - Since Matt Mitchel is out and you reviewed [his PR](https://github.com/dotnet/arcade/pull/15162), could you please take a look at this? Thanks in advance.

**Comment by ViktorHofer** [comment]
I think a re-bootstrap is needed to update the Arcade.Sdk:

![Image](https://github.com/user-attachments/assets/a9ef1251-74e8-487d-b728-718f902ba524)

**Comment by ellahathaway** [comment]
Fixed with https://github.com/dotnet/sdk/pull/44513, closing
