### ISSUE TITLE
Disable/Remove 6.0 source-build pipelines

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4704]
All 6.0 related source-build pipelines should be disabled/removed.  

- dotnet-installer-source-build-tarball-build
- source-build-externals-6.0-CI
- Remove above pipeline from the SB Dashboard

**Comment by MichaelSimons** [comment]
These pipelines were disabled and removed from the SB Dashboard.

**Comment by mthalman** [comment]
@MichaelSimons - Shouldn't this remain open until the pipelines are deleted from AzDO?

**Comment by MichaelSimons** [comment]
Per an offline discussion with @mthalman, we will delete this but will wait 1 month.

**Comment by MichaelSimons** [comment]
These pipeline have now been deleted.  Closing.
