### ISSUE TITLE
[main] VMR sync failing with `error 401 - Unauthorized`

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4708]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2571656&view=logs&j=ac868591-5f39-5047-4b1f-0ffa6f6c3268&t=c76fd82f-4b98-5682-362e-93ad11779b01) (internal Microsoft link)

    fail: A '401 - Unauthorized' status was returned for a HTTP request. We'll set the retries amount to 0. Error details: {"message":"Bad credentials","documentation_url":"[https://docs.github.com/graphql","status":"401"}](https://docs.github.com/graphql%22,%22status%22:%22401%22%7D)
    fail: Non-continuable HTTP 401 error encountered while making request against URI 'https://api.github.com/graphql'
          System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
             at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
             at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount)
    fail: Pushing to the VMR failed. 
          Failure to authenticate: Response status code does not indicate success: 401 (Unauthorized).

**Comment by mthalman** [comment]
A newer pipeline run has passed. This is resolved.
