### ISSUE TITLE
Work items in partner wiki pages need to be relevant to appropriate .NET version(s)

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4711]
When a partner wiki page gets generated, it includes links to work items for that release. These work items get linked based on only the release month with which they're associated. So all work items for that month get linked to all the releases for that month. In most cases, these work items apply to all .NET versions, so this is fine. In some cases, there can be work items that only apply to a specific .NET version. This can result in inaccurate information when these work items get linked to from a release where those work items don't apply.

@leecow has agreed to update the work items with tags (e.g. `8.0`, `9.0`) indicating which .NET version they apply to. The automation logic can query those tags to determine which work items apply to a given wiki page.

**Comment by leecow** [comment]
@mthalman - do I need to update past issues or only new ones?

**Comment by mthalman** [comment]
> [@mthalman](https://github.com/mthalman) - do I need to update past issues or only new ones?

Just new ones.

**Comment by MichaelSimons** [comment]
[Triage] The detailed release info stored in the json and markdown files were going to eliminate the need for the issues.  @richlander, @leecow - When will we be at a point that we can stop creating the vulnerability issues?

**Comment by MichaelSimons** [comment]
Per an offline discussion with @leecow, this is something the release team hopes to start working on in January.

**Comment by MichaelSimons** [comment]
[Triage] Closing as there is no ROI to fix this when we are going to be switching to the new CVE info/process shortly.
