### ISSUE TITLE
[Main] SBRP failing to Publish Using Darc

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4718]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2575584&view=logs&j=dba8c5c4-bab9-551d-cb64-41450f502586&t=cb016dc0-ffd5-5fca-626a-b141b0bf4513&l=75) (internal Microsoft link)

    The promotion build finished but the build isn't associated with at least one of the target channels. This is an error scenario.
    Details are available in the following build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2576151 For any questions, contact @dnceng
    Problems using Darc to promote build 245132 to default channels. Stopping execution...

In the promotion build, `Publish packages, blobs and symbols` failed :

    D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\10.0.0-beta.24530.1\tools\SdkTasks\PublishArtifactsInManifest.proj(131,5): error : Package 'Microsoft.SourceBuild.Intermediate.source-build-reference-packages' has stable version '10.0.555503' but is targeted at a non-isolated feed 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
        0 Warning(s)
        1 Error(s)

**Comment by Winniexu01** [comment]
Error message is from here: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L420-L423

**Comment by ViktorHofer** [comment]
I think that regressed with https://github.com/dotnet/source-build-reference-packages/commit/598ee70e60b92b2dfd853358a84d080e954b76a4

cc @MichaelSimons
