### ISSUE TITLE
Remove smoke tests prereqs tarball support

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4722]
In .NET 8.0 we gather the smoke tests prereqs in a tarball and we publish these as part of the release pipeline.  We should confirm this logic is no longer necessary and remove both the test and release infrastructure.

**Comment by MichaelSimons** [comment]
I have confirmed the tarball is not being utilized by our partners and can be removed.

**Comment by ellahathaway** [comment]
Removed from the release automation with [this PR](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/45280) (internal Microsoft link)

**Comment by ViktorHofer** [comment]
Should this logic also be removed? https://github.com/search?q=repo%3Adotnet%2Fsdk%20SourceBuildTestsPrereqsPath&type=code

**Comment by MichaelSimons** [comment]
> Should this logic also be removed? https://github.com/search?q=repo%3Adotnet%2Fsdk%20SourceBuildTestsPrereqsPath&type=code

Yes - That is part of the test infrastructure cleanup work.

**Comment by MichaelSimons** [comment]
Discussing this with @mthalman, a decision was made that there is limited ROI in cleaning this infra up in 8.0.  The smoke test prereqs is ~192 MB.  The remaining infra in main is being cleaned up with https://github.com/dotnet/sdk/pull/45544
