### ISSUE TITLE
[main] Ubuntu2404Arm64_Offline_MsftSdk_arm64 building failed for `runtime` repo with unexpected architecture

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4739]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2582477&view=logs&j=b1caa8c7-837c-5a0e-fa2b-360b4dfa6cb4&t=5a647af6-2fef-58c2-4caf-850dc1bc163c) (internal Microsoft link)

    /vmr/src/runtime/artifacts/sb/package-cache/microsoft.dotnet.build.tasks.installers/10.0.0-beta.24555.1/build/installer.singlerid.targets(395,5): error MSB4018: The "CreateRpmPackage" task failed unexpectedly. [/vmr/src/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Ref.sfxproj]
    /vmr/src/runtime/artifacts/sb/package-cache/microsoft.dotnet.build.tasks.installers/10.0.0-beta.24555.1/build/installer.singlerid.targets(395,5): error MSB4018: System.ArgumentException: Unknown architecture: aarch64 [/vmr/src/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Ref.sfxproj]
    /vmr/src/runtime/artifacts/sb/package-cache/microsoft.dotnet.build.tasks.installers/10.0.0-beta.24555.1/build/installer.singlerid.targets(395,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.Installers.src.CreateRpmPackage.Execute() in /_/src/arcade/src/Microsoft.DotNet.Build.Tasks.Installers/src/CreateRpmPackage.cs:line 80 [/vmr/src/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Ref.sfxproj]
    /vmr/src/runtime/artifacts/sb/package-cache/microsoft.dotnet.build.tasks.installers/10.0.0-beta.24555.1/build/installer.singlerid.targets(395,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute() [/vmr/src/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Ref.sfxproj]
    /vmr/src/runtime/artifacts/sb/package-cache/microsoft.dotnet.build.tasks.installers/10.0.0-beta.24555.1/build/installer.singlerid.targets(395,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/vmr/src/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Ref.sfxproj]
        0 Warning(s)
        1 Error(s)

**Comment by NikolaMilosavljevic** [comment]
The fix for this was merged to `arcade` on 11/6 with https://github.com/dotnet/arcade/pull/15222. It has just flowed to `sdk` with https://github.com/dotnet/sdk/pull/44757

**Comment by ellahathaway** [comment]
This has been resolved, closing.
