### ISSUE TITLE
What is the license for the dotnet/dotnet build prerequisites called Private.SourceBuilt.Artifacts?

### ISSUE THREAD

**Issue by ader1990** [dotnet/source-build#4742]
### Description

Hello,

I would like to know the License of the two artifacts the `./prep.sh` (https://github.com/dotnet/dotnet/blob/release/8.0.1xx/prep.sh) downloads, in the context of creating a bootstrap package with all the dependencies, that once created, to be able to build dotnet/dotnet fully offline in two stages (download and package the build required artifacts as stage 0, and then build dotnet in a subsequent separate stage):

* https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.110/dotnet-sdk-8.0.110-linux-x64.tar.gz
* https://dotnetcli.azureedge.net/source-built-artifacts/assets/Private.SourceBuilt.Artifacts.8.0.110-servicing.24474.1.centos.9-x64.tar.gz

I have opened this issue here, as dotnet/dotnet repository does not accept Issues.

This issue is in the context of building the dotnet packages in an offline manner.

Thank you.

### Reproduction Steps

Not required.

### Expected behavior

Not required.

### Actual behavior

Not required.

**Comment by MichaelSimons** [comment]
The SDK tarball (https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.110/dotnet-sdk-8.0.110-linux-x64.tar.gz) has a license included in it at the root.

The artifacts tarball is an collection of NuGet packages that each have their own licenses.

The intent is to use these two assets to bootstrap a source-build.  After the initial build, you would take the resulting sdk and artifacts tarballs and rebuild the product with them as inputs.  This process is documented in https://github.com/dotnet/source-build/blob/main/Documentation/bootstrapping-guidelines.md.

**Comment by MichaelSimons** [comment]
@leecow, Can you provide guidance on if the source-build artifacts tarball should include a license file at the root?

**Comment by leecow** [comment]
It's not necessary, and including it could help with questions such as this one. If all NuGet packages included in the source-build artifacts tarball are MIT licensed, including it would be redundant, but not wrong.

**Comment by MichaelSimons** [comment]
[Triage] Adding a single license doesn't seem appropriate.  It feels like it would be more correct to assemble something more like a third party notices file from the individual nupkgs.  We don't see high value in providing this.  Our recommendation is for user's who need this, to look at the individual licenses of the contained nupkgs.  Nupkgs can be treated as regular zip files - e.g. you can extract them to retrieve their license.
