### ISSUE TITLE
[main] All legs: 29 new packages used not in baseline!

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4748]
[All legs](https://dev.azure.com/dnceng/internal/_build/results?buildId=2585477&view=logs&j=27bc86d6-5b04-5e7e-1952-551ad1371b06&t=7de518f5-71d4-5df0-99bc-efa6e473f337) (internal Microsoft link): the build steps did not fail because of these warnings.

    /vmr/repo-projects/Directory.Build.targets(838,5): warning : 29 new packages used not in baseline! See report at /vmr/artifacts/prebuilt-report/baseline-comparison.xml for more information. Package IDs are: [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.AspNetCore.App.Ref.9.0.0-rc.2.24474.3 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.AspNetCore.App.Runtime.linux-x64.9.0.0-rc.2.24474.3 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.Bcl.AsyncInterfaces.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.Bcl.Cryptography.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.NET.ILLink.Tasks.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.NETCore.App.Crossgen2.linux-x64.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.NETCore.App.Host.linux-x64.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.NETCore.App.Ref.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Microsoft.NETCore.App.Runtime.linux-x64.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.CodeDom.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Collections.Immutable.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Composition.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Composition.AttributedModel.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Composition.Convention.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Composition.Hosting.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Composition.Runtime.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Composition.TypedParts.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Configuration.ConfigurationManager.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Diagnostics.EventLog.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Formats.Asn1.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Formats.Nrbf.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.IO.Pipelines.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Reflection.Metadata.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Reflection.MetadataLoadContext.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Resources.Extensions.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Security.Cryptography.Pkcs.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Security.Cryptography.ProtectedData.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Security.Cryptography.Xml.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : System.Threading.Tasks.Dataflow.9.0.0-rc.2.24473.5 [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : Prebuilt usages are different from the baseline. If detected changes are acceptable, update baseline with: [/vmr/repo-projects/dotnet.proj]
    /vmr/repo-projects/Directory.Build.targets(838,5): warning : cp '/vmr/artifacts/prebuilt-report/generated-new-baseline.xml' '/vmr/eng/tools/prebuilt-baseline.xml' [/vmr/repo-projects/dotnet.proj]

**Comment by MichaelSimons** [comment]
This is a result of having prebuilts which is tracked with https://github.com/dotnet/source-build/issues/4715

**Comment by MichaelSimons** [comment]
[Triage] Let's use https://github.com/dotnet/source-build/issues/4715 to track all prebuilt related work.
