### ISSUE TITLE
Documentation for the source build is incomplete

### ISSUE THREAD

**Issue by ader1990** [dotnet/source-build#4756]
According to https://github.com/dotnet/source-build/blob/main/Documentation/bootstrapping-guidelines.md#building-on-a-supported-platform-using-rid-known-to-net, at Stage 2, step 3:

```
./prep-source-build.sh --no-sdk --no-artifacts --with-sdk <extracted-stage1-sdk-path> --with-packages <extracted-stage1-artifacts-path>
```

This command fails with the error:

```
 ERROR: --no-sdk requires --no-bootstrap 
 or a pre-existing .dotnet SDK directory.  Exiting...
```

**Comment by MichaelSimons** [comment]
You should include `no-bootstrap` in that command.  I will open a PR to fix the documentation.

**Comment by ader1990** [comment]
> You should include `no-bootstrap` in that command. I will open a PR to fix the documentation.

I have tried it with `no-bootstrap` and it works as expected.
