### ISSUE TITLE
[8.0] CentOS9 legs are failed to build "CoreCLR component"

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4783]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2593560&view=logs&j=e370af34-c017-5758-dedd-b7a54423e801&t=6146d1d9-a8e2-517b-056c-8122721336d6&l=8181) (internal Microsoft link)

Error:

      /vmr/src/runtime/artifacts/source-build/self/src/src/native/libs/System.Native/pal_io.c:112:1: warning: '_Static_assert' is incompatible with C standards before C11 [-Wpre-c11-compat]
        112 | c_static_assert(PAL_S_IRWXU == S_IRWXU);
            | ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/native/libs/Common/pal_compiler.h:24:28: note: expanded from macro 'c_static_assert'
         24 | #define c_static_assert(e) c_static_assert_msg(e, "")
            |                            ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/native/libs/Common/pal_compiler.h:23:37: note: expanded from macro 'c_static_assert_msg'
         23 | #define c_static_assert_msg(e, msg) _Static_assert((e), msg)
            |                                     ^
      /usr/include/assert.h:140:24: note: expanded from macro 'static_assert'
        140 | # define static_assert _Static_assert
            | 

      /vmr/src/runtime/artifacts/source-build/self/src/src/native/libs/System.Globalization.Native/pal_icushim_internal.h:218:5: note: expanded from macro 'FOR_ALL_ICU_FUNCTIONS'
        218 |     FOR_ALL_UNCONDITIONAL_ICU_FUNCTIONS \
            |     ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/native/libs/System.Globalization.Native/pal_icushim_internal.h:95:5: note: expanded from macro 'FOR_ALL_UNCONDITIONAL_ICU_FUNCTIONS'
         95 |     PER_FUNCTION_BLOCK(u_strcpy, libicuuc, true) \
            |     ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/native/libs/System.Globalization.Native/pal_icushim.c:46:5: note: expanded from macro 'PER_FUNCTION_BLOCK'
         46 |     c_static_assert_msg((sizeof(#fn) + MaxICUVersionStringWithSuffixLength + 1) <= sizeof(symbolName), "The symbolName is too small for symbol " #fn); \
            |     ^

      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/gc/unix/gcenv.unix.cpp:635:36: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
        635 |             unsigned long nodeMask[nodeMaskLength];
            |                                    ^~~~~~~~~~~~~~
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/gc/unix/gcenv.unix.cpp:635:36: note: read of non-const variable 'nodeMaskLength' is not allowed in a constant expression
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/gc/unix/gcenv.unix.cpp:634:17: note: declared here
        634 |             int nodeMaskLength = (usedNodeMaskBits + sizeof(unsigned long) - 1) / sizeof(unsigned long);
            |                 ^

      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/vm/comreflectioncache.hpp:50:15: error: no member named 'LeaveRead' in 'ReflectionCache<Element, CacheType, CacheSize>'
         50 |         this->LeaveRead();
            |         ~~~~  ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/vm/comreflectioncache.hpp:69:15: error: no member named 'EnterWrite' in 'ReflectionCache<Element, CacheType, CacheSize>'; did you mean 'TryEnterWrite'?
         69 |         this->EnterWrite();
            |               ^~~~~~~~~~
            |               TryEnterWrite
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/vm/simplerwlock.hpp:80:10: note: 'TryEnterWrite' declared here
         80 |     BOOL TryEnterWrite();
            |          ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/vm/comreflectioncache.hpp:171:19: error: no member named 'LeaveWrite' in 'ReflectionCache<Element, CacheType, CacheSize>'
        171 |             this->LeaveWrite();
            |             ~~~~  ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/vm/comreflectioncache.hpp:40:15: error: no member named 'EnterRead' in 'ReflectionCache<Element, CacheType, CacheSize>'; did you mean 'TryEnterRead'?
         40 |         this->EnterRead();
            |               ^~~~~~~~~
            |               TryEnterRead
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/vm/simplerwlock.hpp:78:10: note: 'TryEnterRead' declared here
         78 |     BOOL TryEnterRead();
            |          ^

**Comment by omajid** [comment]
I think this should get fixed by https://github.com/dotnet/runtime/pull/109198

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic  - I think we should pull in the runtime fix as a patch until it is merged and flows.  Can you take care of this?

**Comment by NikolaMilosavljevic** [comment]
Patch PR: https://github.com/dotnet/installer/pull/20259
