### ISSUE TITLE
MicroBuild Install Siging Plugin Task fails on MacOS

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4791]
[Description of the issue & workaround](https://portal.microsofticm.com/imp/v5/incidents/details/546577650/summary) (internal microsoft link)
[MicroBuild work item/issue](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2297700) (internal microsoft link)

This is a tracking issue for the workaround.

The MicroBuild Install Siging Plugin Task fails on MacOS. The current workaround is to set pip install uamqp==1.6.9 and set environment variable, CFLAGS.

See https://github.com/ellahathaway/arcade/commit/5fba8f58f9154280cf1f88bfc74bbcc981eeccca#diff-1ef4817ff1b275f8bf600d6e5ddc806af3db278910e0236db4f6d5490b3e2f4dR37-R43 and https://github.com/ellahathaway/arcade/commit/5fba8f58f9154280cf1f88bfc74bbcc981eeccca#diff-1ef4817ff1b275f8bf600d6e5ddc806af3db278910e0236db4f6d5490b3e2f4dR56.

**Comment by ellahathaway** [comment]
Will be addressed by [this PR](https://devdiv.visualstudio.com/Engineering/_git/MicroBuild/pullrequest/593211) (internal microsoft link)

**Comment by ellahathaway** [comment]
MicroBuild folks say that this fix will roll out tomorrow morning.

**Comment by mmitche** [comment]
[heart]         Matt Mitchell (.NET) reacted to your message:
________________________________

**Comment by ellahathaway** [comment]
Closing as this was resolved with the latest update.
