### ISSUE TITLE
[9.0] Alpine319 offline leg failed to download Source-Built SDK

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4797]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2596344&view=logs&j=7212f986-be3c-5f43-e4a5-e58bdfc8e911&t=49e58a3b-7221-57bc-7c1c-0d8908535c37) (internal Microsoft link)

Step `Prep the Build` failed to find the gzip file 

    ++ tar -ozxf /mnt/vss/_work/1/s/prereqs/packages/archive/dotnet-sdk-9.0.101-alpine.3.19-x64.tar.gz -C /mnt/vss/_work/1/s/.dotnet
    
    gzip: stdin: not in gzip format
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now
    

The previous step `Setup Previously Source-Built SDK` failed to download source built sdk with error: "The specified blob does not exist."

    Downloading source-built SDK from https://dotnetcli.azureedge.net/source-built-artifacts/sdks/dotnet-sdk-9.0.101-alpine.3.19-x64.tar.gz...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    100   215  100   215    0     0   4313      0 --:--:-- --:--:-- --:--:--  4387

**Comment by MichaelSimons** [comment]
This is likely fallout from https://github.com/dotnet/sdk/pull/45289.  cc @NikolaMilosavljevic

**Comment by NikolaMilosavljevic** [comment]
Fixed. I've re-queued the build leg.
