### ISSUE TITLE
"Manifest generation failed" error in SBOM generation for all build legs

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4801]
The Generate SBoM Manifest step from the 1ES templates is failing all build legs (excluding the ones with guardian failures) with the following error:

```
##[error]Encountered an error while generating the manifest.
##[error]Error details: Access to the path '/mnt/vss/_work/1/s/artifacts/staging/_manifest' is denied.
```
This step is "succeeding with errors" so it's not failing the overall build. This occurs for 10.0 VMR, but it does not occur in builds of 9.0 and 8.0.

This is likely a regression caused by https://github.com/dotnet/sdk/pull/45323

**Comment by ellahathaway** [comment]
cc @ViktorHofer - can you please TAL? I think this is a result of https://github.com/dotnet/sdk/pull/45323

**Comment by ViktorHofer** [comment]
I believe that the combination of https://github.com/dotnet/sdk/pull/45407 & https://github.com/dotnet/sdk/pull/44969 will fix this

**Comment by Winniexu01** [comment]
Hi @ellahathaway @ViktorHofer , I reopened this issue because the offline legs are still failed with the same issue:

    ##[error]Encountered an error while generating the manifest.
    ##[error]Error details: Access to the path '/__w/1/a/artifacts/_manifest' is denied.
[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2600908&view=logs&j=391e3a46-1d0e-50f6-4b48-986aa9de4d73&t=e9fc764c-5d81-571b-5997-536fd39a4e99) (internal Microsoft link)

**Comment by ViktorHofer** [comment]
Hmm that doesn't make any sense to me. No idea what's going on here. cc @mmitche in case you have ideas

**Comment by ellahathaway** [comment]
Ah it's because it's an offline leg. When running offline builds, we do `sudo unshare -n`. This makes the files produced by the command "protected" such that they can only be accessed by commands run with administrator privileges. `sudo` is necessary here to unshare the network, otherwise I'd suggest that we just remove it

**Comment by ViktorHofer** [comment]
I see, makes sense. Do you have a suggestion on how to handle this? Should we rever the `sudo unshare` command when the build is done (if that's possible)?

**Comment by ellahathaway** [comment]
Not sure. Maybe there's a way to copy to the files to a new location and direct the SBOM generation to look there? I'm not sure that that would change permissions of the files though.

**Comment by ViktorHofer** [comment]
If this is about ownership (sudo vs regular user), could we update the owner of the staging folder after the build?
