### ISSUE TITLE
Remove patches/dev branch from clicommandlineparser

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#484]
Split from https://github.com/dotnet/source-build/issues/405

**Comment by dagood** [comment]
This repo is still on a dev branch (not much different from patches IMO from a maintainability perspective):

https://github.com/dotnet/source-build/blob/275e6615655bc36401aadcc67320db6231f8d3ca/repos/clicommandlineparser.proj#L8-L9

/cc @crummel @tmat @dleeapho

**Comment by crummel** [comment]
CliCommandLineParser was moved back onto the prodcon branch with https://github.com/dotnet/source-build/commit/6b2e3210a40df7aebe18fc561bf27eae97e262a8.
