### ISSUE TITLE
Flow CoreFX packages into NuGet.Client (specifically ProtectedData)

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#487]
Currently nuget-client depends on newtonsoft-json and common, but we think we need to add a dependency on corefx because `Nuget.Configuration` depends on `System.Security.Cryptography.ProtectedData`, from corefx.

This means adding [a `DotNetPackageVersionPropsPath` implementation](https://github.com/dotnet/source-build/blob/dev/release/2.1/Documentation/auto-dependency-flow/api.md#dependency-version-input-arguments) to NuGet.Client, configuring source-build, and making sure corefx produces the `ProtectedData` package.

I have changes that I think will work for for the NuGet.Client PackageVersionProps implementation here, but I haven't tried them yet: https://github.com/dotnet/source-build/compare/dev/release/2.1...dagood:nuget-client-pvp-01. ([Direct link to NuGet.Client patch](https://github.com/dagood/source-build/blob/383c6f2af5eff012a28e2ebefdf7271da35b6f86/patches/nuget-client/0001-Add-DotNetPackageVersionPropsPath-implementation.patch).)

@nkolev92 to keep NuGet.Client patchless for 2.1-RC, do you think you can get a change like that into the NuGet.Client `release-netcore-2.1-rc` branch? (After we see if they work. :smile:)

@dseefeld Can you try the changes with your corefx + cli changes to see if it works?

/cc @crummel

**Comment by nkolev92** [comment]
@dagood 
I think that's doable. 
//cc @rrelyea

**Comment by dagood** [comment]
It turns out we can't realistically turn on the full CoreFX package build yet, so this isn't happening now. Sorry for the false alarm, @nkolev92, we don't need any changes. It would be useful to have the package version props implementation in NuGet.Client for the future, but we don't have any use for it right now and can't really test it out.

Making the CoreFX build produce this package is tracked by *Enable building allConfigurations for corefx in source-build* (#210):

> [@weshaggard] We need to build all packages not just .NET Core app packages when we are in offline source-build mode. However the allconfigurations leg has never worked correctly on non-windows so we need to iterate on it in order to enable.

For now, we'll put `System.Security.Cryptography.ProtectedData` in the tarball as a prebuilt package.
