### ISSUE TITLE
Support setting the default installation dir that is used by the tool host

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#501]
For 2.1, the new global tools feature relies on a native host application that bootstraps the .NET tool.

The native host application contains a path that should match the install location of dotnet on the system. For Microsoft installs this is '/usr/share/dotnet'. For RHEL, Fedora, CentOS, this location is different.
We need to look at how we can configure/patch this location in source-build?

When the location doesn't match the install location, tools will fail to start unless the user sets DOTNET_ROOT to point to the install location.
There is a discussion whether the host should probe PATH to find the dotnet installation (https://github.com/dotnet/cli/issues/9114).

I'm looking at how the host for tools gets included.
I think the cli takes this as a package: https://github.com/dotnet/cli/blob/8c937a0db08e56660aca456ac088f2d0e70735ab/src/redist/redist.csproj#L219?
Does source-build first build that package? And then provide it as input to the cli build?

CC @omajid @dleeapho @crummel @dseefeld @natemcmaster @eerhardt

**Comment by omajid** [comment]
> Does source-build first build that package? And then provide it as input to the cli build?

I think so. I built source-build and the files it builds includes:

    ./bin/obj/x64/Release/blob-feed/packages/Microsoft.NETCore.DotNetAppHost.2.1.0-preview2-26406-04.nupkg
    ./bin/obj/x64/Release/blob-feed/packages/runtime.fedora.28-x64.Microsoft.NETCore.DotNetAppHost.2.1.0-preview2-26406-04.nupkg
    ./bin/obj/x64/Release/blob-feed/assets/Microsoft.NETCore.DotNetAppHost.2.1.0-preview2-26406-04.symbols.nupkg
    ./bin/obj/x64/Release/blob-feed/assets/runtime.fedora.28-x64.Microsoft.NETCore.DotNetAppHost.2.1.0-preview2-26406-04.symbols.nupkg

**Comment by tmds** [comment]
>  the files it builds includes:

So we are building the package, that's good. Do we know if it is this one that is consumed by the cli build?

**Comment by natemcmaster** [comment]
You will probably need to apply a patch to this.
https://github.com/dotnet/core-setup/blob/9a776be820ff4ae83476c7e9e97514ecd8f3ae1d/src/corehost/common/pal.unix.cpp#L192-L200. Cref https://github.com/dotnet/core-setup/pull/3888 for context.

It doesn't look like there is a way to specify default path as a compilation option, though, that should be pretty easy to add.

**Comment by tmds** [comment]
> Do we know if it is this one that is consumed by the cli build?

Yes, the tool host is the one we build from source:
```
$ strings sdk/2.1.300-preview2-006908/AppHostTemplate/apphost  | grep '@(#)'
@(#)Version 2.1.26406.04 @BuiltBy: omajid-trull @SrcCode: https://github.com/dotnet/core-setup/tree/d0205c9c344831e498b8ddfe1329204108803f0c
```

> You will probably need to apply a patch to this

@omajid and I were looking at the same lines. For now, we can patch this our-selves. This should become configurable for source-build.

**Comment by tmds** [comment]
Fixed by the `/etc/dotnet/install_location` introduced in 3.0: https://github.com/dotnet/designs/pull/58.
