### ISSUE TITLE
Smoke-test RC tarball build

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#506]

**Comment by crummel** [comment]
I'm using [Jenkins build 60](https://ci.dot.net/job/dotnet_source-build/job/dev_release_2.1/job/RHEL7.2_Tarball_Release/60/), from hash 9ad4704, which is one commit behind dev/release/2.1 right now.  I'm still getting:
```
Running 'dotnet restore' on /home/chris/dotnet-test/testing-smoke/C#_console/C#_console.csproj...
  Restoring packages for /home/chris/dotnet-test/testing-smoke/C#_console/C#_console.csproj...
/home/chris/dotnet-test/testing-smoke/C#_console/C#_console.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.1.0-rc1-26426-03)
/home/chris/dotnet-test/testing-smoke/C#_console/C#_console.csproj : error NU1102:   - Found 31 version(s) in nuget.org [ Nearest version: 2.1.0-preview2-26406-04 ]
  Generating MSBuild file /home/chris/dotnet-test/testing-smoke/C#_console/obj/C#_console.csproj.nuget.g.props.
  Generating MSBuild file /home/chris/dotnet-test/testing-smoke/C#_console/obj/C#_console.csproj.nuget.g.targets.
  Restore failed in 1,22 sec for /home/chris/dotnet-test/testing-smoke/C#_console/C#_console.csproj.
```

@weshaggard @dleeapho

**Comment by crummel** [comment]
We are producing that package, are we still expecting `smoke-test` to fail without adding the local package source?  cc @dseefeld

**Comment by dseefeld** [comment]
I have an update to smoke-test to set a local package source for the case when the package is something we build, but isn't available on nuget.org, yet.  I'll add a PR now.

**Comment by dseefeld** [comment]
@crummel see #507

**Comment by crummel** [comment]
Thanks Dan, that works for me with the exception of the web projects which I think #504 should fix.  I'm going to stack that, #500, and #505 on top of latest and see if that works.

**Comment by dagood** [comment]
I get this error from the web project smoke test, which I don't think #504 helps with:

```
    running run
Using launch settings from /work/testing-smoke/C#_web/Properties/launchSettings.json...
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-preview2-final' was not found.
  - Check application dependencies and target a framework version installed at:
      /work/testing-smoke/builtCli/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

My understanding is this is being addressed with https://github.com/aspnet/Universe/pull/1130 and https://github.com/dotnet/cli/pull/9178/files#diff-63122f55987fb7fe1993257c06b472b3 (`_AspNetCoreAppSharedFxIsEnabled`) so I'm not sure what we can do for RC.

**Comment by dagood** [comment]
Ah, yep: https://github.com/dotnet/source-build/issues/456#issuecomment-386163331. We don't expect the ASP.NET experience to work in RC1.

**Comment by crummel** [comment]
With e6a3f04 I'm getting a new error, looks like it might be an issue with the MSBuild upgrade?
`Could not load type 'Microsoft.Build.Logging.ProfilerLogger' from assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Logged https://github.com/dotnet/source-build/issues/508 for it.

**Comment by dseefeld** [comment]
I submitted #509 to fix the smoke test issue.

**Comment by crummel** [comment]
16a2bab33273b6685e94db552b62d20f468c3640 works for me building the tarball, now building from the tarball on a clean machine.

**Comment by crummel** [comment]
Smoke test passes for me on the clean machine as well.

**Comment by dleeapho** [comment]
I also validated with RHEL 7.4 Docker
