### ISSUE TITLE
Investigate RHEL 7.5 prereqs Dockerfile

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#520]
Our current RHEL 7.2 prereqs are old and not based off of current RHEL base images and are using matell prereqs. This is to get to a RHEL 7.5 based prereq that uses the prereqs from the LLVM-toolset-7 RHEL software collection.

**Comment by dleeapho** [comment]
Current issue is that coreclr build cannot find LLDB.h since the llvm-toolset-7-clang installs at `/opt/rh/llvm-toolset-7/root/usr/include/lldb/API/LLDB.h` resulting in:
`CMake Error at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:97 (message):
  Cannot find LLDB.h Try installing lldb-3.9-dev (or the appropriate package
  for your platform).  You may need to set LLVM_HOME if the build still can't
  find it.`

**Comment by omajid** [comment]
Does `export LLVM_HOME=/opt/rh/llvm-toolset-7/root/usr ` help?

**Comment by dleeapho** [comment]
@omajid it does not unfortunately.

**Comment by dleeapho** [comment]
setting `CMAKE_INCLUDE_PATH="/opt/rh/llvm-toolset-7/root/usr/include"` got release/2.1 building cleanly.

**Comment by dleeapho** [comment]
Closing the investigation. The rest of the work is in #415
