### ISSUE TITLE
System.Reflection.Emit.Lightweight.4.3.0 is unlisted on nuget.org

### ISSUE THREAD

**Issue by SergeyKhutornoy** [dotnet/source-build#532]
Could you guide me on why System.Reflection.Emit.Lightweight package is unlisted on nuget.org? Highly appreciate your help!
Package: https://www.nuget.org/packages/System.Reflection.Emit.Lightweight/4.3.0
Package Source on github: https://github.com/dotnet/source-build/blob/e09e728c00dbeae8246887bcb987ff493ab15947/src/reference-assemblies/nuspecs/System.Reflection.Emit.Lightweight.4.3.0.nuspec

For example, it causes the following issue.
Before the package being unlisted it was possible to get Selenium.WebDriver package in PowerShell 5 and Core 6 (for .Net Core 2.0) on Windows 10 using the following command: Install-Package Selenium.WebDriver -Destination $PSScriptRoot -Force -ForceBootstrap

Now this command cannot download all the Selenium package dependencies. It fails because System.Reflection.Emit.Lightweight.4.3.0 package is unlisted on nuget.org.
Error: Install-Package : Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)

**Comment by dagood** [comment]
The nuspec in this repo doesn't produce the "real" package, just a special compile-only version that was used internally by this repo. The real one is produced by CoreFX. This issue describes why it was unlisted: https://github.com/dotnet/corefx/issues/29365.
