### ISSUE TITLE
Add updater to update version info from prodcon build manifest

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#534]

**Comment by dagood** [comment]
To clarify a bit, this tracks bringing this kind of info from the manifest:

```
<Build Name="core-setup" BuildId="20180515-03" ...
```

to

https://github.com/dotnet/source-build/blob/c627c32ee8818a88d84713a2cff5c14272ea257b/repos/core-setup.proj#L9

**Comment by dagood** [comment]
The functionality chunk I'm adding for the build ID also lets us update the ProdCon feed URL and update package versions from the manifest.

**Comment by dagood** [comment]
Moving this back to backlog for now until I'm available to work on it. This updater won't be useful until we start getting ProdCon builds for the next release (whether from `master` or `release/2.1`) and it's just automation of a task that can be done manually so I think it can wait.

**Comment by dagood** [comment]
Completed: new updaters added to `master` #602 and `release/2.1` #605.
