### ISSUE TITLE
Core-Setup runtime packages sometimes produced as "2.1-rtm--", causing CLI build failure

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#535]
From https://github.com/dotnet/source-build/pull/528

> [@dagood] Found something interesting in the CentOS logs that might help explain the flakiness we're seeing for a while. In [the failed CentOS leg](https://ci.dot.net/job/dotnet_source-build/job/dev_release_2.1/job/CentOS7.1_Tarball_Release_prtest/197/), the outer PVP contains:
> 
> ```
> <MicrosoftNETCoreAppPackageVersion>2.1.0-rtm-26426-03</MicrosoftNETCoreAppPackageVersion>
> ...
> <RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>2.1.0-rtm-26426-03</RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>
> <RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>2.1.0-rtm-26426-03</RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>
> ```
> 
> And the tarball build contains:
> 
> ```
> <MicrosoftNETCoreAppPackageVersion>2.1.0-rtm-26426-03</MicrosoftNETCoreAppPackageVersion>
> ...
> <RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>2.1.0-rtm--</RuntimeCentos7X64MicrosoftNETCoreAppPackageVersion>
> <RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>2.1.0-rtm--</RuntimeCentos7X64MicrosoftNETCoreDotNetAppHostPackageVersion>
> ```
> 
> The chmod task is trying to find `.../runtime.centos.7-x64.microsoft.netcore.app/2.1.0-rtm-26426-03/...`, which doesn't match up with the PVP.
> 
> No idea why this only happens sometimes, though.
> 
> For the RHEL leg (and presumably successful CentOS runs are similar), both outer and in-tarball build PVPs contain:
> 
> ```
> <RuntimeRhel7X64MicrosoftNETCoreAppPackageVersion>2.1.0-rtm-26426-03</RuntimeRhel7X64MicrosoftNETCoreAppPackageVersion>
> <RuntimeRhel7X64MicrosoftNETCoreDotNetAppHostPackageVersion>2.1.0-rtm-26426-03</RuntimeRhel7X64MicrosoftNETCoreDotNetAppHostPackageVersion>
> ```

> [@weshaggard] I have seen this happen before but it was in the publish leg in prodcon which didn't correctly get the versions file generated. Be sure that whatever is running is running https://github.com/dotnet/core-setup/blob/master/build.proj#L17 otherwise the build numbers might not be setup correctly. 

This shows up as flakiness in the CentOS leg on PR CI, and more consistently in the rolling build in multiple other platforms.

**Comment by dagood** [comment]
I think we're hitting a pretty precise timing error when the day rolls over (in universal time). Here's the log with local timezone timestamps enabled (UTC-5):

```
18:59:18        Microsoft.DotNet.PlatformAbstractions -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/src/core-setup/Bin/obj/centos.7-x64.Release/sign/forPackaging/centos.7-x64.Release/Microsoft.DotNet.PlatformAbstractions/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll
18:59:18        Microsoft.Extensions.DependencyModel -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/src/core-setup/Bin/obj/centos.7-x64.Release/sign/forPackaging/centos.7-x64.Release/Microsoft.Extensions.DependencyModel/netstandard1.3/Microsoft.Extensions.DependencyModel.dll
18:59:19        Microsoft.Extensions.DependencyModel -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/src/core-setup/Bin/obj/centos.7-x64.Release/sign/forPackaging/centos.7-x64.Release/Microsoft.Extensions.DependencyModel/netstandard1.6/Microsoft.Extensions.DependencyModel.dll
...
19:00:08      Microsoft.NETCore.DotNetAppHost -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/runtime.centos.7-x64.Microsoft.NETCore.DotNetAppHost.nuspec
19:00:08      Microsoft.NETCore.DotNetHost -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/runtime.centos.7-x64.Microsoft.NETCore.DotNetHost.nuspec
19:00:09      Microsoft.NETCore.DotNetHostPolicy -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/runtime.centos.7-x64.Microsoft.NETCore.DotNetHostPolicy.nuspec
19:00:10      Microsoft.NETCore.DotNetAppHost -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/Microsoft.NETCore.DotNetAppHost.nuspec
19:00:10      Microsoft.NETCore.DotNetHostResolver -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/runtime.centos.7-x64.Microsoft.NETCore.DotNetHostResolver.nuspec
19:00:10      Microsoft.NETCore.DotNetHost -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/Microsoft.NETCore.DotNetHost.nuspec
19:00:11      Microsoft.NETCore.DotNetHostResolver -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/Microsoft.NETCore.DotNetHostResolver.nuspec
19:00:11      Microsoft.NETCore.DotNetHostPolicy -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/Microsoft.NETCore.DotNetHostPolicy.nuspec
19:00:47      Microsoft.NETCore.App -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/runtime.centos.7-x64.Microsoft.NETCore.App.nuspec
...
19:00:55      Microsoft.NETCore.App -> /mnt/resource/j/workspace/dotnet_source-build/dev_release_2.1/CentOS7.1_Tarball_Release_prtest/tarball-output/bin/obj/x64/Release/blob-feed/packages/specs/Microsoft.NETCore.App.nuspec
```

Moving to the next day could make Core-Setup "miss" the `BuildVersion-....props`, where it's supposed to find major and minor build number, and use nothingness instead. It's a little weird that `Microsoft.NETCore.App.nuspec` is last, but has a proper version number, but I suspect there's some project nesting thing happening where the `Microsoft.NETCore.App.nuspec` project was loaded earlier.

I think we should move this off RTM-blocking because it's rare and retrying is a guaranteed workaround.

A good fix for this is probably to add BuildTools override to use a static `BuildVersion.props` file that doesn't include the date in the filename. Including date is only useful for a dev who wants the output build number to get updated each day, which doesn't matter in source-build.

**Comment by weshaggard** [comment]
@dagood thanks for the investigation I think that is a high likelihood of what is going on.  We could test the theory by adding some additional checks. 

However I thought even it if didn't find the versions file it should try to regenerate but it is possible that isn't hooked up for pkgprojs. https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L263 I'd have to investigate whether or not ResolveProjectReferences us ever called in pkgprojs, it might not. We could potentially address this by making sure that it does get called.

However I also like your idea for any cases where we are producing the version from OfficialBuildId we can simply remove the timestamp from the filename because we know the version isn't going to change based on time. 

cc @mmitche @JohnTortugo FYI - Here is an interesting case to consider with the version file caching.

**Comment by dagood** [comment]
Do you know if the result would always work if the new file was generated? I'm wondering if dev builds might still get into a situation where the runtime.json points to the earlier day's versions, but the runtime packages produced end up at the later day's versions. If the versions in the runtime.json are actually gathered from what was built, this probably isn't a problem.

This isn't a problem for source-build because both files are forced to a single number because of the properties we pass in, but seems like a concern for Core-Setup dev/Msft builds.

**Comment by weshaggard** [comment]
Yes it is possible that even if you have it regenerated somewhere in the middle of the build that the build could be inconsistent, but it wouldn't ever be empty. I do you like the idea of trying to make it consistent through a build in some way.

**Comment by dagood** [comment]
I'm closing this as a duplicate of https://github.com/dotnet/core-setup/issues/4208. This seems like a product infra problem, unrelated to source-build.
