### ISSUE TITLE
Correctly truncate product versions

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#544]
Right now we do not truncate product versions at all - leading to versions like "2.1.0-rc1-26426-03" which do not match NuGet.org packages.  `StabilizePackageVersions` truncated too much, leading to "2.1.0", which is not yet released.  Figure out how prodcon does this and apply it to our build.

**Comment by dseefeld** [comment]
This is fixed.  The right combination of params was used with RTM build.
