### ISSUE TITLE
Update output version stabilization settings from ProdCon auto-update

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#550]
In 2.1, ProdCon controls how stabiliized the versions are (`2.1.0-rtm-12345-00` vs `2.1.0-rtm` vs `2.1.0`) by passing in parameters. This is different than 2.0 which has checkins in each repository. We should update the source-build default stabilization config to match what the ProdCon build used. This will help ensure we match what ends up being published to the NuGet gallery.

We can figure out what it is by looking at a known package's version, but to do this reliably, ProdCon should put the configuration in the build manifest.

**Comment by dagood** [comment]
What comes to mind:

 1. Have pipebuild pass the versioning properties into `DotNet-Orchestration-Push-Manifest` (ProdCon utility build def), and have that pass the version stabilization parameters into the MSBuild call.
 2. Pass the MSBuild properties into the task that creates the final orchestrated build manifest: [Microsoft.DotNet.Build.Tasks.Feed.targets#L177 (Arcade)](https://github.com/dotnet/arcade/blob/a4867b9af404b4b7ac96164db5b8347630760da2/src/Microsoft.DotNet.Build.Tasks.Feed/build/Microsoft.DotNet.Build.Tasks.Feed.targets#L177),  [PushOrchestratedBuildManifest.cs#L49 (Arcade)](https://github.com/dotnet/arcade/blob/a4867b9af404b4b7ac96164db5b8347630760da2/src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifest/PushOrchestratedBuildManifest.cs#L49).
 3. One of:
    * Add the new properties/elements to the strongly typed model in VersionTools (in BuildTools).
    * Add a fake `Build` element in the manifest that relays the versioning properties.
    * Add the properties to some/each product's `Build` element in the manifest.

@mmitche does that sound like the best way to flow these properties through?

**Comment by dseefeld** [comment]
@dagood to create an issue in Arcade

**Comment by mmitche** [comment]
Sounds fine to me.

**Comment by dagood** [comment]
Opened https://github.com/dotnet/arcade/issues/239. This issue now tracks setting up auto-update once the versioning settings start appearing in the manifest.

**Comment by dagood** [comment]
Stabilization settings are now available in the manifest, on the root element: https://github.com/dotnet/versions/blob/c4b79cfb08318686df1a8948e599de4e54abf24c/build-info/dotnet/product/cli/release/2.1/build.xml#L1

`<OrchestratedBuild Name="cli" BuildId="20180910-01-2016925" IsStable="false" VersionStamp="servicing">`

Next steps for this issue:
 * Implement VersionTools updater for these new attributes
 * Use new updater in source-build

**Comment by MichaelSimons** [comment]
[Triage] This issue is obsolete.  Source-build now clones off of the versions.details.xml graph.
