### ISSUE TITLE
Align phases and dependencies props files

### ISSUE THREAD

**Issue by chcosta** [dotnet/source-build#56]
There are some redundant concepts between phases.props and dependencies.props.  we should look into aligning these two files.

https://github.com/dotnet/source-build/pull/54

>chcosta commented 2 hours ago 
Thanks for the pointer @dagood . Do you think there's any way we can connect https://github.com/dotnet/source-build/blob/master/phases.props and dependencies.props and remove the need to make updates in two locations? If aligning them means we lose flexibility with respect to the versioning stuff, then we probably don't want to do it, but it would be great if this kind of repo related stuff was just captured in one location.
    
>dagood commented 2 hours ago 
I think that would be reasonable, and if a target is required to make that happen, it could be added as a dependency of everything in update-submodules.targets.

**Comment by karajas** [comment]
No longer use phases.
