### ISSUE TITLE
Investigate/fix web HTTPS tests in OSX

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#560]
The dotnet-dev-certs tool doesn't seem to work in Fedora24 and OSX, so it's disabled in the CI smoke tests. We don't think we need to support Fedora24 at this point, so OSX is the important one to fix.

**Comment by omajid** [comment]
AFAIK, dotnet-dev-certs isn't supported on Linux at all: https://github.com/dotnet/cli/issues/9008

**Comment by dagood** [comment]
My impression from using it is that it generates the cert fine and ASP.NET Core projects can use the generated cert, but dotnet-dev-certs can't automatically trust the dev cert. I assume you need trust to actually visit the https site you're hosting--I haven't tried that.

**Comment by dseefeld** [comment]
This doesn't repro on Fedora28.
