### ISSUE TITLE
Remove source code modification workaround that injects ProdCon NuGet feed into CLI

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#561]
For 2.1 RTM, we started changing a CLI MSBuild file to inject the current ProdCon feed: https://github.com/dotnet/source-build/pull/556. This was done because the `//` was turned into `/` by MSBuild when we tried to pass it in through the usual environment variable, and we couldn't find a way to escape it.

The source-build repo API approach is to pass a file that CLI would import to read a property that contains all the sources.

To remove this code modification workaround, we need to decide if we want a targeted fix (maybe adding unescaping to the CLI file), have CLI implement this one part of the source-build repo API, or think forward to what the Arcade/ProdCon v2 approach will be.

/cc @dleeapho @crummel @dseefeld

**Comment by dseefeld** [comment]
@dagood to create an issue in CLI for this.

**Comment by dagood** [comment]
I'm not sure anymore that we **need** a CLI fix for this. On Fedora28, in CLI `9ab03e695`, I can run:

```
export ExternalRestoreSources='https://example.com/foo/bar;/home/abc'
./build.sh
(cancel the build when it starts restoring to save time)
cat NuGet.Config
```

And I see these lines, which are fine:

```
<add key="PrivateBlobFeedhttps://example.com/foo/bar" value="https://example.com/foo/bar" />
<add key="PrivateBlobFeed/home/abc" value="/home/abc" />
```

I think the issue is that we're storing the environment variables in Items in source-build, and/or `Exec` is interpreting things.

That said, it would still definitely be easiest for us if the CLI implemented `DotNetRestoreSourcePropsPath`, so I'm submitting that as an issue. Escaping (especially the `;`) is notoriously difficult to get right everywhere.

**Comment by MichaelSimons** [comment]
[Triage] The injection of the ProdCon feed is handled by generic Arcade infra.  The aforementioned mechanism has been removed.  Closing as obsolete.
