### ISSUE TITLE
source-build needs to accept the SDK version I gave it

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#578]
When bootstrapping a new OS (or just building .NET Core from source in general), there are times when I don't have the exact version of the SDK that source-build wants.  One case is where I build a bootstrap SDK, run a source-build, and then use the output of that first source-build to build again.

We currently export the SDK_VERSION environment variable based on the value in DotnetCLIVersion.txt:

https://github.com/dotnet/source-build/blob/ac7159ec5f61d1ebadb454471d5f6190a4ebbc3b/build.sh#L6

1. I would hope we could get rid of all the places that need this SDK_VERSION, but that is a long-term goal.
2. In the meantime, we should instead get the correct version of the SDK we are using instead of the one that is checked into source. That way people don't need to edit source files just to get the build to work.

We can get the SDK version by executing `dotnet --version`.

**Comment by omajid** [comment]
> One case is where I build a bootstrap SDK, run a source-build, and then use the output of that first source-build to build again.

I had the same use case and the same exact issue.

A more general fix to improve this use case might be to provide the path to an entire SDK (not just the version) to the build. Source build can just pick it up from there and use it.

We should document the minimum/maximum version required for the SDK too.

**Comment by omajid** [comment]
Is this fixed by https://github.com/dotnet/source-build/pull/1455 ?

**Comment by dagood** [comment]
I believe so--at some point this issue was duplicated by https://github.com/dotnet/source-build/issues/1435, which we closed with https://github.com/dotnet/source-build/pull/1455.
/cc @crummel
