### ISSUE TITLE
Support sdk version branches/tags

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#585]
The [package guidelines for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging) describe a set of packages that are versioned based on the \<runtime version> and \<sdk version>.

To create these packages from source-build repo, we need branches/tags at the sdk level, for example: `dotnet-sdk-2.1.3xx` branch.

CC @dleeapho

**Comment by dseefeld** [comment]
We will add tags for each release which indicate which sdk version was released.

**Comment by tmds** [comment]
I see those tags are available. Thank you for providing them!
