### ISSUE TITLE
Enable net46 builds in source-build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#592]
End-to-end, this enables VS Code usage with source-build .NET Core (https://github.com/dotnet/source-build/issues/125 -> https://github.com/dotnet/sdk/issues/2249)

**Comment by crummel** [comment]
Related: https://github.com/dotnet/sdk/pull/2309, https://github.com/dotnet/source-build/pull/588.

**Comment by dleeapho** [comment]
@crummel Please test the E2E scenario with VS Code once PRs are merged.

**Comment by dagood** [comment]
Merged in https://github.com/dotnet/source-build/pull/598. I'm going to try validating VS Code/Omnisharp with a local build I'm building of https://github.com/dotnet/source-build/pull/610.

**Comment by crummel** [comment]
Confirmed, I also get a working VS Code.  `dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     rhel
 OS Version:  7
 OS Platform: Linux
 RID:         rhel.7-x64
 Base Path:   /home/chris/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  N/A

.NET Core SDKs installed:
  2.1.301 [/home/chris/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.1 [/home/chris/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
