### ISSUE TITLE
Use source-built newtonsoft JSON throughout product

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#593]
Right now the final product uses several prebuilt versions of Newtonsoft.Json. They should use the source-built one, if possible.

**Comment by dagood** [comment]
This is also interesting: https://github.com/dotnet/core-setup/issues/3311 "Remove dependency from JSON.NET". If that means the CLI product (and everything it uses) won't depend on Newtonsoft.Json, we wouldn't have to build it.

**Comment by dseefeld** [comment]
Fixed with https://github.com/dotnet/source-build/pull/1118
