### ISSUE TITLE
Update Newtonsoft.Json and build it without patches/fork

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#594]
In https://github.com/dotnet/source-build/pull/582, the newtonsoft-json submodule was pointed at @dseefeld's fork instead of using patches checked into source-build. This makes it easier to work with as a dev because we don't have to worry about `git apply` and cleaning/resetting submodules at the right times.

However, in the past, we've been bitten by pointing at "unofficial" forks of one of the submodules. The repo/branch might disappear or the branch might accidentally be force pushed, making the original commit inaccessible. This interrupts development by making it impossible to freshly clone source-build. The risk of *losing data*, however, is small: everyone who has a long-lived clone of the repo still has the old commit on their machine and just needs to push it to a new location.

Related: the source-build product isn't reliably using the source-built Newtonsoft.Json, tracked by https://github.com/dotnet/source-build/issues/593.

---

Short term, I think we're ok as-is. We could look into making a newtsonsoft-json fork in the dotnet org to store these patches, do something weird like storing it in an source-build orphan branch, or go back to patch files. I don't think that's worthwhile.

Long term, we should work with newtonsoft-json to get the project source-buildable on the latest sources.

**Comment by dleeapho** [comment]
The short-term fix is turning out longer than anticipated. #921 might be the solution but I think CLI would still want to use Newtonsoft.Json.

**Comment by crummel** [comment]
From eyeballing it, I think 10.0.3 should build without patches.  Commandeering this issue for the update as well as the patch removal.
