### ISSUE TITLE
Add dotnet/diagnostics submodule to source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#596]
https://github.com/dotnet/diagnostics is a new repo that extracts some bits that are currently in the CoreCLR repo. Parts of its readme:

> This repository contains the source code for various .NET Core runtime diagnostic tools. It currently contains SOS, the managed portion of SOS and the lldb SOS plugin. [...]
> 
> This repo will also allow out of band development of new SOS and lldb plugin features like symbol server support for the .NET Core runtime and solve the source build problem having SOS.NETCore (managed portion of SOS) in the coreclr repo.

It's on a recent RepoToolset, so adding it shouldn't be a lot of trouble. It's currently expected to be a leaf repo depended on by Core-Setup or CLI.

/cc @mikem8361

**Comment by mikem8361** [comment]
The diagnostics repo is still a work in progress; it isn't ready yet to be included in the source build.

**Comment by dagood** [comment]
@mikem8361 Is it reasonable to expect it to be ready before it's first used in Core-Setup/CLI `master`? (Rather than source-build "catching up" like we have to do when we see new repos too late.)

**Comment by mikem8361** [comment]
Are you asking me when the diagnostics repo will  be ready? I’m still in the middle of getting the CI build/test jobs setup.  I have to update our internal docker images to fix testing SOS on lldb across all of the supported distros, and a long list of other things before it will be officially be ready for source build.  It may be another month or so.

**Comment by dagood** [comment]
I'm just confirming the order: that there won't be a period where artifacts from the repo are used in Core-Setup/CLI even though the repo isn't ready for source-build yet.

**Comment by mikem8361** [comment]
Ok. I understand.

**Comment by mikem8361** [comment]
SOS/diagnostics repo is only going to ship out of band so it will not be part of the source build.

**Comment by dagood** [comment]
> SOS/diagnostics repo is only going to ship out of band

What I think of as OOB doesn't affect whether something's needed in source-build. OOB repos may produce tooling necessary to build from source, or the OOB artifacts might be distributed in the .NET Core SDK or Runtime.

But I think it's correct that we don't need this in source-build for another reason: based on the readme, it looks like the diagnostic tooling is always downloaded independently. That means that at least we won't have a feature gap in the source-built SDK itself.

/cc @dseefeld @crummel

**Comment by mikem8361** [comment]
Yes, everything in the diagnostics repo is shipped/downloaded as a dotnet CLI global tool.  Some of the tools (like SOS) even work across the various versions of the runtimes (1.1 to 3.x).

**Comment by am11** [comment]
For the new OS (/OS family) bring up, https://github.com/dotnet/source-build/blob/release/3.0/Documentation/boostrap-new-os.md, is there anything consumer need to do differently to get the sos plugin soon after CoreCLR build succeeds (like release/2.2)?

Was thinking about updating that document with new way of building diagnostics, but couldn't solve the chicken-egg problem, as it requires a well-known RID when building out of the band dotnet tools.
