### ISSUE TITLE
released 2.1.300 sdk prints it is a preview message

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#599]
When running sdk commands (e.g. `dotnet build`/`dotnet publish`) on rhel released 2.1.300 sdk, it prints out a message:

> You are working with a preview version of the .NET Core SDK. You
can define the SDK version via a global.json file in the current
project. More at https://go.microsoft.com/fwlink/?linkid=869452

This is due to:
```
./sdk/2.1.300/Microsoft.NETCoreSdk.BundledVersions.props:    <_NETCoreSdkIsPreview>true</_NETCoreSdkIsPreview>
```

In our `repos/cli.proj` we have:
```xml
<EnvironmentVariables Include="DropSuffix=true" />
```
and in `src/cli/build/MSBuildExtensions.targets` we have:
```xml
<_NETCoreSdkIsPreview Condition=" '$(DropSuffix)' != 'true' ">true</_NETCoreSdkIsPreview>
```

So it's not clear for me where things go wrong.

CC @omajid @dleeapho

**Comment by omajid** [comment]
cc @crummel

**Comment by dseefeld** [comment]
@tmds Is this failing for you?   Or is it just that the message says "preview" and you're able to continue?

**Comment by omajid** [comment]
It looks like the condition in the following task (in `src/cli/build/MSBuildExtensions.targets`) is never satisfied:

     <_NETCoreSdkIsPreview Condition=" '$(DropSuffix)' != 'true' ">true</_NETCoreSdkIsPreview>

But there is also this in the same file:

    <_NETCoreSdkIsPreview>$(_NETCoreSdkIsPreview)</_NETCoreSdkIsPreview>

Perhaps this is inheriting the default value, whatever that is? The bootstrap SDK defines a value for this already:

    Tools/dotnetcli/sdk/2.1.300-rc1-008673/Microsoft.NETCoreSdk.BundledVersions.props:    <_NETCoreSdkIsPreview>true</_NETCoreSdkIsPreview> 

As a workaround, adding this, just below the other `'$(DropSuffix)' != 'true' ` condition makes the message go away:

    <_NETCoreSdkIsPreview Condition=" '$(DropSuffix)' == 'true' ">false</_NETCoreSdkIsPreview>

**Comment by dleeapho** [comment]
For 2.1.1 I'm ok with having a patch.

**Comment by tmds** [comment]
I'm eager to learn why this is not working as expected :)

**Comment by dseefeld** [comment]
This appears to be an issue when building a stable version of source-build with a preview version of the SDK.  This needs more investigation, but moving out of 2.1.1 Servicing, since we're building 2.1.1 with stable 2.1.0 and the problem doesn't manifest in that case.

**Comment by tmds** [comment]
It's no longer important to look into this for 2.1. Maybe for 2.2 we'll see this again.
