### ISSUE TITLE
Add "--publish" to repos that use new RepoToolset version

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#604]
There's a new RepoToolset change that makes `--publish` a required parameter to publish artifacts. E.g., for the RepoToolset submodule itself, this:

https://github.com/dotnet/source-build/blob/cfc21efbb00f92cf384a4b457bbe3d8bd1d81e09/repos/roslyn-tools.proj#L5

should change to:

```xml
<BuildCommand>$(ProjectDirectory)\build$(ShellExtension) --pack --publish --configuration $(Configuration)</BuildCommand>
```

As RepoToolset users are updated to use the new toolset, source-build will need this change for each one.

**Comment by dseefeld** [comment]
This is pointing out an issue that may occur when repos update their SHAs.  We'll fix it when it breaks.  There is really nothing proactive that we can do with this.
