### ISSUE TITLE
Auto-update AspNetCore package versions from ProdCon builds

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#611]
These versions should be updated from the ProdCon build to remove a manual servicing build update step:

https://github.com/dotnet/source-build/blob/6ec0829d9b40171f512e4fad7920977c8570c8da/repos/cli.proj#L47-L52

**Comment by dagood** [comment]
We have to track these separately: ASP.NET Core intentionally versions each package independently. 2.1.3 built each of these:

```xml
<ExtraPackageVersionPropsPackageInfo Include="Microsoft.AspNetCore.All" Version="2.1.3" />
<ExtraPackageVersionPropsPackageInfo Include="Microsoft.AspNetCore.App" Version="2.1.3" />
<ExtraPackageVersionPropsPackageInfo Include="Microsoft.NET.Sdk.Razor" Version="2.1.2" />
```

FYI @dleeapho @dseefeld @crummel

**Comment by dseefeld** [comment]
Is this complete?

**Comment by dagood** [comment]
`release/2.1` and `release/2.2` do:

https://github.com/dotnet/source-build/blob/b5a02e93099cbef7ad5e6fce3800903322859f7c/dependencies.targets#L99-L103

https://github.com/dotnet/source-build/blob/f1c73c8babc0303b57ddf5f2355dacc38f229cd4/dependencies.targets#L99-L103

`master` doesn't have it, but it doesn't need it. It's only useful for uptaking ProdCon v1 builds. For 3.0, ProdCon v2 obviates this work and we'll have aspnet building from source anyway.

Closing as complete.
