### ISSUE TITLE
Change check-submodules behavior: notify by default, configurable prompt or disable

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#613]
`check-submodules.sh/ps1` is helpful if you mistakenly didn't `git submodule update` or have some dev changes you haven't cleaned up. However, it gets in the way if you're actually trying to make a custom runtime. We could change the current on/off to three modes to keep some of the benefit without getting in the way:

 * default: detect submodule checkout mismatches and notify the user. Notify the user how to set up the environment for the other two modes.
 * "prompt": the current behavior, where the user is prompted for what to do for each mismatch repo.
 * "disabled": don't check for mismatches.

This way, an observant user is notified of the mismatch, and they can set the default mode they like best by setting an env variable on their machine.

**Comment by dleeapho** [comment]
This is likely obviated by Arcade 'uber-clone'.

**Comment by MichaelSimons** [comment]
[Triage] This issue is obsolete, source-build no longer utilizes submodules.
