### ISSUE TITLE
Improve method used to determine if smoke-test is possible in CI legs

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#615]
Right now the build creates a txt file with the root repo, and smoke-test reads it to check if it makes to smoke-test at this level (added in https://github.com/dotnet/source-build/pull/589 so that work can continue on Core-Setup root):

https://github.com/dotnet/source-build/blob/62fc857befbec8bd73e6bdd33e5877c9cd3d36fb/smoke-test.sh#L10

Instead, we could hook up the msbuild projects directly somehow to get the information needed to decide if CI can smoke-test. (And maybe the maximum options for the smoke-test?) Idea from https://github.com/dotnet/source-build/pull/589#discussion_r196879314:

> This could actually be fixed pretty quick: have a `/t:RunSmokeTest` that checks what RootRepo ends up being, and only `Exec`s `smoke-test.sh` if RootRepo is enough. Then, instead of calling smoke-test.sh in CI, call `./build.sh /t:RunSmokeTest`.

**Comment by MichaelSimons** [comment]
[Triage] This issue is obsolete.  smoke-test.sh no longer exists.
