### ISSUE TITLE
Figure out how to set DotnetCLIVersion automatically

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#618]
We should figure out how to maintain the tooling SDK version at the N-1 version automatically.

**Comment by omajid** [comment]
This might be a stupid question, but how is N-1 version determined? I see that both 2.1.3 and 2.1.2 have  `2.1.301` in `DotnetCLIVersion.txt`. 2.1.1 has `2.1.300`.  Is it just a previous update? And in that case, why do 2.1.3 and 2.1.2 have the same cli version?

**Comment by dagood** [comment]
N-1 means the previous SDK release, and yeah, we haven't been consistent in applying it. (Hence this issue. :wink:) The SDK being any previous update seems *ok* since it means people should be able to use that N-x built-from source SDK to build N, but ideally we'd use N-1 for simplicity and getting new toolset features (e.g. for perf and reliability).

/cc @dseefeld

**Comment by MichaelSimons** [comment]
[Triage] The process to update the SDK is automated by a release pipeline.  PRs are automatically created as part of the release.
