### ISSUE TITLE
Baseline 2.1 prebuilt packages and allow comparison with master

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#630]
- [ ] Get a baseline of the prebuilt packages for our latest shipped release
- [ ] Verify that the list of packages is sensible
- [ ] Come up with a (preferably automated) process to compare baseline with a new build

**Comment by dagood** [comment]
Automating is already tracked by https://github.com/dotnet/source-build/issues/493.

**Comment by dseefeld** [comment]
Duplicate of #493
