### ISSUE TITLE
Get CI working through smoke-test

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#635]
Once core-sdk is building, re-enable smoke-test in CI.

**Comment by crummel** [comment]
My PR https://github.com/dotnet/source-build/pull/658 introduced two hacks in smoke-test that have to be removed after getting the associated scenarios passing:
- Disabling tests with remote sources and web tests in general (packages are not available yet).
- Replacing `netcoreapp2.1` with `netcoreapp3.0` in projects after `new` and before `restore`.

**Comment by dagood** [comment]
We should be good to go with 3.0.0-preview1 submodules set up and 3.0 preview1 Microsoft build released. Moving to backlog.

**Comment by dleeapho** [comment]
Closing since we have this working in 3.0 Preview 2.
