### ISSUE TITLE
Changing tasks/Microsoft.DotNet.SourceBuild.Tasks/vendor/ breaks roslyn

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#64]
I was trying to understand how new RIDs might be supported by source-build. So I made this change:

    diff --git a/tasks/Microsoft.DotNet.SourceBuild.Tasks/vendor/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs b/tasks/Microsoft.DotNet.SourceBuild.Tasks/vendor/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs
    index 2786534..36ceaac 100644
    --- a/tasks/Microsoft.DotNet.SourceBuild.Tasks/vendor/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs
    +++ b/tasks/Microsoft.DotNet.SourceBuild.Tasks/vendor/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs
    @@ -112,10 +112,27 @@ namespace Microsoft.DotNet.PlatformAbstractions.Native
                             result.VersionId = line.Substring(11).Trim('"', '\'');
                         }
                     }
    +                if (string.Equals(result.Id, "rhel", StringComparison.Ordinal))
    +                {
    +                   result = NormalizeRhelDistroInfo(result);
    +                }
                     return result;
                 }
                 return null;
             }
    + 
    +        // RHEL minor versions are backwards compatible. Normalize all 7.x
    +        // versions to '7'
    +        private static DistroInfo NormalizeRhelDistroInfo(DistroInfo distro)
    +        {
    +            var result = new DistroInfo(); 
    +            result.Id = distro.Id;
    +            if (distro.VersionId.StartsWith("7."))
    +            {
    +                result.VersionId = "7";
    +            }
    +            return result;
    +        }
     
             // I could probably have just done one method signature and put the #if inside the body but the implementations
             // are just completely different so I wanted to make that clear by putting the whole thing inside the #if.

Then building using `./build.sh` on RHEL 7.2 (actually 7.3 with `/etc/os-release` claiming `7.2`), causes the build to work until roslyn. Then it hits roslyn's Makefile:

    $(BINARIES_PATH)/dotnet-cli/dotnet publish -o $(TOOLSET_PATH)

Which fails without a `--runtime` flag.

**Comment by karajas** [comment]
Mentioned fix is merged, @omajid please let me know if you hit this again.
