### ISSUE TITLE
Fedora28 CI significantly slower than other Linux CI legs

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#648]
For example, for https://github.com/dotnet/source-build/pull/638 (chose a non-code PR to look at):

 * `22 min` CentOS https://ci.dot.net/job/dotnet_source-build/job/master/job/CentOS7.1_Release_prtest/62/
 * `21 min` Debian https://ci.dot.net/job/dotnet_source-build/job/master/job/Debian8.4_Release_prtest/53/
 * `1 hr 14 min` Fedora28 https://ci.dot.net/job/dotnet_source-build/job/master/job/Fedora28_Release_prtest/8/

The Fedora28 leg seems to have more warnings in the native compilation steps than CentOS, nothing else stands out, though.

@dseefeld do you know if this is expected with https://github.com/dotnet/source-build/pull/603? (Changing to running on Helix?)

**Comment by dseefeld** [comment]
@dagood Certainly not expected.  I looked at the vm configuration, and I don't see anything different than others.

**Comment by dagood** [comment]
@MattGal took a look at the queues and saw the machines are different: the faster legs are running on `D3_v2s` (4-core), and Fedora 28 runs on `D2_v3s` (2-core). It's possible to move Fedora up to `D4_v3` (closest to `D3_v2`) if the perf is worth it.

I don't think Fedora28 speed is affecting dev flow enough to justify it. The tarball legs won't get under `1h14m`, and the number of Fedora28 agents should keep up to PR demand.

We also can't be completely sure that upgrading will fix this completely. There might be something about Fedora28 that makes our PR builds slow.

(Recently I noticed there was only one Fedora28 agent up, causing a backlog, but Matt fixed that with https://github.com/dotnet/core-eng/issues/3991.)
