### ISSUE TITLE
Where should cli resolve platform packages from?

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#650]
I am on tag `v2.1.1`/`v2.1.301` of source-build. I noticed that changes I made to corefx to add more target platforms (via patch files thrown in `patches/corefx`) aren't making it through to the final SDK build. For example, one patch file contains changes like this:

pkg/Microsoft.NETCore.Platforms/runtimeGroups.props:
```diff
     <RuntimeGroup Include="rhel">
       <Parent>linux</Parent>
       <Architectures>x64</Architectures>
-      <Versions>7;7.0;7.1;7.2;7.3;7.4</Versions>
+      <Versions>7;7.0;7.1;7.2;7.3;7.4;7.5;7.6</Versions>
+    </RuntimeGroup>
```

pkg/Microsoft.NETCore.Platforms/runtime.json:
```diff
+    "rhel.7.5-x64": {
+      "#import": [
+        "rhel.7.5",
+        "rhel.7.4-x64"
+      ]
+    },
```

pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json:
```diff
+  "rhel.7.5-x64": [
+    "rhel.7.5-x64",
+    "rhel.7.5",
+    "rhel.7.4-x64",
+    "rhel.7.4",
+    "rhel.7.3-x64",
+    "rhel.7.3",
+    "rhel.7.2-x64",
+    "rhel.7.2",
+    "rhel.7.1-x64",
+    "rhel.7.1",
+    "rhel.7.0-x64",
+    "rhel.7.0",
+    "rhel.7-x64",
+    "rhel.7",
+    "rhel-x64",
+    "rhel",
+    "linux-x64",
+    "linux",
+    "unix-x64",
+    "unix",
+    "any",
+    "base"
+  ],
```

When I run the sdk (located at `./bin/x64/Release/dotnet-sdk-2.1.301-linux-x64.tar.gz`) using 

    COREHOST_TRACE=1 ./dotnet --version 2>&1 | grep rhel.7.5

I get nothing. It seems like my changes to corefx are not flowing across? Looking at `src/cli/msbuild.log`, I see:

    $ grep Microsoft.NETCore.Platforms src/cli/msbuild.log                              
                             Microsoft.NETCore.Platforms/2.1.0                                                        
                                     Name=Microsoft.NETCore.Platforms                                                 
                             Microsoft.NETCore.Platforms/2.1.0/.signature.p7s                                         
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/LICENSE.TXT                                            
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/THIRD-PARTY-NOTICES.TXT                                
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/microsoft.netcore.platforms.2.1.0.nupkg.sha512         
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/microsoft.netcore.platforms.nuspec                     
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/runtime.json                                           
                                     PackageName=Microsoft.NETCore.Platforms                                          
                             Microsoft.NETCore.Platforms/2.1.0/useSharedDesignerContext.txt                           
                                     PackageName=Microsoft.NETCore.Platforms                                         
                             Microsoft.NETCore.Platforms/2.1.0/version.txt                                           
                                     PackageName=Microsoft.NETCore.Platforms                                         
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0                                                       
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                             Microsoft.NETCore.Platforms/2.1.0
                                   Name=Microsoft.NETCore.Platforms

It looks like it's only using `Microsoft.NETCore.Platforms` version `2.1.0`? And never the version built by source-build (~~`2.1.1`~~ The source-built version is also 2.1.0). The build log also shows things like:

                             Microsoft.NETCore.Platforms/2.1.0
                                     Name=Microsoft.NETCore.Platforms
                                     Path=microsoft.netcore.platforms/2.1.0
                                     ResolvedPath=/home/omajid/source-build/packages/microsoft.netcore.platforms/2.1.0
                                     Type=package
                                     Version=2.1.0

Which also shows that the `ResolvedPath` is `source-build/packages`, not `source-build/bin/obj/x64/Release/blob-feed/`.

**Comment by dleeapho** [comment]
cc @weshaggard

**Comment by omajid** [comment]
@weshaggard Thanks. I am still quite confused. When I build source-build, isn't it building some version of Microsoft.NETCore.Platform package from the sources at `src/corefx/pkg/Microsoft.NETCore.Platforms/`? Where does that package end up? Is there no way to make a change (say, for local testing) in that package without bumping the version?

**Comment by weshaggard** [comment]
By default it only builds the packages we list in https://github.com/dotnet/corefx/blob/v2.1.1/src/packages.builds which we don't list any packages we don't plan to ship. So I did miss the fact that you would also need to add it to that list to be able to build it, or pass BuildAllPackages=true. 

If you do that without bumping the version it will produce a 2.1.0 which may conflict with the one we already shipped. If you are building offline and only using the packages you build it may still work but if there are any online feeds you still risk picking up packages from nuget.org.

**Comment by omajid** [comment]
> By default it only builds the packages we list in https://github.com/dotnet/corefx/blob/v2.1.1/src/packages.builds which we don't list any packages we don't plan to ship.

Aaaaah. Thanks! That makes a lot more sense now.

A general question about the design here: isn't the goal to build everything from source in source-build? Why would we want the final cli build in source-build to consume a Microsoft.NETCore.Platforms which is not from the source-build version of corefx?

**Comment by weshaggard** [comment]
That is a very good question and I agree that the general goal. We may want to consider always passing BuildAllPackages=true when doing a source-build.

**Comment by weshaggard** [comment]
I will fix this when I get some time, unless you would be interested in submitting a PR?

**Comment by omajid** [comment]
Sure. Let me try it out: if I can fix it, I will open a PR.

**Comment by omajid** [comment]
I opened a PR for this: #653

**Comment by dseefeld** [comment]
Assigning to @crummel to see if this is fixed with buildAllPackages
