### ISSUE TITLE
Search source-build submodules to find the latest roslyn-tools in use and drive updates

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#652]
Pretty often, the roslyn-tools version depended on goes out of sync across the repos in source-build. Since we have all the repos in one place, we can pretty easily determine the max version of roslyn-tools (repo toolset) that all the repos use by looking at their `global.json`s. We should use this information to drive updates in repos where necessary. For example, we can also see which repos are far behind.

This issue might just track finding the right `grep` command and raising awareness that this should be used to make sure toolsets are up to date.

In `master`, once RepoToolset/Arcade auto-updates are added, this shouldn't matter so much. In `release/2.1`, this will probably be useful for longer.

Thanks @tmat for the suggestion.

**Comment by MichaelSimons** [comment]
[Triage] Submodules are no longer used and roslyn-tools no longer exists.  Closing as obsolete.
