### ISSUE TITLE
"Broken pipe" after executing first build command

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#66]
Using the Fedora dockerfile on OSX 10.11.6, I get this error which fails the repository build:

```
Project "/sb/build.proj" (1) is building "/sb/targets/repository.proj" (3) on node 1 (Build target(s)).
Build:
  Executing /sb/src/standard/> /sb/src/standard/build.sh -Release -- /p:BuildVersionFile=/sb/bin/obj/BuildVersion.props
  /sb/src/standard/build.sh -Release -- /p:BuildVersionFile=/sb/bin/obj/BuildVersion.props
cat : write error : Broken pipe [/sb/targets/repository.proj]
```

I've also hit it in different environments. I haven't run enough builds to see if it's transient or not.

Has anyone else seen this? @ellismg

**Comment by karajas** [comment]
No repro since, please let me know if otherwise. Closing for now.
