### ISSUE TITLE
Documentation for Portable Builds

### ISSUE THREAD

**Issue by weshaggard** [dotnet/source-build#660]
@janvorli do we have any documentation on what our portable build means? What dependencies we can or cannot take? If not can we please add some notes about what we mean when we say portable.

cc @omajid

**Comment by omajid** [comment]
I know one particular piece: non-portable does not mean it will always use the native libraries from the system. See https://github.com/dotnet/coreclr/pull/17250.

**Comment by MichaelSimons** [comment]
[Triage] Closing in preference of tracking with https://github.com/dotnet/source-build/issues/2932.
