### ISSUE TITLE
source tarball is not useful across linux distributions

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#666]
It's common for the source-tarball published by a project to work across different platforms and linux distributions. This is not the case for the tarballs produced by source-build. In my experience, a tarball produced only works on the OS it was generated on. For example, a tarball built on RHEL 7 will generally not build on CentOS 7 nor on Fedora 27.

This isn't an urgent issue, but noting it here so it serves as a reminder and something to potentially fix in the future.

**Comment by omajid** [comment]
For another example, I built a source-tarball on Fedora 28. To make it work on other Fedora versions (26, 27, 29), I had to patch `Tools/configuration/configuration.props` whenever I need to build on another version:

    sed -i -E 's|fedora.[0-9]+(</RuntimeOS>)|fedora.%{fedora}\1|' Tools/configuration/configuration.props

`%{fedora}` is automatically replaced by Fedora's build system with the current version of Fedora.

**Comment by dagood** [comment]
After https://github.com/dotnet/source-build/pull/669 was merged for the Tools/configuration/configuration.props issue, are there any other issues that make the tarball not quite reusable? Should this be closed as resolved?

**Comment by omajid** [comment]
Just tested it out: f I remove `Tools/configuration/configuration.props` locally, I can rebuild the same `dotnet-2.1.2.tar.gz` tarball (generated by @crummel ?) on RHEL 7, CentOS 7 and Fedora 28 without further changes. This is fantastic! :tada:
