### ISSUE TITLE
Investigate OSX runtime.native.System.Security.Apple/OpenSsl prebuilts

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#697]
These prebuilts are odd, and we should prioritize understanding them because they end up in the product (even when the product isn't built for OSX):

```xml
<Package Name="runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple/4.3.0" PoisonEndsUpInOutput="true" />
<Package Name="runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0" PoisonEndsUpInOutput="true" />
```

/cc @crummel

**Comment by crummel** [comment]
These are included because we do not build portable like the official SDK does.  Once #717 and #718 are in we should be able to not include these assemblies by building portable.
