### ISSUE TITLE
Investigate XliffTasks prebuilt packages

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#698]
```xml
<Package Name="XliffTasks/0.2.0-beta-000081">
  <Project Name="/src/roslyn" />
  <Project Name="/src/roslyn-tools" />
</Package>
<Package Name="XliffTasks/0.2.0-beta-62730-03">
  <Project Name="/src/msbuild" />
</Package>
```

We should be able to unify these on the version of the package we build in source-build. This looks like a undeclared dependency problem (XliffTasks builds after these repos), but it might also be a PVP uptake issue.

This is hopefully low-hanging fruit, since we do build the xliff-tasks repo.

/cc @crummel

**Comment by crummel** [comment]
The simple fix of just adding the correct dependency didn't work - looks like this is a PVP problem.

**Comment by dseefeld** [comment]
This is fixed.  A single version of xliff tasks is now restored.
