### ISSUE TITLE
coreclr not producing NuGet packages, core-setup not using built coreclr as a result.

### ISSUE THREAD

**Issue by pauldotknopf** [dotnet/source-build#699]
I noticed this:

https://github.com/dotnet/source-build/blob/e50ba2d5a1bb0c8463e00aa9db49fc0e9774819f/repos/coreclr.proj#L9

The ```skipnuget``` causes the core-setup project to not find the coreclr nuget packages.

This causes the core-setup project to fetch the coreclr nuget packages from public feeds, instead of the one built locally.

Am I missing something?

**Comment by crummel** [comment]
Our ARM build isn't being kept up right now and likely doesn't even build without modifications.  We have a couple of related issues: https://github.com/dotnet/source-build/issues/324 and https://github.com/dotnet/source-build/issues/655.  This is definitely something we should fix when we do look at ARM again though, thanks!

**Comment by pauldotknopf** [comment]
Out of curiosity, how do you guys currently deploy the ARM SDK? Does each repo produce NuGet packages in their own custom CI pipeline?

**Comment by crummel** [comment]
Yes, the individual repos have ARM builds.  I don't think you'll be able to see the build itself, but you can see the status of core-sdk's ARM build on their readme, for instance: https://github.com/dotnet/core-sdk.

**Comment by MichaelSimons** [comment]
[Triage] Arm64 is officially supported.  This issue is very old.  If you are still having troubles building on ARM, please open a new issue with the current problems.
