### ISSUE TITLE
[SNAP] - Incorrect PATH

### ISSUE THREAD

**Issue by deinok** [dotnet/source-build#713]
Taking this, https://snapcraft.io/dotnet-sdk

Seems like dotnet-sdk, the CLI is installed as `dotnet-sdk.dotnet` insted of `dotnet`.
IDK if this is the correct repository to issue this bug.

**Comment by dagood** [comment]
It looks like Core-Setup is the right place for questions about this. The name seems intentional, based on https://github.com/dotnet/core-setup/issues/4230#issuecomment-398841315:

> The need to call dotnet using `dotnet-sdk.dotnet` has to do with how Snaps are constructed and exposed commands are accessed and the way that all interacts with the dotnet host. Retaining the Snap namespace for calling dotnet was the direction we wanted to experiment with first as it will allow distinct calling of install SDKs and Runtime versions. 
> 
> The easiest way to enable `dotnet <verb> for you will be to use Snap's alias feature. The following will get you going but will essentially tie the dotnet command to this Snap installed SDK.
> 
> `sudo snap alias dotnet-sdk.dotnet dotnet` 
> 
> This unfortunately does not get us past the SSL errors when projects are trying to restore.
