### ISSUE TITLE
Fix: use source-built Newtonsoft.Json 9.0.1, not online 9.0.1

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#716]
This is a subset of https://github.com/dotnet/source-build/issues/593. This issue focuses on making existing 9.0.1 usages use the source-built one. Other versions of the package will still be prebuilt. https://github.com/dotnet/source-build/issues/593 is broader, where all versions of Newtonsoft.Json should be replaced with the source-built 9.0.1.

This is detected by https://github.com/dotnet/source-build/pull/711 in `release/2.1`, as this usage:

```
{
  "UnusedPackages": [],
  "Usages": [
    {
      "ProjectDirectory": ".../src/common",
      "AssetsFile": ".../src/common/test/Microsoft.Extensions.CommandLineUtils.Tests/obj/project.assets.json",
      "PackageIdentity": "Newtonsoft.Json/9.0.1",
      "Annotation": null
    }
  ]
}
```

When we restore `common`, a test project restores Newtonsoft.Json. The test build is skipped, so test restore should be skipped, too, to avoid the problem.

Adding a dependency on the Newtonsoft.Json project and setting up the source-built restore source would also work, but doesn't seem necessary and would probably be more work.

**Comment by dseefeld** [comment]
Fixed with https://github.com/dotnet/source-build/pull/1118
