### ISSUE TITLE
Enable Toolset Bootstrapping

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#724]
This work requires setting up scripts to build the .NET Core toolset from source and then using the result to build source-build. This is to define the process and to ensure that it works consistently by adding CI.

Need to make sure this work is acceptable to packaging guidelines and will be what we want to submit to distro maintainers.

Need to build both SDK and Buildtools as part of bootstrapping.

**Comment by dleeapho** [comment]
@dseefeld can this also be closed?

**Comment by dseefeld** [comment]
Complete.
