### ISSUE TITLE
Should we be including System.CodeDom.dll in the SDK?

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#738]
Official SDK does but it seems it should be useless and the NuGet version should be used instead: https://github.com/dotnet/core/issues/1117.  Problem on their side or should we be including this for eventual use?

**Comment by dseefeld** [comment]
In production builds, System.CodeDom.dll was brought in by msbuild.  Source-build was behind with a number of repos that weren't built with prodcon.  Including newer versions of these repos fixed this issue.
