### ISSUE TITLE
Add commit id to core-setup builds

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#741]
The fix on the core-setup side: https://github.com/dotnet/core-setup/pull/4510

Once this is merged and we pull in a recent-enough version of core-setup, we will need to use it via something like:

```diff
--- a/repos/core-setup.proj
+++ b/repos/core-setup.proj
@@ -20,6 +20,8 @@
   </ItemGroup>
 
   <ItemGroup>
+    <EnvironmentVariables Include="CommitCount=$(GitCommitCount)" />
+    <EnvironmentVariables Include="LatestCommit=$(GitCommitHash)" />
     <EnvironmentVariables Include="OfficialBuildId=$(OfficialBuildId)" />
   </ItemGroup>
 
```

This is related to: https://github.com/dotnet/source-build/issues/651

**Comment by dagood** [comment]
We already have `LatestCommit` being passed here:

https://github.com/dotnet/source-build/blob/4f3eacdd0551677444ab917d4e332653672e0bd5/repos/dir.targets#L3-L4

("Offline" here just means it's a tarball build. Online, we expect `git` to be available to run in the submodule.)

CommitCount does need to be added though.

**Comment by dagood** [comment]
Sorry, looking at the scenario, noticed that `OfflineBuild` wouldn't be set. I don't see any reason not to always pass `LatestCommit`.

**Comment by omajid** [comment]
Oops. I saw similar chunks in `repos/cli.proj`, so didn't think to check in `repos/dir.targets`. Definitely agree on putting `LatestCommit` there too, and always.

Are `LatestCommit` and `CommitCount` well known variables that are shared across repositories? Should I propose a patch to cli (or other repos) to pick that up?
