### ISSUE TITLE
Fix prebuilt per-repo isolation

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#744]
To help with minimizing prebuilts, we should include only the necessary prebuilt packages when building each repo.

- Prebuilts should be put into a repo-specific directory when building the tarball.
- Source-built packages should still be removed from each prebuilt folder.
- Only each repo's prebuilt directory should be included in its prebuilt path.

**Comment by dagood** [comment]
Maybe gzip handles this well enough that we don't care, but we can avoid putting duplicates in the tarball if we make a list of all nupkgs needed in each repo's prebuilt folder, and copy/move them from a tarball dir that has the duplicates removed.

> Source-built packages should still be removed from each prebuilt folder.

Only if they're bitwise identical though--we can't remove a package if it was only source-built after it was used as a prebuilt.

**Comment by MichaelSimons** [comment]
[Triage] This has been superseded by https://github.com/dotnet/source-build/issues/2482.
