### ISSUE TITLE
Improve official build tarball file name

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#747]
With this line, we get names like `tarball_1987062.tar.gz`:

https://github.com/dotnet/source-build/blob/bb2b2d1f85f72ec61586cb82123e50fadd7d1f77/.vsts.pipelines/phases/ci-linux.yml#L35

We should figure out something better (and still maintainable).

Maybe `dotnet-source-build-{last part of branch}-{7 chars of commit hash}-{date}`, to be complete? E.g. ending up like:
 * `dotnet-source-build-2.1-abc4567-2018-09-04.tar.gz`.
 * `dotnet-source-build-2.1-abc4567-2018-09-04-smoke-test-prereqs.tar.gz`

To include the full 2.1.3 (or 2.1.401) branding ~~we'd have to auto-update it from somewhere and have it checked in, which doesn't seem worth it~~(edit: see below, there are some other ways). `2.1` should already be available as `$(Build.SourceBranchName)`.

**Comment by omajid** [comment]
Are you mostly concerned about the regular daily builds? or final public releases (eg, .NET Core 2.1.3)? Or both?

If you are producing release-style tarballs, I would strongly suggest a including the actual full version (`2.1.3`, not `2.1`). A common convention in various projects is to call their release tarball as `NAME-VERSION.(tar.gz|zip)`. So something like `dotnet-3.2.9.tar.gz` for a final release.

**Comment by dseefeld** [comment]
Note: Names should use the same pattern that is used for existing assets.  i.e. dotnet-<component>-<version>.ext  This will be relevant when we split runtime and SDK as well.

**Comment by MichaelSimons** [comment]
This will be addressed with the ArPow feature work.  The agreed upon file name will be `dotnet-sdk-source-<version>.tar.gz`.  This name is in alignment with the other .NET artifacts.
