### ISSUE TITLE
Automatically check out LKG commit when ProdCon v1 stops building a repository

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#748]
This series of events can result in bad source-build state:

1. Changes are put into repos (e.g.) `Tool` and `Runtime` in preparation for a release.
1. ProdCon builds, including both `Tool` and `Runtime`.
1. Source-Build updates `Tool` and `Runtime` submodules to match ProdCon.
1. Due to a design change, it's decided the changes in `Tool` won't be included in the next release.
1. ProdCon builds, only including `Runtime`.
   * Dependencies on `Tool` during this build are resolved by getting the previous release's packages from nuget.org.
1. Source-Build makes no update. ProdCon didn't convey any information about `Tool`, and `Runtime` is still using the same commit as last time.
   * Even if `Runtime` gets a commit and Source-Build gets auto-updated, dependencies on `Tool` still get the bad changes, because submodule outputs are always used, not nuget.org.
1. Now: the Source-Build SDK has the changed `Tool`, but ProdCon has the previous release's `Tool`.

I haven't looked through how to do it, but ideally we would move `Tool` back to the previous release (last known good) when ProdCon stops providing info about it.

(Another way to resolve the situation is to revert the changes in `Tool` and update the submodule, but this isn't suitable for automation.)

/cc @dleeapho @dseefeld @crummel

**Comment by mmitche** [comment]
To clarify, this basically means that mid-release we decide to remove a repo from prodcon, effectively pushing it back to the previous version, or whatever is in source?

If that's the case here, then we probably should error in the updater and then determine what to do next.  Here is why:
- There's no guarantee that a dependency update *didn't* happen in `Runtime` in the middle of the release.  For instance, if we had 5 successful builds and dependency updates on 2.1.5, then decided to remove `Tool` from the flow prior to release (E.g. `Tool` ships in VS and shuts down early), then reverting to the previous release is not correct.
- There's no guarantee that a dependency update *did* happen in `Runtime` after the last release.  Prodcon could be accidentally reverting back to a very old version (which is bad).  This provides a sentinel for that.

Ideally the updater would note the repos that should be in release X based on the decisions made in shiproom, then if the set provided after a build doesn't match, error out.  Then we would need to go and determine what the right set should, and whether the submodule commits are correct.

**Comment by dagood** [comment]
Yep, you got it. Good points.

Changing to error out rather than allowing this situation is as simple as removing these:

https://github.com/dotnet/source-build/blob/4f3eacdd0551677444ab917d4e332653672e0bd5/dependencies.targets#L88

However, that makes us vulnerable to the opposite scenario: if ProdCon *adds* a repo, we won't get an auto-update for it because we had to manually remove that linkage. So we also need to add something to VersionTools that lets us fail if something is added to ProdCon that we don't expect. (There are repos in ProdCon like ASP.NET's that we don't have submodules for, so we allowed this in the current implementation.)

I don't expect auto-update to work often, configured like that... but until we get ProdCon v2 where dependencies are more uniform and actually always trackable to the sources that produced them, that might just be a fact of life.

**Comment by mmitche** [comment]
Generally, the release branches have been fairly stable in terms of the repos we're building.  I've been biasing towards NOT adding or subtracting repos as much as possible.

I think we should add a check that ensures that the set of inputs is the same as the expected inputs.

**Comment by mmitche** [comment]
Btw, that previous comment also implies that occasionally we are updating dependencies outside of prodcon.

**Comment by dagood** [comment]
> I think we should add a check that ensures that the set of inputs is the same as the expected inputs.

Yeah, that'd be the end result of the two changes I mentioned. (Assuming "inputs" here means repo commit hashes.)

> Btw, that previous comment also implies that occasionally we are updating dependencies outside of prodcon.

If any repo we have a submodule for produces a package outside ProdCon that some inside-ProdCon repo takes a dependency on through a source change, I can't think of anything anyone can do to catch that in ProdCon v1.

It's starting to sound like auto-updates can't be trusted in any situation whatsoever. ProdCon simply doesn't have access to enough information (and therefore any followup automation).

**Comment by mmitche** [comment]
The only thing you can say is that if things auto-updated, then at least a build was done with those inputs.  You can't say anything past that though.

**Comment by dagood** [comment]
Here's where I'm at: any ProdCon-v1-build-based update needs in-depth vetting (it seems) to make accurate source-build changes. Erroring out if the set of repos doesn't match the expected/previous set gives the vetter a little more info to go on to produce the correct update.

I'm a little concerned that the repo set check will create a false sense of security, but I guess it's up to whoever's doing source-build updates not to get that sense.

By the way, this scenario has also concretely happened to us now:

> If any repo we have a submodule for produces a package outside ProdCon that some inside-ProdCon repo takes a dependency on through a source change, I can't think of anything anyone can do to catch that in ProdCon v1.

**Comment by dagood** [comment]
I chatted with @mmitche offline and we have some ideas to catch more stuff (in ProdCon v1 timeframe):

1. Automatically monitor the files in each repo that contain the dependency changes.
   * Since they have to work with the ProdCon v1 infra and this is how we override the versions in source-build, they're fairly standardized across repos.
   * Search for checked-in dependency changes that source-build cares about, comparing the old commit vs. the auto-update commit.
   * E.g.
     * https://github.com/dotnet/cli/blob/release/2.2.1xx/build/DependencyVersions.props.
     * https://github.com/dotnet/core-setup/blob/release/2.1/dependencies.props
     * (Every build that takes package flow in ProdCon v1 has a similar file, but these two repos bring together the most stuff.)
2. Compare the source-built version of a package to the checked-in dependency's version.
   * We can check the dependency files to see if our source-built package version is different from the checked-in package version.
   * This would catch the quoted scenario in my last comment.
   * To make this check succeed often, we have to make sure we run the builds with the right stabilization parameters. (https://github.com/dotnet/source-build/issues/550)

I think these would actually catch the problems we're facing.

**Comment by MichaelSimons** [comment]
[Triage]  A number of issues raised here are solved by source-build cloning the version.details.xml graph.  Additionally we have https://github.com/dotnet/source-build/issues/2222 tracking scenarios where a package is no longer getting source-build but still referenced.
