### ISSUE TITLE
Remove private Docker image infrastructure from VSTS build YAML

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#752]
There are some parts of the build definition YAML we can remove since we decided not to test on Red Hat images in https://github.com/dotnet/source-build/issues/677#issuecomment-417459491 (RHEL is only non-public image we currently use):

https://github.com/dotnet/source-build/blob/4f3eacdd0551677444ab917d4e332653672e0bd5/.vsts.pipelines/phases/ci-linux.yml#L2-L4

https://github.com/dotnet/source-build/blob/4f3eacdd0551677444ab917d4e332653672e0bd5/.vsts.pipelines/phases/ci-linux.yml#L45-L55

https://github.com/dotnet/source-build/blob/4f3eacdd0551677444ab917d4e332653672e0bd5/.vsts.pipelines/steps/docker-cleanup-linux.yml#L2-L6

https://github.com/dotnet/source-build/blob/4f3eacdd0551677444ab917d4e332653672e0bd5/.vsts.pipelines/builds/ci.yml#L12-L17

This should be applied to 2.1, 2.2, and master. (There might be more in the YAML, I skimmed through.)

**Comment by MichaelSimons** [comment]
[Triage]  This is obsolete.  Current build pipeline is all in AzDO and every leg builds within shared docker images.
