### ISSUE TITLE
Prebuilt baseline should warn by default (not error) to avoid blocking dev builds

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#770]
Baseline comparison is basically a test of the repo output. I think it should emit warnings, not errors, by default. CI should configure it to emit errors. A dev will either see the warnings and preemptively update the baselines, or see the errors in CI and update them then.

Another reason to do this is that in some cases, the baselines might be irrelevant, such as adding a new repo or making dev builds that won't necessarily be merged back into source-build. (E.g. creating a custom Microsoft.NETCore.App with experimental CoreCLR changes.)

**Comment by crummel** [comment]
Fixed in #776.
