### ISSUE TITLE
Archive all project.assets.json files in CI builds

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#774]
Looking at `project.assets.json` files that are generated throughout the repos is our primary way to track down dependency/restore problems. We should save them in CI to make issues much easier to diagnose. This is especially important for issues that don't repro that we suspect have something to do with transitive dependencies.

For a local build, all `project.assets.json` files gathered together is 68 MB. Putting them in `tar -zcf` reduces that to 6 MB.

I think the usage report infra should (while it looks at these files anyway) put them all in an archive in the report directory, where it will be picked up by CI automatically.

This idea came up for the baseline issue in https://github.com/dotnet/source-build/pull/766 that just seems random so far.

/cc @dseefeld

**Comment by crummel** [comment]
Fixed in #776.
