### ISSUE TITLE
Remove linker repo '-h' patch adding reflection heuristics

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#777]
There are a few ways like these that would make the patch go away:

 * Merge the change into mono/linker.
 * Create a dotnet/linker fork where the feature is maintained.

**Comment by crummel** [comment]
Might end up being taken by Linker after all; mono/linker#626.

**Comment by sbomer** [comment]
@dagood The patch should no longer be required with the latest linker updates. We're using sources straight from mono/linker now.

**Comment by MichaelSimons** [comment]
[Triage]  Closing - All linker patches have been eliminated.
