### ISSUE TITLE
Include 'prebuilt/source-built/' packages in prebuilt report

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#784]
These are different than the prebuilts acquired from the NuGet gallery, since they can in theory be taken from an N-1 build, and they are at least known to have been built during the online source-build build.

Reasons to reduce this set of packages:
* Make the set of packages pulled in from N-1 smaller, to simplify.
* Reduce the size of our online-built tarball artifact by not including some packages.
  * As of https://github.com/dotnet/source-build/pull/781#issuecomment-422945569 these prebuilts were ~330 MB.

**Comment by dagood** [comment]
Once these are reported, it'll be easier to tell what we have to do to get them from an N-1 build and force the repos to use them instead of the version checked in. (Right now `prebuilt/source-built/` packages will be used if the version happens to match what the repo asks for, but we don't force version uptake like we do during PVP flow.)

**Comment by MichaelSimons** [comment]
[Triage] This has been implemented some time ago - https://github.com/dotnet/installer/blob/fb1775d03b6b1fda596c97aed2d63389e6b7c713/src/SourceBuild/tarball/content/tools-local/init-build.proj#L213
