### ISSUE TITLE
CoreFX fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by deinok** [dotnet/source-build#799]
OS: Ubuntu18.04_amd64_server
Source-build commit: 92546b3
CoreFX commit: 9dfcd8f
Trying to build CoreFX using the `build.sh` script of `./src/corefx/` fails on the native steps

**Comment by wfurt** [comment]
this is probably because of openssl-1.1. You will need 3.0/master branch or you will need openssl1.0 headers. You can check prerequisites on corefx wiki. Source build will not help you with that.
