### ISSUE TITLE
Cross directory as git submodule

### ISSUE THREAD

**Issue by deinok** [dotnet/source-build#804]
Seems like a lot of projects use /cross, but changes to that folder need to be ported to other repositories.
In order to centralize that common part, I think that the creation of a repository and then add the /cross folder as a git submodule should work pretty well. 

https://github.com/dotnet/coreclr/pull/20202#issuecomment-425836152

**Comment by dagood** [comment]
Centralizing the cross scripts is tracked by https://github.com/dotnet/arcade/issues/53. The plan of record isn't to use submodules, but rather to share the infra that is being set up to centralize all the basic build scripts.
