### ISSUE TITLE
Update ARM crossbuild image

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#811]
We are currently using microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20172211042239.  This image is missing clang-5.0, now required by CoreCLR.  Once I installed clang-5.0 manually, I started running into https://github.com/dotnet/source-build/issues/514, so it seems like the LLVMgold requirement may apply for all builds now, or there may be another switch we have to turn off - this will require either another change to the image or a change to our flags in repos/coreclr.proj.

**Comment by MichaelSimons** [comment]
[Triage] Closing as obsolete.
