### ISSUE TITLE
Investigate and remove poisoned file leaks

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#812]
[Latest leak report](https://ci.dot.net/job/dotnet_source-build/job/release_2.1/job/CentOS7.1_Tarball_Release/lastSuccessfulBuild/artifact/tarball-output/bin/prebuilt-report/poison-usage.xml/*view*/).

- dotnet-sdk-2.1.403-linux-x64.tar.1/sdk/2.1.403/Microsoft.DotNet.Archive.dll - known issue #591.
- dotnet-sdk-2.1.403-linux-x64.tar.1/sdk/2.1.403/System.CodeDom.dll - result of an old version of MSBuild, fixed now.
- dotnet-sdk-2.1.403-linux-x64.tar.1/sdk/2.1.403/System.Text.Encoding.CodePages.dll - was at one point included with an old version of a repo (not sure which one), fixed now.
- template packages - known inclusions, include no binaries, #257.
- dotnet-sdk-2.1.403-linux-x64.tar.1/shared/Microsoft.NETCore.App/2.1.5 - new inclusions
- dotnet-sdk-2.1.403-linux-x64.tar.1/sdk/2.1.403/Microsoft/Microsoft.NET.Build.Extensions - known core-setup issue (number?)

dotnet-sdk-internal and dotnet-sdk-langpack do not need to be included in this investigation as they do not ship.

**Comment by crummel** [comment]
@crummel to update for 3.0.

**Comment by MichaelSimons** [comment]
[Triage] There are new active issues for the specific issues in the current poison report.  Closing.
