### ISSUE TITLE
release/2.2 source-built SDK includes prebuilt binaries from Microsoft.NET.Sdk.Razor preview3

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#822]
https://github.com/dotnet/source-build/pull/821 (2.2.0-preview3) upgraded Microsoft.NET.Sdk.Razor from `2.2.0-preview2-35157` to `2.2.0-preview3-35497`.

Microsoft.NET.Sdk.Razor is built by ASP.NET Core, and the CLI repo uses it as a prebuilt. The `preview2` version was text-only and an acceptable prebuilt, but `preview3` added some task DLLs. These do get into the source-built CLI output:

```
./sdk/2.2.100/Sdks/Microsoft.NET.Sdk.Razor/tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll
./sdk/2.2.100/Sdks/Microsoft.NET.Sdk.Razor/tasks/netstandard2.0/Microsoft.NET.Sdk.Razor.Tasks.dll
```

This Microsoft.NET.Sdk.Razor package [*is* on nuget.org](https://www.nuget.org/packages/Microsoft.NET.Sdk.Razor/2.2.0-preview3-35497)… so maybe we can just force CLI not to bundle it while source-building and let the MSBuild NuGet SDK resolver fetch it from the network on demand. I don't know one way or the other whether the mechanism will work as-is.

/cc @dleeapho @dseefeld @crummel

**Comment by crummel** [comment]
I'm getting
```
/home/chris/testing/sdk/2.2.100/Sdks/Microsoft.NET.Sdk.Web/Sdk/Sdk.targets(16,11): error MSB4236: The SDK 'Microsoft.NET.Sdk.Razor' specified could not be found. [/home/chris/testing/app/app.csproj]

The build failed. Please fix the build errors and run again.
```
when I try to run a Razor project so I don't think the easy fix is enough.  Looking into a smarter fix now.

**Comment by crummel** [comment]
Based on the comments in https://github.com/aspnet/Razor/issues/2553 I'm not sure that any fix that doesn't include the binaries in this package is really valid - it seems like we would just bring that issue back for source-build users.  I tried added the Razor repo to source-build but it doesn't seem like an easy repo; we might have to depend on ASP.NET being source-buildable in general.

**Comment by natemcmaster** [comment]
> Is there a way to defer acquiring the Microsoft.NET.Sdk.Razor package until restore/run?

No. This is in-box with Microsoft.NET.Sdk.Web by design.

**Comment by dagood** [comment]
Any other ideas how to make this work with source-build?

The only thing I can think of to fix this potentially quickly (i.e. without forcing design changes) is to add https://github.com/aspnet/Razor/tree/master/src/Microsoft.NET.Sdk.Razor to source-build in a very targeted fashion. The csproj looks simple enough, maybe it's an iceberg though.

**Comment by natemcmaster** [comment]
What did you do in 2.1? Microsoft.NET.Sdk.Razor isn't new in 2.2.

**Comment by dagood** [comment]
It's ok as a prebuilt that ends up in the product in `2.1.*` and `2.2.0-preview2` because the package only has text (and is therefore maintainable by distro maintainers). `2.2.0-preview3` adds DLLs which make it not acceptable as a prebuilt.

**Comment by natemcmaster** [comment]
Adding Razor in a target fashion is probably the best we can do for now then. We still don’t really support aspnet in source build but I get that this would be a step back from 2.1 so it’s not an option to drop this. 

FYI - we’re going to merge aspnet/Razor into aspnet/AspNetCore in the next few weeks. That will probably impact servicing.

**Comment by dagood** [comment]
Fixed with https://github.com/dotnet/source-build/pull/839 by adding the aspnet-razor submodule. Thanks for your input, Nate!
