### ISSUE TITLE
cli including store packages [2.0]

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#83]
@omajid and I asked some questions on this PR: https://github.com/dotnet/cli/pull/6460 which were unanswered, so I am creating this issue.

In the meanwhile I got some more info as I hit an issue when publishing an mvc application: https://github.com/dotnet/cli/issues/6516.

I think the PR is to populate the store with typical ASP.NET packages. Those packages will no longer be included on publish.

For RHEL, we don't want to ship binary blobs we are not building. So it would be great if we can build the CLI and not include the packages. Instead, we can include the manifest file. Then the user can use the manifest to install those packages in his store.

Does this make sense? Can we make this happen?

CC @JunTaoLuo @ellismg @bleroy @davidfowl @eerhardt @livarcocc @aslicerh

**Comment by karajas** [comment]
@tmds Do you know if there is any activity on this issue? Can this be merged with the greater ASP.NET effort, @Eilon ?

**Comment by tmds** [comment]
@karajas afaik no one is looking at this yet.

**Comment by Eilon** [comment]
Is this still true with ASP.NET Core 2.0.0? We did a big push before the release to standardize the references of the ASP.NET Core 2.0.0. It's certainly possible we missed some. But, also, many of the packages mentioned above come from other teams at Microsoft, or are 3rd party packages.

**Comment by tmds** [comment]
@Eilon Perhaps there is no more work to be done for ASP.NET Core. For the other Microsoft and 3rd party packages, it's a matter of reaching out to those folks. Most library maintainers will be happy to reduce their dependency size by using the NETStandard.Library package.

**Comment by Eilon** [comment]
Yeah it would be good to re-check and see what the current problem places are (if any).

**Comment by tmds** [comment]
Are there some changes for 2.1?
- in the way the runtime store is distributed?
- whether those packages can be built from source and bundled for use with the runtime?

**Comment by omajid** [comment]
> in the way the runtime store is distributed?

Based on my understanding, the runtime store is going away in 2.1. There are just too many issues with it. It will be replaced by a asp.net core shared framework. I don't know that means in practice and whether everything will be built from source by 2.1 time-frame.

**Comment by tmds** [comment]
@DamianEdwards @JunTaoLuo Is the idea we will be able to built the asp.net core shared framework for 2.1 from https://github.com/aspnet/universe? Or should we disable the shared framework dependency during publish (similar to what we have done for 2.0 via PublishWithAspNetCoreTargetManifest=false)?
