### ISSUE TITLE
Packages built with a custom corefx branch fail to update beyond the first build

### ISSUE THREAD

**Issue by steveisok** [dotnet/source-build#837]
Ok, this *should* be pretty easy to reproduce.  

Environment: **Ubuntu 16.04**

1.) Follow the instructions for pointing to a  custom corefx branch https://github.com/dotnet/source-build/blob/master/Documentation/README.md#building-a-custom-net-runtime

2.) Build source build (./build.sh /p:RootRepo=core-setup)

3.) Note the package version of the Microsoft.NETCore.App nuget package 

4.) Go back into src/corefx and make some kind of commit.

5.) Commit the submodule change to source-build root and build again.

6.) Note the package version of Microsoft.NETCore.App nuget package. 

Result: 
The nuget package commit will always be the first commit in your custom branch

Expected Result:
The nuget package(s) should update with the new commit

NOTE: 
I was able to successfully build once I did a clean AND I deleted the obj, packages, and Tools directories.

**Comment by MichaelSimons** [comment]
[Triage] Closing as obsolete.  Much of the source-build infra has changed since this was originally opened.  Please retry with 7.0 and opened a new issue with any problems you encounter.
