### ISSUE TITLE
Move Microsoft.Extensions.CommandLineUtils into NuGet repository

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#849]
This idea came up in https://github.com/aspnet/Extensions/pull/445 (`common` submodule):

We only use the `common` project to source-build `Microsoft.Extensions.CommandLineUtils 1.0.1`, which is only used by `nuget-client`. We use the `servicing/1.0.x` branch of `common`:

> [@natemcmaster] The servicing branch is dead from a functional perspective. It only exists to support source-build and the NuGet client's dependency on Microsoft.Extensions.CommandLineUtils 1.x. We don't plan to ship updates to Microsoft.Extensions.CommandLineUtils.
> 
> An alternative solution, which I highly recommend, is to copy the sources of Microsoft.Extensions.CommandLineUtils into NuGet.

If the package's sources are moved to `nuget-client`, we could remove `common` from source-build. That means the NuGet team can do whatever maintenance they need, and since we regularly upgrade the `nuget-client` submodule, we would get fixes without extra effort.

@rrelyea, does this suggestion sound reasonable?

/cc @dseefeld @dleeapho

**Comment by crummel** [comment]
This is being handled by ASP.NET.
