### ISSUE TITLE
Include ref-only packages in prebuilt report

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#866]
Including ref-only prebuilts as IL in the tarball is ok because the IL can be maintained, but it's still better if we can avoid them altogether. We should include these in the prebuilt report with proper annotations for tracking purposes. (Right now, they're just removed.)

**Comment by dagood** [comment]
@dseefeld I'm thinking about how this affects the dashboard... would just adding an attribute to the `AnnotatedUsage` affect the packageversion count delta? Is that fixable? Or should I try something different like change the element name or only include it in the other (not `annotated-usage.xml`) files?

If an attribute is ok, another thought is that I should always include the annotation with true/false, so when/if they all go away it doesn't break the report like the test annotations.

**Comment by dagood** [comment]
I'm probably overthinking it and adding a `RefOnlyPrebuilt="true/false"` is fine. Let me know if something else would be better. 🙂

**Comment by dseefeld** [comment]
Ref-only prebuilts as IL was removed in 5.0.  Tracking these no longer applies.  Closing.
