### ISSUE TITLE
release/2.2 source-built SDK contains Microsoft.Web.XmlTransform.dll from nuget package

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#867]
Microsoft.Web.XmlTransform.dll showed up in release/2.2 as an additional poisoned package. This is not there in release/2.1.  This should be addressed with the issue to Investigate and remove poisoned file leaks.  See #812

**Comment by crummel** [comment]
@crummel to check if this is still relevant

**Comment by MichaelSimons** [comment]
release/2.2 is EOL.  Closing
