### ISSUE TITLE
Analyze prebuilts for cli

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#880]
The following prebuilt packages are included as dependencies in source-build by **cli**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## Prebuilt Table Updated 2019-05-07

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.DotNet.Cli.CommandLine | 0.1.1 | 1.0.0-dev.19208.1 

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  
Microsoft.DotNet.Cli.CommandLine | 0.1.1 | 1.0.0-dev.19074.1 
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |  
Microsoft.SymbolUploader.Build.Task | 1.0.0-beta-63604-05 |  
Microsoft.TemplateEngine.Abstractions | 1.0.2-beta5.19066.2 |  
Microsoft.TemplateEngine.Cli | 1.0.2-beta5.19066.2 |  
Microsoft.TemplateEngine.Orchestrator.RunnableProjects | 1.0.2-beta5.19066.2 |  
Microsoft.TemplateEngine.Utils | 1.0.2-beta5.19066.2 |  
Microsoft.Win32.Registry | 4.3.0 |  
Newtonsoft.Json | 11.0.1 | 9.0.1 
System.Diagnostics.TextWriterTraceListener | 4.3.0 |  
System.Diagnostics.TraceSource | 4.3.0 |  
System.Private.DataContractSerialization | 4.3.0 |  
System.Runtime.InteropServices.RuntimeInformation | 4.3.0 |  
System.Runtime.Serialization.Primitives | 4.3.0 |  
System.Text.Encoding.CodePages | 4.5.0 |  
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 
sn | 1.0.0 |  
vswhere | 2.5.2 |

**Comment by nguerrera** [comment]
This one needs more investigation.

**Comment by nguerrera** [comment]
#### (1) Should be source built version, is dotnet/templating missing from source-build?
Microsoft.TemplateEngine.Abstractions | 1.0.2-beta5.19066.2 |   |  
Microsoft.TemplateEngine.Cli | 1.0.2-beta5.19066.2 |   |  
Microsoft.TemplateEngine.Orchestrator.RunnableProjects | 1.0.2-beta5.19066.2 |   |  
Microsoft.TemplateEngine.Utils | 1.0.2-beta5.19066.2

#### (1)Should be source built, version inherited by arcade
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048

#### (1) Should be source built version
Microsoft.DotNet.Cli.CommandLine | 0.1.1 | 1.0.0-dev.19074.1


#### (1) Should be source built version, but 9.0.1 is too old as dependencies have 10.0.3. We are referencing 10.0.3, not sure where 11 came from
Newtonsoft.Json | 11.0.1 | 9.0.1



### (2) Should not be used, already removed by arcade
sn | 1.0.0 |   |  
vswhere | 2.5.2
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6

### (2) Should not be used, removed by PR in progress to dotnet/cli
Microsoft.Win32.Registry | 4.3.0 |   |  
System.Diagnostics.TextWriterTraceListener | 4.3.0 |   |  
System.Diagnostics.TraceSource | 4.3.0 |   |  
System.Private.DataContractSerialization | 4.3.0 |   |  
System.Runtime.InteropServices.RuntimeInformation | 4.3.0 |   |  
System.Runtime.Serialization.Primitives | 4.3.0 |   |  
System.Text.Encoding.CodePages | 4.5.0

**Comment by nguerrera** [comment]
@dseefeld  https://github.com/dotnet/source-build/blob/master/Documentation/SourceBuildPrebuiltRepoStatus.md shows templating as complete and "removed from source build". This seems like an error. templating is needed.

**Comment by dseefeld** [comment]
@nguerrera Thanks for the feedback.  When moving to 3.0 preview 2 it was removed because we weren't even using the version that was being built.  The plan is to add it back in and figure out why it wasn't getting picked up.  https://github.com/dotnet/source-build/issues/994

**Comment by nguerrera** [comment]
OK, I reopened #895, and reset the status in #996

**Comment by dseefeld** [comment]
All direct-dependency prebuilts removed.
