### ISSUE TITLE
Analyze prebuilts for cli-migrate

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#881]
The following prebuilt packages are included as dependencies in source-build by **cli-migrate**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## Prebuilt Table Updated 2019-05-07

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.DotNet.Cli.Utils | 1.0.1 | 3.0.100-dev.19212.2 

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  
Microsoft.DotNet.Cli.Utils | 1.0.1 | 3.0.100-dev.19075.1 
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |  
System.Collections.Specialized | 4.3.0 |  
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 
sn | 1.0.0 |  
vswhere | 2.5.2 |

**Comment by nguerrera** [comment]
### (1) should be source-built version
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048

### (3) reference only (causes a cycle and can't be source built version)
Microsoft.DotNet.Cli.Utils | 1.0.1 | 3.0.100-dev.19075.1


### (2) not needed in source build, already removed by arcade
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |   |  
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |   |  
sn | 1.0.0 |   |  
vswhere | 2.5.2

### (5) needs investigation
System.Collections.Specialized | 4.3.0

**Comment by nguerrera** [comment]
Investigation for System.Collections.Specialized - https://github.com/dotnet/cli-migrate/pull/116

**Comment by nguerrera** [comment]
@livarcocc Are we removing migrate from 3.0?

**Comment by nguerrera** [comment]
Migrate has been removed. #1055 tracks removing it from source-build.
