### ISSUE TITLE
Analyze prebuilts for common repo

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#882]
The following prebuilt packages are included as dependencies in source-build by **common**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
System.Console | 4.0.0 |  | Removal dependent on #849
System.IO | 4.1.0 |   | Removal dependent on #849
System.Linq | 4.1.0 |   | Removal dependent on #849

**Comment by natemcmaster** [comment]
If it were me, I would close this in favor of https://github.com/dotnet/source-build/issues/849 or https://github.com/dotnet/source-build/issues/890. We're not planning on making any changes to aspnet/common's 1.x branch. It exists in source-build only to serve NuGet.Client.

**Comment by dagood** [comment]
@rrelyea Can you comment on whether #849 "Move Microsoft.Extensions.CommandLineUtils into NuGet repository" is doable to clean this up?

**Comment by natemcmaster** [comment]
Un-assigning myself because I am not planning on taking action on this.

**Comment by dseefeld** [comment]
All direct-dependency prebuilts removed.
