### ISSUE TITLE
Analyze prebuilts for coreclr

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#883]
The following prebuilt packages are included as dependencies in source-build by **coreclr**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Prebuilt Table Updated 2019-05-07~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Cci | 4.0.0-rc3-24214-00 |  
Microsoft.Net.Compilers.Toolset | 3.1.0-beta2-19206-01 | 3.1.0-beta2-19067-14 
Microsoft.Net.Compilers.netcore | 2.6.0-beta3-62316-02 |  
Newtonsoft.Json | 10.0.3 |  

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Cci | 4.0.0-rc3-24214-00 |  
Microsoft.NETCore.Compilers | 2.9.0 | 3.0.0-beta3-19067-14 
Microsoft.Net.Compilers.netcore | 2.6.0-beta3-62316-02 |  
Newtonsoft.Json | 10.0.3 | 9.0.1 
System.Diagnostics.FileVersionInfo | 4.3.0 |  
System.Diagnostics.TraceSource | 4.3.0 |  
System.IO.FileSystem | 4.3.0 |  
System.Reflection.Metadata | 1.4.1 |  
System.Runtime.InteropServices | 4.3.0 |

**Comment by RussKeldorph** [comment]
We're hoping most of these will go away once we move off of dotnet/buildtools.

A cursory search seems to indictate that this repo doesn't use coreclr's `build-test.*` scripts, which is good, because removing the buildtools dependency from the test build is going to be much more work.

**Comment by RussKeldorph** [comment]
We are targeting week of April 8 to be off buildtools, at which point we also expect to drop all of these prebuild dependencies.

**Comment by jashook** [comment]
@swaroop-sridhar most of the System.* package references seem to be coming from SOS

**Comment by swaroop-sridhar** [comment]
I don't (yet) have access to the report, but I see the dependencies in the [csproj file](https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/NETCore/SOS.NETCore.csproj).

[Upcoming changes](https://github.com/swaroop-sridhar/coreclr/commit/4ac0e7c3dc4d8a4fbbcd1010e871df9821b8af8a#diff-a7089ede544f4fd0fcd6967150b864f9) to the SOS project will remove 2/3 of these `ProjectReferences.`
But the `SymbolReader` does use `System.Reflection.Metadata` implementation. So, this should be built from source(?).

CC: @mikem8361

**Comment by dseefeld** [comment]
@jashook @swaroop-sridhar I gave you both access to the report.

**Comment by ericstj** [comment]
Just chiming in here as this came up in tactics.  I took a look at these and most seem to be coming in from the old build-tools "tool-runtime".  @RussKeldorph mentioned this is going away, seems like that is the last bit blocking here.

**Comment by RussKeldorph** [comment]
@ericstj We believe CoreCLR has removed its buildtools dependencies.  It's just a bit of work to verify it since source-build doesn't build with 3.0 yet, and we broke the ability to build CoreCLR with 2.x.  @jashook is looking at dotnet/coreclr/#24888.
