### ISSUE TITLE
Analyze prebuilts for core-setup

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#885]
The following prebuilt packages are included as dependencies in source-build by **core-setup**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Additional prebuilt from @adaggarwal 2019-06-20~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Newtonsoft.Json | 9.0.1 | | Ref-only

## ~~Additional prebuilt mentioned in email 2019-06-06~~

https://github.com/dotnet/core-setup/issues/6730

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
System.Reflection.Metadata | 1.5.0 | | Needs to be source-built

## ~~Prebuilt Table Updated 2019-05-07~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.7.0-preview-000143 | 16.0.461 
Microsoft.Build.Tasks.Core | 15.7.0-preview-000143 | 16.0.461 
Microsoft.Build.Utilities.Core | 15.7.0-preview-000143 | 16.0.461 
Microsoft.Build | 15.7.0-preview-000143 | 16.0.461 
Microsoft.Cci | 4.0.0-rc3-24214-00 |  
Microsoft.DiaSymReader.Native | 1.7.0 |  
Microsoft.Extensions.DependencyModel | 2.1.0-preview2-26306-03 | 3.0.0-preview4-27615-11 
Microsoft.Net.Compilers.Toolset | 3.1.0-beta2-19206-01 | 3.1.0-beta2-19067-14 
Microsoft.Net.Compilers.netcore | 2.6.0-beta3-62316-02 |  
Newtonsoft.Json | 10.0.3 |  
NuGet.ProjectModel | 4.3.0-preview2-4095 | 5.1.0-rtm.5921 
System.Memory | 4.5.2 |  

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.7.0-preview-000143 | 16.0.0-preview.385 | Ref-only (build)
Microsoft.Build.Tasks.Core | 15.7.0-preview-000143 | 16.0.0-preview.385 | Ref-only (build)
Microsoft.Build.Utilities.Core | 15.7.0-preview-000143 | 16.0.0-preview.385 | Ref-only (build)
Microsoft.Build | 15.7.0-preview-000143 | 16.0.0-preview.385 | Ref-only (build)
Microsoft.Cci | 4.0.0-rc3-24214-00 | | BuildTools
Microsoft.DiaSymReader.Native | 1.7.0 | | Complicated: https://github.com/dotnet/core-setup/issues/5297
Microsoft.Extensions.DependencyModel | 2.1.0-preview2-26306-03 | 3.0.0-preview-27324-5 | Ref-only (build)
Microsoft.NETCore.Compilers | 2.9.0 | 3.0.0-beta3-19067-14 | BuildTools
Microsoft.Net.Compilers.netcore | 2.6.0-beta3-62316-02 | | BuildTools
Newtonsoft.Json | 10.0.3 | 9.0.1 | BuildTools
Newtonsoft.Json | 11.0.1 | 9.0.1 | [Replace with CoreFX JSON](https://github.com/dotnet/core-setup/issues/3311)
NuGet.ProjectModel | 4.3.0-preview2-4095 | 5.0.0-preview1.5754 | Ref-only (build)
System.AppContext | 4.1.0 | | Ref-only
System.Diagnostics.FileVersionInfo | 4.0.0 | | Ref-only (build)
System.Diagnostics.FileVersionInfo | 4.3.0 | | BuildTools
System.Diagnostics.TraceSource | 4.3.0 | | BuildTools
System.Dynamic.Runtime | 4.0.11 | | Ref-only
System.IO.FileSystem | 4.0.1 | | Ref-only
System.IO.FileSystem | 4.3.0 | | BuildTools
System.IO | 4.1.0 | | Ref-only
System.Linq | 4.1.0 | | Ref-only
System.Reflection.TypeExtensions | 4.1.0 | | Ref-only
System.Runtime.Extensions | 4.1.0 | | Ref-only
System.Runtime.<br/>InteropServices.RuntimeInformation | 4.0.0 | | Ref-only
System.Runtime.InteropServices | 4.1.0 | | Ref-only

> * *Ref-only (build)*: ref used to compile MSBuild build tasks, but I believe MSBuild uses the implementation from the SDK or Shared Framework.
> * *BuildTools* : A dependency of BuildTools. Should be replaced by Arcade SDK.

**Comment by adaggarwal** [comment]
@dseefeld  : Can we update source-built newtonsoft.json version to 12.0.2?

**Comment by dseefeld** [comment]
> @dseefeld : Can we update source-built newtonsoft.json version to 12.0.2?

@adaggarwal You can just add it to the table.  These aren't auto updated.

**Comment by dseefeld** [comment]
All prebuilts removed.
