### ISSUE TITLE
Analyze prebuilts for fsharp

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#886]
The following prebuilt packages are included as dependencies in source-build by **fsharp**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Prebuilt Table Updated 2019-06-24~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
FSharp.Core | 4.6.2 | | Exclude from source build |
System.Collections.Immutable | 1.5.0 | | Ref-only |
System.Reflection.Metadata | 1.6.0 | | Ref-only |
System.Runtime.Loader | 4.3.0 | | Ref-only |

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
FSharp.Core | 4.5.2 |  
Microsoft.Win32.Registry | 4.3.0 |  
Pdb2Pdb | 1.1.0-beta1-63314-01 |  
System.Collections.Immutable | 1.4.0 |  
System.Data.SqlClient | 4.3.0 |  
System.Diagnostics.Process | 4.3.0 |  
System.Diagnostics.TraceSource | 4.3.0 |  
System.Linq.Expressions | 4.3.0 |  
System.Linq.Queryable | 4.3.0 |  
System.Net.Requests | 4.3.0 |  
System.Net.Security | 4.3.0 |  
System.Reflection.Emit | 4.3.0 |  
System.Reflection.Metadata | 1.5.0 |  
System.Reflection.TypeExtensions | 4.3.0 |  
System.Runtime.InteropServices | 4.3.0 |  
System.Runtime.Loader | 4.3.0 |  
System.Runtime | 4.3.0 |  
System.Security.Claims | 4.3.0 |  
System.Security.Cryptography.Algorithms | 4.3.0 |  
System.Security.Principal | 4.3.0 |  
System.Threading.Tasks.Parallel | 4.3.0 |  
System.Threading.ThreadPool | 4.3.0 |  
System.Threading.Thread | 4.3.0 |  
System.ValueTuple | 4.4.0 |  
XliffTasks | 0.2.0-beta-000081 | 0.2.0-beta-000048

**Comment by brettfo** [comment]
Updated table from [SourceBuildPrebuildReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23) as of 5/31/2019:

| PackageName | PackageVersion | SourceBuiltVersion | Category |
|:--:|:--:|:--:|:--:|
| System.Runtime.Loader | 4.3.0 | | 3 |
| System.Reflection.Metadata | 1.6.0 | | 3 |
| System.Collections.Immutable | 1.5.0 | | 3 |
| FSharp.Core | 4.5.2 | | Filed issue dotnet/fsharp#6912 |

**Comment by dseefeld** [comment]
All prebuilts removed.
