### ISSUE TITLE
Analyze prebuilts for roslyn

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#891]
The following prebuilt packages are included as dependencies in source-build by **roslyn**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Prebuilt Table Updated 2019-05-07~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.1.548 | 16.0.461 
Microsoft.Build.Tasks.Core | 15.1.548 | 16.0.461 
Microsoft.CSharp | 4.3.0 |  
Microsoft.CodeAnalysis.Analyzers | 2.6.2-beta2 |  
Microsoft.CodeQuality.Analyzers | 2.6.2-beta2 |  
Microsoft.DiaSymReader.Native | 1.7.0 |  
Microsoft.Net.Compilers.Toolset | 3.1.0-beta1-19164-01 | 3.1.0-beta2-19067-14 
Microsoft.NetCore.Analyzers | 2.6.2-beta2 |  
Microsoft.VisualStudio.Threading.Analyzers | 15.8.209 |  
Roslyn.Diagnostics.Analyzers | 2.6.2-beta2 |  
System.Collections.Immutable | 1.5.0 |  
System.Memory | 4.5.2 |  
System.Reflection.Metadata | 1.6.0 |  
System.Runtime.CompilerServices.Unsafe | 4.5.2 |  
System.Text.Encoding.CodePages | 4.5.1 |  
System.Threading.Tasks.Extensions | 4.5.2 |  

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.1.548 | 16.0.0-preview.385 | 3
Microsoft.Build.Tasks.Core | 15.1.548 | 16.0.0-preview.385 | 3
Microsoft.CSharp | 4.3.0 |  | 3
Microsoft.CodeAnalysis.Analyzers | 2.6.2-beta2 | | 2 
Microsoft.CodeQuality.Analyzers | 2.6.2-beta2 |  | 2
Microsoft.DiaSymReader.Native | 1.7.0 |  | 2
Microsoft.NETCore.Compilers | 2.9.0-beta7-63018-03 | 3.0.0-beta3-19067-14 | 1
Microsoft.NetCore.Analyzers | 2.6.2-beta2 |  | 2
Microsoft.VisualStudio.Threading.Analyzers | 15.8.168 | | 2 
Roslyn.Diagnostics.Analyzers | 2.6.2-beta2 |  | 2
System.Collections.Immutable | 1.5.0 |  | 3*
System.IO.Pipes.AccessControl | 4.3.0 |  | 3
System.Memory | 4.5.1 |  | 3
System.Reflection.Metadata | 1.6.0 | | 3 
System.Runtime.CompilerServices.Unsafe | 4.5.0 | | 4 
System.Text.Encoding.CodePages | 4.5.0 |  | 4
System.Threading.Tasks.Extensions | 4.5.0 |  | 2
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 | 5

**Comment by 333fred** [comment]
@dseefeld updated the table. Some notes:

* For things marked 2, by exclude we mean exclude from just sourcebuild, not exclude from the repo altogether.
* For many things marked 3, especially things like System.Collections.Immutable, it's only a ref assembly if the version of SCI in the SDK is equal or bigger. We do require 1.5.0 as a minimum for reference.
* For XliffTasks, the sourcebuild version needs to be updated.

For determining what we're using as just a reference assembly, I looked through our vbc/publish and csc/publish directories, and examined which of the above dlls were in there, and whether they were type forwards, ref assemblies, or full implementation assemblies. We only have CompilerServices and Text.Encoding.CodePages there, both of which are real implementations. Is there a better process or set of tools for determining this info?

**Comment by 333fred** [comment]
Also, `Microsoft.NETCore.Compilers`, Roslyn is currently on a newer version than sourcebuild, and we'll likely prefer to update sourcebuild if at all possible.

**Comment by dseefeld** [comment]
All prebuilts removed.
