### ISSUE TITLE
Analyze prebuilts for sdk

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#893]
The following prebuilt packages are included as dependencies in source-build by **sdk**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Prebuilt Table Updated 2019-05-07~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
NETStandard.Library.NETFramework | 2.0.1-servicing-26011-01 |  
System.Reflection.Metadata | 1.5.0 |  

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.4.8 | 16.0.0-preview.385 
Microsoft.Build.Utilities.Core | 15.4.8 | 16.0.0-preview.385 
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  
Microsoft.DotNet.SignTool | 1.0.0-beta.19073.5 |  
Microsoft.Extensions.DependencyModel | 2.1.0-preview2-26306-03 | 3.0.0-preview-27324-5 
NETStandard.Library.NETFramework | 2.0.1-servicing-26011-01 |  
System.Reflection.Metadata | 1.5.0 |  
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 
sn | 1.0.0 |  
vswhere | 2.5.2 |

**Comment by nguerrera** [comment]
### (3) Reference only
Microsoft.Build.Framework | 15.4.8 | 16.0.0-preview.385 |  
Microsoft.Build.Utilities.Core | 15.4.8 | 16.0.0-preview.385 |
NETStandard.Library.NETFramework | 2.0.1-servicing-26011-01 |


### (2) Not needed by source build., already removed by arcade
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |   |  
Microsoft.DotNet.SignTool | 1.0.0-beta.19073.5 |
sn | 1.0.0 |   |  


### (4) should be source-built
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 |
Microsoft.Extensions.DependencyModel | 2.1.0-preview2-26306-03 | 3.0.0-preview-27324-5
System.Reflection.Metadata | 1.5.0

The latter two ship implementation assemblies in the net46 folder which is used by VS Code on Linux and therefore cannot be removed from source build even though `dotnet build` will not use them. We used to exclude this folder and a lot of Red Hat users complained.

**Comment by nguerrera** [comment]
> NETStandard.Library.NETFramework | 2.0.1-servicing-26011-01 |

This isn't actually reference only. The version here is used for running tests so could not be pulled down at all during source build, bcli or core-sdk ship it in the product but they are not be reported as the true source of of the prebuilt.

**Comment by dseefeld** [comment]
All prebuilts removed.
