### ISSUE TITLE
Analyze prebuilts for standard

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#894]
The following prebuilt packages are included as dependencies in source-build by **standard**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## Prebuilt Table Updated 2019-05-07

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.DotNet.ApiCompat | 1.0.0-beta.19207.1 |  | Will turn off for source-build
Microsoft.DotNet.GenAPI | 1.0.0-beta.19207.1 |  | Will turn off for source-build

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  | not-critical, fixed with dotnet/arcade@2ddb2b5
Microsoft.DotNet.Build.Tasks.Feed | 3.0.0-preview1-03617-02 | |  not-critical, fixed with dotnet/arcade@2ddb2b5
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |  | not-critical, fixed with dotnet/arcade@2ddb2b5
Microsoft.NETCore.Compilers | 2.9.0 | 3.0.0-beta3-19067-14 | should be built from dotnet/roslyn
sn | 1.0.0 |  | not-critical, fixed with dotnet/arcade@2ddb2b5
vswhere | 2.5.2 | | not-critical, fixed with dotnet/arcade@2ddb2b5

**Comment by ericstj** [comment]
@dseefeld I took a look at all of these and added some comments.  I think most should be fixed with the latest arcade build.  I've also made a PR to standard to fix a few that aren't in this list (likely because data is stale).
https://github.com/dotnet/standard/pull/1109

**Comment by dseefeld** [comment]
All prebuilts removed.
