### ISSUE TITLE
Analyze prebuilts for vstest

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#896]
The following prebuilt packages are included as dependencies in source-build by **vstest**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## Additional prebuilt from @adaggarwal 2019-06-20

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Newtonsoft.Json | 9.0.1 | 12.0.2 | Use Source-build version

## ~~Prebuilt Table Updated 2019-05-31~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.1.548 | 16.0.461 
Microsoft.Build.Utilities.Core | 15.1.548 | 16.0.461 
Microsoft.Extensions.DependencyModel | 1.0.3 | 3.0.0-preview4-27615-11 
Microsoft.Internal.Dia.Interop | 14.0.0 |  
Microsoft.TargetingPack.NETFramework.v4.6 | 1.0.1 |  
StyleCop.Analyzers | 1.0.1 |  
System.Xml.XPath.XmlDocument | 4.0.1 |  

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.1.548 | 16.0.0-preview.385 
Microsoft.Build.Utilities.Core | 15.1.548 | 16.0.0-preview.385 
Microsoft.Extensions.DependencyModel | 1.0.3 | 3.0.0-preview-27503-5 
Microsoft.Internal.Dia.Interop | 14.0.0 |  
Microsoft.Internal.Dia | 14.0.0 |  
Microsoft.Internal.Intellitrace | 15.8.0-preview-20180702-05 |  
Microsoft.Internal.TestPlatform.Extensions | 15.8.0-preview-1831095 |  
Microsoft.TargetingPack.NETFramework.v4.6 | 1.0.1 |  
Microsoft.VSSDK.BuildTools | 15.0.26201 |  
Microsoft.VisualStudio.CUIT | 15.8.0-preview-1831095 |  
Microsoft.VisualStudio.QualityTools.DataCollectors | 15.8.0-preview-1831095 |  
Microsoft.VisualStudio.QualityTools | 15.8.0-preview-1831095 |  
Microsoft.VisualStudio.Sdk.BuildTasks.14.0 | 14.0.12-pre |  
Microsoft.VisualStudio.Telemetry | 15.6.815-master284DF69C |  
NuGet.CommandLine | 3.4.3 |  
Pdb2Pdb | 1.1.0-beta1-62316-01 |  
StyleCop.Analyzers | 1.0.1 |  
System.Xml.XPath.XmlDocument | 4.0.1 |  
fmdev.xlftool | 0.1.3 |  
vswhere | 2.0.2 |

**Comment by mayankbansal018** [comment]
@dseefeld We tried building [`TestPlatform_BuildFromSource`](https://github.com/Microsoft/vstest/blob/master/TestPlatform_BuildFromSource.sln) via `dotnet build TestPlatform_BuildFromSource.sln -p:DotNetBuildFromSource=true`, & we did not find any dependencies apart from those of system, or runtime.

Attached list of packages that actually got restored.
[packages.txt](https://github.com/dotnet/source-build/files/3062373/packages.txt)

**Comment by dseefeld** [comment]
> @dseefeld We tried building [`TestPlatform_BuildFromSource`](https://github.com/Microsoft/vstest/blob/master/TestPlatform_BuildFromSource.sln) via `dotnet build TestPlatform_BuildFromSource.sln -p:DotNetBuildFromSource=true`, & we did not find any dependencies apart from those of system, or runtime.
> 
> Attached list of packages that actually got restored.
> [packages.txt](https://github.com/dotnet/source-build/files/3062373/packages.txt)

Right.  The list above contains the restored packages that show up in source-build for vstest that aren't being built from source.  These are direct dependencies only.  There are a bunch of transitive dependencies as well, but we're not tackling those right now.  What we'd like is a response from you in the table above regarding how each of these should be handled.  I've included some possible responses above.  Thanks.

**Comment by singhsarab** [comment]
@dseefeld How are we restoring these packages ? Are we running the build script in the repo?

 Like Mayank mentioned, vstest repo should be built using
 ``` dotnet build TestPlatform_BuildFromSource.sln -p:DotNetBuildFromSource=true ```

And when we do that we don't see any of these dependencies that you mentioned above.

**Comment by dseefeld** [comment]
@singhsarab Here's the command that we're using to build vstest in source-build:
`/src/src/vstest/build.sh -DotNetBuildFromSource -DotNetCoreSdkDir /src/Tools/dotnetcli/ -c Release -r centos.7-x64 -v 15.9.0 -vs preview-20180807-05`

Building with the command that you mentioned above doesn't produce any nupkgs.  Should it?

**Comment by singhsarab** [comment]
@dseefeld Thanks for pointing that out. We'd need to fix this script then. The command that I gave you can be used only for building the projects, it does not create all the packages. Creation of  nuget packages happens via the script you pointed out.

@mayankbansal018 Can you please take a look.

**Comment by mayankbansal018** [comment]
>Building with the command that you mentioned above doesn't produce any nupkgs. Should it?

@dseefeld  No this will not create any nuget package.

Can you please specify if you need **nuget packages** while running dotnet build from source command. If you do need nugets then we will need to fix our build.sh script to generate those, if the packages are not needed, then we suggest you use the command specified by Sarab earlier.

>dotnet build TestPlatform_BuildFromSource.sln -p:DotNetBuildFromSource=true

**Comment by dseefeld** [comment]
@mayankbansal018 Yes.  We need the build to produce nuget packages.  We currently build Microsoft.TestPlatform.Build and Microsoft.TestPlatform.CLI

**Comment by singhsarab** [comment]
@dseefeld I have merged the PR.

**Comment by dseefeld** [comment]
All prebuilts removed.
