### ISSUE TITLE
Analyze prebuilts for websdk

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#897]
The following prebuilt packages are included as dependencies in source-build by **websdk**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Prebuilt Table Updated 2019-06-24~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.AspNetCore.Mvc.Analyzers | 3.0.0-preview6.19307.2 |  | Dependent on aspnetcore |
Microsoft.AspNetCore.Mvc.Api.Analyzers | 3.0.0-preview6.19307.2 | | Dependent on aspnetcore |
Microsoft.Build.Framework | 15.1.1012 | 16.2.0-dev-19278-01 |  Ref-only |
Microsoft.Build.Utilities.Core | 15.1.1012 | 16.2.0-dev-19278-01 | Ref-only |
Microsoft.Web.Xdt | 3.0.0 |  | Add repo to source-build |
Newtonsoft.Json | 10.0.3 | 12.0.2 
System.Security.Cryptography.ProtectedData | 4.3.0 |  | Ref-only |
System.Xml.XmlDocument | 4.3.0 |  | Ref-only |

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.1.1012 | 16.0.0-preview.385 
Microsoft.Build.Utilities.Core | 15.1.1012 | 16.0.0-preview.385 
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |  
Microsoft.Web.Xdt | 3.0.0 |  
System.Collections.Specialized | 4.3.0 |  
System.Security.Cryptography.ProtectedData | 4.3.0 |  
System.Xml.XmlDocument | 4.3.0 |  
sn | 1.0.0 |  
vswhere | 2.5.2 |

**Comment by vijayrkn** [comment]
@dseefeld - The above dependencies list was generated before the arcade. Can we re-run this to see what are the pending source build dependencies?

**Comment by vijayrkn** [comment]
@dseefeld - The xdt dependency to websdk should be fixed now 

https://github.com/aspnet/websdk/blob/b603b295fd0d97bed95faea40ce564147baa68f7/eng/Version.Details.xml#L12

**Comment by vijayrkn** [comment]
Package | Version | Status
-- | -- | --
Microsoft.Build.Framework | 15.1.1012 | Reference Only
Microsoft.Build.Utilities.Core | 15.1.1012 | Reference Only
Microsoft.Web.Xdt | 3.0.0 | https://github.com/aspnet/websdk/issues/664
Microsoft.AspNetCore.Mvc.Analyzers | 3.0.0-preview4-19216-03 | https://github.com/aspnet/websdk/issues/665
Microsoft.AspNetCore.Mvc.Api.Analyzers | 3.0.0-preview4-19216-03 | https://github.com/aspnet/websdk/issues/666
System.Security.Cryptography.ProtectedData | 4.3.0 | Reference Only
System.Xml.XmlDocument | 4.3.0 | Reference Only

**Comment by dseefeld** [comment]
All prebuilts removed.
