### ISSUE TITLE
Analyze prebuilts for application-insights

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#900]
The following prebuilt packages are included as dependencies in source-build by **application-insights**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
System.Diagnostics.DiagnosticSource | 4.4.0 | | reference only
System.Diagnostics.StackTrace | 4.3.0 | | reference only
System.Net.Requests | 4.0.11 | | reference only
System.Runtime.Serialization.Primitives | 4.1.1 | | reference only

**Comment by SergeyKanzhelev** [comment]
@dseefeld can you please elaborate on what's required from me to address this issue? All listed dependencies are used by Application Insights.

**Comment by dseefeld** [comment]
@SergeyKanzhelev I think yours will all be "reference only".  I set them all to that for now.  Hopefully they will go away when we get a solution for refererence only packages.  You shouldn't have to take any more action now.

**Comment by SergeyKanzhelev** [comment]
please ping me when any actions will be needed here.

**Comment by dseefeld** [comment]
All direct dependency prebuilts have been removed.
