### ISSUE TITLE
How to build corefx's System.Data.SqlClient 

### ISSUE THREAD

**Issue by crntn** [dotnet/source-build#902]
Hi !

I have been trying to get a custom build of System.Data.SqlClient from corefx but I have not been successful so far.

When I build directly from the dotnet/corefx repository I get stuck at 
`C:\projects\corefx\Tools\depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [C:\projects\corefx\external\runtime\runtime.depproj]
Build FAILED.
C:\projects\corefx\Tools\depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [C:\projects\corefx\external\runtime\runtime.depproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:02:10.39
`

Since I was able to use dotnet/source-build to build  the runtime I figured I could get the nuget generated with `build.sh /p:RootRepo=core-setup` but it does not seem to generate the nupkg of System.Data.SqlClient

Is it the expected behavior ? I'm curious if you guys would have any pointers on how to build this package ?

Thanks a lot !

**Comment by dagood** [comment]
Yes, unfortunately source-build isn't set up to build CoreFX `System.*` packages yet. 🙁 Tracked by https://github.com/dotnet/source-build/issues/210.

It looks like that issue has been encountered a few times: https://github.com/dotnet/corefx/issues?utf8=✓&q=is%3Aissue+Error+no+assets+were+resolved+from+NuGet. Not sure if the scenarios there look similar to what you're doing.

I'd recommend trying to clone/build CoreFX by itself, following CoreFX repo instructions and getting help there. When you only want to make changes in single repo (or just build the packages of a single repo), that's your best bet to get help when things go wrong.
