### ISSUE TITLE
Enable prebuilt baseline failures on Windows CI

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#907]
In https://github.com/dotnet/source-build/issues/898, Windows CI was enabled in 2.1, but it ignores prebuilt baseline failures. It makes sense that Windows is different enough that it pulls in different prebuilts.

I'm not aware of any scenario where prebuilts for the Windows build matter, but filing this to track.

(Prebuilt baseline failure might happen to detect when we use a prebuilt package rather than a source-built package, but cache conflict detection catches this situation in a much more targeted way. It would have a lot more value to fix what it detects regularly (even baseline it?) and change that into an error.)

**Comment by crummel** [comment]
See #1134.
