### ISSUE TITLE
Build ASP.NET Core cli tool packages from source to include in source-built SDK

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#927]
This issue tracks investigating whether `dotnet-dev-certs` and similar ASP.NET Core tool packages can be included in source-build. If they can be, the tools can be included in the SDK and our product will be more similar to the Microsoft-built SDK.

Specifically, users wouldn't hit the "cannot find command" experience where they need to run `dotnet install --global ...`. See https://github.com/dotnet/source-build/issues/926 for an example of how this experience can require non-obvious workarounds.

**Comment by natemcmaster** [comment]
I would not expect this to be difficult for some tools, but doing it for all of them will be difficult. Here is my estimate, ordered from least difficult to most.

* dotnet-dev-certs
* dotnet-watch
* dotnet-user-secrets
* dotnet-sql-cache
* dotnet-ef

**Comment by MichaelSimons** [comment]
Closing as a duplicate of https://github.com/dotnet/source-build/issues/428
