### ISSUE TITLE
Excessive warnings in CoreFX build: RestoreSources.props imported multiple times

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#940]
This warning shows up many, many times (~1700) in the `master` CoreFX source-build:

> /work/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props(79,3): warning MSB4011: "/work/bin/obj/x64/Release/RestoreSources.props" cannot be imported again. It was already imported at "/work/Tools/RepoAPI.Mapping.props (29,3)". This is most likely a build authoring error. This subsequent import will be ignored.

Both BuildTools and Arcade detect `DotNetRestoreSourcePropsPath` and try to import it, causing this warning. The way forward is probably to remove it from BuildTools since Arcade is taking over. However it might not be that simple if other projects still depend on BuildTools for this functionality.

I think the "header guard" approach would also work: set some property inside the props file that disables the other import. It would be better to fix the root cause, though.

**Comment by crummel** [comment]
@crummel to check if this is still an issue

**Comment by crummel** [comment]
This should go away with BuildTools.
