### ISSUE TITLE
source-built prebuilts and reference-assemblies conflict causing "package cache" warning in tarball build

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#952]
Microsoft.NETCore.Platforms and Microsoft.NETCore.Targets are used by coreclr when building with stable versions.  These are built by corefx after coreclr uses them.  Plus, they are both text-only  packages, so they get included in the reference-assemblies packages that get built with the tarball.  The issue is that the version included in the ref-assy package and the source-built package are different, even though the contents are the same.  This results in the ref-assy package getting loaded first, which causes the conflicting packages warning: 
```
warning : Detected packages in the cache that should be source-built, but contents don't match. See /src/source-build/bin/conflict-report/before-cli-migrate/ for usage details:
warning : Microsoft.NETCore.Platforms/2.1.2 : Nupkg found at '/src/source-build/reference-packages/packages/Microsoft.NETCore.Platforms.2.1.2.nupkg'
warning : Microsoft.NETCore.Targets/2.1.0 : Nupkg found at '/src/source-build/reference-packages/packages/Microsoft.NETCore.Targets.2.1.0.nupkg'
```

This warning causes no functional issue, though, because the package contents are the same.

**Comment by omajid** [comment]
Does this mean if we were to patch corefx to include additional runtimes in the runtime graph, the updated runtimes wouldn't be included in the final built SDK? Or will this only affect the coreclr build?

**Comment by dseefeld** [comment]
@omajid This issue doesn't change that behavior.  Either way, Microsoft.NETCore.Platforms and Microsoft.NETCore.Targets are included as prebuilts in the tarball (either source-built prebuilts or reference-only package prebuilt) and the prebuilt one is the one that gets used.  To impact these would take a multi-stage build, requiring a build through corefx first and then replacing the prebuilts and rebuilding.  In that case this issue would surface and the reference-only package would need to be removed.

**Comment by omajid** [comment]
Got it. Thanks for clarifying!

**Comment by crummel** [comment]
@dseefeld to investigate if this is still an issue

**Comment by dseefeld** [comment]
Closing.  There's no action to take here.
