### ISSUE TITLE
Vstest depends on Desktop assemblies to build localized bits

### ISSUE THREAD

**Issue by karajas** [dotnet/source-build#96]
https://github.com/dotnet/sdk/issues/335

The TestHost folder is missing from the output. It has the different localized bits of the Microsoft.TestPlatform.CLI assemblies that are produced in the Microsoft/vstest repo.

**Comment by omajid** [comment]
@dleeapho Hey, did we ever confirm whether TestHost bits are meant to be included or not?

**Comment by karajas** [comment]
@nguerrera Thoughts?

**Comment by nguerrera** [comment]
As I indicated on the offline thread, vstest folks need to answer this. @codito, @sbaid I cannot.

**Comment by karajas** [comment]
Thanks! wasn't sure who to tag.

**Comment by omajid** [comment]
@dleeapho mentioned Testhost should not be part of SDK.

**Comment by dleeapho** [comment]
Related to #125

**Comment by crummel** [comment]
Verified that TestHost and associated resource DLLs are still making it into the final product and we appear to still be grabbing net451 packages to make this happen, although none of those make it into the final output themselves.  Taking myself off this assignment for now since I'm FR the next two weeks.

**Comment by crummel** [comment]
Removed triaged to bring this back up from https://github.com/dotnet/source-build/issues/708: the official SDK is including the TestHost - should we be or are they incorrect in doing so?  We also in general know how to deal with required full-framework assemblies now (add the TargetingPack in their build).

**Comment by codito** [comment]
looping in vstest folks @mayankbansal018 @smadala @cltshivash

**Comment by MichaelSimons** [comment]
[Triage] Closing this issue in favor of tracking with https://github.com/dotnet/source-build/issues/3014
