### ISSUE TITLE
Add static commit hashes to Version.Details.xml for repos that are not participating in arcade

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#965]
Current list of repos source-build uses but are not in the core-sdk manifest (notes from Matt):
application-insights
arcade
cli-migrate – This should be in the graph soon, if it isn’t already
common
fsharp
nuget-client – I think this should be in the graph now
roslyn-tools (this will go away after everyone is on Arcade)
standard – this is an officially shipped version currently
vstest
xliff-tasks

**Comment by crummel** [comment]
This is an intermediate step while we work to get all repos into the core-sdk graph to allow arcade to uber-clone properly.  These will then be removed from Versions.Details.xml again.

**Comment by dseefeld** [comment]
Done.
