### ISSUE TITLE
Receive only coherent build from BAR for source-build updates

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#968]
What we need from arcade: an option in Maestro++ to only create an update PR if a core-sdk build is coherent.

Nice to have: an indicator of coherence in build info.

**Comment by crummel** [comment]
Depends on https://github.com/dotnet/arcade/issues/1923 and https://github.com/dotnet/arcade-services/pull/128.

**Comment by mmitche** [comment]
@crummel This likely means that you'll only get a PR like...on the last build, and never before.

There is a coherency note in the darc dependency information (get-dependency-graph) today.

**Comment by dseefeld** [comment]
Done.  Waiting for updates from DARC.
