### ISSUE TITLE
Work with repo owners to keep static Version.Details.xml up to date and get automated hash updates into BAR

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#969]
After #965, we will want to keep the Version.Details.xml up to date until the missing submodules can be added to the core-sdk dependency graph.  We also want all represented repos to be in the dependency graph - this will require working with the repo owners.

**Comment by crummel** [comment]
Related issues: https://github.com/dotnet/toolset/issues/1256, https://github.com/microsoft/vstest/issues/2063, https://github.com/dotnet/arcade/issues/3099.

**Comment by crummel** [comment]
Remaining issue is XDT flow to websdk, related issue https://github.com/dotnet/arcade/issues/3518.

**Comment by dleeapho** [comment]
Done now except for XDT issue above.
