### ISSUE TITLE
Analyze prebuilts for core-sdk

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#972]
The following prebuilt packages are included as dependencies in source-build by **core-sdk**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Prebuilt Table Updated 2019-05-07~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Utilities.Core | 15.6.82 | 16.0.461 
Microsoft.Build | 15.6.82 | 16.0.461 

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Utilities.Core | 15.7.177 | 16.0.0-preview.385 
Microsoft.Build | 15.7.177 | 16.0.0-preview.385 
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  
Microsoft.DotNet.PlatformAbstractions | 2.0.0 | 3.0.0-preview-27324-5 
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |  
NuGet.Versioning | 4.3.0 | 5.0.0-preview1.5754 
System.Reflection.Metadata | 1.4.2 |  
WindowsAzure.Storage | 8.4.0 |  
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 
sn | 1.0.0 |  
vswhere | 2.5.2 |

**Comment by nguerrera** [comment]
### (3) reference only
Microsoft.Build.Utilities.Core | 15.7.177 | 16.0.0-preview.385 |  
Microsoft.Build | 15.7.177 | 16.0.0-preview.385
Microsoft.DotNet.PlatformAbstractions | 2.0.0 | 3.0.0-preview-27324-5
System.Reflection.Metadata | 1.4.2
NuGet.Versioning

### (2) not needed for source build, already fixed by arcade
sn | 1.0.0 |   |  
vswhere | 2.5.2
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |   |  
Microsoft.DotNet.SignTool

### (1) should be source built
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048

### (2) not needed for source build
WindowsAzure.Storage | 8.4.0

**Comment by dseefeld** [comment]
@nguerrera Is there a core-sdk issue to eliminate WindowsAzure.Storage for source-build and to use the source-built version of XliffTasks?

**Comment by nguerrera** [comment]
@dseefeld I closed the issues when everything was categorized. What is the expectation for closing these "Analyze" issues?

I'll take a look at eliminating WindowsAzure.Storage.

For xliff-tasks, this effects multiple repos. The version is chosen by arcade, the issue should be tracked on arcade if source build can't override that version: https://github.com/dotnet/arcade/blob/002cce7e8e3e043c50acae673741ee3962411e10/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L90

Is the problem that arcade is not using the (PackageName)PackageVersion property names. cc @tmat

**Comment by dseefeld** [comment]
@nguerrera Thanks.  The issues should remain open as long as there's work being done to eliminate these prebuilts.  So, in the example of WindowsAzure.Storage, I would expect that if there is an issue in core-sdk to fix this, it would be linked here and this would be left open.

**Comment by nguerrera** [comment]
@dseefeld The issue title and description do not make this clear, FWIW. It reads as a task to categorize everything.

Anyhow, I sent https://github.com/dotnet/core-sdk/pull/1133 to fix the WindowsAzure.Storage. I will start going through the other closed issues and reopen appropriately with linked issues or PRs.

**Comment by dseefeld** [comment]
All prebuilts removed.
