### ISSUE TITLE
Analyze prebuilts for clicommandlineparser

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#976]
The following prebuilt packages are included as dependencies in source-build by **clicommandlineparser**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  | (2) not needed in source build, and pulled in by arcade
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |   | (2) not needed in source build, and pulled in by arcade
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 | (4)  should be source built version, pulled in by arcade
sn | 1.0.0 |   | (2) not needed in source build, and pulled in by arcade
vswhere | 2.2.7 |   | (2) not needed in source build, and pulled in by arcade

**Comment by nguerrera** [comment]
XliffTasks is in category (4), it should be source-built version. It is pulled in by arcade.

The reset are in category (2) and a recent fix to arcade should remove them.
